CSHARP-4449: Implement Find projections in LINQ3.
mongodb/mongo-csharp-driver pull request #1000
Opened 2022-12-22 16:12 UTC by rstam

2022-12-22 16:16 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            return TranslateExpressionToProjection(expression, sourceSerializer, serializerRegistry, translationOptions: null);
Now that the server supports the full aggregation language in `Find` projections we can simply translate a `Find` projection the same way as a `$project` stage projection.

Note: this only works on server version 4.4 and higher. Users on older server versions can still use `Find` projections, with the limitation that they can't project computed fields (`Find` projections prior to server 4.4 are limited to including/excluding fields).

2022-12-22 16:16 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +                "{ \"_v\" : { \"$concat\" : [\"$FirstName\", \" \", \"$LastName\"] }, \"_id\" : 0 }";
LINQ2 and LINQ3 translate this differently.

LINQ2 handles the computation client side. LINQ3 handles the computation server side (as it should be).

2023-01-06 01:44 UTC, JamesKovacs requested changes
Based on your comments, we need to skip the LINQ3 tests on MongoDB 4.2 and earlier.

2023-01-06 01:44 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +                "{ \"_v\" : { \"$concat\" : [\"$FirstName\", \" \", \"$LastName\"] }, \"_id\" : 0 }";
Won't this test fail with LINQ3 on MongoDB 4.2 and earlier? Do we need a `RequireServer` guard clause?

2023-01-06 01:44 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +            var subject = CreateSubject(linqProvider)
Same issue here. I think we need `RequireServer` guard clause to prevent LINQ3 version from running on MongoDB 4.2 and earlier.

2023-01-07 02:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +                "{ \"_v\" : { \"$concat\" : [\"$FirstName\", \" \", \"$LastName\"] }, \"_id\" : 0 }";
Done

2023-01-07 02:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +            var subject = CreateSubject(linqProvider)
Done

2023-01-11 02:44 UTC, JamesKovacs approved these changes
LGTM

2023-01-12 14:55 UTC, merged