CSHARP-4420: EG tests for Atlas Search
mongodb/mongo-csharp-driver pull request #1001
Opened 2022-12-22 18:33 UTC by BorisDog

This PR is rebased on top of [CSHARP-4440](https://github.com/mongodb/mongo-csharp-driver/pull/989).
The main focus here is AtlasSearchTest.cs

2023-01-06 12:01 UTC, DmitryLukyanov commented on evergreen/run-atlas-search-test.sh
> +set -o errexit  # Exit the script with error if any of the commands fail
add a section like in most of other files about output variables: https://github.com/mongodb/mongo-csharp-driver/blob/master/evergreen/run-csfle-azure-tests.sh#L11

2023-01-06 12:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Search/Highlight.cs
> +        public string Path { get; private set; }
why `private set` is here? Sounds like it does nothing?

2023-01-06 12:03 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +        protected override void DisposeInternal() =>
nit: I think all content suites in one line like: 
` protected override void DisposeInternal() => _disposableMongoClient.Dispose();`

2023-01-06 12:06 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            GetTestCollection().Aggregate().Search(searchDefintion)
this should be at least:

     GetTestCollection().Aggregate().Search(searchDefintion)
        .Limit(1)
        .ToList()
        .Single();

but I would recommend a better formatting:

     GetTestCollection()
        .Aggregate()
        .Search(searchDefintion)
        .Limit(1)
        .ToList()
        .Single();

2023-01-06 12:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Search/Highlight.cs
> +        public string Path { get; private set; }
sounds like it's for deserialization only. Does it deserve a comment?

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +        private static readonly GeoJsonPolygon<GeoJson2DGeographicCoordinates> __testPolygon =
Done.

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            new(new(new(new GeoJson2DGeographicCoordinates[]
This is a long chain of classes creation with long names shortened to omit the names for readability.
So for example in creation of `GeoWithinBox`, the only important and visible data is its 2 corners.

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +        protected override void DisposeInternal() =>
Done.

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +        public void Autocomplete()
I am not big fun of having same prefix for all test methods, especially when it does not add any information. Can you think of other alternatives here?

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            var result = SearchSingle(Builders.Search.Compound()
Done.

2023-01-06 23:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            GetTestCollection().Aggregate().Search(searchDefintion)
Done.

2023-01-06 23:29 UTC, BorisDog commented on evergreen/run-atlas-search-test.sh
> +powershell.exe .\\build.ps1 --target TestAtlasSearch
Choice for Windows platform is arbitrary, but we don't plan to extend to other OS.

2023-01-06 23:29 UTC, BorisDog commented on evergreen/run-atlas-search-test.sh
> +set -o errexit  # Exit the script with error if any of the commands fail
Done.

2023-01-06 23:29 UTC, BorisDog commented on src/MongoDB.Driver/Search/Highlight.cs
> +﻿// Copyright 2010-present MongoDB Inc.
Good catch, I'll fix this in the main search PR too.

2023-01-06 23:29 UTC, BorisDog commented on src/MongoDB.Driver/Search/Highlight.cs
> +        public string Path { get; private set; }
Yeah it's for deserialization. Looks pretty minor for a comment.

2023-01-09 14:54 UTC, DmitryLukyanov reviewed
some mostly minor comments

2023-01-09 14:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Search/Highlight.cs
> +﻿// Copyright 2010-present MongoDB Inc.
for the future :( I would suggest using a different PR approach (we already did similar work in past) since it's hard to follow what was fixed and what should be reviewed. Sounds like at least in this file the above suggestion was applied..

2023-01-09 14:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            _disposableMongoClient = new(new MongoClient(atlasSearchUri), CreateLogger<DisposableMongoClient>());
I would suggest creating a new CreateDisposableClient(connectionString) method to DriverTestConfiguration to be able creating a test client in the same way across driver tests

2023-01-09 23:33 UTC, BorisDog commented on evergreen/run-atlas-search-test.sh
> +powershell.exe .\\build.ps1 --target TestAtlasSearch
I think it's fine for now, just copied from `run-atlas-data-lake-test` and `run-atlas-connectivity-tests`

2023-01-09 23:33 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            _disposableMongoClient = new(new MongoClient(atlasSearchUri), CreateLogger<DisposableMongoClient>());
I would suggest doing this in different small refactoring PR, to change all other places too.

2023-01-09 23:35 UTC, DmitryLukyanov approved these changes
LGTM

2023-01-17 17:39 UTC, rstam requested changes
Minor changes requested. Overall looks good.

I think this needs to be reviewed again (in a new clean PR) once you have rebased this on the csharp4440 work.

2023-01-17 17:39 UTC, rstam commented on src/MongoDB.Driver/Search/Highlight.cs
> +    public sealed class Highlight
Why is this new file in this PR? Shouldn't all work that is not testing related be in the CSHARP-4440 PR?

In any case, I'm not reviewing this file in this PR because it's not testing related.

This whole folder is wildly out of date with CSHRP-4440.

2023-01-17 17:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +    public class AtlasSearchTest : LoggableTestClass
nit: rename file and class to `AtlasSearchTests` (plural)

2023-01-17 17:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTest.cs
> +            new(new(new(new GeoJson2DGeographicCoordinates[]
> omit the names for readability

LOL. 

I found it much *harder* to read because there is no way to know what each call to `new` is doing without going into Visual Studio and hovering the mouse over each `new` to see what it does.

I agree with Dima. This looks like an abuse of a new C# feature.

2023-01-17 17:46 UTC, DmitryLukyanov commented on evergreen/run-atlas-search-test.sh
> +powershell.exe .\\build.ps1 --target TestAtlasSearch
it's mandatory only on non windows OSs if I recall correctly

2023-01-17 18:04 UTC, rstam commented on evergreen/run-atlas-search-test.sh
> +powershell.exe .\\build.ps1 --target TestAtlasSearch
At one point it was mandatory on my Windows machine also, so I got used to using the `=` form.

My guess is that at some point a Cake release made it mandatory, and they got lots of complaints, and then they reverted the change.

I'm assuming it's Cake that parses this argument(s) and not Powershell.

2023-01-19 16:20 UTC, closed without merging