CSHARP-4453: Support Bucket and BucketAuto stages in LINQ3.
mongodb/mongo-csharp-driver pull request #1005
Opened 2022-12-30 00:03 UTC by rstam

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/AggregateBucketAutoResultIdSerializer.cs
> +    public class AggregateBucketAutoResultIdSerializer<TValue> : ClassSerializerBase<AggregateBucketAutoResultId<TValue>>, IBsonDocumentSerializer
I'm wondering now as I write these comments whether we could have just let this be class mapped?

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +                var (bucketStage, projectStage) = PipelineStageDefinitionBuilder.BucketForLinq3(groupBy, boundaries, output, options);
Similar to what we had to do for `GroupForLinq3`.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +            Expression<Func<IGrouping<TValue, TResult>, TNewResult>> output, // the IGrouping has been wrong all along, only fixing it for LINQ3
LINQ2 depends on this being declared this way, even thought it is wrong.

I imagine it would be hard to fix LINQ2, and I have no idea how to even begin.

Better to just fix it in LINQ3.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstGroupingPipelineOptimizer.cs
> +                if (IsGroupingStage(stage))
The gist of the changes in this PR are that there are 3 kinds of "grouping" stages:

1. Group
2. Bucket
3. BucketAuto

Any names using "grouping" refer to any of the 3. If a name uses just "group" it refers to the first.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupExpressionStageDefinitions.cs
> -    internal sealed class GroupExpressionStageDefinitions<TInput, TKey, TOutput>
This class has been replaced by the new `GroupingAndProjectStageDefinitions` class.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupExpressionStageDefinitions.cs
> -                var expression = CreateExpression(inputSerializer);
I found a simpler way to get the `AstPipelineOptimizer` to do its thing without having to create an `Expression` (not to mention that there is no possible `Expression` for `Bucket` or `BucketAuto` because LINQ doesn't have those).

See the `RenderGroupingStage` method in `GroupingAndProjectStageDefinitions.cs`.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupExpressionStageDefinitions.cs
> -            private class PseudoQueryProvider : IMongoQueryProvider
A nice side effect of the new way of invoking the `AstPipelineOptimizer` is that we no longer need a `PseudoQueryProvider` or a `PseudoSource`.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingAndProjectStageDefinitions.cs
> +    internal static class GroupingAndProjectStageDefinitions
These are static factory methods. Static factory methods are nice because they can infer type parameters (constructor calls can't).

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingAndProjectStageDefinitions.cs
> +    public sealed class GroupingAndProjectStageDefinitions<TInput, TGrouping, TOutput>
`TGrouping` is a type parameter because `BucketAuto` has a different `IGrouping` than the other 2.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingAndProjectStageDefinitions.cs
> +        public override RenderedPipelineStageDefinition<TGrouping> Render(IBsonSerializer<TInput> inputSerializer, IBsonSerializerRegistry serializerRegistry, LinqProvider linqProvider)
When asked to `Render` the grouping stage we also render the project stage and we run the pair through the `AstPipelineOptimizer` so that accumulators can be moved from the project stage to the grouping stage.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingAndProjectStageDefinitions.cs
> +    internal abstract class GroupingStageDefinition<TInput, TGrouping, TOutput> : PipelineStageDefinition<TInput, TGrouping>
There are 3 subclasses for each of the grouping stages:

1. `BucketStageDefinition`
2. `BucketAutoStageDefinition`
3. `GroupStageDefinition`

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/IGroupingSerializer.cs
> +            return new IGroupingSerializer<TKey, TElement>(keySerializer, elementSerializer);
If the type parameters can be inferred we don't need to use reflection.

2022-12-30 00:25 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +        public static GroupingAndProjectStageDefinitions<TInput, IGrouping<TValue, TInput>, TOutput> GroupForLinq3<TInput, TValue, TOutput>(
`GroupingAndProjectStageDefinitions` replaces `GroupForLinq3Result`.

This could be considered a breaking change, but LINQ3 has not been the default up to now so maybe it's OK? Let's discuss.

We could choose to keep the `GroupForLinq3Result` return type and just do a conversion to it.

2022-12-30 00:25 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentBucketAutoTests.cs
> +                    g => new { _id = default(AggregateBucketAutoResultId<int?>), Years = g.Select(e => e.Year), Count = g.Count() });
Notice the odd way `_id` is used here.

It is only present to add the `_id` property to the anonymous class. LINQ2 actually removes the `_id` from the translation!

2022-12-30 00:25 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentBucketAutoTests.cs
> +                    e => (int?)e.Year,
The only reason we have to cast to `int?` is because the test data is missing the `Year` in one document. This could be considered an error in the test data, but at the same time this illustrates what you would have to do if a `struct` valued property might be missing in the database (not a problem with `class` because `null` is a valid value).

2022-12-30 00:25 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentBucketAutoTests.cs
> +                    g => new { Key = g.Key, Years = g.Select(e => e.Year), Count = g.Count() });
Notice the use of `Key = g.Key` instead of the `_id = default(AggregateBucketAutoResultId<int?>)` hack.

In LINQ3 the `IGrouping` is declared correctly and `g.Key` for `BucketAuto` is of type `AggregateBucketAutoResultId<TValue>`.

2023-01-13 17:26 UTC, JamesKovacs requested changes
Minor comments below. We had a larger discussion around `XyzForLinq3`. Robert is going to prototype an idea for possibly removing the need for `XyzForLinq3` methods. I'll review again after those changes.

2023-01-17 01:13 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstGroupingPipelineOptimizer.cs
> +                    _ => throw new Exception($"Unexpected groupintStage node type: {groupingStage.NodeType}.")
Done

2023-01-17 01:13 UTC, rstam commented on src/MongoDB.Driver/AggregateBucketAutoResultIdSerializer.cs
> +﻿/* Copyright 2016-present MongoDB Inc.
Done

2023-01-25 01:49 UTC, JamesKovacs requested changes
Very nice refactoring! Minor feedback on some comments. Otherwise LGTM.

2023-01-25 01:49 UTC, JamesKovacs commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +        /// Appends a $bucketAuto stage to the pipeline (this method can only be used with LINQ3).
This is an overload, not just a method.

2023-01-25 01:49 UTC, JamesKovacs commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +        /// Appends a $bucketAuto stage to the pipeline (this overload can only be used with LINQ2).
This is a new method, not an overload.

2023-01-25 21:32 UTC, rstam commented on src/MongoDB.Driver/AggregateBucketAutoResultIdSerializer.cs
> +    public class AggregateBucketAutoResultIdSerializer<TValue> : ClassSerializerBase<AggregateBucketAutoResultId<TValue>>, IBsonDocumentSerializer
I've thought about it some more, and the answer is no.

We have to be able to pass in the correct value serializer. If we just let it be automapped the value serializer would be looked up in the registry and that might or might not be the correct one.

2023-01-25 21:32 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +        /// Appends a $bucketAuto stage to the pipeline (this method can only be used with LINQ3).
Done

2023-01-25 21:32 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +        /// Appends a $bucketAuto stage to the pipeline (this overload can only be used with LINQ2).
Done

2023-01-25 23:30 UTC, JamesKovacs approved these changes
LGTM

2023-01-26 01:56 UTC, merged