CSHARP-4475: Add an AllowedTypes filter to ObjectSerializer.
mongodb/mongo-csharp-driver pull request #1008
Opened 2023-01-06 22:03 UTC by rstam

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                throw new BsonSerializationException(message, ex);
This change helped me figure out why some tests were failing.

We already do the same thing on Deserialize, so it seems like we should do it here in Serialize also.

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DictionarySerializerBase.cs
> +            : this(dictionaryRepresentation, BsonSerializer.LookupSerializer<object>(), BsonSerializer.LookupSerializer<object>())
Look it up in the registry instead of newing it up to pick up any specially configured ObjectSerializer.

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +            _objectSerializer = ((ObjectSerializer)BsonSerializer.LookupSerializer<object>()).WithDiscriminatorConvention(_discriminatorConvention);
We need to lookup the ObjectSerializer in the registry and then reconfigure the discriminatorConvention.

WithDiscriminator is a new method.

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            }
This is the key change that ensures only allowed types are deserialized.

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +
While the most important check is in Deserialize I think Serialize should do the same thing. Why let you serialize something that can't be deserialized?

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            private readonly static HashSet<Type> __allowedTypes = new HashSet<Type>
This list is pretty complete, but I'm sure someone will report missing types and we will add to this list over time.

2023-01-06 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                    type.GetGenericArguments().All(a => AllowedTypes(a));
A generic type is allowed if the generic type definition is allowed and all the type arguments are also allowed.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.TestHelpers/TestObjectSerializerRegisterer.cs
> +                    cache.AddOrUpdate(typeof(object), testObjectSerializer, (objectType, existingObjectSerializer) => testObjectSerializer); // might replace existing ObjectSerializer!
I wouldn't normally write code like this, but it's the only way to get our tests to pass given that we can't reliably register a custom ObjectSerializer early enough.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Jira/CSharp1559Tests.cs
> +        }
This static constructor here and similarly in many classes below ensures that the correct ObjectSerializer is registered before running these tests.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionaryGenericSerializerTests.cs
> +            });
The problem here is that while line 43 ensures that the correct ObjectSerializer is registered, line 43 doesn't help with any Dictionary (and similar) serializers that might already be registered and that have cached the wrong ObjectSerializer (as the key and value serializers) before line 43 was executed.

The workaround is to manually configure a class map for `T` that has all the correct serializers regardless of what may or may not already be in the registry.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionarySerializerTests.cs
> +
Similar issue as above.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> -            var exception = Record.Exception(() => new ObjectSerializer(null));
With the addition of a new constructor `new ObjectSerializer(null)` has become ambiguous.

2023-01-06 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +            var exception = Record.Exception(() => new ObjectSerializer(discriminatorConvention: null));
Using `discriminatorConvention: null` resolves the ambiguity.

2023-01-11 01:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +        private static readonly Func<Type, bool> __noAllowedTypes = t => false;
I struggled a bit with this name.

`AllowedTypes` is a suffix here.

This is a filter that allows `No` types (as opposed to `All` types).

That's how I came up with `NoAllowedTypes`.

2023-01-11 01:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                    type.GetGenericArguments().All(a => AllowedTypes(a));
Good optimization. Done.

2023-01-11 01:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                typeof(System.Collections.ObjectModel.ReadOnlyDictionary<,>),
I can't remember why I omitted KeyValuePair. Don't see any harm in adding it.

I got my list by scanning through the types loaded into Reflector. PriorityQueue is not there. Admittedly I was looking at net472 DLLs. Maybe PriorityQueue is not in net472, or maybe it's in a DLL I didn't have loaded into Reflector.

I'll try to think of a better list to check against.

2023-01-12 15:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +            if (_cache.TryAdd(type, serializer))
I considered using `GetOrAdd` but it doesn't quite fit our needs in this case.

We need to know whether the value was added or not (i.e. whether it already existed) in order to check for error and provide the proper error message when attempting to register a serializer that is already registered.

2023-01-12 15:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +                    var message = string.Format("There is already a different serializer registered for type {0}.", BsonUtils.GetFriendlyTypeName(type));
Sure, I like string interpolation a lot.

This was just copy/pasted from existing code and adapted.

I will change it to string interpolation here in this new code, but I'm reluctant to change existing code.

2023-01-12 15:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +                    var message = string.Format("There is already a different serializer registered for type {0}.", BsonUtils.GetFriendlyTypeName(type));
Done

2023-01-12 15:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                typeof(System.Collections.ObjectModel.ReadOnlyDictionary<,>),
Do you want to help me come up with more types to add to this list?

I'm going to push a new commit addressing your other comments, but leave this pending for now.

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.TestHelpers/RegisterObjectSerializerFixture.cs
> +    {
sealed is good

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.TestHelpers/RegisterObjectSerializerFixture.cs
> +    {
Done

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Jira/CSharp1559Tests.cs
> +        }
Turns out that if you don't actually need to use the fixture in your tests you can just omit this constructor.

We're only using the collection fixture for its side effect of registering the object serializer.

I'm going to remove all these constructors.

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/RegisterObjectSerializerCollection.cs
> +    [CollectionDefinition("RegisterObjectSerializer")]
Done

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionaryGenericSerializerTests.cs
> +            });
Originally this was done here because this was the only test affected by this.

But it does make sense to do it `RegisterObjectSerializerFixture`.

2023-01-12 15:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionaryGenericSerializerTests.cs
> +            });
There is a problem though... we can't move the class map registration to the fixture.

I'm going to leave this alone for now. Think about it a bit more and let me know if you want to pursue it further.

2023-01-12 21:35 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                typeof(System.Collections.ObjectModel.ReadOnlyDictionary<,>),
I can see just those two: 
`ObservableCollection`,
`ReadOnlyObservableCollection`

2023-01-12 21:35 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionaryGenericSerializerTests.cs
> +            });
Maybe we could just register serializers for `Dictionary<>`, `IDictionary<>` like we do with `ObjectSerializer` and skip the mapping?

2023-01-12 21:35 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +            if (_cache.TryAdd(type, serializer))
Sorry, I missed that `GetOrAdd` return value would not allow us to indicate if it was already inserted.

2023-01-14 00:28 UTC, JamesKovacs approved these changes
LGTM

2023-01-14 00:28 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                throw new BsonSerializationException(message, ex);
SGTM

2023-01-14 00:28 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +
Agreed.

2023-01-23 23:51 UTC, BorisDog requested changes

2023-01-23 23:51 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                typeof(System.Collections.ObjectModel.ReadOnlyDictionary<,>),
Reminder, do we want to the mentioned types above as well?

2023-01-23 23:51 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DictionaryGenericSerializerTests.cs
> +            });
Reminder.

2023-01-25 17:41 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +                typeof(System.Collections.ObjectModel.ReadOnlyDictionary<,>),
The full list I added in this commit is:

    ListDictionary
    OrderedDictionary
    Version
    KeyValuePair<,>
    KeyedCollection<,>
    ObservableCollection<>
    ReadOnlyObservableCollection<>
    System.Tuple<,,,,,,,> // one missing Tuple class

2023-01-25 17:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            obj is ObjectSerializer other &&
For non-sealed classes `obj is ObjectSerializer` is not a good enough test because `obj` might be a subclass of `ObjectSerializer` in which case we want to return `false`.

Because `ObjectSerializer` is `sealed` we know that if obj is an `ObjectSerializer` it can't be a subclass of `ObjectSerializer`.

2023-01-25 17:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            .Hash(_discriminatorConvention)
Deliberately left `_alowedTypes` out of the computation of the hash code because we don't know anything about the behavior of `GetHashCode` for delegates (and it's not worth finding out).

Technically `public override int GetHashCode() => 0` would be correct also if we don't anticipate serializers being put into a hash table (and even if they are `0` would just be a small performance hit).

2023-01-25 17:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +    public sealed class ObjectSerializer : ClassSerializerBase<object>
Changed to `sealed` in part to simplify the implementation of `Equals`.

Any concern that this could be considered a breaking change?

2023-01-25 17:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +        /// <inheritdoc/>
There is another ticket to implement `Equals` for *all* serializers.

In this PR I'm only implementing `Equals` for `ObjectSerializer` because it is required for the tests of `TryRegisterSerializer` to pass.

2023-01-25 17:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            _guidRepresentation == other._guidRepresentation;
I firmly believe `Equals` should be implemented by calling `Equals` on fields in order to preserve the semantics of `Equals` (without being forced to analyze whether `==` is semantically equivalent to `Equals` or not on a case by case basis).

But... in the case of `enum` fields calling `Equals` would involve boxing. It would still be correct, but there would be a small performance hit.

2023-01-25 23:20 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            .Hash(_discriminatorConvention)
I agree with your remark that `GetHashCode() => 0` would work, as this class is not designed to be used for lookup in hash tables.
Would not `=> base.GetHashCode()` be sufficient then?
The default implementation calculates the hash based on reference, so I would recommend to offload this to .net framework.

2023-01-25 23:20 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +    public sealed class ObjectSerializer : ClassSerializerBase<object>
We can avoid this by checking `other.GetType()`

2023-01-25 23:28 UTC, JamesKovacs requested changes
While I suspect that no one has subclassed `ObjectSerializer` there is no way to know for sure. See my suggested change to `Equals` avoids the need for this breaking change.

2023-01-25 23:28 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +    public sealed class ObjectSerializer : ClassSerializerBase<object>
It will break anyone with a `IBsonSerializer<T>` deriving from `ObjectSerializer`. A quick google for `mongodb objectserializer` returns our API docs and a few SO questions, but no one recommending deriving a new serializer from `ObjectSerializer`. It's probably not common, but we can't know for certain.

2023-01-25 23:28 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +        /// <inheritdoc/>
Agreed.

2023-01-25 23:28 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            obj is ObjectSerializer other &&
To avoid the `sealed` breaking change, would the following not be sufficient?
```
obj is ObjectSerializer other &&
GetType() == obj.GetType() &&
```

2023-01-26 00:10 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +    public sealed class ObjectSerializer : ClassSerializerBase<object>
Removing sealed to avoid possible though unlikely breaking change.

2023-01-26 00:22 UTC, JamesKovacs approved these changes
LGTM

2023-01-26 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ObjectSerializer.cs
> +            .Hash(_discriminatorConvention)
> If Equals returns true for x and y then x.GetHashCode() MUST EQUAL y.GetHashCode(). Calling base.GetHashCode() violates that.

I think this only applies to cases where `Hashcode` is actually used, which is lookups. But I agree that it's a "bon ton" not to violate this in any case.

I think 0 is a good option, to state that "we don't care", otherwise using `Hasher` leads to wrong impression that this class is designed and optimized to be used for lookups.

2023-01-26 00:33 UTC, BorisDog approved these changes
LGTM.
Comment re. `GetHashcode` for your consideration.

2023-01-26 04:55 UTC, merged