CSHARP-4448: Implement OIDC SASL mechanism.
mongodb/mongo-csharp-driver pull request #1010
Opened 2023-01-17 00:47 UTC by DmitryLukyanov

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcInputConfiguration.cs
> +            if (_requestTokenFunc == null && _requestTokenFuncAsync != null)
currently the spec wording suggests using "id"s of provided callbacks to determine whether it's a new oidc configuration or no. `Id` is effectively a memory address for a function. It looks good, but it doesn't work well if we implicitly generate not provided callbacks. This logic might be changed, so want to look at it again tomorrow.

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                    var command = result == null
small refactoring to be able to make `Transition` method async easier

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public virtual Task<ISaslStep> TransitionAsync(SaslConversation conversation, byte[] bytesReceivedFromServer, CancellationToken cancellationToken = default) =>
only `oidc` and `aws` (it's not done yet, but I will create a ticket for it) authentication currently requires async code path for `Transition`, so I think it's a good simplification that almost won't require changes in other authenticators

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +        protected class ClientLastOnlySendBytes : SaslStepBase
This steps means that the provided data won't be used for anything other than sending data to a server one more last time. I'm open to suggestion for a better naming. Put it here since the same class presents in aws

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                if (bytesReceivedFromServer.Length > 0)
this logic wasn't here before, but I assume we need this :)

2023-01-17 01:08 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoCredential.cs
> -        private void ValidatePassword(string password)
Nothing called this

2023-01-17 16:40 UTC, blink1073 commented on evergreen/evergreen.yml
> +    # - command: s3.put
You can uncomment this, I was debugging AWS creds

2023-01-17 16:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOIDCAuthenticator.cs
> +                    { "n", _principalName, _principalName != null }
yep

2023-01-17 16:42 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    # - command: s3.put
yeah, currently I simply copied what you had, but it's not in final form yet, thanks will do it

2023-02-23 16:23 UTC, DmitryLukyanov commented on evergreen/run-mongodb-oidc-test.sh
> +echo "MONGODB_URI_OIDC_AWS_DEVICE: $MONGODB_URI_OIDC_AWS_DEVICE"
from this list, I left only `MONGODB_URI`. The rest should be removed. Will do it in the next commit

2023-02-24 12:46 UTC, blink1073 requested changes

2023-02-24 12:46 UTC, blink1073 commented on evergreen/evergreen.yml
> +          mongo setup_oidc.js
This should be `mongosh`

2023-02-24 14:22 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          mongo setup_oidc.js
done

2023-02-24 17:05 UTC, blink1073 commented on evergreen/evergreen.yml
> -            git clone https://github.com/mongodb-labs/drivers-evergreen-tools.git $DRIVERS_TOOLS
You can use `master` now

2023-03-15 00:05 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Sasl/SaslAuthenticator.cs
> +        private protected virtual MongoAuthenticationException CreateException(ConnectionId connectionId, Exception ex, BsonDocument command)
The 3rd actual change in this file. Now we allow customizing authentication exception

2023-03-15 00:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/IConnectionInitializer.cs
> +    internal sealed class ConnectionInitializerContext
this is already in master

2023-03-28 23:51 UTC, BorisDog requested changes

2023-03-28 23:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/FileOidcExternalAuthenticationCredentialsProvider.cs
> +
remove blank line

2023-03-28 23:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/FileOidcExternalAuthenticationCredentialsProvider.cs
> +            using StreamReader streamReader = new StreamReader(_path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
nit: using var streamReader.

2023-03-28 23:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +    public sealed class MongoOidcAuthenticator : SaslAuthenticator
I think this class can be internal?

2023-03-28 23:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcCallbackProviders.cs
> +            Func<string, BsonDocument, CancellationToken, BsonDocument> requestCallbackFunc,
Consider defining 
```
public delegate BsonDocument RequestCallback(string a, BsonDocument b, CancellationToken c);
public delegate Task<BsonDocument> RequestCallbackAsync(string a, BsonDocument b, CancellationToken c);
...
```
Seems to be more readable than using Func<...> everywhere.

2023-03-28 23:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcCallbackProviders.cs
> +            _refreshCallbackFunc = (refreshCallbackFunc ?? ((principalName, saslResponse, previousCallbackAuthenticationData, cancellationToken) => refreshCallbackAsyncFunc(principalName, saslRespons
I guess the default implementation is for user convenience?

I am not a big fan of using Async method in Sync path. It's considered anti-pattern is sometimes dangerous.
In our case it does not seem to be justified, and I would much prefer to enforce providing Sync callback for Sync path.
So I suggest offloading this burden on user and just simply using sync in sync, async in async, and consider improvements here if we get any specific requests.

2023-03-29 18:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/CacheableCredentialsProvider.cs
> +        TCredentials ValidCredentials { get; }
Now we return just credentials regardless valid or no

2023-03-31 00:26 UTC, BorisDog requested changes

2023-03-31 00:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcCacheKey.cs
> +            while (dictionary.TryRemove(removeRecordsMarker, out var provider))
I am not sure `_removeInvalidRecordsRequested` and the related design is our best option.
Consider something simpler like:
```
  var expiredKeys = dictionary.Keys.Where(t => t.InvalidRecord);

            foreach (var key in expiredKeys)
            {
                if (dictionary.TryRemove(key, out var provider))
                {
                    (provider as IDisposable)?.Dispose();
                }
            }
```

Furthermore, the cache implementation is split between OidcCacheKey and `ExternalCredentialsAuthenticators`
Consider wrapping everything in a simpler `OidcCache` object with a single `Get(OidcInputConfiguration)` method.
This also would be more testable.

2023-03-31 00:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcCacheKey.cs
> +        public void TrackUsage() => _modifiedAt = _clock.UtcNow;
Sometimes this method is called `Touch`. Maybe just `Update` or `Refresh`

2023-03-31 00:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcCallbackProviders.cs
> +                : !a.IsProvided && !b.IsProvided;
Why do we need to handle nulls differently?

2023-03-31 00:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcInputConfiguration.cs
> +                _providerName == rhs._providerName&&
space before &&.

2023-03-31 00:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcInputConfiguration.cs
> +                _principalName == rhs._principalName;
Remove extra space at the end.
nit: I would rearrange the comparisons, so simple comparisons will fail faster (leave the most complex to the end).

2023-04-03 23:49 UTC, BorisDog requested changes

2023-04-04 22:12 UTC, BorisDog requested changes

2023-04-07 23:41 UTC, BorisDog requested changes

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcExternalAuthenticationCredentialsProvider.cs
> +                    // ignore it, may be already disposed
Got it.

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcExternalAuthenticationCredentialsProvider.cs
> +                    // ignore it, may be already disposed
adding  a comment would help : Semaphore might be already disposed by provider.

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcExternalAuthenticationCredentialsProvider.cs
> +                    _semaphore.Release();
Release only if acquired. Consider throwing everywhere if not acquired (and the opposite in Acquire).

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/OidcExternalAuthenticationCredentialsProvider.cs
> +                    _cancellationTokenSource.Cancel();
Why do we need to cancel here?

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/UsernamePasswordCredential.cs
> +using MongoDB.Driver.Core.Authentication.Sasl;
If we are cleaning usings, let's update copyright.

2023-04-07 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +        /// Gets the name of a device name authorization property.
Btw we don't really need comments here :)

2023-04-27 23:27 UTC, JamesKovacs requested changes
About halfway done. Pushing comments so you can make changes. I'll continue my review tomorrow after you've addressed these comments and pushed the additional changes you have pending.

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +                                    : throw new InvalidCastException($"The {ProviderMechanismProperyName} must be string, but was {value.GetType()}.");
ProviderMechanismProperyName => ProviderMechanismPropertyName (missing t)

Same feedback on the exception message as above.

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +                                allowedHostNames = value is IEnumerable<string> enumerable
```
foo = value is IEnumerable<T> enumerable ? enumerable : throw new Exception()
```
can be written more simply as:
```
foo = value as IEnuermable<T> ?? throw new Exception()
```

Similarly below.

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +                    return new OidcInputConfiguration(endpoint, principalName);
Don't we need to assert `EnsureHostsAreValid(endpoint, DefaultAllowedHostNames)` before returning the configuration object?

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +                static bool IsHostMatch(string host, string pattern)
I assume that this has been updated to match the current FQDN/subdomain rules that we discussed in Slack. As written, this function will accept `*mongodb.com`, which would match `evilmongodb.com`.

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +        internal static MongoOidcAuthenticator CreateAuthenticator(
Can be private.

2023-04-27 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +        private readonly new OidcSaslMechanism _mechanism;
We shouldn't be redefining the type of `_mechanism`. We should use a type constraint instead:

```
public abstract class SaslAuthenticator<TMechanism> : AuthenticatorBase where TMechanism: class, ISaslMechanism
```

Then `_mechanism` can be `TMechanism`.

2023-04-28 15:09 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/MongoOidcAuthenticator.cs
> +                static bool IsHostMatch(string host, string pattern)
done

2023-04-30 14:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                _connectionInitializerContext = _connectionInitializer.SendHello(this, cancellationToken);
now we save `_connectionInitializerContext` for the whole connection to be able to pass used credentials from initial auth call to reauth attempts. Saving not full authenticator, because current speculative auth impl expects recreating authenticator instance for reauth calls. It may be reconsidered in the follow up tickets

2023-04-30 14:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
> +                return (previousAuthenticators ?? authenticatorFactories.Select(c => c.Create(new DefaultAuthenticationContext(endPoint)))).ToList();
an initial handshake where `previousAuthenticators` is null for a hello call and will be not null for actual auth call, so speculative auth impl requires using the same authenticator instances for hello and auth calls in handshake.

2023-04-30 14:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
> +            var result = new List<IAuthenticator>();
Reauthentication case. Current speculative auth requires using a new authenticator instance, so previously saved speculative data won't be in play, however we need to share auth context with credentials from the initial auth call.

2023-04-30 14:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
> +            var result = new List<IAuthenticator>();
This logic is workaround, I think what we need is to share a single authenticator for a connection and play with his context if necessary including speculative authentication

2023-08-29 17:23 UTC, ashwinisingh01 commented
OIDC is supported for 7.0 release? The 7.0 release was targeted in August 2023.  Do we not support OIDC yes from the driver side ?

2023-09-22 17:43 UTC, JamesKovacs commented
> OIDC is supported for 7.0 release? The 7.0 release was targeted in August 2023. Do we not support OIDC yes from the driver side ?

We have not released support for OIDC machine workflows in the .NET/C# Driver yet. Please follow and comment on [CSHARP-4448](https://jira.mongodb.org/browse/CSHARP-4448) for updates.

2024-02-27 23:57 UTC, sanych-sun commented
I'm closing this PR as we got updated requirements and re-implemented OIDC as a separate PR.
Thank you for the PR though, I've used it as a guide.

2024-02-27 23:57 UTC, closed without merging