Release notes for 2.19.0.
mongodb/mongo-csharp-driver pull request #1013
Opened 2023-01-26 20:18 UTC by BorisDog

2023-01-26 20:20 UTC, DmitryLukyanov approved these changes
LGTM

2023-01-27 17:20 UTC, JamesKovacs requested changes
Minor changes.

2023-01-27 17:20 UTC, JamesKovacs commented on Release Notes/Release Notes v2.19.0.md
> +More information about the ObjectSerializer is available at FAQ page at:
ObjectSerializer => `ObjectSerializer`
(e.g. backticks around the class name)

>is available at FAQ page at:

is available in [our FAQ](https://www.mongodb.com/docs/drivers/csharp/v2.19/faq).

The FAQ link should be correct based on the docs staging site.

2023-01-27 17:29 UTC, JamesKovacs approved these changes
LGTM

2023-01-27 18:22 UTC, merged