CSHARP-4564: Implement ValueSerializers.
mongodb/mongo-csharp-driver pull request #1039
Opened 2023-03-13 15:26 UTC by rstam

2023-03-13 15:30 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +                case BsonType.Document:
ValueTuples serialized before this serializer was implemented will have been serialized as documents using the `BsonClassMapSerializer`.

We could make the representation configurable. If you want to do that I suggest we do that as a separate ticket.

2023-03-13 15:30 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ValueTupleSerializersTests.cs
> +        }
There are no tests for serializing or deserializing `null` because `ValueTuple` is a `struct` (as opposed to `Tuple` which is a `class`).

2023-03-13 16:53 UTC, rstam commented
A good way to review this is to compare the existing TupleSerializer to the new ValueTupleSerializer and the same for the tests.

Since ValueTupleSerializer is a clone of TupleSerializer I've made the smallest changes possible (so no formatting improvements).

2023-03-14 18:48 UTC, BorisDog requested changes
Few minor comments

2023-03-14 18:48 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +            if (serializerRegistry == null) { throw new ArgumentNullException("serializerRegistry"); }
`nameof`

2023-03-14 18:48 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +        public IBsonSerializer<T1> Item1Serializer
consider shorter form public `IBsonSerializer<T1> Item1Serializer => _lazyItem1Serializer.Value` everywhere.

2023-03-14 19:15 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +        public IBsonSerializer<T1> Item1Serializer
I mentioned in a comment that this file was cloned from `TupleSerializers.cs` and that I deliberately avoided making any formatting changes to make it easy to diff the two files.

Do you still think we should make these changes? And if yes, do I make the same changes to `TupleSerializers.cs`?

2023-03-14 20:57 UTC, BorisDog approved these changes
LGTM.

2023-03-14 20:57 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +        public IBsonSerializer<T1> Item1Serializer
I don't see any real-world use case where we would need to diff the two files. But either way is fine. For your consideration.

2023-03-14 22:22 UTC, rstam reviewed
Applied the requested formatting changes.

2023-03-14 23:22 UTC, BorisDog approved these changes
LGTM

2023-03-15 00:09 UTC, merged