CSHARP-4549: Better support for Tuples and ValueTuples in LINQ3.
mongodb/mongo-csharp-driver pull request #1040
Opened 2023-03-15 21:10 UTC by rstam

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TupleSerializers.cs
> +    public interface IBsonTupleSerializer
We need a non-generic interface that is implemented by all tuple serializers to get the item serializers.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TupleSerializers.cs
> +        public static IBsonSerializer Create(IEnumerable<IBsonSerializer> itemSerializers)
A factory method to create tuple serializers when the item types are only known at runtime.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TupleSerializers.cs
> +        public IBsonSerializer<T1> Item1Serializer => _lazyItem1Serializer.Value;
Boris requested these formatting changes in ValueTupleSerializer and I'm making the same changes in this file since we're already in here working on this file.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ValueTupleSerializers.cs
> +using System.Linq;
Most comments I made in TupleSerializers.cs apply to this file as well.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/ReflectionInfo.cs
> +        public static MethodInfo Method<T1, T2, T3, T4, T5, T6, TResult>(Expression<Func<T1, T2, T3, T4, T5, T6, TResult>> lambda)
Just adding a few more overloads since we've never needed 6+ types before now.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberExpressionToAggregationExpressionTranslator.cs
> +                    var ast = AstExpression.ArrayElemAt(container.Ast, index: itemNumber - 1);
This is where an item name becomes an array element access (in aggregation expression language).

 Note that the notation `tuple.0` is only valid in filter language and not aggregation language.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CreateMethodToAggregationExpressionTranslator.cs
> +                var items = new List<AstExpression>(arguments.Count);
The main job here to implement Create is to gather up the items and itemSerializers.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CreateMethodToAggregationExpressionTranslator.cs
> +                var ast = AstExpression.ComputedArray(items);
Now that we know the items and itemSerializers it's relatively easy to create the computed array and the corresponding tuple serializer.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CreateMethodToAggregationExpressionTranslator.cs
> +                        item = AstExpression.ComputedArray(valueTranslation.Ast);
Note that the 8th item is processed differently. It's wrapped in a 1-Tuple.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewTupleExpressionToAggregationExpressionTranslator.cs
> +                var items = new List<AstExpression>();
This is all similar to the `Create` method but starting from a `NewExpression`.

Also, the 8th item is NOT processed specially the way it is for `Create`.

2023-03-15 21:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ToFilterFieldTranslators/MemberExpressionToFilterFieldTranslator.cs
> +                        var itemPath = $"{field.Path}.{itemNumber - 1}";
This is where `tuple.Item<n>` is translated to `tuple.<N>` in filter language.

2023-03-15 21:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3924Tests.cs
> +            AssertStages(stages, "{ $project : { _v : ['$X'], _id : 0 } }");
Just adjusting tests because LINQ3 now represents Tuples as arrays the same way as they would be when serializing a POCO with a Tuple property.

2023-03-17 22:48 UTC, JamesKovacs requested changes
Nice job. I tried to break it by passing in a 16-member tuple, but it handles tuples with more than 8 members correctly. I also tried modifying `Item7` to be a string so that different serializers would have to be used for different elements and that was correct too. Your ItemSerializer code looked correct, but I wanted to make sure that it behaved correctly as well. It does.

Two suggestions:
1. Implement a test with a `Tuple<int, string>`. We don't have to exhaustively test different data types, but let's test at least one tuple with mixed types.
2. Serializing a `Tuple<T1,...,T16>` writes a nested tuple to the database (e.g. `Tuple16: [ 1, 2, 3, 4, 5, 6, 7, [ 8, 9, 10, 11, 12, 13, 14, [ 15, 16 ] ] ]`). We shouldn't be leaking C#'s tuple impl details to the database. We should serialize tuples as flat arrays regardless of width.

2023-03-22 18:39 UTC, JamesKovacs approved these changes
LGTM

2023-03-22 21:26 UTC, closed without merging