CSHARP-4528: Extend Search.Equals to support number and date
mongodb/mongo-csharp-driver pull request #1043
Opened 2023-03-20 19:38 UTC by BorisDog

2023-03-21 23:09 UTC, JamesKovacs requested changes
Spelling correction and minor question. Overall looks good.

2023-03-21 23:09 UTC, JamesKovacs commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                DateTime v => (BsonDateTime)v,
Should we support `DateTimeOffset` too?

2023-03-21 23:41 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                DateTime v => (BsonDateTime)v,
We can. We don't have a direct implicit conversion to `BsonDateTime`, so not sure how best to account for offset in this case.
Maybe we can consider support for `DateTimeOffset` both for equals and `Range` in a separate ticket?

2023-03-21 23:41 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        public static object[][] EqualsSupporteddTypesTestData => new[]
Thanks, done.

2023-03-22 17:00 UTC, JamesKovacs approved these changes
LGTM

2023-03-22 18:08 UTC, merged