CSHARP-4576: Atlas search: support score in Compound operator
mongodb/mongo-csharp-driver pull request #1045
Opened 2023-03-22 21:07 UTC by BorisDog

2023-03-22 22:01 UTC, JamesKovacs requested changes
Looks good. We should include `MetaSearchScore(x => x.Score)` rather than forcing users to specify the field name as a string.

2023-03-22 22:01 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +                .MetaSearchScore("score");
We should include strongly-typed expressions as well as string-based field names.

2023-03-22 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +                .MetaSearchScore("score");
I agree, that's also applies to `MetaSearchHighlights` and `MetaTextScore`.
I think it's better to address this in separate ticket.

2023-03-23 00:00 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +                .MetaSearchScore("score");
Fair enough. Create a separate ticket and it can be implemented post-2.19.1.

2023-03-23 00:00 UTC, JamesKovacs approved these changes
LGTM

2023-03-23 02:19 UTC, merged