CSHARP-4483: connectionId returned in heartbeats may be int32, double, or int64.
mongodb/mongo-csharp-driver pull request #1051
Opened 2023-03-30 00:22 UTC by JamesKovacs

Although CSHARP-4417 changes the client and server connectionIds to use `int64`, the server description update code path was not tested. The update code path is where the server response is used update the `ConnectionId.LongServerValue`. `HelloResult.ConnectionIdServerValue` still parsed `connectionId` in the response as an `int32`. This has been fixed and additional tests added.

Although `HelloResult` is public, it is in Core. We renamed this class during the offensive language removal initiative and no one complained. Thus changing the data type of `HelloResult.ConnectionIdServerValue` from `int?` to `long?` shouldn't be problematic.

2023-03-30 16:57 UTC, rstam requested changes
Two minor changes requested.

I'm also willing to LGTM as is.

2023-03-30 16:57 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
> +        public void InitializeConnection_should_acquire_connectionId_from_hello_response([Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int.MaxVal
Consider reformatting on multiple lines:

    [Theory]
    [ParameterAttributeData]
    public void InitializeConnection_should_acquire_connectionId_from_hello_response(
        [Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int.MaxValue*4)] object serverConnectionId,
        [Values(false, true)] bool async)

2023-03-30 16:57 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
> +        public void InitializeConnection_should_acquire_connectionId_from_legacy_hello_response([Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int
Consider reformatting on multiple lines:

    [Theory]
    [ParameterAttributeData]
    public void InitializeConnection_should_acquire_connectionId_from_legacy_hello_response(
        [Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int.MaxValue*4)] object serverConnectionId,
        [Values(false, true)] bool async)

2023-04-12 23:01 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
> +        public void InitializeConnection_should_acquire_connectionId_from_hello_response([Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int.MaxVal
Done.

2023-04-12 23:01 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ConnectionInitializerTests.cs
> +        public void InitializeConnection_should_acquire_connectionId_from_legacy_hello_response([Values(1, int.MaxValue, (long)int.MaxValue + 1, long.MaxValue, 1d, (double)int.MaxValue+1, (double)int
Done.

2023-04-12 23:03 UTC, merged