CSHARP-4353: Collect FaaS platform information as part of the environment information in driver handshake metadata.
mongodb/mongo-csharp-driver pull request #1054
Opened 2023-03-30 20:52 UTC by DmitryLukyanov

2023-03-30 20:53 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +            if (clientDocument.TryGetValue("driver", out var driver) && driver.AsBsonDocument.ElementCount > 0)
this part is not really clear yet. Since at least `driver.name` is required bu the server. So we can really remove everything inside driver as the spec suggests. Trying to clarify it.

2023-04-03 22:56 UTC, JamesKovacs requested changes
LGTM. Just need to rebase on `master` to remove unrelated wildcard index changes.

2023-04-03 22:56 UTC, JamesKovacs commented on tests/MongoDB.Driver.Legacy.Tests/Builders/IndexKeysBuilderTests.cs
> +            index["wildcardProjection"].Should().Be(BsonDocument.Parse("{ _id : 1 }"));
Looks like you need to rebase as you've got unrelated changes.

2023-04-03 22:56 UTC, JamesKovacs commented on tests/MongoDB.Driver.Legacy.Tests/Builders/IndexKeysBuilderTypedTests.cs
> +            index["wildcardProjection"].Should().Be(BsonDocument.Parse("{ b : 1, _id : 0 }"));
More unrelated changes.

2023-04-06 15:59 UTC, JamesKovacs approved these changes
LGTM

2023-04-06 16:43 UTC, merged