CSHARP-4596: Translate widening Convert instead of ignoring them.
mongodb/mongo-csharp-driver pull request #1059
Opened 2023-04-06 23:22 UTC by rstam

2023-04-06 23:28 UTC, rstam commented on src/MongoDB.Bson/Serialization/IBsonNumericSerializer.cs
> +    public interface IBsonNumericSerializer : IBsonSerializer
All numeric serializers implement this new interface.

2023-04-06 23:28 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> +        public static IBsonSerializer CreateWiderSerializer(Expression expression, IBsonSerializer narrowerSerializer, Type widerType)
The idea here is to create a new serializer for the wider type, but *only* if the serializer for the narrower type serializes values as numbers.

2023-04-06 23:28 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/BinaryExpressionToAggregationExpressionTranslator.cs
> -
Instead of throwing away the Convert just let it be translated. That way we'll end up with the proper serializer for any constants involved.

2023-04-06 23:28 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +
Special new handling for Convert that is a numeric widening conversion.

2023-04-06 23:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            result.Projection.Should().Be("{ Result: { \"$divide\": [{ $toDouble : \"$C.E.F\" }, { $toDouble : \"$C.E.H\" }] }, _id: 0 }");
Please check all the changed test assertions with an eye to whether any of the new MQL is invalid.

2023-04-06 23:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4596Tests.cs
> +        public void Test_widening_expressions()
I should remove this before pushing to master.

I was just verifying that for all these combinations the C# compiler does a single Convert (without any intermediate converts for example).

2023-04-06 23:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4596Tests.cs
> +                exception.Should().BeOfType<NotSupportedException>();
Note that this is not a regression against LINQ2, but it is a regression against some earlier version of LINQ3 (don't know exactly when this broke but I can find out if necessary).

2023-04-13 23:50 UTC, JamesKovacs requested changes
See comments inline.

2023-04-13 23:50 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            result.Projection.Should().Be("{ Result: { \"$divide\": [{ $toDouble : \"$C.E.F\" }, { $toDouble : \"$C.E.H\" }] }, _id: 0 }");
`$toDouble`, `$toLong`, etc. were added in MongoDB 4.0. We will have to avoid running these tests on MongoDB 3.6.

2023-04-13 23:50 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4596Tests.cs
> +        public void Test_widening_expressions()
Don't forget to remove these tests before pushing.

2023-04-13 23:55 UTC, JamesKovacs commented
`MongoDB.Driver.Tests.Linq.Linq3ImplementationTests.Jira.CSharp4596Tests.MongoDB.Driver.Tests.Linq.Linq3ImplementationTests.Jira.CSharp4596Tests.Subtract_DateTimes_should_work_linqProvider__V3_` is failing on MongoDB 4.4 and earlier.
`Command aggregate failed: Invalid $project :: caused by :: Unrecognized expression '$dateDiff'.`

2023-09-26 16:38 UTC, rstam commented
This work has been incorporated into the work for CSHARP-4566, so this PR is now moot.

2023-09-26 16:38 UTC, closed without merging