CSHARP-4492: Drivers should not create the ECC collection in v2 of queryable encryption.
mongodb/mongo-csharp-driver pull request #1067
Opened 2023-04-17 20:08 UTC by DmitryLukyanov

2023-04-18 23:38 UTC, JamesKovacs requested changes
Two issues...
- Question about whether this change prevents new drivers from using FLEv1 features.
- Minor formatting issue.

2023-04-18 23:38 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +
Extraneous newline.

2023-04-18 23:38 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +            EnsureFeatureSupported(database.Client.Cluster, Feature.Csfle2QEv2, cancellationToken);
Won't this prevent FLEv1 from being used with newer drivers?

2023-04-19 14:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +
done

2023-04-19 14:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +            EnsureFeatureSupported(database.Client.Cluster, Feature.Csfle2QEv2, cancellationToken);
Inside this method there is a validation on encryptedFields value which is part of CSFLE2. So, FLE1 should be not affected. NOTE: I'm not sure off the top of my head whether it's even possible to be in this mode with latest libmongocrypt bingins

2023-04-19 22:48 UTC, JamesKovacs requested changes
Question about the asserter and then we're good.

2023-04-19 22:48 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/JsonDrivenTests/CommandStartedEventAsserter.cs
> +                                    case "eccCollection":
`eccCollection` was removed. We shouldn't need this case anymore.

2023-04-19 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/JsonDrivenTests/CommandStartedEventAsserter.cs
> +                                    case "eccCollection":
in theory yes, but json tests assert that this value is not filled

2023-04-25 22:00 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/JsonDrivenTests/CommandStartedEventAsserter.cs
> +                                    case "eccCollection":
Ah ok. LGTM then.

2023-04-25 22:00 UTC, JamesKovacs approved these changes
LGTM

2023-04-25 22:06 UTC, merged