CSHARP-4622: Process constant expression to a filter query
mongodb/mongo-csharp-driver pull request #1074
Opened 2023-05-02 22:50 UTC by sanych-sun

2023-05-02 23:42 UTC, rstam requested changes

2023-05-02 23:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionToFilterTranslator.cs
> +                    return ConstantExpressionToFilterTranslator.Translate(context, (ConstantExpression)expression);
Try handling this in the AstSimplifier instead?

https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstSimplifier.cs#L310

Replace `VisitMatchStage` with `VisitExprFilter` and adapt the logic accordingly.

2023-05-03 00:39 UTC, rstam requested changes
A few more comments about the tests.

2023-05-03 00:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +        public async Task ReplaceOneAsync(
No need to test `ReplaceOneAsync`. The code path for translating `d => true` is the same as for `ReplaceOne`.

2023-05-03 00:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +        }
We like to use `FluentAssertions` in tests. You will only see `Assert.Null` in older tests.

I would propose these two methods be refactored as:

    [Theory]
    [ParameterAttributeData]
    public void ReplaceOne(
        [Values(LinqProvider.V2, LinqProvider.V3)] LinqProvider linqProvider)
    {
        var collection = GetCollection(linqProvider);
        var options = new ReplaceOptions { IsUpsert = true };
        var data = new Data { Id = 1 };

        var result = collection.ReplaceOne(d => true, data, options);

        result.UpsertedId.Should().Be(1);
    }

    private IMongoCollection<Data> GetCollection(LinqProvider linqProvider)
    {
        var collection = GetCollection<Data>("test", linqProvider);
        CreateCollection(collection);
        return collection;
    }

Note the new call to `CreateCollection`. Without it the second run of the test for the other LinqProvider fails because the data from the first test is left behind.

2023-05-03 00:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +            var record = Record.Exception(() => collection.ReplaceOne(d => true, data, options));
If we don't expect an exception we don't need to use `Record.Exception`.

See next comment.

2023-05-03 01:24 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionToFilterTranslator.cs
> +                    return ConstantExpressionToFilterTranslator.Translate(context, (ConstantExpression)expression);
As per our discussion: we will stick to the proposed changes and remove VisitMatchStage instead.

2023-05-03 01:47 UTC, rstam requested changes

2023-05-03 01:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConstExpressionToFilterTranslater.cs
> +    internal static class ConstantExpressionToFilterTranslator
Name the file the same as the class (no abbreviations)

2023-05-03 16:53 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +        public async Task ReplaceOneAsync(
Done

2023-05-03 16:55 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +        }
Done

2023-05-03 17:53 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +            var record = Record.Exception(() => collection.ReplaceOne(d => true, data, options));
Done

2023-05-03 17:54 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConstExpressionToFilterTranslater.cs
> +    internal static class ConstantExpressionToFilterTranslator
Done

2023-05-03 22:57 UTC, rstam requested changes
Very close to finished!

2023-05-03 22:57 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +                new Data { Id = 1, Text = "original"});
By inserting a document you have converted the upsert into an update.

I don't think it matters but the test is now subtly different from what the user  originally reported.

2023-05-03 22:57 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConstantExpressionToFilterTranslatorTests.cs
> +        public void Translate_should_process_supported_constants(BsonValue expected, ConstantExpression expression)
Minor comment: we normally put the parameters that are inputs to the test first and the expected results last.

    public void Translate_should_process_supported_constants(ConstantExpression expression, BsonValue expected)

2023-05-03 22:57 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +
Unnecessary blank line?

2023-05-03 22:57 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConstantExpressionToFilterTranslatorTests.cs
> +        public void Translate_should_process_supported_constants(BsonValue expected, ConstantExpression expression)
Also consider renaming the `expected` parameter to `expectedFilter`.

But not a big deal if you like `expected` better.

2023-05-04 02:44 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +                new Data { Id = 1, Text = "original"});
Done

2023-05-04 02:44 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ConstantExpressionToFilterTranslatorTests.cs
> +        public void Translate_should_process_supported_constants(BsonValue expected, ConstantExpression expression)
Done

2023-05-04 02:44 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4622Tests.cs
> +
done

2023-05-04 22:11 UTC, rstam approved these changes
LGTM

2023-05-05 22:42 UTC, merged