CSHARP-4616: OfType should match derived types
mongodb/mongo-csharp-driver pull request #1075
Opened 2023-05-04 18:02 UTC by sanych-sun

2023-05-04 22:49 UTC, rstam requested changes

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +        public void OfTypeMethodToPipeline()
Our usual naming convention for test methods is something like:

    OfType_should_return_expected_results

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            AssertTypeOf<Company>(collection, "{ $match: { _t: 'Company' } }", 2);
I understand why you wrote it this way... but this does mean that this one test is testing three different things.

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            AssertTypeOf<Company>(collection, "{ $match: { _t: 'Company' } }", 2);
Probably makes sense to list the tests in descending order according to the class hierarchy:

    AssertTypeOf<Account>(collection, "{ $match : { _t : 'Account' } }", 3);
    AssertTypeOf<Company>(collection, "{ $match : { _t : 'Company' } }", 2);
    AssertTypeOf<Contact>(collection, "{ $match : { _t : 'Contact' } }", 1);

nit: we usually use spaces on both sides of `:` in JSON constants.

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +        private void AssertTypeOf<TDocument>(IMongoCollection<Entity> collection, string expectedStage, int resultsCount)
Maybe rename `resultsCount` to `expectedCount` (or `expectedResultsCount`)

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            var query = collection
The name `query` is not wrong here, but in all our other tests this variable is named `queryable`

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            var stages = Translate<Entity, TDocument>(query);
I would prefer this line be:

    var stages = Translate(collection, queryable);

For two reasons: it can infer the generic types, and it also uses the correct Linq provider configured for the collection.

2023-05-04 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +                new Contact { FirstName = "John", LastName = "Doe" });
The values of these properties do not participate in the test in any way. Should we remove them? Or should we assert something about them in the results?

I suppose even if we don't assert against them at least we are verifying that deserialization doesn't throw.

2023-05-05 17:02 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +        public void OfTypeMethodToPipeline()
Done

2023-05-05 17:04 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            var query = collection
Done

2023-05-05 17:04 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            var stages = Translate<Entity, TDocument>(query);
Done

2023-05-05 17:05 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +                new Contact { FirstName = "John", LastName = "Doe" });
I prefer to leave the extra fields here. Because if there is any problem with filter and wrong documents will return, the serializer will failure to deserialize the document because of extra fields.

2023-05-05 17:39 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            AssertTypeOf<Company>(collection, "{ $match: { _t: 'Company' } }", 2);
Done

2023-05-05 17:40 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            var items = queryable.ToList();
Done

2023-05-05 17:40 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +                new Contact { FirstName = "John", LastName = "Doe" });
Done

2023-05-05 17:40 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            [BsonId]
Done

2023-05-05 17:40 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +            public ObjectId Id { get; set; }
Done

2023-05-05 17:41 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToPipelineTranslators/OfTypeMethodToPipelineTranslatorTests.cs
> +using Xunit;
Done

2023-05-05 17:59 UTC, rstam approved these changes
LGTM

2023-05-05 20:18 UTC, merged