CSHARP-4634: Error in LINQ3 provider when custom ObjectSerializer is used
mongodb/mongo-csharp-driver pull request #1080
Opened 2023-05-10 22:30 UTC by sanych-sun

2023-05-10 23:56 UTC, rstam requested changes

2023-05-10 23:56 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +
You need to also change the no-argument constructor to:

    public DiscriminatedInterfaceSerializer()
        : this(discriminatorConvention: null)
    {
    }

and postpone the lookup of the DiscriminatorConvention until later.

2023-05-10 23:56 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
>              _discriminatorConvention = discriminatorConvention;
_discriminatorConvention = discriminatorConvention ?? BsonSerializer.LookupDiscriminatorConvention(typeof(TInterface));

2023-05-10 23:56 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +                _objectSerializer = standardObjectSerializer.WithDiscriminatorConvention(discriminatorConvention);
Probably need to pass `_discriminatorConvention` instead of `discriminatorConvention` here.

2023-05-12 19:35 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
>              _discriminatorConvention = discriminatorConvention;
Done

2023-05-12 19:35 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +                _objectSerializer = standardObjectSerializer.WithDiscriminatorConvention(discriminatorConvention);
Done

2023-05-12 19:37 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +
Done

2023-05-18 18:26 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +            _discriminatorConvention = discriminatorConvention ?? BsonSerializer.LookupDiscriminatorConvention(typeof(TInterface));;
Ups, removed. Thanks!

2023-05-23 18:28 UTC, merged