CSHARP-4656 Simplify A : "$A" to A : 1 only on find
mongodb/mongo-csharp-driver pull request #1087
Opened 2023-05-16 19:25 UTC by sanych-sun

2023-05-16 19:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            var simplifiedProjectStage = AstFindProjectionSimplifier.SimplifyFindProjection(projectStage);
I expected this extra step to be in `TranslateExpressionToFindProjection` only.

2023-05-16 19:53 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            var simplifiedProjectStage = AstFindProjectionSimplifier.SimplifyFindProjection(projectStage);
Right, fixed

2023-05-18 21:22 UTC, rstam requested changes
I like your idea of replacing a regular expression projection definition with a `FindExpressionProjectionDefinition` when we know we're doing a `Find`.

2023-05-18 21:22 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstFindProjectionSimplifier.cs
> +﻿using MongoDB.Driver.Linq.Linq3Implementation.Ast.Expressions;
Add copyright

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +﻿using System;
Add copyright

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +                "{ A : 1, _id : 0 }");
I would refactor these two tests to be:

    [Fact]
    public void Projection_to_class_should_work()
        => AssertProjection(
            x => new Projection { A = x.A, X = x.B },
            "{ A : 1, X : '$B', _id : 0 }");

    [Fact]
    public void Projection_to_anonymous_type_should_work()
        => AssertProjection(
            x => new { x.A, X = x.B },
            "{ A : 1, X : '$B', _id : 0 }");

(Note shorter property names)

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        [Fact]
I would remove this test

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        public void Should_project_to_anonymous_type_with_custom_fields()
Maybe add a test like this also (probably not in this file?):

    [Fact]
    public void Find_projection_should_simplify_as_expected()
    {
        var collection = GetCollection<Document>();
        Expression<Func<Document, Projection>> expression = x => new Projection { A = x.A, X = x.B };
        var projectionDefinition = new ProjectExpressionProjection<Document, Projection>(expression, new ExpressionTranslationOptions());

        var find = collection.Find("{}").Project(projectionDefinition);

        var translatedProjection = TranslateFindProjection(collection, find);
        translatedProjection.Should().Be("{ A : 1, X : '$B', _id : 0 }");

        var results = find.ToList();
    }

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        private void AssertProjection<TSource, TProjection>(
TSource can just be Document. It doesn't have to be a type parameter.

2023-05-18 21:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +            public int Number { get; set; }
Probably just A and X for field names. One is the same as Document and the other is not.

2023-05-19 16:29 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstFindProjectionSimplifier.cs
> +﻿using MongoDB.Driver.Linq.Linq3Implementation.Ast.Expressions;
Done

2023-05-19 16:32 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +﻿using System;
Done

2023-05-19 16:37 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +                "{ A : 1, _id : 0 }");
Done

2023-05-19 16:37 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        [Fact]
Done

2023-05-19 16:37 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        private void AssertProjection<TSource, TProjection>(
Done

2023-05-19 16:37 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +            public int Number { get; set; }
Done

2023-05-19 17:25 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindExpressionProjectionDefinitionTests.cs
> +        public void Should_project_to_anonymous_type_with_custom_fields()
Added similar test to FindFluentTests without interacting with the database to follow that test class way.

2023-05-19 21:03 UTC, rstam requested changes
Let me know if you want to have a Zoom meeting to discuss requested changes.

2023-05-19 22:48 UTC, sanych-sun commented on src/MongoDB.Driver/FindFluent.cs
> +
Done, as it was discussed offline via virtual method.

2023-05-19 23:29 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +        public void Find_projection_should_simplify_as_expected()
Done

2023-05-23 18:59 UTC, rstam requested changes
There is still one call to:

    new FindExpressionProjectionDefinition

in `IFindFluentExtensions.cs`.

I think it can be replaced with a call to:

    new ExpressionProjectionDefinition

That would mean that the `FindExpressionProjectionDefinition` class is no longer used at all (and that's a good thing).

We can't really remove the `FindExpressionProjectionDefinition` class because it is `public` and we don't know if any users is creating it directly.

2023-05-23 18:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +        }
This class is no longer used.

Did you not find a new (better) place for the test you removed in this commit? (The test that used this class)

2023-05-23 18:59 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            LinqProvider linqProvider)
nit: for better readability I prefer that parameters either all be on one line or each on a separate line, as in:

    internal override RenderedProjectionDefinition<TOutput> RenderForFind(
        IBsonSerializer<TInput> sourceSerializer,
        IBsonSerializerRegistry serializerRegistry,
        LinqProvider linqProvider)

2023-05-23 18:59 UTC, rstam commented on src/MongoDB.Driver/ProjectionDefinition.cs
> +
This was a really good suggestion to make this method virtual!

We also discussed overriding this method in subclasses where it doesn't make sense and throw `InvalidOperationException`.

2023-05-24 18:38 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +        }
Removed the unused class. Will create tests once we decide how to share that useful helper methods.

2023-05-24 18:38 UTC, sanych-sun commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            LinqProvider linqProvider)
Done

2023-05-24 19:39 UTC, sanych-sun commented on src/MongoDB.Driver/ProjectionDefinition.cs
> +
Done

2023-05-24 20:20 UTC, rstam approved these changes
LGTM

2023-05-24 21:13 UTC, merged

2023-11-17 18:27 UTC, connorstorer-kbxcom commented
> There is still one call to:
> 
> ```
> new FindExpressionProjectionDefinition
> ```
> 
> in `IFindFluentExtensions.cs`.
> 
> I think it can be replaced with a call to:
> 
> ```
> new ExpressionProjectionDefinition
> ```
> 
> That would mean that the `FindExpressionProjectionDefinition` class is no longer used at all (and that's a good thing).
> 
> We can't really remove the `FindExpressionProjectionDefinition` class because it is `public` and we don't know if any users is creating it directly.

@rstam Prior to 2.19.2, (2.19.1) this was valid below, where `Projection = Builders<TDocumentEntity>.Projection.Expression` returned FindExpressionProjectionDefinition (public) but now returns sealed `ExpressionProjectionDefinition`. What's your suggestion on how I can continue to Cast/Select/Project this. This is used within a test suite and I know there are a lot of missing pieces below, but I wanted to get your shot from the hip opinion? Much appreciated, no matter how brutal it is :D!

```csharp
public void ApplyProjections<TDocumentEntity, TSelectEntity>()
{
    Expression<Func<TDocumentEntity, TSelectEntity>> select = null;
    var findOpts = new FindOptions<TDocumentEntity, TSelectEntity>
    {
        Projection = Builders<TDocumentEntity>.Projection.Expression(select)
    };
    var projectedData = GetData<TDocumentEntity, TSelectEntity, TSelectEntity>(findOpts.Projection);
}

public async Task<List<TReturnEntity>> GetData<TDocumentEntity, TSelectEntity, TReturnEntity>(
    ProjectionDefinition<TDocumentEntity, TSelectEntity> select)
{
    var queryable = _instance.CollectionDocuments.AsQueryable();
    var additionalExp = GetSomeExpression();
    queryable = queryable.Where(additionalExp);
    var expSelect = select as FindExpressionProjectionDefinition<TDocumentEntity, TSelectEntity>;
    return queryable.Select(expSelect.Expression).Cast<TReturnEntity>().ToList();
}
```

2023-12-04 17:53 UTC, connorstorer-kbxcom commented
Bypassing with some temporary reflection as noted in [CSHARP-4860](https://jira.mongodb.org/browse/CSHARP-4860).