CSHARP-4632: Consolidate new and init expression translation
mongodb/mongo-csharp-driver pull request #1094
Opened 2023-05-25 18:18 UTC by sanych-sun

2023-05-25 22:40 UTC, rstam requested changes
Minor changes suggested.

2023-05-25 22:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> +            return MemberInitExpressionToAggregationExpressionTranslator.Translate(context, Expression.MemberInit(expression, Array.Empty<MemberBinding>()));
I don't like the call to `Expression.MemberInit` to create a fake `MemberInitExpression` that was not present in the user's original LINQ query.

Instead let's introduce a new overload of `MemberInitExpressionToAggregationExpressionTranslator.Translate` that can be called from two places with the proper parameters.

From this location we would call it like this:

    return MemberInitExpressionToAggregationExpressionTranslator.Translate(context, expression, expression, Array.Empty<MemberBinding>());

2023-05-25 22:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberInitExpressionToAggregationExpressionTranslator.cs
> +            if (classType.BaseType != null)
Create a new helper overload that contains the bulk of this file and is called from both this file and from `NewExpressionToAggregationExpressionTranslator`.

In this file the call would look like:

    public static AggregationExpression Translate(TranslationContext context, MemberInitExpression expression)
    {
        return Translate(context, expression, expression.NewExpression, expression.Bindings);
    }

The signature of the new overload would be:

    public static AggregationExpression Translate(TranslationContext context, Expression expression, NewExpression newExpression, IReadOnlyList<MemberBinding> bindings)

The point of the new helper method is so that `NewExpressionToAggregationExpressionTranslator` doesn't have to create a fake `MemberInitExpression`.

2023-05-25 22:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> -            var members = expression.Members;
Have you convinced yourself that all this code being deleted is the same as what `MemberInitExpressionToAggregationExpressionTranslator` does?

If not how does it differ? Any breaking changes?

2023-05-25 22:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> -                var memberMap = classMap.MapMember(members[i]).SetSerializer(valueSerializer).SetDefaultValue(defaultValue);
I don't see anything related to default values in `MemberInitExpressionToAggregationExpressionTranslator`.

Is that OK?

2023-05-26 22:58 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> +            return MemberInitExpressionToAggregationExpressionTranslator.Translate(context, Expression.MemberInit(expression, Array.Empty<MemberBinding>()));
Done

2023-05-26 22:58 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberInitExpressionToAggregationExpressionTranslator.cs
> +            if (classType.BaseType != null)
Done

2023-05-26 22:59 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> -                var memberMap = classMap.MapMember(members[i]).SetSerializer(valueSerializer).SetDefaultValue(defaultValue);
Added default value set for constructor parameters.

2023-05-30 17:53 UTC, rstam approved these changes
LGTM but remember you were planning to remove a test before pushing to master.

2023-05-30 17:53 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4632Tests.cs
> +﻿using FluentAssertions;
Don't forget to remove this test.

2023-05-30 19:47 UTC, merged