CSHARP-4659: Improve BsonClassMapSerializer to support stuctures
mongodb/mongo-csharp-driver pull request #1098
Opened 2023-05-29 17:57 UTC by sanych-sun

2023-05-29 17:59 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonMemberMap.cs
> +                // Fallback to reflection for value type to avoid boxing-unboxing problems
I was not able to find a strict documentation for Expression.Unwrap to prof it works or find a scenarios when it not working. So I've decided to fallback to reflection, that works with once boxed struct, without unboxing it.

2023-05-30 17:40 UTC, rstam requested changes
Looks great. Just a few minor suggestions.

2023-05-30 17:40 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +
Remove "Fails" from the test name.

2023-05-30 17:40 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +            var result = _collection.FindOneAs<S>();
Remove "Fails" from the test name.

2023-05-30 17:40 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +
Could also use `Remove and Sort Usings" to clean up using statements.

2023-05-30 19:51 UTC, sanych-sun commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +
Done

2023-05-30 19:51 UTC, sanych-sun commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +            var result = _collection.FindOneAs<S>();
Done

2023-05-30 20:24 UTC, rstam approved these changes
LGTM

2023-05-30 20:55 UTC, merged