CSHARP-4347: Add log messages to Server selection spec
mongodb/mongo-csharp-driver pull request #1103
Opened 2023-06-01 22:41 UTC by BorisDog

2023-06-09 23:13 UTC, JamesKovacs requested changes
Feedback and questions for your consideration.

2023-06-09 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogTemplateProvidersCluster.cs
> +                    //e.Exception?.ToString()));
Debug code `exception123` should be replaced with commented impl on line 91.

2023-06-09 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/DatabaseExistsOperation.cs
> +
Missing calls to `BeginOperation` in `Execute` and `ExecuteAsync`.

2023-06-09 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/ReadPreference.cs
> +                    case "tagSets":
This looks unrelated. Move to another ticket?

2023-06-14 23:12 UTC, JamesKovacs requested changes
One comment was missed.

2023-06-14 23:12 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/DatabaseExistsOperation.cs
> +
Above comment needs addressing.

2023-06-15 00:58 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/DatabaseExistsOperation.cs
> +
Thanks, `BeginOperation` removed.

2023-06-15 15:18 UTC, merged