CSHARP-4665: Add LINQ3 support for IsNullOrWhiteSpace.
mongodb/mongo-csharp-driver pull request #1105
Opened 2023-06-06 00:37 UTC by rstam

2023-06-06 17:07 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsNullOrWhiteSpaceMethodToAggregationExpressionTranslatorTests.cs
> +            results.Select(x => x.R).Should().Equal(true, true, true, true, false);
AFAIK the server will always return documents in insertion order, assuming no updates after insertion that might possibly result in them being moved.

Queries might return documents in other orders if they use indexes, but when doing a simple collection scan I know of no scenarios where the server would not return documents in insertion order.

We have hundreds of tests that assume the server will return documents in insertion order (barring any exceptions mentioned above).

I don't think a cluster scenario is any different unless the collection is sharded (which this one is not).

@JamesKovacs what do you think?

2023-06-06 19:03 UTC, rstam commented
I've refactored the tests to not assume the server returns documents in insertion order.

@JamesKovacs I would like to know whether this was necessary or not?

2023-06-07 20:42 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsNullOrWhiteSpaceMethodToAggregationExpressionTranslatorTests.cs
> +            results.Select(x => x.R).Should().Equal(true, true, true, true, false);
I was going to say exactly this. Yes, except when the collection is sharded. Or the other case that Robert points out, when updates are made between the read and write. If no sort is applied, documents are returned in "natural" order, which is on-disk order. If tests start breaking because the server starts violating our ordering assumption, then we have work to do across the entire test suite to fix this. Best not to worry about this for now.

2023-06-07 20:43 UTC, JamesKovacs approved these changes
LGTM

2023-06-07 20:47 UTC, JamesKovacs requested changes
All Windows variants are failing with `path too long`. `IsNullOrWhiteSpaceMethodToAggregationExpressionTranslatorTests.cs` blows through the Windows path length limit. 😢 

Works on Linux though. 🤷

2023-06-27 23:56 UTC, JamesKovacs approved these changes
LGTM

2023-06-28 00:00 UTC, merged