CSHARP-4688: Calling queryable.First when queryable is of type IMongoQueryable<T> doesn't add { $limit : 1 } stage to pipeline.
mongodb/mongo-csharp-driver pull request #1116
Opened 2023-06-23 20:25 UTC by rstam

2023-06-23 20:25 UTC, rstam commented
This is an initial POC for just Any and First (and async versions).

If you approve of the approach we can flesh it out for the rest of the affected methods.

2023-06-23 20:34 UTC, rstam commented on src/MongoDB.Driver.Core/IAsyncCursorSource.cs
> +                return Queryable.Any(queryable);
In this case we can forward directly to `Queryable.Any` because `Queryable` is a type known to Core.

2023-06-23 20:34 UTC, rstam commented on src/MongoDB.Driver.Core/IAsyncCursorSource.cs
> +                return await queryableForwarder.AnyAsync(cancellationToken).ConfigureAwait(false);
In this case we cannot forward directly to `MongoQueryable.AnyAsync` becase this file is in Core and `MongoQueryable` is in High.

So we need an intermediate interface known to both Core and High that Core can use to forward this `AnyAsync` method to `MongoQueryable`.

Note that this intermediate interface is `internal` so we are not touching the public API.

Further note that once Core and High are merged we will no longer need this intermediate interface and will instead be able to forward directly to `MongoQueryable.AnyAsync`.

2023-06-23 20:34 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQuery.cs
> -            return executableQuery.Execute(_provider.Session, CancellationToken.None);
These changes are to ensure that all executions go through the provider which is in charge of capturing the resulting stages.

2023-06-23 20:34 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQuery.cs
> +        Task<TOutput> IMongoQueryableForwarder<TOutput>.FirstAsync(CancellationToken cancellationToken) =>  MongoQueryable.FirstAsync(this, cancellationToken);
These are the almost trivial statements forwarding calls to `MongoQueryable`.

2023-06-23 20:34 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +            return Execute(executableQuery, CancellationToken.None);
For now we default to `CancellationToken.None`.

I envision a future where a provider could be configured with a `CancellationToken` (similar to how `_options` are configurable). If that comes to pass the default would be `_cancellationToken` instead.

2023-06-23 20:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Linq3IntegrationTest.cs
> +
New helper method to make it easier to execute a query and capture the stages.

Centralizing that in this method also makes it easier to adjust to future changes in the API to capture stages (a separate PR that is also currently under discussion).

2023-06-23 20:39 UTC, rstam commented on src/MongoDB.Driver.Core/IAsyncCursorSource.cs
> +                return Queryable.Any(queryable);
Note: to handle a cancellationToken would require a change to the public API (for example, adding a new overload of `MongoQueryable.Any` that takes a `CancellationToken`).

2023-06-28 00:03 UTC, JamesKovacs approved these changes
LGTM

2023-06-28 17:17 UTC, sanych-sun requested changes
Minor changes requested

2023-06-28 19:19 UTC, sanych-sun approved these changes
LGTM

2023-06-29 16:26 UTC, merged