CSHARP-4691: Support GetType comparison in LINQ3.
mongodb/mongo-csharp-driver pull request #1118
Opened 2023-06-27 17:14 UTC by rstam

2023-06-27 17:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/GetTypeComparisonExpressionToFilterTranslator.cs
> +                }
This weird way of checking the `_t` value is to work around how MQL handles array queries.

2023-06-27 17:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/TypeIsExpressionToFilterTranslator.cs
> +                    discriminatorValue = array.Last();
We need just the last value so that we match against subclasses also (as per `is` semantics).

2023-06-27 17:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                var objectSerializer = new ObjectSerializer(discriminatorConvention, allowedTypes);
We need a custom object serializer for the `Object` property for two reasons:

1. We have to configure `AllowedTypes`
2. We have to configure the discriminator convention

If we don't configure the discriminator convention then the generated MQL will be wrong because it will be using the wrong discriminator values.

2023-06-27 17:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +            Implementation<MyActivityObject, int>();
This is a bit weird, but I wanted to use a generic method as similar as possible to the one in the JIRA ticket.

2023-06-27 17:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                    // LINQ2 filter and results are both wrong
But we're not going to fix any of the LINQ2 bugs discovered in this test.

2023-06-27 17:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                        ((TActivityObject)(object)x.Object).Id.Equals(activityId)
Double cast (with intermediate `object`) required to compile without errors.

2023-06-27 17:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +        [BsonKnownTypes(typeof(MyActivityObjectDerived))]
Without these attributes the polymorphic serialization wouldn't work.

2023-06-27 22:51 UTC, rstam commented
Added a second commit supporting GetType equals and is in aggregation expressions as well as filters.

2023-06-29 19:51 UTC, sanych-sun requested changes

2023-06-29 19:51 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/GetTypeComparisonExpressionToAggregationExpressionTranslator.cs
> +                leftExpression is MethodCallExpression methodCallExpression &&
It looks as almost exact copy of lines 34-37. Could we separate this condition into internal  method with signature like 
`bool CanConvertInternal(BinaryExpression expression, out ..., out ...)`

And call this new method from both places. So we will be sure that conditions are processed consistently.

2023-06-29 19:51 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                var objectSerializer = new ObjectSerializer(discriminatorConvention, allowedTypes);
Does it mean you will remove/mark as Ignored all this tests before merge?

2023-06-29 19:51 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                        x.Object is TActivityObject &&
Do we support "is" pattern matching? Like:
`x.Object is TActivityObject activity && activity.Id == activityId`

2023-06-29 20:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                var objectSerializer = new ObjectSerializer(discriminatorConvention, allowedTypes);
No need to. This setup doesn't alter any global state.

2023-06-29 20:34 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/GetTypeComparisonExpressionToAggregationExpressionTranslator.cs
> +                leftExpression is MethodCallExpression methodCallExpression &&
See what you think of the refactoring.

2023-06-29 20:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +                        x.Object is TActivityObject &&
This type of pattern matching is not supported in expression trees (unfortunately).

2023-06-29 20:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/GetTypeComparisonExpressionToAggregationExpressionTranslator.cs
> +            return CanTranslate(expression, out _, out _);
It kind of bothers me when I see out parameters being discarded. It makes me feel like they shouldn't have been there in the first place. But the only way to avoid it here would be to have two separate implementations of this method, one with out parameters and one without out parameters. But that defeats the whole purpose of having only a single implementation of the logic.

So throwing away the out parameters seems like the lesser evil here...

2023-06-29 21:06 UTC, sanych-sun approved these changes
LGTM

2023-06-29 21:14 UTC, merged