CSHARP-4698: Expression not supported: Regex.IsMatch
mongodb/mongo-csharp-driver pull request #1120
Opened 2023-06-28 20:03 UTC by sanych-sun

2023-06-28 22:04 UTC, rstam reviewed
Overall looks good. See minor changes requested or suggested.

2023-06-28 22:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            var query = collection.AsQueryable()
Our convention in our tests is to name this variable `queryable`.

2023-06-28 22:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            var translated = Translate(collection, query);
Our convention in our tests is to name this variable `stages`.

2023-06-28 22:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            results.Should().OnlyContain(i => Regex.IsMatch(i.A + i.B, @"\dB.*0"));
I get concerned when I see "logic" in assertions. Consider this simpler assertion instead:

     results.Select(x => x.Id).Should().Equal(2);

2023-06-28 22:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +
Extra blank line

2023-06-28 23:02 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/RegexMethod.cs
> +            if (method.Is(IsMatch))
Done

2023-06-28 23:02 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/RegexMethod.cs
> +            if (method.IsOneOf(StaticIsMatch, StaticIsMatchWithOptions))
Done

2023-06-28 23:03 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/RegexMethod.cs
> +            return false;
Done

2023-06-28 23:06 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslator.cs
> +            if (RegexMethod.IsMatchMethod(expression, out var inputExpression, out var regularExpression))
Done

2023-06-28 23:06 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslator.cs
> +                throw new ExpressionNotSupportedException(inputExpression, expression, because: $"input expression is not evaluated as a string");
Done

2023-06-28 23:07 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslator.cs
> +            return new AggregationExpression(expression, ast, new BooleanSerializer());
Done

2023-06-28 23:08 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslator.cs
> +                return Translate(context, expression, inputExpression, regularExpression);
Done

2023-06-28 23:08 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslator.cs
> +using MongoDB.Driver.Linq.Linq3Implementation.Reflection;
Done

2023-06-28 23:09 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/IsMatchMethodToFilterTranslator.cs
> +            if (RegexMethod.IsMatchMethod(expression, out var inputExpression, out var regularExpression))
Done

2023-06-28 23:10 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +﻿using System.Text.RegularExpressions;
;( Done

2023-06-28 23:11 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            var query = collection.AsQueryable()
Done

2023-06-28 23:11 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            var translated = Translate(collection, query);
Done

2023-06-28 23:12 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +
Done

2023-06-28 23:13 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/IsMatchMethodToAggregationExpressionTranslatorTests.cs
> +            results.Should().OnlyContain(i => Regex.IsMatch(i.A + i.B, @"\dB.*0"));
Done

2023-06-29 01:10 UTC, rstam requested changes

2023-06-29 01:10 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        /// Performs a regular expression pattern matching
/// Gets the regex match feature.

2023-06-29 01:10 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/IsMatchMethodToFilterTranslator.cs
> +                return Translate(context, expression, inputExpression, regex);
Do you want to inline the `Translate` method here the same as we did in the `IsMatchMethodToAggregationExpressionTranslator` file?

2023-06-29 19:19 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        /// Performs a regular expression pattern matching
Done

2023-06-29 19:21 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/IsMatchMethodToFilterTranslator.cs
> +                return Translate(context, expression, inputExpression, regex);
Done

2023-06-29 21:11 UTC, rstam approved these changes
LGTM

2023-06-30 00:23 UTC, merged