CSHARP-4695: Expression not supported: string.Concat
mongodb/mongo-csharp-driver pull request #1123
Opened 2023-06-30 18:11 UTC by sanych-sun

2023-06-30 20:33 UTC, rstam requested changes
Looks good with only some minor suggestions.

2023-06-30 20:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +            __concatWith4StringParameters = ReflectionInfo.Method((string s1, string s2, string s3, string s4) => string.Concat(s1, s2, s3, s4));
Slightly out of alphabetical order.

2023-06-30 20:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +        public static MethodInfo ConcatWith4StringParameters => __concatWith4StringParameters;
To stay consisten with our naming can you rename these to:

    ConcatWith2Strings
    ConcatWith3Strings
    ConcatWith4Strings

same with the backing fields.

2023-06-30 20:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ConcatMethodToAggregationExpressionTranslator.cs
> -            var method = expression.Method;
I like this refactoring.

2023-06-30 20:33 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/StringConcatMethodToAggregationExpressionTranslatorTests.cs
> +        public void String_concat_with_two_string_parameters_filter()
These names are fine but slightly different than what we usually use. The usual convention is something like one of the following:

    Some_scenario_should_work
    Some_scenario_should_have_expected_effect
    Some_scenario_should_return_expected_result

Applying that to this method would be something like:

    Filter_using_string_concat_with_two_strings_should_work

Let me know what you think about naming the methods in this class...

2023-06-30 20:33 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/StringConcatMethodToAggregationExpressionTranslatorTests.cs
> +                "{ '$match' : { '$expr' : { '$eq' : [{ '$concat' : ['$A', '+'] }, 'A1+'] } } }");
We usually use the fewest quotes possible to make it esaier to read:

    "{ $match : { $expr : { $eq : [{ $concat : ['$A', '+'] }, 'A1+'] } } }");

Same for other tests in this same file.

2023-06-30 20:33 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/StringConcatMethodToAggregationExpressionTranslatorTests.cs
> +                .Where(i => string.Concat(i.A, "+") == "A1+");
The use of `+` confused me a little bit here because `+` is also a string concatenation operator! :)

2023-06-30 20:45 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +            __concatWith4StringParameters = ReflectionInfo.Method((string s1, string s2, string s3, string s4) => string.Concat(s1, s2, s3, s4));
Done

2023-06-30 20:45 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +        public static MethodInfo ConcatWith4StringParameters => __concatWith4StringParameters;
Done

2023-06-30 22:15 UTC, rstam requested changes
Tiny changes suggested.

2023-06-30 22:15 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +            __concatWithStringArray = ReflectionInfo.Method((string[] s) => string.Concat(s));
These are still out of alphabetical order.

2023-06-30 22:15 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +            __concatWithStringArray = ReflectionInfo.Method((string[] s) => string.Concat(s));
Let's use the same parameter names as the used by .NET in the method signatures:

    s => values
    s1 => str0
    s2 => str1
    s3 => str2
    s4 => str3

2023-06-30 23:09 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/StringMethod.cs
> +            __concatWithStringArray = ReflectionInfo.Method((string[] s) => string.Concat(s));
Done

2023-07-03 16:26 UTC, rstam approved these changes
LGTM

2023-07-03 19:34 UTC, merged