CSHARP-4697: Expression not supported: -i.A
mongodb/mongo-csharp-driver pull request #1125
Opened 2023-06-30 22:24 UTC by sanych-sun

2023-06-30 22:49 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegationExpressionToAggregationExpressionTranslator.cs
> +    internal static class NegationExpressionToAggregationExpressionTranslator
Name file and class `NegateExpressionToAggregationExpressoinTranslator`.

Because `expression.NodeType == ExpressionType.Negate`

2023-06-30 22:49 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegationExpressionToAggregationExpressionTranslator.cs
> +                var ast = AstExpression.Multiply(operandTranslation.Ast, -1);
I would reverse the order of the arguments:

    var ast = AstExpression.Multiply(-1, operandTranslation.Ast);

Or consider whether this alternative is better/faster:

    var ast = AstExpression.Subtract(0, operandTranslation.Ast);

2023-06-30 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegationExpressionToAggregationExpressionTranslatorTests.cs
> +                .Where(i => -i.A == 10);
Instead of testing with `Where` test with `Select`.

Any filter that ends up translating to `$expr` does not need to be tested using `Where`.

2023-06-30 22:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegationExpressionToAggregationExpressionTranslatorTests.cs
> +            public int A { get; set; }
Test other data types?

Test more values at the extremes of the domain of the `Negate` function?

At the same time we don't want to slide down the slippery slope of testing the server!

2023-07-04 01:48 UTC, rstam requested changes

2023-07-04 01:48 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslator.cs
> +        private static readonly ISet<BsonType> __supportedRepresentations = new HashSet<BsonType>(
For small lists I would expect a linear search of an array to be faster.

But see below, we probably don't need this field.

2023-07-04 01:48 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslatorTests.cs
> +            results.Should().Equal(10, -5, 0, long.MaxValue, -long.MaxValue);
Probably worth using explicit long constants to be really clear about what we expect:

    results.Should().Equal(10L, -5L, 0L, long.MaxValue, -long.MaxValue);

Not sure how it's working currently exactly. There must be some magic somewhere that results in comparing `int` and `long` to work.

2023-07-04 01:48 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslatorTests.cs
> +            results.Should().Equal(10, -5, 0, float.MaxValue, -float.MaxValue);
results.Should().Equal(10F, -5F, 0F, float.MaxValue, -float.MaxValue);

2023-07-04 01:48 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslatorTests.cs
> +            public decimal Decimal { get; set; }
Can we name this property `DecimalAsString`?

2023-07-04 22:34 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslator.cs
> +                }
I've moved the logic partially: I've decided not to move the logic casting Serializer to IRepresentationConfigurable. Because current implementation is silently skipping the validation if serializer is not implementing IRepresentationConfigurable. Not sure if such approach is right for all use-cases. Please let me know what do you think about this?

2023-07-05 00:07 UTC, rstam requested changes

2023-07-05 00:07 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslator.cs
> +                }
I think it is better to call:

    SerializationHelper.EnsureRepresentationIsNumeric(expression, operandTranslation.Serializer);

We don't want to have to duplicate the `is IHasRepresentationSerializer` test everywhere.

It's OK that `EnsureRepresentationIsNumeric` is on a best-effort basis.

2023-07-05 00:07 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
> +        public static void EnsureRepresentationIsNumeric(Expression expression, Type valueType, BsonType representation)
These two methods should not be public. The only public method should be:

    public static void EnsureRepresentationIsNumeric(Expression expression, IBsonSerializer serializer)

2023-07-05 00:44 UTC, rstam requested changes

2023-07-05 00:44 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
> +        public static void EnsureRepresentationIsNumeric(Expression expression, Type valueType, BsonType representation)
nit: put in alphabetical order

2023-07-06 05:12 UTC, rstam approved these changes
LGTM with a minor comment

2023-07-06 05:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
> +            static bool IsNumericRepresentation(BsonType representation) =>
I'm not a huge fan of `=>` specially for anything that is not a one liner.

But when we do use `=>` I prefer to see it at the beginning of the next line. Things at the far right of a line tend to be harder to see.

At first glance this method appears to be missing the `{` and `}`. I have to go hunting for the `=>` to figure out that this is an expression body.

    => representation switch

2023-07-06 20:55 UTC, merged