CSHARP-4702: Recognize all Contains methods that are equivalent to Enumerable.Contains.
mongodb/mongo-csharp-driver pull request #1128
Opened 2023-07-03 23:27 UTC by rstam

2023-07-03 23:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/EnumerableMethod.cs
> +        public static bool IsContainsMethod(MethodCallExpression methodCallExpression, out Expression sourceExpression, out Expression valueExpression)
Putting this method here is analogous to how we recently put the IsMatch method in RegexMethod.cs.

2023-07-03 23:51 UTC, sanych-sun requested changes

2023-07-03 23:51 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            var lookingFor = new List<string> { "value1", "value2" };
Can we have test for at least one more collection type (for hashset for example) to ensure the code compatible not just with Lists?

2023-07-04 01:01 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/AnyWithContainsInPredicateMethodToFilterTranslator.cs
> -                methodCallExpression.Method.Is(EnumerableMethod.Contains) &&
An alternative would be to find all Contains methods that we want to support and use `method.IsOneOf`.

2023-07-04 17:26 UTC, JamesKovacs approved these changes
LGTM. I agree with @sanych-sun's comment about adding a test for another variety of `Contains`, but I'm happy to leave it to you to implement and @sanych-sun to verify.

2023-07-04 19:24 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/TypeExtensions.cs
> +        public static bool ImplementsIEnumerableOf(this Type type, Type itemType)
Renamed from previous commit.

2023-07-04 19:24 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/TypeExtensions.cs
> +                actualItemType == itemType;
Use `==` instead of `IsAssignableFrom`.

2023-07-04 19:24 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/EnumerableMethod.cs
> +            var parameters = method.GetParameters();
Base decisions on parameter types, not argument types (which might be subclasses of the parameter types).

2023-07-04 19:24 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            public HashSet<string> HashSet { get; set; }
Added tests using HashSet also.

2023-07-04 19:28 UTC, sanych-sun approved these changes
LGTM

2023-07-04 19:52 UTC, merged