CSHARP-4666: Support simple projections to a field in Find.
mongodb/mongo-csharp-driver pull request #1129
Opened 2023-07-04 23:52 UTC by rstam

2023-07-04 23:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            // { _v : '$field', _id : 0 } => { field : 1, _id : 0 } or { _id : 1 } for compatibility with older servers
By implementing this transformation here it ONLY affects `Find`

2023-07-04 23:53 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4538Tests.cs
> +            projection.Should().Be("{ D : 1, _id : 0 }");
Only two tests were affected since we limited the transformation to `Find` only.

2023-07-05 00:28 UTC, JamesKovacs requested changes
Overall looks reasonable. Minor changes requested.

2023-07-05 00:28 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4538Tests.cs
> +            projection.Should().Be("{ D : 1, _id : 0 }");
Line 30 above should no longer be necessary.

2023-07-05 00:28 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        if (Regex.IsMatch(fieldPath, @"^\$[^.$]+"))
What is the regex protecting against? If dollars or dots are present in the field name, `$getField` will be used and the outer predicates will evaluate to false. It is probably worth a guard clause that `fieldPath.StartsWith("$")`.

2023-07-05 00:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        if (Regex.IsMatch(fieldPath, @"^\$[^.$]+"))
`$x.y` is a valid field reference, but for example it references the `2` in `{ x : { y : 2 } }`

2023-07-05 21:37 UTC, JamesKovacs requested changes
Still not clear to me what the regex is protecting against. See comment.

2023-07-05 21:37 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        if (Regex.IsMatch(fieldPath, @"^\$[^.$]+"))
`{ "x.y": 1 }` is a valid `find` projection even for 4.2 and earlier as far as I recall. Plus the regex `^\$[^.$]+` matches `$x.y` because the `$x` part matches. So I'm still not understanding what the regex is protecting against.

2023-07-05 21:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        if (Regex.IsMatch(fieldPath, @"^\$[^.$]+"))
Yes, it is a valid projection as far as the server is concerned.

But the wrapped values serializer only works with fields one level deep. 

So it only works with `$x`, not with `$x.y`.

2023-07-05 21:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        if (Regex.IsMatch(fieldPath, @"^\$[^.$]+"))
Good point about the regex needing to be fixed.

2023-07-06 04:52 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +        {
Alex objected to this change offline because it does an odd transformation in an odd place in an odd domain.

It is true that it would be nice if the MQL were backward compatible in the first place, but at the point we're generating this MQL we don't know yet whether it's for a Find or not, and it would be rather invasive to try to pass that information down.

It is true that this is an odd place to be doing a transformation. We've already done all the work, and at the very last minute we pull a switcheroo. We discussed doing this in the AstFindSimplifier, but that's not quite possible because the transformation requires a serializer adjustment, and AstFindSimplifier doesn't have access to or return a serializer.

It is true that it's in an odd domain. By that I mean that we usually do our MQL generation (and transformations like simplifications) in the AST domain, and here we're working very late with MQL that has already been rendered to a BsonDocument.

I spent all day today trying to get some other approach working. I wish I hadn't.

I think in spite of the valid objections to this somewhat hacky approach we should nevertheless go with it anyway. Here are the reasons:

1. It is crystal clear that this only applies to Find
2. The changes are in this ONE place only without need to any other refactoring
3. Once server 4.4 is the minimum supported version we can remove this ONE block of code with no architectural side effects

@sanych-sun and @JamesKovacs what do you think?

2023-07-06 04:52 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                        IsFieldNamePath(wrappedValueExpression.AsString, out var fieldName))
I got rid of the regular expression and wrote a helper method instead.

https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/

2023-07-06 16:56 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +        {
I still do not like the fact that we:
1) Doing this patchwork after whole logic is done.
2) We remaster BSON document itself bypassing all existing abstractions and classes designed to compose a projection.

However I do not want to be a show-stopper if James is OK with this approach.

2023-07-06 17:43 UTC, JamesKovacs approved these changes
LGTM

2023-07-06 17:43 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +        {
Discussed in Slack. While the solution is not ideal, it is the best option available for the reasons stated above.

2023-07-06 17:48 UTC, sanych-sun approved these changes

2023-07-11 21:38 UTC, rstam commented
Closing in favor of alternate approach in https://github.com/mongodb/mongo-csharp-driver/pull/1131

2023-07-11 21:38 UTC, closed without merging