CSHARP-4360: Add log messages to SDAM spec
mongodb/mongo-csharp-driver pull request #1136
Opened 2023-07-18 02:04 UTC by BorisDog

2023-08-17 23:26 UTC, JamesKovacs requested changes
Looks good. Minor comment on logging the wrong component of a `DateTime`. See inline for details.

2023-08-17 23:26 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogTemplateProvidersSdam.cs
> +                (e, o) => GetParams(e.ConnectionId, "Server heartbeat failed", e.Awaited, (long)e.Timestamp.Millisecond, FormatCommandException(e.Exception, o)));
`e.Timestamp` returns a `DateTime`. `DateTime.Millisecond` returns the millisecond portion of the `DateTime`, which is a number between 0 and 999. I don't think this is what you're looking for.

2023-08-18 22:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogTemplateProvidersSdam.cs
> +                (e, o) => GetParams(e.ConnectionId, "Server heartbeat failed", e.Awaited, (long)e.Timestamp.Millisecond, FormatCommandException(e.Exception, o)));
Good catch, thanks!
I had marked this as TODO, and forgot. Added `Duration` field.

2023-08-22 22:08 UTC, JamesKovacs approved these changes
LGTM

2023-08-31 15:35 UTC, merged