CSHARP-4723: Linq V2 Projection when upgrading from 2.19.1 to 2.19.2
mongodb/mongo-csharp-driver pull request #1144
Opened 2023-07-31 17:04 UTC by sanych-sun

2023-07-31 18:19 UTC, rstam requested changes

2023-07-31 18:19 UTC, rstam commented on src/MongoDB.Driver/IFindFluentExtensions.cs
> +            return find.Project<TNewProjection>(new FindExpressionProjectionDefinition<TDocument, TNewProjection>(projection));
This is the change I was expecting.

In *this* case we *know* the projection will be used with a `Find`.

2023-07-31 18:19 UTC, rstam commented on src/MongoDB.Driver/ProjectionDefinitionBuilder.cs
> +            return new FindExpressionProjectionDefinition<TSource, TProjection>(expression);
This doesn't seem right.

In this case we *don't* know whether the projection will be used with `Find` until it is actually used.

2023-08-01 17:42 UTC, rstam approved these changes
LGTM

2023-08-02 03:12 UTC, rstam requested changes

2023-08-02 03:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            if (typeof(TSource) == typeof(TProjection)
Comparing types is redundant because they will always be equal for `x => x`.

This PR seems to overlap with the discussions we are having on Slack.

2023-08-02 03:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                && expression.Body == expression.Parameters.First())
`[0]` is often more efficient than `First()`.

2023-08-02 03:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            if (typeof(TSource) == typeof(TProjection)
Note: this check should probably be in `TranslateExpressionToProjection` instead of here, as per discussions in Slack.

2023-08-02 15:49 UTC, rstam commented
Let's focus on the PR for CSHARP-4681 first. This PR might no longer be necessary once we merge that PR.

2023-08-02 19:10 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +            if (typeof(TSource) == typeof(TProjection)
This code was done in scope of another PR.

2023-08-02 19:17 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/LinqProviderAdapterV3.cs
> +                && expression.Body == expression.Parameters.First())
This code was done in scope of another PR.

2023-08-02 19:35 UTC, rstam approved these changes
LGTM

2023-08-02 20:58 UTC, merged