CSHARP-4734: Throw an exception when an aggregation style projection is used with Find on servers prior to 4.4.
mongodb/mongo-csharp-driver pull request #1147
Opened 2023-08-01 17:25 UTC by rstam

2023-08-01 19:07 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4734Tests.cs
> +            if (Feature.FindProjectionExpressions.IsSupported(wireVersion))
I would prefer to have 2 separate tests with ignore condition: one that is run on "newer servers" and expecting results, another that is run on "older servers" and expecting exception. Because we testing to different outputs, not just a slightly different generated MQL, but totally different behavior.

2023-08-01 19:18 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +            if (_projection != null && !Feature.FindProjectionExpressions.IsSupported(connectionDescription.MaxWireVersion))
Because `MaxWireVersion` is what determines what the server supports.

`MinWireVersion` determines which older drivers the server can talk to.

2023-08-01 19:18 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                return value.BsonType switch
The whole point of this PR is to throw an exception when a projection like `{ x : '$x' }` is run on an older server. What we do NOT want to do is silently return the wrong value.

Note that this is *different* from supporting `x => x.F` in LINQ.

2023-08-01 19:18 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4734Tests.cs
> +            if (Feature.FindProjectionExpressions.IsSupported(wireVersion))
I hear you... and would almost always agree with you.

But what I'm trying to avoid here is having to duplicate the `InlineData` test cases and the setup.

I think a situation like this is an OK exception. These are the exact same tests... even though different server versions affect the results.

It's analogous to how we run many LINQ tests for both V2/V3 and *sometimes* have different assertions for V2 and V3 (sometimes including that V2 throws and V3 does not). We're just trying to avoid duplicating the whole test case setup.

2023-08-01 19:18 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                return value.BsonType switch
Hmmm... perhaps you are making a subtle distinction between `{ x : "$x" }` vs `{ x : "$y" }`?

I still think I'd rather be consistent and say that variable references should throw exceptions prior to 4.4

2023-08-01 19:25 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                return value.BsonType switch
Yes, the idea of the comment was that projection like `{ x : "$x" }` is returning proper results today. So we might dot not want to break it in the upcoming version.

2023-08-01 19:27 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4734Tests.cs
> +            if (Feature.FindProjectionExpressions.IsSupported(wireVersion))
We could use MemberData to avoid duplicating of code, but I'm not insist.

2023-08-01 19:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +            if (_projection != null && !Feature.FindProjectionExpressions.IsSupported(connectionDescription.MaxWireVersion))
This is actually a confusing area.

What *actually* determines whether a feature is supported is the server *VERSION*, but the server team considers knowing the server version a security risk. So we have to use `MaxWireVersion` is an *approximation* of the server version.

As originally envisioned the `MaxWireVersion` would only change when the wire protocol changes. It has since evolved to basically be incremented with every major or minor server version.

2023-08-01 19:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                return value.BsonType switch
I'm leaning towards throwing an exception on ANY variable reference, without making an exception for this very weird edge case.

2023-08-01 19:43 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                return value.BsonType switch
Agree that simple and consistent behavior is preferable one. But end-user does not  generate MQL on their end in most cases, driver does it somewhere behinds the scene. Are we sure we never generate such projection?

2023-08-02 17:28 UTC, sanych-sun requested changes

2023-08-02 17:28 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private void EnsureProjectionIsSupportedPriorTo44(BsonDocument projection)
I do not like the fact that we mentioned server version in the method name instead of functionality. Do you think `EnsureProjectionSupportedByQueryLanguage` might works better here?

2023-08-02 17:53 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private void EnsureProjectionIsSupportedPriorTo44(BsonDocument projection)
Discussed offline.

2023-08-02 19:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
>          public BsonDocument CreateCommand(ConnectionDescription connectionDescription, ICoreSession session)
Good catch. Done.

2023-08-02 19:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private void EnsureProjectionIsSupportedPriorTo44(BsonDocument projection)
Moved to a helper class and renamed to `ThrowIfAggregationExpressionIsUsedWhenNotSupported`.

2023-08-02 19:37 UTC, sanych-sun approved these changes
LGTM

2023-08-03 15:43 UTC, merged