CSHARP-4477: Implement embeddedDocuments operator in Atlas Search
mongodb/mongo-csharp-driver pull request #1155
Opened 2023-08-08 19:54 UTC by BorisDog

2023-08-08 22:19 UTC, sanych-sun requested changes

2023-08-08 22:19 UTC, sanych-sun commented on src/MongoDB.Driver/Search/SearchDefinitionRenderContext.cs
> +    public sealed class SearchDefinitionRenderContext<TDocument>
Do you think we can implement SearchDefinitionRenderContext as a record with init-only properties and then utilize non-destructive mutation approach by using `with` statement to create a shallow copy of the context?

2023-08-08 22:19 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +                "{ embeddedDocument: { path : 'x', operator : { compound : { must : [{ text : { query : '1', path : 'x.y' } }], should : [{ exists : { path : 'x.z' } }] } }}}");
Minor: missed spaces between curly brackets (here and some below)

2023-08-08 22:19 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchPathDefinitionBuilderTests.cs
> +                "basepath");
Do we have any tests for more complex basepath? Like "root.nested".

2023-08-08 23:38 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchPathDefinitionBuilderTests.cs
> +                "basepath");
Good point, added in SearchDefinitionBuilderTests and SearchPathDefinitionBuilderTests

2023-08-08 23:38 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        public abstract BsonDocument Render(SearchDefinitionRenderContext<TDocument> renderContext);
Yes.

2023-08-09 16:04 UTC, sanych-sun approved these changes
LGTM

2023-08-09 19:48 UTC, merged