CSHARP-4748: ContainsKey throws an exception when key is not a string but is serialized as a string.
mongodb/mongo-csharp-driver pull request #1159
Opened 2023-08-10 00:39 UTC by rstam

2023-08-10 00:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsKeyMethodToAggregationExpressionTranslator.cs
> +            if (keyExpression is ConstantExpression keyConstantExpression)
This feels like it might be a workaround to a failure of the known serializer finder, but I'm not sure. What do you all think?

2023-08-10 00:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/ContainsKeyMethodToFilterTranslator.cs
> -                return (string)keyConstantExpression.Value;
Two problems here:

1. If it throws an `InvalidCastException` that's not very helpful
2. It's not using the key serializer

2023-08-10 00:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/ContainsKeyMethodToFilterTranslator.cs
> +                if (serializedKeyValue.BsonType == BsonType.String)
What matters is not if the key is a string, but whether it is represented as a string.

2023-08-16 18:42 UTC, sanych-sun requested changes

2023-08-16 18:42 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsKeyMethodToAggregationExpressionTranslator.cs
> +            var keyRepresentation = keySerializer switch
What the advantage of switch here instead of if that is more readable at least for me?
`if (keySerializer is IRepresentationConfigurable representationConfigurable)`

2023-08-16 18:42 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsKeyMethodToAggregationExpressionTranslator.cs
> +                _ when keySerializer is IRepresentationConfigurable representationConfigurable => representationConfigurable.Representation,
I suppose we have to work with `IHasRepresentationSerializer` interface here instead. As we do not checking whether it could be configured, but rather want to know if serializer provides representation information.

2023-08-16 18:42 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4748Tests.cs
> +            public String Id { get; set; }
Minor: I suppose we prefer to use c# `string` alias rather then dotnet `String` type.

2023-08-16 18:42 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4748Tests.cs
> +            public String Service { get; set; }
Do we need those extra properties?

2023-08-16 18:42 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4748Tests.cs
> +            AssertStages(stages, "{ $match : { 'Languages.en' : { $exists : true } } }");
Do we want to execute the queryable and validate the output?

2023-08-16 23:10 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4748Tests.cs
> +            AssertStages(stages, "{ $match : { 'Languages.en' : { $exists : true } } }");
Done

2023-08-16 23:10 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4748Tests.cs
> +            public String Service { get; set; }
Nope

2023-08-17 00:06 UTC, sanych-sun approved these changes
LGTM

2023-08-17 01:00 UTC, merged