Proof of concept for supporting compound primary keys in LINQ with the EF Core Provider.
mongodb/mongo-csharp-driver pull request #1161
Opened 2023-08-16 18:50 UTC by rstam

2023-08-16 18:51 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        public static BsonSerializationInfo CreateWithPath(IEnumerable<string> elementPath, IBsonSerializer serializer, Type nominalType)
Adding a new public constructor was a breaking change so I added a new static factory method instead.

Note: a new public constructor resulted in compile time ambiguity when called with `null` as the first argument.

2023-08-16 18:52 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +            get { return _elementPath?.Single(); }
One advantage of using `Single` here is that whenever LINQ2 calls this property it will throw an exception if the member is grouped under a nested path. That's far better than silently doing the wrong thing.

2023-08-16 18:52 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        [Obsolete("This method is no longer relevant because field names are now allowed to contain dots.")]
We never call this method.

Should we delete it? Technically that's a breaking change, but the method no longer works reliably anyway since the server now allows `.` in element names.

2023-08-16 18:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/MemberSerializationInfo.cs
> +        public MemberSerializationInfo(IReadOnlyList<string> elementPath, IBsonSerializer serializer)
This is an internal class so this is not a publicly breaking change.

2023-08-16 18:54 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberExpressionToAggregationExpressionTranslator.cs
> +            return new AggregationExpression(expression, subField, serializationInfo.Serializer);
This is a relatively simple change. We just need to call `GetField` more than once when there is a path.

If the path list has count == 1 this code is equivalent to the previous code.

2023-08-16 18:55 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ToFilterFieldTranslators/MemberExpressionToFilterFieldTranslator.cs
> +                return subField;
Same as above but this time for filters.

I'm surprised I only found TWO places that needed to be changed. Hope I didn't miss any.

2023-08-16 18:56 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +            var serializedOrderItem = "{ _id : { OrderId : 1, ProductId : 2 }, Quantity : 3 }";
Note that `OrderId` and `ProductId` are grouped under the `_id` element.

2023-08-16 18:56 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +                AssertStages(stages, "{ $project : { _v : '$_id.OrderId', _id : 0 } }");
Note that the use of `$_id.OrderId` instead of `$OrderId`.

2023-08-16 18:57 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +        private class OrderItemsSerializer : ClassSerializerBase<OrderItem>, IBsonDocumentSerializer
This is for testing.

We would implement similar code in the `EntitySerializer`.

2023-08-16 18:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +            public bool IsGroupedMember(string name, out string groupElementName)
Oops this method is obsolete. Ignore it. It was when I was experimenting with a new interface instead.

2023-08-16 19:28 UTC, sanych-sun requested changes

2023-08-16 19:28 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        private readonly IReadOnlyList<string> _elementPath;
I would suggest to have both: `_elementPath` and `_elementName`. We can use _elementName for situation when there is a single element path. And switch to the _elementPath in that rare case when there are multiple. It could save some allocations.

2023-08-16 19:28 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +            get { return _elementPath?.Single(); }
Agree with the fact that we want to throw here. But I think we have to throw something more readable rather that just "Sequence contains more then one element".

2023-08-16 19:28 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ToFilterFieldTranslators/MemberExpressionToFilterFieldTranslator.cs
> +                return subField;
What about:
SelectMethodToFilterFieldTranslator line 47

2023-08-16 19:44 UTC, JamesKovacs requested changes
Straightforward and reasonable approach. Minor comments inline.

2023-08-16 19:44 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        public IReadOnlyList<string> ElementPath
Given this is a collection of paths, shouldn't this be `ElementPaths`?

2023-08-16 19:44 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +        [BsonSerializer(typeof(OrderItemsSerializer))]
So it is the responsibility of `OrderItemsSerializer` to configure the composite `_id`. If we agree on this path forward, it would be useful to allow specification of multiple `[BsonId(Order=N)]` attributes as well as `BsonClassMap<T>` configuration.

2023-08-16 20:05 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        private readonly IReadOnlyList<string> _elementPath;
I guess a related question is: do we need a variable length path at all?

Is it sufficient to only support a single level of nesting?

2023-08-16 20:24 UTC, JamesKovacs reviewed
See comments inline.

2023-08-16 20:24 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        [Obsolete("This method is no longer relevant because field names are now allowed to contain dots.")]
While I agree that the inclusion of `.` in element names breaks this method, that is not a mainline use case. This method works for the common case of element names without `.`. We can make the breaking change in 3.0.0, but not in a 2.X release IMHO.

2023-08-16 20:24 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        public IReadOnlyList<string> ElementPath
OK.

2023-08-16 20:24 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharpxxxxTests.cs
> +        [BsonSerializer(typeof(OrderItemsSerializer))]
I agree that the most common use case is for EF Core, but it would be surprising for EF Core to write data that the driver cannot interoperate with.

2023-08-16 20:27 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        [Obsolete("This method is no longer relevant because field names are now allowed to contain dots.")]
I'm not proposing we make any changes to this method.

I'm merely pointing out that it's already broken, and that we don't use it.

Although I do wish we could just delete it.

2023-08-16 20:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        private readonly IReadOnlyList<string> _elementPath;
I've pushed a commit that has mutually exclusive `_elementName` and `_elementPath` to reduce allocations.

Note the changes in the users of this class that now have to check whether `ElementPath` is `null` or not and only use `ElementName` when there is no `ElementPath`.

2023-08-16 21:51 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ToFilterFieldTranslators/MemberExpressionToFilterFieldTranslator.cs
> +                return subField;
I think we can ignore this one for now.

If it ever gets used when a path is involved the call to `ElementName` will throw an exception and we can deal with it then.

2023-08-17 16:23 UTC, closed without merging

2023-08-17 16:23 UTC, rstam commented
Moving to a new PR now that we have a JIRA ticket number:

https://github.com/mongodb/mongo-csharp-driver/pull/1161