CSHARP-4757: Modify BsonSerializationInfo to handle properties that are grouped in a nested document.
mongodb/mongo-csharp-driver pull request #1163
Opened 2023-08-17 16:22 UTC by rstam

2023-08-18 18:35 UTC, sanych-sun approved these changes
LGTM + there might be more code we need to improve with the ElementPath property knowledge, but I suppose it could be done on-demand.

2023-08-23 23:13 UTC, JamesKovacs requested changes
Let me know what you think about only storing `_elementPath` and eliminating the branch logic based on whether `ElementPath` is null.

2023-08-23 23:13 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +                return _elementName;
`return _elementPath[0];`

This eliminates the need for the `_elementName` field.

2023-08-23 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/MemberSerializationInfo.cs
> +        private readonly IReadOnlyList<string> _elementPath;
Here we could always use `_elementPath` and eliminate the branching logic.

2023-08-23 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MemberExpressionToAggregationExpressionTranslator.cs
> +            }
This code block could be simplified to iterate over `ElementPath`, which for the common case would only contain a single string.

2023-09-01 00:15 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializationInfo.cs
> +        [Obsolete("This method is no longer relevant because field names are now allowed to contain dots.")]
I would like to argue in favor of removing this method even though it is public.

The method makes little sense and probably doesn't even work as intended. If we don't remove it then it seems like we would have to commit to fixing it.

2023-09-01 16:04 UTC, sanych-sun approved these changes
LGTM

2023-09-08 00:09 UTC, JamesKovacs approved these changes
LGTM. Discussed via Slack and Zoom. Maintaining both `_elementPath` and `_elementName` avoids an extra allocation of an array as the mainline use case only has a single `_elementName`.

2023-09-14 17:54 UTC, merged