CSHARP-4772: Add support for List<T>.Exists and Array.Exists<T> in LINQ3.
mongodb/mongo-csharp-driver pull request #1171
Opened 2023-08-31 23:58 UTC by rstam

2023-09-01 00:01 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +                var exception = Record.Exception(() => Translate(collection, queryable));
A number of these scenarios are not supported by LINQ2.

2023-09-01 00:01 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +            }
The MQL is different between LINQ2 and LINQ3 but I believe both of them to be correct.

2023-09-01 16:15 UTC, sanych-sun requested changes

2023-09-01 16:15 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +                var exception = Record.Exception(() => Translate(collection, queryable));
Should we check the exception somehow? If now, why do we even need LINQ2 provider here?

2023-09-01 16:15 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +                var exception = Record.Exception(() => Translate(collection, queryable));
Same here. We should either check the exception if it's expected one, or remove LINQ2 code at all.

2023-09-01 16:15 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +                    ProfilesArray = new Profile[] { new Profile { OrganizationIdsArray = new int[] { 2 } } },
Should we add tests with empty and null arrays and lists?

2023-09-01 17:56 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +                    ProfilesArray = new Profile[] { new Profile { OrganizationIdsArray = new int[] { 2 } } },
I've added more test data.

2023-09-05 21:56 UTC, sanych-sun approved these changes
LGTM

2023-09-11 23:38 UTC, JamesKovacs approved these changes
LGTM

2023-09-11 23:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +            }
Agreed that they are equivalent.

2023-09-14 17:58 UTC, merged