CSHARP-4747: Add support for $set stage.
mongodb/mongo-csharp-driver pull request #1172
Opened 2023-09-07 01:11 UTC by rstam

2023-09-14 22:30 UTC, JamesKovacs requested changes
Overall this looks fantastic. I think it would be useful to add integration tests to all the test cases.

One design question came to mind... I was expecting that `Set(x => new {})`, `Set(x => new C())`, and `Set(x => new C(x))` would all result in an empty `{ $set : { } }` stage, but they failed with `ExpressionNotSupportedException`. Given that there isn't an easy way in C# to dynamically build a ctor with or without member initializers, I think it's fine to throw but wanted to raise it as a discussion point. Is there a use case where supporting a potentially empty `$set` would be beneficial?

2023-09-26 18:30 UTC, sanych-sun approved these changes
LGTM + minor comments

2023-09-26 18:30 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            newExpression = expression.Body as NewExpression;
Should we reset the `newExpression` value in case test in next line evaluates to `false`?

2023-09-26 18:30 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +                var constructor = memberInitExpression.NewExpression.Constructor;
As far as I remember, `NewExpression.Constructor` could be null in case default constructor for struct is used.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/LinqProviderAdapter.cs
> +        internal abstract BsonDocument TranslateExpressionToSetStage<TDocument, TOutput>(
I changed the return type from AstStage to BsonDocument because I don't want the AST types to leak out of the LINQ3 implementation classes.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +        private static AstStage TranslateNewWithOptionalMemberInitializers(TranslationContext context, IBsonDocumentSerializer documentSerializer, MemberInitExpression memberInitExpression)
Renamed method to indicate member initializers are optional.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            if (expression.Body is NewExpression tempNewExpression &&
Refactored to make sure out variable is not prematurely set. (This is better than letting it be prematurely set and having to reset it).

James: this is in response to Alex requesting that all out variables be null when returning false.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            if (expression.Body is MemberInitExpression tempMemberInitExpression)
Refactored to make sure out variable is not prematurely set. (This is better than letting it be prematurely set and having to reset it).

James: this is in response to Alex requesting that all out variables be null when returning false.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            if (members != null)
Members are optional.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            if (memberInitExpression != null)
Member initializers are optional.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/SetFieldDefinitions.cs
> +                document[renderedSetFieldDefinition.Name] = renderedSetFieldDefinition.Value; // if same element name is set more than once last one wins
This is a change from previous commits.

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/SetFieldDefinitionsBuilder.cs
> +    public static class ListSetFieldDefinitionsExtensions
Fixed the class name (was `SetFieldDefinitionsExtensions` in previous commit).

2023-10-03 00:20 UTC, rstam commented on src/MongoDB.Driver/SetFieldDefinitionsBuilder.cs
> +        internal static ListSetFieldDefinitions<TDocument> Set<TDocument>(this ListSetFieldDefinitions<TDocument> fields, SetFieldDefinition<TDocument> setFieldDefinition)
Made `internal` (was `public` in previous commits).

2023-10-03 00:20 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4747Tests.cs
> +            AssertStages(stages, "{ $set : { X : 2 } }");
Done.

2023-10-03 00:20 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4747Tests.cs
> +    public class CSharp4747Tests : Linq3IntegrationTest
Lots of changes in this file. I'm not going to comment on every one.

2023-10-03 19:56 UTC, sanych-sun approved these changes
LGTM

2023-10-05 16:54 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToSetStageTranslators/ExpressionToSetStageTranslator.cs
> +            if (expression.Body is NewExpression tempNewExpression &&
SGTM

2023-10-05 22:01 UTC, rstam commented
Pushed a new commit to skip tests on older servers.

2023-10-05 23:58 UTC, JamesKovacs approved these changes
LGTM

2023-10-06 00:09 UTC, merged