CSHARP-4566: Support widening numeric and nullable-numeric conversions.
mongodb/mongo-csharp-driver pull request #1176
Opened 2023-09-14 23:08 UTC by rstam

2023-09-14 23:14 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/BinaryExpressionToAggregationExpressionTranslator.cs
> -
We now have code to translate these `Convert`s and no longer want to remove them.

2023-09-14 23:14 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4596Tests.cs
> +    public class CSharp4596Tests : Linq3IntegrationTest
Note that this PR fixes CSharp4596 also. That ticket was also related to numeric conversions, which this PR addresses.

2023-09-14 23:14 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4596Tests.cs
> +        public void Test_widening_expressions()
This tests can be removed. It's just experimenting to make sure all these conversions are compiled to a single `ConvertExpression`.

2023-09-14 23:14 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableIntComparedToDoubleWithStringRepresentationTests.cs
> -        [InlineData(1.5, "{ \"I\" : \"1.5\" }")]
I would argue that this translation was questionable. What we actually want to do is pass the value to the underlying serializer, and in this case `1.5` can't be converted to an `Int32` (without loss) to pass to the underlying `Int32Serializer`.

2023-09-15 00:07 UTC, JamesKovacs reviewed
Overall looks great. (So many test cases!) :) Just a question about widening converts and then I'll LGTM this.

2023-09-15 00:07 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableIntComparedToDoubleWithStringRepresentationTests.cs
> -        [InlineData(1.5, "{ \"I\" : \"1.5\" }")]
Agreed.

2023-09-15 00:25 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> -            (typeof(double), typeof(decimal))
Because I wasn't sure they actually are widening converts.

Maybe float -> double should stay.

Possibly the other two as well. Let's think about it...

2023-09-19 17:17 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> -            (typeof(double), typeof(decimal))
The C# language does not have implicit conversions from `float` or `double` to `decimal`.

I think the reason it does not is that these conversions are not guaranteed to be lossless. Widening conversions are supposed to be lossless.

2023-09-28 16:53 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> -            (typeof(double), typeof(decimal))
`float` to `double` is definitely a lossless widening convert. We should add that back in. Agreed that `float` or `double` to `decimal` in not guaranteed to be lossless and you need a cast to assign a `decimal` to a `float`/`double`. Users probably already have those casts in their LINQ expressions to make the C# compiler happy. I'm ok with removing those. But let's keep `float` to `double`.

2023-09-28 16:53 UTC, JamesKovacs requested changes
See my comment about adding the `float` to `double` widening convert back in.

2023-09-28 16:55 UTC, JamesKovacs approved these changes
LGTM

2023-09-28 16:55 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> -            (typeof(double), typeof(decimal))
Oh, my bad. You didn't remove `float` to `double`. The line just got modified. LGTM.

2023-10-06 00:19 UTC, sanych-sun approved these changes
LGTM + minor comment

2023-10-06 00:19 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/MongoQueryableIntComparedToDoubleWithStringRepresentationTests.cs
> +                exception.Message.Should().Contain("The constant 1.5 could not be converted to Int32 in order to be serialized using the proper serializer");
Minor: `1.5` should not be hardcoded here, but built based on parameter value.

2023-10-06 00:45 UTC, merged

2023-10-28 17:03 UTC, rstam commented
Note: even thought the status of this PR is "Merged" it was later reverted when some remaining issues with it were discovered.