CSHARP-4722: Add durations to connection pool events
mongodb/mongo-csharp-driver pull request #1177
Opened 2023-09-15 17:46 UTC by adelinowona

2023-09-27 15:52 UTC, BorisDog requested changes
Few minor comments

2023-09-27 18:17 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                Stopwatch stopwatch = new();
Minor: we could save a little on allocations by using the following technic:
capture `Stopwatch.GetTimestamp()` before the measured code
 and compare it to the timestamp after and convert diffrence from ticks to ms.

2023-09-28 16:21 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                Stopwatch stopwatch = new();
In this particular case, I think it may be overkill since the previous version of the code was also allocating a new stopwatch under the cover so I am not really adding anything.  However, I like the savings on allocations (even though they may be very small) from this technique but I would advocate that if we do that here, then we might as well do it in other places where we use a stopwatch to save on allocations there too and maintain uniformity in the code. This may be good for quick wins ticket for the future though. Let me know what you think.

2023-09-29 20:45 UTC, sanych-sun approved these changes
LGTM

2023-10-03 20:17 UTC, BorisDog approved these changes
LGTM

2023-10-04 19:58 UTC, merged