CSHARP-4781: DefaultIfEmpty using wrong default value.
mongodb/mongo-csharp-driver pull request #1178
Opened 2023-09-19 00:44 UTC by rstam

2023-09-19 01:12 UTC, rstam commented on src/MongoDB.Driver/Support/ReflectionExtensions.cs
> +            return genericMethod.Invoke(null, null);
This change *might* not actually be needed, but I wanted a way to *actually* use `default(TValue)` to be 100% sure I was getting the right default value for all types.

2023-09-19 16:06 UTC, JamesKovacs requested changes
Some dead code in tests needs to be removed. As well have we verified that this fix resolves the `$unwind` issue reported in CSHARP-4781?

2023-09-19 16:06 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4781Tests.cs
> +            var client = new MongoClient(settings);
`settings` and `client` are unused.

2023-09-19 16:06 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4781Tests.cs
> +            var client = new MongoClient(settings);
`settings` and `client` are unused.

2023-09-25 22:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4781Tests.cs
> +            var client = new MongoClient(settings);
Oops. Copy/paste leftovers. Removed.

2023-09-25 22:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4781Tests.cs
> +            var client = new MongoClient(settings);
Removed.

2023-09-25 23:09 UTC, JamesKovacs approved these changes
LGTM

2023-09-25 23:17 UTC, sanych-sun approved these changes
LGTM

2023-09-25 23:49 UTC, merged