CSHARP-4789: MongoUrlBuilder builds urls with invalid query string fo…
mongodb/mongo-csharp-driver pull request #1179
Opened 2023-09-21 22:07 UTC by adelinowona

…rmat

2023-09-21 22:36 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            _originalConnectionString = Ensure.IsNotNull(connectionString, nameof(connectionString)).Replace(';', '&');
I don't know about this... if the user chose to use `;` instead of `&` who are we to replace it?

But maybe it makes sense to normalize their non-standard choice.

In that case I worry about the `Replace` being too broad. Are we sure there aren't sometimes instances of `;` that should *not* be replaced?

For example, what if the password contains `;`?

2023-09-22 19:19 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            _originalConnectionString = Ensure.IsNotNull(connectionString, nameof(connectionString)).Replace(';', '&');
Agreed, we shouldn't normalize the user's non-standard choice.

2023-09-26 17:17 UTC, JamesKovacs requested changes
Overall looks good. Just need to switch our tests to use `&` by default rather than `;` and thus eliminate the need to call `Replace`.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +                var expectedConnectionString = connectionString.Replace(';', '&');
Rather than bulk replacing `;` with `&`, we should update the tests to use `&` as that is now our default representation.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +            var expectedConnectionString = connectionString.Replace(';', '&');
Since `connectionString` contains no `;`, `Replace` is a NOP and not necessary.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
>                  var @params = compressionProperty.Split(';');
Rather than splitting on `;`, we should use `&` in our tests and split on those when needed.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +            var expectedConnectionString = canonicalConnectionString.Replace(';', '&');
Use `&` in tests.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +            var expectedConnectionString = connectionString.Replace(';', '&');
Same here. Use `&` in tests.

2023-09-26 17:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlTests.cs
> +                var expectedConnectionString = connectionString.Replace(';', '&');
And here.

2023-09-28 17:02 UTC, JamesKovacs approved these changes
LGTM

2023-10-03 14:11 UTC, merged