CSHARP-4778: Add synonym support to text operator for Atlas Search
mongodb/mongo-csharp-driver pull request #1186
Opened 2023-09-27 19:32 UTC by adelinowona

2023-09-29 01:08 UTC, BorisDog requested changes
Looks great overall! Some changes requested.

2023-09-29 01:08 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +
minor: remove extra blank line.

2023-09-29 01:08 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            Assert.False(vesselSearchResults.SequenceEqual(sailSearchResults));
`AtlasSearchTests` are more like a smoke tests, and they don't have to be exhaustive. It's usually single test method per parameter. Let's try to think how to compress those test cases into single method or two.

2023-09-29 01:08 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +                .Must(subject.Text("y", "1", "testSynonyms"))
Move synonym tests to `Text` and `Text_typed` (instead of `Emebedded`)

2023-10-03 19:44 UTC, sanych-sun approved these changes
LGTM + minor comment

2023-10-03 19:44 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            Assert.True(automobileAndAtttireSearchResults.SequenceEqual(vehicleAndDressSearchResults));
Should we use fluent assertions here?

2023-10-03 20:37 UTC, BorisDog requested changes

2023-10-03 20:37 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                { "synonyms", () => new BsonString(_synonyms), _synonyms != null }
`{ "synonyms", _synonyms, _synonyms != null }` should also work.

2023-10-03 20:37 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            new TextSearchDefinition<TDocument>(path, query, null, score, synonyms);
Match indentation of other overloads.

2023-10-03 20:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +                    .Single();
We should use Single directly. `Limit(1).Single()`
Also in the old code as well.

2023-10-03 20:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            var automobileAndAtttireSearchResults = SearchMultipleSynonymMapping(
`automobileAndAttireSearchResults`

2023-10-04 15:28 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            Assert.True(automobileAndAtttireSearchResults.SequenceEqual(vehicleAndDressSearchResults));
Agreed, helps keep consistency in tests. Thanks!

2023-10-04 20:28 UTC, BorisDog approved these changes
LGTM

2023-10-05 19:00 UTC, merged