CSHARP-4768: Introduce $vectorSearch aggregation stage
mongodb/mongo-csharp-driver pull request #1187
Opened 2023-09-29 00:46 UTC by BorisDog

2023-10-03 15:12 UTC, adelinowona reviewed
LGTM + minor comments

2023-10-03 19:31 UTC, sanych-sun requested changes

2023-10-03 19:31 UTC, sanych-sun commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +        /// <returns>The stage.</returns>
Xml docs for parameters are missed.

2023-10-03 19:31 UTC, sanych-sun commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            int limit,
Should we validate `limit` parameter's value?

2023-10-03 19:31 UTC, sanych-sun commented on src/MongoDB.Driver/VectorSearchQueryVector.cs
> +                bsonWriter.WriteDouble(span[i].ToDouble(null));
Should we use `QueryVectorBsonArray<T>.Values` property here instead to localize all convertion logic there?

2023-10-03 19:31 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/VectorSearchQueryVectorTests.cs
> +                new object[] { () => (VectorSearchQueryVector)(new[] { 1.1, 2.2 }), ToBsonArray(new[] { 1.1, 2.2 }) },
Just curious: why should we provide Func<> as a test data? Cannot we provide created VectorSearchQueryVector or double-arrays?

2023-10-04 18:48 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                    var vectorSearchOperator = new BsonDocument()
Thanks!

2023-10-04 18:48 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            int limit,
Yes, done.

2023-10-04 18:48 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +        /// <returns>The stage.</returns>
Thanks, fixed.

2023-10-04 18:48 UTC, BorisDog commented on src/MongoDB.Driver/VectorSearchQueryVector.cs
> +                bsonWriter.WriteDouble(span[i].ToDouble(null));
Could be a good idea, but we want to skip allocation for `BsonDouble` in `.Values` (it's implicit allocation)

2023-10-04 18:48 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/VectorSearchQueryVectorTests.cs
> +                new object[] { () => (VectorSearchQueryVector)(new[] { 1.1, 2.2 }), ToBsonArray(new[] { 1.1, 2.2 }) },
Technically we can, but original idea was to test the implicit conversion action itself.
If providing `VectorSearchQueryVector` the conversion failures will be caught not as part of test cases.

2023-10-04 18:48 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +        public void VectorSearch_should_add_expected_stage_with_floats_vector()
Discussing offline.

2023-10-04 19:12 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/VectorSearchQueryVectorTests.cs
> +                new object[] { () => (VectorSearchQueryVector)(new[] { 1.1, 2.2 }), ToBsonArray(new[] { 1.1, 2.2 }) },
Discussed offline.

2023-10-04 19:51 UTC, sanych-sun approved these changes
LGTM

2023-10-04 20:05 UTC, adelinowona approved these changes
LGTM

2023-10-04 23:42 UTC, JamesKovacs requested changes
Minor feedback. Plus consider Robert's idea of supporting casts from `IEnumerable<T>` to `QueryVector`.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// A new pipeline with an additional stage.
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// A new pipeline with an additional stage.
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// A new pipeline with an additional stage.
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// </returns>
Formatting. Most others have it on a single line.

2023-10-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver/VectorSearchQueryVector.cs
> +    public sealed class VectorSearchQueryVector
`VectorSearchQueryVector` reads like `Vector---Vector` to me. Having `Vector` at both ends of the class name sounds strange to my ear. Is there any ambiguity - either in our API or in C# - if we call it `QueryVector`?

2023-10-05 01:10 UTC, BorisDog commented on src/MongoDB.Driver/VectorSearchQueryVector.cs
> +    public sealed class VectorSearchQueryVector
Thanks, changed to `QueryVector`.

2023-10-05 16:53 UTC, JamesKovacs approved these changes
LGTM

2023-10-05 17:17 UTC, rstam requested changes

2023-10-05 17:17 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                options);
This formatting makes it very hard to tell that there is `=>` involved. 

Maybe format with `=>` at the beginning of an indented line instead of semi-hidden at the end of a line?

2023-10-05 17:17 UTC, rstam commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// <returns>A new pipeline with an additional stage.</returns>
This is a lot of diffs unrelated to this PR.

2023-10-05 17:17 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +    internal sealed class QueryVectorArraySerializer<T> : BsonValueSerializerBase<QueryVectorBsonArray<T>>
It's probably just as cheap (and certainly simpler) to just create a new BsonArray on the fly when rendering rather than write and register a whole new serializer.

Note that when subclassing `BsonArray` the subclass should be 100% substitutable wherever a regular `BsonArray` would be used, and I don't thinks this type acts as a real `BsonArray` at all (the only thing it supports is being serialized).

Even though this class is internal, a reference to it can leak to the user via public `QueryVector.Array` property. Imagine their surprise when that `Array` is not a fully functional `BsonArray`.

2023-10-05 17:17 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +    internal sealed class QueryVectorBsonArray<T> : BsonArray
It's probably just as cheap (and certainly simpler) to just create a new BsonArray on the fly when rendering rather than write and register a whole new serializer.

Note that when subclassing BsonArray the subclass should be 100% substitutable wherever a regular BsonArray would be used, and I don't thinks this type acts as a real BsonArray at all (the only thing it supports is being serialized).

Even though this class is internal, a reference to it can leak to the user via public QueryVector.Array property. Imagine their surprise when that Array is not a fully functional BsonArray.

2023-10-05 18:33 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +    internal sealed class QueryVectorArraySerializer<T> : BsonValueSerializerBase<QueryVectorBsonArray<T>>
This is meant to optimize usage with larger memory chunks.

2023-10-05 18:33 UTC, BorisDog commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +        /// <returns>A new pipeline with an additional stage.</returns>
Yes, just used the opportunity of modifying this file to fix comments.

2023-10-05 18:33 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                options);
Thanks, done.

2023-10-05 21:51 UTC, rstam requested changes

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +        internal BsonArray Array { get; }
Add warning comment so we don't make this public by mistake some day:

    internal BsonArray Array { get; } // do not make public because in the case of ReadOnlyMemory the BsonArray subclass is not fully functional

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +
Add a warning comment that this subclass of BsonArray is not fully functional and is only intended to be serialized:

    // WARNING: this class is a very partial implementation of a BsonArray subclass
    // it is not fully functional and is only intended to be serialized

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +        public override int Count => _memory.Length;
I think you can remove this property (but see suggested change below).

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +
Add a comment explaining that this property ONLY exists for testing.

    // note: Values is only used in tests

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +
Perhaps if the tests were written differently this property wouldn't be needed.

2023-10-05 21:51 UTC, rstam commented on src/MongoDB.Driver/QueryVector.cs
> +                for (int i = 0; i < _memory.Length; i++)
for (int i = 0; i < span.Length; i++)

Since the index is being used with `Span[i]` I would rather control the for loop with `span.Length` (I realize of course that both evaluate to the same number, but I'd rather not have a level of indirection).

2023-10-05 23:25 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +
Done.

2023-10-05 23:25 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +        internal BsonArray Array { get; }
Done.

2023-10-05 23:25 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +
Left the `Values` and `Count` properties for simplicity, and added a comment.

2023-10-05 23:25 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +                for (int i = 0; i < _memory.Length; i++)
Good point, done.

2023-10-05 23:34 UTC, rstam approved these changes
LGTM

Thanks for walking through the justifications for ReadOnlyMemory in the public API with me. I wish I had known sooner that we were talking about vectors of 2000 numbers instead of less than 10.

2023-10-06 00:58 UTC, merged