CSHARP-4799: Pipeline stage with BsonDocumentSearchDefinition can be rendered only once
mongodb/mongo-csharp-driver pull request #1188
Opened 2023-09-29 23:56 UTC by BorisDog

2023-10-02 20:47 UTC, adelinowona requested changes

2023-10-02 20:47 UTC, adelinowona commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +`            (BsonDocument)Document.DeepClone();
Typo `'` on this line :)

2023-10-02 20:47 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +        [InlineData(null)]
Just curious, what is the null test case testing?

2023-10-02 20:47 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +            renderedPipeline = pipeline.Render(BsonSerializer.SerializerRegistry.GetSerializer<BsonDocument>(), BsonSerializer.SerializerRegistry);
Is the returned BsonDocument somehow altered in between the two `Render` calls? From my understanding it seems we want it so that subsequent calls to render will continue to render the same result even if the returned BsonDocument is modified. I don't explicitly see it unless it is not required?

2023-10-03 18:58 UTC, sanych-sun approved these changes
LGTM + minor comment

2023-10-03 18:58 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +        [InlineData(null)]
Should we test empty document (`"{}"`) as well?

2023-10-03 19:32 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +`            (BsonDocument)Document.DeepClone();
Thanks!

2023-10-03 19:32 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +        [InlineData(null)]
It tests that `null` is returned in the following case:
`var x = (SearchDefinition<BsonDocument>)null;`

2023-10-03 19:32 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +        [InlineData(null)]
I don't think so, the only distinction is between `null` and not `null`.

2023-10-03 19:32 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +            renderedPipeline = pipeline.Render(BsonSerializer.SerializerRegistry.GetSerializer<BsonDocument>(), BsonSerializer.SerializerRegistry);
`SearchDefinition` stage alters the underlying `BsonDocument` returned by `BsonDocumentSearchDefinition`.
So we need to test that pipeline containing the `Search` stage can be rendered more than once, so we are testing this through `pipeline.Render`.

You are correct in your observation that we are not testing the rendering with modification of `renderedPipeline`, but that's not a goal of this test case.

2023-10-03 19:45 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionTests.cs
> +            renderedPipeline = pipeline.Render(BsonSerializer.SerializerRegistry.GetSerializer<BsonDocument>(), BsonSerializer.SerializerRegistry);
Oh ok, thanks for the info.

2023-10-03 19:50 UTC, adelinowona approved these changes

2023-10-04 18:24 UTC, merged