CSHARP-4809: If a string serializer doesn't implement IHasRepresentationSerializer don't assume string values are actually represented as strings.
mongodb/mongo-csharp-driver pull request #1200
Opened 2023-10-16 19:19 UTC by rstam

2023-10-16 19:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> -                if (field.Serializer is IRepresentationConfigurable representationConfigurable &&
At the time this code was written the `IHasRepresentationSerializer` interface didn't exist.

2023-10-16 19:21 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> +                if (field.Serializer is not IHasRepresentationSerializer hasRepresentationSerializer)
If the serializer does not implement `IHasRepresentationSerializer` then we are unable to safely determine that the configured string serializer actually stores string values as strings in the database.

2023-10-16 23:55 UTC, BorisDog approved these changes
LGTM

2023-10-20 23:52 UTC, JamesKovacs approved these changes
LGTM

2023-10-23 18:08 UTC, sanych-sun requested changes

2023-10-23 18:08 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4809Tests.cs
> +        public void Filter_by_Id_with_custom_serializer_should_work(
I can see only "negative" case, the case when string was represented as non-string. Should we have positive test(s) as well?

2023-10-23 18:08 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4809Tests.cs
> +    public class CSharp4809Tests : Linq3IntegrationTest
Can we try to use more meaningful name for test class? Like a `StringExpressionToRegexFilterTranslatorTests`

2023-10-23 18:19 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> +                if (field.Serializer is not IHasRepresentationSerializer hasRepresentationSerializer)
I don't think this is a breaking change. It is a bug fix.

We used erroneously generate regex queries against values that weren't strings in the database.

2023-10-23 18:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4809Tests.cs
> +    public class CSharp4809Tests : Linq3IntegrationTest
https://mongodb.slack.com/archives/GQ27C9N7J/p1697495123127329?thread_ts=1697471201.169569&cid=GQ27C9N7J

2023-10-23 18:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4809Tests.cs
> +        public void Filter_by_Id_with_custom_serializer_should_work(
There are plenty of tests for the normal case elsewhere.

I can add one here also if you want.

2023-10-23 22:13 UTC, sanych-sun approved these changes
LGTM

2023-10-23 22:15 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> +                if (field.Serializer is not IHasRepresentationSerializer hasRepresentationSerializer)
If someone implemented their own serializer for string for any reasons. It was not throwing before (but simply assume it should be string out there), but it will throw after the next release.

2023-10-23 22:39 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> +                if (field.Serializer is not IHasRepresentationSerializer hasRepresentationSerializer)
OK I see your point. I think we discussed this and decided that simply assuming the representation was a string was not safe.

@JamesKovacs does this need to be reconsidered?

The core question is: if we have no evidence that some string serializer uses string representation or not what should we assume? That it does? Or throw because we can't determine whether it does?

2023-10-23 22:39 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/StringExpressionToRegexFilterTranslator.cs
> +                if (field.Serializer is not IHasRepresentationSerializer hasRepresentationSerializer)
Note: if you look at the test in this PR the test still works even though an exception is thrown. This test specifically uses a user writer custom serializer that does not implement `IHasRepresentationSerializer` (the situation you were worried about).

That's because the exception simply means that this string expression can't be translated using regular expressions. The exception will be caught and the expression will then be translated in some other way that doesn't use regular expressions (and therefore doesn't require knowing whether the database representation is a string).

2023-10-26 18:16 UTC, merged