CSHARP-4716: Log informational message client-side based on detected environment (DocumentDB or CosmosDB)
mongodb/mongo-csharp-driver pull request #1203
Opened 2023-10-18 01:57 UTC by BorisDog

2023-10-23 15:36 UTC, adelinowona requested changes

2023-10-23 15:36 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Clusters/ClusterFactory.cs
> +            bool IsExternalEnvironment(string host, string environment, string documentationUrl, params string[] suffixes)
`IsExternalEnvironment()` seems to always return false.

2023-10-23 15:36 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterFactoryTests.cs
> +        public void ClusterFactory_should_not_log_if_no_external_environment_is_detected(string connectionString)
Should we add a test with multiple external hosts to ensure that only one log message is emitted?

2023-10-23 17:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ClusterFactory.cs
> +            bool IsExternalEnvironment(string host, string environment, string documentationUrl, params string[] suffixes)
Good catch! Done, thanks!

2023-10-23 17:39 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterFactoryTests.cs
> +        public void ClusterFactory_should_not_log_if_no_external_environment_is_detected(string connectionString)
Added.

2023-10-23 18:27 UTC, adelinowona approved these changes
LGTM

2023-10-30 19:04 UTC, JamesKovacs requested changes

2023-10-30 19:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Clusters/ClusterFactory.cs
> +                if (IsCosmosDB(host) || IsDocumentDB(host))
Cross-cloud clusters are possible in Atlas. You can deploy a cluster with some nodes in Azure and others AWS. We should log informational messages for both in such a case.

As well, `IsCosmosDB` and `IsDocumentDB` call `IsExternalEnvironment`, which has side effects. This is unexpected. I would not expect calling `IsCosmosDB` in a tight loop to chew up log space. There's nothing wrong with the logic, but naming should be adjusted to reflect what the method is actually doing. Something like `LogIfCosmosDB`. I don't particularly care for that name and would love a better suggestion, but hopefully you get the idea.

2023-10-30 21:02 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ClusterFactory.cs
> +                if (IsCosmosDB(host) || IsDocumentDB(host))
Good point regarding the naming. Done.

2023-10-31 22:25 UTC, JamesKovacs approved these changes
LGTM

2023-10-31 22:36 UTC, merged