CSHARP-4670: Implement Drivers Performance Benchmarking Spec
mongodb/mongo-csharp-driver pull request #1204
Opened 2023-10-18 23:04 UTC by adelinowona

2023-11-03 02:03 UTC, BorisDog requested changes
Partial review.
Looks really good overall. Mainly minor and styling comments.

2023-11-03 16:32 UTC, adelinowona commented on CSharpDriver.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "benchmarks", "benchmarks\benchmarks.csproj", "{6C1F8B13-7CAD-44BB-B26E-CDCF9785A1A8}"
I think this is a good suggestion, it also provides a place to keep future benchmark projects.

2023-11-03 18:21 UTC, adelinowona commented on benchmarks/download-data.sh
> +#!/bin/sh
Agreed, it helps clean up the root directory the benchmark project

2023-11-03 20:35 UTC, adelinowona commented on benchmarks/BenchmarkResult.cs
> +        public double GetPercentile(int percentile)
The spec says to collect those percentiles and report them so that's why I have it here. But after inspecting most of the other driver's benchmarks, no one is reporting the percentiles yet. So I think we can remove this functionality for now and introduce it when needed or asked for.

2023-11-08 18:10 UTC, sanych-sun requested changes

2023-11-08 18:10 UTC, sanych-sun commented on benchmarks/download-data.sh
> +#!/bin/sh
I suppose it could be in the `benchmarks` folder. Having the file in `evergreen` folder might be confusing, because the script is intended to be used locally as well.

2023-11-17 19:29 UTC, adelinowona commented on benchmarks/BSON/DeepBsonDecodingBenchmark.cs
> +                BsonDocumentSerializer.Instance.Deserialize(_context);
discussed in slack

2023-11-17 19:29 UTC, adelinowona commented on benchmarks/BSON/DeepBsonEncodingBenchmark.cs
> +                BsonDocumentSerializer.Instance.Serialize(_context, _document);
discussed in slack

2023-11-17 19:29 UTC, adelinowona commented on benchmarks/BSON/DeepBsonDecodingBenchmark.cs
> +        public void DeepBsonDecoding()
done

2023-11-17 19:30 UTC, adelinowona commented on benchmarks/CustomExporters/EvergreenExporter.cs
> +namespace benchmarks.CustomExporters
done

2023-11-17 19:30 UTC, adelinowona commented on benchmarks/Multi-Doc/FindManyBenchmark.cs
> +namespace benchmarks.Multi_Doc
done

2023-11-17 19:31 UTC, adelinowona commented on benchmarks/BSON/DeepBsonDecodingBenchmark.cs
> +using static benchmarks.BenchmarkExtensions;
done. Renamed to MongoDB.Driver.Benchmarks instead

2023-11-17 19:32 UTC, adelinowona commented on benchmarks/BenchmarkResult.cs
> +
will do when we decide to add percentiles to the benchmark report in evergreen

2023-11-17 19:32 UTC, adelinowona commented on benchmarks/BenchmarkResult.cs
> +    public class BenchmarkResult
done

2023-11-17 19:34 UTC, adelinowona commented on benchmarks/BenchmarkExtensions.cs
> +    public static class BenchmarkExtensions
Updated benchmark suite to use categories for filtering!

2023-11-17 19:34 UTC, adelinowona commented on benchmarks/BenchmarkExtensions.cs
> +        public static IReadOnlyList<string> SingleBenchmarks { get; } =
not doing since this code is now removed

2023-11-17 19:34 UTC, adelinowona commented on benchmarks/BSON/DeepBsonDecodingBenchmark.cs
> +using MongoDB.Bson.Serialization.Serializers;
done

2023-11-23 02:01 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/FindManyBenchmark.cs
> +            _collection.InsertMany(documents);
Consider:

```
var documents = Enumerable
                .Range(0, 10000)
                .Select(_ => _tweetDocument.DeepClone().AsBsonDocument);
 _collection.InsertMany(documents);
```

2023-11-23 02:01 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/GridFSDownloadBenchmark.cs
> +            _client.DropDatabase("perftest");
I think we need to port `DisposableMongoClient` from tests, and use it here to dispose the cluster.

2023-11-23 02:04 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/Exporters/EvergreenExporter.cs
> +            using (var jsonWriter = new JsonWriter(File.CreateText(resultsPath), new JsonWriterSettings { Indent = true }))
I think `File.CreateText` just overwrites the existing file, no need to delete.

2023-11-23 02:05 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/Exporters/EvergreenExporter.cs
> +        {
Maybe the previous `WriteCompositeScoreToResults` method can be reused here?

2023-11-23 02:11 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileImportBenchmark.cs
> +        }
Looks like this setup can be extracted to 
```
_database = MongoConfiguration.CreateDatabase();
_client = _database.Client;
```

2023-11-23 19:43 UTC, BorisDog requested changes

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
> +    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.13.8" Condition="'$(OS)' == 'Windows_NT'"/>
Out of curiosity, why is this package needed on Windows?

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/FindManyBenchmark.cs
> +using BenchmarkDotNet.Attributes;
Remove/Sort usings everywhere.

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                "GridFSMultiFileUploadBenchmark" or "GridFSMultiFileDownloadBenchmark" => 262144000,
Let use `nameof`:
`nameof(InsertOneLargeBenchmark) or nameof(InsertManyLargeBenchmark) => 1111`

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/Exporters/EvergreenExporter.cs
> +                if (report.BenchmarkCase.Descriptor.HasCategory(DriverBenchmarkCategory.BsonBench))
Looks like this code is shared with LocalExporter and can be extracted to 
`var benchmarkName = BenchmarkHelper.GetBenchmarkName(BenchmarkCase)`
or event simpler:
`var  benchmarResult = BenchmarkHelper.GetBenchmarkResult(report);`
and then `GetDatasetSize` can stay private.

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/Exporters/LocalExporter.cs
> +    public class LocalExporter : IExporter
sealed

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/FindManyBenchmark.cs
> +        }
Do we need simple verifications of the correctness of the results? For  example count verification in this case.
Also to avoid any possible compiler optimization where unused results can be discarded (I don't think it applies here but not 100% sure).

2023-11-23 19:43 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/GridFSMultiFileDownloadBenchmark.cs
> +            Task[] tasks = new Task[50];
We need to understand the threading model prescribed by spec here.
Multiple tasks execution is not guarantied to be fully parallelized, and depends on various factors and various across different machines, setups, load.
So we might need to use threads directly or other solutions to for deterministic behavior.

2023-11-23 21:37 UTC, sanych-sun requested changes

2023-11-23 21:37 UTC, sanych-sun commented on benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
> +    <PackageReference Include="NDesk.Options" Version="0.2.1" />
Is this project still alive? Could we use [System.CommandLine](https://www.nuget.org/packages/System.CommandLine) instead? It's still in beta, but at least this is Microsoft supported one.

2023-12-11 16:31 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
> +    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.13.8" Condition="'$(OS)' == 'Windows_NT'"/>
I think it was auto added when I created the benchmark project. With BenchmarkDotNet you can add diagnosers for your benchmarks such as GC and memory allocations, JIT etc. Some of the diagnosers are only available on windows so I think the package is auto added so that one can add some diagnosers that will only run if they ran the benchmarks on a windows machine. We are not using any of those windows-only diagnosers so I can remove this for now.

2023-12-11 19:50 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/FindManyBenchmark.cs
> +        }
I tested correctness as I was writing the benchmarks so the benchmarks as is should be correct. Having correctness checks in some benchmarks seem very trivial while in others it may require doing something a bit more involved which may start having us diverge from performance work to correctness work. Most of the other driver benchmarks I have seen don't do correctness checks. I assume they probably did test for correctness as well while writing the benchmarks but I'll ask just out of curiosity.

2023-12-11 19:56 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/FindManyBenchmark.cs
> +        }
Regarding the possible compiler optimization, I looked at the generated IL code and I don't think the compiler optimizations will do anything since almost all of the operations in benchmarks are performed on a member variable of a class which means compiler will be probably think that the variable is modified in some way by the calls thus it remains cautious. I also played around with this lab to confirm: [SharpLab](https://sharplab.io/)

2023-12-14 20:22 UTC, BorisDog requested changes
Great refactoring, few more comments

2023-12-14 20:22 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +            if (benchmarkCategory == DriverBenchmarkCategory.DriverBench)
Please double check if this switch is needed.

2023-12-19 21:13 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
I am calling ToList here to avoid possible multiple enumeration since I am calling Any and Average on the enumerable. This helps in avoiding the costs of doing multiple enumerations if the objects being enumerated are large thus saving some performance.

2024-01-09 16:53 UTC, sanych-sun reviewed
Generally looks good + some comments.

2024-01-09 16:53 UTC, sanych-sun commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileExportBenchmark.cs
> +                    var documents = _collection.Find(Builders<BsonDocument>.Filter.Empty).Skip((startingFileNumber+i) * 5000).Limit(5000).ToList();
Let's discuss this code in offline.

2024-01-10 00:27 UTC, BorisDog requested changes
Looks great, mainly stylistic comments.

2024-01-10 00:27 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileExportBenchmark.cs
> +                    using (StreamWriter streamWriter = File.CreateText(filepath))
minor: `using (var streamWriter...)`

2024-01-10 00:27 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileExportBenchmark.cs
> +            foreach (var file in _tmpDirectory.EnumerateFiles())
Consider dropping the whole dir.

2024-01-10 00:27 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileExportBenchmark.cs
> +                documents.AddRange(File.ReadLines(resourcePath).Select(BsonDocument.Parse));
minor:  consider
`var documents = File.ReadLines(resourcePath).Select(BsonDocument.Parse).ToArray();`

2024-01-10 00:27 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileImportBenchmark.cs
> +                    _collection.InsertMany(documents);
Consider:
var documents = File.ReadLines(resourcePath).Select(BsonDocument.Parse).ToArray();

Also this is code appears in other places, consider moving to `BenchmarkHelper`

2024-01-10 00:32 UTC, rstam commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
`ToArray` implementation creates the equivalent of a `List` first and then once that list is populated and it knows how many elements are in it it then creates an array and copies the elements to it, so it requires an extra memory allocation and some copying.

Other than that `ToArray` is fine.

2024-01-10 00:35 UTC, rstam commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
Also, a `List<T>` can be cast to an `IReadOnlyList<T>` if you want to hide the rest of the `List<T>` methods and properties.

`IReadOnlyList<T>` is like an array `T[]` but is immutable.

2024-01-10 21:17 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
Optimizations considerations are probably neglectable in most cases here, but `ToArray` is probably more optimal in most of our use cases:

- If the underlying enumerable is `ICollection` (not here) creating temporary list is skipped.
- Copying:
 `ToList` will have [N, 2N) bytes copied(16 + 32 + , ... N^(floor(log(N ))
 `ToArray` will have N bytes copied.
- Allocation: You are correct that `ToArray` will allocate additional copy, but it would be gen0 object and quickly collected. But `ToList` will always (almost always) allocate more memory (up to N additional bytes) that will survive much longer. After first gen0 collection:
`ToList` [N, 2N) allocated bytes
`ToArray` N allocated bytes

So adopting `ToArray` instead of `ToList` as a rule of thumb will allow us to benefit from having less copying and less long surviving memory, as well as having simpler data type to work with.

2024-01-10 22:12 UTC, rstam commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
I don't see how `ToArray` will result in less copying. It will always allocate roughly the same amount of memory as `ToList` for the temporary list and then an additional allocation for the final array. (With the exception of classes that implement `ToArray` more efficiently, but as you say that's not the case here).

I agree that if the result is to be long lived the array version will prevent only the required memory to hold the array and no more from being garbage collected.

But in this case the result of `ToList` is short lived anyway.

I don't mind encouraging the use of `ToArray`, but the argument should be that you want the result to be an *array* and not a performance or memory use argument.

2024-01-10 22:23 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
> +    <PackageReference Include="NDesk.Options" Version="0.2.1" />
Discussed on slack

2024-01-10 22:38 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/GridFSUploadBenchmark.cs
> +        public int BenchmarkDataSetSize { get; set; }
This stores the dataset size for the benchmark and it is accessed in the BenchmarkResult constructor. I created this in an effort to keep all benchmark related data in their own class so I don't have to externally get that info from somewhere else.

2024-01-10 23:27 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
Less copying:
`ToList` -> Each underlying array will be copied to the new one when list grows, so we'll end up with [N, 2N) bytes copied.
`ToArray` -> When growing the underlying array creator structure, additional array is added for new items, while preserving old array. Exactly N bytes will be copied.

As mentioned at the begging of this thread my motivation to encourage usage of `Array` is to use simpler types where possible and opt-in into more complex types only when additional specific functionality is required.
This performance analysis is to address the concern of additional memory being used in `ToArray`,  while theoretically `ToArray` appears to be more optimal.

2024-01-11 00:23 UTC, rstam commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Select(benchmark => benchmark.Score).ToList();
> ToArray -> When growing the underlying array creator structure, additional array is added for new items, while preserving old array. Exactly N bytes will be copied.

That's not the implementation I saw. Perhaps they have improved the implementation in more recent versions of .NET. That would be great.

I also like the idea of using the simplest data type possible, but an array is not quite that. It's mutable. The simplest data type possible would be `IReadOnlyList<T>`, assuming all you want to do is consume the results.

But like I said earlier, I'm fine with using `ToArray`.

2024-01-11 01:03 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +                .Where(benchmark => benchmark.Categories.Contains(benchmarkCategory))
Yeah probably doesn't really matter here but it doesn't hurt to have more efficient code if it is just a simple change.

2024-01-11 01:22 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/Exporters/EvergreenExporter.cs
> +            using (var jsonWriter = new JsonWriter(File.CreateText(resultsPath), new JsonWriterSettings { Indent = true }))
Seems like `JsonWriter` doesn't dispose the `StreamWriter`, the dispose of `JsonWriter` calls its `Close` method which in turn calls the `Flush` method on the `StreamWriter` but no disposing is done.

2024-01-11 02:11 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/MultiFileImportBenchmark.cs
> +                    _collection.InsertMany(documents);
I think it only appears in two places, I think it is isolated enough to not move it `BenchmarkHelper`

2024-01-11 21:21 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/ParallelBench/GridFSMultiFileDownloadBenchmark.cs
> +                var numFilesToDownload = threadNumber == 15 ? 5 : 3;
I was using 16 threads as I wanted to use the optimal thread count for the evergreen host on which the benchmarks are run which has 16 logical CPUs. Alex also already suggested I use ConcurrentQueue since my current set up might be hard to read. So I will explore using using it as that is better than having this funky work distribution.

2024-01-12 18:30 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +        public static void AddFilesToQueue(ConcurrentQueue<(string, int)> filesQueue, string directoryPath, string fileNamePrefix, int fileCount)
Added this function as the piece of code encapsulated here would have been reused in the parallel benchmarks to fill the concurrentQueue.

2024-01-12 20:07 UTC, BorisDog approved these changes
Great job, LGTM!
Minor optional comments.

2024-01-12 20:07 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/scripts/compare-results.py
> +# Copyright 2021 MongoDB, Inc.
2010

2024-01-12 20:07 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/scripts/download-data.sh
> +# Copyright 2021 MongoDB, Inc.
2010

2024-01-12 20:36 UTC, sanych-sun approved these changes
LGTM

2024-01-12 23:45 UTC, merged