CSHARP-4783: API docs generating with docfx
mongodb/mongo-csharp-driver pull request #1206
Opened 2023-10-19 16:06 UTC by sanych-sun

2023-10-20 23:44 UTC, JamesKovacs requested changes
This looks great. Minor feedback on naming. As well since this commit replaces Sandcastle with DocFX, we should remove the `./Docs` folder as part of this commit. I realize that this will remove both the Sandcastle-related files as well as the reference docs. The reference docs aren't related, but we stopped updating them awhile ago.

2023-10-20 23:44 UTC, JamesKovacs commented on .gitignore
> +/build
Other tasks build into the `artifacts` directory. We should use that rather than adding another directory.

2023-10-20 23:44 UTC, JamesKovacs commented on docfx_project/api/index.md
> +# MongoDB C# Driver API Reference
MongoDB .NET/C# Driver API Reference

2023-10-20 23:44 UTC, JamesKovacs commented on evergreen/apidocs-build.sh
> +#!/usr/bin/env bash
Most of our other scripts use `verb-noun.sh`. Consider changing this to `build-apidocs.sh`.

2023-10-20 23:44 UTC, JamesKovacs commented on evergreen/evergreen.yml
> -        - func: run-atlas-search-index-helpers-test
Unrelated change even if it is fixing whitespace.

2023-10-21 00:03 UTC, sanych-sun commented on .gitignore
> +/build
Ups, I've discovered that test results file being output into the ./build directory and did not check if other tasks output to the same folder. Will update here and some another tasks (packages creation script also output to the ./build folder now, will update it to use ./artifacts folder).

2023-10-21 00:08 UTC, sanych-sun commented on evergreen/apidocs-build.sh
> +#!/usr/bin/env bash
I probably would like to review this naming convention. If we use opposite convention: `noun-verb.sh` this let us group together related scripts. For example:
apidocs-build
apidocs-validate
packages-pack
packages-push
packages-test
tests-run

2023-10-30 22:40 UTC, sanych-sun commented on evergreen/apidocs-build.sh
> +#!/usr/bin/env bash
I've reviewed other drivers/repos: all of them are using `verb-noun.sh` notation. I'll update scripts to follow the same naming conventions. Thanks.

2023-11-01 17:48 UTC, sanych-sun commented on docfx_project/.gitignore
> +.manifest
As we removed "old" `Docs` folder, should we rename this folder to `Docs` instead of `docfx_project`?

2023-11-01 17:50 UTC, sanych-sun commented on evergreen/evergreen.yml
>             fi
I've applied proper naming to all recently added scripts/tasks. Also I'll create a separate green-build-friday task to implement CI step to call docfx.

2023-11-07 23:58 UTC, JamesKovacs commented on docfx_project/.gitignore
> +.manifest
SGTM

2023-11-16 15:45 UTC, JamesKovacs requested changes
Cake includes a [DocFX add-in](https://cakebuild.net/dsl/docfx/). We should keep the `ApiDocs` task and use that add-in. If we decide to replace Cake entirely with shell scripts eventually, we can do it then. But for now we should keep the Cake tasks for consistency.

2023-12-08 01:43 UTC, merged