CSHARP-4730: Always encode CompressionType.ZStandard as zstd.
mongodb/mongo-csharp-driver pull request #1207
Opened 2023-10-19 16:30 UTC by JamesKovacs

2023-10-19 16:54 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +        public void TestCompressorProperties()
The only supported compressor property is zlib compression level. So I rewrote the test to test it directly and remove the overly complex string split impl.

2023-10-20 02:42 UTC, BorisDog requested changes

2023-10-20 02:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +            subject.Compressors = compressors?.Select(x=> new CompressorConfiguration(x)).ToList();
```suggestion
            subject.Compressors = compressors?.Select(x => new CompressorConfiguration(x)).ToList();
```

2023-10-20 02:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoUrlBuilderTests.cs
> +        public void TestCompressors(CompressorType[] compressors, string expectedConnectionString)
Good idea.

2023-10-20 02:42 UTC, BorisDog commented on src/MongoDB.Driver/MongoUrlBuilder.cs
> +                query.AppendFormat("compressors={0}&", string.Join(",", _compressors.Select(x => CompressorTypeMapper.ToServerName(x.Type))));
I think it's a good opportunity to fix [MongoClientSettings.ToString](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver/MongoClientSettings.cs#L1224) as well. (Even if that's only used for debugging)

2023-10-20 22:20 UTC, JamesKovacs reviewed
Comments on latest changes inline.

2023-10-20 22:20 UTC, JamesKovacs commented on src/MongoDB.Driver/MongoUrlBuilder.cs
> +                query.AppendFormat("compressors={0}&", string.Join(",", _compressors.Select(x => CompressorTypeMapper.ToServerName(x.Type))));
Valid point. Added to this PR.

2023-10-20 22:20 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Contains(expectedConnectionString, result);
Performing an `Assert.Contains` because other options are output to the debug string which we don't care about in this test.

2023-10-20 22:20 UTC, JamesKovacs commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                sb.AppendFormat("Compressors=[{0}];", string.Join(",", _compressors.Select(x => CompressorTypeMapper.ToServerName(x.Type))));
Previously this output `Compressors=[MongoDB.Driver.Core.Configuration.CompressorConfiguration]`, which isn't terribly useful. I've switched this to output the list of configured compressors. I haven't included compressor properties, but that's only supported by zlib - which isn't a recommended compressor anyways. Seemed of little value to include it.

2023-10-20 22:37 UTC, BorisDog approved these changes
LGTM

2023-10-20 23:07 UTC, merged