CSHARP-4719: Benchmark performance of in-use Encryption
mongodb/mongo-csharp-driver pull request #1216
Opened 2023-11-18 03:56 UTC by adelinowona

2023-11-20 16:53 UTC, adelinowona commented on CSharpDriver.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "BenchmarkLibmongocrypt", "BenchmarkLibmongocrypt\BenchmarkLibmongocrypt.csproj", "{F2C683ED-138E-48AF-9C49-2BF8A0631842}"
Once the driver benchmarking PR is merged, I plan on placing this encryption benchmarks under the new benchmarks solution folder  introduced in the driver benchmarking PR.

2023-11-28 01:49 UTC, BorisDog requested changes

2023-11-28 01:49 UTC, BorisDog commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +using BenchmarkDotNet.Reports;
Remove and sort usings.

2023-11-28 01:49 UTC, BorisDog commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +            byte[] localMasterKey = Convert.FromBase64String(LocalMasterKey);
var

2023-11-28 01:49 UTC, BorisDog commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +            Task.WaitAll(tasks);
We need to use real threads, or `ThreadPerTaskScheduler`.
Also benchmark measures thread creations, so maybe it's worth creating the threads in GlobalThread.

2023-11-28 23:39 UTC, sanych-sun commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +            // since the benchmark is not in the same assembly as MongoClient, we can't directly get the LibMongoCryptController in it
Can InternalsVisibleTo attribute help with this like we doing for unit-tests? Reflection is known to be a little slower.

2024-01-10 02:54 UTC, BorisDog requested changes

2024-01-10 22:08 UTC, adelinowona commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +        public void FindWithNoEncryption()
Will remove this

2024-01-10 22:09 UTC, adelinowona commented on MongoDB.LibMongoCryptBindingsBenchmark/Benchmarks.cs
> +        public void FindWithEncryption()
Will remove this as well

2024-01-17 01:53 UTC, BorisDog requested changes

2024-01-17 01:53 UTC, BorisDog commented on benchmarks/MongoDB.Libmongocrypt.Benchmarks/LibmongocryptBindingBenchmark.cs
> +            byte[] localMasterKey = Convert.FromBase64String(LocalMasterKey);
nit: var

2024-01-17 01:53 UTC, BorisDog commented on benchmarks/MongoDB.Libmongocrypt.Benchmarks/LibmongocryptBindingBenchmark.cs
> +                var cryptClient = CryptClientCreator.CreateCryptClient(autoEncryptionOptions.ToCryptClientSettings());
I think `cryptClient` needs to be disposed as well.

2024-01-17 17:33 UTC, sanych-sun approved these changes
LGTM

2024-01-17 18:29 UTC, sanych-sun commented on benchmarks/MongoDB.Libmongocrypt.Benchmarks/LibmongocryptBindingBenchmark.cs
> +        [Benchmark]
I can see only one benchmark here, but PR description refers to 3. Could you please describe in readme or somewhere else how to perform such benchmarking

2024-01-19 19:19 UTC, BorisDog approved these changes
LGTM (few minor comments)

2024-01-19 19:19 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/LibmongocryptBindingBenchmark.cs
> +            "Mng0NCt4ZHVUYUJCa1kxNkVyNUR1QURhZ2h2UzR2d2RrZzh0cFBwM3R6NmdWMDFBMUN3YkQ5aXRRMkhGRGdQV09wOGVNYUMxT2k3NjZKelhaQmRCZGJkTXVyZG9uSjFk";
Same line is fine here.

2024-01-19 19:19 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/LibmongocryptBindingBenchmark.cs
> +                }
minor: Looks like the scope of `using clientEncryption` can end here.

2024-01-19 19:19 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkRunner.cs
> +            config = executingDriverBenchmarks
nit: IMHO having regular assignments here are more readable, as u don't need to validate the `else` no-op clause:

```
if (..)
{
 config = config.With(...)
}
```

2024-01-19 21:26 UTC, merged