EF-73: Add more EF Core metadata to Client Metadata Handshake
mongodb/mongo-csharp-driver pull request #1222
Opened 2023-11-24 00:42 UTC by sanych-sun

2023-11-24 00:46 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +            var versionAttribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
Try to read the `AssemblyInformationalVersionAttribute` insted of `AssemblyFileVersionAttribute`, because it contains version suffixes (like a -dev or -preview.1), when `AssemblyFileVersionAttribute` does not.

2023-11-24 00:48 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +            if (versionAttribute == null)
Fallback to the "previous" logic incase `AssemblyInformationalVersionAttribute` is missed (this is kind of overkill here, but want to make sure we have some version in any case)

2023-12-02 00:12 UTC, BorisDog requested changes

2023-12-05 16:01 UTC, BorisDog approved these changes
LGTM

2023-12-05 20:14 UTC, merged