CSHARP-4706: Support for  to Time-series collections
mongodb/mongo-csharp-driver pull request #1223
Opened 2023-11-28 00:51 UTC by adelinowona

2023-12-04 19:22 UTC, BorisDog requested changes
Looks great, some comments about testing.

2023-12-04 19:22 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Jira/CSharp3397Tests.cs
> +        public void Aggregate_out_to_time_series_collection_should_work()
I am not sure we need such test for time-series here. Probably `Execute_to_time_series_collection_should_work` is sufficient. cc @JamesKovacs

2023-12-04 19:22 UTC, BorisDog commented on src/MongoDB.Driver/IAggregateFluent.cs
> +        /// <param name="timeSeriesOptions">The time series options</param>
Period at the end (here and elsewhere).

2023-12-04 19:22 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateToCollectionOperationTests.cs
> +        [Theory]
Lets also add tests in `PipelineDefinitionBuilderTests` and in `PipelineStageDefinitionBuilderTests` (no need to cover all Out cases, just for time-series.).

2023-12-04 19:22 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/AggregateToCollectionOperation.cs
> +            if (lastStageName == "$out" && lastStage["$out"] is BsonDocument outDocument && !outDocument.Contains("timeseries"))
Do we have this tested directly or indirectly somewhere?

2023-12-06 17:00 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Jira/CSharp3397Tests.cs
> +        public void Aggregate_out_to_time_series_collection_should_work()
I added this test here since server added support of $out to time series on secondaries. The original tests in CSharp3397Tests.cs test for support of $merge and $out executing on secondaries (https://jira.mongodb.org/browse/CSHARP-3397) so I thought it would be appropriate to add my test here. Also I should probably rename the test to `Aggregate_out_to_time_series_collection_on_secondary_should_work`

2023-12-06 18:10 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Operations/AggregateToCollectionOperation.cs
> +            if (lastStageName == "$out" && lastStage["$out"] is BsonDocument outDocument && !outDocument.Contains("timeseries"))
This is tested indirectly through the `Aggregate_out_to_time_series_collection_on_secondary_should_work` test and the AggregateToCollection time series tests. Without this, the simplification of the out stage will just remove the timeseries options resulting in the time series tests failing.

2023-12-06 20:47 UTC, BorisDog requested changes

2023-12-06 20:47 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +            var client = DriverTestConfiguration.Client;
Looks like we just need the collection namespace for rendering.
Maybe we can just mock the collection, and then the test would not be dependent on server?

2023-12-06 20:47 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RenderStage(result).Document.Should().Be("{ $out: { db: 'database', coll: 'collection', timeseries: { timeField: 'time', metaField: 'symbol' } } }");
Same comment about mocking collection.

2023-12-06 20:47 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOutTimeSeriesOnSecondary = new Feature("AggregateOutTimeSeriesOnSecondary", WireVersion.Server70);
Not sure that we need the secondary feature.

2023-12-06 20:47 UTC, BorisDog commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +            Ensure.IsNotNull(pipeline, nameof(pipeline));
We should either merge overloads (add `timeSeriesOptions = null` parameter) or forbid null here.
I personally would prefer having less overloads for simplicity.

2023-12-06 23:12 UTC, BorisDog requested changes

2023-12-06 23:12 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOutTimeSeries = new Feature("AggregateOutTimeSeries", WireVersion.Server70);
Alphabetical order (field and property).

2023-12-07 01:10 UTC, JamesKovacs requested changes
While I don't like optional parameters (see comment below for why), we use them elsewhere. I'm fine with using an optional parameter for `timeSeriesOptions` and not adding more overloads. Fix that and some minor comment issues and you're good to go.

2023-12-07 01:10 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +            Ensure.IsNotNull(pipeline, nameof(pipeline));
I see that we are already doing this elsewhere in our Fluent Aggregate API. Sigh. I guess we can use `TimeSeriesOptions timeSeriesOptions = null` here to reduce the number of overloads.

2023-12-07 01:10 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +        public static PipelineStageDefinition<TInput, TInput> Out<TInput>(
It is a minor breaking change (and I don't like it for the reasons stated above), but we are already doing it elsewhere in our public API. We can do it here too to reduce the number of overloads. We will release this in a new version, not a patch build. So users should recompile their apps and not notice the breakage as the C# compiler will do the right thing.

2023-12-07 17:14 UTC, BorisDog approved these changes
LGTM!

2023-12-07 22:08 UTC, merged