CSHARP-4858: Add IsMissing and IsNullOrMissing MongoDBFunctions.
mongodb/mongo-csharp-driver pull request #1224
Opened 2023-11-28 22:09 UTC by rstam

2023-11-28 22:17 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Damien thinks `MongoDBFunctions` should not be a static class and that `IsMissing` should be an extension method instead.

To the user the difference would be that they would write

    MongoDB.Functions.IsMissing(x.S)

Note the period between `MongoDB` and `Functions`.

@JamesKovacs let's discuss when you get back.

2023-11-28 22:17 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Damien would also like to see the LINQ provider support

    EF.Functions.IsMissing(x.S)

even though the C# driver knows nothing about the type `DbFunctions` (that's the type of the `EF.Functions` static property) or anything about any extension methods defined on `DbFunctions`.

The question from the perspective of the C# driver is whether we want to start writing EF Core provider specific code (so far we have avoided doing so).

Ideally we would avoid having EF Core specific code in the C# driver. From a pragmatic viewpoint we might be willing to do some of that.

2023-11-29 21:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Besides the question of whether this class should be static or not we should also think hard about naming.

We currently have a few places custom LINQ related methods live:

* Various extensions methods on existing .NET classes (e.g. DateTime, String, NullableDateTime)
* MongoDBMath
* LinqExtensions
* MongoEnumerable (similar to .NET Enumerable)
* MongoQueryable (similar to .NET Queryable)

MongoDBFunctions is named similarly to `EF.Functions`, but I don't think we need to follow EF Core naming conventions in the C# driver. Maybe a simpler name would be possible.

Hopefully we don't end up with too many new places for custom LINQ methods to live.

2023-12-01 15:41 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Additional point to consider:
As we are planning to support trimming in [CSHARP-4840](https://jira.mongodb.org/browse/CSHARP-4840), it would be great to ensure that at least all new code supports trimming.
In this PR the reflection is an immediate suspect for trimming compatibility issues. If it can be avoided that would be preferable.

2023-12-01 15:45 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/MongoDBFunctionsMethod.cs
> +            __isNullOrMissing = ReflectionInfo.Method((object field) => MongoDBFunctions.IsNullOrMissing(field));
Don't these two static references to `IsMissing` and `IsNullOrMissing` avoid any trimming concerns?

2023-12-01 15:53 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Usually reflection is problematic, as the trimming process does not know of dynamically loaded types, and might trim them.
In this case we just need to make sure that there are no issues around usage of `MongoDBFunctionsMethod` in the trimmed mode.
Testing this in not trivial, as our driver can't even load in trimmed mode, so if you choose to research this issue, probably the best way to do so is via sample app.
Or just avoid reflection if possible.

2023-12-01 18:34 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Thanks for checking that.

2023-12-07 00:33 UTC, JamesKovacs approved these changes
LGTM. See my inline comment for my discussion points.

2023-12-07 00:33 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
What is the problem with using `MongoDbFunctions.IsNullOrMissing` in EF? It is a MongoDB-specific extension that other providers won't understand.

While we could write it as an extension method, we end up with `field.IsNullOrMissing()` - which while possible would suggest we are calling a method on a potentially null value. Not a huge deal as it is an extension method. No different than writing `someString.IsNullOrEmpty()`, which is simply defined as:

```
public class StringExtensions
{
    public static bool IsNullOrEmpty(this string str)
    {
        return String.IsNullOrEmpty(str);
    }
}
```

Totally valid C# but still quirky as it looks like you're calling a method on a potentially `null` value but not throwing.

Is there an existing `EF.Functions.IsMissing`? Why wouldn't we simply use `MongoDbFunctions.IsMissing` directly?

The larger question of whether we should merge the various extensions is a 3.0 driver question. It would be nice to simply `using MongoDB.Driver.Extentions` (or whatever we call it) and have them all available. But that sounds like a task for another ticket targeted at the 3.0 driver.

2023-12-07 17:35 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
I would vote for implementing this as extensions methods ([empty class](https://github.com/dotnet/efcore/blob/e84e5add7a1046c7248515884fcd321cc03678ef/src/EFCore/DbFunctions.cs) that exists only to be extended). Because if we would ever came to the point when our LINQ provider would be extendable from outside it would be nice extension point to inject 3rd-party functions. And they would be available same way as built-in.

2023-12-24 19:54 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBLinq.Functions.IsMissing(x.S));
I first thought of using `MongoDB.Functions` (patterned after `EF.Functions`) but we can't have a class named `MongoDB` because it conflicts with the root of our namespaces which is also `MongoDB`.

I suppose we could consider `MDB.Functions` but we normally avoid abbreviations.

2023-12-24 19:56 UTC, rstam commented
The latest commit explores Alex's suggestion to define `IsMissing` and `IsNullOrMissing` as extension methods against a dummy `MongoDBFunctions` class. This idea comes from how EF Core does something similar.

This is just a prototype of such an approach. I need you to review the approach and the naming even more than reviewing the code itself. If we use this approach we are committing to it for future methods.

2023-12-26 16:26 UTC, rstam commented
The latest commit adds an Exists method to test for the existence of a field.

Using `Exists` is more convenient than `!IsMissing`.

2023-12-28 19:55 UTC, sanych-sun approved these changes
LGTM

2024-01-02 16:48 UTC, damieng commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBFunctions.IsMissing(x.S));
Two comments:

**1. Trimming** - Given these are going to be static methods (either extension or regular) I don't think they're going to cause a problem for trimming. While reflection has limitations I haven't seen anything that says the compiler is incapable of identifying references inside expression trees that the compiler builds during compilation.

**2. Naming** - Let's go with whatever works best for the LINQ provider for now. EF doesn't *require* them to be in `EF.Functions` so let's see if it causes confusion or not. Worse case at some later point we duplicate the static class/stubs and either translate it from one to the other in the EF provider or recognize both in the V3 provider.

2024-01-11 00:42 UTC, JamesKovacs approved these changes
LGTM

2024-01-11 00:42 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +                .Select(x => MongoDBLinq.Functions.IsMissing(x.S));
`MongoDBLinq.Functions.IsMissing` (and friends) isn't readily discoverable. Make sure you mark this as requiring documentation. I would have said the same thing about `MongoDBFunctions`. It's not the name change. It's the fact that it won't appear readily in Intellisense.

2024-01-11 16:53 UTC, JamesKovacs approved these changes
Renaming LGTM.

2024-01-19 19:06 UTC, BorisDog requested changes

2024-01-19 19:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +    internal static class FieldExistsOrIsMissingMethodToAggregationExpressionTranslator
We name these classes after the method(s) they translate.

We wouldn't want to group ALL of them into a single `MqlMethodsTranslator`.

We could separate translation of `Exists` and `IsMissing` but they have so much in common that there is good opportunity to share code here.

2024-01-19 19:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +                return new AggregationExpression(expression, ast, BooleanSerializer.Instance);
We haven't worried to much about this in other translators.

The initial test is to ensure it's one of the methods that this translator knows how to handle.

In other translators that would be it, but in this one there are slight variations depending on which method is being translated.

I will refactor a slightly different way.

2024-01-19 19:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Mql.cs
> +    public static class Mql
Originally I would have said yes to putting this in the `Linq` namespace.

This was discussed and others felt it shouldn't be in the `Linq` namespace because you can use this with builders (and the LINQ machinery is incidental).

What do others think about which namespace this should be in?

2024-01-19 19:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4858Tests.cs
> +    public class CSharp4858Tests : Linq3IntegrationTest
Tests moved to `FieldExistsOrIsMissingMethodToAggregationExpressionTranslatorTests.cs`

2024-01-19 19:30 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +                    nameof(Mql.IsNullOrMissing) => AstExpression.In(AstExpression.Type(fieldAst), new BsonArray { "null", "missing" }),
It's safe to use string comparisons here because line 42 verified that it REALLY is one of the supported methods and not just one that is named alike.

2024-01-19 19:43 UTC, rstam commented on src/MongoDB.Driver/Linq/Mql.cs
> +    public static class Mql
Sorry I misunderstood your question.

It currently IS under the `MongoDB.Driver.Linq` namespace.

Should we move it up one level?

2024-01-19 20:18 UTC, damieng commented on src/MongoDB.Driver/Linq/Mql.cs
> +    public static class Mql
I'd go with bringing it up one level. Even when they are doing LINQ they may well have not brought the MongoDB.Driver.Linq namespace in.

2024-01-19 20:22 UTC, damieng commented on src/MongoDB.Driver/Linq/Mql.cs
> +            throw new NotSupportedException("This method is not functional. It is only usable in MongoDB LINQ queries.");
Might be worth having the method name explicitly in the message, e.g.

```csharp
static InvalidOperationException BuildException([CallerMemberName] string memberName = null)
{
   return new InvalidOperationException($"Mql.{memberName} is a method for mapping queries to MongoDB and should not be called directly client-side.");
}
```

EF goes an `InvalidOperationException` with the message:

> The '{methodName}' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.

2024-01-19 20:25 UTC, BorisDog requested changes

2024-01-19 20:25 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +    internal static class FieldExistsOrIsMissingMethodToAggregationExpressionTranslator
Got it. 
So any new method in MqlMethods, would require to implement a new translator, and could not take advantage of code reuse here? Or we don't expect new methods for the same form?

2024-01-19 20:25 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Mql.cs
> +    public static class Mql
It seems that it should be moved up, to be more easily discoverable for Builder users. Unless it can be used only with Linq.

2024-01-19 20:25 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslatorTests.cs
> +namespace MongoDB.Driver.Tests.Linq.Linq3Implementation.Jira
Need to adjust the namespace as well.

2024-01-19 21:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +    internal static class FieldExistsOrIsMissingMethodToAggregationExpressionTranslator
Sharing a translator for multiple methods is only reasonable when all the methods have something in common. In this case the thing they have in common is that they all do some kind of existence tests on a field.

The usual case is that a new method requires a new translator.

2024-01-19 21:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Mql.cs
> +    public static class Mql
Done.

2024-01-19 21:33 UTC, rstam commented on src/MongoDB.Driver/Linq/Mql.cs
> +            throw new NotSupportedException("This method is not functional. It is only usable in MongoDB LINQ queries.");
This is a good suggestion. Maybe we need a separate JIRA ticket for it.

This exception was copied verbatim from existing custom methods.

Changing the exception type would normally be considered a breaking change. Changing the message is somewhat less breaking.

2024-01-19 21:33 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslatorTests.cs
> +namespace MongoDB.Driver.Tests.Linq.Linq3Implementation.Jira
Good catch.

2024-01-19 21:50 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +    internal static class FieldExistsOrIsMissingMethodToAggregationExpressionTranslator
Just trying to think what happens when a method that has similar translation will be added to `Mql`, and `FieldExistsOrIsMissingMethodToAggregationExpressionTranslator` would be the most natural place for it.

Which might be the case for many potential methods in Mql, or is it unlikely at this point?

2024-01-19 22:51 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslator.cs
> +    internal static class FieldExistsOrIsMissingMethodToAggregationExpressionTranslator
In general when we add new MQL methods they won't have anything in common with these three.

There will be all sorts of combinations of return types, number of arguments, argument types, argument interpretations (i.e. in this case they must idenitfy a field) and all kinds of different translations.

I don't anticipate supporting any new methods in this translator.

2024-01-19 23:54 UTC, BorisDog requested changes
Few minor comments.

2024-01-19 23:54 UTC, BorisDog commented on src/MongoDB.Driver/Mql.cs
> +        /// <returns>True if the field is missing.</returns>
field exists

2024-01-19 23:54 UTC, BorisDog commented on src/MongoDB.Driver/Mql.cs
> +        /// <returns>True if the field is null missing.</returns>
null or missing?

2024-01-19 23:54 UTC, BorisDog commented on src/MongoDB.Driver/Mql.cs
> +        /// <returns>True if the field is missing.</returns>
`<c>true</c>` in all comments?

2024-01-20 05:22 UTC, BorisDog approved these changes
LGTM

2024-01-20 23:25 UTC, damieng commented
LGMT

2024-01-20 23:25 UTC, damieng approved these changes

2024-01-23 17:30 UTC, sanych-sun approved these changes
LGTM

2024-01-23 23:16 UTC, JamesKovacs approved these changes
LGTM

2024-01-23 23:19 UTC, JamesKovacs requested changes
Just noticed that the patch is failing on Windows due to a path length issue.
```
[2024/01/19 17:16:15.096] LibGit2Sharp.LibGit2SharpException: path too long: 'C:/data/mci/98efc01bfb8b1056ce0fd6be52c3b4a2/mongo-csharp-driver/tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FieldExistsOrIsMissingMethodToAggregationExpressionTranslatorTests.cs'
```

2024-01-24 01:31 UTC, merged