CSHARP-4859: Nested AsQueryable POC.
mongodb/mongo-csharp-driver pull request #1226
Opened 2023-11-29 18:47 UTC by rstam

2023-11-29 18:50 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ExpressionHelper.cs
> +        public static LambdaExpression UnquoteLambdaIfQueryableMethod(MethodInfo method, Expression expression)
New helper method to unquote lambda only when method is a Queryable method.

2023-11-29 18:50 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AsQueryableMethodToAggregationExpressionTranslator.cs
> +                return new AggregationExpression(expression, sourceTranslation.Ast, sourceTranslation.Serializer);
In essence the `AsQueryable` itself is ignored.

2023-11-29 18:50 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CountMethodToAggregationExpressionTranslator.cs
> +                QueryableMethod.LongCountWithPredicate
This commit only a POC.

We will have to go through the entire LINQ3 codebase and add support Queryable methods wherever Enumerable methods are processed.

2023-11-29 18:50 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/WhereMethodToAggregationExpressionTranslator.cs
> +                var predicateLambda = ExpressionHelper.UnquoteLambdaIfQueryableMethod(method, arguments[1]);
The predicate is ONLY quoted when using the Queryable.Where method.

2023-12-01 00:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/NestedAsQueryableSerializer.cs
> +    internal class NestedAsQueryableSerializer<TITem> : IQueryableSerializer<TITem>, INestedAsQueryableSerializer
This class is a way of tracking that a nested queryable came from a use of AsQueryable.

2023-12-01 00:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AsQueryableMethodToAggregationExpressionTranslator.cs
> +                return new AggregationExpression(expression, sourceTranslation.Ast, nestedAsQueryableSerializer);
In the previous commit we were using the source serializer directly, but that's wrong because that serializer has the wrong ValueType.

2023-12-01 00:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsMethodToAggregationExpressionTranslator.cs
> +            NestedAsQueryableHelper.EnsureQueryableMethodHasValidSource(expression, sourceTranslation.Serializer);
This verification might be overkill, but I'm worried about blindly translating Queryable methods that we shouldn't.

2023-12-01 00:40 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/WhereMethodToAggregationExpressionTranslator.cs
> +                return new AggregationExpression(expression, ast, resultSerializer);
The serializer's ValueType MUST match the expression.Type.

2023-12-07 01:17 UTC, JamesKovacs reviewed
I'm good with the overall direction of this PR. From a purest point of view, enumerables and queryables are different beasts. But in actual practice, developers tend to use them interchangeably whether we agree or not. I think it is reasonable to make this change so that our LINQ implementation matches user expectations.

2023-12-14 23:28 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/EnumerableMethod.cs
> +        public static bool IsToArrayMethod(MethodCallExpression methodCallExpression, out Expression sourceExpression)
Not all ToArray methods are declared in the Enumerable class.

So we're being a bit more general here. Any ToArray method that "looks" right is considered a ToArray method.

2023-12-14 23:30 UTC, rstam commented
The general pattern of how each translator method had to be modified to support nested AsQueryable is:

1. Accept the Queryable equivalent of the relevant method
2. If it's a queryable method ensure the source is a nested AsQueryable
3. If it's a queryable method with lambda arguments they need to be Unquoted
4. Use the correct serializer for the result

2024-01-13 00:59 UTC, JamesKovacs requested changes
The new tests are passing only on MongoDB 6.0. Earlier MongoDB versions (e.g. 3.6) fail with an error `$sortArray` does not exist. Later versions (including latest) fail with array results coming back in an unexpected order. Probably worthwhile figuring out why the new tests aren't behaving as expected before we do an in-depth review of the code.

2024-01-18 16:58 UTC, rstam commented
I've refactored the few failing tests to pass on all server versions.

2024-01-19 20:01 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodCallExpressionToAggregationExpressionTranslator.cs
> +                case "ElementAt":
Not sure why these and the FirstOrDefault/LastOrDefault are needed here.

2024-01-19 20:14 UTC, damieng reviewed
Just a few questions really and one possible omission.

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodCallExpressionToAggregationExpressionTranslator.cs
> +                case "ElementAtOrDefault":
It's not clear why  ElementAtOrDefault/FirstOrDefault/LastOrDefault are part of this work.

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                            var2: AstExpression.VarBinding(restVar, AstExpression.Slice(sourceAst, 1, int.MaxValue)),
Can you clarify why this is part of the AsQueryable work?

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CountMethodToAggregationExpressionTranslator.cs
> +                QueryableMethod.LongCountWithPredicate
Is this now done?

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ElementAtMethodToAggregationExpressionTranslator.cs
> +                if (method.IsOneOf(__elementAtOrDefaultMethods))
Presumably this PR is also adding support for ElementAtOrDefault for both Enumerable and Queryable?

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/FirstOrLastMethodToAggregationExpressionTranslator.cs
> +                if (method.IsOneOf(__orDefaultMethods))
Again, additional support for FirstOrDefault/LastOrDefault for both Queryable and Enumerable?

2024-01-19 20:14 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/MaxOrMinMethodToAggregationExpressionTranslator.cs
> +            QueryableMethod.MinWithSelector
Why do we need signatures for Enumerable's Min/Max with the types but only Min/Max without types on Queryable?

2024-01-19 21:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodCallExpressionToAggregationExpressionTranslator.cs
> +                case "ElementAtOrDefault":
Because you can use these methods with an `IQueryable` value. 

It could have been factored out into a separate ticket but it's more convenient to do it now.

2024-01-19 21:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                            var2: AstExpression.VarBinding(restVar, AstExpression.Slice(sourceAst, 1, int.MaxValue)),
Becuase we're making changes anyway and it's an opportunity to make a small improvement.

2024-01-19 21:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/CountMethodToAggregationExpressionTranslator.cs
> +                QueryableMethod.LongCountWithPredicate
This is now done. Other than finishing the code review.

2024-01-19 21:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ElementAtMethodToAggregationExpressionTranslator.cs
> +                if (method.IsOneOf(__elementAtOrDefaultMethods))
Yes. And they are both tested.

2024-01-19 21:51 UTC, damieng approved these changes

2024-01-23 21:28 UTC, sanych-sun approved these changes
LGTM

2024-01-26 23:06 UTC, JamesKovacs approved these changes
LGTM. Minor refactoring suggested.

2024-01-27 00:07 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ContainsMethodToAggregationExpressionTranslator.cs
> +            if (method.IsOneOf(EnumerableMethod.Contains, QueryableMethod.Contains))
I probably haven't been super consistent about this but usually I extract the list of methods into a static field when there are 3 or more method names. With just 2 it's a toss up.

2024-01-28 00:38 UTC, merged