CSHARP-4615: Switch to polling monitoring on FaaS environment.
mongodb/mongo-csharp-driver pull request #1237
Opened 2023-12-15 18:03 UTC by adelinowona

2023-12-19 15:48 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            _eventLoggerSdam.LogAndPublish(new ServerHeartbeatStartedEvent(connection.ConnectionId, _streamingEnabled && _currentDescription.TopologyVersion != null));
Adding this here as the spec tests seemed to require that the first server heartbeat events have the awaited field as false. Before this change we were only started logging server heartbeat events after the initial handshake (by then we know if the server supports streaming thus the awaited field would not be false causing spec tests to fail). I don't know if that was a requirement but I couldn't find anything about not emitting heartbeat events in the initial handshake in the specs. 

TLDR; I added the logging of server heartbeats when we initialize the server monitor connection as it is technically a heartbeat event.

2023-12-19 15:59 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> -            // no ServerHeartbeat events should be triggered during initial handshake
Is this driver's requirement or just one set for the C# driver? I couldn't find reasoning for this in the specs.

2023-12-19 16:05 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                    case ServerHeartbeatFailedEvent serverHeartbeatFailedEvent:
These cases are very similar to each other and thought of collapsing them to the same together but I don't know how to do that while keeping the captured variable like:
case Event1:
case Event2:
case Event3 variable:
   variable is either of type Event1, Event2, Event3.

2024-01-11 02:40 UTC, BorisDog requested changes
Partial review, looks great so far.

2024-01-11 02:40 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +        private bool _streamingEnabled;
minor: `_isStreamingEnabled`

2024-01-11 02:40 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            _eventLoggerSdam.LogAndPublish(new ServerHeartbeatStartedEvent(connection.ConnectionId, _streamingEnabled && _currentDescription.TopologyVersion != null));
Yes this part is not consistent among drivers, and is being clarified in [DRIVERS-2677](https://jira.mongodb.org/browse/DRIVERS-2677).
This also should affect logging tests.
I would suggest to temporary adapt the tests accordingly, and make the code change if needed in [CSHARP-4831](https://jira.mongodb.org/browse/CSHARP-4831). Let's discuss more offline if needed.

2024-01-11 02:40 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                                               heartbeatHelloResult != null &&
formatting: new lines alignment (no need for parenthesis) 
```
var serverSupportsStreaming = newDescription.Type != ServerType.Unknown &&
   heartbeatHelloResult != null &&
   ...
```

2024-01-11 02:40 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            return (Environment.GetEnvironmentVariable("AWS_EXECUTION_ENV")?.StartsWith("AWS_Lambda_") ?? false) ||
I could not find this in spec PR, is this specified in spec somewhere?

2024-01-11 23:31 UTC, BorisDog requested changes

2024-01-11 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                if ((!_streamingEnabled || (_streamingEnabled && connection.Description.HelloResult.TopologyVersion == null)) && helloResult != null)
Equivalent to shorter  `(!_streamingEnabled || connection.Description.HelloResult.TopologyVersion == null)` ?

2024-01-11 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ServerSettingsTests.cs
> +            subject.ServerMonitoringMode.Should().Be(ServerMonitoringMode.Stream);
We can verify just the `ServerMonitoringMode` here and in `With_serverMonitoringMode_should_return_expected_result`?

2024-01-11 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> -            // no ServerHeartbeat events should be triggered during initial handshake
The spec is not clear about this, so other drivers might have different behavior. I think we should change this in different ticket.

2024-01-11 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            Environment.SetEnvironmentVariable("VERCEL", "vercel");
Do we want to test all environment variables?

2024-01-11 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                    case ServerHeartbeatFailedEvent serverHeartbeatFailedEvent:
You could use dynamic, but that's hacky.
Another option is to have `BsonDocument GetHeartbeatDocument(IEvent event)` helper.

2024-01-11 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                   Environment.GetEnvironmentVariable("AWS_LAMBDA_RUNTIME_API") != null ||
Maybe it's worth specifying the FAAS provider in a comment for each var.

2024-01-11 23:31 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            serverMonitoringMode.GetValueOrDefault(settings.ServerMonitoringMode);
minor: could place assignment in the same line.

2024-01-18 17:45 UTC, sanych-sun requested changes

2024-01-18 17:45 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +        bool Started { get; }
_Minor_: should it be named `IsStarted`?

2024-01-18 17:45 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                lock (_lock)
Are we expecting high concurrency here? If so - it's better to use ReaderWriterLockSlim so to have let multiple readers read the value in parallel.

2024-01-18 17:45 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +            _started = true;
Having lock on read and no-lock on write looks suspicious. We either need both or none.

2024-01-18 18:06 UTC, JamesKovacs commented on src/MongoDB.Driver.Legacy/MongoServerSettings.cs
> +        public ServerMonitoringMode ServerMonitoringMode
Excellent point. Customers shouldn’t be using the legacy driver anymore, especially for new applications. FaaS apps are by definition new apps as cloud providers only introduced these capabilities relatively recently. We can remove the changes in legacy.

2024-01-18 18:23 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                lock (_lock)
I don't think we are expecting high concurrency here, so I will lean towards leaving it as is for now.

2024-01-18 23:00 UTC, BorisDog requested changes

2024-01-18 23:00 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                lock (_lock)
Actually we don't need any kind of synchronization at all here.
Proposed refactoring would eliminate the need of this property. Otherwise `Started => _roundTripTimeMonitorThread != null`  would be sufficient.

2024-01-20 00:48 UTC, BorisDog requested changes

2024-01-20 00:48 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +        private bool UsingStreamingProtocol(HelloResult helloResult)
1. Alphabetical order.
2. Personal preference : consider short arrow form `=>`
3. Also consider `IsUsingStreamingProtocol` as just `Using` might be read as some action.

2024-01-20 00:48 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                var serverSupportsStreaming = newDescription.Type != ServerType.Unknown &&
Alignment of new lines should be: 
```
var serverSupportsStreaming = newDescription.Type != ServerType.Unknown &&
   heartbeatHelloResult != null &&
   heartbeatHelloResult.TopologyVersion != null;
```

2024-01-20 00:48 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +        private bool IsRunningInFaaS()
Place with `IsUsing`, in alphabetical order.

2024-01-20 00:48 UTC, BorisDog commented on src/MongoDB.Driver/MongoDB.Driver.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="1.8.0" />
unrelated change.

2024-01-20 00:48 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            SpinWait.SpinUntil(() => mockConnection.GetSentMessages().Count >= 1, TimeSpan.FromSeconds(5)).Should().BeTrue();
I don't understand how this test works, let's sync offline.

2024-01-20 00:48 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +        }
It this stable?
Waiting for >= 2 events, but checking for 4.

2024-01-20 00:48 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            Environment.SetEnvironmentVariable(environmentVariableName, null);
try/finally. Or even better move `DisposableEnvironmentVariable` to utils and reuse it.

2024-01-23 17:44 UTC, sanych-sun approved these changes
LGTM + minor comment

2024-01-23 17:44 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                if (UsingStreamingProtocol(connection.Description.HelloResult) is not true)
Minor: why do we need pattern matching here? Probably could be simplified with:
`if (!UsingStreamingProtocol(connection.Description.HelloResult))`

2024-01-24 22:07 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +        }
Waiting for the 2 sent messages should generate the 4 heartbeat events. Indeed it was a bit unstable and I had already fixed it locally. I just have to push the changes. Basically now I am straight up waiting for the 4 events to be ready before proceeding.

2024-01-26 03:09 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            SpinWait.SpinUntil(() => mockConnection.GetSentMessages().Count >= 1, TimeSpan.FromSeconds(5)).Should().BeTrue();
Discussed offline.

2024-01-26 16:26 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +                        { "counter", new BsonInt64(0) }
This was a bug as the `Topology` get method from `HelloResult` expects this to be a 64-bit int and thus silently fails omitting the topology version even though it was provided in the response. This caused my tests to not behave properly even when I knew the server supported streaming based on the responses.

2024-01-31 22:58 UTC, BorisDog requested changes

2024-01-31 22:58 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +                        { "counter", new BsonInt64(0) }
nice find

2024-01-31 22:58 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +                TimeSpan.FromMilliseconds(100),
Can we try even lower heartbeat interval, like 5ms in all tests?

2024-01-31 22:58 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/DisposableEnvironmentVariable.cs
> +public class DisposableEnvironmentVariable : IDisposable
nice.
make is sealed for Bon tone.

2024-01-31 22:58 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> + *
revert?

2024-02-01 16:08 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            SpinWait.SpinUntil(() => capturedEvents.Count >= 4, TimeSpan.FromSeconds(5)).Should().BeTrue();
`IsStarted` is setup in the `CreateSubject` method, it switches to returning true after it is called once. I will add checking `IsStarted` call count as well.

2024-02-01 20:25 UTC, BorisDog approved these changes
LGTM! + minor comment

2024-02-01 20:47 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +using FluentAssertions;
Nope I'll remove it!

2024-02-08 23:41 UTC, merged