CSHARP-4891: Append driverInfo to DriverDocument
mongodb/mongo-csharp-driver pull request #1241
Opened 2023-12-21 03:02 UTC by BorisDog

`DriverInfo` name was inspired by Python driver.

2023-12-21 23:09 UTC, rstam requested changes
Also pending is the discussion about whether `DriverInfo` should more accurately be named `LibraryInfo`.

2023-12-21 23:09 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionSettings.cs
> +        public DriverInfo DriverInfo
Put in alphabetical order.

2023-12-21 23:09 UTC, rstam commented on src/MongoDB.Driver/AggregateExpressionDefinition.cs
> +using MongoDB.Driver.Core.Connections;
Seems like an accidental change that should not be made.

2023-12-22 02:29 UTC, rstam requested changes
Overall looks good. Some minor changes requested.

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionSettings.cs
> +        /// Information of library using .NET driver.
Suggested rephrasing:

    /// Information about a library using the .NET driver.

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LibraryInfo.cs
> +        /// <param name="version">Library version.</param>
Suggested rephrasing:

    /// <param name="name">The library name.</param>
    /// <param name="version">The library version.</param>

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver.Legacy/MongoServerSettings.cs
> +                null,
Consider the self documenting:

    libraryInfo: null,

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/ClusterKey.cs
> +                object.Equals(_libraryInfo, rhs.LibraryInfo) &&
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        /// Gets or sets an information of a library using .NET Driver.
Suggested rephrasing:

    /// Gets or sets information about a library using the .NET Driver.

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        private LibraryInfo _libraryInfo;
Consider setting `_libraryInfo` to null in the constructor (I know it's technically no necessary but we set other properties to null also in the constructor and it could be considered good practice to set initial values explicitly and not rely on default values).

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        private LibraryInfo _libraryInfo;
Also in the FromUrl method.

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +            clone._libraryInfo = _libraryInfo;
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                object.Equals(_libraryInfo, rhs._libraryInfo) &&
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                .Hash(_libraryInfo)
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +            }
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                _libraryInfo,
Put in alphabetical order?

2023-12-22 02:29 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LibraryInfo.cs
> +    /// Represents the information of library using .NET driver.
Suggested rephrasing:

    /// Represents information about a library using the .NET driver.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionSettings.cs
> +        /// Information of library using .NET driver.
Thanks, done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LibraryInfo.cs
> +    /// Represents the information of library using .NET driver.
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LibraryInfo.cs
> +        /// <param name="version">Library version.</param>
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver.Legacy/MongoServerSettings.cs
> +                null,
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/ClusterKey.cs
> +                object.Equals(_libraryInfo, rhs.LibraryInfo) &&
Thanks, done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        private LibraryInfo _libraryInfo;
Good point, done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        /// Gets or sets an information of a library using .NET Driver.
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                object.Equals(_libraryInfo, rhs._libraryInfo) &&
Thanks, done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                .Hash(_libraryInfo)
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +            }
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                _libraryInfo,
Done.

2023-12-22 18:23 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +            clone._libraryInfo = _libraryInfo;
Done.

2023-12-22 18:36 UTC, rstam approved these changes
LGTM

2023-12-22 19:31 UTC, merged