CSHARP-4540: Add full support for $dateFromString.
mongodb/mongo-csharp-driver pull request #1242
Opened 2023-12-27 21:51 UTC by rstam

2023-12-27 21:55 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoDBFunctionsExtensions.cs
> +        public static DateTime DateFromString(
Expressions in LINQ queries can't have default parameters, so that's why there are multiple overloads.

2023-12-27 21:55 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoDBFunctionsExtensions.cs
> +    public static class MongoDBFunctionsExtensions
This approach for MongoDB specific extension methods to be used in LINQ queries is copied from the pending PR for CSHARP-4858. 

If the approach changes there we will change it here also.

2023-12-27 21:56 UTC, rstam commented
You should probably review the Exists/IsMissing PR first:

https://github.com/mongodb/mongo-csharp-driver/pull/1224

2024-01-11 00:57 UTC, JamesKovacs approved these changes
LGTM

2024-01-11 01:00 UTC, JamesKovacs requested changes
See previous comment about `$dateFromString` failing in 3.6.

2024-01-12 17:48 UTC, JamesKovacs approved these changes
LGTM

2024-01-20 17:45 UTC, rstam commented
Rebased on master and 4548 approach using static Mql method and force pushed.

2024-01-23 21:49 UTC, sanych-sun requested changes
Looks good. Just some minor comments. Please take a look if you want to take the ideas on board.

2024-01-23 21:49 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4540Tests.cs
> +        public void Parse_should_work(int id, string expectedResult, LinqProvider linqProvider)
Somehow I do not like the idea to mix positive and negative tests, but I do not have enough arguments to insist on separating them.

2024-01-23 21:49 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4540Tests.cs
> +            }
It might makes sense to move code on lines 67-76 into helper method (`AssertResult`?) and reuse it from all tests in the class.

2024-01-24 02:15 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4540Tests.cs
> +        public void Parse_should_work(int id, string expectedResult, LinqProvider linqProvider)
I hear you... but I also like that these are all variants of the exact same test scenario,  just with different data, and that in some cases the result is a string value and in some cases the result is an exception.

It makes it a lot easier to confirm that you are covering all desired scenarios (whether they throw or not) when all the `InlineData` lines are clustered together.

2024-01-24 02:15 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4540Tests.cs
> +            }
I considered that but there are slight variations from test to test that make that hard.

One thing that makes it hard is that in some tests the exception is thrown during translation and in other tests the exception is thrown when executing the query.

I can pursue further if you really want me to. There are only 4 test methods so not a huge amount of sharing, and the sharing benefit is reduced by the added complication.

2024-01-26 17:00 UTC, sanych-sun approved these changes
LGTM

2024-01-26 17:03 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4540Tests.cs
> +    public class CSharp4540Tests : Linq3IntegrationTest
Consider to rename the class to something like `DateFromStringMethodTranslatorTests` or make tests name to include the `DateFromString` term (not just `Parse_should_work` but `Parse_from_date_string_should_work`) to provide some more context on what we are testing here.

2024-01-26 22:19 UTC, JamesKovacs approved these changes
LGTM

2024-01-28 00:36 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/DateFromStringMethodToAggregationExpressionTranslatorTests.cs
> +    public class DateFromStringMethodToAggregationExpressionTranslatorTests : Linq3IntegrationTest
@sanych-sun I moved the tests here as you suggested.

2024-01-28 00:36 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/DateFromStringMethodToAggregationExpressionTranslatorTests.cs
> +            AssertOutcome(collection, queryable, expectedStages, expectedResult);
@sanych-sun I was able to share assertion code as you suggested in an earlier review but it took 5 methods instead of one. See what you think.

2024-01-29 23:06 UTC, sanych-sun approved these changes
LGTM

2024-01-29 23:06 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/DateFromStringMethodToAggregationExpressionTranslatorTests.cs
> +            AssertOutcome(collection, queryable, expectedStages, expectedResult);
If there is so much differences it might be easier to leave validation in each test method.  \I'm OK with both versions. Please choose what looks better for you.

2024-01-30 18:44 UTC, merged