CSHARP4886: Mark API that will be removed in 3.0 as obsolete: MongoDB.Bson
mongodb/mongo-csharp-driver pull request #1243
Opened 2023-12-28 18:41 UTC by BorisDog

Additional entities to consider: 
Utf8Helper
IBsonChunk
IBsonChunkSource
IByteBuffer
IChildSerializerConfigurable

2024-01-04 18:55 UTC, rstam requested changes
First: I think we are doing this way too prematurely. Am waiting for @JamesKovacs to get back to revisit this question with him.

Second: I think there is some uncertainty about *what* exactly is going to be deprecated. We won't really know for sure until we are close to being done with 3.0 and see what ended up changing and what didn't.

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/AttributedSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonObjectModelSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TupleSerializers.cs
> +        /// Gets this serializer for an item.
/// Gets the serializer for an item.

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/DiscriminatedInterfaceSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/CreatorMapDelegateCompiler.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/IdGenerators/BsonBinaryDataGuidGenerator.cs
> +        [Obsolete("This method will be removed in later release. Please use UnspecifiedInstance instead")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/IdGenerators/ZeroIdChecker.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/PrimitiveSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Bson/Serialization/TypeMappingSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Really?

2024-01-04 18:55 UTC, rstam commented on tests/BuildProps/Tests.Build.props
> +      1701;1702; <!--https://github.com/dotnet/roslyn/issues/19640-->
This is a sign that these changes will be painful for our users.

2024-01-04 18:55 UTC, rstam commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    </NoWarn>
This is a sign that these changes will be painful for our users.

2024-03-06 21:17 UTC, BorisDog reviewed
Addressed some of the comments.
Please advise what else needs to be deprecated.

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/IdGenerators/BsonBinaryDataGuidGenerator.cs
> +        [Obsolete("This method will be removed in later release. Please use UnspecifiedInstance instead")]
Yes, directing to use `UnspecifiedInstance` instead.

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/IdGenerators/BsonBinaryDataGuidGenerator.cs
> +        public static BsonBinaryDataGuidGenerator UnspecifiedInstance
Yes, fixing a typo.

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/IdGenerators/ZeroIdChecker.cs
> +    [Obsolete("This class will be removed in later release.")]
Reverted.

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/PrimitiveSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Will our user be needing our built-in serializer providers?

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/TupleSerializers.cs
> +        /// Gets this serializer for an item.
Thanks, done.

2024-03-06 21:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    </NoWarn>
But hopefully significantly less painful than just removing API in 3.0 without prior warning.

2024-03-06 21:17 UTC, BorisDog commented on tests/BuildProps/Tests.Build.props
> +      1701;1702; <!--https://github.com/dotnet/roslyn/issues/19640-->
But hopefully significantly less painful than just removing API in 3.0 without prior warning.

2024-03-13 17:48 UTC, rstam requested changes

2024-03-13 17:48 UTC, rstam commented on src/Directory.Build.props
> +      CS0618 <!--Temporary disable obsolete warnings due the massive volume of warnings-->
I think we should have a goal that users who stay on 2.x don't have to deal with these warnings at all.

2024-03-13 17:48 UTC, rstam commented on src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Users can write custom serialization providers and in general configure any mix of serialization providers in any order. To do so the providers need to be public.

Removing these classes (or making them internal) removes a feature.

2024-03-13 17:48 UTC, rstam commented on src/MongoDB.Bson/Serialization/CreatorMapDelegateCompiler.cs
> +    [Obsolete("This class will be removed in later release.")]
I thought when you said "removed" you meant "removed".

It probably can be made `internal`.

2024-03-13 17:48 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonSymbol.cs
> +﻿/* Copyright 2010-present MongoDB Inc.
What happened here?

Why does the entire file appear to be modified?

Same for several other files below.

2024-03-13 17:48 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonValueSerializer.cs
> +/* Copyright 2010-present MongoDB Inc.
Hard to tell if you changed anything in this file or not...

Same for several other files.

2024-07-09 20:48 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
> +    [Obsolete("This class will be removed in later release.")]
Do we really need the predefined providers to be public, is our intent to fully support that API going forward?
Looks like they all are added in `CreateSerializerRegistry` and user has no control over it.

2024-07-09 20:48 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/CreatorMapDelegateCompiler.cs
> +    [Obsolete("This class will be removed in later release.")]
Updated the comments.

2024-07-23 20:46 UTC, rstam requested changes

2024-07-23 20:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/AttributedSerializationProvider.cs
> +    [Obsolete("This class will be removed from public API in later release.")]
Why are we removing serialization providers, including this one?

The user is supposed to be able to configure the serialization providers they want to use.

2024-07-23 20:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/AttributedSerializationProvider.cs
> +    [Obsolete("This class will be removed from public API in later release.")]
Same for similar obsoletions below...

2024-07-23 20:46 UTC, rstam commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    </NoWarn>
We can't leave this in here.

This is going to hide important warnings even from ourselves!!!

2024-07-23 20:46 UTC, rstam commented on src/Directory.Build.props
> +      CS0618 <!--Temporary disable obsolete warnings due the massive volume of warnings-->
We can't leave this in here.

This is going to hide important warnings even from ourselves!!!

2024-10-17 23:22 UTC, BorisDog commented
Stale PR.

2024-10-17 23:22 UTC, closed without merging