CSHARP-4900: Uploading a duplicate file larger than the original one …
mongodb/mongo-csharp-driver pull request #1244
Opened 2024-01-09 02:14 UTC by sanych-sun

…causes errors in downloading the original file

2024-01-12 00:03 UTC, BorisDog requested changes
Looks greats, minor comments.
Also need to double check whether aborting on all exceptions is correct.

2024-01-12 00:03 UTC, BorisDog commented on src/MongoDB.Driver.GridFS/GridFSForwardOnlyUploadStream.cs
> +            try
Consider `ExecuteOrAbort` wrappers.

2024-01-17 21:58 UTC, sanych-sun commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
I would prefer to fill the "files" with some content, to double-check if the original file was not overwritten or damaged.

2024-01-18 21:17 UTC, BorisDog requested changes

2024-01-18 21:17 UTC, BorisDog commented on src/MongoDB.Driver.GridFS/GridFSForwardOnlyUploadStream.cs
> +                await filesCollection.InsertOneAsync(filesCollectionDocument, cancellationToken: cancellationToken).ConfigureAwait(false);
nit: you could return `filesCollection.InsertOneAsync` task directly  and skip additional task wrapper.

2024-01-18 21:17 UTC, BorisDog commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Ok, then `var random = new Random() `

2024-01-18 22:18 UTC, rstam commented on src/MongoDB.Driver.GridFS/GridFSForwardOnlyUploadStream.cs
> +        private void ExecuteOrAbort(Action action)
Consider a more accurate name like `ExecuteSetAbortedOnException`.

But if you don't want to change the name I won't insist.

2024-01-18 22:18 UTC, rstam commented on src/MongoDB.Driver.GridFS/GridFSForwardOnlyUploadStream.cs
> +                    .ConfigureAwait(false);
No need to put `ConfigureAwait(false)` on the next line.

Our usual practice is to place it at the end of the line.

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
How about instead of random content we use deterministic content?

    var bucket = CreateBucket();
    var fileId = ObjectId.GenerateNewId();
    var content1 = new byte[10];
    var content2 = new byte[36_000_000]; // big enough to need more than one batch
    FillArray(content1, 1);
    FillArray(content2, 2);

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Which because of the old target frameworks we test on requires a helper method for now:

    // TODO: use Array.Fill instead once it is available on all our target test frameworks
    static void FillArray(byte[] array, byte value)
    {
        for (var i = 0; i < array.Length; i++)
        {
            array[i] = value;
        }
    }

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +                await bucket.UploadFromBytesAsync(fileId, "unrelevant", content1).ConfigureAwait(false);
I would use `"filename"` as the dummy value for filename.

Also, I don't think "unrelevant" is a word. Normally one says "irrelevant".

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var readContent = async
Consider renaming `readContent` to `uploadedContent`.

Then the assertion reads nicely:

    uploadedContent.Should().Equal(content1);

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +                await bucket.UploadFromBytesAsync(fileId, "unrelevant", content1).ConfigureAwait(false);
`ConfigureAwait(false)` is only needed in driver code, not in test code.

2024-01-18 22:18 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var record = async
var exception = async

We use `exception` as the variable name for the result of `Record.Exception`

2024-01-18 23:11 UTC, BorisDog commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
For same value `var content1 = Enumerable.Repeat((byte)1, 10000).ToArray();` could be used.

2024-01-18 23:14 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
That's what I was going to suggest first but got worried about the overhead when the size of the array was 36 million.

2024-01-18 23:28 UTC, BorisDog commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Right, Gen0 mem would be twice as much. We could also optimize this by reducing the `batchsize`.

2024-01-18 23:31 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
I looked into that also but didn't find an easy way to configure the batch size.

I do like the idea. Then we could test with smaller chunks and smaller batches and use much less memory (and network traffic).

2024-01-18 23:33 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Actually it does seem easy to configure the chunk size and the batch size.

The `UploadFromBytes` has an optional `GridFSUploadOptions` parameter I hadn't noticed.

2024-01-19 17:31 UTC, sanych-sun commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Regarding configuring smaller batch - will do.

2024-01-19 17:32 UTC, sanych-sun commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Regarding Random - what the harm to have Random here instead of home grown FillArray method?

2024-01-19 17:34 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
While Random "works" here, it helps in general to have deterministic values in tests. These values can show up in test failure messages.

A message that says "expected 1 but got 2" makes more sense than "expected <some random value> but got <some other random value>".

2024-01-19 17:50 UTC, sanych-sun commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var r = new Random();
Ok, will do.

2024-01-19 20:09 UTC, BorisDog approved these changes
LGTM

2024-01-19 23:39 UTC, rstam approved these changes
LGTM

2024-01-19 23:39 UTC, rstam commented on tests/MongoDB.Driver.GridFS.Tests/GridFSUploadStreamTests.cs
> +            var content2 = Enumerable.Repeat((byte)2, 100).ToArray();
With small arrays this approach is fine (instead of the proposed FillArray method).

2024-01-24 21:51 UTC, merged