CSHARP-4927: Add support for Atlas Search $in operator to builder
mongodb/mongo-csharp-driver pull request #1249
Opened 2024-01-18 20:37 UTC by BorisDog

2024-01-19 20:46 UTC, sanych-sun requested changes

2024-01-19 20:46 UTC, sanych-sun commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private static BsonValue ToBsonValue(TField value) =>
Do we have limited list of mapped types here (BTW is decimal and ulong out)? or should we use `BsonTypeMapper` instead to support wide variety or types?

2024-01-19 20:46 UTC, sanych-sun commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            _value = Ensure.That(array, arr => arr.All(v => v.GetType() == bsonType), nameof(values), "All values must be of same type");
Should it be: All values must be of **the** same type

2024-01-19 20:46 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            results[0].Title.Should().Be("Home from Home: Chronicle of a Vision");
Should we check value of the `Runtime`, the field used for filtering?

2024-01-19 20:46 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +             new object[] { new short[] { 1, 2 }, new[] { "1", "2" } },
Is this test case is exact copy of the previous one?

2024-01-19 20:46 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +             new object[] { new sbyte[] { 1, 2 }, new[] { "1", "2" } },
Do we need test for `byte[]`

2024-01-19 20:46 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        [MemberData(nameof(RangeUnsupportedTypesTestData))]
Should we use `InUnsupportedTypesTestData` here instead?

2024-01-19 21:30 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            _value = Ensure.That(array, arr => arr.All(v => v.GetType() == bsonType), nameof(values), "All values must be of same type");
Thanks, done.

2024-01-19 21:30 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private static BsonValue ToBsonValue(TField value) =>
Good question, it's a subset of bson types:  bool, number, string, objectId, date
https://www.mongodb.com/docs/atlas/atlas-search/in/.

ulong: is not explicitly supported
guid: is not explicitly supported
decimal: added support

2024-01-19 21:30 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +             new object[] { new sbyte[] { 1, 2 }, new[] { "1", "2" } },
We do, thanks.

2024-01-19 21:30 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +             new object[] { new short[] { 1, 2 }, new[] { "1", "2" } },
Yes, thanks for catching this.

2024-01-19 21:30 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        [MemberData(nameof(RangeUnsupportedTypesTestData))]
Yes, it's practically the same, so it worked :)

2024-01-19 21:30 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            results[0].Title.Should().Be("Home from Home: Chronicle of a Vision");
Just wanted to be aligned with other tests, where title was checked (which implied the specific expected result).
But changed to Runtime for simplicity.

2024-01-19 21:31 UTC, sanych-sun commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private static BsonValue ToBsonValue(TField value) =>
Makes sense. Thank you for details.

2024-01-19 21:34 UTC, sanych-sun approved these changes
LGTM

2024-01-19 23:52 UTC, rstam requested changes

2024-01-19 23:52 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            TField[] values,
In existing APIs we have tended to use `IEnumerable<TField>` instead of `TField[]` to allow the caller to use a wider range of enumerable types.

Do you want to consider that here?

2024-01-19 23:52 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            TField value,
Why do we need a single value version? Wouldn't the caller almost always use multiple values?

And in those cases where they only have one value they can just pass in a list with only one item.

This overload also risks creating ambiguities with the overload that takes multiple values.

Consider having only two overloads instead of four.

2024-01-23 19:50 UTC, rstam requested changes

2024-01-23 19:50 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly BsonValue _value;
The type of this field should probably be `BsonArray`.

2024-01-23 19:50 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly BsonValue _value;
And be named `_values` (plural).

2024-01-23 19:50 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly BsonValue _value;
Although... the server some reason used `value`?

It's odd they didn't use the plural.

But we should probably stay with the plural form right up until we render it JSON.

2024-01-23 19:57 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly BsonValue _value;
Done.

2024-01-23 21:42 UTC, merged