Records and Optional<T> demo
mongodb/mongo-csharp-driver pull request #1251
Opened 2024-01-19 20:04 UTC by BorisDog

- Records demo
- Removal of Optional<T>

2024-01-28 14:14 UTC, barbahgamesfounder approved these changes

2024-01-29 18:28 UTC, rstam requested changes
Overall I see no serious issues with using `record` for our settings classes (and other classes also).

There is still an issue when calling a constructor with how to tell the difference between the caller omitting an optional argument and passing `null`. In the first case we might want to supply a default value, in the second we would want to respect the explicitly passed `null`.

    new Settings() ;  // assigns a default value to `OptionalProperty`
    new Settings(optionalProperty: null); // also assigns a default value to `OptionalProperty` instead of null    


It might be that the only way a user can explicitly set a property to null is:

    new Settings() with { OptionalProperty = null };

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        public static TimeSpan IsGreaterThanZero(TimeSpan value, [CallerArgumentExpression("value")]string paramName = "value") =>
Once you use `CallerArgumentExpression` it's no longer a `paramName`, it's a string representing the expression the caller used to provide the argument when calling this method.

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        public static TimeSpan IsGreaterThanZero(TimeSpan value, [CallerArgumentExpression("value")]string paramName = "value") =>
In the next line `IsGreaterThan` expects a parameter name as its last argument, not a string representing the caller's argument expression.

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        public static TimeSpan IsGreaterThanZero(TimeSpan value, [CallerArgumentExpression("value")]string paramName = "value") =>
The net result is that the following line of code on line 97:

```throw new ArgumentOutOfRangeException(paramName, message)```

might be called with a value for  `paramName` that is not a parameter name, but rather a string representing an `Expression`. That seems wrong.

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver/RenderContext.cs
> +    public sealed record RenderContext<TDocument>
The old class name was `SearchDefinitionRenderContext`.

Are you implying that this `RenderContext` class will be used in more places?

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver/RenderContext.cs
> +    public sealed record RenderContext<TDocument>
Seems like you are proposing replacing multiple `Render` arguments with an instance of this class.

In which case the name `RenderArgs` might be more appropiate.

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver/RenderContext.cs
> +            init => _documentSerializer = Ensure.IsNotNull(value, nameof(value));
A good example of why I prefer we standardize on using explicit backing fields (like `_documentSerializer`) instead of auto properties.

2024-01-29 18:28 UTC, rstam commented on src/MongoDB.Driver/RenderContext.cs
> +    public sealed record RenderContext<TDocument>
And should probably be a a `struct` to avoid an extra memory allocation.

2024-07-10 01:03 UTC, closed without merging

2024-07-10 01:03 UTC, BorisDog commented
Closing this draft PR which started as POC for RenderArgs and using records, which was implemented in https://github.com/mongodb/mongo-csharp-driver/pull/1278.