Release notes for 2.24.0.
mongodb/mongo-csharp-driver pull request #1261
Opened 2024-02-09 00:40 UTC by rstam

2024-02-09 10:21 UTC, damieng reviewed
No mention of nested AsQueryable support?

2024-02-13 16:40 UTC, rstam commented
> No mention of nested AsQueryable support?

Good question. I didn't want to mention it since no user should ever be writing queries this way. This feature was solely for the benefit of the EF Core Provider.

@JamesKovacs what do you think?

2024-02-13 22:18 UTC, JamesKovacs commented
> > No mention of nested AsQueryable support?
> 
> Good question. I didn't want to mention it since no user should ever be writing queries this way. This feature was solely for the benefit of the EF Core Provider.
> 
> @JamesKovacs what do you think?

We should mention it on the off chance that it affects a user's query. We may want to mention that it is intended for internal use only (or however we want to word it).

2024-02-13 22:28 UTC, JamesKovacs requested changes
As noted in my earlier comment, I would mention nested AsQueryable support. I would also add:
- Updated authentication to occur over OP_MSG on supporting servers to improve MongoDB Atlas Serverless compatibility
- Use polling monitoring when running within a FaaS environment such as AWS Lambda
- Fixed segfault in Kerberos (libgssapi) on newer Linux distros

2024-02-13 22:28 UTC, JamesKovacs commented on Release Notes/Release Notes v2.24.0.md
> +* New custom method to test if a field exists or is missing in LINQ
>New custom methods to test if a field exists or is missing in LINQ (Mql.IsMissing, Mql.Exists, Mql.IsNullOrMissing)

2024-02-13 22:59 UTC, rstam commented on Release Notes/Release Notes v2.24.0.md
> +* New custom method to test if a field exists or is missing in LINQ
Done

2024-02-15 18:11 UTC, JamesKovacs approved these changes
LGTM

2024-02-15 19:27 UTC, merged

2024-02-18 12:22 UTC, Evengard commented
The release seems to be absent on NuGet and Github Releases

2024-02-18 16:30 UTC, rstam commented
This is in preparation of the upcoming release of 2.24.0. The release has not happened yet.