CSHARP-4962: Fix package build script on CI to produce 472 binaries
mongodb/mongo-csharp-driver pull request #1264
Opened 2024-02-09 22:07 UTC by sanych-sun

Run packages-pack on Windows host + set priority to 10 for all package-related tasks.

2024-02-09 23:29 UTC, sanych-sun commented on evergreen/evergreen.yml
> +        local_file: mongo-csharp-driver/artifacts/nuget/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg
Windows hosts were not happy with the absolute path, it was threated it as relative.

2024-02-09 23:30 UTC, sanych-sun commented on evergreen/evergreen.yml
> +    os: "windows-64" # should produce package on Windows to make sure full framework binaries created.
Setting host as a matrix_spec axis also set env variable, so platform detection works properly in sh-files.

2024-02-09 23:32 UTC, sanych-sun commented on evergreen/evergreen.yml
> +      priority: 10
When someone starting a release, he/she have to wait for it's completion to move forward with after release manual steps. So I've decided to prioritize package-related steps.

2024-02-13 22:14 UTC, JamesKovacs requested changes
Some questions and suggested simplifications.

2024-02-13 22:14 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +        local_file: mongo-csharp-driver/artifacts/nuget/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg
We use `${PROJECT_DIRECTORY}` throughout `evergreen.yml` and it runs successfully on Windows hosts. Any idea why it is problematic when used for the `local_file` argument?

2024-02-13 22:14 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +    os: "windows-64" # should produce package on Windows to make sure full framework binaries created.
`matrix_name` allows us to run all combinations of the specified `matrix_spec`. Given that the package step is a single action, we can simply use `buildvariants`/`name` with `run_on` similar to `gssapi-auth-tests-windows` or `driver-performance-tests`. No need to invoke the `matrix_*` machinery.

2024-02-13 22:14 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +    os: "ubuntu-2004"
Why are we moving from `ubuntu2004-small` to `ubuntu2004` for these variants?

2024-02-13 23:37 UTC, sanych-sun commented on evergreen/evergreen.yml
> +    os: "windows-64" # should produce package on Windows to make sure full framework binaries created.
But I was unable to properly set the OS expansion/env variable without axis, so the platform detection was not working properly.

2024-02-14 21:52 UTC, sanych-sun commented on evergreen/evergreen.yml
> +    os: "ubuntu-2004"
Basically I've removed explicit run_on by using the matrix_spec (so it would set OS env variable and for consistency). Setting OS axis to "ubuntu-2004" is to be run on the ubuntu2004-small.
```
      - id: "ubuntu-2004"
        display_name: "Ubuntu 20.04"
        variables:
          OS: "ubuntu-2004"
          python3_binary: "/opt/python/3.8/bin/python3"
        run_on: ubuntu2004-small
```

2024-02-14 21:54 UTC, sanych-sun commented on evergreen/evergreen.yml
> +        local_file: mongo-csharp-driver/artifacts/nuget/${PACKAGE_ID}.${PACKAGE_VERSION}.nupkg
As it was discussed offline: s3.put command somehow does not work very well with absolute path on Windows hosts. So will go with relative path as per proposed code.

2024-02-15 21:12 UTC, JamesKovacs approved these changes
LGTM

2024-02-16 18:32 UTC, merged