CSHARP-4432: POC of standard implementations of Equals.
mongodb/mongo-csharp-driver pull request #1273
Opened 2024-02-22 22:23 UTC by rstam

2024-02-22 22:25 UTC, rstam commented
I'm about to implement a bunch of new `Equals` methods. 

Before doing so I'd like us to agree as a team on how we want to implement `Equals` going forward.

2024-02-22 22:37 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableBaseClass.cs
> +            _value1.Equals(other._value1);
Notes:

Some very old articles claim the following is faster than using `object.ReferenceEquals`:

    (object)this == other

but most newer articles say that after JITing they are exactly the same thing. Using `object.ReferenceEquals` is more intention-revealing than the more obscure cast.

We must check that the types are equal. Objects of different types are never equal.

My recommendation is that we NEVER use `==` in the implementation fo `Equals`. Instead, we should always call `Equals` when comparing fields.

The reason is that in some cases `==` and `Equals` do NOT return the same value. When writing and reading `Equals` implementations it is better to standardize on calling `Equals` to compare fields instead of having to analyze field by field whether `==` semantics are correct.

Always use `object.Equals(_ref1, other._ref1)` instead of `_ref1.Equals(other._ref1)` when comparing reference values. That way nulls are handled correctly.

Always use `_value1.Equals(other._value1)` when comparing struct values. That way boxing is usually avoided (most struct classes will implement `IEquatable<T>`).

2024-02-22 22:37 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableDerivedClass.cs
> +            _value2.Equals(other._value2);
Notes:

The `object.ReferenceEquals(this, other)` check must be coded at every level of a polymorphic class hierarchy for the optimization to apply at each level.

No need to check for null or compare types, that happens in `base.Equals`.

2024-02-22 22:37 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableNonPolymorphicClass.cs
> +            _value.Equals(other._value);
No need to compare types because the class is non polymorphic.

This assumption is only valid is the class is `sealed`.

2024-02-22 22:37 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableStruct.cs
> +            _value.Equals(other._value);
No need to check for null because this is a struct.

No need to compare types because structs can't be polymorphic.

2024-02-23 19:24 UTC, sanych-sun approved these changes
LGTM

2024-02-26 22:10 UTC, adelinowona approved these changes
LGTM

2024-02-28 19:05 UTC, BorisDog approved these changes
Looks great overall, one small comment.

2024-02-28 19:05 UTC, BorisDog commented on src/MongoDB.Bson/EqualsPoc/EquatableBaseClass.cs
> +            object.ReferenceEquals(this, other) ||
I'd suggest to check for `null` first.
I think in general a comparison to a different non-derived type is more likely than to the same instance. 
This will also fail faster for `null`-case for derived classes (instead of two subsequent `object.ReferenceEquals(this, other)` calls)
Maybe this is one of the reasons that null check is first in MS examples.

2024-02-28 21:50 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableBaseClass.cs
> +            object.ReferenceEquals(this, other) ||
Good suggestions.

I've refactored to compare to null first.

2024-02-28 21:50 UTC, rstam commented
I've re-requested a review from everyone on this PR.

2024-02-28 23:34 UTC, BorisDog approved these changes
LGTM.

2024-02-29 09:57 UTC, damieng approved these changes
Looks good. I did something similar a while back but had base classes implement CompareTo and get all the other operators https://github.com/damieng/DamienGKit/blob/master/CSharp/DamienG.Library/System/AutoOperators.cs

2024-02-29 16:47 UTC, adelinowona approved these changes
LGTM

2024-03-01 20:58 UTC, sanych-sun requested changes

2024-03-01 20:58 UTC, sanych-sun commented on src/MongoDB.Bson/EqualsPoc/EquatableDerivedClass.cs
> +            return
Should we check if `this` and `other` types are the same? What if someone try to compare `EquatableDerivedClass` with `EquatableDerivedFromDerivedClass`? As far as I understood the current implementation will returns `true` is all local variables would be equal.

2024-03-01 21:16 UTC, rstam commented on src/MongoDB.Bson/EqualsPoc/EquatableDerivedClass.cs
> +            return
If the two objects are not of the same type then `base.Equals` will return `false`.

2024-03-01 21:47 UTC, sanych-sun approved these changes
LGTM

2024-03-14 21:57 UTC, rstam commented
Closing the PR as it is only a POC. See CSHARP-3315 for new examples of Equals methods implemented in this standard way.

2024-03-14 21:57 UTC, closed without merging