CSHARP-4350: Add FaaS tests
mongodb/mongo-csharp-driver pull request #1276
Opened 2024-02-28 22:41 UTC by adelinowona

This is the C# implementation for automated testing of a deployed lambda function.

- Added the lambda function in tests/LambdaTests
- Created the evergreen tasks to execute the scripts in drivers-evergreen-tools. (https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/aws_lambda/run-deployed-lambda-aws-tests.sh)

Spec for this changes can be found here: [mongodb/specifications@master/source/faas-automated-testing/faas-automated-testing.rst](https://github.com/mongodb/specifications/blob/master/source/faas-automated-testing/faas-automated-testing.rst?rgh-link-date=2023-02-14T20%3A45%3A23Z)

What is the motivation for this change?
WRITING-11435/[DRIVERS-2384](https://jira.mongodb.org/browse/DRIVERS-2384)

2024-02-29 17:52 UTC, rstam requested changes
I only reviewed the C# code because I am unfamiliar with the rest of the Evergreen and other configuration.

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +using System;
Do we need a copyright?

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +        public async Task<APIGatewayProxyResponse> LambdaFunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
async method names usually end in `Async`, but maybe this name is forced on us externally?

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            var col = _mongoClient.GetDatabase("lambdaTest").GetCollection<BsonDocument>("test");
We avoid abbreviations. Use `collection`?

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            var testDoc = new BsonDocument("n", 1);
Use `testDocument`?

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            }
Could potentially be simplified to:

```_serverHeartbeatWasAwaited |= @event.Awaited;```

2024-02-29 17:52 UTC, rstam commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            }
Could potentially be simplified to:

```_serverHeartbeatWasAwaited |= @event.Awaited;```

2024-02-29 19:17 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +using System;
Yep. Done

2024-02-29 19:18 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +        public async Task<APIGatewayProxyResponse> LambdaFunctionHandler(APIGatewayProxyRequest apigProxyEvent, ILambdaContext context)
Added `Async`, the function name isn't forced on us externally.

2024-02-29 19:19 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            var col = _mongoClient.GetDatabase("lambdaTest").GetCollection<BsonDocument>("test");
Done.

2024-02-29 19:19 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            var testDoc = new BsonDocument("n", 1);
Done.

2024-02-29 19:19 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            }
Done.

2024-02-29 19:19 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            }
Done.

2024-03-04 15:54 UTC, BorisDog requested changes

2024-03-04 15:54 UTC, BorisDog commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +/* Copyright 2010-present MongoDB Inc.
Looks like we are going to have other FaaS tests, Do we want add `FaaSTests` parent folder?

2024-03-04 15:54 UTC, BorisDog commented on tests/LambdaTests/README.md
> +- src - Code for the application's Lambda function.
`src` is probably not the right folder.

2024-03-04 15:54 UTC, BorisDog commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +                    { "CommandCount", $"{_totalCommandCount}" },
lower case?

2024-03-04 15:54 UTC, BorisDog commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            _openConnections--;
This might be concurrent execution, so better to use `Interlocked.Dec`.

2024-03-06 21:01 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +/* Copyright 2010-present MongoDB Inc.
Done.

2024-03-06 21:02 UTC, adelinowona commented on tests/LambdaTests/README.md
> +- src - Code for the application's Lambda function.
Fixed!

2024-03-06 21:02 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +                    { "CommandCount", $"{_totalCommandCount}" },
fixed!

2024-03-06 21:02 UTC, adelinowona commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            _openConnections--;
Done!

2024-03-06 23:35 UTC, BorisDog commented on tests/FaasTests/LambdaTests/README.md
> +The SAM CLI installs dependencies defined in `tests/LambdaTests/src/MongoDB.Driver.LambdaTest.csproj`, creates a deployment package, and saves it in a `.aws-sam/build` folder.
Update the path, or maybe make it relative?

2024-03-06 23:35 UTC, BorisDog commented on tests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +            _openConnections--;
Sorry I meant that we need to access `_openConnections` in a threadsafe manner, so need to increment it with Interlocked as well.

2024-03-06 23:37 UTC, BorisDog requested changes
minor comments

2024-03-06 23:37 UTC, BorisDog commented on tests/FaasTests/LambdaTests/MongoDB.Driver.LambdaTest/LambdaFunction.cs
> +        private void Reset()
So why do we need reset?

2024-03-12 15:36 UTC, rstam approved these changes
LGTM

2024-03-13 16:02 UTC, sanych-sun approved these changes
LGTM

2024-03-14 14:28 UTC, merged