CSHARP-4988: Fix flaky ServerMonitor test
mongodb/mongo-csharp-driver pull request #1277
Opened 2024-02-29 19:43 UTC by sanych-sun

2024-02-29 19:58 UTC, adelinowona requested changes

2024-02-29 19:58 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            mockConnection.EnqueueCommandResponseMessage(CreateHeartbeatCommandResponseMessage(), TimeSpan.FromMilliseconds(500));
Is it possible to reduce the delay a bit more to like maybe 100ms?

2024-02-29 19:58 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
>              var subject = CreateSubject(out var mockConnection, out _, out var mockRoundTripTimeMonitor, capturedEvents, serverMonitorSettings: serverMonitorSettings);
Also I think you might want remove the serverMonitorSettings variable before this. Looking at the code I don't think it is needed since we will be streaming heartbeats with the server.

2024-02-29 20:32 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            mockConnection.EnqueueCommandResponseMessage(CreateHeartbeatCommandResponseMessage(), TimeSpan.FromMilliseconds(500));
I think it would be great if could not rely on timings at all, and then have much lower intervals like in the rest of tests (5ms).

2024-02-29 20:47 UTC, sanych-sun commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +            mockConnection.EnqueueCommandResponseMessage(CreateHeartbeatCommandResponseMessage(), TimeSpan.FromMilliseconds(500));
So after additional discussion with Boris we decided to remove delays at all, as well as verification of the Start method was called after the very first heartbeat (because the way we detecting the first heartbeat was done is not that reliable)

2024-02-29 20:49 UTC, sanych-sun commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
>              var subject = CreateSubject(out var mockConnection, out _, out var mockRoundTripTimeMonitor, capturedEvents, serverMonitorSettings: serverMonitorSettings);
Done

2024-02-29 20:53 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> -            var serverMonitorSettings = new ServerMonitorSettings(TimeSpan.FromSeconds(5), TimeSpan.FromMilliseconds(10));
I think we still need this to override the higher default interval.

2024-02-29 21:19 UTC, sanych-sun commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> -            var serverMonitorSettings = new ServerMonitorSettings(TimeSpan.FromSeconds(5), TimeSpan.FromMilliseconds(10));
OK, will revert this =)

2024-02-29 23:31 UTC, BorisDog approved these changes
LGTM

2024-03-01 00:32 UTC, adelinowona approved these changes
LGTM

2024-03-01 01:29 UTC, merged