CSHARP-4955: Add Render overload with RenderArgs
mongodb/mongo-csharp-driver pull request #1278
Opened 2024-02-29 21:40 UTC by BorisDog

- Added support for records (IsExternalInit.cs)
- Added RenderArgs overloads
- Removed RenderForFind and FilterDefinitionRenderContext workarounds
- Added obsoletion attributes for older Render methods

2024-02-29 21:46 UTC, BorisDog commented on src/MongoDB.Shared/IsExternalInit.cs
> +    internal class IsExternalInit { }
This is needed for records support.

2024-02-29 21:46 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                        { "filter", () => options.Filter.Render(renderArgs with { RenderDollarForm = true }), options?.Filter != null },
This replaces the workaround with `FilterDefinitionRenderContext`, which is removed now.

2024-02-29 21:46 UTC, BorisDog commented on src/MongoDB.Driver/ProjectionDefinitionBuilder.cs
> +            var sliceArgs = renderArgs.IsAggregateMode ? RenderArgs(renderedField.FieldName) : RenderArgsForFind(renderedField.FieldName);
`IsAggregateMode` replaces `RenderForFind` pattern.

2024-03-06 02:09 UTC, rstam requested changes
I started with a quick review and some initial questions.

2024-07-16 00:36 UTC, rstam requested changes

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingWithOutputExpressionStageDefinitions.cs
> +        public override RenderedPipelineStageDefinition<TOutput> Render(RenderArgs<TInput> renderArgs)
What would you think about using `args` instead of `renderArgs`? (For the parameter name, not the class).

It would result in more compact code everywhere, and we know these `args` for the `Render` method because we are *in* the `Render` method.

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionRenderContext.cs
> +﻿using System;
Missing copyright.

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionRenderContext.cs
> +    public sealed class SearchDefinitionRenderArgs<TDocument>
I don't think we should change the name of this class. It should stay `SearchDefinitionRenderContext`.

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                enderArgs =>
Name should be `renderArgs`, or `args` if you agree with the suggestion to shorten `renderArgs` to `args`.

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                    IEnumerable <BsonDocument> documents;
Extra space accidentally insterted. Should be:

    IEnumerable<BsonDocument> documents;

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +        private readonly bool _isAggregateMode = true;
Any desire to keep these in alphabetical order?

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +            DocumentSerializer as IBsonSerializer<T> ?? SerializerRegistry.GetSerializer<T>();
I would normally use the backing field directly when INSIDE the class:

    _documentSerializer as IBsonSerializer<T> ?? _serializerRegistry.GetSerializer<T>();

It might be faster? Or likely the JITter optimizes it anyway?

In any case, I feel like the properties are for external clients to use, and we can use the backing fields directly.

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Shared/IsExternalInit.cs
> +﻿using System.ComponentModel;
Copyright missing

2024-07-16 00:36 UTC, rstam commented on src/MongoDB.Shared/IsExternalInit.cs
> +    internal class IsExternalInit { }
Add a comment documenting when this class can be removed?

It's only needed for certain older target frameworks right?

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionRenderContext.cs
> +    public sealed class SearchDefinitionRenderArgs<TDocument>
Good catch. Reverted.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                enderArgs =>
Thanks! Done.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                    IEnumerable <BsonDocument> documents;
Fixed.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Driver/RenderArgs.cs
> +        private readonly bool _isAggregateMode = true;
Yes, done.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Shared/IsExternalInit.cs
> +﻿using System.ComponentModel;
Done.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Shared/IsExternalInit.cs
> +    internal class IsExternalInit { }
Added a comment.
It's needed for all frameworks prior to .net5.

2024-07-18 00:44 UTC, BorisDog commented on src/MongoDB.Driver/RenderArgs.cs
> +            DocumentSerializer as IBsonSerializer<T> ?? SerializerRegistry.GetSerializer<T>();
Changed, it's a leftover from before introducing backing fields.

2024-07-18 19:46 UTC, rstam requested changes
Looks good. Main change I'm requesting is to change `RenderArgs.IsAggretateMode` to `RenderArgs.RenderForFind` (see notes in `RenderArgs.cs`).

2024-07-18 19:46 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            return new("operator", _operator.Render( newRenderArgs));
nit: an extra blank snuck in

2024-07-18 19:46 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4742Tests.cs
> +            [Values(true, false)] bool isAggregateMode)
[Values(true, false)] bool renderForFind)

for that matter, do we need to be testing with `renderForFind == true` here?

2024-07-18 19:46 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Linq3IntegrationTest.cs
> +            var renderedProjection = projection.Render(new(documentSerializer, serializerRegistry, linqProvider, isAggregateMode: false));
var renderedProjection = projection.Render(new(documentSerializer, serializerRegistry, linqProvider, renderForFind: true));

2024-07-18 19:46 UTC, rstam commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +            Assert.Equal(expectedProjection, subject.Options.Projection.Render(new(BsonSerializer.SerializerRegistry.GetSerializer<Person>(), BsonSerializer.SerializerRegistry, linqProvider, isAggreg
Assert.Equal(expectedProjection, subject.Options.Projection.Render(new(BsonSerializer.SerializerRegistry.GetSerializer<Person>(), BsonSerializer.SerializerRegistry, linqProvider, renderForFind: true)).Document);

2024-07-19 18:09 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4742Tests.cs
> +            [Values(true, false)] bool isAggregateMode)
Combined the two tests into single one:
```
ExpressionProjectionDefinition_with_identity_projection_RenderForFind_should_work
ExpressionProjectionDefinition_with_identity_projection_Render_should_work
```

2024-07-19 18:09 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4742Tests.cs
> +            [Values(true, false)] bool isAggregateMode)
Combined the two tests into single one:
```
FindExpressionProjectionDefinition_with_identity_projection_Render_should_work
FindExpressionProjectionDefinition_with_identity_projection_RenderForFind_should_work
```

2024-07-19 19:13 UTC, rstam requested changes
One minor suggestion and one fix requested.

2024-07-19 19:13 UTC, rstam commented on src/MongoDB.Driver/FindFluent.cs
> +                var renderedProjection = Render(_options.Projection.Render, true);
Minor suggestion to make clear what `true` means:

    var renderedProjection = Render(_options.Projection.Render, renderForFind: true);

2024-07-19 19:13 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +            bool renderForFind = true)
Default should be `false`.

2024-07-19 19:25 UTC, rstam commented on src/MongoDB.Driver/FindFluent.cs
> +            return renderer(args);
My thinking was that no matter what we're rendering we are in fact rendering for find. 

I think any renderers that don't do anything special for find will return the exact same thing whether `RenderForFind` is `true` or `false`.

2024-07-19 19:26 UTC, rstam commented on src/MongoDB.Driver/FindFluent.cs
> +            return renderer(args);
Not saying you need to change it... just explaining my thinking.

Either way is fine.

2024-07-19 21:09 UTC, rstam approved these changes
LGTM

2024-07-24 15:43 UTC, merged