CSHARP-3315: Implement Equals for serializers.
mongodb/mongo-csharp-driver pull request #1281
Opened 2024-03-05 16:26 UTC by rstam

2024-05-09 15:13 UTC, rstam commented
Not ready for review yet. The new commits are just to back up work in progress in case something happens to my laptop.

2024-05-29 22:19 UTC, BorisDog reviewed
Partial review. About ~50% of the tests remain to be reviewed.

2024-05-29 22:19 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/BsonClassMapTests.cs
> +            result.Should().Be(notEqualFieldName == null ? true : false);
`notEqualFieldName` can't be null?

2024-05-29 22:19 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/BsonClassMapTests.cs
> +            var clone = (BsonClassMap)FormatterServices.GetUninitializedObject(classMap.GetType());
Do we have to use the Reflector here?

2024-05-29 22:19 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/StandardDiscriminatorConventionTests.cs
> +            var x = (StandardDiscriminatorConvention)new ConcreteStandardDiscriminatorConvention("_t");
minor: is this cast needed?

2024-05-29 22:39 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonMemberMap.cs
> +                object.Equals(_shouldSerializeMethod, other._shouldSerializeMethod);
I think so. Looks like I missed it.

2024-05-29 22:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/BsonClassMapTests.cs
> +            result.Should().Be(notEqualFieldName == null ? true : false);
I will remove the null check. It's left over from some intermediate experiments.

2024-05-29 22:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/BsonClassMapTests.cs
> +            var clone = (BsonClassMap)FormatterServices.GetUninitializedObject(classMap.GetType());
I think we do because there is no easy way to change just ONE field at a time to test `Equals`, but we can do it easily using reflection.

2024-05-29 22:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/BsonClassMapTests.cs
> +            var clone = (BsonClassMap)FormatterServices.GetUninitializedObject(classMap.GetType());
I have avoided using reflection wherever possible.

2024-05-29 22:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/StandardDiscriminatorConventionTests.cs
> +            var x = (StandardDiscriminatorConvention)new ConcreteStandardDiscriminatorConvention("_t");
Depends how you define "needed".

I wanted the *compile* time type of `x` to be the `abstract` base class, not the `concrete` type.

2024-05-29 22:39 UTC, rstam commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <Folder Include="Shared\" />
Not sure how it got here. Don't think I edited this file manually.

2024-06-13 23:00 UTC, BorisDog requested changes

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumerableInterfaceImplementerSerializerBaseTests.cs
> +﻿/* Copyright 2015-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumerableSerializerBaseTests.cs
> +﻿/* Copyright 2015-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/IEnumerableDeserializingAsCollectionSerializerTests.cs
> +﻿/* Copyright 2019-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ImpliedImplementationInterfaceSerializerTests.cs
> +﻿/* Copyright 2019-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectIdSerializerTests.cs
> +﻿/* Copyright 2019-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ProjectingDeserializerTests.cs
> +﻿/* Copyright 2015-present MongoDB Inc.
2010

2024-06-13 23:00 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/QueueSerializerTests.cs
> +﻿/* Copyright 2015-present MongoDB Inc.
2010

2024-06-20 00:03 UTC, rstam reviewed
Code review changes and implemented Equals for MemorySerializers.

2024-06-20 15:55 UTC, BorisDog approved these changes
LGTM!

2024-06-26 21:24 UTC, closed without merging