CSHARP-2353: BsonDocument.DeepClone() fails on documents with duplicate element names
mongodb/mongo-csharp-driver pull request #1283
Opened 2024-03-05 23:00 UTC by BorisDog

Also addresses [CSHARP-2354](https://jira.mongodb.org/browse/CSHARP-2354)

2024-03-06 01:43 UTC, rstam requested changes
Visual Studio warned that the line endings in BsonDocument.cs are inconsistent.

Other than that everything looks OK.

2024-03-06 07:48 UTC, damieng commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
> +                throw new ArgumentNullException("document");
`nameof(document)` instead of `"document"` ensures any refactoring stays in tact.

2024-03-06 20:24 UTC, BorisDog commented
> Visual Studio warned that the line endings in BsonDocument.cs are inconsistent.
> 
> Other than that everything looks OK.

Thanks, line endings should be consistent now.

2024-03-06 20:24 UTC, BorisDog commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
> +                throw new ArgumentNullException("document");
Thanks! Done.

2024-03-12 15:35 UTC, rstam approved these changes
LGTM

2024-03-13 16:32 UTC, merged