CSHARP-3745: Add support for srvServiceName URI option
mongodb/mongo-csharp-driver pull request #1284
Opened 2024-03-06 22:35 UTC by adelinowona

- Added a new URI options `srvServiceName` which allows the user to change the srv address prefix from the default of `mongodb`

2024-03-08 00:40 UTC, JamesKovacs approved these changes
LGTM

2024-03-08 17:33 UTC, BorisDog requested changes

2024-03-12 19:25 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            if (!_isInternalRepresentation && _srvServiceName != null && _scheme != ConnectionStringScheme.MongoDBPlusSrv)
So `_isInternalRepresentation` helps to differentiate between a connection string provided by the user and one that has been transformed into a `mongodb://` after the SRV and TXT records are resolved from DNS. So we need to check the connection string before the transformation has happened.

2024-03-13 19:38 UTC, adelinowona commented on src/MongoDB.Driver/MongoDefaults.cs
> +        public static string SrvServiceName
Done!

2024-03-13 19:38 UTC, adelinowona commented on src/MongoDB.Driver/MongoUrlBuilder.cs
> +            _srvServiceName = connectionString.SrvServiceName;
Done

2024-03-13 19:38 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ClusterSettingsTests.cs
> +        }
Done

2024-03-13 19:38 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +        public string SrvServiceName => _srvServiceName;
Done

2024-03-13 19:38 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            AssertException(settings =>
Done

2024-03-13 19:56 UTC, BorisDog approved these changes
LGTM

2024-03-14 15:23 UTC, merged