CSHARP-4985: Verify that operands to numeric operators in LINQ expressions are represented as numbers on the server.
mongodb/mongo-csharp-driver pull request #1294
Opened 2024-03-15 21:51 UTC by rstam

Let's not try and push this to master until after I get back. Feel free to take a look and comment. Mainly I wanted to get this work backed up.

I probably need a few more tests (though there are some tests already).

2024-04-23 15:14 UTC, JamesKovacs requested changes
A variety of LINQ3 tests are timing out with these changes. Please investigate the root cause of the timeouts before we review the code closely. Thanks.

2024-06-11 15:53 UTC, rstam commented
> A variety of LINQ3 tests are timing out with these changes. Please investigate the root cause of the timeouts before we review the code closely.

Done. Ready for review.

2024-06-18 15:22 UTC, rstam commented
There were a bunch of failed variants with cryptic log files that made no sense to me. I'm hoping they were transient Evergreen failures so I've rebase on master and force pushed the branch to trigger a new patch build.

2024-06-27 20:35 UTC, JamesKovacs requested changes
Minor improvement suggested below.

2024-06-27 20:35 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
> +        public static bool IsRepresentedAsIntegerOrNullableInteger(AggregationExpression translation)
All other `IsRepresentedAsXyz` methods take an `IBsonSerializer` as the only argument. Consider the same here.

2024-06-27 23:51 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/SerializationHelper.cs
> +        public static bool IsRepresentedAsIntegerOrNullableInteger(AggregationExpression translation)
There already is an overload of `IRepresentedAsIntegerOrNullableInteger` that takes an `IBsonSerializer`.

This is a convenience method when checking that a translation is represented as an integer or nullable integer.

It is analogous to another similar convenience method like `EnsureRepresentationIsNumeric`.

Let me know if this changes your request.

2024-07-08 17:28 UTC, JamesKovacs approved these changes
LGTM

2024-07-08 18:04 UTC, merged