CSHARP-4718: Enable Container and kubernetes awareness
mongodb/mongo-csharp-driver pull request #1295
Opened 2024-03-18 18:58 UTC by adelinowona

Enables container and kubernetes awareness in the driver as specified in the [MongoDB Handshake Spec](https://github.com/abr-egn/specifications/blob/c4831b426c7eab8749723d7f3cd6bb5c237bcbbe/source/mongodb-handshake/handshake.rst#container) .

#### What is the motivation for this change?
 - Allows Product to track user usage of docker and kubernetes.

2024-03-18 19:15 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +                var isExecutionContainerDocker = File.Exists("/.dockerenv");
I hesitated a little about checking for existence of a file to detect if we are in a docker container. Doing this makes us a dependent on the file system which might have potential issues related to file permissions or availability. I did some digging and found there is a environment variable called `DOTNET_RUNNING_IN_CONTAINER ` which is set automatically by official Microsoft .Net images [More info](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_running_in_container-and-dotnet_running_in_containers) . Problem is using this environment variable relies on the .net runtime to set it which is guaranteed if users use the official .Net images for their docker containers. However, it doesn't cover cases where users don't use the official .net images or choose to manually install a .net runtime in their containers. So I think checking for the file existence is our best bet unless we want to use both strategies and let them compensate for each other?

2024-03-18 19:19 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +        public void CreateEnvDocument_should_return_expected_result()
Using file existence as check for docker container presence means we can't really unit test it because we can't easily mock `FIle.Exist` as it is a static class. There is a way to bypass that but it will mean complicating the code for checking docker container presence just for the sake of testing. However, I manually tested by running a mongodb .net application in a docker container with the changes to test and the docker detection logic works.

2024-03-18 20:36 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +                var isOrchestratorKubernetes = Environment.GetEnvironmentVariable("KUBERNETES_SERVICE_HOST") != null;
It might makes sense to use `EnvironmentVariableProvider` here. It might be substitutable and it will help us when we will approach task to run tests in parallel.

2024-03-18 20:36 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +                var isOrchestratorKubernetes = Environment.GetEnvironmentVariable("KUBERNETES_SERVICE_HOST") != null;
We probably ought to implement something similar for file system. With the same motivation: having such substitutable components could help us to isolate each test without necessarily to have file existence on the host machine or setting environment variables, as each such host adjustment could affect other tests.

2024-03-18 20:36 UTC, sanych-sun commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +        public void CreateEnvDocument_should_return_expected_result()
See mine comment above.

2024-03-20 16:31 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +                var isExecutionContainerDocker = File.Exists("/.dockerenv");
Is Windows file system OK with such check? Should we wrap this with try-catch (some permissions restriction could lead to exception I suppose)?

BTW, this check looks like a Linux container detection. What about Windows containers? Should we try to detect them as well?

2024-03-21 17:14 UTC, JamesKovacs requested changes
Looking good. I'm OK with the current impl or switching to our own mocks for `IFileSystem` and `IEnvironment` (or whatever we want to call it. We do need the two additional test cases noted.

As for Windows container detection, if we find a way to reliably detect Docker on Windows, then we need to create a new DRIVERS ticket and update the spec so all drivers perform the detection in the same way.

2024-03-21 17:14 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +
We should also verify:
- `client.env.container.runtime` is set to `docker` when `/.dockerenv` is present.
- `client.env.container` is not present if neither Docker nor Kubernetes is deteced.

2024-03-25 16:15 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +
Done. Also I think I found a reliable way to detect Docker for Windows. I will reach out the owners of the DRIVERS ticket for this work to discuss further if spec needs to be updated or if we are ok with drivers not detecting Windows containers given their low usage.

2024-03-26 16:26 UTC, JamesKovacs approved these changes
LGTM

2024-03-28 20:50 UTC, sanych-sun requested changes
Looks good, minor changes requested.

2024-03-28 20:50 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +            __environmentVariableProvider = new Lazy<IEnvironmentVariableProvider>(() => new EnvironmentVariableProvider());
Why it's Lazy? It could point to `EnvironmentVariableProvider.Instance` by default.

2024-03-28 20:50 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +            __fileSystemProvider = new Lazy<IFileSystemProvider>(() => new FileSystemProvider());
Same here: I suppose we do not need Lazy, just use Instance by default.

2024-03-28 21:13 UTC, sanych-sun approved these changes
LGTM

2024-03-28 22:17 UTC, BorisDog approved these changes
LGTM, some minor comments for your consideration.
File and environment vars mocking approach is a great addition.

2024-03-28 22:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/FileWrapper.cs
> +    internal class FileWrapper : IFile
minor: sealed?

2024-03-28 22:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/FileSystemProvider.cs
> +        public static IFileSystemProvider Instance => __instance;
minor: maybe read-only property is sufficient ?
`public static IFileSystemProvider Instance { get; } = new FileSystemProvider();`

2024-03-28 22:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +        private static IEnvironmentVariableProvider __environmentVariableProvider;
Do we want to use `__environmentVariableProvider` for all other variables in this file?
Follow up ticket for that? This is also pre-requisite for future tests parallelization.

2024-03-28 22:17 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +            using (new DisposableEnvironmentVariable("VERCEL"))
Ideally we'd just use `environmentVariableProviderMock` for "VERCEL".

2024-03-28 22:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Connections/ClientDocumentHelper.cs
> +                    return new BsonDocument
minor: styling shortcut for your consideration
```
return new() 
{
 ....
}
```

2024-04-02 15:20 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/ClientDocumentHelperTests.cs
> +            using (new DisposableEnvironmentVariable("VERCEL"))
Yeah this is connected to replacing uses of Environment with EnvironmentVariableProvider in ClientDocumentHelper.cs

2024-04-02 15:25 UTC, merged