CSHARP-4979: Gossip cluster time from internal MongoClient to session entities
mongodb/mongo-csharp-driver pull request #1300
Opened 2024-03-26 23:12 UTC by sanych-sun

2024-03-28 22:14 UTC, JamesKovacs requested changes
Minor refactoring suggestion.

2024-03-28 22:14 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +            var serverTime = AddInitialData(DriverTestConfiguration.Client, initialData);
Rather than returning the `serverTime`, wouldn't it make more sense to update it in `AddInitialiData` by passing in the `_entityMap`?

2024-03-28 23:21 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +            var serverTime = AddInitialData(DriverTestConfiguration.Client, initialData);
Done

2024-04-02 19:35 UTC, JamesKovacs approved these changes
LGTM

2024-04-02 20:59 UTC, merged