CSHARP-3757: Redirect read/write retries to other mongos if possible
mongodb/mongo-csharp-driver pull request #1304
Opened 2024-04-10 23:13 UTC by adelinowona

### Description
On a sharded cluster, retrying reads and writes will attempt to prioritize other mongos for selection if available.

### What is changing?
- Server selection now takes a collection of servers to deprioritize and will attempt to exclude those servers when the topology is sharded and multiple mongoses are present.
- Adds unit tests for server selection and prose tests for retryable reads and writes.
- Adds functionality to provide a collection of servers to deprioritize in relevant places.

2024-04-10 23:22 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +            for (int i = 0; i < 15; i++)
Running multiple times to account for server selection randomness and guarantee we get the expected result for each run.

2024-04-16 00:59 UTC, BorisDog requested changes
Looks good, few minor comments.

2024-04-16 00:59 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/IBinding.cs
> +        IChannelSourceHandle GetReadChannelSource(IReadOnlyCollection<ServerDescription> deprioritizedServers, CancellationToken cancellationToken);
This interface is pseudo public (going to be hidden in 3.0), and we are introducing a breaking change anyway.
So should we consider just adding a parameter to the existing method?

2024-04-16 00:59 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                var excludingDeprioritizedServers = deprioritizedServers != null && _cluster.Description.Type == ClusterType.Sharded;
Consider micro optimization: `deprioritizedServers?.Any() == true`

2024-04-16 00:59 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadOperationExecutor.cs
> +                context.ReplaceChannelSource(context.Binding.GetReadChannelSource(new []{ context.ChannelSource.ServerDescription }, cancellationToken));
minor: missing space `new [] {}`

2024-04-16 00:59 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +            [Values(false, true)] bool IsSharded)
minor: lower case `isSharded`

2024-04-16 00:59 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +            var endPoint1 = new DnsEndPoint("localhost", 27017);
minor: add simple test to validate `deprioritizedServers == null ` case

2024-04-16 00:59 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +                    result = subject.SelectServerAsync(selector, deprioritizedServers, CancellationToken.None).GetAwaiter().GetResult();
Make the test return `Task`, and just await here.

2024-04-16 00:59 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +                var deprioritizedServersEndpoints = deprioritizedServers.Select(description => description.EndPoint);
minor: define `deprioritizedServersEndpoints `once. Do this one.

2024-04-24 18:15 UTC, BorisDog requested changes

2024-04-24 18:15 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ICluster.cs
> +        IServer SelectServer(IServerSelector selector, CancellationToken cancellationToken, IReadOnlyCollection<ServerDescription> deprioritizedServers = null);
Consider having augmenting `IServerSelector` to account for `deprioritizedServers`.

2024-05-22 19:48 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Bindings/IBinding.cs
> +        IChannelSourceHandle GetReadChannelSource(IReadOnlyCollection<ServerDescription> deprioritizedServers, CancellationToken cancellationToken);
We settled with using the overloads

2024-05-23 23:16 UTC, BorisDog requested changes
Some minor comments.

2024-05-24 17:09 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +            [Values(false, true)] bool IsSharded)
lowercase `isSharded`

2024-05-25 01:16 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        public async void SelectServer_should_return_deprioritized_servers_if_no_other_servers_exist_or_cluster_not_sharded(
Forgot to mention that async method should return `Task`, for better clarity.

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/RetryableWriteOperationExecutor.cs
> +                context.ReplaceChannelSource(context.Binding.GetWriteChannelSource(new [] { context.ChannelSource.ServerDescription }, cancellationToken));
Remove the extra space in `new []` --> `new[]`

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/PriorityServerSelector.cs
> +    public sealed class PriorityServerSelector : IServerSelector
We probably should have few very basic tests for this selector. like `EndPointServerSelectorTests`

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/WritableServerBinding.cs
> +
`new IServerSelector[] `-> `new[]`

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/WritableServerBinding.cs
> +            return await GetWriteChannelSourceAsync(null, mayUseSecondary, cancellationToken).ConfigureAwait(false);
No need to await, can just return the task.
Additional await might create addition wrapping task object.

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/WritableServerBinding.cs
> +                ? (IServerSelector)new CompositeServerSelector(new IServerSelector[] { new PriorityServerSelector(deprioritizedServers), writableServerSelector })
Same [comment](https://github.com/mongodb/mongo-csharp-driver/pull/1304/files#r1612347781) applies here

2024-05-25 01:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/PriorityServerSelector.cs
> +            _deprioritizedServers = Ensure.IsNotNull(deprioritizedServers, nameof(deprioritizedServers));
Should this be `IsNotNullOrEmpty` maybe?

2024-05-28 20:36 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/PriorityServerSelector.cs
> +            _deprioritizedServers = Ensure.IsNotNullOrEmpty(deprioritizedServers, nameof(deprioritizedServers)) as IReadOnlyCollection<ServerDescription>;
I wish we had appropriate overload, to skip the `as` .

2024-06-03 23:45 UTC, JamesKovacs requested changes
Looks like the logic around `PriorityServerSelector` isn't quite right as we have a lot of failing variants complaining about `deprioritizedServers` being empty. Please investigate and resolve. Thanks.

2024-06-03 23:45 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/PriorityServerSelector.cs
> +            _deprioritizedServers = Ensure.IsNotNullOrEmpty(deprioritizedServers, nameof(deprioritizedServers)) as IReadOnlyCollection<ServerDescription>;
Why can't our list of deprioritized servers be empty? Wouldn't this be the case on the first call and wouldn't it only contain servers on the subsequent retry?

Right now 26 out of 28 patch variants are failing because `deprioritizedServers` is empty.

2024-06-04 15:29 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/PriorityServerSelector.cs
> +            _deprioritizedServers = Ensure.IsNotNullOrEmpty(deprioritizedServers, nameof(deprioritizedServers)) as IReadOnlyCollection<ServerDescription>;
`PriorityServerSelector` is created conditionally (`deprioritizedServers != null`), so extending this condition to involve `PriorityServerSelector` only when deprioritizedServers is not empty seems natural.

2024-06-12 17:16 UTC, JamesKovacs approved these changes
LGTM

2024-06-12 17:21 UTC, merged