[WIP] CSHARP-4610: OIDC: Automatic token acquisition for GCP Identity Provider
mongodb/mongo-csharp-driver pull request #1315
Opened 2024-04-29 18:50 UTC by sanych-sun

Changes is based on auth spec for OIDC + not merged yet PR regarding TOKEN_RESOURCE encoding:
https://github.com/mongodb/specifications/pull/1569

Legacy tests should be updated once spec PR approved and merged.

2024-04-29 18:57 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            if (!string.Equals(name, "authmechanismproperties", StringComparison.OrdinalIgnoreCase))
This change was introduced because of spec change that is not merged yet. The value of TOKEN_RESOURCE for GCP could contain special symbols, so we have to split the properties by separators before decoding the string.

2024-04-29 18:58 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                var separatorPosition = property.IndexOf(':');
Minor optimization: we know for sure it should be no more then 2 parts, so can avoid array allocation.

2024-04-29 19:00 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                if (separatorPosition == -1)
There were explicit changes in spec that ALLOW users to have ":" inside the value. For example:
`TOKEN_RESOURCE:http://localhost` should be decoded as `TOKEN_RESOURCE`=`http://localhost`
So we basically split on first ':' now.

2024-04-30 17:24 UTC, blink1073 commented
@sanych-sun you have a merge conflict.  :smile

2024-04-30 17:27 UTC, blink1073 commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            if (!string.Equals(name, "authmechanismproperties", StringComparison.OrdinalIgnoreCase))
The spec has been merged

2024-05-01 18:07 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +            request.Accept = "application/json";
Yep. There is a code to read the entire response body as access_token. I've refactored the code to remove this unnecessary setting of Accept header for GCP provider.

2024-05-01 19:10 UTC, blink1073 approved these changes
LGTM!

2024-05-01 22:29 UTC, BorisDog requested changes

2024-05-01 22:29 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +            using (cancellationToken.Register(() => request.Abort(), useSynchronizationContext: false))
Consider `HttpClient` instead .

2024-05-01 22:51 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +            using (cancellationToken.Register(() => request.Abort(), useSynchronizationContext: false))
As discussed via Slack: HttpClient does not have sync methods prior net5.0.

2024-05-02 18:29 UTC, adelinowona requested changes

2024-05-02 18:29 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +                var response = request.GetResponse();
We need to dispose of this response object.

2024-05-02 18:45 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +                var response = request.GetResponse();
Good catch! Thank you!

2024-05-02 18:47 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                if (separatorPosition == -1)
I would prefer to keep this micro-optimization to avoid an extra array.

2024-05-02 19:01 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/AzureOidcCallback.cs
> +        protected override (Uri Uri, IReadOnlyDictionary<string, string> headers) GetMetadataRequestInfo(OidcCallbackParameters parameters)
Done

2024-05-02 19:04 UTC, sanych-sun commented on src/MongoDB.Driver.Core/Core/Authentication/Oidc/HttpRequestOidcCallback.cs
> +        protected abstract OidcAccessToken ParseMetadataResponseContent(Stream responseStream);
Done

2024-05-02 19:12 UTC, adelinowona approved these changes
LGTM.

2024-05-02 22:12 UTC, BorisDog approved these changes
LGTM

2024-05-06 16:50 UTC, JamesKovacs approved these changes
LGTM

2024-05-07 20:09 UTC, merged