CSHARP-5071: Support string concatenation of mixed types.
mongodb/mongo-csharp-driver pull request #1317
Opened 2024-05-03 20:23 UTC by rstam

2024-05-03 20:24 UTC, rstam commented
Added tests for all combinations of string concatenation using `+` or `string.Concat` and implemented any missing support.

2024-05-06 14:38 UTC, damieng commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5071Tests.cs
> +        [InlineData("stringproperty+stringproperty+stringproperty", "{ $project : { _v : { $concat : ['$A', '$B', '$C'] }, _id : 0 } }", "ABC", LinqProvider.V3)]
Given how much you need in an inline dat a+ the need for the big switch to convert I wonder if these would be better of as individual tests?

2024-05-06 15:42 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5071Tests.cs
> +        [InlineData("stringproperty+stringproperty+stringproperty", "{ $project : { _v : { $concat : ['$A', '$B', '$C'] }, _id : 0 } }", "ABC", LinqProvider.V3)]
I started that way: writing a different test for each scenario, but quickly realized that the tests were all the same except for a few lines, so I prefer refactoring it this way.

The other reason I went this way is that I could scan the scenario strings in the InlineData and quickly confirm that I was in fact testing all the combinations I intended to.

2024-05-08 15:20 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5071Tests.cs
> +        [InlineData("stringproperty+stringproperty+stringproperty", "{ $project : { _v : { $concat : ['$A', '$B', '$C'] }, _id : 0 } }", "ABC", LinqProvider.V3)]
I'm aware of MemberData and we've certainly used it before, but it's not usually my go to choice because it feels awkward to me.

And worse, Theory(s) that have non-primitive parameters aren't well supported by TestExplorer. There are ways around this but they require more code where you create an xUnit TestCase and calculate the test name yourself (as a string).

I can change this if you insist...

2024-05-08 16:26 UTC, damieng approved these changes

2024-05-08 16:28 UTC, damieng requested changes
Just need to address those test failures.

2024-05-30 16:36 UTC, damieng approved these changes

2024-06-11 23:47 UTC, merged