Push master build to MyGet + validate Api Docs generation script
mongodb/mongo-csharp-driver pull request #1319
Opened 2024-05-03 23:27 UTC by sanych-sun

Push master build to MyGet
Validate Api Docs generation script (PR build probably has to be configured to include this variant)

2024-05-06 19:03 UTC, BorisDog requested changes

2024-05-06 19:03 UTC, BorisDog commented on evergreen/evergreen.yml
> +            PACKAGES_SOURCE_KEY: ${myget_api_key}
Polling would be additional func?

2024-05-06 19:03 UTC, BorisDog commented on evergreen/evergreen.yml
> +            echo "Cannot run release script for non-clean version: '$PACKAGE_VERSION'"
```suggestion
            echo "Cannot run release script for dev version: '$PACKAGE_VERSION'"
```

2024-05-06 19:18 UTC, BorisDog commented on evergreen/evergreen.yml
> +          if [ "${BUILD_TARGET}" = "release" ] && [[ ! "$PACKAGE_VERSION" =~ $clear_version_rx ]]; then
Consider moving this check to `push-packages.sh `or somewhere in that area.

2024-05-07 05:16 UTC, sanych-sun commented on evergreen/evergreen.yml
> +            PACKAGES_SOURCE_KEY: ${myget_api_key}
Done, inside of `push-packages.sh`

2024-05-07 05:19 UTC, sanych-sun commented on evergreen/evergreen.yml
> +
Done

2024-05-07 05:20 UTC, sanych-sun commented on evergreen/evergreen.yml
> +          if [ "${BUILD_TARGET}" = "release" ] && [[ ! "$PACKAGE_VERSION" =~ $clear_version_rx ]]; then
Done

2024-05-07 18:54 UTC, BorisDog approved these changes
LGTM

2024-05-07 20:39 UTC, merged