CSHARP-5065: Dispose RawBsonDocument in ExplicitEncryptionLibMongoCryptController.cs
mongodb/mongo-csharp-driver pull request #1321
Opened 2024-05-07 21:32 UTC by adelinowona

- wrap uses of `RawBsonDocument` appropriately in using statements.

- Switch to using `BsonSerializer.Deserialize` in the `UnwrapValue` function instead of using `RawBsonDocument`. This helps us since we couldn't dispose of `RawBsonDocument` in this case as the returned value would be disposed as well. Also avoids us having to do cloning as a remedy if we were to still use `RawBsonDocument`.

2024-05-07 21:59 UTC, sanych-sun approved these changes
LGTM

2024-05-08 00:54 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/ExplicitEncryptionLibMongoCryptController.cs
> +            var bsonDocument = BsonSerializer.Deserialize<BsonDocument>(encryptedWrappedBytes);
Looks safe to me. I don't recall what was the motivation to use `RawBsonDocument`  as in most cases the `v` value will being read completely but consumer.
Maybe @rstam has some ideas.

2024-05-24 22:53 UTC, rstam requested changes

2024-05-24 22:53 UTC, rstam commented on src/MongoDB.Driver/Encryption/ExplicitEncryptionLibMongoCryptController.cs
> +            var bsonDocument = BsonSerializer.Deserialize<BsonDocument>(encryptedWrappedBytes);
I don't know why a `RawBsonDocument` is being used here. If the goal is to deserialize the key bytes we should just do that directly.

Not sure that is the goal though.

2024-05-28 20:30 UTC, BorisDog approved these changes
LGTM

2024-05-28 20:50 UTC, rstam approved these changes
LGTM

2024-05-29 19:37 UTC, merged