CSHARP-5087 Bump MacOS version used for tests
mongodb/mongo-csharp-driver pull request #1324
Opened 2024-05-11 05:25 UTC by sanych-sun

2024-05-11 05:47 UTC, sanych-sun commented on evergreen/evergreen.yml
> -          python3_binary: "C:/python/Python38/python.exe"
I've checked our scripts and drivers-evergreen-tools and did not find any usage of the variable.

2024-05-13 15:36 UTC, BorisDog requested changes
Small comment about jq

2024-05-13 15:36 UTC, BorisDog commented on build.config
> +DOTNET_VERSION=8.0.204
Finally!

2024-05-13 15:36 UTC, BorisDog commented on evergreen/evergreen.yml
> -          python3_binary: "/opt/python/3.8/bin/python3"
Make sure that `jq` is still available after this change

2024-05-13 15:59 UTC, sanych-sun commented on evergreen/evergreen.yml
> -          python3_binary: "/opt/python/3.8/bin/python3"
Yep, it is. I've include the `package_push_myget` into the PR patch and it's succeeded.

2024-05-13 16:58 UTC, BorisDog approved these changes
LGTM

2024-05-14 22:45 UTC, JamesKovacs approved these changes
LGTM

2024-05-14 22:45 UTC, JamesKovacs commented on evergreen/evergreen.yml
> -          python3_binary: "C:/python/Python38/python.exe"
If you `git blame`, you'll find my name on the `python3_binary` lines. I had to add the `python3_binary` variable to work around `python3` detection issues on different variants. Looks like `driver-evergreen-tools` has fixed the issue and this is no longer required.

2024-05-16 16:16 UTC, merged