[WIP] Refactor tests to use fixture for test data population
mongodb/mongo-csharp-driver pull request #1332
Opened 2024-05-27 23:37 UTC by sanych-sun

Most of the integration tests we have currently re-inserting the same data for each run. For the tests that is reading data (like a most LINQ tests) it's inefficient. Proposed changes let us utilize xUnit's Fixture to share the test data for the test collection. It means that Fixture will hold the test data, which will be inserted only one before tests will be run for a test class. Also fixture will be disposed after all tests were run, so we can cleanup the test collection.

I've choose 20 last tests in Jira folder because all of them are integration and refactored to use the approach. On mine local machine I saw like a 4 times improvement for this tests.
![Unit-tests-before](https://github.com/mongodb/mongo-csharp-driver/assets/31327136/7ddd2050-444a-49d6-8430-2515ef9e1dbb)
![Unit-tests-after](https://github.com/mongodb/mongo-csharp-driver/assets/31327136/d3586db3-f921-43ec-a256-29c24e667529)

2024-05-27 23:39 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    [Trait("Category", "Integration")]
I would like to have this category assigned to all tests that require database connection. In future we might use it to optimize test variants. So we can filter down functional tests from integration tests.

2024-05-27 23:41 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        protected void AssertStages(IEnumerable<BsonDocument> stages, params string[] expectedStages)
All `Assert-` and `Translate-` methods were simply copied from existing `Linq3IntegrationTest` base class (which probably has to be removed)

2024-05-27 23:43 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +    public class TemporaryDatabaseFixture: IDisposable
There is no direct usage for this fixture for now, but the idea was to have it for test classes that require more comprehensive test data (more then 1 collection).

2024-05-27 23:47 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +    public class CSharp702Tests : IntegrationTest<CSharp702Tests.TestDataFixture>
The main difference with comparing to the current test class structure:
1) Test class should be inherited from `IntegrationTest` base class
2) For typical test class that uses only 1 set of data we should create TestDataFixture as nested class and provide it as a type parameter for base IntegrationTest
3) Test class should have ctor to pass the Fixture created by xUnit infrastructure
4) Test collection is available through the Fixture property
5) Test data should be moved from GetCollection method to TestDataFixture

2024-05-27 23:50 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        {
BTW, we already have 2 set of such methods: in `Linq3IntegrationTest` class and also in `Linq3TestHelpers` static class. We probably ought to standardize the approach and have either static helper class or use base `IntegrationTest` class.

2024-05-28 00:02 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        protected virtual string CollectionName => _collectionName.Value;
Default collection name would be taken from the parent class name, as I suggest to put all test fixtures as a nested class of the test class.

2024-05-29 23:34 UTC, BorisDog reviewed
Looks like a great improvement to our tests. Waiting to see how faster our tests get when the rest of the tests are migrated.

2024-05-29 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
This one is not needed?

2024-05-29 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +    public abstract class TemporaryCollectionFixture<TModel> : TemporaryDatabaseFixture
We might need to readjust the naming, as more tests are migrated to use this approach. Something like ReadOnlyCollectionFixture...

2024-05-29 23:37 UTC, rstam reviewed
Overall I think this approach is great! Nice!

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +        public class ProfileModel
Do you remember why you renamed the class?

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
This class is not used.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +    public abstract class TemporaryCollectionFixture<TModel> : TemporaryDatabaseFixture
We should use `TDocument` instead of `TModel`.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        private readonly Lazy<bool> _initCollection;
I would name this field `_collectionInitializer`. Fields names are usually nouns.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        public IMongoCollection<T> GetCollection<T>(LinqProvider provider = LinqProvider.V3)
I would get rid of this overload.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        protected abstract IEnumerable<TModel> GetInitialData();
Add another optional overload:

    protected virtual IEnumerable<BsonDocument> GetRawInitialData();

to be used in the rare cases where we need to initialize test data with raw BsonDocuments.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            _ = _initCollection.Value;
I would replace the previous two lines with:

    EnsureCollectionIsInitialized();

and add a helper method:

    private void EnsureCollectionIsInitialized()
    {
        _ = _collectionInitializer.Value;
    }

to encapsulate the trickiness of using a Lazy field to ensure the collection is initialized.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        private string GetDeclaringTypeName()
I would rename this method `GetCollectionName`.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        private bool InitCollection()
I would rename this method `InitializeCollection`.

Eschew abbreviations.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            var collection = GetCollection<TModel>(CollectionName);
`var collection` can be moved inside the `if` statement.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            }
Add:

    var rawInitialData = GetRawInitialData();
    if (rawInitialData != null)
    {
        var rawCollection = GetCollection<BsonDocument>(CollectionName);
        rawCollection.InsertMany(rawInitialData);
    }

to handle the rare cases where we want to initialize the collection with raw BsonDocuments.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        private readonly ConcurrentBag<string> _createdCollections = new();
Rename field `_createdCollectionNames` because we are only storing the names, not the collections.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        public IMongoClient MongoDbClient => DriverTestConfiguration.Client;
I would remove this property.

We want to encourage using `GetClient(linqProvider)` and not using this property by mistake.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +    public class CSharp702Tests : IntegrationTest<CSharp702Tests.TestDataFixture>
Maybe fix the class name while we're at it? Doesn't match the filename.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +        public class TestDataFixture : TemporaryCollectionFixture<BsonDocument>
public class CollectionFixture : TemporaryCollectionFixture<MyModel>

I would name this class `CollectionFixture` rather than `TestDataFixture`. To me the most important thing is that it is a "collection fixture". Initializing the test data is a secondary function.

Or `Model` if you don't get the same naming conflict with `Amazon,SecurityServices` that I was getting.

2024-05-29 23:37 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            protected override IEnumerable<BsonDocument> GetInitialData()
`GetRawInitialData`

2024-05-29 23:50 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        protected void AssertStages(IEnumerable<BsonDocument> stages, params string[] expectedStages)
I like the idea to derive `Linq3IntegrationTest` from `IntegrationTest`. Will check if we can do it now, or should do it as the very last step of the refactoring if there are any conflicts.

2024-05-29 23:53 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
It will be used for tests that uses `TemporaryDatabaseFixture` instead of `TemporaryCollectionFixture`. I'll show an example in next commit.

2024-05-29 23:55 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            var collection = Fixture.GetCollection<Model>(linqProvider);
Yes, in this particular test we are inserting the data using one model, but want to read the data as another.

2024-05-29 23:56 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4772Tests.cs
> +        public class ProfileModel
The name conflict with some namespace. I did not investigate this deep, just renamed the model to get rid of conflict.

2024-05-29 23:58 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
I'll show the usage for the case when test class do not want to initialize the collection, but want to have db for inserts or another data modification operations.

2024-05-30 00:01 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        public IMongoCollection<T> GetCollection<T>(LinqProvider provider = LinqProvider.V3)
I'll try to remove it by your GetRawInitialData suggestion. Have to investigate existing tests if it will cover all existing cases.

2024-05-30 01:43 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            }
Another option would be to make `InitializeCollection` virtual and in the rare case where a test class needs to initialize the collection with non-standard documents it can simply override `InitializeCollection` instead of `GetInitialDocuments`.

2024-05-31 17:33 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +    public class CSharp702Tests : IntegrationTest<CSharp702Tests.TestDataFixture>
Class was renamed.

2024-05-31 17:34 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +    public abstract class TemporaryCollectionFixture<TModel> : TemporaryDatabaseFixture
Done

2024-05-31 17:34 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        private readonly Lazy<bool> _initCollection;
Done

2024-05-31 17:34 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            _ = _initCollection.Value;
Done

2024-05-31 17:35 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        private bool InitCollection()
Done

2024-05-31 17:35 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            var collection = GetCollection<TModel>(CollectionName);
Done

2024-05-31 17:36 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        private readonly ConcurrentBag<string> _createdCollections = new();
Done

2024-05-31 17:38 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        public IMongoClient MongoDbClient => DriverTestConfiguration.Client;
Done

2024-05-31 17:39 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +        public class TestDataFixture : TemporaryCollectionFixture<BsonDocument>
Done

2024-05-31 19:39 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            var collection = Fixture.GetCollection<Model>(linqProvider);
I've decided to make InitializeCollection virtual, so derived fixtures are free to use any initialization logic.

2024-05-31 19:39 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4702Tests.cs
> +            protected override IEnumerable<BsonDocument> GetInitialData()
InitializeCollection is virtual now as per your another suggestion.

2024-05-31 19:40 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        public IMongoCollection<T> GetCollection<T>(LinqProvider provider = LinqProvider.V3)
Removed.

2024-05-31 19:40 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +        protected abstract IEnumerable<TModel> GetInitialData();
InitializeCollection is virtual now as per your another suggestion.

2024-05-31 19:42 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryCollectionFixture.cs
> +            }
I like idea of making `InitializeCollection` virtual more, because in such case derived fixture free to have any custom initialization logic, not just `BsonDocument` scenario.

2024-05-31 19:44 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
Please find example of usage in `CSharp4066Tests` test class.

2024-05-31 19:44 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
Please find example of usage in `CSharp4066Tests` test class.

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.TestHelpers/XunitExtensions/IntegrationTestAttribute.cs
> +
minor: remove empty line

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
Maybe a better naming to reflect that. And then why not having matching class for `TemporaryCollectionFixture` ?

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +            => DriverTestConfiguration.GetLinqClient(provider);
The question regarding the client still remains. Do we want to use this opportunity to start working with disposable clients?

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        }
Why not to drop the database instead?

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +                var frame = stack.GetFrame(1); // skip 1 frame to get the calling method info
Nice,
I wanted to suggest `[CallerMemberName]` , but we having type name is better.

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest<TFixture> : IClassFixture<TFixture>
Probably worth inheriting for `LoggableTestClass`, to have logging and timeouts for all.
Ideally all test would derive from   `LoggableTestClass`.

2024-05-31 23:34 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +            }
It's worth having some tests that consume same collection, overwrite same data. To see how we avoid collisions. 
So we are ready for parallelization.

2024-06-08 00:04 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        public IMongoClient MongoDbClient => DriverTestConfiguration.Client;
Done. Client(s) will be created per fixture and will be disposed together with fixture. See TemporaryDatabaseFixture class for implementation.

2024-06-08 00:06 UTC, sanych-sun commented on tests/MongoDB.TestHelpers/XunitExtensions/IntegrationTestAttribute.cs
> +
Done

2024-06-08 00:07 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +            => DriverTestConfiguration.GetLinqClient(provider);
Done. See `TemporaryDatabaseFixture` for implementation.

2024-06-08 00:08 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +        }
Currently it would be almost the same, but if we approach running in parallel task - then it will be safer to remove the collection as database might be in use by other tests/fixtures.

2024-06-08 00:11 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/TemporaryDatabaseFixture.cs
> +            }
For test Theories - yep. It will be more complicated, as we will need to add some extra suffixes to the names probably (based on test parameters? or test sequential number). Will try to find a way to work with this.

2024-06-08 00:27 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest<TFixture> : IClassFixture<TFixture>
`IntegrationTest` is not inhireted from `LoggableTestClass`. Let's discuss offline if we need some extra functionality around.

2024-06-08 00:29 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
I've removed the class for now to avoid confusions. We might consider to re-introduce it later.

2024-06-08 00:42 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        protected void AssertStages(IEnumerable<BsonDocument> stages, params string[] expectedStages)
I've decided to introduce new `LinqIntegrationTest` base class.For 2 reasons:

2024-06-08 00:45 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        {
I'll try to consolidate all usages into the just introduced LinqIntegrationTest base class and remove "old" methods.

2024-06-08 00:49 UTC, sanych-sun commented on CSharpDriver.sln.DotSettings
>  ﻿<wpf:ResourceDictionary xml:space="preserve" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:s="clr-namespace:System;assembly=mscorlib" xmlns:ss="urn:shemas-jetbrains-com:settings-stora
This file is really hard to review, but the needed to let Rider/ReSharper add Integration Tests from template. I can demo how it works on some stand up.

2024-06-08 00:54 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +    public abstract class IntegrationTest : IntegrationTest<TemporaryDatabaseFixture>
I've removed the class to avoid confusion.

2024-10-25 23:30 UTC, BorisDog requested changes

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/CollectionFixture.cs
> +        public override IMongoCollection<T> GetCollection<T>(Action<MongoClientSettings> configure = null, string collectionName = null)
Do we have cases where T != TDocument?

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +            return _fixture.GetDatabase(settings =>
minor: expression body ?

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +                var frame = stack.GetFrame(2); // skip 2 frame to get the calling method info (this method and IntegrationTest method)
nit: `frames`

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        }
Don't we want just to drop the DB instead?

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        private readonly string _databaseName = $"CsharpDriver-{__timeStamp}";
nit: `CSharp`

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        {
Dispose the client.

2024-10-25 23:30 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        where TFixture : DatabaseFixture
Do we want to consider reusing the client between tests as well (`ICollectionFixture`)?
So we don't dispose it after each tests class. For example single client for all `LinqIntegrationTest`?

2025-01-10 23:33 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        where TFixture : DatabaseFixture
Done. Now we have a single client per Fixture.

2025-01-10 23:33 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        {
Done.

2025-01-10 23:34 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        private readonly string _databaseName = $"CsharpDriver-{__timeStamp}";
Done

2025-01-10 23:36 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +        }
Discussed, it's better to remove collections just if we will ever decide to implement tests in parallel.

2025-01-10 23:37 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +            return _fixture.GetDatabase(settings =>
This method is gone, by exposing Fixture itself.

2025-01-10 23:39 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/CollectionFixture.cs
> +        public override IMongoCollection<T> GetCollection<T>(Action<MongoClientSettings> configure = null, string collectionName = null)
This method signature is inherited from DatabaseFixture. Currently we throw if  T != TDocument, but it might be changed as we proceed to convert more tests.

2025-01-10 23:43 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/IntegrationTest.cs
> +        public IMongoCollection<T> GetCollection<T>(Action<MongoClientSettings> configure = null, string collectionName = null)
I've decided to expose Fixture itself from the IntegrationTest class. The decision is motivated by the idea of introducing using fixtures for tests that need more then just single collection. Example  could be find in `CSharp5231ests`.

2025-01-10 23:44 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DatabaseFixture.cs
> +    public class DatabaseFixture: IDisposable
Fixed

2025-01-11 00:08 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        protected virtual void InitializeFixture()
Probably have to add some inline documentation here, but the idea was: `InitializeFixture` method is being executed only once per fixture lifetime (per test class in most cases) when `InitializeTestCase` is being executed for each test. So combining this two methods it's easy to implement custom initialization logic depending on nature of test collection.

2025-01-23 23:37 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/app.config
> +    <add key="diagnosticMessages" value="true" />
Revert this change.

2025-01-24 12:44 UTC, papafe commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5188Tests.cs
> +
I suppose these two lines can be removed

2025-01-24 13:29 UTC, papafe reviewed
Overall it makes sense for me

2025-01-24 13:29 UTC, papafe reviewed
Overall it makes sense for me

2025-01-24 18:58 UTC, rstam requested changes
I like this approach a LOT!!! Well done!

Sorry the number of requested changes looks like a lot. It's really just:

1. A bunch of renaming suggestions
2. Changing some methods to properties with Lazy values

The whole basic approach you are proposing seems 100% sound and I am not requesting any changes to the essence of your approach.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +    {
Add:

    private readonly Lazy<IMongoCollection<TDocument>> _collection;

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +        private bool _collectionInitialized;
Rename to `_dataInitialized`.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +            }
Add:

    _collection = new Lazy<IMongoCollection<TDocument>>(CreateCollection);

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +
Add:

    public IMongoCollection<TDocument> Collection => _collection.Value;

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +        public virtual bool ResetOnEachTestCase => false;
Rename to `InitializeDataBeforeEachTestCase`.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +        public override IMongoCollection<T> GetCollection<T>(string collectionName = null)
Replace `GetCollection` method witth `Collection` property. The property can return the same `IMongoCollection<TDocumnt>` instance every time.

Even if we do need to initialize the data before every test case, we don't have to create a new `MongoCollection` instance.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoCollectionFixture.cs
> +        protected override void InitializeTestCase()
Refactor to:

        protected override void InitializeTestCase()
        {
            if (InitializeDataBeforeEachTestCase || !_dataInitialized)
            {
                Collection.Database.DropCollection(_collectionName);
                Collection.Database.CreateCollection(_collectionName);

                var initialData = InitialData;
                if (initialData != null)
                {
                    Collection.InsertMany(initialData);
                }

                _dataInitialized = true;
            }
        }

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        private static readonly string __timeStamp = DateTime.Now.ToString("yyyyMMdd-HHmmss");
Use `DateTime.Now.ToString("MMddHHmm");` like we currently do.

The idea is to have the shortest database name possible but still be unique.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +            client.Dispose();
Thought for the future: 

Currently calling `client.Dispose` doesn't actually do much. It certainly doesn't shut down the connection pool.

However, if in the future `MongoClient` becomes truly disposable then calling `Dispose` will shut down the connection pool, which in turn will result in each test class starting up a NEW cluster, which can take a long time since it has to create a new connection pool, open a bunch of sockets and let SDAM discover a writable server. 

We want all the tests to use the *same* `MongoClient` instance for efficiency (unless of course a test requires a specially configured client, which is a special case).

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        internal void Initialize()
Use `!_fixtureInitialized` instead of `_client == null` to control only initializing the fixture once.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5163Tests.cs
> +        var collection = Fixture.GetCollection<MyModel>();
Same in many other places.

2025-01-24 18:58 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        public virtual IMongoCollection<T> GetCollection<T>(string collectionName = null)
I'm recommending `CreateCollection` instead of `GetCollection` because this actually modifies the collection (`database.GetCollection` doesn't actually do anything on the server, it just returns a `IMongoCollection` instances).

This method could also be called `CreateEmptyCollection`.

2025-01-24 19:19 UTC, rstam commented
My requested changes are prototyped here:

https://github.com/rstam/mongo-csharp-driver/tree/csharp5338-0124

2025-01-27 20:58 UTC, rstam requested changes
Minor request pending. Looks great!

2025-01-27 20:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4066Tests.cs
> +    public class CSharp4066Tests : IntegrationTest<CSharp4066Tests.TestDataFixture>
Consider renaming` TestDataFixture` to `CollectionFixture`.

That way we know immediately that we are using a collection fixture or a database fixture.

2025-01-27 20:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5231Tests.cs
> +    public class CSharp5231Tests : LinqIntegrationTest<CSharp5231Tests.TestDataFixture>
Consider renaming `TestDataFixture` to `DatabaseFixture`.

That way we know immediately that we are using a collection fixture or a database fixture.

2025-01-27 20:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4066Tests.cs
> +    public class CSharp4066Tests : IntegrationTest<CSharp4066Tests.TestDataFixture>
Same in other test files.

2025-01-28 21:13 UTC, BorisDog requested changes
Partial review.
Requested to evaluating the approach of having a collection fixture instead.

2025-01-29 14:17 UTC, papafe approved these changes
LGTM! I also like the new shared`MongoClientFixture`

2025-01-29 19:44 UTC, BorisDog requested changes
Looks great! Few minor comments.

2025-01-29 19:44 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/MongoClientFixture.cs
> +public class MongoClientFixture : IDisposable
nit: sealed?

2025-01-29 19:44 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/MongoClientFixture.cs
> +    internal XUnitOutputAccumulator LogsAccumulator { get; }
Not sure what was my motivation for making `XUnitOutputAccumulator` internal.

2025-01-29 19:44 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        internal IMongoClient MongoClient => _mongoClientFixture.Client;
Most internals can be public?

2025-01-29 20:50 UTC, BorisDog approved these changes
LGTM!

2025-01-31 15:36 UTC, adelinowona approved these changes
LGTM

2025-02-03 21:13 UTC, rstam requested changes

2025-02-03 21:13 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +                var stack = new System.Diagnostics.StackTrace();
This code is not reached.

Throw an exception instead.

2025-02-03 21:13 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        protected IMongoCollection<TDocument> CreateCollection<TDocument>(string collectionName = null)
`collectionName` parameter should be mandatory.

2025-02-03 21:14 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/MongoDatabaseFixture.cs
> +        protected IMongoCollection<TDocument> CreateCollection<TDocument>(string collectionName = null)
Done

2025-02-03 21:19 UTC, rstam approved these changes
LGTM

This is nice!

2025-02-05 20:11 UTC, merged