CSHARP-5048: Integrate with silk and get SBOM document for releases
mongodb/mongo-csharp-driver pull request #1340
Opened 2024-06-07 16:02 UTC by adelinowona

2024-06-07 23:35 UTC, BorisDog requested changes
Nice work, minor comment.

2024-06-07 23:35 UTC, BorisDog commented on evergreen/template_ssdlc_compliance_report.md
> +<a href="https://us-west-2.console.aws.amazon.com/s3/object/csharp-driver-release-assets?region=us-west-2&bucketType=general&prefix=${PRODUCT_NAME}/${PACKAGE_VERSION}/ssdlc_compliance_report.md">here
+1

2024-06-07 23:35 UTC, BorisDog commented on evergreen/download-augmented-sbom.sh
> +cat << EOF > silkbomb.env
Let's specify the input vars, like [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/evergreen/generate-ssdlc-report.sh#L4)
I know that we have not always been doing this, but we should :)

2024-06-10 18:26 UTC, BorisDog approved these changes
LGTM

2024-06-10 22:49 UTC, sanych-sun approved these changes
LGTM + minor suggestions.

2024-06-10 22:49 UTC, sanych-sun commented on evergreen/evergreen.yml
> +    - command: ec2.assume_role
It looks like we can move assume role into the task, because we do not need to do it twice (for SSDLC report upload and for SBOM upload). @BorisDog ?

2024-06-10 22:49 UTC, sanych-sun commented on evergreen/download-augmented-sbom.sh
> +  --env-file silkbomb.env \
We can simplify a little by passing environment variables not through the file, but as docker cli parameters. Like:
`-e SILK_CLIENT_ID "${SILK_CLIENT_ID}" \`
`-e SILK_CLIENT_SECRET "${SILK_CLIENT_SECRET}" \`

2024-06-12 17:46 UTC, sanych-sun approved these changes
LGTM

2024-06-12 18:16 UTC, merged