CSHARP-5140: Coverity analysis defect 102677: Copy-paste error.
mongodb/mongo-csharp-driver pull request #1357
Opened 2024-06-17 21:48 UTC by rstam

2024-06-18 18:19 UTC, adelinowona requested changes

2024-06-18 18:19 UTC, adelinowona commented on src/MongoDB.Bson/IO/JsonReader.cs
> +                var message = string.Format("JSON reader expected a number but found '{0}'.", incrementToken.Lexeme);
I would say add tests. Looking at `TestTimestampConstructor` in `JsonReaderTests.cs` which implicitly tests the `ParseTimestampConstructor` method, we don't test for potential invalid json input which is probably how this error wasn't caught before. 

Something similar to `TestTimestampExtendedJsonNewRepresentationWhenInvalid` should be enough.

2024-06-20 18:31 UTC, adelinowona requested changes

2024-06-20 18:31 UTC, adelinowona commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void TestTimestampConstructorWhenInvalid(string json)
`TestTimestampExtendedJsonNewRepresentationWhenInvalid` seems to expect to fail if the increment value is not an integer. Should we add that check as well for the TimeStampConstructor?

2024-06-26 23:31 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void TestTimestampConstructorWhenInvalid(string json)
Did you mean this test?

    [InlineData("{ \"$timestamp\" : { \"t\" : 1, \"i\" : 2.0 } }")]

2024-06-26 23:37 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void TestTimestampConstructorWhenInvalid(string json)
Looks like `ParseTimestampConstructor` and `ParseTimestampExtendedJsonNewRepresentation` behave differently in the presence of a non-integer value for `timestamp` or `increment`.

`ParseTimestampConstructor`  only requires a number, and converts it to an int32, but `ParseTimestampExtendedJsonNewRepresentation` throws an exception if it's not an integer.

So I can't add this new test unless we also change the implementation of `ParseTimestampConstructor`.

2024-06-26 23:38 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReader.cs
> +                var message = string.Format("JSON reader expected a number but found '{0}'.", incrementToken.Lexeme);
Done

2024-06-26 23:40 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void TestTimestampConstructorWhenInvalid(string json)
I added these two new test cases expecting them to pass but they don't, because they aren't invalid according to the implementation of `ParseTimestampConstructor`

    [InlineData("Timestamp(1.0, 2)")]
    [InlineData("Timestamp(1, 2.0)")]

2024-06-26 23:41 UTC, adelinowona approved these changes
LGTM

2024-06-27 15:15 UTC, merged