CSHARP-5168: Fixed using some LINQ function after a Union throws an Exception
mongodb/mongo-csharp-driver pull request #1374
Opened 2024-06-28 15:44 UTC by 616b2f

For details see Jira Ticket pls.

2024-07-09 23:18 UTC, rstam requested changes
Thank you for the PR. Please see the comments.

2024-07-09 23:18 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersNode.cs
> +
I couldn't figure out why this change was made.

I commented it out and all tests still pas..

2024-07-09 23:18 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +        }
Good call. This change is necessary.

However: all tests (including the new one you wrote below) pass without this.

This change is simply about getting the compile time type of the LINQ query to be `IMongoQueryable<T>` instead of `IQueryable<T>`. The runtime type was already `IMongoQueryable<T>`.

2024-07-09 23:18 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/UnionMethodToPipelineTranslatorTests.cs
> +                .Union(_secondCollection.AsQueryable()
I had to add:

    using MongoDB.Driver.Linq;

above to get the compile time type of `Union` to be `IMongoQueryable<T>` instead of `IQueryable<T>`.

However: this test and all other tests in this file pass with our without the new `using` statement. The `using` statement doesn't change the meaning of any queries, it just changes the compile time type of `Union`.

2024-07-09 23:18 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/UnionMethodToPipelineTranslatorTests.cs
> +                "{ $match : { Id : 2 } }"
I had to change this to:

    "{ $match : { _id : 2 } }"

to get the test to pass. I think `_id` is the correct field name.

2024-07-09 23:18 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersNode.cs
> +
I'm testing against `master` which has some other changes that might have made this change unnecessary.

By "using master" I mean that I rebased the PR on `master` on my machine.

2024-07-11 11:39 UTC, 616b2f commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersNode.cs
> +
I got the test now running locally, I can see that the test I provided is not showing how the issue can be reproduced. I changed it, now you should be able to reproduce it when you comment out this part here.

2024-07-11 11:42 UTC, 616b2f commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/UnionMethodToPipelineTranslatorTests.cs
> +                .Union(_secondCollection.AsQueryable()
Removed it, I could not up with the test that represents why I needed this change. When I find that happening again I create a separate issue for that.

2024-07-11 11:43 UTC, 616b2f commented
@rstam Please have another look, I fixed some shortcomings of my initial request.

2024-08-14 19:23 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersNode.cs
> +                    if (set.Any(x => x.GetHashCode() == serializer.GetHashCode()))
You are sort of on the right track here. But the real fix is to get some broken `Equals` methods to return true for two serializers that are "equal" so they only get added to the HastSet once.

Just because two serializers have the same hash code doesn't mean they are equal.

I have created a new PR that addresses the root issue here and has a very different minimal reproduction.

See CSHARP-5168.

2024-08-14 19:31 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializersNode.cs
> +                    if (set.Any(x => x.GetHashCode() == serializer.GetHashCode()))
Here's the new PR:

https://github.com/mongodb/mongo-csharp-driver/pull/1413

2024-08-14 19:31 UTC, closed without merging

2024-08-14 19:32 UTC, rstam commented
Thank you for submitting this PR! Even though we didn't use it as submitted it was very helpful in finding the underlying issue (which wasn't actually related to Union after all).