CSHARP-4957: Fix issue with new array expression.
mongodb/mongo-csharp-driver pull request #1390
Opened 2024-07-16 23:24 UTC by rstam

2024-07-16 23:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewArrayInitExpressionToAggregationExpressionTranslator.cs
> -            var serializer = context.KnownSerializersRegistry.GetSerializer(expression);
KnownSerializer was returning the wrong serializer here.

I think we need to reevaluate whether the known serializer strategy is working.

In this particular case we should just determine the required result serializer here without help from the known serializer registry.

2024-07-16 23:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewArrayInitExpressionToAggregationExpressionTranslator.cs
> +                // make sure all items are serialized using the same serializer
This goes slightly beyond fixing the reported bug, but it's in the same logic path.

2024-07-17 20:57 UTC, JamesKovacs requested changes

2024-07-17 20:57 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewArrayInitExpressionToAggregationExpressionTranslator.cs
> +                }
Items must use compatible serializers but not necessarily the same serializer. For example I would expect the following to work:

```
var queryable = collection.AsQueryable()
    .Select(x => new Animal[] { x.Cat, x.Dog });
```

2024-07-18 20:46 UTC, JamesKovacs approved these changes
LGTM

2024-07-18 20:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewArrayInitExpressionToAggregationExpressionTranslator.cs
> +                }
After investigating further and discussing in Slack, we are going to leave this as a known limitation that we don't support arrays of polymorphic types in projections.

2024-07-18 20:51 UTC, merged