CSHARP-1276: Provide Strong-Named Assemblies
mongodb/mongo-csharp-driver pull request #1393
Opened 2024-07-19 20:57 UTC by sanych-sun

2024-07-19 20:58 UTC, sanych-sun commented on benchmarks/MongoDB.Driver.Benchmarks/MongoDB.Driver.Benchmarks.csproj
> +    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
Have to replace `NDesk.Options` with `System.CommandLine`, because there is no strong-named version of `NDesk.Options`.

2024-07-19 20:58 UTC, sanych-sun commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkRunner.cs
> +        public static int Main(string[] args)
@adelinowona Could you please double-check if new code properly process all command line parameters?

2024-07-19 20:59 UTC, sanych-sun commented on nuget.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
SHOULD NOT MERGE THIS FILE! It's here just to test not-yet-published libmongocrypt version.

2024-07-19 21:01 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/TypeNameDiscriminator.cs
> +                        (assembly.FullName.StartsWith("MongoDB") && publicKeyToken == "94992a530f44e321"))
Have to add this condition for backward compatibility, because now we have strongly named assemblies and without this changes we would use fully qualified type name here, what would be a breaking change.

2024-07-19 21:01 UTC, sanych-sun commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="1.11.0" />
Do not forget to publish MongoDB.Libmongocrypt 1.11.0 before merging this PR.

2024-07-22 16:46 UTC, BorisDog requested changes

2024-07-22 16:46 UTC, BorisDog commented on src/MongoDB.Bson/Properties/AssemblyInfo.cs
> +using System.Security.Cryptography.X509Certificates;
Is this using needed?

2024-07-22 22:18 UTC, BorisDog approved these changes
LGTM

2024-07-22 22:45 UTC, adelinowona commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkRunner.cs
> +        public static int Main(string[] args)
all good

2024-07-22 22:45 UTC, adelinowona approved these changes
LGTM

2024-07-22 22:55 UTC, merged

2024-07-30 13:25 UTC, adaskos-signal commented
I think public signing an assembly is a breaking change and should have been part of a new major version.

A library built with any of the previous unsigned versions will not be able to be consumed by a project which upgrades to the new, signed version. The two are not assembly compatible, and this applies to .NET Core as well. 
It won't even built, if any Mongo related class is not encapsulated and needs to cross the library boundaries.

Mongo2Go library for example seems ok, but see this issue for example: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2265
Same goes for any internal projects too.

I'm not sure the implications of this change were all assessed before proceeding.

2024-07-31 10:16 UTC, mhbuck commented
The Mongo diagnostic source is also impacted by this change
https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources/issues/34

I would expect a number of projects that use the MongoDB drivers are going to be impacted.

2024-08-05 09:53 UTC, Droxx commented
To add to the above comments. This has also broken some of our dependencies. I agree that this should have been part of a major version. We now have to pin ourselves to 2.27.0 until all of our dependencies are also updated:

https://github.com/ChilliCream/graphql-platform/issues/7306

2024-09-18 02:06 UTC, aj-scram commented
just echoing that this broke things for my org to cause we use: https://github.com/ChangemakerStudios/serilog-sinks-mongodb