CSHARP-5190: Support Select new BsonDocument.
mongodb/mongo-csharp-driver pull request #1396
Opened 2024-07-24 00:19 UTC by rstam

2024-07-24 00:20 UTC, rstam commented
Decided not to even try to support {{new Dictionary<string, object>}} because we have too many issues with object serialization.

2024-07-24 00:22 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/PartialEvaluator.cs
> +            protected override Expression VisitListInit(ListInitExpression node)
This fixes the first bug, the one in {{PartialEvaluator}}.

The rest of the PR is implementing support for {{new BsonDocument}} in LINQ3.

2024-07-24 00:22 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ListInitExpressionToAggregationExpressionTranslator.cs
> +                        var valueTranslation = ExpressionToAggregationExpressionTranslator.Translate(context, valueExpresssion);
The values are the only parts that need to be translated. The names have to be constants.

2024-07-25 03:18 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4062Tests.cs
> +            AssertStages(stages, "{ $project : { _v : { $literal : { R :  true } }, _id : 0 } }");
These were interesting... a bug we didn't know we had!

2024-07-25 16:46 UTC, sanych-sun approved these changes
LGTM, but please check the failing tests

2024-07-25 17:56 UTC, rstam commented
> LGTM, but please check the failing tests

Will do. Was wondering whether there would be any because a lot of tests have #ifdefs on them and may not have run on my machine.

2024-07-25 17:57 UTC, janiavdv requested changes
Looks pretty good so far! Requested two notable changes related to supporting more `BsonDocument` constructors and `Add` methods.

2024-07-25 17:57 UTC, janiavdv commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/BsonDocumentMethod.cs
> +            __addWithNameAndValue = ReflectionInfo.Method((BsonDocument document, string name, BsonValue value) => document.Add(name, value));
**issue**: Similarly, we should support the different `Add` methods, particularly `BsonElement` and `IEnumerable`.

2024-07-25 17:57 UTC, janiavdv commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5190Tests.cs
> +using System.Linq;
**chore**: Remove unused import.

2024-07-25 17:57 UTC, janiavdv commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5190Tests.cs
> +                .Select(x => new BsonDocument("a", x.A) { });
**note**: An example of a failing query due to the unsupported `Add(BsonElement element)` method is:
```cs
var queryable = collection.AsQueryable()
                .Select(x => new BsonDocument() { new BsonElement("a", x.A ) });
```

2024-07-25 18:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/BsonDocumentConstructor.cs
> +        private static readonly ConstructorInfo __withNameAndValue;
Our pattern in a class like this has been to only add the ones we need so far.

2024-07-25 18:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/BsonDocumentMethod.cs
> +            __addWithNameAndValue = ReflectionInfo.Method((BsonDocument document, string name, BsonValue value) => document.Add(name, value));
Our pattern in a class like this has been to only add the ones we need so far.

2024-07-25 18:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/BsonDocumentMethod.cs
> +            __addWithNameAndValue = ReflectionInfo.Method((BsonDocument document, string name, BsonValue value) => document.Add(name, value));
Separate question is whether we need to support all the many different ways to create a BsonDocument.

It's probably not necessary. We are supporting the canonical constructor and the canonical `Add` method. That might be enough.

Thoughts? Alex?

2024-07-25 18:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewBsonDocumentExpressionToAggregationExpressionTranslator.cs
> +            }
Let's discuss whether we even need to support more `Add` methods.

2024-07-25 18:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewBsonDocumentExpressionToAggregationExpressionTranslator.cs
> +        public static AggregationExpression Translate(TranslationContext context, MemberInitExpression expression)
Fair question.

Because:

```new BsonDocument() { }```

compiles to a `MemberInitExpression`.

But that's why we throw on line 56, because `{ }` is the only supported syntax in this case.

2024-07-25 18:26 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5190Tests.cs
> +using System.Linq;
Done.

Note: Visual Studio does not think this is an unused import (that's why it was still there).

2024-07-25 18:26 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5190Tests.cs
> +                .Select(x => new BsonDocument("a", x.A) { });
Let's discuss in Slack whether we even want to expand the scope of this ticket.

2024-07-25 18:56 UTC, janiavdv commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewBsonDocumentExpressionToAggregationExpressionTranslator.cs
> +        public static AggregationExpression Translate(TranslationContext context, MemberInitExpression expression)
If we write
`new BsonDocument() { { "a", x.A } }` 
then 
`expression.Bindings.Count == 0`,
right?

2024-07-25 18:58 UTC, janiavdv commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5190Tests.cs
> +using System.Linq;
It's quite interesting that VS and Rider pick up on import use differently ...

2024-07-25 20:15 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewBsonDocumentExpressionToAggregationExpressionTranslator.cs
> +        public static AggregationExpression Translate(TranslationContext context, MemberInitExpression expression)
Not exactly. ```new BsonDocument() { { "a", x.A } }``` will be represented as a `ListInitExpression` instead of a `MemberInitExpression`.

2024-07-25 20:49 UTC, sanych-sun approved these changes
LGTM

2024-07-25 20:50 UTC, janiavdv approved these changes
LGTM!

2024-07-25 23:03 UTC, merged