CSHARP-5172: Updating an array fails if array contains values rather than documents.
mongodb/mongo-csharp-driver pull request #1399
Opened 2024-07-26 22:39 UTC by rstam

2024-07-29 16:31 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +    public record RenderArgs<TDocument>
@BorisDog add you as a reviewer to weigh in on whether `RenderArgs` should be a `class` or a `struct`.

2024-07-29 22:31 UTC, sanych-sun requested changes

2024-07-29 22:31 UTC, sanych-sun commented on src/MongoDB.Driver/RenderArgs.cs
> +        private readonly bool _renderForFind = false;
Should we introduce Enum instead? Like a 
```
enum RenderingContainer {
  Default = 0,
  Find = 1,
  ElemMatch = 2
}

```
 Or validate the parameters to avoid case when both `_renderForFind` and `_renderForElemMatch` set to `true`

2024-07-29 22:33 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +        private readonly bool _renderForFind = false;
I don't think so.

In this case I think `RenderForFind` and `RenderForElemMatch` might BOTH be true.

2024-08-01 16:10 UTC, rstam commented
@BorisDog if you want you can just review the `RenderArgs` changes.

2024-08-01 16:51 UTC, BorisDog approved these changes
RenderArgs LGTM. 
Left optional suggestion for tests organization.

2024-08-01 16:51 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5172Tests.cs
> +        public void Filter_ElemMatch_should_work(
Ideally we'd organize such tests in more thematic manner. 
For example this test would belong to hypothetical `BuildersFilterTests`  or `BuildersFilterElemMatchTests`

2024-08-12 18:04 UTC, sanych-sun approved these changes
LGTM

2024-08-12 18:15 UTC, merged