CSHARP-5193: Remove LINQ2 provider.
mongodb/mongo-csharp-driver pull request #1408
Opened 2024-08-09 04:35 UTC by rstam

2024-08-09 22:36 UTC, sanych-sun requested changes

2024-08-09 22:40 UTC, sanych-sun requested changes
Minor comments + it looks like GridFS tests are timing out now, need to investigate the problem.

2024-08-09 23:37 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            return new MongoClient();
We should pass results of `GetClientSettings()` to the `MongoClient` ctor here. Otherwise we skipping reading of all test configuration from env.

2024-08-09 23:43 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            return new MongoClient();
Good catch. Thank you!

2024-08-09 23:43 UTC, BorisDog commented on src/MongoDB.Driver/Linq/LinqProvider.cs
>      public enum LinqProvider
I think we should remove `LinqProvider` at all, as it's not used, and V4 is not really in the cards.
We might not even need it for hypothetical V4 with upcoming `MongoClientBuilder`,

2024-08-10 00:32 UTC, rstam commented on src/MongoDB.Driver/Linq/LinqProvider.cs
>      public enum LinqProvider
Removed.

2024-08-10 00:32 UTC, rstam commented on src/MongoDB.Driver/Linq/IMongoQueryable.cs
> -        QueryableExecutionModel GetExecutionModel();
Sure. Boris can you track this?

2024-08-10 00:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4079Tests.cs
> +        public void Positional_operator_with_negative_one_array_index_should_work_or_throw_depending_on_Linq_provider()
Done.

2024-08-10 00:33 UTC, rstam commented
> it looks like GridFS tests are timing out now, need to investigate the problem.

I see variants timing out but I don't see any evidence that it is because of GridFS. Why do you think that?

Not sure how to investigate a timeout. All tests up and until the timeout passed.

2024-08-10 00:34 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            return new MongoClient();
Done.

2024-08-12 16:42 UTC, sanych-sun approved these changes
LGTM

2024-08-12 16:53 UTC, BorisDog commented on src/MongoDB.Driver/Linq/IMongoQueryable.cs
> -        QueryableExecutionModel GetExecutionModel();
Added to the doc.

2024-08-12 17:06 UTC, BorisDog approved these changes
LGTM!

2024-08-12 22:59 UTC, merged