CSHARP-2930: Change default GuidRepresentationMode to V3 and default GuidRepresentation to Unspecified.
mongodb/mongo-csharp-driver pull request #1410
Opened 2024-08-12 16:52 UTC by rstam

2024-08-28 22:37 UTC, sanych-sun reviewed
Please check cake script, there are something that seems to be related to Guid representation.

2024-08-29 01:16 UTC, rstam commented
> Please check cake script, there are something that seems to be related to Guid representation.

I removed unused Guid related parts of build.cake.

2024-09-05 16:14 UTC, sanych-sun approved these changes
LGTM

2024-09-06 22:28 UTC, BorisDog requested changes

2024-09-06 22:28 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/GuidSerializerTests.cs
> +            var data = new TheoryData<GuidRepresentation>();
For your consideration: optional shorter form
`Deserialize_should_return_expected_result_when_representation_is_binary_MemberData() =>
EnumHelper.GetValues<GuidRepresentation>().Except([GuidRepresentation.Unspecified]).Select(v => new object[] { v });`

or
`[Values(GuidRepresentation.CSharpLegacy, GuidRepresentation.JavaLegacy, GuidRepresentation.PythonLegacy, GuidRepresentation.Standard)]`

2024-09-06 22:28 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
>          public void Deserialize_binary_data_should_throw_when_guid_representation_is_unspecified_and_mode_is_v3()
just `Deserialize_binary_data_should_throw_when_guid_representation_is_unspecified` ?

2024-09-06 22:28 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
>              GuidRepresentation writerGuidRepresentation,
`writerGuidRepresentation` not used anymore?

2024-09-06 22:28 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
>              GuidRepresentation readerGuidRepresentation,
`readerGuidRepresentation` not used anymore?

2024-09-09 18:45 UTC, BorisDog approved these changes
LGTM.

2024-09-10 01:08 UTC, merged