CSHARP-5221: Make APIs in ConnectionPools,Servers folders internal
mongodb/mongo-csharp-driver pull request #1416
Opened 2024-08-15 00:08 UTC by BorisDog

2024-08-20 21:07 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseCursorOperation.cs
> +            Task.FromResult(Execute(cancellationToken));
Dispose and CloseAsync seems to be not exactly the same. Is it safe to replace it? BTW, should IAsyncCursor implement IAsyncDisposable?

2024-08-21 17:01 UTC, rstam requested changes

2024-08-21 19:40 UTC, BorisDog commented on src/MongoDB.Driver/Core/ConnectionPools/IConnectionPool.cs
> +        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1721:Property names should not match get methods", Justification = "Backward compatibility")]
Yes, done. Thanks!

2024-08-21 19:40 UTC, BorisDog commented on src/MongoDB.Driver/Core/Configuration/ClusterBuilder.cs
> +        public ICluster BuildCluster() => BuildClusterInternal();
Good question. Eventually yes, the plan is to retire all `Cluster` related public API. 
But for minimizing the breaking changes in `MongoClient` setup and its use, we are thinking for marking this  area obsolete in 3.0 and remove in 4.0.

2024-08-21 19:40 UTC, BorisDog commented on src/MongoDB.Driver/Core/Servers/IServer.cs
> +    internal interface IServer
Via depericated `ClusterBuilder.Subscribe` and upcoming `MongoClientBuilder.Subscribe`. I'll emphasize this in the 3.0 doc.

2024-08-21 19:40 UTC, BorisDog commented on src/MongoDB.Driver/Core/Servers/Server.cs
> -        // fields
I don't recall myself adding them, and I thought they were some sort of a "old convention" leftovers.
Do you think there is still a value of having having such headers?
For example we know that fields are fields, and they should be grouped together. Does marking fields by "fields" add any value for us?

2024-08-21 19:40 UTC, BorisDog commented on src/MongoDB.Driver/Core/Clusters/Cluster.cs
> +        public static Range<int> SupportedWireVersionRange { get; } = WireVersion.SupportedWireVersionRange;
I am not sure auto properties play a role in understating the static part of this class.
IMHO having the static fields and properties defined in more concise way is clearer in this case.

For example `__minSupportedServerVersion` is static readonly, which is basically a constant, and we only need it outside the `Cluster` class. Why would we need to express that both by a private field and a public property?
The other question why `MinSupportedServerVersion` and `SupportedWireVersionRange` are even part of Cluster.

2024-08-22 23:23 UTC, rstam commented on src/MongoDB.Driver/Core/Servers/Server.cs
> -        // fields
It's been a convention in the driver all along to mark the beginning of each section with a comment.

A global search with a regular expression finds 2800+ matches give or take a few false hits.

I'd say it's a fairly well followed convention.

To me it always added value because it clearly separated the sections and served to emphasize to a reader that we have an established grouping.

2024-08-22 23:23 UTC, rstam commented on src/MongoDB.Driver/Core/Clusters/Cluster.cs
> +        public static Range<int> SupportedWireVersionRange { get; } = WireVersion.SupportedWireVersionRange;
The static state of a class consists of the values of all its static fields (whether constant or not).

Splitting the static state into two kinds, fields and auto-properties, makes it harder to understand the full set of static values that the class maintains or uses.

Same is true for instance state of course.

Regarding `MinSupportedServerVersion` and `SupportedWireVersionRange` I'm not sure why they are in this class.

2024-08-23 01:18 UTC, BorisDog commented on src/MongoDB.Driver/Core/Servers/Server.cs
> -        // fields
Looks like we already accumulated significant amount of code not following this convention (I'm responsible for larger part of it :)).
I suggest we address this and other inconsistencies as part of [CSHARP-4408](https://jira.mongodb.org/browse/CSHARP-4408).

2024-08-23 01:18 UTC, BorisDog commented on src/MongoDB.Driver/Core/Clusters/Cluster.cs
> +        public static Range<int> SupportedWireVersionRange { get; } = WireVersion.SupportedWireVersionRange;
In this case it's just a place holder of a contsant used globally. Added this to [CSHARP-3966](https://jira.mongodb.org/browse/CSHARP-3966).

2024-08-23 18:34 UTC, sanych-sun approved these changes
LGTM

2024-08-23 19:16 UTC, BorisDog commented on src/MongoDB.Driver/Core/Clusters/Cluster.cs
> +        public static Range<int> SupportedWireVersionRange { get; } = WireVersion.SupportedWireVersionRange;
Tracked in https://jira.mongodb.org/browse/CSHARP-5246

2024-08-23 20:09 UTC, rstam approved these changes
LGTM

2024-08-23 22:48 UTC, merged