CSHARP-5226: Remove non-RenderArgs Render overloads
mongodb/mongo-csharp-driver pull request #1417
Opened 2024-08-15 00:17 UTC by BorisDog

2024-08-15 00:18 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +                var renderedFilter = (BsonDocument)renderMethod.Invoke(filterDefinition, new object[] { renderArgs });
@rstam: Just discovered this dynamic rendering due to failing tests.

2024-08-15 17:34 UTC, rstam requested changes
Small change requested.

2024-08-15 17:34 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +                var renderedFilter = (BsonDocument)renderMethod.Invoke(filterDefinition, new object[] { renderArgs });
I propose adding a new private static helper method:

```
// private static methods
private static BsonDocument RenderFilter<TDocument>(FilterDefinition<TDocument> filterDefinition, IBsonSerializer<TDocument> documentSerializer, IBsonSerializerRegistry serializerRegistry)
{
    return filterDefinition.Render(new(documentSerializer, serializerRegistry));
}
```

and replacing lines 44-55 with:

```
var renderFilterMethod = typeof(InjectMethodToFilterTranslator).GetMethod(nameof(RenderFilter), BindingFlags.Static | BindingFlags.NonPublic).MakeGenericMethod(documentType);
var renderedFilter = (BsonDocument)renderFilterMethod.Invoke(null, new object[] { filterDefinition, documentSerializer, serializerRegistry });
return AstFilter.Raw(renderedFilter);
```

This localizes the use of reflection to *this* file only and isolates us from (or at least turns into compile time errors) changes to the `RenderArgs` constructor or the signature of the `Render` method.

2024-08-15 18:13 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +                var renderedFilter = (BsonDocument)renderMethod.Invoke(filterDefinition, new object[] { renderArgs });
Great idea! Done, thanks.

2024-08-15 18:19 UTC, rstam requested changes
Some naming fell through the cracks.

2024-08-15 18:19 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +        private readonly static MethodInfo __renderMethodInfo;
I like this optimization of caching the MethodInfo in a static field.

But the field should be named `__renderFilterMethodInfo`.

2024-08-15 18:19 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +                var renderMethod = __renderMethodInfo.MakeGenericMethod(documentType);
variable should be called `renderFiltermethod`

2024-08-15 18:25 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +        private readonly static MethodInfo __renderMethodInfo;
Done.

2024-08-15 18:26 UTC, BorisDog commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/InjectMethodToFilterTranslator.cs
> +                var renderMethod = __renderMethodInfo.MakeGenericMethod(documentType);
Done.

2024-08-15 18:27 UTC, rstam approved these changes
LGTM

2024-08-15 19:25 UTC, merged

2024-09-26 15:23 UTC, glen-84 commented
@BorisDog This is [another](https://github.com/mongodb/mongo-csharp-driver/pull/1393#issuecomment-2258348204) breaking change. Why was this released in a minor version?