CSHARP-4935: Linq3Implementation unable to handle interface as root
mongodb/mongo-csharp-driver pull request #1419
Opened 2024-08-16 01:12 UTC by rstam

2024-08-16 01:14 UTC, rstam reviewed
The LINQ changes in this PR look fine to me.

The concern we had that has kept this on the back burner is whether the change to `DiscriminatedInterfaceSerializer` would be backward breaking in any way.

2024-08-16 01:14 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +            _objectSerializer = objectSerializer ?? new ObjectSerializer(allowedTypes: type => typeof(TInterface).IsAssignableFrom(type));
Do you see any backward compatibility issues with this change?

2024-08-19 19:10 UTC, sanych-sun requested changes

2024-08-19 19:10 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +            _objectSerializer = objectSerializer ?? new ObjectSerializer(allowedTypes: type => typeof(TInterface).IsAssignableFrom(type));
It might be a problem if someone registered their own object serializer for some reasons. Can we implement method like a `WithAllowedTypes` on objectSerializer? So we lookup the same way as it was before - and then try to use this new method, similar to this:
```
var objectSerializer = BsonSerializer.LookupSerializer<object>();
if (objectSerializer is ObjectSerializer builtInSerializer)
{
    objectSerializer  = builtInSerializer.WithAllowedTypes(allowedTypes: type => typeof(TInterface).IsAssignableFrom(type));
}
```

2025-04-17 13:49 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DiscriminatedInterfaceSerializer.cs
> +            if (objectSerializer == null)
If a user passes in an `objectSerializer` we should use it as-is with no further configuration on our part. It is up to the user to pass in a properly configured seiralizer.

2025-04-17 22:52 UTC, sanych-sun approved these changes
LGTM

2025-04-29 22:57 UTC, sanych-sun approved these changes
LGTM

2025-04-29 23:09 UTC, merged