CSHARP-3310: Add TargetWireVersion to ExpressionTranslationOptions.
mongodb/mongo-csharp-driver pull request #1425
Opened 2024-08-22 18:28 UTC by rstam

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
> +        public static ExpressionTranslationOptions SetTargetWireVersionIfMissing(this ExpressionTranslationOptions options, int? targetWireVersion)
This method takes an existing `options` instance and sets the `TargetWireVersion` if it is missing.

It also creates a new instance if the `options` argument is `null`.

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> +        private readonly ExpressionTranslationOptions _translationOptions;
New field added to `TranslationContext`.

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> +                throw new ArgumentException("TargetWireVersion is not set.", nameof(translationOptions));
While the `translationOptions` might be `null` or have a missing `TargetWireVersion` before this point, by the time code reaches here we insist on having a defined `TargetWireVersion` so that during translation we always have a defined target.

Callers of this code have to ensure that the `translationOptions` are not `null` and have a defined `TargetWireVersion`.

Typically that would be determined as follows:

1. The user specified a `TargetWireVersion` (e.g. in `AggregateOptions`)
2. The target wire version is deduced from the `ClusterDescription`
3. The target wire version is defaulted to `Server40` if nothing else set it

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> -        private readonly RenderArgs<TDocument> _args;
We can't use a cached copy because the new `TargetWireVersion` needs to be determined as late as possible and could change from time to time.

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/PipelineDefinition.cs
> +        public string ToString(IBsonSerializer<TInput> inputSerializer, IBsonSerializerRegistry serializerRegistry) =>
An alternative to a new overload would be to add make the new `translationOptions` parameter optional using `translationOptions = null` in the method signature.

2024-08-22 19:14 UTC, rstam commented on src/MongoDB.Driver/RenderArgs.cs
> +        private readonly ExpressionTranslationOptions _translationOptions = default;
New field for `RenderArgs`. This will eventually get copied to the `TranslationContext` if rendering involves invoking a LINQ translator.

2024-08-22 19:14 UTC, rstam commented on tests/MongoDB.Driver.Tests/FindFluentTests.cs
> +/* Copyright 2010-present MongoDB Inc.
I think this file had inconsistent line ending prior to me editing it and asking Visual Studio to make the line endings consistent.

2024-08-22 19:14 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3933Tests.cs
> +            var stages = Linq3TestHelpers.Render(pipeline, BsonDocumentSerializer.Instance, ExpressionTranslationOptions.Default);
There is no way to compute the `TargetWireVersion` here so we just use the default `ExpressionTranslationOptions`.

The default has `TargetWireVersion` set to `Server40`.

2024-08-26 17:43 UTC, JamesKovacs requested changes
I’ve been going through the PR and have a few overall concerns:

- Potential implications of blocking to determine `maxWireVersion`. - Query rendering behaviour changing depending on connectivity to certain cluster members.
- Impossible to reason about the resulting MQL in a deterministic fashion.
- Problems for the Analyzer since at design time in the IDE you aren’t connected to any servers. The Analyzer would have to add a configuration option to specify maxWireVersion to be used when rendering out queries for tooltips.

Let’s discuss over Zoom.

2024-08-29 20:57 UTC, rstam commented on src/MongoDB.Driver/Core/Clusters/ClusterDescription.cs
> +        }
Sorry I missed this comment. I will add the tests and push a new commit.

2024-08-30 00:10 UTC, rstam commented on src/MongoDB.Driver/IMongoDatabaseExtensions.cs
> +            database.Client.GetTargetWireVersion();
Note that I would have used `ServerVersion` as the name of the `enum` but that type name was already taken to `TargetServerVersion` was the best alternative I could come up with.

2024-08-30 00:12 UTC, rstam commented
This PR is still blocked on https://github.com/mongodb/mongo-csharp-driver/pull/1420 (remove `IMongoQueryable`)

2024-08-30 17:35 UTC, sanych-sun requested changes

2024-08-30 17:35 UTC, sanych-sun commented on src/MongoDB.Driver/TargetServerVersion.cs
> +    public enum TargetServerVersion
I like enum better then set of int constants. But do we really need both of them? Can we eliminate constants in `WireVersion` by replacing with this new enum?

2024-08-30 17:35 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        public static int GetTargetWireVersion()
Should we call the method from `GetClientSettings` for proper defaults in tests?

2024-08-30 20:47 UTC, rstam commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
> +        public TargetServerVersion? TargetServerVersion { get; set; }
It is named `ExpressionTranslationOptions.TargetServerVersion` because this option means:

"When translating an Expression target this server version"

So it sounded quite natural to me.

2024-08-30 20:49 UTC, rstam commented on src/MongoDB.Driver/TargetServerVersion.cs
> +    public enum TargetServerVersion
Possibly... I didn't want to touch all the code that currently uses `WireVersion`.

2024-08-30 20:53 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        public static int GetTargetWireVersion()
No. 

`MongoClientSettings` is where the user tells us what server version to target. That's not necessarily the same as the server version currently connected to. If they don't tell us anything we default to target server 4.0. Almost all our tests should run with default settings (i.e. target server 4.0), and the few tests that need to target a newer server version will set their own `TargetServerVersion`.

This method determines the `TargetWireVersions` of the servers we are CURRENTLY connected to. It will be used in a subsequent commit related to `Join/GroupJoin` to determine what the current server is capable of, and to set the `TargetWireVersion` accordingly in some new tests.

2024-08-30 21:28 UTC, sanych-sun commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
> +        public TargetServerVersion? TargetServerVersion { get; set; }
I'm not insisting, but term "Target" sounds strict for me (like "I expect the exact version out there"), and not obvious what system will do if there is different server version discovered. When term "Compatibility" - sounds more understandable for me like "expect at least this level of API available on that side of wire".

2024-08-30 21:31 UTC, sanych-sun commented on src/MongoDB.Driver/TargetServerVersion.cs
> +    public enum TargetServerVersion
Ok, Can we at least redefine WireVersion constants referencing new enum values? like 
`public const int Server26 = (int)ServerVersionEnum.Server26;`

This way it will be obvious that both places are connected and should have the same set of versions.

2024-08-31 04:56 UTC, rstam commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
> +        public TargetServerVersion? TargetServerVersion { get; set; }
Discussed in Slack and we settled on `CompatibilityLevel`.

2024-08-31 04:56 UTC, rstam commented on src/MongoDB.Driver/TargetServerVersion.cs
> +    public enum TargetServerVersion
I've actually gone a step further and removed the integer values from the `ServerVersion` enum.

My thinking is that `ServerVersion` and `WireVersion` are actually two completely separate concepts and there is no reason they should have the same numeric values.

There is a mapping between them but it is not 1-to-1. There are many more server versions than there are wire versions.

When mapping from server version to wire version the result is the the wire version supported by that server version.

When mapping from wire version to server version the result is the FIRST server version that supported that wire version.

2024-09-03 19:30 UTC, rstam commented
Looks like a lot of failed variants due to some failing `SemanticVersionTests`.

I'll fix those... but they are basically orthogonal to the real work in this PR. They are related to the removal of the `ServerVersion` class, which we removed to free up the name for the new `ServerVersion` enum.

2024-09-03 22:37 UTC, rstam commented
I've fixed the SemanticVersion CompareTo issue.

2024-09-03 23:34 UTC, sanych-sun approved these changes
LGTM

2024-09-04 23:15 UTC, JamesKovacs requested changes
Overall looking good. There are still some remanants of trying to figure out `ServerVersion` from the `ClusterDescription` and those should be removed. Also there are a number of places where we pull apart `RenderArgs` to pass into a method whereas we could simply pass in `RenderArgs` directly.

2024-09-04 23:15 UTC, JamesKovacs commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +        }
These methods may no longer be required or can simply return `_args`.

2024-09-04 23:15 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineDefinition.cs
> +                var renderedStage = stage.Render(currentSerializer, args.SerializerRegistry, args.TranslationOptions);
Given that `currentSerializer` is `args.DocumentSerializer`, we could simply pass `args`to `Render` instead of deconstructing it to pull out specific parameters.

2024-09-04 23:15 UTC, JamesKovacs commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        }
Unused. Remove.

2024-09-04 23:15 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Core/Clusters/ClusterDescriptionTests.cs
> +        }
No longer used. Remove.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/Core/Clusters/ClusterDescription.cs
> +            _servers.Min(s => s.WireVersionRange?.Max);
We will need this in the PRs that are blocked on this one.

This is how we determine at runtime what capabilities the servers we are connected to have.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/Core/Misc/SemanticVersion.cs
> +        private static bool TryParseInternalPrelease(string preReleaseIn, out string preReleaseOut, out int? commitsAfterRelease, out string commitHash)
Oh interesting. I copy/pasted this from the deleted `ServerVersion.cs` file and didn't even  notice the typo!

Done.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
>          internal static ExpressionTranslationOptions Default = new ExpressionTranslationOptions();
OK. It was being used for awhile but I switched over to using `null` to mean use defaults.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/FieldDefinition.cs
> +            return LinqProviderAdapter.TranslateExpressionToField(_expression, args.DocumentSerializer, args.SerializerRegistry, args.TranslationOptions);
I briefly considered that, but these aren't `Render` methods.

I don't want to count on any coincidental overlap between translation arguments and render arguments.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/Linq/IMongoQueryProvider.cs
> +        ExpressionTranslationOptions GetTranslationOptions();
Why do you think it is unused? I find multiple references to it.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> -        private readonly RenderArgs<TDocument> _args;
It's still true but for a slightly different reason. It can be overridden by the various Aggregate methods.

It still feels safer to determine the `RenderArgs` dynamically when needed. 

It would be extremely confusing if we sometimes used cached `RenderArgs` and other times did not.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> -            _args = new(_documentSerializer, _settings.SerializerRegistry);
See comment above.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +            var renderedPipeline = pipeline.Render(renderArgs);
See comment above.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +            var renderedPipeline = pipeline.Render(renderArgs);
Same here.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +            var renderedPipeline = pipeline.Render(renderArgs);
And here.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +            var renderedPipeline = pipeline.Render(renderArgs);
See previous reply.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +        }
Pay close attention to the fact there there are TWO methods and in one case the `translationOptions` are computed by merging two different sets of translation options.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/PipelineDefinition.cs
> +                var renderedStage = stage.Render(currentSerializer, args.SerializerRegistry, args.TranslationOptions);
`currentSerializer` changes for every iteration of the loop.

2024-09-04 23:41 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        }
This is required in the next two PRs for tests that need to determine at runtime what the servers they are connected to support.

2024-09-04 23:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/Core/Clusters/ClusterDescriptionTests.cs
> +        }
See previous comments about why this method exists.

2024-09-04 23:41 UTC, rstam commented on src/MongoDB.Driver/FieldDefinition.cs
> +            return LinqProviderAdapter.TranslateExpressionToField(_expression, args.DocumentSerializer, args.SerializerRegistry, args.TranslationOptions);
Also, `RenderArgs` have a bunch of other things that have nothing to do with LINQ translation.

2024-09-05 04:07 UTC, rstam commented on src/MongoDB.Driver/Core/Clusters/ClusterDescription.cs
> +            _servers.Min(s => s.WireVersionRange?.Max);
I thought about this some more and for testing purposes we can use `CoreTestConfiguration.MaxWireVersion` to determine the capabilities of the server we are connected to.

While `CoreTestConfiguration.MaxWireVersion` does not acount for clusters with mixed server versions, that's OK because our test clusters never have mixed server versions.

2024-09-05 04:07 UTC, rstam commented on src/MongoDB.Driver/Core/Clusters/ClusterDescription.cs
> +            _servers.Min(s => s.WireVersionRange?.Max);
Removed

2024-09-05 04:07 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        }
As mentioned in a previous comment I thought about this and decided that we can use the existing `CoreTestConfiguration.MaxWireVersion` property instead.

2024-09-05 04:07 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +        }
Removed.

2024-09-05 04:07 UTC, rstam commented on tests/MongoDB.Driver.Tests/Core/Clusters/ClusterDescriptionTests.cs
> +        }
Removed. See updates to previous comments.

2024-09-05 23:17 UTC, JamesKovacs approved these changes
LGTM

2024-09-06 03:34 UTC, merged