CSHARP-5234: Make IConnection/IChannels and related API internal
mongodb/mongo-csharp-driver pull request #1434
Opened 2024-09-02 19:57 UTC by BorisDog

2024-09-03 17:46 UTC, JamesKovacs requested changes
Minor suggestions.

2024-09-03 17:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/Bindings/CoreTransaction.cs
> +        internal IChannelHandle PinnedChannel
XmlDoc comments above can be removed.

2024-09-03 17:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/Bindings/IChannel.cs
>          [Obsolete("Use an overload that does not have an oplogReplay parameter instead.")]
This can be removed as it is obsolete.

2024-09-03 17:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/Bindings/IChannel.cs
>          [Obsolete("Use an overload that does not have an oplogReplay parameter instead.")]
This method can be removed as it is obsolete.

2024-09-03 17:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/Connections/BinaryConnection.cs
> +    internal sealed class BinaryConnection : IConnection
XmlDoc comments can be removed.

2024-09-03 17:46 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/Connections/BinaryConnectionFactory.cs
> +    internal sealed class BinaryConnectionFactory : IConnectionFactory
XmlDoc comments can be removed.

2024-09-03 21:10 UTC, BorisDog commented on src/MongoDB.Driver/Core/Bindings/IChannel.cs
>          [Obsolete("Use an overload that does not have an oplogReplay parameter instead.")]
This new overload just fallbacks to the deprecated one. Removing it requires a larger change of removing `oplogReplay` everywhere (`CommandEventHelper`, `QueryMessage`...).  Created [CSHARP-5264](https://jira.mongodb.org/browse/CSHARP-5264) for that.

2024-09-03 21:10 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/BinaryConnection.cs
> +    internal sealed class BinaryConnection : IConnection
Done.

2024-09-03 21:10 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/BinaryConnectionFactory.cs
> +    internal sealed class BinaryConnectionFactory : IConnectionFactory
Done, thanks.

2024-09-04 16:31 UTC, JamesKovacs approved these changes
LGTM

2024-09-04 16:38 UTC, merged