CSHARP-5225: Mongo Serialization Deadlock
mongodb/mongo-csharp-driver pull request #1436
Opened 2024-09-04 16:47 UTC by sanych-sun

2024-09-04 16:50 UTC, sanych-sun commented on tests/MongoDB.Bson.Tests/DeadLockInvestigation.cs
> +        public void TestDeadLock()
This test will be removed before merging, because we have to add thread.sleep in factory method to make the problem visible.

2024-09-11 20:42 UTC, rstam requested changes
Let me know what you think of my comments. I might be off base... :)

2024-09-11 20:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +            if (classMap == null)
I don't think the check for `null` makes sense.

The only time it won't be `null` is if it *was* registered but *not* frozen. I don't think that happens very often.

In this rare case we can just look it up again.

2024-09-11 20:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +
I would propose the following variation for lines 333-368:

    BsonSerializer.ConfigLock.EnterReadLock();                                                             
    try                                                                                                    
    {                                                                                                      
        if (__classMaps.TryGetValue(classType, out var classMap))                                          
        {                                                                                                  
            if (classMap.IsFrozen)                                                                         
            {                                                                                              
                return classMap;                                                                           
            }                                                                                              
        }                                                                                                  
    }                                                                                                      
    finally                                                                                                
    {                                                                                                      
        BsonSerializer.ConfigLock.ExitReadLock();                                                          
    }                                                                                                      
                                                                                                           
    // automatically create a new classMap for classType and register it (unless another thread does first)
    // do the work of speculatively creating a new class map outside of holding any lock                   
    var classMapDefinition = typeof(BsonClassMap<>);                                                       
    var classMapType = classMapDefinition.MakeGenericType(classType);                                      
    var newClassMap = (BsonClassMap)Activator.CreateInstance(classMapType);                                
    newClassMap.AutoMap();                                                                                 
                                                                                                           
    BsonSerializer.ConfigLock.EnterWriteLock();                                                            
    try                                                                                                    
    {                                                                                                      
        if (!__classMaps.TryGetValue(classType, out var classMap))                                         
        {                                                                                                  
            RegisterClassMap(newClassMap);                                                                 
            classMap = newClassMap;                                                                        
        }                                                                                                  
                                                                                                           
        return classMap.Freeze();                                                                          
    }                                                                                                      
    finally                                                                                                
    {                                                                                                      
        BsonSerializer.ConfigLock.ExitWriteLock();                                                         
    }

2024-09-11 22:37 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +            if (classMap == null)
Sure can remove that check, I was not sure how often that might be happening. If it's absolutely rare case - then yep, definitely can simplify.

2024-09-11 23:22 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +
Done

2024-09-17 22:49 UTC, rstam approved these changes
Don't forget to remove the code that isn't supposed to be merged.

LGTM

2024-09-25 00:15 UTC, merged