CSHARP-5245: Make WireProtocol internal
mongodb/mongo-csharp-driver pull request #1437
Opened 2024-09-04 16:52 UTC by BorisDog

2024-09-04 17:32 UTC, JamesKovacs requested changes
See whether `JsonEncoders` for wire protocol messages are still needed. Also consider leaving test-related helpers as public.

2024-09-04 17:32 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/JsonEncoders/CommandMessageJsonEncoder.cs
> +    internal sealed class CommandMessageJsonEncoder : MessageJsonEncoderBase, IMessageEncoder
Do we even need this class (and related) anymore? We should never be serializing OP_MSG as JSON, only BSON. I suspect that everything in `src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/JsonEncoders/` can be deleted.

2024-09-04 17:32 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string ShellVersion = nameof(ShellVersion);
The JSON-related settings can be deleted.

2024-09-04 17:32 UTC, JamesKovacs commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string FixOldDateTimeMaxValueOnInput = nameof(FixOldDateTimeMaxValueOnInput);
Check which if any of these old settings can be deleted.

2024-09-04 17:32 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Core/Operations/OperationTestBase.cs
> +        private protected MessageEncoderSettings _messageEncoderSettings;
We don't typically use this access modifier. Seems unnecessary especially for a field in a test assembly.

2024-09-04 17:32 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/CommandMessageSectionEqualityComparer.cs
> +    internal sealed class CommandMessageSectionEqualityComparer : IEqualityComparer<CommandMessageSection>
Do we want to make test-related helpers internal? Consider leaving them public.

2024-09-04 22:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string FixOldDateTimeMaxValueOnInput = nameof(FixOldDateTimeMaxValueOnInput);
This is also a bigger task, need to remove `BsonBinarySubType.OldBinary`  and related logic for that.

2024-09-04 22:27 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Core/Operations/OperationTestBase.cs
> +        private protected MessageEncoderSettings _messageEncoderSettings;
With `MessageEncoderSettings` changed to be `internal`, compiler needs `private protected` to indicate that this field is limited to derived classes within the same assembly. And yes, I find "private protected" confusing...

2024-09-04 22:27 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Core/WireProtocol/Messages/CommandMessageSectionEqualityComparer.cs
> +    internal sealed class CommandMessageSectionEqualityComparer : IEqualityComparer<CommandMessageSection>
We need this change because `CommandMessageSection` is `internal` now.

2024-09-04 22:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string ShellVersion = nameof(ShellVersion);
Will be done in [CSHARP-5267](https://jira.mongodb.org/browse/CSHARP-5267).

2024-09-04 22:31 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string FixOldDateTimeMaxValueOnInput = nameof(FixOldDateTimeMaxValueOnInput);
Sorry, the previous comment might not be accurate. Double checking.

2024-09-04 22:49 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/MessageEncoderSettings.cs
> +        public const string FixOldDateTimeMaxValueOnInput = nameof(FixOldDateTimeMaxValueOnInput);
Removed. `BsonBinarySubType.OldBinary` does not have to be removed for that. These settings are never altered in wire protocol. Good catch.

2024-09-05 23:08 UTC, JamesKovacs approved these changes
LGTM

2024-09-06 00:45 UTC, merged