CSHARP-5266: Switch to Ubuntu for package creation
mongodb/mongo-csharp-driver pull request #1438
Opened 2024-09-04 18:36 UTC by sanych-sun

2024-09-04 23:27 UTC, BorisDog requested changes

2024-09-04 23:27 UTC, BorisDog commented on src/Directory.Build.props
> +    <TargetFrameworks>netstandard2.0;netstandard2.1;net472</TargetFrameworks>
same change for tests?

2024-09-04 23:41 UTC, sanych-sun commented on src/Directory.Build.props
> +    <TargetFrameworks>netstandard2.0;netstandard2.1;net472</TargetFrameworks>
Done

2024-09-05 17:07 UTC, sanych-sun commented on src/Directory.Build.props
> +    <TargetFrameworks>netstandard2.0;netstandard2.1;net472</TargetFrameworks>
Changes to tests were reverted. We need that condition there, so tests would not failure locally on non-Windows platforms.

2024-09-06 00:34 UTC, BorisDog approved these changes
LGTM! Please double check that the failures are not related to the changes.

2024-09-06 00:59 UTC, merged