CSHARP-5261: Add DateOnly support
mongodb/mongo-csharp-driver pull request #1440
Opened 2024-09-05 09:28 UTC by papafe

This PR is still in draft because we need support for the .NET 6 target framework before merging. I have made the changes for .NET 6 locally, but I did not push them to avoid polluting the PR. 

The behaviour of `DateOnlySerializer` has taken mostly inspiration from `DateTimeSerializer` with `DateOnly = true`, including throwing an exception when deserializing a date time with a non-zero time component.

2024-09-05 09:32 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateTimeSerializer.cs
>                          switch (flag)
I am not sure why here for `Ticks` we use `Int64Serializer`, while some lines down we use `bsonReader.ReadInt64`. Is it because here we want to be a little more permissive with the actual type used?

2024-09-11 19:01 UTC, rstam requested changes

2024-09-11 19:01 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    bsonWriter.WriteString(value.ToString("yyyy-MM-dd"));
Is this culture invariant?

2024-09-12 07:35 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +        public BsonType Representation { get; }
Fixed

2024-09-12 07:36 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                Representation.Equals(other.Representation);
Fixed the `Equals` method. 
And I should already have the indent set to spaces.

2024-09-12 07:38 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    bsonWriter.WriteString(value.ToString("yyyy-MM-dd"));
Reading the documentation at https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings, this seems to be the case

2024-09-12 07:38 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    value = DateOnly.ParseExact(bsonReader.ReadString(), "yyyy-MM-dd");
Reading the documentation at https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings, this seems to be the case

2024-09-12 07:38 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +    #if NET6_0_OR_GREATER
Fixed

2024-09-12 08:03 UTC, papafe commented
@rstam I've fixed the things you noted in your review and that we discussed yesterday. 
The only modification I have done is to use the `Int64Serializer` instead of spelling out the different cases for the various `BsonType` in the deserializer. I have decided to do so mostly to avoid code repetition and keeping the code for the deserialization of numeric types in the `Int64Serializer`, so in case we decide to do that kind of deserialization in other ways we can modify only that serializer and not also all the others. I can definitely be convinced otherwise though 😄

2024-09-12 15:38 UTC, rstam commented
> The only modification I have done is to use the `Int64Serializer` instead of spelling out the different cases for the various `BsonType` in the deserializer.

It's not wrong to do this, but we expect that 99% of the time the `BsonType` will actually be `Int64` and this approach involves several more levels of indirection before finally calling `ReadInt64` after all.

It's a tradeoff between conciseness and efficiency.

I made the comment in our Zoom conversation that serialization is the slowest part of our driver so maybe we need to worry more about efficiency.

2024-09-12 15:43 UTC, rstam commented
> Another question. I have added the `BsonType.Document` representation to align with the `DateTimeSerializer`. I remember you saying that it was a legacy representation for `DateTime`. Should we maybe avoid this representation at least for the new `DateOnlySerializer`?

The `Document` representation for `DateTime` is NOT legacy. It has a purpose.

The purpose is this: when representing a `DateTime` as a `BsonDateTime` there is a loss of precision. When saving a `DateTime` as an `Int64` we maintain full precision but make it hard to do MQL queries based on dates.

The `Document` representation stores the `DateTime` twice: once for easy of querying in MQL and again for keeping full precision.

That being said, IF we have a `Document` representation for `DateOnly` it would probably look different than the `Document` representation for `DateTime`.

2024-09-13 12:37 UTC, papafe commented
> > The only modification I have done is to use the `Int64Serializer` instead of spelling out the different cases for the various `BsonType` in the deserializer.
> 
> It's not wrong to do this, but we expect that 99% of the time the `BsonType` will actually be `Int64` and this approach involves several more levels of indirection before finally calling `ReadInt64` after all.
> 
> It's a tradeoff between conciseness and efficiency.
> 
> I made the comment in our Zoom conversation that serialization is the slowest part of our driver so maybe we need to worry more about efficiency.



> > The only modification I have done is to use the `Int64Serializer` instead of spelling out the different cases for the various `BsonType` in the deserializer.
> 
> It's not wrong to do this, but we expect that 99% of the time the `BsonType` will actually be `Int64` and this approach involves several more levels of indirection before finally calling `ReadInt64` after all.
> 
> It's a tradeoff between conciseness and efficiency.
> 
> I made the comment in our Zoom conversation that serialization is the slowest part of our driver so maybe we need to worry more about efficiency.

I have corrected this.

2024-09-17 08:50 UTC, papafe commented
@rstam The work for .NET 6 has been merged to main and I've rebased on top of that, so this should be mergeable after your review.

2024-09-17 23:07 UTC, rstam requested changes

2024-09-17 23:07 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +using Xunit;
Remove unused usings.

2024-09-17 23:07 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +        [InlineData("""{ "x" : { "$numberDouble" : "638649792000000000" } }""","10/20/2024" )]
I would use `"2024-10-20"` as the string for a date to avoid confusion about whether month or date goes first.

2024-09-17 23:07 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +            Action action = () => subject.Deserialize(context);
We use the following:

```
var exception = Record.Exception(() => subject.Deserialize(context));

exception.Should().BeOfType<FormatException>();
exception.Message.Should().Be("...");
```

```

2024-09-18 09:08 UTC, papafe commented
@rstam I've done the corrections following your points

2024-09-19 16:58 UTC, rstam requested changes

2024-09-19 16:58 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +        [InlineData("""{ "x" : { "$numberDouble" : "638649792000000000" } }""","2024/10/20" )]
The ISO standard for culture invariant dates is to use dashes: `2024-10-20`

2024-09-19 16:58 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +            exception!.Should().BeOfType<FormatException>();
I understand what the `!` is doing here but I didn't think we needed it with our current project settings.

2024-09-20 08:55 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +        [InlineData("""{ "x" : { "$numberDouble" : "638649792000000000" } }""","10/20/2024" )]
Sorry, when you wrote it the first time I did not notice the dashes, I've just corrected id

2024-09-20 08:56 UTC, papafe commented
Corrected according to notes

2024-09-20 08:57 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/DateOnlySerializerTests.cs
> +            exception!.Should().BeOfType<FormatException>();
You're right, corrected it.

2024-09-26 21:31 UTC, rstam approved these changes
LGTM

2024-09-27 13:05 UTC, merged