CSHARP-5250: Change Decimal128 default serialization to Bson.Decimal128
mongodb/mongo-csharp-driver pull request #1441
Opened 2024-09-05 11:41 UTC by papafe

2024-09-05 11:42 UTC, papafe commented
@rstam `Decimal128Serializer` has a static property called `Decimal128Instance` that is a "a cached instance of a Decimal128Serializer with Decimal128 representation". Given that now the `Decimal128` is the default representation, should we change the name of the static property to just `Instance` like with other serializers?

2024-09-11 16:02 UTC, rstam commented
> Given that now the `Decimal128` is the default representation, should we change the name of the static property to just `Instance` like with other serializers?

Sure. That makes sense.

2024-09-11 16:04 UTC, rstam requested changes
Looking good!

2024-09-11 16:04 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/Decimal128Serializer.cs
> +            : this(BsonType.Decimal128)
We need to make the same changes to `DecimalSerializer`.

There actually is no `Decimal128` datatype in .NET or a `decimal` type in BSON so we map between them when serializing and deserializing.

2024-09-11 18:56 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/Decimal128Serializer.cs
> +            : this(BsonType.Decimal128)
Makes sense. Done

2024-09-17 23:11 UTC, rstam approved these changes
LGTM

2024-09-18 06:50 UTC, merged