CSHARP-5269: Add ReadGuid and WriteGuid to BSON readers and writers.
mongodb/mongo-csharp-driver pull request #1446
Opened 2024-09-12 18:59 UTC by rstam

I probably should write more tests, particularly for failing scenarios.

But I wanted to get an initial review of this and pivot to working on discriminators for EF for a while.

2024-09-19 01:49 UTC, BorisDog reviewed
Overall approach LGTM

2024-09-19 01:49 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReader.cs
> +            VerifyBsonType("ReadGuid", BsonType.Binary);
`nameof(ReadGuid)` ?

2024-09-23 21:31 UTC, BorisDog approved these changes
LGTM + minor comment

2024-09-24 18:46 UTC, rstam commented on src/MongoDB.Bson/IO/BsonBinaryReader.cs
> +                throw new FormatException($"Length must be 16, not {bytes.Length}, when subType is {subType}.");
new `BsonBinaryData` throws an `ArgumentException` in this case but we want a `FormatException` from the serializer.

2024-09-24 18:46 UTC, rstam commented on src/MongoDB.Bson/IO/BsonReader.cs
> +                throw new FormatException($"Expected length to be 16, not {bytes.Length}.");
`GuidConverter.FromBytes` throws an `ArgumentException` in this case but we want a `FormatException` from the serializer.

2024-09-24 18:46 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReader.cs
> +                throw new FormatException($"Length must be 16, not {bytes.Length}, when subType is {subType}.");
new `BsonBinaryData` throws an `ArgumentException` in this case but we want a `FormatException` from the serializer.

2024-09-24 18:46 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
> +        [Theory]
These tests are new in the most recent commit.

2024-09-24 18:46 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        [InlineData("{ v : { $uuid : '01020304-0506-0708-090a-0b0c0d0e0f10' } }", BsonBinarySubType.UuidStandard, "0102030405060708090a0b0c0d0e0f10")]
Added some new JSON formats to test against.

2024-09-24 18:46 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void ReadGuid_should_throw_when_guid_representation_is_unknown(string json)
This test is new in the latest commit.

2024-09-24 18:46 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void ReadGuid_with_guidRepresentation_should_throw_when_subType_is_invalid(string json, GuidRepresentation guidRepresentation)
This test is new in the latest commit.

2024-09-24 18:46 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonReaderTests.cs
> +        public void ReadGuid_with_guidRepresentation_should_throw_when_length_is_invalid(string json, GuidRepresentation guidRepresentation)
This test is new in the latest commit.

2024-09-24 18:46 UTC, rstam commented on src/MongoDB.Bson/IO/IBsonWriter.cs
> +        /// Writes a Guid in Standard representation to the writer.
Good catch.

Done.

2024-09-24 19:57 UTC, BorisDog requested changes
Minor comments

2024-09-24 19:57 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
> +        [InlineData("{ v : HexData(128, '03') }", BsonBinarySubType.UuidStandard)]
minor: Consider adding a test for hexdata longer than 16 bytes, for completeness.

2024-09-24 19:57 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
> +        public void ReadGuid_should_throw_when_subType_is_invalid(string json)
Should this test be similar to  `JsonReaderTests.ReadGuid_should_throw_when_guid_representation_is_unknown` in naming and test cases?

2024-09-24 20:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
> +        public void ReadGuid_should_throw_when_subType_is_invalid(string json)
Renamed to `ReadGuid_should_throw_when_guid_representation_is_unknown` to match the other test.

I don't think we need the additional test case because in the other file we are testing JSON, and in this file we are testing BSON (and only using JSON as a human readable way to create a BSON document).

2024-09-24 20:39 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/BsonBinaryReaderTests.cs
> +        [InlineData("{ v : HexData(128, '03') }", BsonBinarySubType.UuidStandard)]
Done

2024-09-24 20:42 UTC, BorisDog approved these changes
LGTM!

2024-09-24 20:46 UTC, merged