CSHARP-5201: Allow update to supply sort option
mongodb/mongo-csharp-driver pull request #1453
Opened 2024-09-18 14:21 UTC by papafe

2024-09-19 01:05 UTC, BorisDog reviewed
Looks good overall! Now we need to wait for spec finalization.

2024-09-19 01:05 UTC, BorisDog commented on src/MongoDB.Driver/MongoCollectionBase.cs
> +            //TODO Why don't UpdateOne and UpdateOneAsync have a common path for creating the UpdateOneModel and BulkWriteOptions (if not more)?
In that case that can be done elegantly, we should do that in a separate ticket for other methods as well. Usually we can address such improvements on green-build Fridays.

2024-09-19 01:05 UTC, BorisDog commented on src/MongoDB.Driver/Core/Operations/UpdateRequest.cs
> +        public BsonDocument Sort
Alphabetical order.

2024-10-16 16:26 UTC, sanych-sun requested changes

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +        public BsonDocument Sort { get; init; }
I suppose it should be `SortDefinition<TDocument>` instead of BsonDocument.

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteUpdateOneModel.cs
> +        //TODO Maybe we need to pass the sort argument also to the constructors...?
I suppose we should have both: `init` and constructor. Init - it's a convenient modern way, ctor - it's needed for older dev environments where `init` is not supported.

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteUpdateOneModel.cs
> +        public BsonDocument Sort { get; init; }
Should we use `SortDefinition<TDocument>`?

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/ReplaceOneModel.cs
> +        private BsonDocument _sort;
Should we use `SortDefinition<TDocument>`?

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/ReplaceOptions.cs
> +        public BsonDocument Sort
Use `SortDefinition<TDocument>`.

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/UpdateOneModel.cs
> +        public BsonDocument Sort
Use `SortDefinition<TDocument>`.

2024-10-16 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/UpdateOptions.cs
> +        public BsonDocument Sort
Use `SortDefinition<TDocument>`.

2024-10-17 10:14 UTC, papafe commented on src/MongoDB.Driver/UpdateOptions.cs
> +        public BsonDocument Sort
Unfortunately `UpdateOptions` and `ReplaceOptions` are not generic classes, so we can't parametrize the properties. We can add the parameter, but I think it would be a breaking change. 
We could also add the generic `UpdateOptions<TDocument>` alongside the non generic version and make new methods that use this, while deprecating the methods that are using the non generico version. This would be the long road

2024-10-23 12:11 UTC, papafe commented on src/MongoDB.Driver/UpdateOptions.cs
> +        public BsonDocument Sort
I have done this only for `ReplaceOptions` for now. If all I've done makes sense, I'll do the same for `UpdateOptions`. 
This required to create a new class `ReplaceOptions<T>` and an implicit conversion operator from `ReplaceOptions` to `ReplaceOptions<T>`.

2024-10-30 22:51 UTC, BorisDog requested changes

2024-10-30 22:51 UTC, BorisDog commented on src/MongoDB.Driver/ReplaceOptions.cs
> +    public sealed class ReplaceOptions : ReplaceOptionsBase
Need to ensure that this change is not breaking.

2024-10-30 22:51 UTC, BorisDog commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
Yup we avoid breaking changes.

2024-10-30 23:21 UTC, rstam commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
This looks like a binary breaking change but not a source code breaking change.

There is also an implicit conversion operator from `ReplaceOptions` to `ReplaceOptions<TDocument>` that provides backward compatibility.

2024-10-31 07:36 UTC, papafe commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
Yes, I discussed this with Robert and this was an attempt to avoid creating more methods/overloads and keep source compatibility.
I was reading a little bit around online about semver in regards to binary compatibility. It seems that there is not a complete agreement on it, but overall it's recommended to increase major version with a binary-incompatible change. I'm not sure what's our stance on this debate, but I think I'll make an overload to be on the safe side 😁

2024-10-31 15:50 UTC, rstam commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
I would prefer a solution that doesn't involve doubling (or worse) the number of overloads. Too many overloads is a bad thing.

The current approach uses an implicit conversion from `ReplaceOptions` to `ReplaceOptions<TDocument>` to preserve backward compatibility.

Another approach could be to use subclassing: `ReplaceOptions<TDocument> : ReplaceOptions`. Then we could leave the current overloads unchanged at the expense of some type safety. The code that uses the `replaceOptions` would have to test whether the passed in options are the subclass or not.

2024-10-31 16:18 UTC, papafe commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
Given what we discussed at Triage today I'll park this ticket until next when we can have a more general discussion about breaking changes in general

2024-10-31 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
I have to apologize, I did not notice the implicit conversion. So this is not code breaking change.
On other hand I suppose it's better to follow Robert's suggestion with using of subclasses as clearer way to do the same thing. At least because this way we could avoid changes to public API.

2024-11-04 13:20 UTC, papafe commented on src/MongoDB.Driver/IMongoCollection.cs
> +        ReplaceOneResult ReplaceOne(FilterDefinition<TDocument> filter, TDocument replacement, ReplaceOptions<TDocument> options = null, CancellationToken cancellationToken = default(CancellationToke
I went for Robert suggestion and made the generic options derive from the base class we have now

2024-11-04 14:31 UTC, papafe commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +            : this(CollectionNamespace.FromFullName(collectionNamespace), filter, replacement, collation, hint, isUpsert, sort)
This is not binary compatible.
The alternative would be to add other two constructors (given that we already have two) but:
- Then we have 4 very similar constructors
- Developers using those constructors will have errors due to constructor ambiguity if they do not specify all parameters. This is theoretically still source compatible, but definitely annoying
Any suggestions about this? Personally I'd just keep the sort definition out of the constructor if we cannot find another alternative

2024-11-06 04:44 UTC, sanych-sun requested changes

2024-11-06 04:44 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +            : this(CollectionNamespace.FromFullName(collectionNamespace), filter, replacement, collation, hint, isUpsert, sort)
What if we add new constructor with `sort` as the very last non-optional parameter? In such way it would not be a breaking change and there would not be an ambiguity.

2024-11-06 09:19 UTC, papafe commented on tests/MongoDB.Driver.Tests/IMongoCollectionExtensionsTests.cs
> +            var replaceOptions = new ReplaceOptions<Person>();
Definitely

2024-11-06 09:28 UTC, papafe commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +            : this(CollectionNamespace.FromFullName(collectionNamespace), filter, replacement, collation, hint, isUpsert, sort)
That's a good idea, I didn't think about it :)
I've added two new constructor to mirror the ones we have already, and added a new private one that is being called by all the others

2024-11-06 17:47 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +            : this(CollectionNamespace.FromFullName(collectionNamespace), filter, replacement, collation, hint, isUpsert, sort)
Nice! And I suppose the plan should be to eliminate this copied ctors in next major release, by making the `sort` parameter as optional. So the question is: how we going to track this and not forget to do?

2024-11-06 17:49 UTC, sanych-sun reviewed
I'm ready to LGTM the changes, but could you please rebase before that? Because in the current main we already have that apicompat script, just want to be sure we did everything right in terms of backward compatibility.

2024-11-06 20:05 UTC, papafe commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +            : this(CollectionNamespace.FromFullName(collectionNamespace), filter, replacement, collation, hint, isUpsert, sort)
Yup, that would be the plan! I've added the constructors and the non generic options to the list of breaking changes for next version.

2024-11-06 20:09 UTC, papafe commented
@sanych-sun just rebased on main, curious to see what will the script say 😁

2024-11-07 08:50 UTC, papafe commented
@sanych-sun it seems the validate-apicompat task gave its ok 😁 
Do you think this is mergeable now?

2024-11-18 20:02 UTC, sanych-sun approved these changes
LGTM

2024-11-19 07:46 UTC, merged