CSHARP-5286: Add IHierarchicalDiscriminatorConvention and IScalarDiscriminatorConvention interfaces.
mongodb/mongo-csharp-driver pull request #1454
Opened 2024-09-18 18:13 UTC by rstam

2024-09-18 18:20 UTC, rstam commented
Here is a high level overview of the changes:

Added new interfaces:
* IHierarchicalDiscriminatorConvention
* IScalarDiscriminatorConvention
* IHasDiscriminatorConvention (and new GetDiscriminatorConvention helper extension method)

Rules about how discriminators work:
* discriminator can be omitted when nominal type == actual type (i.e. root class)
* discriminator for root class can be scalar even for hierarchical convention
* discriminator value of null means don't serialize _t

Additional notes:
* added SetDiscriminatorConvention to BsonClassMap
* the existing HierarchichalDiscriminatorConvention implements the new IHierarchicalDiscrminatorConvention interface
* the existing ScalarDiscriminatorConvention does not implement the new IScalarDiscriminatorConvention (yet)
* the only initial user of the in IScalarDiscriminatorConvention will be EF

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Bson/Serialization/IHasDiscriminatorConvention.cs
> +    public interface IHasDiscriminatorConvention
Named after the existing `IHasRepresentationSerializer`.

Just noticed I didn't add the `Serializer` suffix. Should I add it?

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/GetTypeComparisonExpressionToAggregationExpressionTranslator.cs
> +                var discriminator = discriminatorConvention.GetDiscriminator(nominalType, actualType);
Standardizing on `discriminator` instead of `discriminatorValue` everywhere.

The return value of `GetDiscriminator` is a `discriminator`...

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/TypeIsExpressionToAggregationExpressionTranslator.cs
> +                ast = AstExpression.Constant(true);
Optimization for trivial case.

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/TypeIsExpressionToAggregationExpressionTranslator.cs
> +                else if (discriminatorConvention is IScalarDiscriminatorConvention scalarDiscriminatorConvention)
This is new MQL to support queries against scalar discriminators.

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/TypeIsExpressionToAggregationExpressionTranslator.cs
> +                        AstExpression.Eq(discriminatorField, actualTypeDiscriminator));
I believe this MQL is slightly better than what we were generating.

Thoughts?

2024-09-18 18:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/AllOrAnyMethodToFilterTranslator.cs
> +                    var ofTypeFilter = AstFilter.Eq(discriminatorField, discriminator); // TODO: hierarchical vs scalar?
Feels like there is some more work to do here.

I'll have to figure this one out.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/Jira/CSharp2622Tests.cs
> +        [BsonKnownTypes(typeof(D))]
This class was misconfigured.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4691Tests.cs
> +            });
Not sure this configuration could have been done with attributes.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp5188Tests.cs
> +            AssertStages(stages, "{ $match : { '_t' : 'G' } }");
`F`, `G` and `H` use a scalar discriminator so the query can be simplified.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/Translators/PredicateTranslatorTests.cs
> +                "{ \"G\" : { \"Ids\" : null, \"D\" : \"Dolphin\", \"E\" : { _t : \"E\", \"F\" : 55, \"H\" : 66, \"S\": null, \"I\" : [\"insecure\"], \"C\" : null }, \"S\" : null, \"X\" : null, \"Y\"
`E` is now configured to use a hierarchical discriminator with the discriminator required even for the root class.

Note: `OfType` and `is` queries against hierarchical discriminators only work if the discriminator for an instance of the root class is not omitted, that's why it is required.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/FilterDefinitionBuilderTests.cs
> +            Assert(subject.OfType<Animal, Cat>("FavoritePet"), "{ \"favoritePet._t\" : \"Cat\" }");
Not sure how this worked with the lower case name.

2024-09-18 18:41 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            mockRootCollection.SetupGet(c => c.DocumentSerializer).Returns(BsonSerializer.LookupSerializer<TRoot>());
I don't like testing with mocks because tests fail in weird ways when the mock is not properly set up.

2024-09-18 20:43 UTC, damieng reviewed
Haven't had chance to go through the query/visitor stuff yet, a few comments for now. Will try this version with my EF fork to see how it goes in a couple of hours.

2024-09-18 20:43 UTC, damieng commented on src/MongoDB.Bson/Serialization/IHasDiscriminatorConvention.cs
> +    public interface IHasDiscriminatorConvention
I could go either way but have a preference for not having Serializer in the name. Originally I'd proposed IDiscriminationConventionProvider to match some of the other interfaces but I wasn't aware of IHasRepresentationSerializer.

2024-09-18 20:43 UTC, damieng commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                                convention = StandardDiscriminatorConvention.Scalar;
Is this a breaking change? Or is it safe given that heirarchical would only have emitted a single value and that it did that without wrapping it in a bsonarray?

2024-09-18 20:43 UTC, damieng commented on src/MongoDB.Bson/Serialization/Conventions/ScalarDiscriminatorConvention.cs
> +            if (actualType != nominalType || classMap.DiscriminatorIsRequired)
Why don't we want to store the discriminator in this case? Wouldn't it be beneficial to store it anyway?

2024-09-18 21:35 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                                convention = StandardDiscriminatorConvention.Scalar;
It might be breaking but I'm not sure how to analyze it.

The issue is that a hierarchical discriminator MUST have a root class that is the beginning of the hierarchy, so defaulting to hierarchical here was just plain wrong because there is no known root.

2024-09-18 21:35 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ScalarDiscriminatorConvention.cs
> +            if (actualType != nominalType || classMap.DiscriminatorIsRequired)
In order to preserve existing behavior.

I don't' recall exactly why we didn't store the discriminator for the root class when not using the hierarchical discriminator convention. Could have been because it's redundant and not storing it saves a few bytes?

The other reason might be that we don't actually know when serializing an instance of the root class whether it's part of a polymorphic hierarchy or not. So for example we want to avoid storing `{ _t : "Employee" }` in a collection of employees where every document is an instance of `Employee` and there are no subclasses.

2024-09-18 21:35 UTC, rstam commented on src/MongoDB.Bson/Serialization/IHasDiscriminatorConvention.cs
> +    public interface IHasDiscriminatorConvention
Our interfaces that end with `Provider` are more like factory interfaces that create new objects of some kind.

2024-09-19 13:22 UTC, damieng commented
Can confirm all EF Provider functional tests passing with these new changes including adding the IHasDiscriminator onto the EntitySerializer and no longer registering them on `BsonSerializer.__discriminatorConventions` via reflection. 💯

2024-09-19 16:01 UTC, JamesKovacs requested changes
We should avoid switching on types and simply implement a method to encapsulate the discriminator convention logic.

2024-09-19 17:18 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +                if (discriminatorConvention is IHierarchicalDiscriminatorConvention)
I don't think we want LINQ translation code in the discriminator convention.

The discriminator convention is ONLY about providing the values for `_t` during serialization and determining the *actual* type during deserialization.

How those `_t` values might or might not be used in the MQL generated by a LINQ query is not a concern of the discriminator convention.

Remember also that  users might want to implement their own discriminator conventions and in case they do we want to only burden them with the most minimal implementation demands possible.

Having said that, I do acknowledge the repetitive nature of some of this code. I will look for creating ways to refactor.

2024-09-19 17:18 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +                if (discriminatorConvention is IHierarchicalDiscriminatorConvention)
Note: `IDiscriminatorConvention` *already* has a method called `GetDiscriminator` whose purpose is to supply the value to store in the `_t` discriminator field.

2024-09-19 17:20 UTC, rstam commented
> We should avoid switching on types and simply implement a method to encapsulate the discriminator convention logic.

I don't think we can avoid switching on types, but I will look for a way to refactor to reduce the repetitive parts.

I had in fact already started looking at that but what looks repetitive at first glance is not 100% the same in each case so refactoring the repetitive part is not trivial.

2024-09-20 04:15 UTC, rstam commented
@JamesKovacs I've worked on addressing your concerns about code duplication.

The approach I came up with was to move the generation logic to the Ast classes. This is makes sense in general, but is slightly at odds with most Ast methods which tend to match closely to server MQL features. The new `TypeEquals` and `TypeIs` methods are at a slightly higher level because they can generate slightly more complex MQL. You can think of them as "macros".

I also modifed the Builders that were generating MQL by generating BsonDocuments directly to instead call the new Ast methods and then Rendering the Ast. This further reduced code duplication.

2024-09-20 16:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstExpression.cs
> +        public static AstExpression TypeEquals(AstGetFieldExpression discriminatorField, IDiscriminatorConvention discriminatorConvention, Type nominalType, Type actualType)
These new methods might be better as internal extension methods on the discriminator conventions (with suitably changed names).

It sort of feels wrong to me that the AST classes would know anything about discriminator conventions, because the AST mirrors server MQL and discriminator conventions are just something the driver knows about and AST shouldn't know about them.

Thoughts?

2024-09-23 18:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/DiscriminatorAstExpression.cs
> +    public static AstExpression TypeEquals(AstGetFieldExpression discriminatorField, IDiscriminatorConvention discriminatorConvention, Type nominalType, Type actualType)
I moved these methods here from `AstExpression.cs` because the Ast classes should not have any knowledge of how discriminators work.

Since there was no existing good place to put these methods I created a new class.

I named the class `DiscriminatorAstExpression` because it's like the `AstExpression` factory class but with knowledge of how discriminators are represented.

2024-09-23 18:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/DiscriminatorAstFilter.cs
> +    public static AstFilter TypeEquals(AstFilterField discriminatorField, IHierarchicalDiscriminatorConvention discriminatorConvention, Type nominalType, Type actualType)
I moved these methods here from `AstFilter.cs` because the Ast classes should not have any knowledge of how discriminators work.

Since there was no existing good place to put these methods I created a new class.

I named the class `DiscriminatorAstFilter` because it's like the `AstFilter` factory class but with knowledge of how discriminators are represented.

2024-09-26 12:50 UTC, damieng approved these changes
One nit and a few questions but nothing blocking.

Tested this version with latest EF type discriminator branch and still passing tests.

2024-09-26 12:50 UTC, damieng commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +                ofTypeFilter= discriminatorConvention switch
Nit: Missing space.

2024-09-26 12:50 UTC, damieng commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/DiscriminatorAstExpression.cs
> +            AstExpression.IsMissing(discriminatorField) :
Under what scenario does this get hit? We'd need to say we have a discriminator convention... but then return a null? And that would then exclude all docs with a discriminator value I presume. Wondering what query gets us here and the use case.

2024-09-26 12:50 UTC, damieng commented on src/MongoDB.Driver/OfTypeMongoCollection.cs
>                                                  new BsonDocument("$eq", new BsonArray { new BsonDocument("$type", "$_id"), "missing" }), // if "_id" is missed
Is `$type` remapped elsewhere or should this be using `discriminatorConvention.ElementName` ?

2024-09-27 23:08 UTC, JamesKovacs approved these changes
LGTM

2024-09-27 23:54 UTC, merged