CSHARP-3431: Make MongoClient IDisposable
mongodb/mongo-csharp-driver pull request #1461
Opened 2024-09-24 19:36 UTC by BorisDog

2024-09-26 18:35 UTC, mongoKart commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +            public static IMongoClient CreatClient()
Just happened to notice this typo while perusing the repo. Not sure how much it matters! Will require changes in all files, of course

```suggestion
            public static IMongoClient CreateClient()
```

2024-09-30 20:04 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/BenchmarkHelper.cs
> +            public static IMongoClient CreatClient()
Thanks, done!

2024-10-02 17:08 UTC, adelinowona approved these changes
LGTM

2024-10-02 17:25 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/MongoClientTests.cs
> +            client.Dispose();
Same a above

2024-10-02 17:26 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/OcspIntegrationTests.cs
> +        private IMongoClient CreateIMongoClient(bool tlsInsecure)
Minor: `CreateMongoClient`, without I.

2024-10-02 17:29 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +        private readonly IMongoClient _IMongoClient;
MInor: just `_mongoClient`

2024-10-02 18:26 UTC, rstam reviewed
See question in comments.

2024-10-03 01:26 UTC, BorisDog commented on src/MongoDB.Driver/MongoClient.cs
> +        public override void Dispose()
Good idea to add disposable pattern, done.
Normally we'd need finalizer only for unmanaged resources, so no need in this case.

2024-10-03 01:26 UTC, BorisDog commented on src/MongoDB.Driver/MongoClient.cs
> +            _settings.ClusterSource.ReturnCluster(_cluster);
Added `bool _disposed`.

2024-10-03 01:26 UTC, BorisDog commented on src/MongoDB.Driver/IClusterSource.cs
> +        public IClusterInternal GetOrCreateCluster(ClusterKey key);
Good idea, done.

2024-10-03 01:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoClientTests.cs
> +            client.Dispose();
Fixed.

2024-10-03 01:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OcspIntegrationTests.cs
> +        private IMongoClient CreateIMongoClient(bool tlsInsecure)
Fixed, thanks.

2024-10-03 01:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +        private readonly IMongoClient _IMongoClient;
Done.

2024-10-03 01:26 UTC, BorisDog commented on src/MongoDB.Driver/MongoDatabaseBase.cs
> +    internal abstract class MongoDatabaseBase : IMongoDatabase
Good suggestion, reverted, will submit a separate PR.

2024-10-03 17:54 UTC, rstam requested changes

2024-10-03 17:54 UTC, rstam commented on src/MongoDB.Driver/MongoClient.cs
> +        protected override void Dispose(bool disposing)
ALL the `MongoClient` methods should probably throw an `ObjectDisposedException` if called after the client has been disposed.

Not sure what should happen when you call collection and database methods after the client has been disposed. They should probably throw some sort of exception also.

2024-10-03 18:08 UTC, sanych-sun requested changes

2024-10-03 18:08 UTC, sanych-sun commented on src/MongoDB.Driver/MongoClient.cs
> +        public override void Dispose()
I still think we need finalizer here to ensure cluster will be returned. But as discussed - this could be done in upcoming releases.

2024-10-03 18:08 UTC, sanych-sun commented on src/MongoDB.Driver/IClusterSource.cs
> +        public void Return(IClusterInternal cluster) => ClusterRegistry.Instance.UnregisterAndDisposeCluster(cluster);
As it was discussed: we should either implement reference counting here or not unregister cluster at all (for now), as current implementation will have weird behavior in case two clients share same cluster, but one of them was disposed.

2024-10-03 21:32 UTC, BorisDog commented on src/MongoDB.Driver/IClusterSource.cs
> +        public IClusterInternal Get(ClusterKey key) => ClusterRegistry.Instance.GetOrCreateCluster(key);
Done.

2024-10-03 21:32 UTC, BorisDog commented on src/MongoDB.Driver/MongoClient.cs
> +        protected override void Dispose(bool disposing)
Good suggestion. Added `GetCluster()` to validate the state.

2024-10-03 21:32 UTC, BorisDog commented on src/MongoDB.Driver/MongoClient.cs
> +                    _settings.ClusterSource.Return(_cluster);
Added `GetCluster()` for that.

2024-10-03 21:32 UTC, BorisDog commented on src/MongoDB.Driver/IClusterSource.cs
> +        public void Return(IClusterInternal cluster) => ClusterRegistry.Instance.UnregisterAndDisposeCluster(cluster);
Yes this an important issue, changed the default behavior.

2024-10-07 16:40 UTC, rstam commented on src/MongoDB.Driver/MongoClient.cs
> +                    _settings.ClusterSource.Return(_cluster);
This is a pretty indirect method of throwing `ObjectDisposedException`.

Are there any methods that need to throw `ObjectDisposedException` that *don't* call `GetCluster`?

2024-10-07 23:48 UTC, sanych-sun approved these changes
LGTM

2024-10-08 14:31 UTC, rstam approved these changes
LGTM with the minor comment that calling `GetCluster` is a pretty indirect (and non-obvious) way of throwing an `ObjectDisposedException`.

A more normal way would be to call a `ThrowIfDisposed` helper method.

2024-10-09 16:43 UTC, sanych-sun approved these changes
LGTM + small suggestion

2024-10-09 16:43 UTC, sanych-sun commented on src/MongoDB.Driver/MongoClient.cs
> +        private void ThrowIfDisposed() => ThrowIfDisposed("dummy");
May be `string.Empty` instead of `"dummy"`?

2024-10-09 20:59 UTC, merged