CSHARP-4763: Support client side projections.
mongodb/mongo-csharp-driver pull request #1463
Opened 2024-09-26 18:19 UTC by rstam

2024-09-26 18:44 UTC, rstam commented on src/MongoDB.Driver/AggregateOptions.cs
> +            new AggregateOptions { TranslationOptions = translationOptions };
Does this implicit conversion seem OK?

It makes it much easier to create `AggregateOption` when the only setting you care about is translation options.

2024-09-26 18:44 UTC, rstam commented on src/MongoDB.Driver/ClientSideProjectionDeserializer.cs
> +            var document = _inputSerializer.Deserialize(context);
Currently bringing the whole document down to the client.

A future optimization (different JIRA ticket and different PR) will figure out what pieces of the document are actually needed by the client side projection.

2024-09-26 18:44 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/SelectMethodToPipelineTranslator.cs
> +                ClientSideProjectionHelper.ThrowIfClientSideProjection(expression, pipeline, method);
We have to throw this exception *outside* of the try/catch below.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            clientSettings.TranslationOptions = new ExpressionTranslationOptions { EnableClientSideProjections = true };
I defaulted to true for running the test suite in order to find all the tests that needed to be refactored after adding support for client side projections.

The default for `EnableClientSideProjections` is `false` (so actually the default is `null` but we interpret `null` as `false`).

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3529Tests.cs
> +                exception.Message.Should().Contain("This method is not functional");
This error message is not very helpful.

I would reword it to something like:

```The Bottom method is intended to be used in LINQ queries executed on the server and cannot be used in a client-side projection```

There are *many* methods with the same error message right now and they should probably all be reworded. Not sure if as part of this ticket or later as part of a separate ticket.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3958Tests.cs
> +                exception.Should().BeOfType<InvalidOperationException>(); // TeamMembers are not IComparable
This `Select` *could* have been executed client side *if* the `TeamMember` class had implemented `IComparable`.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3958Tests.cs
> +                result.Result.Select(tm => tm.Name).Should().Equal("Charlie", "Dallas", "Pat");
Even though `TeamMember` does not implement `IComparable` we got away with it here because there are no ties when sorting on `Name`.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4100ExpressionTests.cs
> +                serializer.Should().BeAssignableTo<IClientSideProjectionDeserializer>();
The collection doesn't have any data (yet) so we can't execute the query and assert against the results.

Should I add data and refactor a whole bunch of tests to execute the queries with client side projections and assert against the results?

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4410Tests.cs
> +                results.Should().Equal(true, true, true, true, true, true);
This is an example of a projection that can't be executed server side (because the two enums being compared are represented differently in the database) but can be executed client side because even though the two enums are represented differently in the database by the time they have been deserialized client side they are just enum values that can be compared.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4517Tests.cs
> +                results.Select(r => r.R).Should().Equal(true);
In this case we couldn't translate the `x.Id == 1` expression to MQL because it involves a user-defined implementation of the `==` operator.

But when we execute this projection client side the user-defined implementation of the `==` operator is accessible.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4763Tests.cs
> +        public void Aggregate_Project_with_client_side_projection_Match_should_throw(
More tests like this need to be written for all the kinds of things that could follow a client-side projection.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4957Tests.cs
> -        private class YSerializer : StructSerializerBase<int>
This test didn't actually require a custom serializer, but when it was first written we hadn't implemented `Equals` for serializers and using a custom serializer of a completely different class was a way to get this test to pass.

Now it is sufficient to just use two standard `IntSerializers` configured with different representations.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Linq3IntegrationTest.cs
> +            var translationOptions = aggregate.Options?.TranslationOptions.AddMissingOptionsFrom(collection.Database.Client.Settings.TranslationOptions);
This change was necessary to merge the two sets of translation options before passing them to `Translate` on the next line.

There are other similar changes that I didn't comment on each time.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NegateExpressionToAggregationExpressionTranslatorTests.cs
> +                results.Should().Equal(10M, -5M, 0M, decimal.MaxValue, -decimal.MaxValue);
Even though the `DecimalAsString` is a `string` in the database by the time we deserialize the value and pass it to the client-side projection it is a `decimal` instance.

2024-09-26 18:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationWithLinq2Tests/Translators/AggregateProjectTranslatorTests.cs
> +            var translationOptions = new ExpressionTranslationOptions { EnableClientSideProjections = false };
This is an old test that I didn't bother refactoring to run with `EnableClientSideProjections` either `false` or `true`.

2024-09-26 22:26 UTC, rstam commented
I'm checking out the failed tests on the patch build.

2024-09-26 22:42 UTC, rstam commented
One test was failing because .NET itself was throwing a different exception in .NET Framework 4.7.2 than in other target frameworks. I had been testing against net60.

2024-10-02 18:27 UTC, sanych-sun requested changes

2024-10-02 18:27 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            clientSettings.TranslationOptions = new ExpressionTranslationOptions { EnableClientSideProjections = true };
Should we revert this before merging into the main branch? As we probably do not want to run all tests with client side projection enabled.

2024-10-02 18:27 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3529Tests.cs
> +                exception.Message.Should().Contain("This method is not functional");
Should we create ticket to track this work?

2024-10-02 18:27 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4100ExpressionTests.cs
> +                serializer.Should().BeAssignableTo<IClientSideProjectionDeserializer>();
I'm OK with leaving as is.

2024-10-02 18:27 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3529Tests.cs
> +            [Values(false, true)] bool enableClientSideProjections)
There are really 3 possible states: `true`, `false` and `null`. Should we test all of the possible states to make sure we defaults to `false` on `null`s?

2024-10-02 22:25 UTC, rstam commented on src/MongoDB.Driver/ExpressionTranslationOptions.cs
> +                EnableClientSideProjections.Equals(other.EnableClientSideProjections);
And wouldn't you know it adding unit tests revealed some issues (but not `NullReferenceException`).

2024-10-02 22:25 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3529Tests.cs
> +            [Values(false, true)] bool enableClientSideProjections)
As per our discussion on Slack added tests including `null` in `CSharp4763.cs` only. That is sufficient.

2024-10-02 22:25 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp3529Tests.cs
> +                exception.Message.Should().Contain("This method is not functional");
I think so. I'm checking with Boris.

2024-10-02 22:43 UTC, rstam commented on src/MongoDB.Driver/AggregateOptions.cs
> +            new AggregateOptions { TranslationOptions = translationOptions };
Are we in agreement that this implicit conversion is OK?

2024-10-02 22:51 UTC, JamesKovacs commented on src/MongoDB.Driver/AggregateOptions.cs
> +            new AggregateOptions { TranslationOptions = translationOptions };
I agree that implicit conversions can be troublesome, but this use LGTM.

2024-10-03 16:18 UTC, damieng commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4763Tests.cs
> +            var translationOptions = new ExpressionTranslationOptions { EnableClientSideProjections = enableClientSideProjections };
This line showing as unused in my IDE.

2024-10-03 22:40 UTC, sanych-sun approved these changes
LGTM

2024-10-07 18:33 UTC, rstam commented
I rebased and fixed merge conflicts and made a few small changes requested. 

Force pushed a new commit to trigger the patch build.

2024-10-09 22:27 UTC, JamesKovacs approved these changes
LGTM

2024-10-09 23:20 UTC, merged