CSHARP-5262: Add TimeOnly support
mongodb/mongo-csharp-driver pull request #1467
Opened 2024-09-29 07:57 UTC by papafe

2024-09-30 17:59 UTC, rstam requested changes
Please re-request my review after the branch is linear.

2024-10-01 16:46 UTC, rstam requested changes
Some questions.

2024-10-01 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +        private readonly BsonType _representation;
Do we want to allow the user to configure `units` like we do in the `TimeSpanSerializer`?

A `TimeOnly` value is kind of like a `TimeSpan`.

I could imagine someone wanting the `TimeOnly` value stored in the database as hours or minutes instead of some oddball unit like ticks.

2024-10-01 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                case BsonType.String:
What about `Int32` or `Double`?

`Double` would be important if we also allow them to specify the units.

2024-10-01 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                BsonType.String => TimeOnly.ParseExact(bsonReader.ReadString(), "o"),
Is this culture invariant?

2024-10-01 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                    bsonWriter.WriteString(value.ToString("o"));
Is this culture invariant?

2024-10-01 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                _converter.Equals(other._converter);
The `_converter` is not user configurable and therefore doesn't actually need to be compared here.

`_converter.Equals(other._converter)` will always return `true`.

2024-10-01 17:03 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                BsonType.String => TimeOnly.ParseExact(bsonReader.ReadString(), "o"),
Yes, it should be: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier

2024-10-01 17:03 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                    bsonWriter.WriteString(value.ToString("o"));
As before

2024-10-01 17:04 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +        private readonly BsonType _representation;
I did not think about it... Do we want to give the same kind of units for this serializer too?

2024-10-02 13:01 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +        private readonly BsonType _representation;
I am adding configurable `units` too. Something that I've noticed is that for the string representation, the `TimeSpanSerializer` does not distinguish between the units. I think this makes sense, but I just want to be sure we want to do the same for the `TimeOnlySerializer` too

2024-10-02 15:23 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                case BsonType.String:
I have added `Int32` and `Double` as a consequence of adding various `units`

2024-10-02 15:24 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +                _converter.Equals(other._converter);
Ah right 🤦 . Corrected

2024-10-02 15:24 UTC, papafe commented
I have added the possibility of choosing different units, as well as tests for those

2024-10-07 20:06 UTC, rstam requested changes

2024-10-07 20:06 UTC, rstam commented on src/MongoDB.Bson/Serialization/Options/TimeOnlyUnits.cs
> +        Microseconds
Curious why you omitted `Nanoseconds` (which are present in `TimeSpanUnits`)?

Would it be a good idea to have the *same* units for `TimeOnly` as we already have for `TimeSpan`?

2024-10-07 20:06 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +        private readonly RepresentationConverter _converter;
`_converter` is not used?

2024-10-08 07:08 UTC, papafe commented
@rstam Added nanoseconds as a unit, as we discussed and removed the unused converter

2024-10-08 14:29 UTC, rstam approved these changes
LGTM with minor comment

2024-10-08 14:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +            return units is TimeOnlyUnits.Nanoseconds
Kind of odd to use `is` instead of `==` ...

2024-10-08 15:55 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/TimeOnlySerializer.cs
> +            return units is TimeOnlyUnits.Nanoseconds
Yeah, in this case it doesn't make much of a difference, but recently I have started using the pattern matching `is` compared to `==` because with this it is possible do things like:
```
if (units is Units.Microseconds or Units.Nanoseconds or Units.Days)
```

2024-10-08 15:58 UTC, merged