CSHARP-5237: Remove optional MD5 support from GridFS
mongodb/mongo-csharp-driver pull request #1475
Opened 2024-10-02 07:24 UTC by papafe

2024-10-02 19:38 UTC, BorisDog requested changes
Could you also create a ticket to mark this API as obsolete in 2.x please?

2024-10-02 19:38 UTC, BorisDog commented on src/MongoDB.Driver/GridFS/GridFSForwardOnlyDownloadStream.cs
> +            GridFSFileInfo<TFileId> fileInfo)
Do we also need remove MD5 option in `GridFSForwardOnlyUploadStream`,`GridFSBucketOptions`, `GridFSFileInfoCompat` and `GridFSUploadOptions`?

2024-10-02 20:08 UTC, papafe commented on src/MongoDB.Driver/GridFS/GridFSForwardOnlyDownloadStream.cs
> +            GridFSFileInfo<TFileId> fileInfo)
Yes, sorry, I should have opened this as a draft

2024-10-03 16:35 UTC, BorisDog approved these changes
LGTM!

2024-10-03 17:35 UTC, merged