[WIP] CSHARP-4145: Improved Bulk Write API
mongodb/mongo-csharp-driver pull request #1481
Opened 2024-10-04 17:35 UTC by sanych-sun

Work in progress. Please ignore tests at all.

2024-10-07 23:27 UTC, BorisDog requested changes
Partial review, some syntactic changes so far.

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +            return new[] { payload };
minor: ` return [payload]` ?

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> +
empty line

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> +        : base(operations, maxBatchCount, maxDocumentSize)
shift one tab right

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
empty lines

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +            else if(section is BatchableCommandMessageSection batchableSection)
add space `else if (`

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    case Type1CommandMessageSection type1Section:
minor: for readability/simplicity, you could do a single switch instead of two, with `sectionMaxSize` computation in a private method.

2024-10-07 23:27 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    var maxBatchSize = 2 * 1024 * 1024; // 2 MiB
minor: const (as class member)?

2024-10-08 03:04 UTC, BorisDog requested changes

2024-10-08 16:11 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                            if (bulkWriteResults.TopLevelException == null)
The idea here is to touch the cursor, and either consume it or just dispose (kill it) if there was an error. If we move the TopLevelException check upper it will not kill the cursor.

2024-10-08 16:12 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                    return ToFinalResultsOrThrow(context.Channel.ConnectionDescription.ConnectionId, bulkWriteResults);
We should provide ConnectionId for all ServerExceptions, which is not available outside of the loop =(

2024-10-08 16:43 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +            return new[] { payload };
We need to bump LangVersion to use collection expressions.

2024-10-08 16:49 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                            if (bulkWriteResults.TopLevelException == null)
I've simplified the code a little though. Thank you for the suggestions.

2024-10-08 16:54 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +        private readonly Dictionary<BulkWriteModel, BsonValue> _idsMap = new();
Done

2024-10-08 16:54 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                    "An error occured while ordered bulkWrite operation. See WriteErrors for more details.",
Fixed the error message.

2024-10-08 16:55 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                cursorDocument["firstBatch"].AsBsonArray.OfType<BsonDocument>().ToList(),
Probably Cast makes more sense here. Thanks!

2024-10-08 16:57 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                        bulkWriteResults.InsertResults.Add(operationIndex, new BulkWriteInsertOneResult
Done.

2024-10-08 16:59 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +            else if(section is BatchableCommandMessageSection batchableSection)
Done

2024-10-08 17:00 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    var maxBatchSize = 2 * 1024 * 1024; // 2 MiB
Done

2024-10-08 17:07 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    case Type1CommandMessageSection type1Section:
Done.

2024-10-08 17:07 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
Fixed.

2024-10-08 17:07 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> +
Fixed.

2024-10-08 17:08 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> +        : base(operations, maxBatchCount, maxDocumentSize)
Done

2024-10-08 17:09 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteDeleteManyModel.cs
> +    /// Represents delete one operation in scope of BulkWrite operation.
Fixed.

2024-10-08 17:12 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteDeleteManyModel.cs
> +        /// <param name="hint">The index to use.</param>
Hint it's a way to specify what index to use: https://github.com/mongodb/specifications/blob/7517681e6a3186cb7f3114314a9fe1bc3a747b9f/source/crud/bulk-write.md?plain=1#L79

2024-10-08 17:15 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteDeleteResult.cs
> +    /// Represents BulkWriteDelete operation result.
This class represents results for DeleteOne and DeleteMany operations. Comment has been adjusted a little.

2024-10-08 17:15 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteInsertOneResult.cs
> +        /// The _id of the inserted document.
Fixed.

2024-10-08 17:18 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteInsertOneResult.cs
> +    /// Represents BulkWriteInsertOne operation result.
Done.

2024-10-08 17:19 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +        /// <param name="isUpsert">Indicating whether to insert the document if it doesn't already exist.</param>
Fixed.

2024-10-08 17:19 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteResults.cs
> +        public sealed class Unacknowledged : BulkWriteResults
Fixed. Thanks.

2024-10-08 17:28 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteResults.cs
> +                get { throw new NotSupportedException("Only acknowledged writes support the InsertedCount property."); }
Done.

2024-10-08 17:30 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteException.cs
> +    public class ClientBulkWriteException : MongoServerException
Done. It was added because we use to have Serializable MongoServerException before.

2024-10-08 17:30 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteException.cs
> +        /// <param name="writeErrors">Errors that occurred during the execution of individual write operations.</param>
Fixed.

2024-10-08 17:31 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteException.cs
> +        public BulkWriteResults PartialResult { get; init; }
Done.

2024-10-08 17:32 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteOptions.cs
> +        /// Is bulk requests are fulfilled in order.
Done.

2024-10-08 17:33 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteOptions.cs
> +        public bool VerboseResult { get; set; }
It was `init` initially, but changed to `set` while unified spec implementation: we construct options step by step there.

2024-10-08 17:38 UTC, sanych-sun commented on src/MongoDB.Driver/IMongoClient.cs
> +        BulkWriteResults BulkWrite(IReadOnlyList<BulkWriteModel> models, ClientBulkWriteOptions options = null, CancellationToken cancellationToken = default);
BatchableSource require IReadOnlyList as a parameter. If we choose to have IReadOnlyCollection here, we will have to call ToList there, which is not good in terms of copying big list.

2024-10-08 18:08 UTC, sanych-sun commented on src/MongoDB.Driver/MongoClient.cs
> +            // TODO: use serializer registry configured on clint/settings when it will be implemented
Removed

2024-10-08 19:57 UTC, BorisDog commented on src/MongoDB.Driver/BulkWriteModel.cs
> +    /// Represents base class for all operations in scope of bulk write.
in the

2024-10-08 19:58 UTC, BorisDog commented on src/MongoDB.Driver/BulkWriteDeleteManyModel.cs
> +        /// <param name="hint">The index to use.</param>
I didn't know that, thanks for link.

2024-10-08 21:31 UTC, BorisDog requested changes

2024-10-08 21:31 UTC, BorisDog commented on src/MongoDB.Driver/IBulkWriteModelVisitor.cs
> +        void Visit(BulkWriteModel bulkWriteModel);
No need for non generic for now?

2024-10-08 21:31 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            => WriteOperation("delete", deleteManyModel, (context, model) =>
Consider avoiding lambdas (not sure they are being cached here, which means new instance is created for every request).

```
public void VisitDeleteMany<TDocument>(BulkWriteDeleteManyModel<TDocument> deleteManyModel)
{
    WriteOperation("delete", deleteManyModel, WriteBody);

    void WriteBody(BsonSerializationContext context, BulkWriteDeleteManyModel<TDocument> model)
    {
        var documentSerializer = _serializerRegistry.GetSerializer<TDocument>();
        WriteFilter(context, model.Filter, documentSerializer);
        WriteBoolean(context, "multi", true);
        WriteHint(context, model.Hint);
        WriteCollation(context, model.Collation);
    }
}
```

2024-10-08 21:31 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +                _idsMap.Add(_currentIndex, BsonValue.Create(objectId));
minor optimization: We can postpone creating `BsonValue` to the point we need it. (And maintain object instead)

2024-10-09 00:04 UTC, rstam requested changes
I haven't had much time to look at this closely but here's an initial review.

Please excuse any comments or requests that don't make sense to you if they are just a result of not understanding the code.

2024-10-09 00:04 UTC, rstam commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        public void VisitInsertOne<TDocument>(BulkWriteInsertOneModel<TDocument> insertOneModel)
Consider removing all uses of the word "visitor" because this doesn't seem to be a real visitor pattern.

This method might better be called `WriteInsertOneModel` and the method it calls might better be called `WriteModel`.

2024-10-09 02:21 UTC, BorisDog requested changes

2024-10-09 02:21 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedErrorMatcher.cs
> +            bool IsClientError(Exception exception)
move to the end

2024-10-09 02:21 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    var type1SectionFormatter = new Type1SectionFormatter(GetSectionMaxSize());
Ideally the formatters would be static and stateless, but we can consider this later.

2024-10-10 16:21 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                            if (bulkWriteResults.TopLevelException == null)
We need to kill the cursor if it exists. I suppose this is the simplest way to do that in Driver.

2024-10-10 16:26 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +                    var document = batch.Items[batch.Offset + i];
Renamed.

2024-10-10 16:56 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            RequireServer.Check().VersionGreaterThanOrEqualTo(new SemanticVersion(8, 0, 0, ""));
Feature

2024-10-10 17:43 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        public void VisitInsertOne<TDocument>(BulkWriteInsertOneModel<TDocument> insertOneModel)
Done.

2024-10-10 19:06 UTC, BorisDog requested changes
minor changes

2024-10-10 19:06 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            bulkWriteException.InnerException.Should().BeOfType<FormatException>();
Consider checking the message as well.

2024-10-10 19:06 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var client = DriverTestConfiguration.CreateDisposableClient((MongoClientSettings settings) =>
using

2024-10-10 19:12 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +            if (rawResults.InsertedCount + rawResults.UpsertedCount + rawResults.DeletedCount + rawResults.ModifiedCount == 0)
> Drivers MUST record the summary count fields in a `BulkWriteResult` to be returned to the user or embedded in a
> `BulkWriteException` if the response indicates that at least one write was successful
But it  seems like they changes the criteria from "any succedded" to "no errors", have to update the implementation.

2024-10-10 19:13 UTC, sanych-sun commented on src/MongoDB.Driver/IBulkWriteModelVisitor.cs
> +        void Visit(BulkWriteModel bulkWriteModel);
Removed.

2024-10-10 19:14 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            => WriteOperation("delete", deleteManyModel, (context, model) =>
Rewritten not to allocate delegates.

2024-10-10 19:17 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteResults.cs
> +        public virtual IReadOnlyDictionary<int, BulkWriteDeleteResult> DeleteResults { get; init; }
Yep. This is done accordingly to spec: https://github.com/mongodb/specifications/blob/c70785db882026bbc6119ab38d36fa564a216552/source/crud/bulk-write.md?plain=1#L326

2024-10-10 19:17 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteResults.cs
> +            private NotSupportedException CreateNotSupportedException([CallerMemberName] string callerMethod = null)
It's not really throws, but constructs the exception to be thrown in the calling property accessors.

2024-10-10 19:18 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        public void Visit(BulkWriteModel bulkWriteModel)
Removed.

2024-10-10 19:19 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> +        public RenderArgs<BsonDocument> RenderArgs { get; }
I had to store it somewhere, because we construct message with sections and then pass it to encoder. Otherwise I had to change lots of methods to pass it as a parameter.

2024-10-10 19:48 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +        private readonly Dictionary<int, BsonValue> _idsMap = new();
Yes, this class should be newed up for each operation. I suppose as all of our operations, as each of them store method's parameters as fields or properties on it.

2024-10-10 19:48 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +        : base(DatabaseNamespace.Admin, messageEncoderSettings)
Fixed.

2024-10-10 19:50 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +        public RenderArgs<BsonDocument> RenderArgs { get; init; }
In perfect world - yes, but I do not want to refactor all operations to introduce new parameter.

2024-10-10 19:57 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +            if (rawResults.InsertedCount + rawResults.UpsertedCount + rawResults.DeletedCount + rawResults.ModifiedCount == 0)
Code was updated to match the spec changes.

2024-10-10 20:00 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            _nsInfoWriter = new BsonBinaryWriter(new MemoryStream());
Fixed.

2024-10-10 20:01 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        public void Dispose() => _nsInfoWriter?.Dispose();
Dispose null up the value now.

2024-10-10 20:02 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            _renderArgs = section.RenderArgs;
Yes. But let's defer it until merging of high and core models.

2024-10-10 20:23 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +                        processedCount = i;
Probably need, will add this as a technical debt.

2024-10-10 20:24 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +
Removed.

2024-10-10 20:24 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +        private const int EncriptedMaxBatchSize = 2 * 1024 * 1024; // 2 MiB
Fixed.

2024-10-10 20:25 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +            long? GetSectionMaxSize()
Done

2024-10-10 20:26 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteModel.cs
> +    /// Represents base class for all operations in scope of bulk write.
Fixed.

2024-10-10 20:28 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +                .Subject.Should().Match(c => ((CommandStartedEvent)c).Command["ops"].AsBsonArray.Count == models.Length - 1);
Done

2024-10-10 20:30 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            result.InsertedCount.Should().Be(models.Length);
Done

2024-10-10 20:30 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +                .Subject.Should().Match(c => ((CommandStartedEvent)c).Command["ops"].AsBsonArray.Count == models.Length - 1);
Done

2024-10-10 20:31 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var failPointCommand = @"
Done

2024-10-10 20:32 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var failPointCommand = @"
Done

2024-10-10 20:53 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            RequireServer.Check().VersionGreaterThanOrEqualTo(new SemanticVersion(8, 0, 0, ""));
Done, thanks!

2024-10-10 20:53 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var client = DriverTestConfiguration.CreateDisposableClient((MongoClientSettings settings) =>
Done.

2024-10-10 20:54 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedErrorMatcher.cs
> +            bool IsClientError(Exception exception)
Done

2024-10-10 20:55 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedClientBulkWriteOperation.cs
> +        {
Done

2024-10-10 20:55 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedClientBulkWriteOperation.cs
> +            List<BulkWriteModel> models = null;
Done.

2024-10-10 21:13 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                    var writeModelType = writeModel.GetType().GetGenericTypeDefinition();
Will consider this for later.

2024-10-10 21:13 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +            public Dictionary<int, BulkWriteUpdateResult> UpdateResults { get; } = new();
Will add this to technical debt ideas.

2024-10-10 21:16 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/CommandMessageBinaryEncoder.cs
> +                    var type1SectionFormatter = new Type1SectionFormatter(GetSectionMaxSize());
Will review it later in scope of merging high and core models.

2024-10-10 22:00 UTC, JamesKovacs requested changes
Overall looking great. See comments inline.

2024-10-10 22:33 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteUpdateOneModel.cs
> +        public BulkWriteUpdateOneModel(
Will be added in scope of [CSHARP-5201](https://jira.mongodb.org/browse/CSHARP-5201): Allow update to supply sort option

2024-10-10 22:34 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +        public BulkWriteReplaceOneModel(
Will be added in scope of [CSHARP-5201](https://jira.mongodb.org/browse/CSHARP-5201): Allow update to supply sort option

2024-10-10 22:34 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteDeleteOneModel.cs
> +        public BulkWriteDeleteOneModel(
Will be added in scope of [CSHARP-5201](https://jira.mongodb.org/browse/CSHARP-5201): Allow update to supply sort option

2024-10-10 22:34 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
>          // private fields
Done

2024-10-10 22:34 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> -        private readonly int? _maxDocumentSize;
Done

2024-10-10 22:35 UTC, sanych-sun commented on src/MongoDB.Driver.Encryption/LibraryLoader.cs
> +                "libmongocrypt/macos",
Yep it is. But we have prose test that uses Auto-Encryption, that was failing, have to figure this out.

2024-10-10 22:36 UTC, sanych-sun commented on src/MongoDB.Driver/ClientBulkWriteOptions.cs
> +        }
I suppose we need it for some unfortunate developers who cannot use `init` yet.

2024-10-10 22:40 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/CommandMessageSection.cs
> -        private readonly IBsonSerializer _documentSerializer;
I've introduced another class in the same file with auto-props. And then decided to convert all the classes in the file. Can revert and use back-fields if we prefer so.

2024-10-10 22:59 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +                .Subject.Should().Match(c => ((CommandStartedEvent)c).Command["ops"].AsBsonArray.Count == models.Length - 1);
We can't do this for all tests.

2024-10-10 23:23 UTC, rstam requested changes
I don't get too deep into the depths of the Core classes...

The public API that a user would see looks good.

A few naming suggestions.

2024-10-10 23:23 UTC, rstam commented on src/MongoDB.Driver/BsonSerializerExtensions.cs
> +        public static object EnsureIdAssigned<TDocument>(this IBsonSerializer<TDocument> serializer, object container, TDocument document)
Suggested method name: `SetDocumentIdIfMissing`

Most `EnsureSomeCondition` methods throw an exception if the condition is not met, but this method doesn't do that.

2024-10-10 23:23 UTC, rstam commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            var objectId = documentSerializer.EnsureIdAssigned(null, model.Document);
Maybe name this variable `documentId`?

The name `objectId` implies that the type is `ObjectId`.

2024-10-10 23:23 UTC, rstam commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        private int EnsureNsInfo(string nsName)
Suggested method name: `GetNsInfoIndex`.

It is an implementation detail whether we're seeing the namespace for the first time or not.

2024-10-10 23:40 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            var documentSerializer = _serializerRegistry.GetSerializer<TDocument>();
We do not have collection here. Client's BulkWrite is available on MongoClient.

2024-10-10 23:45 UTC, BorisDog commented on src/MongoDB.Driver/Core/Operations/ClientBulkWriteOperation.cs
> +                            if (bulkWriteResults.TopLevelException == null)
Got it thanks.

2024-10-10 23:46 UTC, sanych-sun commented on src/MongoDB.Driver/MongoClient.cs
> +            return new RenderArgs<BsonDocument>(BsonDocumentSerializer.Instance, serializerRegistry, translationOptions: translationOptions);
Yes, you are right. This is a trick to have "type-less" renderArgs. Will pass `null`.

2024-10-10 23:48 UTC, sanych-sun commented on src/MongoDB.Driver/BsonSerializerExtensions.cs
> +        public static object EnsureIdAssigned<TDocument>(this IBsonSerializer<TDocument> serializer, object container, TDocument document)
Done.

2024-10-10 23:49 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            var objectId = documentSerializer.EnsureIdAssigned(null, model.Document);
Done

2024-10-10 23:49 UTC, sanych-sun commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +        private int EnsureNsInfo(string nsName)
Done

2024-10-11 00:30 UTC, rstam commented on src/MongoDB.Driver/MongoClient.cs
> +            return new RenderArgs<BsonDocument>(BsonDocumentSerializer.Instance, serializerRegistry, translationOptions: translationOptions);
Stupid auto-properties obscured from me the fact that `Ensure.IsNotNul`l was being called... :(

I saw this:

    DocumentSerializer = documentSerializer;

and assumed `null` would be OK.

2024-10-11 00:31 UTC, rstam commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +            var documentSerializer = _serializerRegistry.GetSerializer<TDocument>();
This will become a problem in the future when we let users configure the document serializer for a collection.

2024-10-11 00:34 UTC, rstam approved these changes
LGTM with the caveat that I started from the top down and didn't get to the very lowest levels.

The public API seen by a user looks good.

2024-10-11 17:51 UTC, BorisDog commented on src/MongoDB.Driver.Encryption/LibraryLoader.cs
> +                "libmongocrypt/macos",
Need to decide re. this.

2024-10-11 17:51 UTC, BorisDog commented on src/MongoDB.Driver/Core/WireProtocol/Messages/Encoders/BinaryEncoders/ClientBulkWriteOpsSectionFormatter.cs
> +                    if (writtenSize > (_maxSize - _nsInfoWriter.Position) && batch.CanBeSplit && i > 0)
Asked a question about `i >0`

2024-10-11 18:23 UTC, BorisDog approved these changes
LGTM!
Just need to double check the tests and create all the follow up tickets.

2024-10-11 20:27 UTC, merged