CSHARP-5311: Remove deprecation from BSON area
mongodb/mongo-csharp-driver pull request #1482
Opened 2024-10-07 11:01 UTC by papafe

2024-10-07 19:18 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonBinarySubType.cs
> +        [Obsolete("Use Binary instead")]  //TODO Should we remove this?
Not sure if we should remove this here

2024-10-07 19:21 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
>          public BsonDocument(params BsonElement[] elements)
Not sure if we want to remove this constructor, as in some cases it's easier than to create an enumerable and pass it. On the other hand maybe we do not want to have so many similar constructor

2024-10-07 19:43 UTC, papafe commented on src/MongoDB.Bson/IO/JsonOutputMode.cs
> +        [Obsolete("Use CanonicalExtendedJson instead.")]  //TODO Should we remove this?
Not sure if we should remove this

2024-10-07 19:44 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DictionarySerializerBase.cs
> +        [Obsolete("CreateInstance is deprecated. Please use CreateAccumulator instead.")]  //TODO Not sure what we want to do with this, it's used by the CreateAccumulator method
I'm not sure about this, the `CreateAccumulator` method is actually using this one  in its body.

2024-10-07 19:46 UTC, papafe commented
@rstam I have removed everything with the `Obsolete` attribute from almost everywhere in the BSON package, apart from a couple of places where I'm unsure. I've left a TODO and a comment in those places.

2024-10-07 20:36 UTC, rstam requested changes
Overall looks great!

2024-10-07 20:36 UTC, rstam commented on src/MongoDB.Bson/IO/JsonOutputMode.cs
> +        [Obsolete("Use CanonicalExtendedJson instead.")]  //TODO Should we remove this?
Good question! Not sure either.

2024-10-07 20:36 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonBinarySubType.cs
> +        [Obsolete("Use Binary instead")]  //TODO Should we remove this?
We could, but... if we do anyone who has really old data might not be able to read it anymore.

I'd ask Boris and Rishit.

2024-10-07 20:36 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
> +        //TODO Are we sure we want to remove this? Having a constructor with params is useful
Agreed.

2024-10-07 20:36 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DictionarySerializerBase.cs
> +        [Obsolete("CreateInstance is deprecated. Please use CreateAccumulator instead.")]  //TODO Not sure what we want to do with this, it's used by the CreateAccumulator method
I think we do want to remove this method and change `CreateAccumulator` to throw `NotImplementedException`.

2024-10-07 20:36 UTC, rstam commented on src/MongoDB.Bson/IO/JsonOutputMode.cs
> +        [Obsolete("Use CanonicalExtendedJson instead.")]  //TODO Should we remove this?
FYI `Strict` is a format the C# driver used BEFORE there was any extended JSON standard, but it is very similar to `CanonicalExtendedJson`.

2024-10-07 20:46 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonBinarySubType.cs
> +        [Obsolete("Use Binary instead")]  //TODO Should we remove this?
@BorisDog @rishitb-mongodb What do you think, should we remove this?

2024-10-07 20:47 UTC, papafe commented on src/MongoDB.Bson/IO/JsonOutputMode.cs
> +        [Obsolete("Use CanonicalExtendedJson instead.")]  //TODO Should we remove this?
@BorisDog @rishitb-mongodb Also here, do you think we should remove `JsonOutputMode.Strict`?

2024-10-09 18:09 UTC, BorisDog commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
>          public BsonDocument(params BsonElement[] elements)
Either way it fine IMHO.

2024-10-09 18:17 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonDocument.cs
> +        //TODO Are we sure we want to remove this? Having a constructor with params is useful
Removed the comment and left the constructor

2024-10-09 18:17 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DictionarySerializerBase.cs
> +        [Obsolete("CreateInstance is deprecated. Please use CreateAccumulator instead.")]  //TODO Not sure what we want to do with this, it's used by the CreateAccumulator method
Done

2024-10-09 18:17 UTC, papafe commented on src/MongoDB.Bson/IO/JsonOutputMode.cs
> +        [Obsolete("Use CanonicalExtendedJson instead.")]  //TODO Should we remove this?
We decided to remove it

2024-10-09 18:17 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonBinarySubType.cs
> +        [Obsolete("Use Binary instead")]  //TODO Should we remove this?
We decided to keep it, for compatibility reasons

2024-10-09 20:29 UTC, merged