CSHARP-5319: Remove AsDateTime and similar from BsonValue
mongodb/mongo-csharp-driver pull request #1494
Opened 2024-10-10 16:29 UTC by papafe

2024-10-10 21:44 UTC, rstam requested changes
There is a discussion going on about what exactly we should do.

I am proposing that we should keep `AsLocalTime` and `AsUniversalTime` because that it is the existing pattern established by all our other `AsXyz` properties.

2024-10-10 21:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> -        public DateTime AsLocalTime
I think this was obsoleted by mistake and we should keep the property and remove the `[Obsolete]` attribute.

2024-10-10 21:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> -        [Obsolete("Use ToUniversalTime instead.")]
I think this was obsoleted by mistake and we should keep the property and remove the `[Obsolete]` attribute.

2024-10-10 21:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> -        public DateTime? AsNullableDateTime
This property should be replaced with two properties: `AsNullableLocalTime` and `AsNullableUniversalTime`.

2024-10-10 21:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> -        [Obsolete("Use ToUniversalTime instead.")]
This obsoletion was proper and the member can be deleted.

The error message was wrong though. It should have been "Use AsUniversalTime" instead.

2024-10-11 01:14 UTC, rstam commented
Given our time zone difference and that I'm out of the office tomorrow I have prototyped in code what we were discussing earlier today:

https://github.com/rstam/mongo-csharp-driver/commits/csharp5319/

Summary of proposed changes:

Remove `AsDateTime` (use `AsUniversalTime` instead)
Remove `AsNullableDateTime` (use `AsNullableUniversalTime` instead)

Keep `AsLocalTime` (remove `[Obsolete]` attribute)
Keep `AsUniversalTime` (remove `[Obsolete]` attribute)

Add `AsNullableLocalTime`
Add `AsNullableUniversalTime`

Leave any existing "to date" methods alone.

2024-10-14 22:34 UTC, rstam requested changes

2024-10-14 22:34 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> +        [EditorBrowsable(EditorBrowsableState.Never)]
I think we want `DebuggerBrowsable` here.

Also, we want it for ALL `AsXyz` properties, not just the DateTime ones.

2024-10-15 06:46 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> +        [EditorBrowsable(EditorBrowsableState.Never)]
Yes, you're right, `DebuggerBrowsable` is the correct one, I've misunderstood the situation

2024-10-15 16:15 UTC, rstam requested changes

2024-10-15 16:15 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> +        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
Missing attribute on line 94.

2024-10-15 16:15 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> +        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
Missing attribute on line 192.

2024-10-15 16:19 UTC, papafe commented on src/MongoDB.Bson/ObjectModel/BsonValue.cs
> +        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
🤦 just added

2024-10-15 16:19 UTC, rstam approved these changes
LGTM

2024-10-15 16:21 UTC, merged