CSHARP-5342: Make sure ClientBulkWrite supports retryability properly
mongodb/mongo-csharp-driver pull request #1506
Opened 2024-10-18 19:19 UTC by sanych-sun

2024-10-25 21:42 UTC, BorisDog requested changes

2024-10-25 21:42 UTC, BorisDog commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +        internal override bool IsRetryable() => true;
Consider
`internal abstract bool IsMulti { get; }`
instead.

So `retryablity` decision is not in the model

2024-10-28 20:41 UTC, sanych-sun commented on src/MongoDB.Driver/BulkWriteReplaceOneModel.cs
> +        internal override bool IsRetryable() => true;
Done.

2024-10-28 22:38 UTC, BorisDog approved these changes
LGTM.
Please check the failures before merging.

2024-10-29 18:36 UTC, merged