CSHARP-5335: New serializers for immutable collections
mongodb/mongo-csharp-driver pull request #1508
Opened 2024-10-21 12:57 UTC by papafe

2024-10-21 23:29 UTC, rstam requested changes
Looks good so far.

2024-10-21 23:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumerableInterfaceImplementerSerializer.cs
> +            where TValue : IList, new()  //TODO Why this one uses IList instead of IEnumerable?
Not sure. If everything compiles and all tests pass with `IEnumerable` we can change it.

2024-10-21 23:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumerableInterfaceImplementerSerializerBase.cs
> -    public abstract class EnumerableInterfaceImplementerSerializerBase<TValue> : EnumerableSerializerBase<TValue>, IBsonArraySerializer where TValue : class, IEnumerable
Just trying to understand why `IBsonArraySerializer` was removed...

Is it because it was already declared as implemented on the base class?

2024-10-21 23:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumerableSerializerBase.cs
> +                    return default;
These lines look correct to me.

2024-10-21 23:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumerableSerializerBase.cs
> +                        throw new FormatException("Cannot deserialize a null value into a value type.");
Should we include the name of the value type in the message to help in debugging?

2024-10-21 23:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/ImmutableArraySerializer.cs
> +    public class ImmutableArraySerializer<T>: EnumerableInterfaceImplementerSerializerBase<ImmutableArray<T>, T>
This is exactly what I expected this small class to look like.

2024-10-22 06:48 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/EnumerableInterfaceImplementerSerializerBase.cs
> -    public abstract class EnumerableInterfaceImplementerSerializerBase<TValue> : EnumerableSerializerBase<TValue>, IBsonArraySerializer where TValue : class, IEnumerable
Exactly, it's already on the base class.

2024-10-23 06:53 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/ImmutableDictionarySerializer.cs
> +    public class ImmutableDictionarySerializer<TKey, TValue>: DictionaryInterfaceImplementerSerializer<ImmutableDictionary<TKey, TValue>, TKey, TValue>
This and the sorted dictionary have a different base class

2024-10-23 07:17 UTC, papafe commented
@rstam This should be ready for review now

2024-10-23 18:57 UTC, rstam requested changes
Minor requested change.

2024-10-23 18:57 UTC, rstam commented on src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
> +#if NETCOREAPP1_0_OR_GREATER
Use `NET6_0_OR_GREATER` here and in the other places also.

2024-10-25 06:04 UTC, papafe commented on src/MongoDB.Bson/Serialization/CollectionsSerializationProvider.cs
> +#if NETCOREAPP1_0_OR_GREATER
Done

2024-10-25 16:56 UTC, rstam approved these changes
LGTM

2024-10-28 09:28 UTC, merged