CSHARP-5349: Fix discriminator convention inheritance.
mongodb/mongo-csharp-driver pull request #1512
Opened 2024-10-23 23:44 UTC by rstam

2024-10-24 17:01 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +                        return StandardDiscriminatorConvention.Hierarchical;
I think this is still wrong... there just isn't a test to show that it is.

Consider this scenario: there might be a registered discriminator convention at this level and we're not looking it up.

2024-10-24 19:10 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +                        BsonSerializer.GetOrRegisterDiscriminatorConvention(classMap._classType, StandardDiscriminatorConvention.Hierarchical);
Calling `GetOrRegisterDiscriminatorConvention` instead of `RegsiterDiscriminatorConvention` is in order to avoid collisions between threads.

2024-10-24 19:10 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +        internal static IDiscriminatorConvention GetOrRegisterDiscriminatorConvention(Type type, IDiscriminatorConvention discriminatorConvention)
These don't need to be `public`.

2024-10-24 20:42 UTC, adelinowona commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +                        BsonSerializer.GetOrRegisterDiscriminatorConvention(classMap._classType, StandardDiscriminatorConvention.Hierarchical);
How does it avoid collisions?

2024-10-24 20:52 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonClassMap.cs
> +                        BsonSerializer.GetOrRegisterDiscriminatorConvention(classMap._classType, StandardDiscriminatorConvention.Hierarchical);
The new `GetOrRegisterDiscriminatorConvention` method uses the same lock as `RegsiterDiscriminatorConvention` to handle thread safety.

2024-10-24 21:09 UTC, adelinowona commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +            }
Is this whole block really needed? Seems a bit redundant to check for a registered convention here and then check again later on below when trying to register.

2024-10-24 21:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +            }
It may seem redundant but it's not. All the other methods use the same pattern.

The idea is that after the initial configuration phase is over everything can be done with read lock only, eliminating lock contention between threads.

The second check below is because of multithreading. Between releasing the read lock and acquiring the write lock some other thread might have snuck in and registered the convention.

2024-10-25 18:27 UTC, adelinowona approved these changes
LGTM

2024-10-30 07:31 UTC, papafe approved these changes

2024-11-01 17:10 UTC, sanych-sun requested changes

2024-11-01 17:10 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +        internal static IDiscriminatorConvention GetOrRegisterDiscriminatorConvention(Type type, IDiscriminatorConvention discriminatorConvention)
I would suggest to have slightly different method signature to mimic `ConcurrentDictionary.GetOrAdd` method signature:

```
internal static IDiscriminatorConvention GetOrAddDiscriminatorConvention(Type type, Func<Type, IDiscriminatorConvention> discriminatorConventionFactory)
```

2024-11-19 00:11 UTC, sanych-sun approved these changes
LGTM

2024-11-22 17:08 UTC, sanych-sun approved these changes
LGTM

2024-11-22 18:10 UTC, merged