CSHARP-5046: Test that durations are included on relevant pool events
mongodb/mongo-csharp-driver pull request #1526
Opened 2024-10-31 22:54 UTC by sanych-sun

2024-10-31 22:56 UTC, sanych-sun commented on src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                var stopwatch = Stopwatch.StartNew();
Have to start the stopwatch before all checks in StartCheckingOut happened. Otherwise ConnectionPoolCheckingOutConnectionFailedEvent could have zero duration for closed pool tests.

2024-10-31 22:57 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
There are new tests that ensure Duration has value, so cannot use TimeSpan.Zero anymore. So decide to use 42, because why not =)

2024-11-01 20:47 UTC, BorisDog requested changes

2024-11-01 20:47 UTC, BorisDog commented on src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                var stopwatch = Stopwatch.StartNew();
Good catch, looks like the previous implementation was actually a bug.

I think it would be more accurate to start the timer after emitting `ConnectionPoolCheckingOutConnectionEvent`.
so `StartCheckingOut` can return or receive the `stopwatch`.

2024-11-01 20:47 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
So the duration has a value here, it's just 0. Do we need to check that for mockConnection for Closed event?

2024-11-01 20:47 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
> +                        a++;
`a += 42` ? :)

2024-11-04 20:52 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
> +                        a++;
Ups, some debug code that does not intent to be pushed =)

2024-11-06 00:55 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
The test assert if the value is not `default`, when we use TimeSpan here which has TimeSpan.Zero (or simply 0) as default value.

2024-11-06 00:56 UTC, sanych-sun commented on src/MongoDB.Driver/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                var stopwatch = Stopwatch.StartNew();
I've decided to pass `stopwatch` into the `StartCheckingOut` method, to reduce the affected areas.

2024-11-06 21:03 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
So maybe let's use a different value here? like 1ms (also make it consistent with code below that uses `FromTicks`)?
It might be confusing to a reader to have two different meanings for `42` value.

2024-11-08 17:04 UTC, BorisDog requested changes
Small change in tests requested

2024-11-12 18:15 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
Sure. Will do =)

2024-11-14 20:20 UTC, sanych-sun commented on tests/MongoDB.Driver.TestHelpers/Core/MockConnection.cs
> +            _closedEventHandler?.Invoke(new ConnectionClosedEvent(_connectionId, TimeSpan.FromMilliseconds(42), EventContext.OperationId));
Done

2024-11-18 22:13 UTC, BorisDog approved these changes
LGTM

2024-11-18 22:15 UTC, merged