CSHARP-5200: Allow valid SRV hostnames with less than 3 parts
mongodb/mongo-csharp-driver pull request #1527
Opened 2024-11-01 13:24 UTC by papafe

2024-11-01 13:33 UTC, papafe commented on tests/MongoDB.Driver.Tests/Specifications/initial-dns-seedlist-discovery/prose-tests/SrvPartsTests.cs
> +                Which.Message.Should().Be("Hosts in the SRV record must have the same parent domain as the seed host.");
How much specific should we be with the error message? If we wanted to be very precise it could become:
"Hosts in the SRV record must have the same parent domain as the seed host. If the seed host has less than three separated dot separated parts, then the returned hostname must have at least one more domain level than the seed".
Would it be too much?

2024-11-01 16:38 UTC, sanych-sun requested changes

2024-11-01 16:38 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/initial-dns-seedlist-discovery/prose-tests/SrvPartsTests.cs
> +        [Theory]
Could you please add permalink to the prose test description in comment before the test so we can easily find what this test about?

2024-11-01 16:38 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Configuration/ConnectionString.cs
> +            var hostParts = host.Split('.').ToArray();
Can we avoid array allocation here? By counting number of '.' chars for length and checking if resolved host ends with original where we are comparing parts now.

2024-11-01 18:34 UTC, papafe commented on tests/MongoDB.Driver.Tests/Specifications/initial-dns-seedlist-discovery/prose-tests/SrvPartsTests.cs
> +        [Theory]
Just added them

2024-11-01 18:34 UTC, papafe commented on src/MongoDB.Driver/Core/Configuration/ConnectionString.cs
> +            var hostParts = host.Split('.').ToArray();
Makes sense! I've rewritten the method, hope it's readable enough

2024-11-01 18:34 UTC, papafe commented on tests/MongoDB.Driver.Tests/Specifications/initial-dns-seedlist-discovery/prose-tests/SrvPartsTests.cs
> +                Which.Message.Should().Be("Hosts in the SRV record must have the same parent domain as the seed host.");
@sanych-sun What do you think?

2024-11-05 23:56 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/Specifications/initial-dns-seedlist-discovery/prose-tests/SrvPartsTests.cs
> +                Which.Message.Should().Be("Hosts in the SRV record must have the same parent domain as the seed host.");
I'm OK with the current message.

2024-11-05 23:59 UTC, sanych-sun requested changes

2024-11-05 23:59 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Configuration/ConnectionString.cs
> +            for (int hostIndex = host.Length - 1, originalIndex = original.Length - 1;
Can this loop also be replaced with EndsWith?

2024-11-06 09:15 UTC, papafe commented on src/MongoDB.Driver/Core/Configuration/ConnectionString.cs
> +            for (int hostIndex = host.Length - 1, originalIndex = original.Length - 1;
You're right. I've rewritten the method to use `EndsWith` and use spans as much as possible to avoid string allocations

2024-11-14 09:18 UTC, merged