CSHARP-4960: Add new type field support for search indexes
mongodb/mongo-csharp-driver pull request #1528
Opened 2024-11-01 18:12 UTC by adelinowona

Add support for the `type` field when creating search indexes. Also syncs the unified search index tests and adds two new search index prose tests, as added in [jira.mongodb.org/browse/DRIVERS-2768](https://jira.mongodb.org/browse/DRIVERS-2768).

2024-11-01 21:26 UTC, BorisDog requested changes
Looks great, few changes in tests requested.

2024-11-01 21:26 UTC, BorisDog commented on src/MongoDB.Driver/CreateSearchIndexModel.cs
> +        public SearchIndexType? Type { get; }
Alphabetical order.

2024-11-01 21:26 UTC, BorisDog commented on src/MongoDB.Driver/Search/IMongoSearchIndexManager.cs
> +        string CreateOne(BsonDocument definition, SearchIndexType type, string name = null, CancellationToken cancellationToken = default);
We need to discuss how to avoid breaking changes here, maybe by using extension methods.

2024-11-01 21:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +        public async Task case8_driver_requires_explicit_type_to_create_vector_search_index()
Capital `C`

2024-11-01 21:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +        public async Task Case7_driver_can_handle_search_index_types_when_creating_indexes()
I think we need the sync version as well. And the index names to reflect that.
I've completely ignored that in other tests.

2024-11-01 21:26 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +                    "{ fields: [ { type: 'vector', path: 'plot_embedding', numDimensions: 1536, similarity: 'euclidean' } ] }");
We can make this a member like `_indexDefinition`

2024-11-04 16:17 UTC, adelinowona commented on src/MongoDB.Driver/CreateSearchIndexModel.cs
> +        public SearchIndexType? Type { get; }
Is this relevant in this context? From my observations, the properties in this class appeared to be arranged according to the sequence in which the parameters would be provided for index creation.

2024-11-04 16:37 UTC, adelinowona commented on src/MongoDB.Driver/Search/IMongoSearchIndexManager.cs
> +        string CreateOne(BsonDocument definition, SearchIndexType type, string name = null, CancellationToken cancellationToken = default);
I believe this change maintains both binary and source compatibility. Code compiled with `CreateOne(definition, name)` will continue to function as expected. Additionally, making the type parameter an enum and marking it as required eliminates any potential source ambiguity among the various `CreateOne` overloads

2024-11-07 00:24 UTC, BorisDog requested changes

2024-11-07 00:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +            [Values(false, true)] bool runAsync)
`async`, to align with rest of the tests.

2024-11-07 00:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +            return runAsync ? CreateIndexAndValidate("test-search-index-async", _indexDefinition) : CreateIndexAndValidate("test-search-index", _indexDefinition, false);
minor: use a shorter form:
pass `async` (runAsync) as parameter, and move name selection into `CreateIndexAndValidate`

2024-11-07 00:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +                : GetIndexes(indexDefinition1.Name, indexDefinition2.Name).GetAwaiter().GetResult();
All `GetAwaiter().GetResult()` should not be present anymore.
Pass `async` into `GetIndexes`.

2024-11-12 23:03 UTC, BorisDog approved these changes
LGTM + minor request

2024-11-12 23:03 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +            await CreateIndexAndValidate(runAsync ? "test-search-index-async" : "test-search-index", _indexDefinition, runAsync);
minor: You can just return the task without await:
```
Case1_driver_should_successfully_create_and_list_search_indexes =>
   CreateIndexAndValidate(...)
```

2024-11-12 23:03 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchIndexManagmentTests.cs
> +            [Values(false, true)] bool runAsync)
Need to address this

2024-11-14 13:32 UTC, merged