CSHARP-5345: Unable to deserialize C# DateOnly objects
mongodb/mongo-csharp-driver pull request #1534
Opened 2024-11-05 08:32 UTC by papafe

[JIRA ticket](https://jira.mongodb.org/browse/CSHARP-5345)

2024-11-05 08:37 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/SerializerHelper.cs
> -        private readonly long _allMemberFlags;
This was assigned but not used

2024-11-15 00:34 UTC, rstam requested changes

2024-11-15 00:34 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    if (_documentFormat is DateOnlyDocumentFormat.Classic)
Do we want to be more forgiving and deserialize whatever we find instead of requiring that the stored documents match the configured format?

2024-11-15 00:34 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +            if (_documentFormat is DateOnlyDocumentFormat.Classic)
It really throws me off to see `is` instead of `==`

2024-11-15 00:34 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +            return new DateOnlySerializer(representation, documentFormat);
Probably should include `_documentFormat` in line 291 below.

2024-11-15 08:08 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +            if (_documentFormat is DateOnlyDocumentFormat.Classic)
I started doing that mostly because I think it is convenient to use this form when one must check if the enum is one of multiple values:
`v is Enum.A or Enum.B` vs `v == Enum.A || v == Enum.B`
And from there I started using also when there is only value, for consistency, even though there is no particular advantage here. 
Of course I can put `==` if we prefer.

2024-11-15 08:10 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +            return new DateOnlySerializer(representation, documentFormat);
Definitely

2024-11-25 21:28 UTC, rstam requested changes

2024-11-25 21:28 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    if (_documentFormat is DateOnlyDocumentFormat.Classic)
Developers should ensure that their documents are all serialized in the same way in the database.

However, we almost always are willing to deserialize whatever we find. I don't see why deserializing whatever document format we find is any different than deserializing `Double` vs `DateTime` vs `Document` etc...

Maybe we need other people to chime in also.

2024-11-27 11:08 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    if (_documentFormat is DateOnlyDocumentFormat.Classic)
I corrected this part. The correction is kinda convoluted, but I'm not sure if we can make it easier on the eyes

2024-11-28 00:41 UTC, rstam requested changes

2024-11-28 00:41 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +        }
No need for two sets of flags. We can do this:

```
private static class Flags
{
    public const long DateTime = 1;
    public const long Ticks = 2;
    public const long Year = 4;
    public const long Month = 8;
    public const long Day = 16;
                               
    public const long DateTimeTicks = DateTime | Ticks;
    public const long YearMonthDay = Year | Month | Day;
}                                                         
```

See below for how the last two are used.

2024-11-28 00:41 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +
This whole `case BsonType.Document` can be improved.

I suggest the following refactoring for this whole method:

```
public override DateOnly Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
{
    var bsonReader = context.Reader;
                                    
    var bsonType = bsonReader.GetCurrentBsonType();
    switch (bsonType)
    {
        case BsonType.DateTime:
            return VerifyAndMakeDateOnly(BsonUtils.ToDateTimeFromMillisecondsSinceEpoch(bsonReader.ReadDateTime()));
                                                                                                                    
        case BsonType.Document:                                                                                     
            var ticks = 0L;                                                                                         
            var year = 0;                                                                                           
            var month = 0;                                                                                          
            var day = 0;                                                                                            
                        
            var foundMemberFlags = _helper.DeserializeMembers(context, (_, flag) =>
            {
                switch (flag)
                {
                    case Flags.DateTime: bsonReader.SkipValue();  break; // ignore value (use Ticks instead)
                    case Flags.Ticks: ticks = Int64Serializer.Instance.Deserialize(context); break;
                    case Flags.Year: year = Int32Serializer.Instance.Deserialize(context); break;
                    case Flags.Month: month = Int32Serializer.Instance.Deserialize(context); break;
                    case Flags.Day: day = Int32Serializer.Instance.Deserialize(context); break;
                }
            });
               
            if (foundMemberFlags == Flags.DateTimeTicks)
            {
                return VerifyAndMakeDateOnly(new DateTime(ticks, DateTimeKind.Utc));
            }
            else if (foundMemberFlags == Flags.YearMonthDay)
            {
                return new DateOnly(year, month, day);
            }
            else
            {
                throw new FormatException("Invalid document format.");
            }
             
        case BsonType.Decimal128:
            return VerifyAndMakeDateOnly(new DateTime(_converter.ToInt64(bsonReader.ReadDecimal128()), DateTimeKind.Utc));
                                                                                                                          
        case BsonType.Double:                                                                                             
            return VerifyAndMakeDateOnly(new DateTime(_converter.ToInt64(bsonReader.ReadDouble()), DateTimeKind.Utc));    
                                                                                                                          
        case BsonType.Int32:                                                                                              
            return VerifyAndMakeDateOnly(new DateTime(bsonReader.ReadInt32(), DateTimeKind.Utc));                         
                                                                                                                          
        case BsonType.Int64:                                                                                              
            return VerifyAndMakeDateOnly(new DateTime(bsonReader.ReadInt64(), DateTimeKind.Utc));                         
                                                                                                                          
        case BsonType.String:                                                                                             
            return DateOnly.ParseExact(bsonReader.ReadString(), "yyyy-MM-dd");                                            
                                                                                                                          
        default:                                                                                                          
            throw CreateCannotDeserializeFromBsonTypeException(bsonType);                                                 
    }                                                                                                                     
                                                                                                                          
    DateOnly VerifyAndMakeDateOnly(DateTime dt)                                                                           
    {                                                                                                                     
        if (dt.TimeOfDay != TimeSpan.Zero)                                                                                
        {                                                                                                                 
            throw new FormatException("Deserialized value has a non-zero time component.");                               
        }                                                                                                                 
                                                                                                                          
        return DateOnly.FromDateTime(dt);                                                                                 
    }                                                                                                                     
}
```

2024-11-28 00:41 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +
Don't forget to modify `Equals` below to also compare the `_documentFormam`

```_documentFormat.Equals(other._documentFormat)```

2024-11-28 08:41 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +
Sure! This looks very nice

2024-11-28 08:49 UTC, papafe commented on src/MongoDB.Bson/Serialization/Options/DateOnlyDocumentFormat.cs
> +        HumanReadable
I think it makes sense. A small thing I don't like is that `DateTimeTicks` at first glance looks like 3 elements, instead of two, but it's a small thing 😁

2024-11-28 10:23 UTC, papafe commented on src/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs
> +        /// <summary>
@rstam do you think this would be an appropriate place for this method?

2024-12-01 00:01 UTC, rstam requested changes

2024-12-01 00:02 UTC, rstam commented
Please rebase on main and force push to fix the failing auth tests in the patch build.

2024-12-02 08:30 UTC, papafe commented on src/MongoDB.Bson/Serialization/Serializers/DateOnlySerializer.cs
> +                    var ticks = 0L;
Makes sense! My bad, I didn't notice the returns in your suggestion before 🤦

2024-12-02 09:08 UTC, papafe commented on src/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs
> +        internal static IBsonSerializer GetReconfigured<T>(this IBsonSerializer serializer, Func<T, IBsonSerializer> reconfigure, Func<IBsonSerializer, bool> shouldReconfigure = null )
Regarding both points, I was actually having in mind the PR for configuring the `EnumRepresentationConvention` to work with collections of enums that we parked until the new major version, in particular [this method](https://github.com/papafe/mongo-csharp-driver/blob/cba6a12ed7949156f370f452bd5468d28f6bba51/src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs#L67).

For that case, because `EnumSerializer` is a generic type we can't simply use `serializer is TSerializer` and we need to do something else. Using the `GetReconfigured` method in that case would look something like this:

```csharp
var reconfigured = serializer.GetReconfigured<IRepresentationConfigurable>(
    configurable => configurable.WithRepresentation(_representation),
    bsonSerializer => serializer.ValueType.IsEnum);
```

This is one case where the `shouldReconfigure` method is used, because we cannot simply check the serializer type as we do it in this PR. 
Also, this shows why I didn't use `TSerializer` in the first place, because I thought it could cause some confusion given that it is not necessarily a serializer. Maybe it would be worth to call it `TSerializer` in any case to make it clearer?
I've also changed a little bit the xml docs because they were deceiving.

2024-12-04 22:09 UTC, rstam requested changes

2024-12-04 22:09 UTC, rstam commented on src/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs
> +        /// <summary>
Suggested new method:

```
namespace MongoDB.Bson.Serialization
{
    internal static class SerializerConfigurator
    {
        internal static IBsonSerializer ReconfigureSerializer<TSerializer>(IBsonSerializer serializer, Func<TSerializer, IBsonSerializer> reconfigure)
        {                                                                                                                                             
            switch (serializer)                                                                                                                       
            {                                                                                                                                         
                case IChildSerializerConfigurable childSerializerConfigurable:                                                                        
                    var childSerializer = childSerializerConfigurable.ChildSerializer;                                                                
                    var reconfiguredChildSerializer = ReconfigureSerializer(childSerializer, reconfigure);                                            
                    return reconfiguredChildSerializer != null? childSerializerConfigurable.WithChildSerializer(reconfiguredChildSerializer) : null;  
                                                                                                                                                      
                case TSerializer typedSerializer:                                                                                                     
                    return reconfigure(typedSerializer);                                                                                              
                                                                                                                                                      
                default:                                                                                                                              
                    return null;                                                                                                                      
            }                                                                                                                                         
        }                                                                                                                                             
    }                                                                                                                                                 
}                                                                                                                                                     
```

Note the name of the method and the removal of the unused `shouldReconfigure` parameter.

While you may have a future use in mind for `shouldReconfigure` as a general rule don't add anything until you actually need it. You might change your mind about it between now and then.

2024-12-05 09:57 UTC, papafe commented on src/MongoDB.Bson/Serialization/IBsonSerializerExtensions.cs
> +        /// <summary>
Makes sense! I've added this and corrected the call.

2024-12-06 21:02 UTC, rstam requested changes

2024-12-06 21:02 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonDateOnlyOptionsAttribute.cs
> +            var reconfiguredSerializer = SerializerConfigurator.ReconfigureSerializer<DateOnlySerializer>(serializer, s => s.WithRepresentation(_representation, _documentFormat));
I kind of liked my suggestion in an earlier review to put the `DateOnlySerializer` on the lambda parameter and let the compiler infer the generic method type from that:

```
var reconfiguredSerializer = SerializerConfigurator.ReconfigureSerializer(serializer, (DateOnlySerializer s) => s.WithRepresentation(_representation, _documentFormat));
```

Don't know if you just didn't notice that or didn't like it.

If you didn't like it we can go with what you have now.

2024-12-10 19:55 UTC, papafe commented on src/MongoDB.Bson/Serialization/SerializerConfigurator.cs
> +        /// <summary>
They don't need it, but I think it's not bad to have it. Maybe it helps at understanding what this method does without trying to read too much the implementation.

2024-12-11 15:14 UTC, rstam approved these changes
LGTM

2024-12-11 15:14 UTC, rstam commented on src/MongoDB.Bson/Serialization/SerializerConfigurator.cs
> +        /// <summary>
Sure you can leave these comments, but we're not going to start writing doc comments for internal classes in general. In general code should be written with proper naming that makes code self-describing.

Occasionally some small comments here and there may be helpful, but full-blown doc comments are not necessary.

2024-12-11 15:28 UTC, merged

2025-01-10 21:01 UTC, sguryev commented
Hey guys.
I have come here looking for the fix for the `An error occurred while deserializing the DateOfBirth property of class CustomerApp.Infrastructure.Entities.Individual: Invalid element: 'year'. Invalid element: 'year'.` error.

How it was before:
![image](https://github.com/user-attachments/assets/7c0b6e3a-1547-4322-bee8-98f398c8b055)

How it is now:
![image](https://github.com/user-attachments/assets/ec9f85b0-ffd9-4a50-b1fd-a6bd854e1a16)

My question is: will we be able to preserve backward compatibility and set the old format globally instead of adding attribute over every single `DateOnly` property or even do nothing and preserve old format?

Is it the correct final way to preserve the old behavior:
https://jira.mongodb.org/browse/CSHARP-5345?focusedId=6802536&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6802536
```
var dateOnlyClassMap = new BsonClassMap<DateOnly>(cm => cm.AutoMap()).Freeze();
var dateOnlyClassMapSerializer = new BsonClassMapSerializer<DateOnly>(dateOnlyClassMap);
BsonSerializer.RegisterSerializer<DateOnly>(dateOnlyClassMapSerializer); 
```

The solution above helped me to fix the issue I think
![image](https://github.com/user-attachments/assets/32cd0b6a-1e98-485f-a916-6ac371cd2f6c)

2025-01-13 08:23 UTC, papafe commented
@sguryev Yes, what you posted is a good "temporary" fix for the problem. When the content of this PR will be included with the next version you can either:
- Use the new attribute: 
```
[BsonDateOnlyOptions(BsonType.Document, DateOnlyDocumentFormat.YearMonthDay)]
 public DateOnly DateOfBirth { get; set; }
```
- Register a static serializer and set the correct format:
```
BsonSerializer.RegisterSerializer(new DateOnlySerializer(BsonType.Document, DateOnlyDocumentFormat.YearMonthDay));
```