CSHARP-2096: Make EnumRepresentationConvention also affect collection…
mongodb/mongo-csharp-driver pull request #1535
Opened 2024-11-05 13:32 UTC by papafe

…s of Enums

2024-11-05 13:33 UTC, papafe commented
This is still in draft because I need to check what happens with dictionaries

2024-11-05 17:16 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> -            if (IsNullableEnum(memberType))
I have removed the "nullable enum" case, since it is covered by new code

2024-11-05 17:25 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +        private IBsonSerializer Reconfigure(IBsonSerializer serializer)
This method here is recursively  trying to fin an `EnumSerializer`. If it finds it, it changes its representation and sets it as the new child serializer.
If no `EnumSerializer` "leaf" is found, it will return null.

2024-11-05 17:27 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (memberMap.MemberType.IsEnum && serializer is IRepresentationConfigurable representationConfigurableSerializer)
This part here of the code could be removed, as it is a special case of `Reconfigure`. I decided to keep it as maybe it's slightly faster than `Reconfigure` and it's possibly a much more common case. 

I've removed the "nullable enum" case though, but we can decide it needs to have the same treatment as this.

2024-11-05 17:28 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
>  */
This is effectively a beahviour breaking change. Should we keep this for next major version?

2024-11-05 17:29 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (serializerType.IsGenericType && serializerType.GetGenericTypeDefinition() == typeof(EnumSerializer<>))
I'm not sure if there is an easier/more efficient way of doing this here.

2024-11-15 00:14 UTC, rstam requested changes

2024-11-15 00:14 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (reconfiguredSerializer is not null)
Why do you prefer `is not null` to `!= null`?

2024-11-15 00:14 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +        private IBsonSerializer Reconfigure(IBsonSerializer serializer)
Searching for an `EnumSerializer` is a little stricter than what we used to do, which was search for a serializer for an enum value type that was representation configurable.

2024-11-15 00:14 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (serializerType.IsGenericType && serializerType.GetGenericTypeDefinition() == typeof(EnumSerializer<>))
How about?

```
if (serializer.ValueType.IsEnum && serializer is IRepresentationConfigurable representationConfigurable)
{                                                                                                       
    return representationConfigurable.WithRepresentation(_representation);                              
}                                                                                                       
```

2024-11-15 08:46 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (reconfiguredSerializer is not null)
I think sometimes it reads a little bit better, but in this case it probably does not make much of a difference. So I can definitely use `!=` if we prefer it

2024-11-15 08:52 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (serializerType.IsGenericType && serializerType.GetGenericTypeDefinition() == typeof(EnumSerializer<>))
That's perfect! I did not think about this 🤦

2024-11-25 16:59 UTC, papafe commented
@rstam I think this is ready to be merged, but I'd keep it open until we want to make the next major release, given that this is a behaviour breaking change

2024-11-25 21:23 UTC, rstam approved these changes
Sounds reasonable to wait until the next major release to deploy this behavioral breaking change.

2024-11-25 21:23 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
> +            if (memberMap.MemberType.IsEnum && serializer is IRepresentationConfigurable representationConfigurableSerializer)
I agree with your choice here.

2024-11-25 21:23 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/EnumRepresentationConvention.cs
>  */
Probably.

2024-11-26 17:37 UTC, papafe commented
Closing this PR for now as we should merge it when we want to release next major version, as this is a behaviour breaking change

2024-11-26 17:37 UTC, closed without merging