CSHARP-4495: Add conventions and attributes to configure ObjectSerial…
mongodb/mongo-csharp-driver pull request #1545
Opened 2024-11-15 12:25 UTC by papafe

…izer AllowedTypes

2024-11-15 18:59 UTC, rstam requested changes
Everything looks very reasonable!

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            var allowedDeserializationTypesArray = allowedDeserializationTypes as Type[] ?? allowedDeserializationTypes.ToArray();
Interesting optimization...

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            set
Maybe `init` instead of `set`?

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +        public bool AllowDefaultFrameworkTypes
I like the idea of giving them a way to opt-in the default framework types.

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            if (memberType == typeof(object) &&  memberMap.GetSerializer() is ObjectSerializer os)
I would avoid the abbreviation and use `objectSerializer`

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            var allowedDeserializationTypesArray = allowedDeserializationTypes as Type[] ?? allowedDeserializationTypes.ToArray();
However... we should probably make a defensive copy anyway because the caller might alter the array they passed in later.

2024-11-15 18:59 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            _allowedDeserializationTypes = allowedSerializationTypesArray.Contains;
`Contains` is a LINQ method that uses an enumerator, so it might be more efficient to use:

```type => Array.IndexOf(allowedDeserializationTypesArray, type) != -1```

Though I suppose it is possible the LINQ implementation of `Contains` has optimizations for arrays.

2024-11-18 08:49 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            if (memberType == typeof(object) &&  memberMap.GetSerializer() is ObjectSerializer os)
Definitely :)

2024-11-18 08:51 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            set
Yep, `init` would make more sense here

2024-11-18 08:52 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/AllowedTypesConvention.cs
> +            var allowedDeserializationTypesArray = allowedDeserializationTypes as Type[] ?? allowedDeserializationTypes.ToArray();
Yes, we should just make a copy

2024-11-18 10:36 UTC, papafe commented
@rstam This is ready for review now. Apart from all your notes, I've also allowed the convention to work with collections and nested collection (as we did with the `EnumConvention`).

2024-11-19 20:20 UTC, BorisDog requested changes
Looks good overall

2024-11-19 20:20 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +    public class ObjectSerializerAllowedTypesConvention
minor: sealed

2024-11-19 20:20 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public bool AllowDefaultFrameworkTypes
Should the default for this value match the default of `ObjectSerializer` for `DefaultFrameworkAllowedTypes`?

2024-11-20 10:52 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public bool AllowDefaultFrameworkTypes
Probably yes!

2024-11-20 11:47 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public ObjectSerializerAllowedTypesConvention() : this(Assembly.GetCallingAssembly())
Makes sense

2024-11-20 12:41 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public ObjectSerializerAllowedTypesConvention() : this(Assembly.GetCallingAssembly())
I have removed the automatic add of the types in the calling assembly and I have made `AllowDefaultFrameworkTypes ` default to true, similar to the behaviour of the `ObjectSerializer`. For this reason now the delegates that are passed to the `ObjectSerializer` are built lazily.

2024-11-20 12:42 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            });
Hope that this is readable enough

2024-11-21 00:28 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/ObjectSerializerAllowedTypesConventionTests.cs
> +            //Type in default framework types
nit: space after `//` : `// Type`

2024-11-21 07:16 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +    public sealed class ObjectSerializerAllowedTypesConvention
I think that would make sense

2024-11-21 07:43 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllCallingAssemblyAndDefaultFrameworkTypes => new(Assembly.GetCallingAssembly());
Not sure if it makes sense to have both `AllowAllCallingAssemblyAndDefaultFrameworkTypes` and `AllowAllCallingAssemblyTypes` or keep only the second one (but then we need to decide if the default framework types are included or not)

2024-11-21 23:53 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllCallingAssemblyAndDefaultFrameworkTypes => new(Assembly.GetCallingAssembly());
I think we need only need `AllowAllCallingAssemblyAndDefaultFrameworkTypes`

2024-11-21 23:53 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            return;
no need for `return`

2024-11-21 23:53 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        /// Default <see cref="ObjectSerializerAllowedTypesConvention"/> where no types are allowed for both serialization and deserialization.
Maybe not need for the word "Default", as it might be confused for an actual default?

2024-11-22 08:20 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllCallingAssemblyAndDefaultFrameworkTypes => new(Assembly.GetCallingAssembly());
Should keep the shortest name then? I'd vote for that

2024-11-22 08:38 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            return;
I agree, it's mostly to separate "visually" the method body from the local functions. I'm not super sold either way to be honest

2024-11-22 08:39 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        /// Default <see cref="ObjectSerializerAllowedTypesConvention"/> where no types are allowed for both serialization and deserialization.
Mmmh, I agree

2024-11-25 23:02 UTC, rstam requested changes

2024-11-26 09:20 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllTypes => new(ObjectSerializer.AllAllowedTypes);
Makes sense. 
Regarding `AllowAllCallingAssemblyAndDefaultFrameworkTypes`, I'd prefer to keep it as a property, for consistency.

2024-11-26 09:23 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            _allowedSerializationTypes = allowedTypesArray.Contains;
This should use only one delegate, so it should not make a difference

2024-11-26 09:30 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            _lazyAllowedSerializationTypes = new Lazy<Func<Type, bool>>(() => Construct(_allowedSerializationTypes));
The `Func` is built when it's used the first time, so the variables will be set by then

2024-11-26 09:31 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +                    : allowedTypes ?? ObjectSerializer.NoAllowedTypes;
Looks good!

2024-11-26 16:46 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllTypes => new(ObjectSerializer.AllAllowedTypes);
The issue with it being a property is that one usually expects that a property will have the same value no matter where it is called from, whereas it is less unexpected for a method to return a different value each time it is called (especially if you name the method in a way that implies that).

I don't insist on this though, but I don't want to highlight that this property is behaving in an odd way.

2024-11-27 10:19 UTC, papafe commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        public static ObjectSerializerAllowedTypesConvention AllowAllTypes => new(ObjectSerializer.AllAllowedTypes);
I think I agree with you on this, I changed it to be a method

2024-11-27 23:20 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +    public sealed class ObjectSerializerAllowedTypesConvention
This class needs to implement `IMemberMapConvention`.

Follow the pattern from other similar classes:

```
public sealed class ObjectSerializerAllowedTypesConvention : ConventionBase, IMemberMapConvention
 ```

2024-11-27 23:21 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +    public sealed class ObjectSerializerAllowedTypesConvention
To verify why implementing `IMemberMapConvention` is required try writing a test that registers this convention and see if it gets used during automapping.

This test will have to be disabled and only run manually in isolation, because registering this convention globally would affect other tests.

2024-11-27 23:22 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +            { AllowDefaultFrameworkTypes = false };
This formatting threw me off. I didn't realize at first that the line was continued on the next line.

Maybe this way:

```
public static ObjectSerializerAllowedTypesConvention AllowNoTypes { get; } =
    new(ObjectSerializer.NoAllowedTypes) { AllowDefaultFrameworkTypes = false };
```

2024-11-27 23:25 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/ObjectSerializerAllowedTypesConvention.cs
> +        private readonly bool _allowDefaultFrameworkTypes = true;
Consider placing line 61 immediately after line 56.

2024-11-28 11:10 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            var conventionName = Guid.NewGuid().ToString();
I found these tests that were registering conventions but never unregistering them

2024-11-28 11:11 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/ObjectSerializerAllowedTypesConventionTests.cs
> +        public void Convention_should_be_applied_during_automapping()
@rstam I've added this test to verify that the convention gets registered during automap. I know you've said we should only run it manually, but can't we register the convention and unregister it at the end of the test like here?

2024-12-01 00:18 UTC, rstam requested changes

2024-12-01 00:18 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            ConventionRegistry.Remove(conventionName);
Wow I am surprised the `Remove` method even exists.

A general principle of our whole serialization configuration machinery is that you shouldn't be able to change how things are serialized in the middle of the program run.

Though I guess this `Remove` method is somewhat less harmful because it doesn't change how anything that is already configured is serialized, only how future classes that have not yet been configured will end up being configured after the convention has been removed.

Note also that this convention does not HAVE to be unregistered. It is already programmed to ONLY apply to this one class with `t => t == typeof(A)`.

2024-12-01 00:18 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/ObjectSerializerAllowedTypesConventionTests.cs
> +        public void Convention_should_be_applied_during_automapping()
As i commented above I'm surprised we even have a method to unregister a convention. You shouldn't be able to alter conventions in the middle of a program run.

We can either unregister it as you discovered (even though I didn't think you should be able to do that), or you can simply program the convention to only apply to the class in this test and just leave it registered forever.

2024-12-01 00:18 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/ObjectSerializerAllowedTypesConventionTests.cs
> +            ConventionRegistry.Register(conventionName, new ConventionPack {subject}, _ => true);
Can't we use something more restrictive that `t => true`?

If we think about a time in the future where we want to run our tests in parallel relying on unregistering will no longer work.

2024-12-01 00:18 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            var conventionName = Guid.NewGuid().ToString();
This was not a problem because of `t => t == typeof(A)`

2024-12-02 09:35 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            ConventionRegistry.Remove(conventionName);
I understand we could have a convention that applies to a certain type and leave it registered, and while this likely does not affect anything else, shouldn’t we aim to keep the tests as independent as possible?

2024-12-02 16:35 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            ConventionRegistry.Remove(conventionName);
Yes, tests should be as independent as possible. That's why we should use `t => t == typeof(A)` instead of `t => true` here.

It's fine if you want to unregister this convention at the end of the test. I just wanted to make the following points:

1. The test was not inherently wrong because the registered convention only applied to this test
2. I was surprised we even had a `Remove` method

The `Remove` method concerns me because the way serialization is supposed to work is that an application configures serialization at startup and then leaves it alone. Removing a convention at some later time sounds like it would destabilize the application because POCOs might be serialized differently depending on whether the POCO is mapped before or after the convention was removed.

2024-12-02 21:03 UTC, papafe commented on tests/MongoDB.Bson.Tests/Serialization/Conventions/MemberDefaultValueConventionTests.cs
> +            ConventionRegistry.Remove(conventionName);
I agree with all the points :) 
I modified the predicate to be more restrictive, but kept the `Remove` to have a clean state after each test. I can agree also that maybe that method should not be there, but for now I'd say it's better to use it

2024-12-05 01:21 UTC, rstam approved these changes
LGTM

2024-12-06 12:21 UTC, merged