CSHARP-5305: Improve error message when custom LINQ extension method is executed client side.
mongodb/mongo-csharp-driver pull request #1547
Opened 2024-11-16 02:16 UTC by rstam

2024-11-16 02:16 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(AllElements)} can only be used in LINQ queries executed server-side.");
Is this error message good enough or can you think of even better?

2024-11-18 18:08 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(Where)} can only be used in LINQ queries executed server-side.");
Can move relace by single helper method to throw:
```
private void ThrowNotSupportedException([CallerMemberName]string callerName = null)
{
    throw new NotSupportedException($"{callerName} can only be used in LINQ queries executed server-side.");
}
```
So each method could be converted to simple expression body method:
```
public static IEnumerable<TSource> Where<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate, int limit) 
=> ThrowNotSupportedException()
```

2024-11-19 16:09 UTC, BorisDog commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(AllElements)} can only be used in LINQ queries executed server-side.");
IMHO it's good enough.

2024-11-19 16:09 UTC, BorisDog commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(Where)} can only be used in LINQ queries executed server-side.");
Good idea.

2024-11-19 17:16 UTC, damieng commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(Where)} can only be used in LINQ queries executed server-side.");
I think losing "MongoDB" is a step backward as no other LINQ providers will be able to translate this.

2024-11-19 20:02 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            throw new NotSupportedException($"{nameof(Where)} can only be used in LINQ queries executed server-side.");
Good point. I will include "MongoDB" in the error message.

2024-11-20 00:32 UTC, sanych-sun requested changes

2024-11-20 00:32 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/CustomLinqExtensionMethodHelper.cs
> +            throw new NotSupportedException($"{methodName} can only be used in MongoDB LINQ queries executed server-side.");
Should we return it instead of throwing?

2024-11-22 17:12 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/DateTimeExtensions.cs
> +            throw CustomLinqExtensionMethodHelper.CreateNotSupportedException();
Kind of "Yes", but being consistent here probably better. I think we should accept this change.

2024-11-22 17:13 UTC, sanych-sun approved these changes
LGTM

2024-11-22 20:24 UTC, merged