CSHARP-5203: Benchmark Collection and Client bulkWrite
mongodb/mongo-csharp-driver pull request #1550
Opened 2024-11-19 16:59 UTC by adelinowona

Here are results of the new benchmarks:
<markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(240, 246, 252); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Name | MB/sec
-- | --
SmallDocClientBulkWriteMixedOps | 1.9320055323
SmallDocCollectionBulkWriteMixedOps | 0.7543254574
LargeDocClientBulkWriteInsert | 94.103463269
LargeDocCollectionBulkWriteInsert | 96.6259091508
SmallDocClientBulkWriteInsert | 36.7585335938
SmallDocCollectionBulkWriteInsert | 40.8752903883

</markdown-accessiblity-table><br class="Apple-interchange-newline">

(Updated with latest EG run found [here](https://spruce.mongodb.com/task/dot_net_driver_driver_performance_tests_test_csharp_spec_benchmarks_patch_1a43b7138e2675ac0837e1ab3d8daa48645e75b0_6765d56f567cab000723c1bf_24_12_20_20_37_13/trend-charts?execution=0))

2024-11-22 23:07 UTC, BorisDog reviewed
Look good overall, would be good to have a sample run attached.

2024-12-05 19:53 UTC, adelinowona commented on CSharpDriver.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApp2", "ConsoleApp2\ConsoleApp2.csproj", "{54EBC539-ABFB-45A0-A77F-1A294576212B}"
Yes, thanks!

2024-12-05 19:55 UTC, adelinowona commented on evergreen/evergreen.yml
> +    - name: test-csharp-spec-benchmarks
Updating the name so that in the future, updating the .NET version or server version doesn't cause us to lose history.

2024-12-20 18:43 UTC, sanych-sun approved these changes
LGTM

2024-12-20 23:42 UTC, BorisDog requested changes
minor comments

2024-12-20 23:42 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/BulkWriteMixedOpsBenchmark.cs
> +        private static readonly List<string> __collectionNamespaces = Enumerable.Range(0, 10)
minor: Consider `string[]`, array is just a simpler type.
Consider this in other places in this PR.

2024-12-20 23:42 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/BulkWriteMixedOpsBenchmark.cs
> +            _collection.BulkWrite(_collectionBulkWriteMixedOpsModels, new BulkWriteOptions());
minor: will `_collection.BulkWrite(_collectionBulkWriteMixedOpsModels, new());` compile?
Same for `SmallDocClientBulkWriteMixedOpsBenchmark` and other benchmarks.

2024-12-20 23:42 UTC, BorisDog commented on evergreen/evergreen.yml
> +
Unnecessary spaces?

2024-12-26 18:56 UTC, BorisDog approved these changes
LGTM!

2024-12-26 18:56 UTC, BorisDog commented on benchmarks/MongoDB.Driver.Benchmarks/MultiDoc/BulkWriteMixedOpsBenchmark.cs
> +            {
nit: having
`var collectionName = __collectionNamespaces[i % __collectionNamespaces.Length]`
would result in more compact code.

2025-01-02 23:51 UTC, merged