CSHARP-5375: Remove KnownSerializerRegistry.
mongodb/mongo-csharp-driver pull request #1552
Opened 2024-11-20 22:23 UTC by rstam

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/PartialEvaluator.cs
> +            typeof(Mql),
To keep `Mql.Constant(...)` from being evaluated client-side.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                    var accumulatorSerializer = BsonSerializer.LookupSerializer(accumulatorParameter.Type);
It might make sense to have a factory for numeric return types to protect ourselves from users registering weird serializers for numeric types.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ConstantMethodToAggregationExpressionTranslator.cs
> +                        throw new ExpressionNotSupportedException(expression, because: "the registred serializer is not representation configurable");
Oops, contains a typo... will fix in next commit.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConditionalExpressionToAggregationExpressionTranslator.cs
> +                if (ifTrueExpression is ConstantExpression ifTrueConstantExpression)
If one result is a constant use the serializer of the other expression to serialize the constant.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewDateTimeExpressionToAggregationExpressionTranslator.cs
> +                var serializer = DateTimeSerializer.Instance;
No need to look up anything. We know which serializer we need.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/ExpressionTranslators/ParameterExpressionToFilterTranslator.cs
> +                    var serializer = symbol.Serializer;
No need to look up anything. We know which serializer we need.

2024-11-20 22:32 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> -        public KnownSerializersRegistry KnownSerializersRegistry => _knownSerializersRegistry;
What do you think of making the serializer registry part of the context so we're not tied to using the global registry?

In the short term it's the same thing, but it looks towards the future where we want to specify different registries for different collections.

2024-11-20 22:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4337Tests.cs
> +            (d => new R<E> { N = d.Id, V = d.S1 == E.E1 ? Mql.Constant(E.E1, BsonType.String) : E.E2 }, "{ $project : { N : '$_id', V : { $cond : { if : { $eq : ['$S1', 'E1'] }, then : 'E1', else : '
This is the scenario we were discussing in Slack.

Since the ternary operator has two constants we now default to using the registered serializer, but using `Mql.Constant` the user can override that.

2024-11-23 00:45 UTC, JamesKovacs reviewed
Overall looks great and allows us to remove a difficult-to-reason-about piece of code. One question around the `TranslationContext` and the now unused `serializer` parameter.

2024-11-23 00:45 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> +            return new TranslationContext(symbolTable, nameGenerator, translationOptions, data);
`serializer` is never used. Are we still translating `$setWindowFields` correctly?

2024-11-23 00:45 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> -        public KnownSerializersRegistry KnownSerializersRegistry => _knownSerializersRegistry;
I like this idea. Up to you whether you want to include it in this PR or create a separate one.

2024-11-25 17:21 UTC, sanych-sun requested changes

2024-11-25 17:21 UTC, sanych-sun commented on src/MongoDB.Driver/Mql.cs
> +            throw new NotSupportedException("This method is not functional. It is only usable in MongoDB LINQ queries.");
Haven't we moved this to helper method?

2024-11-25 18:09 UTC, rstam commented on src/MongoDB.Driver/Mql.cs
> +            throw new NotSupportedException("This method is not functional. It is only usable in MongoDB LINQ queries.");
Yes... in a different PR that was not yet pushed to main when this code was written.

I will change this now that that PR has been pushed to main.

2024-11-26 17:47 UTC, rstam reviewed
Addressed all comments.

Probably needs at least one more careful pass before we decide it's ready to merge (for example the TODO comment).

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/GroupingWithOutputExpressionStageDefinitions.cs
> +            var context = TranslationContext.Create(partiallyEvaluatedOutput, translationOptions);
`Create` method no longer has a `serializer` parameter.

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/BinaryExpressionToAggregationExpressionTranslator.cs
> +                _ => BsonSerializer.LookupSerializer(expression.Type) // Required for Coalesce
TODO: look into this a bit more and confirm whether a lookup is justified.

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                    var accumulatorSerializer = seedTranslation.Serializer;
No lookup is needed. We know which serializer to use.

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                        serializer = resultSelectorTranslation.Serializer;
No lookup is needed. We know which serializer to use.

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/AggregateMethodToAggregationExpressionTranslator.cs
> +                        var resultSelectorAccumulatorSymbol = context.CreateSymbol(resultSelectorAccumulatorParameter, accumulatorSerializer);
No lookup is needed. We know which serializer to use.

2024-11-26 17:47 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/AllOrAnyMethodToFilterTranslator.cs
> +                    var actualTypeSerializer = BsonSerializer.LookupSerializer(actualType);
In the future we might add some way to ask a serializer which serializer to use for a derived type.

For now a lookup is the only option available.

2024-11-29 23:16 UTC, sanych-sun approved these changes
LGTM

2024-12-09 21:10 UTC, sanych-sun approved these changes
LGTM + minor suggestion

2024-12-09 21:10 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/StandardSerializers.cs
> +                serializer = NullableSerializer.Create(valueSerializer);
Does it makes sense to use singletons for Nullable<> in the same way as we have for other standard serializers?

2024-12-11 22:19 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/StandardSerializers.cs
> +            var standardTypes = __standardSerializers.Keys.ToArray(); // call ToArray to make a copy of the current Keys
What if we implement local method `RegisterSerializer` instead, like:
```
            void RegisterSerializer(IBsonSerializer serializer)
            {
                __standardSerializers.Add(serializer.ValueType, serializer);

                var nullableSerializer = NullableSerializer.Create(serializer);
                __standardSerializers.Add(nullableSerializer.ValueType, nullableSerializer);

                var arraySerializer = ArraySerializerHelper.CreateSerializer(serializer);
                __standardSerializers.Add(arraySerializer.ValueType, nullableSerializer);

                var arrayOfNullableSerializer = ArraySerializerHelper.CreateSerializer(itemSerializer: nullableSerializer);
                __standardSerializers.Add(arrayOfNullableSerializer.ValueType, arrayOfNullableSerializer);
            }
```
As far as I understood serializer.ValueType - this is the exact type that serializer will process, so we do not have to construct it here, but can relay on what serializer says.
And then simply call it for each serializer, like:
```
            RegisterSerializer(new BooleanSerializer(representation: BsonType.Boolean));
            RegisterSerializer(new ByteSerializer(representation: BsonType.Int32));
            RegisterSerializer(new CharSerializer(representation: BsonType.Int32));
            RegisterSerializer(new DecimalSerializer(representation: BsonType.Decimal128, allowTruncationConverter));
            RegisterSerializer(new DoubleSerializer(representation: BsonType.Double, strictConverter));
            RegisterSerializer(new Int16Serializer(representation: BsonType.Int32, strictConverter));
            RegisterSerializer(new Int32Serializer(representation: BsonType.Int32, strictConverter));
            RegisterSerializer(new Int64Serializer(representation: BsonType.Int64, strictConverter));
            RegisterSerializer(new SByteSerializer(representation: BsonType.Int32));
            RegisterSerializer(new SingleSerializer(representation: BsonType.Double, allowTruncationConverter));
            RegisterSerializer(new UInt16Serializer(representation: BsonType.Int32, strictConverter));
            RegisterSerializer(new UInt32Serializer(representation: BsonType.Int32, strictConverter));
            RegisterSerializer(new UInt64Serializer(representation: BsonType.Int64, strictConverter));
```

2024-12-11 23:23 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/StandardSerializers.cs
> +            var standardTypes = __standardSerializers.Keys.ToArray(); // call ToArray to make a copy of the current Keys
I like it! Done.

Only difference is I named the local method `AddStandardSerializers` instead.

2024-12-12 18:50 UTC, sanych-sun approved these changes
LGTM, but please check the failed tests.

2024-12-19 00:40 UTC, JamesKovacs approved these changes
LGTM

2024-12-19 17:16 UTC, sanych-sun approved these changes
LGTM

2024-12-20 20:57 UTC, merged