CSHARP-3840: Unresponsive/deadlocked cluster.Dispose()
mongodb/mongo-csharp-driver pull request #1557
Opened 2024-11-26 01:18 UTC by sanych-sun

2024-12-16 18:53 UTC, BorisDog requested changes

2024-12-16 18:53 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +                connectTask = Task.Factory.FromAsync(socket.BeginConnect(dnsEndPoint.Host, dnsEndPoint.Port, null, null), socket.EndConnect);
Please check if `ConnectAsync` can replace `BeginConnect` (`SocketTaskExtensions`)

2024-12-16 18:53 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +            IAsyncResult connectOperation;
Please evaluate the option of using `ConnectAsync()....GetResult()` instead.

2024-12-20 00:50 UTC, BorisDog requested changes

2024-12-20 00:50 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +                socket.Dispose();
I think we need to hide `Dispose` exceptions here, and probably in all cases?

2024-12-20 00:50 UTC, BorisDog commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +                socket.Dispose();
Ignore exceptions?

2024-12-20 17:20 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +                socket.Dispose();
Done

2024-12-20 17:20 UTC, sanych-sun commented on src/MongoDB.Driver/Core/Connections/TcpStreamFactory.cs
> +                socket.Dispose();
Done

2024-12-20 17:25 UTC, BorisDog approved these changes
LGTM!

2024-12-20 18:04 UTC, merged