CSHARP-4938: Support for indexing and querying on UUID and null datatype
mongodb/mongo-csharp-driver pull request #1563
Opened 2024-12-03 09:57 UTC by papafe

2024-12-03 19:28 UTC, BorisDog requested changes

2024-12-03 19:28 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// Supported value types are null, boolean, numeric, ObjectId, Guid and date.
Need to add the `Guid` comment also to `In` operator?

2024-12-03 19:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +        private IMongoCollection<TestClass> GetLocalTestCollection() => _mongoClient
Should be removed?

2024-12-03 19:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            [BsonGuidRepresentation(GuidRepresentation.Standard)]
Remove the extra line.

2024-12-03 19:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            new object[] { Guid.Empty, """{ "$binary" : { "base64" : "AAAAAAAAAAAAAAAAAAAAAA==", "subType" : "04" } }""", Exp(p => p.Guid), nameof(Person.Guid) },
'Raw string literals', nice feature! TIL

2024-12-03 20:13 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// Supported value types are null, boolean, numeric, ObjectId, Guid and date.
Definitely

2024-12-03 20:14 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +        private IMongoCollection<TestClass> GetLocalTestCollection() => _mongoClient
This is used by the tests that are skipped at the moment, but hopefully they'll be soon run also on our Atlas Search cluster we use on CI too

2024-12-03 20:15 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            [BsonGuidRepresentation(GuidRepresentation.Standard)]
You mean to have both attributes on one line?

2024-12-03 20:34 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            public string Name { get; set; }
Where is this being used?

2024-12-03 20:34 UTC, adelinowona approved these changes
LGTM except for one comment

2024-12-03 21:00 UTC, BorisDog approved these changes
LGTM! + Last minor comment about to update the In doc.

2024-12-03 21:00 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            [BsonGuidRepresentation(GuidRepresentation.Standard)]
Oh sorry it's all good, on the smaller laptop screen it seemed like there is an extra empty line.

2024-12-04 05:26 UTC, adelinowona commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            where TField : IComparable<TField> =>
Can we remove this IComparable constraint as well? Looking at the code path we don't do any comparing ourselves, we just render the value in the search stage. I actually don't see a benefit for us if we are not doing the comparing. I tried testing removing all the type constraints here, and everything still works and evergreen doesn't report any breaking changes. Thoughts? @BorisDog

2024-12-04 05:37 UTC, adelinowona commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +        public void InGuid()
Also should we consider adding an overload for our current `In` search builder method to support querying against array fields using expressions? That is, `Builders<A>.Search.In(x => x.StringArray, new [] {"a", "b"})`
 It should be a quick overload addition.

2024-12-04 10:08 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            public string Name { get; set; }
In the last test with `null` of `EqualsSupportedTypesTestData`

2024-12-04 10:50 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            where TField : IComparable<TField> =>
I agree that this can be removed safely.

2024-12-04 10:54 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +        public void InGuid()
Makes sense! Probably it would be worth doing it as a separate ticket though

2024-12-04 14:37 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// Supported value types are null, boolean, numeric, ObjectId, Guid and date.
Just did

2024-12-04 18:32 UTC, papafe commented
Just added the test collections on the common cluster. Waiting for the CI to be green and then I'll merge

2024-12-04 21:39 UTC, merged