CSHARP-5423: Remove deprecated field from GridFS unified tests
mongodb/mongo-csharp-driver pull request #1579
Opened 2024-12-19 12:07 UTC by papafe

2024-12-19 12:12 UTC, papafe commented
Not sure if we want to keep them, but for now I've moved the legacy tests inside the "legacy" folder.

2024-12-19 16:06 UTC, rstam requested changes
Please make the commit tree linear before we review.

2024-12-19 16:37 UTC, papafe commented
@rstam Rebased on main

2024-12-19 18:20 UTC, papafe commented
Converted it to draft as I need to finish a couple of things

2024-12-20 11:30 UTC, papafe commented
@BorisDog regarding the deprecated fields, namely "contentType" and "aliases", I've removed them from the registered members of the serializers and also from a test method input given they were not used. 
Apart from that, no need to do more, since all the extra members are just kept into `GridFSFileInfo.BackingDocument` that is a `BsonDocument` and don't cause any issues in case they are encountered. This test verifies that: https://github.com/mongodb/mongo-csharp-driver/blob/476af2b06a102adef9b1ef12c567562069518e79/tests/MongoDB.Driver.Tests/GridFS/GridFSFileInfoTests.cs#L74

2024-12-21 00:02 UTC, BorisDog requested changes
Looks good overall.
There was some confusion with the legacy tests, as I thought the spec contains both `legacy` and `unified` folders.
We need to align with the spec tests structure, and have just unified tests (and remove legacy runners).
So we need to do [CSHARP-3587](https://jira.mongodb.org/browse/CSHARP-3587) as prerequisite. We could also address CSHARP-3587 as part of this ticket.

2024-12-23 09:52 UTC, papafe commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedGridFsDownloadByNameOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
Corrected. I noticed that there are other files with various years, mostly in the test project.

2024-12-23 10:35 UTC, papafe commented
@BorisDog, I've removed the legacy tests and their runners, so I suppose [CSHARP-3587](https://jira.mongodb.org/browse/CSHARP-3587) could also be closed when this is merged

2024-12-23 19:15 UTC, BorisDog approved these changes
LGTM!

2024-12-30 11:30 UTC, merged