CSHARP-5202: BSON Binary Vector Subtype Support
mongodb/mongo-csharp-driver pull request #1581
Opened 2024-12-27 00:28 UTC by BorisDog

2024-12-30 11:29 UTC, papafe reviewed
Overall it makes sense, I just got some notes/questions

2025-01-21 00:22 UTC, sanych-sun requested changes

2025-01-21 00:22 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +            var vectorDataBytes = MemoryMarshal.Cast<T, byte>(vectorData);
I suppose we should ensure we are allowed to do that and throw in case wrong endian-platform.

2025-01-21 00:22 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] WriteBsonVector<T>(BsonVector<T> bsonVector)
_Minor_: The name of the method is a little confusing to me. If it's **WriteXXX** I expect to pass target into the method, like a stream of buffer where I want it to be written to. In this case, I think **FormatXXX** and **ParseXXX** would work better instead of **Write** and **Read**.

2025-01-27 20:01 UTC, BorisDog reviewed
Add support for VectorSearch.
Test cluster setup is WIP.

2025-01-27 20:38 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +                var vectorSerializer = (IBsonSerializer)Activator.CreateInstance(vectorSerializerType, DataType);
But we can create non-generic static class just to have this factory methods. We are doing it in other places. (far example, NullableSerializer)

2025-01-27 20:43 UTC, sanych-sun requested changes

2025-01-27 20:43 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    public abstract class BsonVectorSerializerBase<TItemCollection, TItem> : SerializerBase<TItemCollection>
Should we move each serializer into it's own file?

2025-01-27 20:43 UTC, sanych-sun commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    public sealed class BsonVectorSerializer<TItemCollection, TItem> : BsonVectorSerializerBase<TItemCollection, TItem>
Let's discuss if it's safe to have comparison implemented in base class only.

2025-01-28 22:03 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    public sealed class BsonVectorSerializer<TItemCollection, TItem> : BsonVectorSerializerBase<TItemCollection, TItem>
We don't override `Equals` if no private data was introduced.

2025-01-28 22:03 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    public abstract class BsonVectorSerializerBase<TItemCollection, TItem> : SerializerBase<TItemCollection>
The nested classes are very simple just a few lines long. I find it more readable to keep all in the same file in this case. But we can discuss further.

2025-01-29 18:44 UTC, rstam requested changes
Overall looks good. But I have a lot of naming suggestions and a few refactoring suggestions. Let me know what you think.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonVector.cs
> +    public abstract class BsonVectorBase<T>
I think a better name for this class is `BsonVector` (no `Base` needed in the name).

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonVector.cs
> +        public ReadOnlyMemory<T> Vector { get; }
The spec calls this property `Data`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/VectorDataType.cs
> +    public enum BsonVectorDataType
Rename file to match enum name.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +            var serializer = CreateSerializer(memberMap.MemberType);
Should there be any checks that this attribute is actually valid for this member?

We might be able to give better error messages if we check here instead of letting `CreateSerializer` throw some kind of exception.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal static class BsonVectorSerializerBase
I think this static class should be named just `BsonVectorSerializer` (no `Base` in the name).

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public static BsonVectorSerializer<BsonVectorFloat32, float> BsonVectorSerializerFloat32 { get; } = new BsonVectorSerializer<BsonVectorFloat32, float>(BsonVectorDataType.Float32);
I think this property should be called `BsonVectorFloat32Serializer`.

An `XyzSerializer` is a serializer for `Xyz`, and here `Xyz` is `BsonVectorFloat32`.

Same for the next two properties.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            throw new InvalidOperationException($"Type {type} is not supported for a binary vector.");
We should throw `NotSupportedException` instead.

Same for other places in this PR.

`InvalidOperationException` should rarely be thrown. It means the operation is temporarily invalid due to the current state of the object, but if the state changed the operation might become valid at some future time.

An example would be calling `ReadBytes` on a socket that is closed. That's an invalid operation. But if you call `Connect` the operation would then become valid.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            Type GetItemType(Type actualType)
Maybe rename `actualType` to `baseType` or `abstractBaseType`?

It's *not* the actual type...

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +                var arguments = actualType.GetGenericArguments();
Maybe rename `arguments` to `genericArguments` or `typeArguments`?

To avoid confusion with method arguments.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            var bsonType = reader.GetCurrentBsonType();
Can lines 123-129 be moved to a common method in the base class and be shared?

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            return binaryData.ToBsonVector<TItem>() as TItemCollection;
Change to:

```(TItemCollection)binaryData.ToBsonVector<TItem>()```

I don't think `as` should ever be used without checking whether it returns null.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal abstract class BsonVectorToCollectionSerializer<TItemCollection, TItem> : BsonVectorSerializerBase<TItemCollection, TItem>
Maybe rename class to `CollectionWithBsonVectorRepresentationSerializer`.

It's a `CollectionSerializer`, but with the caveat that it is `WithBsonVectorRepresentation`.

Also thinking about good names for making some of these serializer public to allow in code configuration.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +                padding = bsonVectorPackedBit.Padding;
Rider says this line is unreachable.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected abstract ReadOnlySpan<TItem> GetSpan(TItemCollection data);
Maybe be a little more explicit in the name `GetItemsSpan`?

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal sealed class BsonVectorArraySerializer<TItem> : BsonVectorToCollectionSerializer<TItem[], TItem>
Rename class to `ArrayWithBsonVectorRepresentationSerializer`

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal sealed class BsonVectorMemorySerializer<TItem> : BsonVectorToCollectionSerializer<Memory<TItem>, TItem>
Rename class to `MemoryWithBsonVectorRepresentationSerializer`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal sealed class BsonVectorReadOnlyMemorySerializer<TItem> : BsonVectorToCollectionSerializer<ReadOnlyMemory<TItem>, TItem>
Consider naming this class `ReadOnlyMemoryWithBsonVectorRepresentationSerializer`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonBinaryDataExtensions.cs
> +        public static BsonVectorBase<T> ToBsonVector<T>(this BsonBinaryData binaryData)
Making these extension methods of `BsonBinaryData` is potentially a bit too broad since they apply to only one kind of `BsonBinaryData`. This might make them too easy to call when it's inappropriate.

Consider making these static factor methods of the `BsonVector` static class.

For example, this method could be called `CreateBsonVector`.

Similarly for the other methods below.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorExtensions.cs
> +        public static BsonBinaryData ToBsonBinaryData<T>(this BsonVectorBase<T> bsonVector)
Not sure why this is an extension method and not a method of the `BsonVector` class.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static BsonVectorBase<T> BsonVectorFromVectorData<T>(ReadOnlyMemory<byte> vectorData)
Consider naming this method `ReadBsonVector`.

Seems like a "reader" should have methods starting with "Read".

Similar for the methods below.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (T[] Elements, byte Padding, BsonVectorDataType vectorDataType) BsonVectorFromVectorDataAsArray<T>(ReadOnlyMemory<byte> vectorData)
Could be called `ReadBsonVectorElements`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (ReadOnlyMemory<byte> VectorDataBytes, byte Padding, BsonVectorDataType VectorDataType) ReadBsonVectorAsBytes(ReadOnlyMemory<byte> vectorData)
Is `As` redundant in the name? Could be `ReadBsonVectorBytes` or `ReadBsonVectorData`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            var paddingSizeBits = vectorDataSpan[1];
This variable could be named just `padding`.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        private static BsonVectorBase<T> CreateBsonVector<T>(T[] elements, byte padding, BsonVectorDataType vectorDataType)
Should this be a static factory method in the `BsonVector<T>` class?

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] BsonVectorToBytes<T>(BsonVectorBase<T> bsonVector)
Consider naming this method `WriteBytes` or `WriteToBytes`.

The "from" is implied by the parameter types.

2025-01-29 18:44 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] VectorDataToBytes<T>(ReadOnlySpan<T> vectorData, BsonVectorDataType bsonVectorDataType, byte padding)
Consider naming `WriteToBytes`.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonBinaryDataExtensions.cs
> +        public static BsonVectorBase<T> ToBsonVector<T>(this BsonBinaryData binaryData)
While I think your point is valid,  I still see in such ease of access more of an advantage.
`BsonBinaryData` should not be used very often directly. And it's intended for more sophisticated usage. 
I think we should be standardizing on using extensions over factory methods for such augmentations.
For example `BsonBinaryData.ToGuid` should eventually move here. (btw it has the same issue of being too specific).

Also we could nest such extensions under additional namespaces if needed in the future.

cc @sanych-sun

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorExtensions.cs
> +        public static BsonBinaryData ToBsonBinaryData<T>(this BsonVectorBase<T> bsonVector)
Similar to `BsonBinaryDataExtensions`, the idea is to decouple `BsonVector `and `BsonBinaryData`.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            var paddingSizeBits = vectorDataSpan[1];
Done.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        private static BsonVectorBase<T> CreateBsonVector<T>(T[] elements, byte padding, BsonVectorDataType vectorDataType)
I don't think so: I didn't see a need for a such a factory outside this class. Also I think BsonVector itself should be just a data holder, decoupled from its factories.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static BsonVectorBase<T> BsonVectorFromVectorData<T>(ReadOnlyMemory<byte> vectorData)
Done.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (T[] Elements, byte Padding, BsonVectorDataType vectorDataType) BsonVectorFromVectorDataAsArray<T>(ReadOnlyMemory<byte> vectorData)
Done.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (ReadOnlyMemory<byte> VectorDataBytes, byte Padding, BsonVectorDataType VectorDataType) ReadBsonVectorAsBytes(ReadOnlyMemory<byte> vectorData)
Done.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] VectorDataToBytes<T>(ReadOnlySpan<T> vectorData, BsonVectorDataType bsonVectorDataType, byte padding)
Done.

2025-01-30 00:31 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] BsonVectorToBytes<T>(BsonVectorBase<T> bsonVector)
Done.

2025-01-30 01:17 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/VectorDataType.cs
> +    public enum BsonVectorDataType
They aren't sequential, but they are also not flags. They just happen to be non-sequential values. I have no idea why they picked the values they did.

2025-01-30 01:18 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    public abstract class BsonVectorSerializerBase<TItemCollection, TItem> : SerializerBase<TItemCollection>
I think we have often bundled very tightly related classes together in a single file. I'm fine with this.

2025-01-30 22:01 UTC, rstam requested changes
Sorry I have so many requested naming changes. 

But specially where things are entering the public API it is important to get the names right because we can't change them later.

2025-01-31 01:06 UTC, BorisDog reviewed
Thanks for the thorough review. I think it's much more polished now.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal abstract class BsonVectorSerializerBase<TItemCollection, TItem> : SerializerBase<TItemCollection>
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for BSON vector to/from a given collection.
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed void Serialize(BsonSerializationContext context, BsonSerializationArgs args, TItemCollection bsonVector)
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public BsonVectorToCollectionSerializer(BsonVectorDataType bsonVectorDataType) :
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed TItemCollection Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] WriteToBytes<T>(BsonVectorBase<T> bsonVector)
Done.

2025-01-31 01:06 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorWriter.cs
> +        public static byte[] WriteToBytes<T>(ReadOnlySpan<T> vectorData, BsonVectorDataType bsonVectorDataType, byte padding)
Done.

2025-01-31 01:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
> Or maybe it's a BsonVector, just represented by byte[] :)

Yes but... serializers have NO control over how things are represented in memory. That is totally defined by the C# data type that this is a serializer for (in this case `byte[]`). In the context of configuring serialization "representation" ALWAYS means how things are represented IN THE DATABASE.

In this case the in memory representation is `byte[]` and the database representation is `BsonVector`. The only thing that can be configured is the database representation.

I think the disconnect here is that I am looking at this from the perspective of "configuring the representation of the C# value in the database" and you are coming from the opposite direction. But as I said, in the case of serializer configuration it is always the database representation that is being configured.

Since I'm thinking about this in terms of "configuring serialization" which in turn means "configuring the database representation" that is why to me `[BsonVector(...)]` by itself makes no sense.

2025-01-31 01:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
> Regarding:
```
[BsonVectorRepresentation(BsonVectorDataType.Int8)] 
[BsonArrayRepresentation(BsonType.Binary)] 
public byte[] A { get; set; }
```
the problem of a user applying contradictory attributes to the same member is not one we have solved.

Also, `BsonArrayRepresentation` doesn't exist but I guess you are using it as a hypothetical.

2025-01-31 01:50 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I'm going to think about this some more...

What I want is a name that clearly implies "A is represented in the database as a BsonVector".

And not one that reads like "A *is* a BsonVector", because it is not.

2025-01-31 20:18 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I guess the word "representation" is relevant to most of our bson attributes and config options. So it becomes redundant at some point.  For example `BsonTimeSpanOptions` can be thought as `BsonTimeSpanRepresentation`, as it does configure how the BsonTime is represented.

I don't think having `BsonVectorRepresentation` is entirely wrong, just not very accurate. We are configuring the **bson** representation of the clr type, so the ideal name probably would be BsonRepresentation(vectorSubtype, vectorType, ...), and we are not configuring just the **vector** representation of the clr type.

I think BsonVector option is just more concise and easier to use.  Especially given that bson vector is a new special type with a very specific use cases.

2025-01-31 23:16 UTC, rstam requested changes

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed TItemContainer Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
`sealed` is redundant when the class is sealed.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed void Serialize(BsonSerializationContext context, BsonSerializationArgs args, TItemContainer value)
`sealed` is redundant when the class is sealed.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            var (elements, padding, _) = binaryData.ToBsonVectorAsArray<TItem>();
Rename `elements` to `items` for consistency.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +                throw new FormatException($"Padding is supported only in {nameof(BsonVectorPackedBit)} data type.");
throw new FormatException($"Non-zero padding is supported only in {nameof(BsonVectorPackedBit)} data type.");

Optional re-wording because only *non-zero* padding is not supported.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected abstract TItemContainer CreateResult(TItem[] elements);
Rename `elements` to `items`.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for BSON vector to/from array of <typeparamref name="TItem"/>.
/// Represents a serializer for <typeparamref name="TItem"/> arrays represented as a BsonVector.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected abstract ReadOnlySpan<TItem> GetItemsContainerSpan(TItemContainer data);
Is `Conntainer` in the name here correct?

Consider `GetItemsSpan`.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for BSON vector to/from <see cref="Memory{TItem}"/>
/// Represents a serializer for <see cref="Memory{TItem}"/> represented as a BsonVector.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected override TItem[] CreateResult(TItem[] elements) =>
private protected override TItem[] CreateResult(TItem[] items) => items;

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected override Memory<TItem> CreateResult(TItem[] elements) =>
private protected override Memory<TItem> CreateResult(TItem[] items) =>
            new(items);

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for <see cref="ReadOnlyMemory{TItem}"/>.
/// Represents a serializer for <see cref="ReadOnlyMemory{TItem}"/> represented as a BsonVector.

2025-01-31 23:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            new(elements);
private protected override ReadOnlyMemory<TItem> CreateResult(TItem[] items) =>
            new(items);

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (ReadOnlyMemory<byte> VectorDataBytes, byte Padding, BsonVectorDataType VectorDataType) ReadBsonVectorAsBytes(ReadOnlyMemory<byte> vectorData)
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +                throw new InvalidOperationException($"Invalid {nameof(vectorData)} size {vectorData.Length}");
Right, done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +                throw new InvalidOperationException($"Invalid padding size {padding}");
Changed to `FormatException`.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +                    {
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +                    throw new InvalidOperationException($"Type {typeof(TItem)} is not supported with {vectorDataType} vector type.");
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            TActualItem[] AsTypedArrayOrThrow<TActualItem>()
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static void ValidateDataType<TItem>(BsonVectorDataType bsonVectorDataType)
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            var supportedType = bsonVectorDataType switch
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            if (supportedType != typeof(TItem))
If think we should be standardizing on lhs for variables and rhs for constants. 
For this matter `typeof(TItem)` can be viewed as a constant.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            throw new NotSupportedException($"Type {type} is not supported for a binary vector.");
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            Type GetItemType(Type collectionType)
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +                    throw new NotSupportedException($"Type {type} is not supported for a binary vector.");
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private static IBsonSerializer CreateSerializerInstance(Type vectorSerializerType, BsonVectorDataType bsonVectorDataType) =>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// <typeparam name="TItemContainer">The concrete type derived from <see cref="BsonVectorBase{TItemContainer}"/>.</typeparam>
Thanks done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        /// Initializes a new instance of the <see cref="ReadonlyMemorySerializer{TItem}" /> class.
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed TItemContainer Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
Good point. Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        public override sealed void Serialize(BsonSerializationContext context, BsonSerializationArgs args, TItemContainer value)
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            var (elements, padding, _) = binaryData.ToBsonVectorAsArray<TItem>();
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +                throw new FormatException($"Padding is supported only in {nameof(BsonVectorPackedBit)} data type.");
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected abstract TItemContainer CreateResult(TItem[] elements);
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected abstract ReadOnlySpan<TItem> GetItemsContainerSpan(TItemContainer data);
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected override TItem[] CreateResult(TItem[] elements) =>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for BSON vector to/from <see cref="Memory{TItem}"/>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +        private protected override Memory<TItem> CreateResult(TItem[] elements) =>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for <see cref="ReadOnlyMemory{TItem}"/>.
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +            new(elements);
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Driver/BsonVectorExtensions.cs
> +    /// Contains extensions methods for <see cref="BsonVectorBase{T}"/>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Driver/BsonVectorExtensions.cs
> +        /// Converts <see cref="BsonVectorBase{T}"/> to <see cref="BsonBinaryData"/>.
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Driver/BsonVectorExtensions.cs
> +        public static QueryVector ToQueryVector<T>(this BsonVectorBase<T> bsonVector)
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Driver/QueryVector.cs
> +        /// Possible values are <see cref="BsonArray"/> or <see cref="BsonBinaryData"/> encoding <see cref="BsonVectorBase{T}"/>
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +        /// Gets the vector data type representation.
Done.

2025-02-01 00:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    /// Represents a serializer for BSON vector to/from array of <typeparamref name="TItem"/>.
Done.

2025-02-01 04:12 UTC, rstam requested changes
A few typos remain.

2025-02-01 04:12 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonBinaryDataExtensions.cs
> +        public static (TItem[] Items, byte Padding, BsonVectorDataType vectorDataType) ToBsonVectorAsArray<TItem>(this BsonBinaryData binaryData)
Shouldn't `vectorDataType` start with an upper case `V`?

2025-02-01 04:12 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +        public static (ReadOnlyMemory<byte> Byte, byte Padding, BsonVectorDataType VectorDataType) ReadBsonVectorAsBytes(ReadOnlyMemory<byte> vectorData)
Shouldn't `Byte` be `Bytes``? (plural)

2025-02-01 04:12 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +                        return new BsonVectorFloat32(AsTypedArrayOrThrow<float>()) as BsonVectorBase<TItem>;
Fix indentation in these three cases.

2025-02-01 04:12 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            if (expectedItemType != typeof(TItem))
if (typeof(TItem) != expectedItemType)

This makes more sense if it reads more like English: "if the item type is not equal to the expected item type"

2025-02-01 04:12 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            if (supportedType != typeof(TItem))
I agree in with variables on the left and constants on the right.

But two things are different here:

1. typeof(TItem) is not a constant, it's an expression involving the type variable `TItem`
2. we also like to standardize on `if (actualXyz != expectedXyz)`

Technically `typeof(TItem)` will become a constant at runtime but ONLY after the generic method is Jitted for a particular `TItem`. But for us as programmers `TItem` is a type variable.

2025-02-01 04:19 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I have a further proposal.

Instead of:

            [BsonVector(BsonVectorDataType.Int8)]
            public byte[] ValuesByte { get; set; }

we could do this:

            [SerializedAsInt8Vector]
            public byte[] ValuesByte { get; set; }

This is shorter, simpler, and includes the important semantic information that exactly what is happening here is that we are configuring the property to be "serialized as an Int8 vector".

Simlarly for `[SerializedAsPackedBitVector]` or `[SerializedAsFloat32Vector]`

2025-02-03 16:26 UTC, rstam requested changes
Added new comments related to changes required to allow users to configure serialization in code rather than using attributes.

2025-02-03 16:26 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal abstract class BsonVectorSerializerBase<TItemContainer, TItem> : SerializerBase<TItemContainer>
This class and all of its subclasses need to be `public` so that users can configure class maps in code.

Some users don't want to (or *can't*) put attributes on their model classes and either prefer or are forced to configure their serialization separately in code.

2025-02-03 16:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
After making the serializers for values represented as vectors public the same configuration can be achieved in code as follows:

            var cm = new BsonClassMap<ArrayHolder>();
            cm.AutoMap();

            cm.MapMember(x => x.ValuesByte).SetSerializer(new ArrayAsBsonVectorSerializer<byte>(BsonVectorDataType.Int8));
            cm.MapMember(x => x.ValuesPackedBit).SetSerializer(new ArrayAsBsonVectorSerializer<byte>(BsonVectorDataType.PackedBit));
            cm.MapMember(x => x.ValuesFloat).SetSerializer(new ArrayAsBsonVectorSerializer<float>(BsonVectorDataType.Float32));

2025-02-03 16:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
But... we can make the user's life easier by defining the following three subclasses:

        public class ByteArrayAsInt8VectorSerializer() : ArrayAsBsonVectorSerializer<byte>(BsonVectorDataType.Int8);
        public class ByteArrayAsPackedBitVectorSerializer() : ArrayAsBsonVectorSerializer<byte>(BsonVectorDataType.PackedBit);
        public class SingleArrayAsFloat32VectorSerializer() : ArrayAsBsonVectorSerializer<byte>(BsonVectorDataType.Float32);

which allow the user to configure the serializers without using the more complicated constructor call requiring a generic type parameter and a vector data type:

            cm.MapMember(x => x.ValuesByte).SetSerializer(new ByteArrayAsInt8VectorSerializer());
            cm.MapMember(x => x.ValuesPackedBit).SetSerializer(new ByteArrayAsPackedBitVectorSerializer());
            cm.MapMember(x => x.ValuesFloat).SetSerializer(new SingleArrayAsFloat32VectorSerializer());

Besides being more compact, it is less error prone (less likely to use invalid generic type parameters or mis-matched vector data types).

2025-02-03 16:26 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
Similarly for the `Memory` and `ReadOnlyMemory` serializers.

2025-02-03 19:14 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
I think it's potentially a good suggestion.
But I'd like to consider it later, hopefully after collecting some user feedback.

BTW we already have some future potential additions to BSON Vector functionality, like BigEndian, other primitive types which are not part of this PR.

2025-02-03 19:14 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
IMO in this case, adding words like "SerializedAs" or "Representation" is just redundant.
Having multiple attributes for denoting Bson Vector would be even more confusing.

So I still think the most convenient and concise approach for our users would be having `BsonVector`. Simple, short, easy to explain.

2025-02-03 19:14 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    /// Sets the representation for this field or property as a BSON Vector with the specified data type.
I think it's done.

2025-02-03 22:03 UTC, rstam requested changes

2025-02-03 22:03 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonVector.cs
> +    public abstract class BsonVectorBase<TItem>
This class should really be called `BsonVector`.

I realize there is a pseudo-conflict with `[BsonVector]` attribute and that's why you chose this unappealing name.

If we can't rename the attribute, then let's just live with the pseudo-conflict. It's not really a conflict because the attribute class name is actually `BsonVectorAttribute`.

2025-02-03 22:03 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal sealed class ReadOnlyMemoryAsBsonVectorSerializer<TItem> : ItemContainerAsBsonVectorSerializer<ReadOnlyMemory<TItem>, TItem>
You probably meant for this one to be public too.

2025-02-03 22:08 UTC, rstam requested changes

2025-02-03 22:08 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I am resolving this comment out of frustration...

2025-02-03 22:08 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonVectorReader.cs
> +            if (expectedItemType != typeof(TItem))
I disagree but since it's not a bug you can write it the way that doesn't read like English.

2025-02-03 22:08 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
I may have misinterreted "I'd like to consider it later".

I thought you meant make the serializers public later. But looks like you did make them public.

2025-02-03 22:44 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonVectorSerializer.cs
> +    internal sealed class ReadOnlyMemoryAsBsonVectorSerializer<TItem> : ItemContainerAsBsonVectorSerializer<ReadOnlyMemory<TItem>, TItem>
Yes. Done.

2025-02-03 22:44 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Attributes/BsonVectorAttributeTests.cs
> +        }
Yes, I just meant considering the shortcuts later. 
Maybe achieving the same by making `static BsonVectorSerializer` public and extending it.

2025-02-03 23:28 UTC, rstam approved these changes
LGTM with reluctance due to the names `BsonVectorBase` and `BsonValueAttribute`.

The implementation is solid though. It's only the names which give me pause.

2025-02-04 21:11 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
Discussed offline. 
`BsonSerializerAttribute` could also work, but it will require awkward configuration of the additional parameter (and adding support of serializer paremeters).
Also it is not as straight forward as `BsonVector`.

2025-02-04 23:34 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I don't think you are consistent in your arguments. You keep saying that:

```
[BsonVector(BsonVectorDataType.Int8)]
public byte[] A;
```

is SHORT and STRAIGHTFORWARD and yet you reject even more compact and straightforward suggestions like:

```
[AsInt8Vector]
public byte[] A;
```

2025-02-05 00:53 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I think I am :) 
IMO having multiple attributes instead of a single simple `BsonVector` is **less** straightforward. Try imaging the user experience of having just a single entry point of `BsonVector`, where the rest of the params are self explanatory,  versus the need of traversing our docs each time to find the right attribute for the right type.

Also I don't think the `AsSomething` naming pattern for attributes is ideal for us. This also collides with the potential idea of having `BsonDoubleAttribute` and similar in the future.

2025-02-05 00:57 UTC, sanych-sun approved these changes
LGTM

2025-02-05 01:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
The flip side of your `BsonDoubleAttribute` argument is that we should be able to use `BsonVector` instead of `BsonVectorBase` as the type name for the BSON vector class.

If you plan on having `BsonDouble` and `[BsonDouble]` coexist there is no reason that `BsonVector` and `[BsonVector]` can't coexist.

2025-02-05 01:34 UTC, rstam commented on src/MongoDB.Bson/Serialization/Attributes/BsonVectorAttribute.cs
> +    public sealed class BsonVectorAttribute : Attribute, IBsonMemberMapAttribute
I think the `AsSomething` pattern is a good one and one we should have adopted from the very beginning. If we are looking to change how our attributes are defined in the future this would be a good direction to move in.

```
[AsDouble]
public int X;
```

is very simple and straightforward. It reads very well: X is an int that is represented *AS* a double in the database.

2025-02-05 10:07 UTC, papafe approved these changes
A small note, but otherwise LGTM

2025-02-05 10:07 UTC, papafe commented on src/MongoDB.Bson/Serialization/BsonVectorExtensions.cs
> +        /// <typeparam name="TItem"></typeparam>
TItem is missing

2025-02-05 10:07 UTC, papafe approved these changes
A small note, but otherwise LGTM

2025-02-05 21:36 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonVectorExtensions.cs
> +        /// <typeparam name="TItem"></typeparam>
Thanks. Done.

2025-02-05 22:41 UTC, rstam reviewed
Looks like all the renaming from `BsonVector` to `BinaryVector` was done consistently.

To me the last remaining question is whether the `<Type>Attribute` naming pattern is viable.

I've started a thread in #csharp-driver-devs to discuss as a team before committing to this public API.

2025-02-08 02:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                    {
The braces for this case are redundant.

2025-02-08 02:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +            IEnumerable<Type> expectedItemTypes = binaryVectorDataType switch
I thought `Type[]` would make more sense, but when I tried it I got a compilation error below on `string.Join`, which I imagine is why you went with `IEnumerable<Type>`.

If you prefer to use `Type[]` the compilation error can be resolved by calling `string.Join<Type>` instead of `string.Join`.

2025-02-08 02:29 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                throw new NotSupportedException($"Item type {typeof(TItem)} is not supported with {binaryVectorDataType} vector type, expected item type to be {string.Join(",", expectedItemTypes)}.")
Consider using `" or "` as the separator for a more readable message?

2025-02-08 03:47 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                    {
Done.

2025-02-08 03:47 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +            IEnumerable<Type> expectedItemTypes = binaryVectorDataType switch
`string.Join<Type>` not available on net472.

2025-02-08 03:47 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                throw new NotSupportedException($"Item type {typeof(TItem)} is not supported with {binaryVectorDataType} vector type, expected item type to be {string.Join(",", expectedItemTypes)}.")
I'm not sure, potentially this list will grow in the future. What does look better to your:
int, unit, short, ushort... or 
int or unit or short or ushort?

2025-02-08 23:31 UTC, rstam requested changes

2025-02-08 23:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +            IEnumerable<Type> expectedItemTypes = binaryVectorDataType switch
OK. Weird of Microsoft to introduce an overload susceptible to ambiguity.

2025-02-08 23:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                throw new NotSupportedException($"Item type {typeof(TItem)} is not supported with {binaryVectorDataType} vector type, expected item type to be {string.Join(",", expectedItemTypes)}.")
True, my suggestion only works with 1 or 2 types. But that's all we have so far.

The motivation was to avoid this awkward construction:

```... expected time type to be Byte, SByte.```

2025-02-10 21:43 UTC, rstam requested changes
One minor change requested.

And also the following discussion on Slack is still open:

https://mongodb.slack.com/archives/GQ27C9N7J/p1738795018585749

2025-02-10 21:43 UTC, rstam commented on src/MongoDB.Bson/Serialization/BinaryVectorReader.cs
> +                    if ((vectorDataBytes.Span.Length & 3) != 0)
I think the more common way to check for not a multiple of `n` (`4` in this case) is:

    if ((vectorDataBytes.Span.Length % 4) != 0)

Works for all values of `n` not just multiples of `2`.

2025-02-10 23:02 UTC, rstam approved these changes
I consider this a good implementation except for the choice of the `[BsonVector]` attribute name which it looks like I am unable to convince Boris of, and other team members have been silent about.

2025-02-10 23:38 UTC, merged