CSHARP-5442: Atlas Search doesn't respect the correct serializer
mongodb/mongo-csharp-driver pull request #1583
Opened 2024-12-31 14:56 UTC by papafe

[Jira ticket](https://jira.mongodb.org/browse/CSHARP-5442)

2024-12-31 15:45 UTC, papafe commented
@BorisDog I've added you as a reviewer since it seems you were the one that worked on search, mostly. 
A couple of notes:
- Probably we need to change the `in` and `range` search definitions as well to use the correct serializers.
- This is effectively a behaviour breaking change, so we need to decide if we want include it in next version or wait for next major

2025-01-02 11:20 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                var serializer =
Incredibly ugly, but was just testing if it worked

2025-01-02 16:41 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                var serializer =
@rstam this is what I was referring to. 
Do you think it would be worth adding a new property to `RenderArgs` so that we can get directly the serializer we need?

2025-01-03 20:47 UTC, rstam requested changes

2025-01-03 20:47 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly TField _value;
Rename `TField` to `TValue` because that is what it is.

2025-01-03 20:47 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            ValidateType();
I question whether we need to have `ValidateType` at all. Looks to me like this was just a client-side limitation related to what .NET types `ToBsonValue` knew how to convert to BSON, but now that we are using the proper serializer this limitation should no longer exist.

2025-01-03 20:47 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                var serializer =
I think this is on the right track but can use a little tweaking to how the right serializer is found and to reduce duplication between how scalar and array fields are handled.

Something like this:

    private protected override BsonDocument RenderArguments(RenderArgs<TDocument> args)
    {
        IBsonSerializer<TValue> valueSerializer;
        if (_field != null)
        {
            var renderedField = _field.Render(args);
            valueSerializer = renderedField.FieldSerializer;
        }
        else
        {
            var renderedArrayField = _arrayField.Render(args);
            valueSerializer = (IBsonSerializer<TValue>)ArraySerializerHelper.GetItemSerializer(renderedArrayField.FieldSerializer);
        }                                                                                                                          
                                                                                                                                   
        var document = new BsonDocument();                                                                                         
        using var bsonWriter = new BsonDocumentWriter(document);                                                                   
        var context = BsonSerializationContext.CreateRoot(bsonWriter);                                                             
        bsonWriter.WriteStartDocument();                                                                                           
        bsonWriter.WriteName("value");                                                                                             
        valueSerializer.Serialize(context, _value);                                                                                
        bsonWriter.WriteEndDocument();                                                                                             
                                                                                                                                   
        return document;                                                                                                           
    }

2025-01-03 20:47 UTC, rstam commented on src/MongoDB.Driver/FieldValueSerializerHelper.cs
> +
Instead of adding this new public property have the class implement `IBsonArraySerializer` and implement the `TryGetItemSerializationIinfo` method:

    public bool TryGetItemSerializationInfo(out BsonSerializationInfo serialization
    {
        serializationInfo = new(elementName: null, _itemSerializer, typeof(TItem));
        return true;                                                               
    }                                                                              

All serializers for array-like values should implement `IBsonArraySerializer`. I don't know why this class did not already implement it.

2025-01-03 20:47 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                    (renderedField.ValueSerializer as FieldValueSerializerHelper.IEnumerableSerializer<TField>)
Instead of trying to cast to the very specific class `FieldValueSerializerHelper.IEnumerableSerializer<TField>` use the more general from (used everywhere else) to get the item serializer from an array-like serializer:

    valueSerializer = (IBsonSerializer<TValue>)ArraySerializerHelper.GetItemSerializer(renderedArrayField.FieldSerializer);

This is why `FieldValueSerializerHelper.IEnumerableSerializer<TItem>` should implement `IBsonArraySerializer` (as all array-like serializers should). Not sure why it didn't already...

2025-01-03 22:23 UTC, rstam requested changes

2025-01-03 22:23 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            ValidateType();
I checked with Boris and he confirmed that it is a server limitation which types are supported.

But even so, we probably shouldn't be checking this client side. We should just send the value to the server and let it return an error if it doesn't support the data type.

That way our driver will work well with all supported versions of the server, which might have different limitations. And if future server versions support new value types we won't have to make any changes.

2025-01-06 08:46 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            ValidateType();
I also like this idea. I tried to keep it consistent with what was there before, but I agree that moving this check server side would allow us to be more free in what we do and don't support over time

2025-01-06 09:06 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                var serializer =
Perfect, this solves my doubts. That makes sense, I was mostly focusing on how to get the correct serializer before trying to refactor. 
Regarding `IBsonArraySerializer`, it seems that the majority of times when we implement that interface we also implement `IChildSerializerConfigurable`, and that makes sense. It also seems that for this use case the result we'd get would be the same, so what do you think about using `IChildSerializerConfigurable` instead? 
To be honest this is more of a generic question, I'm curious about if there's any preference of one over the other, of course considering that `TryGetItemSerializationInfo` can potentially return more info (not in this case though).

2025-01-06 09:29 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            //For the Guid we get (correctly): GuidSerializer cannot serialize a Guid when GuidRepresentation is Unspecified.
@rstam This test here is now failing because now we're using the default serializer and that doesn't have the `GuidRepresentation` specified. 
Do you have any suggestion on how to fix this? The exception makes sense, and normally we'd probably suggest statically registering a serializer, but this would impact all the other tests here. 
Should we ignore the `Guid` field for this test and make a separable test here that can only be run manually?

2025-01-06 16:32 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +                var serializer =
`IBsonArraySerializer` and `IChildSerializerConfigurable` are orthogonal. We can't just implement `IChildSerializerConfigurable` *instead* of `IBsonArraySerializer`.

In this case we *must* implement `IBsonArraySerializer`. 

It is true that in general whenever implementing `IBsonArraySerializer` we would likely also want to implement `IChildSerializerConfigurable`. However, that applies mostly to `public` serializers that a user might want to configure. This is an `internal` serializer, so I think implementing `IBsonArraySerializer` is sufficient.

2025-01-06 17:14 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            //For the Guid we get (correctly): GuidSerializer cannot serialize a Guid when GuidRepresentation is Unspecified.
Yeah, I would have loved to avoid making special cases, but it seems we need to. I'll make some additional tests that can be run manually.

2025-01-06 19:02 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            //For the Guid we get (correctly): GuidSerializer cannot serialize a Guid when GuidRepresentation is Unspecified.
I'm fine with just skipping this test for Guids, because:

1. This test is against `IMongoCollection<BsonDocument>` and that is probably not used often
2. Anyone using `BsonDocument` should either not be using `Guid` or should take control of the conversion themselves

A manual test would involve registering a properly configured global `GuidSerializer`, but we already know that works (in part because the strongly typed version uses a properly configured `GuidSerializer`, though it's true it doesn't get it from the global registry).

2025-01-07 10:40 UTC, papafe commented on src/MongoDB.Driver/FieldValueSerializerHelper.cs
> +        //TODO Never used
Should we remove this?

2025-01-07 10:46 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly TField _value;
`TField` is the type of the field, that is also the type of the value, right? 
Also if we do it here we'd need to make this change also in the other operators, and probably should propagate it as well.

2025-01-07 10:48 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> -             new object[] { new object[] { (byte)1, (short)2, (int)3 }, new[] { "1", "2", "3" } }
Do we want to support this? This does not work anymore because before we were using the serializer depending on the type of the value, while now we're trying to look at the serializer appropriate for the field.

2025-01-07 10:49 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +            Search,  //TODO This is never used, should we remove them?
Should we/can we remove those?

2025-01-07 10:50 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            FieldDefinition<TDocument, TField> path,  //TODO We should try to uniform this to the In operator for next major (this should be SearchPathDefinition<TDocument>)
I can create a ticket for this if we want to go this way

2025-01-07 17:30 UTC, rstam requested changes

2025-01-07 17:30 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly TField _value;
`TField` and `TValue` are only the same when the field is not an array.

In the case of an array `TField` is `IEnumerable<TValue>`.

2025-01-07 17:30 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private readonly TField _value;
Did you remove the code you had earlier for `_arrayField`?

2025-01-07 17:30 UTC, rstam commented on src/MongoDB.Driver/FieldValueSerializerHelper.cs
> +            public bool TryGetItemSerializationInfo(out BsonSerializationInfo serializationInfo)
Keep methods in alphabetical order?

2025-01-07 17:30 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var serializer = renderedField.FieldSerializer switch
Maybe rename `serializer` to `valueSerializer`.

To remove confusion about whether it is the field serializer or the value serializer (which are not the same in the case of array fields).

2025-01-07 17:30 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
>          public EqualsSearchDefinition(FieldDefinition<TDocument> path, TField value, SearchScoreDefinition<TDocument> score)
It is unfortunate that `path` is of type `FieldDefinition<TDocument>` instead of `FieldDefinition<TDocument, TField>`.

This is not type safe because it allows mismatches between the field type and the value type that are not caught at compile time.

In an earlier commit you had changed this but now it's removed. Can you explain why?

2025-01-07 18:33 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
>          public EqualsSearchDefinition(FieldDefinition<TDocument> path, TField value, SearchScoreDefinition<TDocument> score)
I tried to uniform the code between the `Equals`, `In` and `Range` search definition classes. 
Unfortunately for `In` and `Range` we can't have the same constructor with `FieldDefinition<TDocument, Field>` because of the current public API of the operators in `SearchDefinitionBuilder`. 
I agree that this is not type safe, but at least `EqualsSearchDefinition` is an internal class, and the operators in `SearchDefinitionBuilder` that use it have type safety (either through expressions or field definitions).

If this was a major version, I'd suggest to modify `SingleSearchPathDefinition` (the subclass of `SearchPathDefinition` for single fields) from using one generic parameter `TDocument` to two `TDocument, TField`, so we could be on the safer side. 
Probably it would be worth actually removing `SearchPathDefinition<TDocument>` as an input parameter of the operators, and create multiple overrides for the various subclasses of `SearchPathDefinition`, so that we can use as many generic parameters as necessary. 

I think this is something that would be worth doing for next major in order to improve the API, but I don't think we can do much at the moment without making breaking changes.

2025-01-08 09:32 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        [Fact]
According to the mongo docs `In` should support wildcard paths, but we had no tests for that.

2025-01-10 19:32 UTC, rstam approved these changes
I'm not too familiar with the Search API but as far as I can tell this looks OK.

You should get one more LGTM before merging to main though.

2025-01-14 10:30 UTC, papafe commented
> I'm not too familiar with the Search API but as far as I can tell this looks OK.
> 
> You should get one more LGTM before merging to main though.

@sanych-sun can you take a look too?

2025-01-17 19:11 UTC, sanych-sun commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +            Search,  //TODO This is never used, should we remove them?
Cannot find any reference to this or anything on Documentation. @BorisDog  can we remove this?

2025-01-28 19:52 UTC, papafe commented
@BorisDog another thing to consider is that this is a behaviour breaking change, so we need to consider if we want to merge this now or wait. I think it could also be seen as a bug fix to be honest, but we should take a decision. 
The difference is that now the correct registered serializers are used to serialize the values for the `equals`, `in` and `range` operators, while before default conversions were used, ignoring the registered serializers.

2025-02-04 21:07 UTC, BorisDog requested changes

2025-02-04 21:07 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
It's a bit inefficient that we need to render the path twice.
Also it would be good to extract this to a single helper method.

What do you and @rstam  think about having new internal `Render` method in `SearchPathDefinition`, something like

`(BsonValue, RenderedFieldDefinition) Render(...)`

And passing field serializer in `OperatorSearchDefinition.RenderArguments() `?

2025-02-05 10:35 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
I am a little confused, where are we rendering the path again apart from here?

2025-02-05 12:30 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
I see your point. I also think it's a little complicated to extract a method like that to `SearchPathDefinition`, since `(BsonValue, RenderedFieldDefinition) Render(...)` would make sense for a `SingleSearchPathDefinition`, but not for `MultiSearchPathDefinition` or `WildCardSearchPathDefinition`.

2025-02-05 18:26 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
Yeah I meant that the returned `RenderedFieldDefinition` would be null in some cases. I agree that it's not the greatest design, but I don't have any better suggestion as of now. I does have the upside of not rendering the path twice.
As long as all the API changes are internal, we can evolve them in the future if we come up with a better idea (the new suggested Render method should be interna).

2025-02-06 16:54 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
In [60c1d57](https://github.com/mongodb/mongo-csharp-driver/pull/1583/commits/60c1d57c437759784c0df48a6888e8a8650261a6), I've added a fix to avoid rendering the path twice. It's not super nice, and I'm not sure it's worth it given that probably the network call of the atlas search would be much greater than the time needed to render the path twice.

2025-02-06 17:28 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var searchPathDefinition = (SingleSearchPathDefinition<TDocument>)_path;
I think that if we want to have special cases depending on the path we could also specialize `OperatorSearchDefinition.RenderArguments` and produce a different method for each path type, for example `OperatorSearchDefinition.RenderArgumentsForSingleSearchPath` where we can pass additional arguments. This would require quite some changes, but could also allow to control which kind of path can be used with certain kinds of operators.

2025-02-06 20:26 UTC, papafe commented
@BorisDog I've done some corrections following your suggestions, and it looks much better than before, thank you 😄 
I'm a little bit unsure about the names though, they feel a little redundant

2025-02-07 03:35 UTC, BorisDog requested changes

2025-02-07 03:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            //There is no property called "x" where to pick up a properly configured GuidSerializer for the tests
I'm not sure I fully understand this exclusion. Is the default guid serializer different from the one used by serialization?

2025-02-07 03:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            new object[] { DateTimeOffset.MaxValue, """{ "DateTime" : { "$date" : "9999-12-31T23:59:59.999Z" }, "Ticks" : 3155378975999999999, "Offset" : 0 }""", Exp(p => p.DateTimeOffset), nameof(Pe
So does this mean that we are changing the defaults also for non typed queries (`SearchDefinitionBuilder<BsonDocument>`)?

If so, that might be considered a bug and a breaking change.

2025-02-07 06:23 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            //There is no property called "x" where to pick up a properly configured GuidSerializer for the tests
I think I need to improve the comment, I agree it's not super clear. 
The issue here is that when we use a string path, we're going to get the default serializer for the value, so `GuidSerializer`. In v3.0 we decided to have `GuidRepresentation.Unspecified` as the default Guid representation, and this will throw an exception when trying to serialize/deserialize. Normally a user would go over this by registering a default `GuidSerializer` with the proper representation (`BsonSerializer.Register...(GuidSerializer)`), but we can't do it because the registered serializers are global and this would be a problem for all the other tests.

For the typed path on line 305 it's not an issue since we get the default field serializer from the class, and the `Guid` property has the `BsonGuidRepresentation` attribute on it. 

This is more of a testing issue and should be solved when we can pass down the serialization domain 😁

2025-02-07 06:26 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            new object[] { DateTimeOffset.MaxValue, """{ "DateTime" : { "$date" : "9999-12-31T23:59:59.999Z" }, "Ticks" : 3155378975999999999, "Offset" : 0 }""", Exp(p => p.DateTimeOffset), nameof(Pe
Yes it will change also for non typed queries. They would need to convert the `DateTime` themselves if they want to keep the same behaviour.

2025-02-07 06:27 UTC, papafe commented on src/MongoDB.Driver/Search/SearchPathDefinition.cs
> +        internal (string renderedPath, IBsonSerializer fieldSerializer) RenderFieldWithSerializer(FieldDefinition<TDocument> fieldDefinition, RenderArgs<TDocument> args)
Yes, I think it makes sense

2025-02-07 07:02 UTC, papafe commented
@BorisDog, as an additional note. I've tried making an untyped query (using `BsonDocument`) and passing a `DateTime` value for the `Equal` operator. No error returned but zero results as expected.

2025-02-07 13:04 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +            new object[] { DateTimeOffset.MaxValue, """{ "DateTime" : { "$date" : "9999-12-31T23:59:59.999Z" }, "Ticks" : 3155378975999999999, "Offset" : 0 }""", Exp(p => p.DateTimeOffset), nameof(Pe
It's probably a breaking change, but I'm not sure this can be considered a bug. If you're working directly with Bson documents then I assume that you would like to control how to the values are serialized in any case.

2025-02-10 22:55 UTC, rstam requested changes

2025-02-11 09:04 UTC, papafe commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            var valueSerializer = fieldSerializer switch
It's actually a little different between the various operators, so I'd prefer to keep it here

2025-02-11 10:44 UTC, papafe commented
@rstam @BorisDog I've followed Robert's suggestions about the code style.
I've also come up with an extension method to enable the new behaviour, so this won't be a breaking change. It's all in the last commit, so it can be reverted if necessary

2025-02-26 01:20 UTC, sanych-sun commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        public static SearchDefinition<TDocument> WithDefaultSerialization<TDocument>(this SearchDefinition<TDocument> searchDefinition, bool useDefaultSerialization)
The method name is a little confusing: why I as a user should ask driver to do something that is sounds as default. May be it should be named like `WithConfiguredSerializer` or something like that?

2025-02-27 14:50 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        public static SearchDefinition<TDocument> WithDefaultSerialization<TDocument>(this SearchDefinition<TDocument> searchDefinition, bool useDefaultSerialization)
Yeah, the naming is confusing to be honest! I had some difficulty coming up with a reasonable name, but your suggestion makes sense.

2025-02-27 19:29 UTC, rstam requested changes

2025-02-27 19:29 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
I'm not convinced this is a good idea.

Might as well call this `_useTheWrongSerializer`.

2025-02-27 20:17 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
You're not convinced about the naming or the actual API/solution?

2025-02-27 23:42 UTC, rstam requested changes

2025-02-27 23:42 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
I'm not convinced this `bool` should even exist.

I somewhat tongue in cheek suggested a name that illustrates why this makes no sense to me.

We have a bug: we are using the wrong serializer.

We are fixing the bug: we now use the correct serializer.

But somehow we think a user would like to use the wrong serializer???

2025-02-28 09:35 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
I understand your point, but I suppose that some developers could already use this feature as is, and this would be considered a breaking change (even though it was not correct).  The idea here would be to support this behaviour until next major and then get rid of it. 
@BorisDog am I right?

2025-02-28 16:05 UTC, rstam requested changes

2025-02-28 16:05 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
While this sounds like a valid concern, I can't figure out any scenario in which it would actually be valid.

In essence we are replacing are "hand rolled" serializer (the `ToBsonValue` method) with using the correct serializer.

There are only two scenarios:

1. ToBsonValue and the configured serializer return the same serialized values
2. Or they return different values

In the first case there is no problem.

In the second case the value returned by `ToBsonValue` is wrong and I don't see how the query could have worked, and therefore why we would keep the existing behavior.

Can you point me to a test that passes when `_useConfiguredSerialization` is `false` and fails when it is `true`?

2025-03-03 09:09 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
My concern is with pipelines using `BsonDocument` (unfortunately this happens more often than we'd like).
For example `DateTimeOffset` is serialized by default as document, while users with `BsonDocument` pipelines might be relying on it to be serialized as `BsonDate`.

I think in case we should introduce the "correct" behavior in the next major version.

2025-03-04 16:51 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
@papafe can you point me to a test that passes when `_useConfiguredSerialization` is `false` and fails when it is `true`?

I want to confirm that this is not just a hypothetical concern, and if real, whether there isn't a better way to address than turning off the fix entirely by default.

2025-03-04 17:00 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
@rstam sorry for the late reply. 
If you look at the tests `Equals_should_render_supported_type` (it's already in main) and `Equals_with_configured_serializer_should_render_supported_type`, they are essentially the same test but with different test data (`EqualsSupportedTypesTestData` and `EqualsWithConfiguredSerializerSupportedTypesTestData`). The only difference between the two sets of data is the line with `DateTimeOffset`, and that's because in the current implementation that is serialized as a `BsonDate` while the default `DateTimeOffsetSerializer` uses a document representation.

2025-03-19 10:37 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        protected bool _useConfiguredSerialization = false;
@rstam did you have the change to look at this?

2025-04-09 18:55 UTC, rstam requested changes

2025-04-09 18:55 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private protected override BsonDocument RenderArguments(
Refactor this method to emphasize that the only difference `_useConfiguredSerializers` makes is how the values are serialized:

    private protected override BsonDocument RenderArguments(
        RenderArgs<TDocument> args,
        IBsonSerializer fieldSerializer)
    {
        BsonValue serializedValues;
        if (_useConfiguredSerializers)
        {
            var arraySerializer = fieldSerializer switch
            {
                null => new ArraySerializer<TField>(args.SerializerRegistry.GetSerializer<TField>()),
                IBsonArraySerializer => fieldSerializer,                                             
                _ => new ArraySerializer<TField>((IBsonSerializer<TField>)fieldSerializer)           
            };                                                                                       
                                                                                                     
            serializedValues = SerializationHelper.SerializeValue(arraySerializer, _values);         
        }                                                                                            
        else                                                                                         
        {                                                                                            
            serializedValues = new BsonArray(_values.Select(ToBsonValue));                           
        }                                                                                            
                                                                                                     
        return new BsonDocument("value", serializedValues);                                          
    }

2025-04-09 18:55 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +    internal sealed class RangeSearchDefinition<TDocument, TValue> : OperatorSearchDefinition<TDocument>
As mentioned above keep `TField`.

2025-04-09 18:55 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +        private protected override BsonDocument RenderArguments(
Refactor this method to emphasize that the only difference `_useConfiguredSerializers` makes is how the min and max values are serialized:

    private protected override BsonDocument RenderArguments(
        RenderArgs<TDocument> args,
        IBsonSerializer fieldSerializer)
    {
        BsonValue serializedMin;
        BsonValue serializedMax;
        if (_useConfiguredSerializers)
        {
            var valueSerializer = fieldSerializer switch
            {
                null => args.SerializerRegistry.GetSerializer<TField>(),
                IBsonArraySerializer => ArraySerializerHelper.GetItemSerializer(fieldSerializer),
                _ => fieldSerializer
            };
              
            serializedMin = _range.Min == null ? null : SerializationHelper.SerializeValue(valueSerializer, _range.Min.Value);
            serializedMax = _range.Max == null ? null : SerializationHelper.SerializeValue(valueSerializer, _range.Max.Value);
        }                                                                                                                     
        else                                                                                                                  
        {                                                                                                                     
            serializedMin = _range.Min == null ? null : ToBsonValue(_range.Min.Value);                                        
            serializedMax = _range.Max == null ? null : ToBsonValue(_range.Max.Value);                                        
        }                                                                                                                     
                                                                                                                              
        var minInclusive = _range.Min?.Inclusive ?? false;                                                                    
        var maxInclusive = _range.Max?.Inclusive ?? false;                                                                    
                                                                                                                              
        return new()                                                                                                          
        {                                                                                                                     
            { minInclusive ? "gte" : "gt", serializedMin, serializedMin != null },                                            
            { maxInclusive ? "lte" : "lt", serializedMax, serializedMax != null }                                             
        };                                                                                                                    
    }

2025-04-09 18:55 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +    /// Extensions for SearchDefinition
/// Extension methods for SearchDefinition.

2025-04-10 07:48 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        internal void SetUseConfiguredSerialization(bool useDefaultSerialization)
I've renamed it to `useConfiguredSerializers` as in the other places. I had to change the name of the method to `SetUseConfiguredSerializersInternal` though, otherwise it would cause confusion (internally) between this and the extension method.

2025-04-10 08:24 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        public static SearchDefinition<TDocument> WithConfiguredSerialization<TDocument>(this SearchDefinition<TDocument> searchDefinition, bool useDefaultSerialization)
I see your point with `With` and I changed it to `Set`, even though I'm not super convinced by this. I think that in general `With` at least gives the impression of having an object (freshly created or not) returned, while `Set` feel more like a setter method that just changes state and returns void. I don't have strong opinions on either ways though.

2025-04-10 17:00 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        public void InWithConfiguredSerialization_typed<T>(
Find remaining places where "configuredserialization" or "configured serialization" is used...

2025-04-10 17:27 UTC, sanych-sun commented
Please add appropriate label to the PR.

2025-04-10 17:32 UTC, papafe commented on src/MongoDB.Driver/Search/SearchDefinition.cs
> +        public static SearchDefinition<TDocument> SetUseConfiguredSerializers<TDocument>(this SearchDefinition<TDocument> searchDefinition, bool useConfiguredSerializers)
Sounds good!

2025-04-10 17:37 UTC, papafe commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +        public void InWithConfiguredSerialization_typed<T>(
It slipped through the cracks, it was the last one 🤦

2025-04-10 23:54 UTC, rstam approved these changes
LGTM

2025-04-22 11:23 UTC, papafe commented
@rstam @BorisDog I've inverted the boolean controlling the behaviour, so now by default the registered serializers will be used. 
I kept the same name for the method controlling this behaviour, as it seems it made the most sense.

2025-04-22 22:35 UTC, BorisDog approved these changes
LGTM!

2025-04-25 19:33 UTC, rstam approved these changes
LGTM

2025-04-30 13:06 UTC, papafe commented
> We should reword the title of the PR, so it would sounds like a feature. For release notes.

@sanych-sun Your comment made me realize that maybe the bug tag is more appropriate for this PR in the current state. We are actually correcting the behaviour of something that is already there AND also adding the possibility of having the previous behaviour. If this had to go in the release notes under only one section, I think it should be "bug".

2025-04-30 13:07 UTC, merged