CSHARP-4882: Support Skip and Take in expressions.
mongodb/mongo-csharp-driver pull request #1584
Opened 2024-12-31 22:51 UTC by rstam

2024-12-31 22:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstExpression.cs
> +
@sanych-sun let's discuss the pros and cons of doing these simplifications here vs in the AstSimplifier.

2024-12-31 22:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/PartialEvaluator.cs
> +                    method.Is(QueryableMethod.AsQueryable))
We can't let the `PartialEvaluator` evaluate nested `AsQueryable`.

@damieng here's an example of the headaches that nested `AsQueryable` causes.

2024-12-31 22:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SkipOrTakeMethodToAggregationExpressionTranslator.cs
> -                if (sourceExpression is MethodCallExpression sourceSkipExpression && sourceSkipExpression.Method.IsOneOf(__skipMethods))
All simplifications (this was just one) have been moved to `AstSimplifier`.

2024-12-31 22:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4882Tests.cs
> +        [InlineData(4, "{ $project : { _v : { $slice : [[1, 2, 3, 4], { $max : ['$One', 0] }, 2147483647] }, _id : 0 } }", true)]
Testing nested `AsQueryable` doubles the number of tests.

@damieng here's another example of the headaches that nested AsQueryable causes.

2024-12-31 22:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4882Tests.cs
> +                    collection.AsQueryable().Select(x => new[] { 1, 2, 3, 4 }.Skip(x.One).ToArray()),
Testing nested `AsQueryable` doubles the number of scenarios.

@damieng here's another example of the headaches that nested `AsQueryable` causes.

2024-12-31 22:58 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3Implementation/Jira/CSharp4882Tests.cs
> +        [InlineData(8, "{ $project : { _v : { $slice : [{ $slice : [[1, 2, 3, 4], { $max : ['$One', 0] }, 2147483647] }, { $max : ['$Two', 0] }, 2147483647] }, _id : 0 } }", true)]
I stopped modifying test methods to test nested `AsQueryable`  with this one.

I'm wondering whether there is a better way to handle testing nested `AsQueryable`?

2025-01-02 23:16 UTC, sanych-sun requested changes

2025-01-02 23:16 UTC, sanych-sun commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SkipOrTakeMethodToAggregationExpressionTranslator.cs
> +        private static MethodInfo[] __skipOrTakeMethodsWithCount =
Is this the same array as `__skipOrTakeMethods`? Why do we need both?

2025-01-06 19:09 UTC, sanych-sun approved these changes
LGTM

2025-01-06 19:40 UTC, closed without merging