BsonSerializer pointless micro optimization
mongodb/mongo-csharp-driver pull request #283
Opened 2017-06-21 14:10 UTC by dnickless

Again just some algorithmic optimization to make things faster. Mind you, this will have a really tiny effect only... I just avoided some checks that weren't required in the LookupActualType method and cached one reflection call.

2020-12-29 23:12 UTC, BorisDog requested changes

2020-12-29 23:12 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                    if (actualType == null)
Seems that the semantics of raising an exception when actualType == null and discriminator.IsString == false is lost here.

2021-01-06 01:55 UTC, dnickless commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                    if (actualType == null)
Very correct observation... I reverted this bit as it wasn't helping a lot anyway so now, the changes are very digestible.

2021-01-06 17:28 UTC, BorisDog approved these changes

2021-01-06 18:38 UTC, DmitryLukyanov approved these changes
nit: this value https://github.com/mongodb/mongo-csharp-driver/pull/283/files#diff-ac6526d3ae431d24b51f464a5746bca97fbf64612afeeb0da6079f6b4d9de2c5R520 can be used in line 542. Also, it would be good to quickly check this file on similar changes. Other than this, LGTM

2021-01-06 18:52 UTC, BorisDog commented
Thanks @dnickless, 
In addition @DmitryLukyanov comment, same change can be applied to lines [401](https://github.com/mongodb/mongo-csharp-driver/blob/5672935b662a10d85cc4eb24e7b7a3e34803bc98/src/MongoDB.Bson/Serialization/BsonSerializer.cs#L401) -[363](https://github.com/mongodb/mongo-csharp-driver/blob/5672935b662a10d85cc4eb24e7b7a3e34803bc98/src/MongoDB.Bson/Serialization/BsonSerializer.cs#L363)

2021-01-11 19:24 UTC, DmitryLukyanov approved these changes
LGTM, thanks @dnickless

2021-01-13 17:02 UTC, BorisDog commented
Jira ticket: CSHARP-3324

2021-01-13 17:42 UTC, rstam requested changes

2021-01-13 17:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/Conventions/AttributeConventionPack.cs
> +                TypeInfo classTypeInfo = classMap.ClassType.GetTypeInfo();
nit: use var

2021-01-13 17:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                    }
This is a bug.

This prevents us from detecting ambiguous discriminators above.

2021-01-13 17:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                if (discriminator.IsString)
Removing the check for `actualType == null` would be a bug depending on what we do with the above comment.

2021-01-13 17:42 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                        while (true)
Interesting change.

Perhaps `while (parentType != null)` would be a more appropriate change?

2021-01-13 17:52 UTC, rstam requested changes

2021-01-13 17:52 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializer.cs
> +                    }
Correction: I misinterpreted the nesting level of this early return and thought it was exiting the foreach loop early.

Sorry.

2021-01-14 18:08 UTC, BorisDog commented
Thanks @dnickless! Merged [here](https://github.com/mongodb/mongo-csharp-driver/commit/d74848d44e045e95b4f46e48bd05ef13b49b3001)

2021-01-14 18:08 UTC, closed without merging