Fixing method summaries to be coherent
mongodb/mongo-csharp-driver pull request #290
Opened 2017-09-01 22:16 UTC by alexandrevribeiro

Fixing the summary of both "GetSerializer" methods to be coherent with what they actually do. 
They not only gets a registered serializer, but they also ADDs it when it wasn't registered before (behavior I disagree BTW). And it took me a while to find out this was the problem I was facing.

2020-12-03 18:28 UTC, BorisDog approved these changes

2020-12-03 18:38 UTC, JamesKovacs approved these changes
LGTM

2020-12-03 19:48 UTC, rstam requested changes

2020-12-03 19:48 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +        /// Gets the serializer (explicitly registered or default) for the specified <paramref name="type" />.
This change is misleading. There is no such thing as a "default" serializer.

What actually happens is that if no serializer is already registered the serialization providers are used to get one and it is automatically registered.

I would suggest a better change would be:

    /// Gets the serializer for the specified <paramref name="type" />. If none is already registered, the serialization providers will be used to create a serializer and it will be automatically registered.

2020-12-03 19:48 UTC, rstam commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +        /// Gets the serializer (explicitly registered or default) for the specified <typeparamref name="T" />.
See previous comment.

2020-12-03 20:12 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/BsonSerializerRegistry.cs
> +        /// Gets the serializer (explicitly registered or default) for the specified <paramref name="type" />.
Thanks, done.

2020-12-03 21:00 UTC, JamesKovacs approved these changes
LGTM

2020-12-05 01:38 UTC, rstam approved these changes
LGTM

2020-12-08 23:33 UTC, BorisDog commented
[Pushed](https://github.com/mongodb/mongo-csharp-driver/commit/7945ed58c4ddae5f26ef7fb3b6ebff7f69d1490c)

2020-12-08 23:33 UTC, closed without merging