Documentation improvements for Skunkworks
mongodb/mongo-csharp-driver pull request #301
Opened 2017-11-01 14:20 UTC by dgolub

This pull request fills in most of the missing examples in the C# driver documentation and also fixes a batch of typos that I spotted.

2020-12-03 18:10 UTC, BorisDog approved these changes

2020-12-03 18:31 UTC, JamesKovacs commented on Docs/reference/content/reference/driver/expressions.md
> +{{% note %}}`ToLowerInvariant`, `ToUpper`, `ToUpperInvariant`, `Trim`, `TrimStart`, and `TrimEnd` are also supported for the first function call. `StartsWith` and `EndsWith` are also supported for th
👍

2020-12-03 18:37 UTC, JamesKovacs requested changes
Overall looks good, but we are losing examples/heading for `$sum` and `$type`. We should include examples of those operators.

2020-12-03 18:37 UTC, JamesKovacs commented on Docs/reference/content/reference/driver/crud/linq.md
> -
Why are we removing `$sum`? We should use a better example than summing ages (which makes little to no sense), but we should be removing the operator example entirely.

2020-12-03 18:37 UTC, JamesKovacs commented on Docs/reference/content/reference/driver/expressions.md
> -// no example yet
The `$type` example is being removed. We should include it and provide an example.

2020-12-03 19:37 UTC, BorisDog commented on Docs/reference/content/reference/driver/crud/linq.md
> -
It's a duplicate, removing one of the instances :)

2020-12-03 20:40 UTC, BorisDog commented on Docs/reference/content/reference/driver/expressions.md
> -// no example yet
Thanks for catching this. Added an example

2020-12-03 20:57 UTC, JamesKovacs approved these changes
LGTM

2020-12-05 01:59 UTC, rstam requested changes
My only potential change request is where I comment that we might be documenting things we don't want to document here.

2020-12-05 01:59 UTC, rstam commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^(?!.{0,-1}John).{0}John/s }
This one is surprising to say the least!

2020-12-05 01:59 UTC, rstam commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^.{0}a/s }
Another surprising one...

2020-12-05 01:59 UTC, rstam commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^john$/i }
While it's true that this is what we are currently returning is it correct?

What about locales or collations?

2020-12-05 01:59 UTC, rstam commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^john$/i }
If we're not sure this is correct should we be documenting it?

Same question for several other surprising results...

2020-12-07 18:36 UTC, rstam requested changes
Putting back in request changes status because there are unanswered comments.

2020-12-07 19:00 UTC, BorisDog commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^(?!.{0,-1}John).{0}John/s }
Removed

2020-12-07 19:00 UTC, BorisDog commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^.{0}a/s }
Works as expected

2020-12-07 20:45 UTC, BorisDog commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^john$/i }
This example of `'ToLower'` would work as expected regardless of collations.

2020-12-08 05:53 UTC, rstam approved these changes
LGTM

2020-12-08 05:53 UTC, rstam commented on Docs/reference/content/reference/driver/expressions.md
> +{ Name: /^john$/i }
I'm not sure that's a true statement, but it will  work with most values (at least with the standard collation).

It should work with the value `john` if that's what you mean.

2020-12-08 23:46 UTC, BorisDog commented
[Pushed](https://github.com/BorisDog/mongo-csharp-driver/commit/9e538e2cd6e2ea5f1e1ecf1358ebfe7e963d596a)

2020-12-08 23:46 UTC, closed without merging