CSHARP-2683: Lower GC pressure by reducing allocation during deserialization
mongodb/mongo-csharp-driver pull request #375
Opened 2019-08-12 19:47 UTC by dnickless

This small PR addresses https://jira.mongodb.org/browse/CSHARP-2683. It avoids recreating literally millions of almost identical instances inside a loop which proved to waste endless memory in my profiling session (see JIRA: ~28 million instances created adding up to ~900MB of heap space).

2020-12-08 00:03 UTC, DmitryLukyanov requested changes

2020-12-08 00:03 UTC, DmitryLukyanov commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                trieDecoder.Reset();
Consider adding a comment on why this change is required since it can be unclear after some time

2020-12-08 17:34 UTC, dnickless commented on src/MongoDB.Bson/IO/TrieNameDecoder.cs
> +using System.Diagnostics;
done

2020-12-08 17:35 UTC, dnickless commented on src/MongoDB.Bson/IO/TrieNameDecoder.cs
> +        public void Reset()
No longer needed - I think I found a way nicer solution.

2020-12-08 17:35 UTC, dnickless commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                trieDecoder.Reset();
No longer needed - I think I found a way nicer solution.

2020-12-08 17:35 UTC, dnickless commented on src/MongoDB.Bson/IO/TrieNameDecoder.cs
> +        /// Resets this instance to its default state
No longer needed - I think I found a way nicer solution.

2020-12-09 01:44 UTC, rstam approved these changes
LGTM

I like the new commit better than the original one!

Thanks.

2020-12-09 14:14 UTC, DmitryLukyanov commented
Thanks @dnickless . I think we can also mention this logic in tests here https://github.com/mongodb/mongo-csharp-driver/blob/master/tests/MongoDB.Bson.Tests/IO/TrieNameDecoderTests.cs#L23 . Then it will be LGTM

2020-12-14 22:04 UTC, BorisDog reviewed
[EG](https://evergreen.mongodb.com/version/5fd7d9cc61837d457895bd26)

2020-12-14 22:09 UTC, DmitryLukyanov approved these changes
LGTM, thanks @dnickless!

2020-12-15 00:17 UTC, BorisDog commented
[Squashed and merged](https://github.com/mongodb/mongo-csharp-driver/commit/0f3bff509e48af146989fd256c52c5bccf6637d9)

2020-12-15 00:17 UTC, closed without merging

2020-12-15 00:18 UTC, dnickless commented on src/MongoDB.Bson/IO/TrieNameDecoder.cs
> +using System.Diagnostics;
This code no longer exists in the latest version so that should be ok.