CSHARP-3239: Unescape AWS session token when parsing from connection string.
mongodb/mongo-csharp-driver pull request #418
Opened 2020-11-16 22:39 UTC by JamesKovacs

`authMechanismProperties` in the connection string have to be URL escaped, but we did not unescape them when parsing the connection string. Notably this led to `AWS_SESSION_TOKEN` containing `%2F` rather than `/` as expected.

2020-11-19 06:29 UTC, rstam requested changes
Possible minor changes requested. Will LGTM as is if you object to the changes.

2020-11-19 06:29 UTC, rstam commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            const string pwd = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYzEXAMPLEKEY";
avoid abbreviations, consider `password` as the variable name

2020-11-19 06:29 UTC, rstam commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            const string authMech = "MONGODB-AWS";
avoid abbreviations (possible exception of `auth` due to extensive use already).

Consider `authMechanism` as the variable name.

2020-11-19 20:27 UTC, rstam requested changes
I missed the use of `string.Empty` in the first review.

2020-11-19 20:27 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                        credential = credential.WithMechanismProperty(property.Key, Uri.UnescapeDataString(property.Value ?? string.Empty));
We use `""` instead of `string.Empty`

I realize some people prefer `string.Empty` but there are lots of reasons not to use it. Most are a consequence of the difference between a read-only property (which `string.Empty` is) and a compile time constant (which `""` is).

2020-11-19 20:27 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                        credential = credential.WithMechanismProperty(property.Key, Uri.UnescapeDataString(property.Value ?? string.Empty));
Another statement I would make: `""` is always valid but `string.Empty` is sometimes not.

2020-11-19 22:02 UTC, JamesKovacs commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                        credential = credential.WithMechanismProperty(property.Key, Uri.UnescapeDataString(property.Value ?? string.Empty));
No strong opinion on this. I used `string.Empty` because that was what I've used previously. Fixed.

2020-11-20 17:18 UTC, rstam requested changes

2020-11-20 17:18 UTC, rstam commented on src/MongoDB.Driver/MongoClientSettings.cs
> +                        credential = credential.WithMechanismProperty(property.Key, Uri.UnescapeDataString(property.Value ?? ""));
Thinking more about this...

I think the call to `Uri.UnescapeDataString` should be in `ConnectionString.cs` when parsing the URI.

2020-11-24 02:22 UTC, rstam requested changes
These are the principles we should follow for consistent URI escaping/unescaping:

* values are only escaped when they are on a connection string
* values should *not* be escaped when they are in memory
* values need to be re-escaped when building a new connection string
* options from txtRecords should not be prematurely unescaped

github PRs don't let me comment on lines that haven't changed, so instead please refer to my branch for the full set of suggested changes:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3239-1123

2020-11-24 02:22 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                    .Select(value => $"{key}={value}")));
It's OK to rename the variables, but we still need to call `Uri.EscapeDataString`

2020-11-24 02:22 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            // Add them after escaping the resolvedOptions from the TXT record to avoid double-escaping.
These lines should not be added.

2020-11-24 18:32 UTC, MikalaiMazurenka approved these changes
The solutions looks fine to me, with just a few minor comments which are not essential.

2020-11-24 18:32 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        }
Since currently specifying unescaped token works, I suggest to add a test case for that (same for `MongoClientSettingsTests`):
```
[Theory]
[ParameterAttributeData]
public void Resolve_against_mongodb_aws_session_token_should_return_the_expected_aws_session_token(
	[Values(false, true)] bool escapeToken)
{
	const string authMechanism = "MONGODB-AWS";
	const string username = "AKIAIOSFODNN7EXAMPLE";
	const string password = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYzEXAMPLEKEY";
	const string awsSessionToken = "AQoEXAMPLEH4aoAH0gNCAPyJxz4BlCFFxWNE1OPTgk5TthT+FvwqnKwRcOIfrRh3c/LTo6UDdyJwOOvEVPvLXCrrrUtdnniCEXAMPLE/IvU1dYUg2RVAJBanLiHb4IgRmpRV3zrkuWJOgQs8IZZaIv2BXIa2R4OlgkBN9bkUDNCJiBeb/AXlzBBko7b15fjrBs2+cTQtpZ3CYWFXG8C5zqx37wnOE49mRl/+OtkIKGO7fAE";

	var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
	var uri = $"mongodb+srv://{username}:{Uri.EscapeDataString(password)}@test5.test.build.10gen.cc/test?authSource=$external&authMechanism={authMechanism}&authMechanismProperties=AWS_SESSION_TOKEN:{preparedToken}";
	var connectionString = new ConnectionString(uri);

	var result = connectionString.Resolve();

	result.AuthMechanism.Should().Be(authMechanism);
	result.Username.Should().Be(username);
	result.AuthMechanismProperties["AWS_SESSION_TOKEN"].Should().Be(awsSessionToken);
}
```

2020-11-24 18:32 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            // Add them after escaping the resolvedOptions from the TXT record to avoid double-escaping.
I'd suggest to remove the comments as they are too verbose.

2020-11-25 19:42 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        }
Done.

2020-11-25 19:50 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            // Add them after escaping the resolvedOptions from the TXT record to avoid double-escaping.
Changed the logic to always use unescaped options internally. So this comment is no longer necessary.

2020-11-30 17:36 UTC, rstam requested changes

2020-11-30 17:36 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                dummyConnectionString += "?" + string.Join("", txtRecord.Strings);
Don't the multiple `txtRecord.Strings` need to be separated by `&` characters?

We probably don't have any tests failing because in our tests there is only one `txtRecord.Strings`.

2020-11-30 17:36 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        [InlineData("mongodb+srv://test5.test.build.10gen.cc",
Hard to tell what actually changed when arbitrary formatting changes are introduced at the same time...

2020-11-30 17:36 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        [InlineData("mongodb+srv://test5.test.build.10gen.cc",
Hmmm.... looks like NOTHING changed?

Am I missing something?

2020-11-30 17:36 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
I don't understand the purpose of not always escaping.

Shouldn't the `awsSessionToken` be invalid if it is not escaped? It will only be valid IFF it happens to not contain any special characters than need to be escaped.

2020-11-30 17:36 UTC, rstam commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
Same question as above.

2020-11-30 20:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                dummyConnectionString += "?" + string.Join("", txtRecord.Strings);
We are concatenating together `txtRecord.Strings`, not TXT records themselves. We have  a guard clause (lines 1297-1300) on the method asserting that there can be at most 1 TXT record. According to [our SRV spec](https://github.com/mongodb/specifications/blob/master/source/initial-dns-seedlist-discovery/initial-dns-seedlist-discovery.rst), there can be only a single TXT record, but it can contain multiple strings which are to be concatenated together without a separator.

2020-11-30 20:07 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        [InlineData("mongodb+srv://test5.test.build.10gen.cc",
This was Rider trying to be "helpful" in wrapping long lines. I thought I'd reverted all its changes. Guess I missed one. Reverted.

2020-11-30 20:16 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
According to RFC3986 (URI syntax), the query component is delimited by the first `?` and ends with the first `#`. The query component can contain additional `?` characters as well as `/` characters. So the `awsSessionToken` may be escaped or it may not be. I think it worthwhile to test both cases. Typically what made the `awsSessionToken` invalid was the erroneous double-escaping of `/` characters in the token.

2020-11-30 20:16 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
See response above.

2020-11-30 20:32 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
> I don't understand the purpose of not always escaping.

I've requested to add this case because it previously worked. So my intention was to preserve backward compatibility.

2020-12-01 14:53 UTC, rstam approved these changes
LGTM

2020-12-01 14:53 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                dummyConnectionString += "?" + string.Join("", txtRecord.Strings);
Got it. I was confused by the fact that his line was concatenating (sligtly preprocessed) TXT records *before*, but *now* it's concatenating the strings in one TXT record.

Looks correct now that I understand that change.

2020-12-01 14:53 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            var preparedToken = escapeToken ? Uri.EscapeDataString(awsSessionToken) : awsSessionToken;
OK... but **not** escaping **only** works because the particular test value used doesn't contain any special characters that need to be escaped.

2020-12-01 19:36 UTC, JamesKovacs commented
Squashed and merged with `master`.

2020-12-01 23:29 UTC, JamesKovacs commented
Re-opening to fix PR merge.

2020-12-01 23:31 UTC, closed without merging