CSHARP-3271
mongodb/mongo-csharp-driver pull request #425
Opened 2020-12-02 17:45 UTC by BorisDog

- Various docs cleanups
- Minor styling change
- Addressed [209](https://github.com/mongodb/mongo-csharp-driver/pull/290) and [301](https://github.com/mongodb/mongo-csharp-driver/pull/301) PRs

Updated docs can be viewed here: https://borisdog.github.io/mongo-csharp-driver/2.12/reference/

2020-12-02 21:15 UTC, JamesKovacs requested changes
A few minor fixes. One thing I don't like is that this PR is a grab bag of documentation fixes, XML comment fixes, and code fixes. The code fixes are admittedly minor in terms of putting modifiers in standard order. We can either split this into multiple PRs or if we accept it as-is, I would suggest that we are careful in squashing and re-ordering commits. I would keep each type of change in its own commit and only squash together related ones.

2020-12-02 21:15 UTC, JamesKovacs commented on Docs/reference/content/reference/driver/crud/linq.md
> -
Why is the documentation for `Sum` being removed entirely? If we decide to keep `Sum`, we should find a better example than summing up people's ages. That's a strange example.

2020-12-02 21:15 UTC, JamesKovacs commented on Docs/reference/content/reference/driver/expressions.md
> -// no example yet
The example below is for `$exists` but we lose the placeholder for `$type`.

2020-12-03 19:22 UTC, rstam commented
I think we should abort this PR and start over with several smaller ones. There is too much unrelated stuff in this single PR.

Also, when making changes that start with a community submitted PR, we should always start by at least rebase the (usually old) PR on master. There might be merge conflicts to resove, and they should be resolved *before* we begin reviewing. There might be further changes required, and they also should be done after rebasing on master.

2020-12-03 19:22 UTC, rstam requested changes
Change requested: open new smaller PRs that don't contain unrelated changes coming from multiple community PRs.

2020-12-05 00:54 UTC, BorisDog commented
Abandoning, addressing in few separate PRs

2020-12-05 00:54 UTC, closed without merging