CSHARP-2127: EnumSerializer should support all underlying types.
mongodb/mongo-csharp-driver pull request #426
Opened 2020-12-14 18:48 UTC by BorisDog

CSHARP-2127: EnumSerializer should support all underlying types.
Follow up for [310](https://github.com/mongodb/mongo-csharp-driver/pull/310)

2020-12-14 23:05 UTC, rstam requested changes

2020-12-14 23:05 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Don't use `Unsafe.As`. Simply use:

    private int ConvertEnumToInt32(TEnum value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: return (int)(byte)(object)value;
            case TypeCode.Int16: return (int)(short)(object)value;
            case TypeCode.Int32: return (int)(object)value;
            case TypeCode.Int64: return checked((int)(long)(object)value);
            case TypeCode.SByte: return (int)(sbyte)(object)value;
            case TypeCode.UInt16: return (int)(ushort)(object)value;
            case TypeCode.UInt32: return (int)(uint)(object)value;
            case TypeCode.UInt64: return (int)(checked((uint)(ulong)(object)value));
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-14 23:05 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Simply use:

    private long ConvertEnumToInt64(TEnum value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: return (long)(byte)(object)value;
            case TypeCode.Int16: return (long)(short)(object)value;
            case TypeCode.Int32: return (long)(int)(object)value;
            case TypeCode.Int64: return (long)(object)value;
            case TypeCode.SByte: return (long)(sbyte)(object)value;
            case TypeCode.UInt16: return (long)(ushort)(object)value;
            case TypeCode.UInt32: return (long)(uint)(object)value;
            case TypeCode.UInt64: return (long)(ulong)(object)value;
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-14 23:05 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        private string ConvertEnumToString(TEnum value) => value.ToString();
Don't mix method notations in the same file. Just use:

    private string ConvertEnumToString(TEnum value)
    {
        return value.ToString();
    }

2020-12-15 00:24 UTC, DmitryLukyanov approved these changes
Assuming that Robert's comments are resolved. LGTM

2020-12-15 00:24 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
let's revert this diff

2020-12-15 00:24 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +﻿/* Copyright 2010-present MongoDB Inc.
Currently we set the current year in the first year :)

2020-12-15 00:53 UTC, rstam requested changes

2020-12-15 00:53 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
If you find enough documentation to convince ourselves that using `Unsafe.As<>` is a conservative enough approach we can avoid bugs on big endian machines by not trying to have a single `checkedVal` variable whose length is most of the time incorrect:

    private TEnum ConvertInt32ToEnum(int value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: var byteValue = checked((byte)value);  return Unsafe.As<byte, TEnum>(ref byteValue);
            case TypeCode.Int16: var int16Value = checked((short)value);  return Unsafe.As<short, TEnum>(ref int16Value);
            case TypeCode.Int32: return Unsafe.As<int, TEnum>(ref value);
            case TypeCode.Int64: var int64Value = (long)value;  return Unsafe.As<long, TEnum>(ref int64Value);
            case TypeCode.SByte: var sbyteValue = checked((sbyte)value);  return Unsafe.As<sbyte, TEnum>(ref sbyteValue);
            case TypeCode.UInt16: var uint16Value = checked((ushort)value);  return Unsafe.As<ushort, TEnum>(ref uint16Value);
            case TypeCode.UInt32: var uint32Value = checked((uint)value);  return Unsafe.As<uint, TEnum>(ref uint32Value);
            case TypeCode.UInt64: var uint64Value = (ulong)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-15 00:53 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Or a refactored alternative using `Unsafe.As<>` that works on both little and big endian machines:

    private TEnum ConvertInt64ToEnum(long value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: var byteValue = checked((byte)value); return Unsafe.As<byte, TEnum>(ref byteValue);
            case TypeCode.Int16: var int16Value = checked((short)value); return Unsafe.As<short, TEnum>(ref int16Value);
            case TypeCode.Int32: var int32Value = checked((int)value);  return Unsafe.As<int, TEnum>(ref int32Value);
            case TypeCode.Int64: return Unsafe.As<long, TEnum>(ref value);
            case TypeCode.SByte: var sbyteValue = checked((sbyte)value); return Unsafe.As<sbyte, TEnum>(ref sbyteValue);
            case TypeCode.UInt16: var uint16Value = checked((ushort)value); return Unsafe.As<ushort, TEnum>(ref uint16Value);
            case TypeCode.UInt32: var uint32Value = checked((uint)value); return Unsafe.As<uint, TEnum>(ref uint32Value);
            case TypeCode.UInt64: var uint64Value = (ulong)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-15 00:53 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
The key feature of the second refactoring is that the first generic type used with `Unsafe.As<?, TEnum>` is **always** the underlying representation of the enum, so we can be sure that we won't have any surprises by using a variable of the wrong size.

2020-12-15 20:02 UTC, BorisDog commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
Proceeding with this approach as discussed.

2020-12-15 20:02 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +using System.Runtime.CompilerServices;
Proceeding with this approach as discussed.

2020-12-15 20:02 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Proceeding with current approach as discussed.

2020-12-15 20:14 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Thanks, done.

2020-12-15 20:15 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Thanks, done.

2020-12-15 20:16 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        private TEnum ConvertDoubleToEnum(double value) => ConvertInt64ToEnum(checked((long)value));
Proceeded with slightly different formatting, as discussed.

2020-12-15 20:16 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Proceeding with current approach as discussed.

2020-12-15 20:17 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        private TEnum ConvertStringToEnum(string value) => (TEnum)Enum.Parse(typeof(TEnum), value);
Thanks, reordering done.

2020-12-15 20:17 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +﻿/* Copyright 2010-present MongoDB Inc.
Thanks, done.

2020-12-15 20:17 UTC, BorisDog commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Thanks, done.

2020-12-15 20:18 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +        }
Proceeding with current approach as discussed.

2020-12-15 22:16 UTC, rstam requested changes

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    return Unsafe.As<int, TEnum>(ref value);
I don't like this "optimization". Let's treat `int` and `uint` as distinct types.

I understand this "works", but it's tricky.

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
I don't like this "optimization". Let's treat `long` and `ulong` as distinct types.

I understand this "works", but it's tricky.

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
Proposed version using the exact underlying type in every case:

    private TEnum ConvertInt32ToEnum(int value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: var byteValue = checked((byte)value); return Unsafe.As<byte, TEnum>(ref byteValue);
            case TypeCode.Int16: var int16Value = checked((short)value); return Unsafe.As<short, TEnum>(ref int16Value);
            case TypeCode.Int32: return Unsafe.As<int, TEnum>(ref value);
            case TypeCode.Int64: var int64Value = (long)value; return Unsafe.As<long, TEnum>(ref int64Value);
            case TypeCode.SByte: var sbyteValue = checked((sbyte)value); return Unsafe.As<sbyte, TEnum>(ref sbyteValue);
            case TypeCode.UInt16: var uint16Value = checked((ushort)value); return Unsafe.As<ushort, TEnum>(ref uint16Value);
            case TypeCode.UInt32: var uint32Value = (uint)value; return Unsafe.As<uint, TEnum>(ref uint32Value);
            case TypeCode.UInt64: var uint64Value = (ulong)(long)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    return Unsafe.As<long, TEnum>(ref value);
I don't like this "optimization". Let's treat `long` and `ulong` as distinct types.

I understand this "works", but it's tricky.

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    return Unsafe.As<long, TEnum>(ref value);
Proposed refactoring using the exact underlying type in every case:

    private TEnum ConvertInt64ToEnum(long value)
    {
        switch (_underlyingTypeCode)
        {
            case TypeCode.Byte: var byteValue = checked((byte)value); return Unsafe.As<byte, TEnum>(ref byteValue);
            case TypeCode.Int16: var int16Value = checked((short)value); return Unsafe.As<short, TEnum>(ref int16Value);
            case TypeCode.Int32: var int32Value = checked((int)value); return Unsafe.As<int, TEnum>(ref int32Value);
            case TypeCode.Int64: return Unsafe.As<long, TEnum>(ref value);
            case TypeCode.SByte: var sbyteValue = checked((sbyte)value); return Unsafe.As<sbyte, TEnum>(ref sbyteValue);
            case TypeCode.UInt16: var uint16Value = checked((ushort)value); return Unsafe.As<ushort, TEnum>(ref uint16Value);
            case TypeCode.UInt32: var uint32Value = checked((uint)value); return Unsafe.As<uint, TEnum>(ref uint32Value);
            case TypeCode.UInt64: var uint64Value = (ulong)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);
            default: throw new InvalidOperationException($"Unexpected underlying type code: {_underlyingTypeCode}.");
        }
    }

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            (TEnum)Enum.Parse(typeof(TEnum), value);
(TEnum)Enum.Parse(typeof(TEnum), value, ignoreCase: true);

Probably worth specifying `ignoreCase: true`. What do you think?

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            _representation;
We usually don't make style only changes that are unrelated to the task at hand.

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
Notice the double cast `(ulong)(long)value` in the `UInt64` case.

I realize that the `(long)` is implied, but it's tricky and not obvious. Without it it's unclear which of the following two cases might be the implied one:

    (ulong)(long)value
    (ulong)(uint)value

And they are **very** different where negative numbers are concerned.

2020-12-15 22:16 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
Note: cases in type code order (alphabetical).

2020-12-15 22:16 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +    public class ClassWithEnumAll
This test class feels like it is being used to test too many things at once.

Let's think about how to structure all these tests so that each test method is only testing one thing.

We need to consider all combinations of:

1. Underlying type
2. [BsonRepresentation]
3. Overfow or not overflow
4. Valid or invalid data (e.g. value in database is a `BsonDocument` instead of a number)

Let me know if you want to brainstorm about how to structure these tests.

2020-12-17 00:56 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializationTests.cs
> +    public class EnumWrapperAsString<T> where T : Enum
@rstam we can consider unifying all EnumWrapperX classes into single class

2020-12-17 00:56 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
Done

2020-12-17 00:56 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                    return Unsafe.As<long, TEnum>(ref value);
Done

2020-12-17 00:57 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            (TEnum)Enum.Parse(typeof(TEnum), value);
Good idea, done

2020-12-17 00:57 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            _representation;
Just for consistency within same file

2020-12-17 00:58 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +    public class ClassWithEnumAll
@rstam please review EnumSerializationTests.cs and consider removing EnumSerializerTests.cs

2020-12-18 19:17 UTC, rstam requested changes
Some small changes requested to `EnumSerializer` to fix small bugs discovered while refactoring `EnumSerializerTests`.

I've completely refactored `EnumSerializerTests.cs` (which was only partially implemented anyway) following our current best practices for unit testing.

These changes are too extensive to be annotated in individual comments but can be seen on my branch here:

https://github.com/rstam/mongo-csharp-driver/tree/csharp2127-1218

Please seriously consider following our current testing practices rather than deviating from them. It is fair to question them, but at least start from there.

One fundamental difference between your `EnumSerializationTests` and my refactored `EnumSerializerTests` is that I do NOT think it is necessary or useful to use wrapping classes. Instead we should create new instances of `EnumSerializer` using code like:

    var subject = new EnumSerializer<TEnum>(representation);

and write tests against the serializer directly.

Using wrapping classes is simply adding levels of indirection and doesn't contribute in any way to the testing of the `EnumSerializer`.

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                case TypeCode.UInt64: return Unsafe.As<TEnum, long>(ref value);
Testing while refactoring `EnumSerializerTests` confirms that this line should be:

     case TypeCode.UInt64: return (long)Unsafe.As<TEnum, ulong>(ref value);

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                case TypeCode.Int64: var longValue = (long)value; return Unsafe.As<long, TEnum>(ref longValue);
Let's be consistent in our variable naming:

    case TypeCode.Int64: var int64Value = (long)value; return Unsafe.As<long, TEnum>(ref int64Value);

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                case TypeCode.UInt64: var uint64Value = (ulong)(long)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);
Should be:

    case TypeCode.UInt64: var uint64Value = (ulong)(uint)value; return Unsafe.As<ulong, TEnum>(ref uint64Value);

Discovered while refactoring `EnumSerializerTests`

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +                case TypeCode.UInt32: var uint32Value = checked((uint)value); return Unsafe.As<uint, TEnum>(ref uint32Value);
Should be:

    case TypeCode.UInt32: var uint32Value = checked((uint)unchecked((ulong)value)); return Unsafe.As<uint, TEnum>(ref uint32Value);

Discovered while refactoring `EnumSerializerTests`.

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            (TEnum)Enum.Parse(typeof(TEnum), value, true);
It's helpful to include the parameter name when the argument value is not self-explanatory:

    (TEnum)Enum.Parse(typeof(TEnum), value, ignoreCase: true);

2020-12-18 19:17 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializationTests.cs
> +    public class EnumWrapper<T> where T : Enum
I see no need to use wrapper classes to test the `EnumSerializer`. Once you're using wrapper classes you are testing things OUTSIDE of the `EnumSerializer`.

See the refactored `EnumSerializerTests`.

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +    public class EnumSerializer<TEnum> : StructSerializerBase<TEnum>, IRepresentationConfigurable<EnumSerializer<TEnum>> where TEnum : struct, Enum
At the time this was first written I don't think `Enum` was a valid type constraint.

Nice change!

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            _representation;
Fair enough... still, it's good to avoid extraneous diffs most of the time.

2020-12-18 19:17 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +            ConvertInt64ToEnum(checked((long)value));
The issue is that `checked((long)value)` only throws on overflow, not when precision is lost.

Technically `OverflowException` might not be the correct exception type here... but I'm sort of OK with it.

2020-12-18 19:17 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +namespace MongoDB.Bson.Tests.Serialization.Serializers
I have completely refactored this class to follow our current testing practices.

Please study it to learn how we currently write tests.

It's fair to question our current practices, but at least start from them.

2020-12-18 19:17 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +namespace MongoDB.Bson.Tests.Serialization.Serializers
I've not added any additional comments to this file because there are so many changes.

See the refactored version of `EnumSerializerTests.cs` on my branch here:

https://github.com/rstam/mongo-csharp-driver/tree/csharp2127-1218

2021-01-05 23:44 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/EnumSerializerTests.cs
> +namespace MongoDB.Bson.Tests.Serialization.Serializers
Integrated the refactored changes.

2021-01-06 01:10 UTC, rstam approved these changes
LGTM

I really liked your idea of using `CSharpDriver.Bson.slnf` to filter the solution to only the Bson projects. That helped a lot to speed up the Test Explorer.

Feel free to add `CSharpDriver.Bson.slnf` to the repo.

I'd also like to call out a couple nice new ideas you brought to this PR, like:

* Use of `Unsafe.As` to easily re-interpret bytes
* Use of generic test methods in xUnit, this is very cool!!!

2021-01-06 17:02 UTC, BorisDog commented
[EG](https://evergreen.mongodb.com/version/5ff4f43dd1fe076258828688) [Internal Link]

2021-01-06 17:07 UTC, BorisDog commented
[Squashed&Merged](https://github.com/mongodb/mongo-csharp-driver/commit/3592cf28b7de3c007cb74370ea764d0e2a5c3f6d)

2021-01-06 17:07 UTC, closed without merging