Csharp2692
mongodb/mongo-csharp-driver pull request #428
Opened 2020-12-28 21:33 UTC by BorisDog

CSHARP-2693/CSHARP-2692: Encoding.GetBytes buffer caching optimization

2020-12-28 22:46 UTC, BorisDog commented
[EG Patch](https://evergreen.mongodb.com/version/5fea4cdf3e8e862d05ffc5dd)  [InternalLink]

2020-12-29 01:33 UTC, rstam requested changes
Note: we don't usually combine multiple JIRA tickets in a single PR.

I'm waiting to see what others thing about the potential dangers I've identified of using a single cached buffer (per thread) across multiple classes before reviewing further.

2020-12-29 01:33 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +            var bytes = BufferCache.GetBuffer(length);
Initial reaction: this feels like it could be very dangerous.

The main concern is that the `_tempUtf8` buffer was owned by this **class**. Now we're switching to using a buffer owned by the **thread**.

The danger is that two different classes might both try to use the same buffer in a scenario where one class calls the other and both try to use the same buffer. In this scenario the second class will reuse and overwrite the contents of the one and only cached buffer which will corrupt the caller's data. We've had bugs like this before where the same buffer was used simultaneously for two different purposes which were very hard to find.

While we can carefully examine our code to ensure that we don't let this scenario happen, it feels dangerous to use a buffer caching technique that could easily result in unexpected bugs.

Other possible issues to consider:

* Is there potential for a memory leak? What happens to the `[ThreadStatic] __buffer` when the tread that caused it to be allocated no longer exists. One would hope it got garbage collected but this would have to be verified.
* A single large enough allocation can expand the cached buffer to 8K after which it never shrinks. Will this result in an eventual steady state in which all cached buffers are 8K in size? Is that OK?

I'd like to hear what other reviewers thinking about the potential dangers of using a single cached buffer per thread.

Until that question is resolved I'm going to pause reviewing this PR further.

2020-12-29 03:37 UTC, rstam requested changes

2020-12-29 03:37 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +                length = CStringUtf8Encoding.GetBytes(value, bytes, 0, Utf8Encodings.Strict);
Consider keeping `_tempUtf8` as is (possibly increasing its size to make it usable more often) and instead ONLY change the `else` clause to use a buffer from a shared pool instead of allocating a new one.

We should consider using the standard .NET `MemoryPool<byte>.Shared` pool from the `System.Buffers` namespace.

Note that this buffer pool does NOT associated buffers with threads, which is a good thing.

2020-12-29 03:44 UTC, rstam requested changes

2020-12-29 03:44 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +                length = CStringUtf8Encoding.GetBytes(value, bytes, 0, Utf8Encodings.Strict);
Actually we probably would use `ArrayPool<byte>` instead of `MemoryPool<byte>`.

Note that while we have NOT used these classes before, we ALREADY have  an indirect dependency  on the `System.Buffers.dll` Nuget package because `DnsClient.dll` uses it.

2020-12-29 18:31 UTC, BorisDog commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +                length = CStringUtf8Encoding.GetBytes(value, bytes, 0, Utf8Encodings.Strict);
My preference would be to keep things simple on the hot path. MemoryPool and ArrayPool are great solutions, but introduce more complex mechanisms and involve synchronization. In this particular case as we just need a local buffer for a quick operation. MemoryPool and ArrayPool would be an overkill.

The core goal of this PR is to eliminate the need to maintain local buffers. I don’t see any good reason to keep using _tempUtf8.

2020-12-29 18:32 UTC, BorisDog commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +            var bytes = BufferCache.GetBuffer(length);
I understand your concerns. There are always certain dangers when using any programming technique. But this should not prevent us from using any development tool when we are convinced in its correctness.
In this case, this trivial caching technique is intended to be used in very short and self-contained scenarios, like the current example.

Memory leak: The buffers are stored in TLS, and collected when thread is disposed. In any case, accumulative buffers size is limited to 8MB for the whole application lifecycle.

8K: Yes, I believe that this is ok. Notice that this trivial caching is **intended** to be very simple and efficient. I don’t think we need anything more sophisticated at this point.

2020-12-30 06:09 UTC, rstam requested changes
More partial review comments.

This is an interesting PR.

I'd like us to learn more about the performance characteristics of using a ThreadStatic cached buffer. It's possible that the new `GetBuffer` method adds overhead and that it would still be beneficial to keep the `_tempUtf8` field to get better performance when the requried buffer size is small enough.

2020-12-30 06:09 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +                length = CStringUtf8Encoding.GetBytes(value, bytes, 0, Utf8Encodings.Strict);
> The core goal of this PR is to eliminate the need to maintain local buffers.

I thought the core goal of this PR was to avoid allocating new buffers when the `__tempUtf8` buffer isn't big enough, by using the thread cached buffer (when the required buffer size is <= 8K).

2020-12-30 19:53 UTC, BorisDog commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +            var bytes = BufferCache.GetBuffer(length);
Memory leak: Yes, while I haven't not found any specific documentation about TLS garbage collection process yet, I've verified that objects finalizers are being called.

Larger initial size: Absolutely, good point.

2020-12-30 20:02 UTC, BorisDog commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +                length = CStringUtf8Encoding.GetBytes(value, bytes, 0, Utf8Encodings.Strict);
Eliminating branching: It's definitely a good idea. But given that CStringUtf8Encoding.GetBytes is different from Utf8Encodings.Strict.GetBytes we need to consider this carefully, and maybe address this issue in separate PR.

Performance: Good point as well. From by benchmarks, accessing thread static fields vs local field adds about 5-8% to running time. But given that the _tempUtf8 is allocated with **every** instance of the enclosing object, accessing thread static buffer is faster overall, and contributes to reducing memory pressure. In similar scenario benchmark (2 resizes), thread static approach reduces overall time by 50%, while using ArrayPool increases the running time by 100%.

2020-12-30 20:03 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +    internal static class BufferCache
Good point, tnx.

2020-12-30 20:08 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +                __buffer == null && Interlocked.Increment(ref __buffersCount) >= MaxThreads)
It's not decremented. The main idea is to provide a good-enough and very simple heuristics to optimize the majority of uses cases while not degrading the rest. This optimization will fit well with TPL and other ThreadsPools scenarios, which I believe would be vast majority of the use cases.

2020-12-30 20:09 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +        private static int CeilPower2(int number)
Tnx!

2020-12-30 23:16 UTC, rstam requested changes

2020-12-30 23:16 UTC, rstam commented on src/MongoDB.Bson/IO/BufferCache.cs
> +    internal static class BufferCache
Or even `ThreadStaticBuffer` (seems pretty accurate!).

2020-12-30 23:16 UTC, rstam commented on src/MongoDB.Bson/IO/BufferCache.cs
> +                __buffer == null && Interlocked.Increment(ref __buffersCount) >= MaxThreads)
I don't think you should limit this technique to the first 1024 threads.

That means that after 1024 threads have used the thread static buffer we will fall back to allocating a NEW buffer EVERY time, which will be specially bad if you also eliminate the `_tempUtf8` field.

We can't stop applications from creating more than 1024 threads. Some applications create a new thread to process each incoming request. Applications that work that way will blow by the 1024 limit quickly.

I say just remove the `__buffersCount` field and let all threads that need it have a thread static buffer.

2020-12-31 03:07 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +                __buffer == null && Interlocked.Increment(ref __buffersCount) >= MaxThreads)
Done, tnx.

2020-12-31 03:07 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +    internal static class BufferCache
Done, tnx.

2020-12-31 03:07 UTC, BorisDog commented on src/MongoDB.Bson/IO/BufferCache.cs
> +        private static int CeilPower2(int number)
Done.

2021-01-26 22:24 UTC, rstam requested changes

2021-01-26 22:24 UTC, rstam commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +                throw new ArgumentNullException(nameof(encoding), "Value cannot be null.");
It is sufficient to use the single argument form. The default message is fine.

     throw new ArgumentNullException(nameof(encoding));

2021-01-26 22:24 UTC, rstam commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +                throw new ArgumentNullException(nameof(value), "Value cannot be null.");
It is sufficient to use the single argument form. The default message is fine.

     throw new ArgumentNullException(nameof(value));

2021-01-26 22:24 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +            if (!(__buffer?.Length >= size))
I suppose this is correct, but I really don't want to jump through all the mental hoops of how nullable ints are compared and what that negated condition means.

I recommend a slightly longer but much easier to read if statement:

    if (__buffer == null || __buffer.Length < size)

because that's close to the English description of "if the buffer hasn't been created yet or is too small" then "create a new buffer".

2021-01-26 22:24 UTC, rstam commented on src/MongoDB.Bson/PowerOf2.cs
> +                return n;
This isn't changing the results of this method right? Isn't this what the calculation below already did?

No harm in adding this, but I want to confirm that it's some sort of optimization/clarification and not a change in logic.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public void TestEncodingHelper_invalid_encoding_shouldthrow()
We use the following naming convention for our unit test methods:

    Method_should_something
    Method_should_something_when_something

Which in this case would be:

    GetBytesUsingThreadStaticBuffer_should_throw_when_encoding_is_null

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            var exception = Record.Exception(() => EncodingHelper.GetBytesCachedBuffer(null, "asd"));
A typical test method consists of three sections: Arrange, Act, Assert, separated by one blank line. In this case there is no Arrange, just Act and Assert.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            exception.Message.Should().Contain("encoding");
We have  a pattern we use for testing these exceptions:

            var e = exception.Should().BeOfType<ArgumentNullException>().Subject;
            e.ParamName.Should().Be("encoding");

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        }
Putting the above comments together results in a test method conforming to our conventions that looks like:

        [Fact]
        public void GetBytesUsingThreadStaticBuffer_should_throw_when_encoding_is_null()
        {
            var exception = Record.Exception(() => EncodingHelper.GetBytesUsingThreadStaticBuffer(null, "asd"));

            var e = exception.Should().BeOfType<ArgumentNullException>().Subject;
            e.ParamName.Should().Be("encoding");
        }

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public void TestEncodingHelper_invalid_string_shouldthrow()
Rename to `GetBytesUsingThreadStaticBuffer_should_throw_when_value_is_null`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public void TestEncodingHelper_empty_string_shouldbe_default_buffer()
Rename to `GetBytesUsingThreadStaticBuffer_should_throw_when_value_is_null`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            exception.Message.Should().Contain("encoding");
Apply this pattern to the other similar test methods also.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public void TestEncodingHelper_should_reuse_instance(int maxStringSize)
Rename to `GetBytesUsingThreadStaticBuffer_should_return_same_instance_when_possible`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public async Task TestEncodingHelperMultithreaded_should_encode_correctly()
Rename to `GetBytesUsingThreadStaticBuffer_should_return_expected_result_when_multiple_threads_are_used`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public async Task TestEncodingHelperMultithreaded_should_encode_correctly()
I'm not really sure what this method is testing. It appears to be a multi threaded stress test that tries to do a whole bunch of tests in several threads at once.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            const int maxIterations = 10;
This isn't the "max" iterations, it IS the number of iterations. Consider renaming to `numberOfIterations`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            var tasks = Enumerable.Range(0, threadsCount).Select(i => Task.Run(() =>
I myself am usually reluctant to use Task when what I'm trying to test is something Thread related.

It's not that I don't understand the relationship between a Task and the thread(s) it might run on. But when using Task you give up control of which Thread gets used. Given enough Tasks you might even end up running two or more Tasks on the same thread (one after the other) depending on how/when they get scheduled, which might result in spurious failures.

What do you think? Would it be safer and more explicit to use Threads to test multi-threading?

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +                        encodedActual.ShouldAllBeEquivalentTo(encodedExpected);
If this throws an exception it will only cause the Task to fault. It won't directly cause the test to fail.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +            await Task.WhenAll(tasks);
This test will never fail no matter what because we aren't checking whether any of the completed tasks are faulted.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +        public void TestBuffer_invalid_buffer_size_should_throw(int size)
Rename to `GetBuffer_should_throw_when_size_is_invalid`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +        public void TestBufferSizeIncreasing_expected_powerof2()
Rename to something along the lines of `GetBuffer_should_resize_buffer_to_next_power_of_2_when_resizing_buffer`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +                    var expectedSize = Math.Max(16, 1 << (int)Math.Ceiling(Math.Log(requestedSize, 2)));
I try to avoid logic in tests, because of the risk that the logic in the test and in the subject under test will have the same bug (since I wrote them both).

Logic like this can be replace with explicit values using `InlineData`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +        public void TestBufferSizeGreaterThanMaxSize_expected_exact_size(int requestedSize)
Rename `GetBuffer_should_return_expected_length_segment` or something like that

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +        public void TestBufferMultiThreaded_expected_unique_instance_per_thread()
Rename to `GetBuffer_should_return_different_instance_in_different_threads`

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +            buffersOrdered.ShouldAllBeEquivalentTo(buffersDistinct);
I haven't figured out why you need to order the buffers for testing.

2021-01-26 22:24 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +                    throw new TimeoutException();
It is our practice to always use braces even for single line then clauses, like:

                if (!thread.Join(10000))
                {
                    throw new TimeoutException();
                }

2021-01-26 23:41 UTC, JamesKovacs reviewed
Taking a step back from the detailed discussion...

If the problem is that in the hot path `_tempUtf8` buffer isn't sufficiently large enough and we often allocate temporary byte buffers > 128 bytes which must then be GC'd, have we considered the simpler solution of simply increasing the size of `_tempUtf8` buffer to a larger and more reasonable value?

Something else to consider... What is the lifetime of a `BsonStreamAdapter`? What I'm thinking is that if we need a large byte buffer, rather than allocating it for the one `ReadString` operation, we make the larger byte buffer the cached one:

```
var length = ReadInt32();
if (length > _tempUtf8.Length)
{
    _tempUtf8 = new byte[PowerOf2.RoundUpToPowerOf2(length)];
}
var bytes = _tempUtf8;
```

Just some ideas I wanted to throw out there for discussion.

2021-01-29 18:02 UTC, rstam reviewed
Overall I think this PR is looking OK.

Please read the warning in one of the comments about using the `ThreadStaticBuffer` without corruption.

2021-01-29 18:02 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
>              _stream.Write(bytes, 0, length);
This is an example of the potential danger of using the `ThreadStaticBuffer`. We are passing a reference to the `ThreadStaticBuffer` to the `Write` method which for all we know *might* itself attempt to use the `ThreadStaticBuffer` for its own purposes. If it did, the `ThreadStaticBuffer` would get corrupted.

In order to use the `ThreadStaticBuffer` without corruption we MUST understand the FULL code path of any method we pass a reference to the `ThreadStaticBuffer` to ENSURE that only one part of the driver is using the `ThreadStaticBuffer` at the same time.

2021-01-29 18:04 UTC, rstam commented
One other concern about using `ThreadStaticBuffer` has just come to mind.

It could  totally fall apart if a reference to the `ThreadStaticBuffer` is ever used in an async `Task` because execution of the `Task` *might* jump to a different thread later on.

2021-01-29 19:05 UTC, BorisDog commented
@rstam Interesting point re. switching threads in Tasks.
Yes, it's unsafe to use ThreadStatic when execution of a method is not guaranteed to occur on single thread. In context of Tasks, that would happen when a Task consists of multiple sub-tasks, in which case ThreadStatic should not be used. In case of a Task with no sub-tasks it's safe. Added a warning in ThreadStaticBuffer.

2021-01-29 19:24 UTC, rstam commented
> @rstam Interesting point re. switching threads in Tasks.
> Yes, it's unsafe to use ThreadStatic when execution of a method is not guaranteed to occur on single thread. In context of Tasks, that would happen when a Task consists of multiple sub-tasks, in which case ThreadStatic should not be used. In case of a Task with no sub-tasks it's safe. Added a warning in ThreadStaticBuffer.

The subtasks might not even be visible to the caller. Consider:

    var buffer = EncodingHelper.GetBytesUsingThreadStaticBuffer(...);
    await stream.WriteAsync(buffer);

If the buffer is big enough `WriteAsync` might have to write it in several passes, and subsequent passes might execute on a different thread.

So even though the two line snippet "looks" safe it is not.

We just have to be super careful how we use the `ThreadStaticBuffer`. It's a dangerous tool.

2021-01-29 19:29 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +            buffersDistinct.Length.Should().Be(threadsCount);
I understand. But it is redundant. The whole point of this test is to check that every thread gets its own buffer.

Line 111 is only testing the test... we already know that `allBuffers.Count == threadsCount`.

2021-01-29 20:18 UTC, BorisDog commented
@rstam Yes, if we have code like 
```
async Task F() {
  1. syncronious code...
  2. await T
}
```
`await T` is clearly a subtask.
I agree that we should always carefully examine our async code.

2021-01-30 00:41 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/IO/EncodingHelperTests.cs
> +        public void GetBytesUsingThreadStaticBuffer_empty_string_should_return_default_buffer()
Done.

2021-01-30 00:41 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/IO/ThreadStaticBufferTests.cs
> +            buffersDistinct.Length.Should().Be(threadsCount);
Done. Added assertion in ThreadingUtilities.

2021-02-04 00:22 UTC, JamesKovacs reviewed
Overall I like the buffer caching technique and implementation. I see two main risks:

1. If we call `ThreadStaticBuffer.GetBuffer()` twice from the same thread in two different methods, then we will very likely get the same buffer and corrupt it. If the second buffer we happen to request is larger than the currently allocated buffer, then we would end up with two different buffers. While this wouldn't result in corruption because we by happenstance are using two different buffers, this would make debugging buffer corruption problems confusing.
2. `async` code is particularly dangerous. If we get a buffer, `await`, and then use the buffer, we will likely be executing on a different thread. The original thread might be scheduled to do other work that requires a buffer and we now have two threads accessing the same thread-static buffer.

While we can document these two limitations in the comments for `ThreadStaticBuffer`, there are no guarantees that our future selves will remember to read those comments. Are there ways to enforce these constraints in the code itself? Can we make `ThreadStaticBuffer` a private nested class to avoid misuse? (This wouldn't address the async problem though.) Should we consider a buffer pool impl instead? Other ideas?

~Another concern... Our max cached buffer size is configured to be 1GB. This means that under certain workloads that require large buffers, the memory usage of the thread static buffers will gradually increase to ThreadCount x 1GB. This will appear to be a memory leak, but will in fact simply be the thread static buffers slowly growing as each thread happens to require larger and larger buffers.~ Scratch that. Our maximum temporary allocation size is 1GB. Our maximum cached buffer size is 16KB. Maximum memory usage of the cached buffers would be at most ThreadCount x 16KB, which isn't concerning.

2021-02-04 17:45 UTC, BorisDog commented
Thanks @JamesKovacs, it's important to be extra careful with multithreaded programming .
Like with most other programming tools like Threads, TPL or synchronization primitives, we can not really use them until we understand them in full. I find that `ThreadStatic` feature technique is one of the simplest tools in multithreading tools arsenal, so we just need to get used to it. While we can always find scenarios where this tool is not applicable this should not prevent us from valid usages.

1. Yes, we should not call twice `ThreadStaticBuffer.GetBuffer()` in same thread in nested methods. Exactly like we should not use local cached buffer in same thread in nested methods.
2. Yes, as mentioned before, in some/most cases `ThreadStatic` is not suitable to use in tasks that spin off other tasks.

2021-02-05 15:08 UTC, rstam commented
> @JamesKovacs said: Are there ways to enforce these constraints in the code itself?

We could adopt a checkout/checkin protocol for the ThreadStaticBuffer

1. Attempting to check out the buffer twice would throw an exception
2. Attempting to check in a buffer from the wrong thread would throw an exception

2021-02-05 16:19 UTC, JamesKovacs commented
I like @rstam's suggested approach of throwing an exception if we violate our constraints. Let's implement that.

2021-02-11 20:48 UTC, rstam requested changes
Please re-request our review after you have added the check-out/check-in protocol for the ThreadStaticBuffer.

2021-02-12 15:54 UTC, rstam commented
I'm not sure I full know the reasons why, but we avoid force pushing to PRs.

Was the force push necessary? 

Are we wrong to be avoiding force pushes?

2021-02-12 16:09 UTC, BorisDog commented
@rstam I had to rebase (to use  newer C#) and could only force push to feature branch.
Maybe there is a more graceful way?

2021-02-12 19:20 UTC, rstam requested changes
Looks good with some relatively minor requested changes.

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/BsonStreamAdapter.cs
> +            void SetBytes(byte[] bytes, int length)
I like this local helper method but I think you should rename it to `WriteBytes`.

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ByteBufferStream.cs
> +                    using var acquiredBuffer = ThreadStaticBuffer.GetBuffer(maxLengthToUseCStringUtf8EncodingWith);
Can you rename this variable to `rentedBuffer` for consistency?

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        public struct RentableBuffer : IDisposable
I like this helper class. Can we rename to `RentedBuffer`?

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                    throw new InvalidOperationException("Thread static buffer is not in use");
Note: we always use braces for `if` even if it's only one line.

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                    throw new InvalidOperationException("Thread static buffer is not in use");
This checks that we are actually using the buffer that we are trying to return.

We also need to check whether we are trying to return the buffer from the wrong thread.

See suggested change below.

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        }
Requested refactoring for this class:

    public struct RentedBuffer : IDisposable
    {
        private readonly byte[] _buffer;
        private readonly byte[] _bytes; // usually the same as _buffer unless the request was too big

        public RentedBuffer(byte[] buffer, byte[] bytes)
        {
            _buffer = buffer;
            _bytes = bytes;
        }

        public void Dispose()
        {
            if (!__isBufferRented)
            {
                throw new InvalidOperationException("Thread static buffer is not in use");
            }
            if (_buffer != __buffer)
            {
                throw new InvalidOperationException("Attempt to return thread static buffer from the wrong thread.");
            }

            __isBufferRented = false;
        }

        public byte[] Bytes => _bytes;
    }

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        }
Notes:

We need to track both the `_buffer` *and* the `_bytes` because sometimes `RentBuffer` returns a newly allocated buffer that is *not* the thread static buffer.

We usually use explicit backing fields instead of auto properties.

I renamed the public property from `Buffer` to `Bytes` because it's not always the buffer.

Auto properties would be OK for very simple classes (this one almost qualifies), but personally I prefer explicit properties (with the leading underscore naming convention) for consistency.

What we should never do is mix explicit backing fields and auto properties in the same class (which of course you were not doing here, just making a comment for the future).

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private static bool __isBufferInUse;
For consistency rename to `__isBufferRented`

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        public static RentableBuffer GetBuffer(int size)
For consistency rename to `RentBuffer`

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                return new byte[size];
With suggested refactoring of `RentedBuffer` class this line would become:

    return new RentedBuffer(__buffer, new byte[size]);

2021-02-12 19:20 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +            return __buffer;
With suggested refactoring of `RentedBuffer` class this line would become:

    return new RentedBuffer(__buffer, __buffer);

2021-02-14 01:24 UTC, rstam requested changes

2021-02-14 01:24 UTC, rstam commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +        public struct DisposableSegment : IDisposable
I recommend that types that implement `IDisposable` be a `class`, not a `struct`.

2021-02-14 01:24 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private struct RentedBuffer : IRentedBuffer
I recommend that types that implement `IDisposable` be a `class`, not a `struct`.

2021-02-14 01:24 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        public static IRentedBuffer GetBuffer(int size)
Looks like you missed renaming this to `RentBuffer`.

2021-02-14 01:24 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        }
I understand what you are doing here by using an interface, but it may be a unnecessary. In part because the containing class is already `internal`, and also because the interface isn't really hiding anything (if you make the `RentedBuffer` constructor private then the `RentedBuffer` class has exactly the same public members as the proposed interface).

2021-02-14 01:24 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private static object ThreadIdentifier => __buffer ?? (__buffer = new byte[0]);
I understand what you are doing here, but the implication of something called a `ThreadIdentifier` is that the thread would have a stable identifier, and using the `__buffer` as a pseudo-identifier is confusing because it can change over time.

The originally proposed check

    if (_buffer != __buffer)

made intuitive sense to me... is the rented buffer we are returning the right one for the current thread?

I assume you went down this path because you realized that it was theoretically possible for `__buffer` to still be null if all the initial calls to `RentBuffer` are for sizes that are so big they result in the allocation of a temporary buffer. One approach would be to ignore that, it's unlikely and it's temporary. Another approach would be to simply ensure that `__buffer` is not null in the `RentBuffer` method.

I realize that your code in fact ensures that `__buffer` is never null... but the fact that it does so as a hidden side effect of a property called `ThreadIdentifier` is rather surprising.

If you prefer comparing thread identifiers to verifying that the buffer being returned matches the thread static buffer, maybe it would be clearer to use a `Guid` as the `ThreadIdentifier` so that it behaves like you expect an identifier to behave, in the sense that it is stable over time.

2021-02-16 17:43 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        }
Unfortunately we can't prevent creation of structs with private constructors.

2021-02-16 17:43 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private static object ThreadIdentifier => __buffer ?? (__buffer = new byte[0]);
Thanks, it's a good idea to make this owner-returner thread check clear and readable. Initially I thought taking the `__buffer` shortcut would do, but looks like we should take more traditional approach.
Refactored using `Thread.ManagedThreadId` property.

2021-02-16 17:43 UTC, BorisDog commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +        public struct DisposableSegment : IDisposable
Addressed this in `RentedBuffer `comment.

2021-02-16 17:43 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        public static IRentedBuffer GetBuffer(int size)
Thanks, done

2021-02-16 21:39 UTC, rstam requested changes

2021-02-16 21:39 UTC, rstam commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +        public struct DisposableSegment : IDisposable
I recommend (in general) that types that implement `IDisposable` be a `class`, not a `struct`.

This was discussed in Slack.

I completely understand and endorse the desire to use a `struct` to avoid a memory allocation. A `struct` that implements `IDisposable` can sometime behave in very unpredictable ways because value types can result in multiple copies of the `struct`.

In this particular case it appears to be safe, so I think it's OK to use `struct` if that's what you prefer.

2021-02-16 21:39 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private struct RentedBuffer : IRentedBuffer
See previous comments (and Slack discussion) for reasons why combining `struct` with `IDisposable` can be problematic.

In this case using a `struct` has **not** prevented a memory allocation, because the return value of `RentBuffer` is the interface `IRentedBuffer` and the `struct` must be boxed to convert it to the interface type.

To avoid boxing you would have to get rid of the `IRentedBuffer` interface and return the `RentedBuffer` `struct` directly.

2021-02-16 23:14 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private struct RentedBuffer : IRentedBuffer
Good point!
Removed `IRentedBuffer` interface.

Another approach would be to keep the interface, and hold internally same instance of `RenterBuffer `**class**, which would be disposed and reset each time. Not sure what is better, allowing creation of `RenterBuffer` internally outside of `ThreadStaticBuffer`, on disposing the same object repeatedly.

2021-02-17 05:14 UTC, rstam requested changes

2021-02-17 05:14 UTC, rstam commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +        public struct DisposableSegment : IDisposable
I like your idea of using `readonly struct` for `RentedBuffer`.

Maybe make this `struct` readonly also?

2021-02-17 05:14 UTC, rstam commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private static int _threadId;
Use two leading underscores for static field names:

    __threadId

2021-02-17 05:15 UTC, rstam commented
@JamesKovacs when you review this again can you review the tests carefully also? I focused on the driver changes.

2021-02-17 18:51 UTC, BorisDog commented on src/MongoDB.Bson/IO/EncodingHelper.cs
> +        public struct DisposableSegment : IDisposable
Done

2021-02-17 18:51 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +        private static int _threadId;
Tnx, done.

2021-02-18 17:32 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
> +
Right, since this was added this in `MongoDB.Bson` in recent commit.

2021-02-18 17:33 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/ThreadingUtilities.cs
> +                        actionsExecutedCount++;
Good catch, done.

2021-02-18 19:07 UTC, rstam approved these changes
LGTM

2021-02-19 22:31 UTC, JamesKovacs requested changes
LGTM. Requesting a few minor changes to clarify method naming and error message text.

2021-02-19 22:31 UTC, JamesKovacs commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                    throw new InvalidOperationException("Thread static buffer is not in use.");
This should only happen if we attempt to dispose of the `RentedBuffer` twice. Rephrase this to "Attempt to return a thread static buffer that is not in use."

2021-02-19 22:31 UTC, JamesKovacs commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                throw new ArgumentOutOfRangeException(nameof(size), "Invalid requested buffer size.");
`$"Requested buffer size of {size} bytes. Maximum buffer size is {MaxAllocationSize} bytes."`

2021-02-19 22:31 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/ThreadingUtilities.cs
> +        public static void ExecuteOnNewThread(int threadsCount, Action<int> action, int timeoutMilliseconds = 10000)
Since your first argument is `threadsCount`, rename the method to `ExecuteOnNewThreads` (plural).

2021-02-19 22:54 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/ThreadingUtilities.cs
> +        public static void ExecuteOnNewThread(int threadsCount, Action<int> action, int timeoutMilliseconds = 10000)
Done

2021-02-19 23:05 UTC, BorisDog commented on src/MongoDB.Bson/IO/ThreadStaticBuffer.cs
> +                    throw new InvalidOperationException("Thread static buffer is not in use.");
Done

2021-02-19 23:16 UTC, JamesKovacs approved these changes
LGTM

2021-03-01 22:47 UTC, BorisDog commented
Squashed and merged

2021-03-01 22:47 UTC, closed without merging