CSHARP-3297: Handle incomplete regex patterns in JsonScanner
mongodb/mongo-csharp-driver pull request #430
Opened 2020-12-30 15:37 UTC by rkyser

2020-12-30 15:52 UTC, rkyser commented
Link to MongoDB Jira issue: https://jira.mongodb.org/projects/CSHARP/issues/CSHARP-3297

2021-01-07 15:59 UTC, rstam requested changes
Good catch!

2021-01-07 15:59 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +
I would name the test method something more specific than "invalid regular expression".

I think the test should be simplified to not have to deal with detecting infinite loops (now that the bug is fixed there is no infinite loop).

The test can be simply:

    [Theory]
    [InlineData("/")]
    [InlineData("/pattern")]
    [InlineData("/pattern\\/")]
    public void TestMissingClosingSlash(string jsonRegex)
    {
        var buffer = new JsonBuffer(jsonRegex);

        var exception = Record.Exception(() => JsonScanner.GetNextToken(buffer));

        exception.Should().BeOfType<FormatException>();
        exception.Message.Should().StartWith("Invalid JSON regular expression");
    }

2021-01-07 15:59 UTC, rstam commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +
Note: if we don't want to use FluentAssertions in a file that was first written before we started using FluentAssertions the last two lines can be rewritten using xUnit's `Assert`.

2021-01-12 13:43 UTC, rkyser commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +
Thank you for the review @rstam. I'll get these changes pushed in the next couple days.

2021-01-12 15:14 UTC, rkyser commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +
Changes have been pushed.

I opted to use the xUnit assertions to be consistent with the other tests in `JsonScannerTests`.

2021-01-21 16:17 UTC, rkyser commented
@rstam Is there anything else you need from me? If so, let me know.

2021-02-15 22:25 UTC, rstam approved these changes
LGTM

Needs a second reviewer

2021-02-17 19:35 UTC, BorisDog requested changes

2021-02-17 19:35 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +using System.Threading.Tasks;
minor: looks like there is no need for `System.Threading.Tasks`

2021-02-18 17:26 UTC, rkyser commented on tests/MongoDB.Bson.Tests/IO/JsonScannerTests.cs
> +using System.Threading.Tasks;
Good catch--change pushed.

2021-02-18 17:34 UTC, BorisDog commented
LGTM
thanks!

2021-02-18 17:35 UTC, BorisDog approved these changes

2021-02-19 22:20 UTC, rstam commented
Squashed, rebased and merged to master.

2021-02-19 22:20 UTC, closed without merging