Csharp3302
mongodb/mongo-csharp-driver pull request #435
Opened 2021-01-13 03:06 UTC by BorisDog

CSHARP3302 Addressing two issues:
1. Deadlock during heartbeat:  lock eliminated at ServerMonitor.RequestHeartbeat.
2. Eliminated concurrent Cluster.RapidHeartbeatTimerCallback invocations.

[EG](https://evergreen.mongodb.com/version/5ffe518e57e85a61d9f74552)

2021-01-13 03:11 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly TimeSpan _minHeartbeatInterval = __minHeartbeatIntervalDefault;
This change is to enable reflection in unittests

2021-01-14 19:28 UTC, rstam requested changes
Upon initial review this looks very reasonable.

I will review the tests later.

2021-01-14 19:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly InterlockedInt32 _heartbeatState;
This name isn't quite accurate. The intent of this field is to protect against reentrant calls of the `RapidHeartbeatTimerCallback`. 

I recommend more precise names:

        private readonly InterlockedInt32 _rapidHeartbeatTimerCallbackState;

2021-01-14 19:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            _heartbeatState = new InterlockedInt32(State.Initial);
Let's not try to reuse the existing `State` values (which are meant for a different purpose).

I propose:

            _rapidHeartbeatTimerCallbackState = new InterlockedInt32(RapidHeartbeatTimerCallbackState.NotRunning);

where the purpose specific new state class is:

        private static class RapidHeartbeatTimerCallbackState
        {
            public const int NotRunning = 0;
            public const int Running = 1;
        }

2021-01-14 19:28 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            }
What you have above seems completely correct. 

I have a preference for refactoring as:

        private void RapidHeartbeatTimerCallback(object args)
        {
            // avoid running callback reentrantly
            if (_rapidHeartbeatTimerCallbackState.TryChange(RapidHeartbeatTimerCallbackState.NotRunning, RapidHeartbeatTimerCallbackState.Running))
            {
                try
                {
                    RequestHeartbeat();
                }
                catch
                {
                    // TODO: Trace this
                    // If we don't protect this call, we could
                    // take down the app domain.
                }
                finally
                {
                    _rapidHeartbeatTimerCallbackState.TryChange(RapidHeartbeatTimerCallbackState.NotRunning);
                }
            }
        }

but if you don't like the proposed refactoring you can keep the current version (but do apply the renamings).

2021-01-14 19:28 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        }
We don't usually tack `Set` on to the end of this reflection helper method. We use the presence or absence of a value parameter to distinguish between the two overloads.

Also, `=>` works with `void` methods also, so this could be refactored as:

        public static void _minHeartbeatInterval(this Cluster cluster, TimeSpan timeSpan) => Reflector.SetFieldValue(cluster, nameof(_minHeartbeatInterval), timeSpan);

2021-01-14 23:41 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly InterlockedInt32 _heartbeatState;
c

2021-01-14 23:42 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            _heartbeatState = new InterlockedInt32(State.Initial);
Done.
Ideally we would use InterlockedEnum<T> and enums.

2021-01-14 23:42 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            }
Done

2021-01-14 23:42 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        }
Done. Good point, not clear why "Set" was used.

2021-01-15 19:36 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var serverDescriptionConnected = new ServerDescription(
Not used, will be removed.

2021-01-18 17:34 UTC, DmitryLukyanov reviewed
Initial review

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private static HashSet<ServerId> s_primaries = new HashSet<ServerId>();
we don't use abbreviation anymore. Also, static fields are prefixed by `__`

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        [Fact(Timeout = 10000)]
This is quite foggy argument which looks like not recommended anymore: https://github.com/xunit/xunit/issues/217#issuecomment-65907484 
It looks like it still work for some cases (like here), but it doesn't work for sync code paths and for example a case like this:

      [Fact(Timeout = 3000)]
        public  Task Should_convert_from_InsertRequest_to_BsonDocument()
        {
            while (true) ;
        }

Apparently, it works here, so pointing here just to pay attention on this, but I think the whole test can be rewritten without this and without below Task.Yield

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var doc = s_primaries.Contains(serverId) ? primaryDoc : secondaryDoc;
`doc`: we don't use abbreviations anymore.

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            void BlockHeartbeatRequested()
according to our agreement, we place local methods to the end of methods

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
this is unnecessary, I don't think that we need to test our test code

2021-01-18 17:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly TimeSpan _minHeartbeatInterval = __minHeartbeatIntervalDefault;
this is not required. See ClusterTests suggestions

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        public static TimeSpan _minHeartbeatInterval(this Cluster cluster) => (TimeSpan)Reflector.GetFieldValue(cluster, nameof(_minHeartbeatInterval));
this is not required

2021-01-18 17:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        public static void _minHeartbeatInterval(this Cluster cluster, TimeSpan timeSpan) => Reflector.SetFieldValue(cluster, nameof(_minHeartbeatInterval), timeSpan);
We still update just a static value. It's safe since we don't allow running tests in parallel: 

>public static void __minHeartbeatInterval(this Cluster cluster, TimeSpan timeSpan) => 
Reflector.SetStaticFieldValue(typeof(Cluster), nameof(__minHeartbeatInterval), timeSpan);

2021-01-18 17:42 UTC, rstam requested changes

2021-01-18 17:42 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            // Avoid requesting heartbeat concurrently
nit: we don't usually capitalize the first word in a comment (unless it's a doc comment that's input to the generator for the API documentation).

2021-01-18 17:42 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            _heartbeatDelay?.RequestHeartbeat();
@DmitryLukyanov we had a discussion in Slack where we determined that it IS safe to reference the `_heartbeatDelay` variable WITHOUT a `lock` even though we use a `lock` when setting it.

The conclusion is that at worst we would read the previous value rather than the current value of `_heartbeatDelay`.

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private static HashSet<ServerId> s_primaries = new HashSet<ServerId>();
`s_primaries` does not follow our naming conventions, use `__primaries` (i.e. two leading underscores for static fields).

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private static HashSet<ServerId> s_primaries = new HashSet<ServerId>();
Would a more specific name be appropriate? Perhaps `__stalledPrimaries` (not sure I fully understand how you are using this field).

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var allHeartbeatsRecieved = new TaskCompletionSource<bool>(false);
Fix typo by renaming to `allHeartbeatsReceived`

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var calledConcurrently = false;
Since we're testing reentrancy and not concurrency I recommend naming this variable `calledReentrantly`

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var selectServerTask = cluster.SelectServerAsync(CreateWritableServerAndEndPointSelector(__endPoint1), CancellationToken.None);
minor: replace `var selectServerTask` with discard variable `_` since we never use the value of `selectServerTask`?

2021-01-18 17:42 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryStalled = new TaskCompletionSource<bool>();
The word order sounds off here. Perhaps `primaryNoLongerStalled` is more grammatical?

2021-01-18 19:12 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        public static void _minHeartbeatInterval(this Cluster cluster, TimeSpan timeSpan) => Reflector.SetFieldValue(cluster, nameof(_minHeartbeatInterval), timeSpan);
This change is not related to parallelism.

2021-01-18 19:13 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly TimeSpan _minHeartbeatInterval = __minHeartbeatIntervalDefault;
I missed the case when we can update this static value and then it will affect other tests since they will use the changed value insted the default one. In this case I see that this change is required

2021-01-18 19:13 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly TimeSpan _minHeartbeatInterval = __minHeartbeatIntervalDefault;
You are right, this comment is not accurate. Should be: "This change is to enable easier and safer configuration in tests"

2021-01-18 19:32 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
Discussed offline, as I understood, the only reason why this line was added here is to cover a case if the reflection behavior will be changed in the future. Right now, this validation can be only in two states:
* Always pass
* The error will be triggered in the previous reflection steps.
So it will never fail.

But even in the case when the reflection behavior may be changed, the only disadvantage we will have is failing in line 119. I think we should not make any changes with such unreliable assumptions.

My main consern, that we should not test our test code (at least with the reason that something in dotnet will be change on some day or with assumption that we wrote test incorrectly). 
We use settings values via reflection a lot and I don't think that we need to consider such validation anywhere including here.

2021-01-18 19:40 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
I was surprised by this line also but decided to let it pass.

This line is NOT testing the driver at all. It's testing that line 105 worked.

I'd be fine with removing this line.

2021-01-18 20:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryStalled = new TaskCompletionSource<bool>();
Referring to "InvalidatedBecause:NoLongerPrimary" event handler stalling.

2021-01-18 20:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var calledConcurrently = false;
Done.

2021-01-18 20:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var selectServerTask = cluster.SelectServerAsync(CreateWritableServerAndEndPointSelector(__endPoint1), CancellationToken.None);
Done.

2021-01-18 20:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var allHeartbeatsRecieved = new TaskCompletionSource<bool>(false);
Done.

2021-01-18 20:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private static HashSet<ServerId> s_primaries = new HashSet<ServerId>();
Done.

2021-01-18 20:02 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            // Avoid requesting heartbeat concurrently
Done.

2021-01-18 20:02 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            public const int Idle = 0;
Done.

2021-01-18 20:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            void BlockHeartbeatRequested()
Done.

2021-01-18 20:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var doc = s_primaries.Contains(serverId) ? primaryDoc : secondaryDoc;
Done.

2021-01-18 20:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private static HashSet<ServerId> s_primaries = new HashSet<ServerId>();
Done.

2021-01-18 20:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
Done.

2021-01-18 20:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +;
Done.

2021-01-18 20:15 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
This code heavily relies on precise timings tuning.
In case of reflection failure, test troubleshooting would be disproportionately complicated. Therefore choosing "overtesting" approach in this case.

2021-01-18 20:21 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
>This code heavily relies on precise timings tuning.

there is no real reasons to assume that something will be wrong with reflection. We always can say that settings some important test value can be failed via dotnet bug (regardless reflection or no), but we don't test it, so I still don't see reasons to check it. For now, I see a case when someone will investigate this not simple test and will see this asserting which can make his thinking that there is an idea behind this which in turns will confuse.

2021-01-18 20:46 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                cluster._minHeartbeatInterval().Should().Be(TimeSpan.FromMilliseconds(10));
When testing a *unit* it is fair to assume that everything *outside* the unit works (whether that's reflection or anything else). If something *outside* the unit needs to be tested... then it should be tested somewhere else.

For example, in this test you *assumed* that mocking worked (as well as lots of other things).

2021-01-18 21:35 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var isMasterDoc = _currentPrimaries.Contains(serverId) ? primaryDoc : secondaryDoc;
we don't use abbreviations anymore (`doc`)

2021-01-18 21:54 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        [Fact(Timeout = 10000)]
I have no knowledge about this xUnit feature and/or its reliability.

2021-01-18 22:03 UTC, rstam requested changes

2021-01-18 22:03 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryEventStalled = new TaskCompletionSource<bool>();
I still don't understand this variable name.

Perhaps you could explain in English what this variable represents and that will either help me understand how you came up with this name, or it will help us collectively come up with a better name.

2021-01-18 22:10 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private HashSet<ServerId> _currentPrimaries;
can this be moved into the local variable? It looks like yes

2021-01-18 22:35 UTC, JamesKovacs requested changes

2021-01-18 22:35 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            _heartbeatDelay?.RequestHeartbeat();
The comment explains the what, not the why. Robert's comment better explains the why.

2021-01-18 23:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        public static TimeSpan _minHeartbeatInterval(this Cluster cluster) => (TimeSpan)Reflector.GetFieldValue(cluster, nameof(_minHeartbeatInterval));
Done

2021-01-18 23:28 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +            _heartbeatDelay?.RequestHeartbeat();
Done

2021-01-19 00:01 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryEventStalled = new TaskCompletionSource<bool>();
@BorisDog says offline that the purpose of this Task is to record that we DID stall during processing the event, not that the event IS stalled.

2021-01-19 00:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryEventStalled = new TaskCompletionSource<bool>();
Our lines length should be definitely capped.
In this case it's nearly same length as the line above, therefore I think it's appropriate usage here.

2021-01-19 00:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +        private HashSet<ServerId> _currentPrimaries;
Done

2021-01-19 00:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            int heartbeatsCount = 0, isInHeartbeat = 0;
Our lines length should be definitely capped.
In this case it's nearly same length as the line above, therefore I think it's appropriate usage here.

2021-01-19 00:07 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            int heartbeatsCount = 0, isInHeartbeat = 0;
In my opinion there is never a good reason to combine multiple declarations in one line.

And line length is definitely not one.

2021-01-19 00:07 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryEventStalled = new TaskCompletionSource<bool>();
I think your comment was meant for somewhere else.

2021-01-19 00:07 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var noLongerPrimaryEventStalled = new TaskCompletionSource<bool>();
Feel free to improve this variable name or leave it as is...

2021-01-19 00:11 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +            var allHeartbeatsReceived = new TaskCompletionSource<bool>(false);
Done

2021-01-19 00:11 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3302Tests.cs
> +                var isMasterDoc = _currentPrimaries.Contains(serverId) ? primaryDoc : secondaryDoc;
Done.

2021-01-19 00:11 UTC, DmitryLukyanov approved these changes
LGTM

2021-01-19 17:08 UTC, JamesKovacs approved these changes
LGTM

N.B. Deferring questions around testing strategy for later.

2021-01-19 17:19 UTC, rstam approved these changes
LGTM

2021-01-19 17:19 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private readonly InterlockedInt32 _rapidHeartbeatTimerCallbackState;
nit: we keep fields in alphabetical order

no need to make any changes at this late stage as we're trying to get the release out

2021-01-25 20:57 UTC, closed without merging