CSHARP-2750
mongodb/mongo-csharp-driver pull request #441
Opened 2021-01-26 20:43 UTC by BorisDog

CSHARP-2750:
- Upgrade to C# 8
- Bson and Driver solutions filters added

2021-01-26 20:43 UTC, BorisDog commented
[EG](https://evergreen.mongodb.com/version/6010593a1e2d173581aa2c01) (internal link)

2021-01-26 20:47 UTC, BorisDog commented on MongoDB.ruleset
> +    <Rule Id="CA1065" Action="Info" />
As described in [2750](https://jira.mongodb.org/browse/CSHARP-2750), CA1065 warnings are treated as errors.
Downgrading this warning to information.
This also might be solved by upgrading Microsoft.CodeAnalysis.FxCopAnalyzers version. But this can have other side effects. Also this package is deprecated. I think we should tackle this under different code analysis cleanup effort.

2021-01-28 02:35 UTC, DmitryLukyanov commented on CSharpDriver.Bson.slnf
> +{
do we really need this? I would say the best thing we can do here is to add `.slnf` into git ignore. And then if anyone will be interested in this (with any filter conditions), then he will be able to have their own version of this file. I don't feel that it's useful to have added filters under git. 

But I will be happy to hear other reviewers.

2021-01-28 02:43 UTC, rstam commented on CSharpDriver.Bson.slnf
> +{
I didn't know about this feature before, but when Boris taught me about it recently I found them really useful because they can be used to make the Test Explorer load more quickly.

I have no strong feelings whether these should or should not be in the repo.

However, I do feel they shouldn't be added as part of this PR. They have nothing to do with upgrading the language version to C# 8.

2021-01-28 02:50 UTC, DmitryLukyanov commented on MongoDB.ruleset
> +    <Rule Id="CA1065" Action="Info" />
FYI: It looks like this is a related article: https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers?view=vs-2019

But I'm ok with this change as is

2021-01-28 02:50 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <LangVersion>8</LangVersion>
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults
Looking at this:
>You should edit the project file and remove that node. Then, your project will use the compiler version recommended for your target framework.

Should we follow this recommendation?

2021-01-28 02:50 UTC, DmitryLukyanov commented on CSharpDriver.Bson.slnf
> +{
I don't see why it should be just Bson project? Why not just Core? Or just Driver? (the last two will be more useful) So, not sure that it's a good idea to place it under git. However, I don't insist on it

2021-01-28 02:50 UTC, DmitryLukyanov commented on CSharpDriver.Driver.slnf
> +}
the last line in the file should be a blank line. Then you won't see this "red circle"

2021-01-28 02:50 UTC, DmitryLukyanov commented on tests/AtlasConnectivity.Tests/AtlasConnectivity.Tests.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
I'm not sure about this line, we see this diff from time to time. If this is autoformatting change, then let's leave it, otherwise, this should be reverted

2021-01-28 20:41 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <LangVersion>8</LangVersion>
yeah, if this works in this way, then I agree that it's better to leave LangVersion

2021-01-28 22:02 UTC, BorisDog commented on MongoDB.ruleset
> +    <Rule Id="CA1065" Action="Info" />
Exactly

2021-01-28 22:11 UTC, DmitryLukyanov approved these changes
LGTM

2021-01-29 17:25 UTC, rstam requested changes
Overall this looks fine. I have two questions:

1. I thought <LangVersion> was the "old" way to specify the language version. The "new" way is to let Visual Studio automatically pick the language version based on the targeted frameworks. I would like to see some references stating that it is still OK to use <LangVersion>

2. Not all .csproj files have been changed to specify C# 9. I'm assuming this is an oversight. Either specify C# 9 for the remaining projects that don't already specify C# 9 or explain why those projects were left out of this PR

2021-01-29 18:04 UTC, BorisDog commented
@rstam 

1. Yes, as stated [here ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) we can change that value if we want to. The only side effect is that we will have only partial C# 9 features support.
2. Yes, missed 2 projects. Legacy projects where left out intentionally. As no active work is expected there we don't have any good reason to upgrade.

2021-01-29 18:15 UTC, rstam commented
> 1. Yes, as stated [here ](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) we can change that value if we want to. The only side effect is that we will have only partial C# 9 features support.

> 2. Yes, missed 2 projects. Legacy projects where left out intentionally. As no active work is expected there we don't have any good reason to upgrade.

1. Thanks for the link to the C# Language Versioning page. It does state "Choosing a language version newer than the default can cause hard to diagnose compile-time and runtime errors." so we have to stay on our toes.

2. OK. I wasn't sure whether you had chosen to not upgrade the language version from some projects or just missed them.

2021-01-29 18:16 UTC, rstam approved these changes
LGTM with the caveat that I'm relying on the analysis of others that it is OK to manually override the LangVersion and pick a version NEWER than the default.

2021-01-29 19:44 UTC, BorisDog commented
Merged.

2021-01-29 19:44 UTC, closed without merging