CSHARP-2009: Inserting correct discriminator on Upsert
mongodb/mongo-csharp-driver pull request #442
Opened 2021-01-27 17:51 UTC by BorisDog

Few differences from the original PR :

1. Original PR maintains the update object on FilteredMongoCollectionBase.cs level, while I think it is very specific to 
OfTypeMongoCollection and should be handled on that level.
2. No need to create the update object if upsert is never called.
3. SetOnInsert is only called on upsert, and not for every update. Also seems that adding SetOnInsert only on "upsert" logic naturally belongs to OfTypeMongoCollection.

2021-01-28 18:05 UTC, JamesKovacs requested changes
Looks like you're on the right track here. I tested the following program before and after this change.

Prior to the change, we upsert a C document with type discriminator of `_t: "C"`, which then returns no results when we query for documents of type B. With the change, we correctly create the C document with `_t: ["A","B","C"]` and return that document when we query for documents of type B.

I noticed one minor code fix and I think we are good to merge.

```
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;

namespace Csharp2009
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new MongoClient();
            var db = client.GetDatabase("csharp2009");
            var coll = db.GetCollection<A>("coll");
            var justTheCs = coll.OfType<C>();

            var filter = Builders<C>.Filter.Eq(x => x.Id, 42);
            var update = Builders<C>.Update.Set(x => x.Number, 99);
            var options = new UpdateOptions { IsUpsert = true };
            justTheCs.UpdateOne(filter, update, options);

            var allTheBs = coll.OfType<B>();
            foreach (var b in allTheBs.Find(Builders<B>.Filter.Empty).ToList()) {
                Console.WriteLine(b);
            }
        }
    }

    [BsonDiscriminator(RootClass = true)]
    class A {
        public int Id { get; set; }
    }
    class B : A {
        public int Number { get; set; }
    }
    class C : B {
    }
}
```

2021-01-29 01:09 UTC, BorisDog commented on src/MongoDB.Driver/OfTypeMongoCollection.cs
> +                var discriminatorValue = discriminatorConvention?.GetDiscriminator(typeof(TRootDocument), typeof(TDerivedDocument));
Done.
In PipelineStageDefinition.OfType LookupDiscriminatorConvention result is validated as well but I don't see how it can be null.

2021-01-29 17:05 UTC, jyemin commented
Added @rstam as second reviewer

2021-01-29 19:38 UTC, JamesKovacs requested changes
Overall looks good. I'm concerned with the complexity of the test methods. Consider whether update/upsert should be separated into their own test methods. Happy to discuss.

2021-01-29 19:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
Same idea here. I think it would be more readable if we moved the update and upsert tests into separate theories.

2021-01-29 19:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            public int PropA;
Nitpick... These are fields, not properties.

2021-01-29 20:07 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
We can feed rest for parameters via SerializedTypeInfos. @rstam what do you think?

2021-01-29 20:07 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +                "{$set: {x: 1}}";
Would one line look better here? cc @rstam

2021-01-29 20:10 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +                "{$set: {x: 1}}";
@BorisDog and I discussed via Slack. A single-line ternary is harder to read and changing this to an if-else is really long and verbose. Open to other suggestions though this concern would be addressed if we separated the update/upsert tests into separate test methods.

2021-01-29 22:44 UTC, rstam requested changes
I think these changes look really good. I am requesting some name changes that I hope you agree with.

While the two modified tests are more complex than we typically like to see a test be, I think they are fine as is.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
Let's be consistent on whether parameters are on one line or two.

Also, let's put the `where` constraint on a separate line so that it's more easily seen (this is one of our conventions).

In other words:

    [Theory]
    [ParameterAttributeData]
    public void BulkWrite_with_UpdateMany<TRoot, TDerived>(
        [ClassValues(typeof(UpdateTestCases))] (TRoot, TDerived, string Discriminator) testCase,
        [Values(false, true)] bool isUpsert,
        [Values(false, true)] bool async)
            where TDerived : TRoot

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [ClassValues(typeof(SerializedTypeInfos))]
I would like to rename `SerializedTypeInfos` to `UpdateTestCases` and rename the `typeInfo` parameter to `testCase`.

I think those names are more accurate.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var (derivedCollectionMock, ofTypeCollection) = CreateSubject<TRoot, TDerived>();
I'm fine with this type of assignment in general.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var (derivedCollectionMock, ofTypeCollection) = CreateSubject<TRoot, TDerived>();
I would like to rename `derivedCollectionMock` to `mockDerivedCollection`

and to rename `ofTypeCollection` to `subject`

Just about every unit test should have a variable named `subject`.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +        private (Mock<IMongoCollection<TDerived>> Derived, OfTypeMongoCollection<TRoot, TDerived> OfType) CreateSubject<TRoot, TDerived>()
Rename `Derived` to `MockDerivedCollection` and rename `OfType` to `Subject`

    private (Mock<IMongoCollection<TDerived>> MockDerivedCollection, OfTypeMongoCollection<TRoot, TDerived> Subject) CreateSubject<TRoot, TDerived>()

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var mockRootCollectionMock = new Mock<IMongoCollection<TRoot>>();
Rename to `mockRootCollection`

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var mockDerivedCollectionMock = new Mock<IMongoCollection<TDerived>>();
Rename to `mockDerivedCollection`

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var ofTypeCollection = new OfTypeMongoCollection<TRoot, TDerived>(mockRootCollectionMock.Object, mockDerivedCollectionMock.Object, _ofTypeFilter);
Rename `ofTypeCollection` to `subject`

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +        public class A_Discriminated
Rename `A_Discriminated` to `AHierarchical` and same for the B and C versions.

The key difference between `A` and `AHierarchical` is NOT whether it's discriminated or not (in these tests BOTH are discriminated) but rather that `A` etc..  uses a scalar discriminator and `AHierchical` etc.. uses a hierarchical (i.e. array) discriminator.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +                "{$set: {x: 1}}";
I'm willing to let this one slide. If you want to rewrite it you can.

2021-01-29 22:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
I think `SerializedTypeInfos` is fine as is, though I have asked for it to be renamed to `UpdateTestCases`.

2021-01-29 23:24 UTC, BorisDog commented on src/MongoDB.Driver/FilteredMongoCollectionBase.cs
> +        protected virtual UpdateDefinition<TDocument> GetUpdateDefinition(UpdateDefinition<TDocument> updateDefinition, bool isUpsert)
Tnx, changed to AdjustUpdateDefinition.

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [ClassValues(typeof(SerializedTypeInfos))]
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var (derivedCollectionMock, ofTypeCollection) = CreateSubject<TRoot, TDerived>();
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +                "{$set: {x: 1}}";
Left as is.

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +        private (Mock<IMongoCollection<TDerived>> Derived, OfTypeMongoCollection<TRoot, TDerived> OfType) CreateSubject<TRoot, TDerived>()
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var mockRootCollectionMock = new Mock<IMongoCollection<TRoot>>();
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var mockDerivedCollectionMock = new Mock<IMongoCollection<TDerived>>();
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            var ofTypeCollection = new OfTypeMongoCollection<TRoot, TDerived>(mockRootCollectionMock.Object, mockDerivedCollectionMock.Object, _ofTypeFilter);
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +        public class A_Discriminated
Done

2021-01-29 23:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/OfTypeMongoCollectionTests.cs
> +            [Values(false, true)] bool async) where TDerived : TRoot
Renamed

2021-01-29 23:24 UTC, BorisDog commented on src/MongoDB.Driver/OfTypeMongoCollection.cs
> +                var derivedUpdate = builder.SetOnInsert(discriminatorConvention.ElementName, discriminatorValue);
Done

2021-02-02 20:13 UTC, JamesKovacs approved these changes
LGTM

2021-02-02 22:23 UTC, BorisDog commented
Merged.

2021-02-02 22:23 UTC, closed without merging