CSHARP-3281: Versioned MongoDB API for Drivers
mongodb/mongo-csharp-driver pull request #444
Opened 2021-01-29 00:24 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3281
Evergreen: https://evergreen.mongodb.com/version/60132c31d6d80a26748418e7
Specification: https://github.com/mongodb/specifications/blob/master/source/versioned-api/versioned-api.rst

2021-01-29 15:34 UTC, jyemin commented
Added Dmitry as first reviewer, Robert as second.

2021-02-01 16:57 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-02-01 16:57 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            protected override string[] PathPrefixes => new[]
`versioned API` tests mostly reside in a different folder. I was deciding between adding a path to `unified tests` runner or creating an additional test runner for versioned API tests similar to `UnifiedTestFormatNegativeTestRunner` and decided to go with the first option, but that can be altered.

2021-02-05 15:24 UTC, DmitryLukyanov requested changes
NOTE: I didn't look at tests yet

2021-02-05 15:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerFactory.cs
> +        public ServerFactory(
I would say, the driver changes should be the first priority, how big changes in the tests should be a secondary question

2021-02-05 15:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +        public CommandWireProtocol(
similar to the above, the number of changes in the tests is a secondary question

2021-02-05 15:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/IAuthenticator.cs
> +        void Authenticate(IConnection connection, ConnectionDescription description, ServerApi serverApi, CancellationToken cancellationToken);
this is a BC. See this commit with a suggestion on how to avoid this: https://github.com/DmitryLukyanov/mongo-csharp-driver/commit/0fe4d7e027cf03e34e191e2048cf98709a4b6cff

2021-02-05 15:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/ServerApi.cs
> +        public ServerApi(ServerApiVersion version, bool? strict = null, bool? deprecatationErrors = null)
it's probably should be:

        public ServerApi(ServerApiVersion version, Optional<bool> strict = default, Optional<bool> deprecatationErrors = default)
        {
            _version = Ensure.IsNotNull(version, nameof(version));
            _strict = strict.WithDefault(false);
            _deprecatationErrors = deprecatationErrors.WithDefault(false);
        }

2021-02-12 01:44 UTC, MikalaiMazurenka reviewed
Ready for reivew!

2021-02-12 01:44 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Legacy/MongoServerSettings.cs
> +        /// <summary>
Great catch!
Done.

2021-02-12 01:44 UTC, MikalaiMazurenka commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        /// Gets or sets the server api.
Nice find!
Done.

2021-02-12 01:44 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        public static BsonDocument GetServerParameters()
Nope. The property shouldn't do any requests or complex things ([Choosing Between Properties and Methods](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229054(v=vs.100)) or [Property Usage Guidelines: Properties vs. Methods](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/bzwdh01d(v=vs.71)#properties-vs-methods))

2021-02-12 01:44 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            using (var binding = CreateReadBinding(session))
There's no existing session to fork (and I see no point in forking just created session) and btw the method just above (`GetModules()`) uses the same exact code. Unless I'm missing something

2021-02-12 01:44 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +            RequireServer.Check().VersionGreaterThanOrEqualTo("3.6").ClusterTypes(ClusterType.ReplicaSet, ClusterType.Sharded);
Nice find!
It seems I just blindly copypasted the check from above method. My bad.
Done.

2021-02-12 01:44 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Legacy.Tests/MongoServerSettingsTests.cs
> +            settings.ServerApi = new ServerApi(ServerApiVersion.V1, true, true);
Good point!
Done.

2021-02-12 19:48 UTC, DmitryLukyanov reviewed
Some comments and then it will LGTM

2021-02-12 19:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
can query/command wire protocol be just a new Values argument (similar in other places)?

2021-02-12 19:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
I would prefer a new testing way here, but I will defer it to you

2021-02-12 19:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +        public void Command_should_use_serverApi()
async?

2021-02-12 19:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Throws<InvalidOperationException>(() => { settings.ServerApi = serverApi; });
let's avoid using an old testing format. I understand that probably this was copied from somewhere, but it's quite a small test to change it

2021-02-12 19:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            if (schemaSemanticVersion < new SemanticVersion(1, 0, 0) ||
should it be placed into RequireServer or similar?

2021-02-12 19:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoDBCRAuthenticator.cs
> +        private CommandWireProtocol<BsonDocument> CreateAuthenticateProtocol(BsonDocument getNonceReply, ServerApi serverApi)
nit: technically this is not required since we have a local `_serverApi`, I would use it in the same way everywhere, check similar issues

2021-02-15 16:52 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-02-15 16:52 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        public Server(
Missed this one.
Done

2021-02-15 16:52 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/ServerApi.cs
> +    /// Represents a server api.
Missed one. Good catch!
Done

2021-02-15 16:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
I've already tried that and it makes test less readable because of the number of `if` `else` clauses. So potentially yes, but I'd avoid that.

2021-02-15 16:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
I stick to existing format in the file.

2021-02-15 16:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +        public void Command_should_use_serverApi()
Great catch!
Done

2021-02-15 16:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Throws<InvalidOperationException>(() => { settings.ServerApi = serverApi; });
I merely use existing file format.

2021-02-15 16:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            if (schemaSemanticVersion < new SemanticVersion(1, 0, 0) ||
No. Since it is not an attribute of environment but of an implementation.

2021-02-15 16:52 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +        public GssapiAuthenticator(
Done.
Updated all authenticators except for default.

2021-02-15 17:12 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoDBCRAuthenticator.cs
> +        private CommandWireProtocol<BsonDocument> CreateAuthenticateProtocol(BsonDocument getNonceReply, ServerApi serverApi)
I would say that it's better to use the same approach everywhere, for example, you don't use this mechanic for `_credential`. And even more, with your suggestion, you will need to pass all global variables through all call stack which doesn't look right and we definitely don't do this in other places. If you strongly feel that your approach is better, I will rely on you and @rstam here

2021-02-15 17:14 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            if (schemaSemanticVersion < new SemanticVersion(1, 0, 0) ||
yeah, got it, thanks

2021-02-15 17:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Throws<InvalidOperationException>(() => { settings.ServerApi = serverApi; });
it depends on which test you took for example, in this file, there are two approached. The general rule, use a new approach for new tests

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                            cancellationToken).GetAwaiter().GetResult();
expected formatting here:

                        channel.CommandAsync(
                           ...
                            cancellationToken)
                        .GetAwaiter()
                        .GetResult();

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
this file contains different formats

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
And actually, I missed that you mix them. Then, I think you should choose the latest one

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
Not sure that making a full copy of these test (except some input/assert arguments) makes these tests more clear. Consider this refactoring:

        [Theory]
        [ParameterAttributeData]
        public void Authenticate_should_send_serverApi(
            [Values(false, true)] bool useServerApi,
            [Values(false, true)] bool useQueryProtocol,
            [Values(false, true)] bool async)
        {
            var dateTime = DateTime.UtcNow;
            var clientNonce = __randomByteGenerator.Generate(ClientNonceLength);
            var serverNonce = Combine(clientNonce, __randomByteGenerator.Generate(ClientNonceLength));
            var host = "sts.amazonaws.com";
            var credential = new UsernamePasswordCredential("$external", "permanentuser", "FAKEFAKEFAKEFAKEFAKEfakefakefakefakefake");
            var serverApi = useServerApi ? new ServerApi(ServerApiVersion.V1, true, true) : null;

            AwsSignatureVersion4.CreateAuthorizationRequest(
                dateTime,
                credential.Username,
                credential.Password,
                null,
                serverNonce,
                host,
                out var authHeader,
                out var timestamp);

            var mockClock = new Mock<IClock>();
            mockClock.Setup(x => x.UtcNow).Returns(dateTime);

            var mockRandomByteGenerator = new Mock<IRandomByteGenerator>();
            mockRandomByteGenerator.Setup(x => x.Generate(It.IsAny<int>())).Returns(clientNonce);

            var expectedClientFirstMessage = new BsonDocument
            {
                { "r", clientNonce },
                { "p", (int)'n' }
            };
            var expectedClientSecondMessage = new BsonDocument
            {
                { "a", authHeader },
                { "d", timestamp }
            };
            var serverFirstMessage = new BsonDocument
            {
                { "s", serverNonce },
                { "h", host }
            };

            var saslStartReplyString = $"{{ conversationId : 1, done : false, payload : BinData(0,\"{ToBase64(serverFirstMessage.ToBson())}\"), ok : 1 }}";
            var saslContinueReplyString = "{ conversationId : 1, done : true, payload : BinData(0,\"\"), ok : 1}";

            var subject = new MongoAWSAuthenticator(credential, null, mockRandomByteGenerator.Object, mockClock.Object, serverApi);

            var connection = new MockConnection(__serverId);
            connection.Description = ConfigureConnection();

            if (async)
            {
                subject.AuthenticateAsync(connection, connection.Description, CancellationToken.None).GetAwaiter().GetResult();
            }
            else
            {
                subject.Authenticate(connection, connection.Description, CancellationToken.None);
            }

            SpinWait.SpinUntil(() => connection.GetSentMessages().Count >= 2, TimeSpan.FromSeconds(5)).Should().BeTrue();

            var sentMessages = MessageHelper.TranslateMessagesToBsonDocuments(connection.GetSentMessages());
            sentMessages.Count.Should().Be(2);

            var actualRequestId0 = sentMessages[0]["requestId"].AsInt32;
            var actualRequestId1 = sentMessages[1]["requestId"].AsInt32;

            var expectedMessages = GetExpectedMessages();
            sentMessages[0].Should().Be(expectedMessages.ExpectedStartMessage);
            sentMessages[1].Should().Be(expectedMessages.ExpectedContinueMessage);

            ConnectionDescription ConfigureConnection()
            {
                if (useQueryProtocol)
                {
                    var saslStartReply = MessageHelper.BuildReply(RawBsonDocumentHelper.FromJson(saslStartReplyString));
                    var saslContinueReply = MessageHelper.BuildReply(RawBsonDocumentHelper.FromJson(saslContinueReplyString));
                    connection.EnqueueReplyMessage(saslStartReply);
                    connection.EnqueueReplyMessage(saslContinueReply);
                    return __descriptionQueryWireProtocol;
                }
                else
                {
                    var saslStartResponse = MessageHelper.BuildCommandResponse(RawBsonDocumentHelper.FromJson(saslStartReplyString));
                    var saslContinueResponse = MessageHelper.BuildCommandResponse(RawBsonDocumentHelper.FromJson(saslContinueReplyString));
                    connection.EnqueueCommandResponseMessage(saslStartResponse);
                    connection.EnqueueCommandResponseMessage(saslContinueResponse);
                    return __descriptionCommandWireProtocol;
                }
            }

            (string ExpectedStartMessage, string ExpectedContinueMessage) GetExpectedMessages()
            {
                var expectedServerApiString = useServerApi ? ", apiVersion : \"1\", apiStrict : true, apiDeprecationErrors : true" : "";
                string expectedFirstMessage;
                string expectedSecondMessage;
                if (useQueryProtocol)
                {
                    expectedFirstMessage = GetExpectedSaslStartQueryMessage(actualRequestId0, expectedClientFirstMessage, expectedServerApiString);
                    expectedSecondMessage = GetExpectedSaslContinueQueryMessage(actualRequestId1, expectedClientSecondMessage, expectedServerApiString);
                }
                else
                {
                    expectedFirstMessage = GetExpectedSaslStartCommandMessage(actualRequestId0, expectedClientFirstMessage, expectedServerApiString);
                    expectedSecondMessage = GetExpectedSaslContinueCommandMessage(actualRequestId1, expectedClientSecondMessage, expectedServerApiString);
                }
                return (expectedFirstMessage, expectedSecondMessage);
            }
        }

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
NOTE: I think all logic from here: `ConfigureConnection` can be moved into `MessageHelper` like:

    MessageHelper.BuildResponse<ReplyMessage>(...)
    MessageHelper.BuildResponse<CommandResponseMessage>(...)

and we can decide which message should be processed based on the T argument

2021-02-15 17:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +            act.ShouldNotThrow();
this is not necessary, since we can take (and do it in other places) the fact that the test hasn't failed as the flag that nothing was failed :)

2021-02-15 21:48 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-02-15 21:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
Conditional asserts in unit tests are harder to maintain and understand. I would like to hear @rstam opinion on this before implementing these changes.

2021-02-15 21:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +            act.ShouldNotThrow();
I removed it here and in similar places.
Done.

2021-02-15 21:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
This file contains one format, which I am using.

2021-02-15 21:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                            cancellationToken).GetAwaiter().GetResult();
Done

2021-02-15 21:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Throws<InvalidOperationException>(() => { settings.ServerApi = serverApi; });
All of the tests which assert a particular option of `MongoClientSettings` use `Assert.Equal` format which I am using. Mixing the formats will reduce readability.

2021-02-15 22:52 UTC, rstam requested changes
Reviewed it rapidly and looks good initially.

I will review once more a little more carefully once someone else has given it the first approval.

2021-02-15 22:52 UTC, rstam commented on src/MongoDB.Driver.Core/ServerApi.cs
> +        private readonly bool? _deprecatationErrors;
Fix typo in field name, should be:

    _deprecationErrors

Make sure it's fixed everywhere.

2021-02-15 23:16 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-02-15 23:16 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/ServerApi.cs
> +        private readonly bool? _deprecatationErrors;
Fixed this typo everywhere.
Done

2021-02-15 23:16 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +                act = () => subject.AuthenticateAsync(connection, __descriptionQueryWireProtocol, CancellationToken.None).GetAwaiter().GetResult();
Switched new tests to new format.
Done.

2021-02-15 23:16 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> +            Assert.Throws<InvalidOperationException>(() => { settings.ServerApi = serverApi; });
Switched new tests to new format.
Done.

2021-02-15 23:27 UTC, DmitryLukyanov approved these changes
Some typo fix and then LGTM
@rstam, there are a few comments where you're mentioned, it would be good to hear your opinion there

2021-02-15 23:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                    if (async)
should be inverted

2021-02-16 00:29 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                    if (async)
Done

2021-02-17 18:45 UTC, rstam requested changes
Possible changes? Not sure. See comments.

2021-02-17 18:45 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +            : this(credential, new DefaultRandomStringGenerator(), serverApi: null)
Why not remove this constructor?

Seems like defaulting `serverApi` to `null` makes it too easy to forget to call the constructor that takes an explicit `serverApi` value (which might be `null` of course).

Same for all other places where you default `serverApi: null`.

2021-02-17 18:45 UTC, rstam commented on src/MongoDB.Driver.Core/ServerApi.cs
> +        public ServerApi(ServerApiVersion version, Optional<bool?> strict = default(Optional<bool?>), Optional<bool?> deprecationErrors = default(Optional<bool?>))
This can be shortened to:

    public ServerApi(ServerApiVersion version, Optional<bool?> strict = default, Optional<bool?> deprecationErrors = default)

2021-02-17 18:46 UTC, rstam commented
@DmitryLukyanov I did not review the tests. I'm assuming you did.

2021-02-17 19:03 UTC, MikalaiMazurenka reviewed
Ready for review!
@rstam could you please check the comments where you mentioned to help with decisions.

2021-02-17 19:11 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                if (commandName == "getMore")
I don't have a better solution either.

2021-02-17 19:12 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_command_wire_protocol(
Agreed that the simpler the test is the better.

I defer to you two what's simplest here.

2021-02-17 19:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/MongoDBCRAuthenticator.cs
> +        private CommandWireProtocol<BsonDocument> CreateAuthenticateProtocol(BsonDocument getNonceReply, ServerApi serverApi)
> It is generally preferable to explicitly specify local parameters whenever possible which increases readability and reusability of code.

Maybe, but when I see this parameter it seems like the reason for adding it is because you want to pass in an arbitrary value. If you always pass in `_serverApi` then having it as a parameter here seems redundant (and even confusing because it implies the wrong thing).

2021-02-17 19:19 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +            : this(credential, new DefaultRandomStringGenerator(), serverApi: null)
Yes of course I understand the goal of non-breaking.

But this isn't a class an application would ever call... and leaving the old constructor in place makes it easy to forget to pass the `serverApi` which would be a bug now.

I leave it up to you (and maybe @DmitryLukyanov could comment also) whether you want to prioritize backward compatibility (in a class an application wouldn't ever use) or safety.

2021-02-17 19:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +            : this(credential, new DefaultRandomStringGenerator(), serverApi: null)
Let's make old ctors obsolete?

2021-03-02 12:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            protected override string[] PathPrefixes => new[]
I checked how it looks on different tickets. I think we should create a new test unified runner for each ticket, like a new CrudUnifiedTestRunner and so on, that will use this test runner inside.

2021-03-02 12:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            protected override string[] PathPrefixes => new[]
nit: Also, it looks like this factory (together with ClassData method) also should be moved from this class into a new one. And after all, you will have one common class(without mentions of particular tests) which you will reuse everywhere, and also two specific test runners for `unified` logic. I think this is out of scope for your PR, so see whether you want to work on it now or no

2021-03-02 15:35 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-03-02 15:35 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            protected override string[] PathPrefixes => new[]
Moved `versioned-api` tests into separate test runner. Further improvements require too many changes, so should be made in scope of a dedicated story.

2021-03-02 22:59 UTC, rstam approved these changes
LGTM

2021-03-03 17:19 UTC, merged