CSHARP-3321: Sharing a MongoClient for metadata lookup can lead to deadlock in drivers using automatic encryption.
mongodb/mongo-csharp-driver pull request #446
Opened 2021-01-29 22:44 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/60148e575623433e9c236559

2021-01-29 23:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            internalClientMongoSettings.ClusterConfigurator = null;
not sure that this line is required and safe. The current test design doesn't call this method, so in theory, we can remove this line (without affecting tets), but if anyone will configure ClusterConfigurator, he won't be able to reuse internalClient, if he creates more than one parent mongo client, however leaving this line as is can also be dangerous.

2021-01-29 23:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            internalClientMongoSettings.ClusterConfigurator = null;
So, probably this should be removed, and maybe instead we can document this somewhere, but I would like to use another set of eyes here before.

2021-01-29 23:13 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                    internalMongoClient ??
this client is added to have control over the used client here, in particular, to be able to dispose of the internal client after each test. Otherwise, after a big enough number of launched tests, the tests become really slow down and, finally, starts to fail

2021-01-29 23:49 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
I will add isNotNull validation here in the next commit

2021-02-01 18:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                        AddDisposable(disposableMongoClient);
the used client will be disposed after each test

2021-02-01 18:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +            internalClientMongoSettings.AutoEncryptionOptions = null;
this logic can be moved into a separate static method, then we will be able to reuse it on the tests side

2021-02-01 18:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                return new Mock<DisposableMongoClient>(new MongoClient(internalClientMongoSettings))
in the current test implementation, we create an internal client on the test side all the time regardless we will use this client in the driver or no. So, the way with events doesn't really work for us. But mocking helps with this :)

2021-02-02 00:23 UTC, rstam requested changes
I was having a real hard time trying to convince myself these changes were correct and how to reconcile them with what the spec said.

Would you please consider an alternate approach prototyped here:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3321-mongoclientapproach

The main points of this alternate approach are:

1. Let MongoClient create and own the internal client just like the spec says
2. Modify DisposableMongoClient to automatically clean up the cluster for the internal client (if any)

Note: the somewhat awkard use of an internal interface is because C# does not let you define internal members of an interface. The entire interface has to be either public or internal.

Let me know what you think. Thanks!

2021-02-02 21:51 UTC, rstam commented
While I have no concerns in principle about `MongoClient` creating and owning the internal client, I do appreciate your concerns about the `IMongoClientInternal` interface approach. It's a limitation of the C# language that we can't add internal methods to an interface, so there is no less awkward way to add internal methods to `IMongoClient`.

I would be OK I guess with your suggestion that `AutoEncryptionLibMongoCryptController` be the one to create and own the internal client. Since `MongoClient` has at most one instance of an `AutoEncryptionLibMongoCryptController`, letting the controller create and own the internal client is the same as letting `MongoClient` create and own the internal client just with one level of indirection.

I refactored my first `MongoClient` based proposal to move the creation and owning of the internal client to `AutoEncryptionLibMongoCryptController` and came up with:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3321-controllerapproach

Take a look and see what you think. With these changes it's much closer to what you have proposed, but with some differences that I do consider important:

* no changes to the `AutoEncryptionLibMongoCryptController` constructor parameters
* delay creation of the internal client until it is first needed
* don't pass in an internal client from tests , let the driver create the internal client as it normally would
* so therefore no changes to `AutoEncryptionOptions` (no `InternalClient` property)
* let `DisposableMongoClient` clean up the internal client also 

I haven't made any changes to the tests. I assume they would need to be refactored also.

2021-02-02 21:56 UTC, jyemin commented
> delay creation of the internal client until it is first needed

I'm not sure I agree that this is important.  If an application is configuring client-side encryption, they are almost certainly going to need the internal client, so is there benefit in delaying creation?

2021-02-02 21:57 UTC, DmitryLukyanov commented
NOTE: I'm almost finished refactoring my previous version with taking Robert's suggestions into account, I need just to check the prose tests

2021-02-02 23:15 UTC, rstam commented
>> delay creation of the internal client until it is first needed

> I'm not sure I agree that this is important. If an application is configuring client-side encryption, they are almost certainly going to need the internal client, so is there benefit in delaying creation?

You have a good point. The subtle issue is that the `AutoEncryptionLibMongoCryptController` is created from the `MongoClient` constructor. That means that the `client` passed in to the `AutoEncryptionLibMongoCryptController` is NOT yet fully constructed and initialized and cannot yet be used.

However, to create the internal client we only need to access the `Settings` of the `MongoClient`, and that should be safe as long as the `_settings` field of `MongoClient` is initialized before the `AutoEncryptionLibMongoCryptController` constructor is called.

So while delaying creating the internal client is 100% safe, creating it up front should also be safe if we are careful.

2021-02-02 23:30 UTC, rstam commented
The latest commit of my branch:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3321-controllerapproach

shows what it would look like if we don't delay creating the internal client.

2021-02-02 23:39 UTC, DmitryLukyanov commented
> 
> 
> While I have no concerns in principle about `MongoClient` creating and owning the internal client, I do appreciate your concerns about the `IMongoClientInternal` interface approach. It's a limitation of the C# language that we can't add internal methods to an interface, so there is no less awkward way to add internal methods to `IMongoClient`.
> 
> I would be OK I guess with your suggestion that `AutoEncryptionLibMongoCryptController` be the one to create and own the internal client. Since `MongoClient` has at most one instance of an `AutoEncryptionLibMongoCryptController`, letting the controller create and own the internal client is the same as letting `MongoClient` create and own the internal client just with one level of indirection.
> 
> I refactored my first `MongoClient` based proposal to move the creation and owning of the internal client to `AutoEncryptionLibMongoCryptController` and came up with:
> 
> https://github.com/rstam/mongo-csharp-driver/tree/csharp3321-controllerapproach
> 
> Take a look and see what you think. With these changes it's much closer to what you have proposed, but with some differences that I do consider important:
> 
>     * no changes to the `AutoEncryptionLibMongoCryptController` constructor parameters
> 
>     * delay creation of the internal client until it is first needed
> 
>     * don't pass in an internal client from tests , let the driver create the internal client as it normally would
> 
>     * so therefore no changes to `AutoEncryptionOptions` (no `InternalClient` property)
> 
>     * let `DisposableMongoClient` clean up the internal client also
> 
> 
> I haven't made any changes to the tests. I assume they would need to be refactored also.

> * no changes to the `AutoEncryptionLibMongoCryptController` constructor parameters

why? I think I can rewrite code without this, but it will take time and I don't see any benefits with this yet.

> delay creation of the internal client until it is first needed

this will always be done in this way with the exception of tests, but in the current version it's true for all case

>* don't pass in an internal client from tests , let the driver create the internal client as it normally would

done

>* so therefore no changes to `AutoEncryptionOptions` (no `InternalClient` property)

done

> * let `DisposableMongoClient` clean up the internal client also

It could be done as you suggested, but I would not do it. With your suggestion, we move the FLE specific details into the Dispose level which is just a wrapper for a client. The problem here is related to the fact that we have a "gap" in the disposing approaches, in particular, I mean that MongoClient and, in turns, FLE auto controller don't implement IDisposable interface, so we actually have no control over this. So since we cannot fix it, I would not create any specific workaround and instead fix it on the particular test level (when it matters)

>delay creation of the internal client until it is first needed

this is how it's defined in the spec: https://github.com/mongodb/specifications/commit/947be4cf82a8e44f1589d5ac19413d06ebc11e9d#diff-de01d398114f63480af23798e09ffca599aa758efd04f15a9beec89b4566041bR311

2021-02-02 23:42 UTC, DmitryLukyanov commented
@rstam , please check the latest commit

2021-02-02 23:43 UTC, rstam commented
>> no changes to the AutoEncryptionLibMongoCryptController constructor parameters
> why? I think I can rewrite code without this, but it will take time and I don't see any benefits with this yet.

Why? Because the changes you made to how an `AutoEncryptionLibMongoCryptController` is created are unnecessarily complicated (all the static methods).

As for rewriting, did you look at my branch? It already has the proposed simpler changes.

2021-02-03 14:51 UTC, DmitryLukyanov commented
ready for review: https://evergreen.mongodb.com/version/601ab85d0305b905dce46f48

2021-02-03 15:31 UTC, rstam requested changes

2021-02-03 15:31 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                internalClient);
The proposed change was:

    return new AutoEncryptionLibMongoCryptController(
        internalClient,
        keyVaultClient,
        metadataClient,
        cryptClient,
        autoEncryptionOptions);

Why did you arbitrarily move the `internalClient` parameter to the end?

We could discuss the order of the three client parameters, but certainly we should keep them together.

2021-02-03 15:31 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        private readonly IMongoClient _metadataClient;
Keep fields in alphabetical order.

2021-02-03 15:31 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// </summary>
This comment is superfluous.

2021-02-03 15:31 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        internal IMongoClient InternalClient => _internalClient;
`public` would have been fine because the whole class is `internal`.

2021-02-03 15:31 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                  Ensure.IsNotNull(keyVaultClient, nameof(keyVaultClient)),
`keyVault` will never be null.

But you can keep this validation if you want to.

2021-02-03 15:31 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            // so we need to add this workaround to force disposing of some internal resources
This comment is misleading. Please remove it.

To the extent that it is true it applies to the whole class and not just to the lines below.

2021-02-03 15:31 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            // so we need to add this workaround to force disposing of some internal resources
`DisposableMongoClient` is a class used in `Tests` **only** to close down the `Cluster` associated with the `MongoClient`.

Before there was always exactly one `Cluster` owned by the `MongoClient`. Now there **might** be two.

2021-02-03 15:32 UTC, rstam commented
Note: I have not yet started reviewing the tests because we were still working through the implementation itself.

2021-02-03 16:28 UTC, rstam requested changes
Will review the tests when we are done working through the pending change requests.

2021-02-03 16:28 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                  Ensure.IsNotNull(keyVaultClient, nameof(keyVaultClient)),
No problem

2021-02-03 16:28 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// </summary>
The property may not otherwise be needed, but the `_internalClient` field definitely is (If `MongoClient` and this class was `IDisposable` the `Dispose` method would need to use the `_internalClient` field to `Dispose` the internal client).

2021-02-03 16:28 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// </summary>
One of my objections to your comment is the judgmental tone.

Let's simplify to:

    // this property is used by DisposableMongoClient.Dispose to unregister the internal cluster

2021-02-03 16:28 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        internal IMongoClient InternalClient => _internalClient;
If you insist. It is not common to use `internal` properties when the whole class is `internal`.

2021-02-03 16:28 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            // so we need to add this workaround to force disposing of some internal resources
I think you missed my main point: these comments do NOT apply to just the lines below.

Any comments you might add apply to the `DisposableMongoClient` class as a whole.

2021-02-03 16:28 UTC, rstam commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            // so we need to add this workaround to force disposing of some internal resources
If you feel the need to add some sort of comment add the following to the class:

    // This class is used in tests to close down the MongoClient cluster (and also the cluster for the internal MongoClient if there is one)

but please remove the comments on lines 240-241

2021-02-03 16:28 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            _internalClient = internalClient; // can be null
Move to between 73-74. It is good to use the parameters in the order they appear in the method signature.

2021-02-03 16:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            _internalClient = internalClient; // can be null
done

2021-02-03 16:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// </summary>
done

2021-02-03 16:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            // so we need to add this workaround to force disposing of some internal resources
np, done.

>I think you missed my main point: these comments do NOT apply to just the lines below.

I didn't miss this, I just said that the original intention is not clear from the code itself. So, I'm ok to add this comment to the whole class

2021-02-03 18:26 UTC, rstam reviewed
Resolved some comments.

2021-02-03 18:26 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
It's usually not necessary to add this kind of validation in private methods.

If we are the only ones calling this method we can make sure that it is not called when `_metadataClient` is null.

You can leave this if you want... but let's not be tempted to start adding argument validation to all our private methods.

For public methods of course we have to validate arguments.

2021-02-03 18:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
we don't have control over when this method will be called since it's up to the libmongocrypt level logic. And we definitely can have null in the metadataClient. So, it's about preventing a null reference exception in case if something will be changed on the C level. So, I would say in this particular case it's required.

2021-02-03 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
but I agree that this should not be a common rule

2021-02-03 19:13 UTC, rstam commented
@MikalaiMazurenka I've reviewed the driver changes but not the tests. The driver changes currently look OK to me.

You can be first reviewer on the tests. I'll do a second review of the tests once you are done.

2021-02-03 19:26 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
We do know whether this method will be called or not. If `AutoEncryptionOptions.BypassAutoEncryption` is `true` then we know that this method is never called.

That's precisely why we set `_metadataClient` to `null` when we know it won't be needed.

2021-02-03 19:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
>We do know whether this method will be called or not. If AutoEncryptionOptions.BypassAutoEncryption is true then we know that this method is never called.

if there is no bug in the C level, then yes, but we don't have control over this. It can be changed at any moment, we can have a bug in this logic even now, and we may not see this just because it happens only in some circumstances

2021-02-03 19:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
I don't say that this is expected, but I do say that libmongocrypt is an external library for the driver and it's better to validate their "output"

2021-02-03 19:45 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
`_metadataClient` is not output of the libmongocrypt library.

We create it ourselves (unless `AutoEncryptionOptions.BypassAutoEncryption` is `true`).

As I understand it the C level can't call us back unless we call it first (which we won't do if `BypassAutoEncryption` is `true`).

Anyway... if you feel better with this `Ensure` here I'm still OK with you leaving it.

2021-02-03 19:47 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
Note: `Ensure` is used for validating arguments... and therefore throws an `ArgumentNullException` here. But `_metadataClient` is not an argument, it's part of the object state.

Perhaps you should manually check for null and throw an `InvalidOperationException` instead.

2021-02-03 19:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
the C level can potentially call this method even in decrypt steps, so in that case, this value will be null

2021-02-03 19:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
>Perhaps you should manually check for null and throw an InvalidOperationException instead.

yeah, I also thought about this, I will do it

2021-02-03 19:49 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
> the C level can potentially call this method even in decrypt steps, so in that case, this value will be null

Are you sure?

If that's true then why are we setting `_metadataClient` to `null` when `BypassAutoEncryption` is `true`?

2021-02-03 19:51 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
I meant that it may be if there is a bug on the C level (with "routing"). But it's not expected according to the spec

2021-02-08 14:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            var database = _metadataClient.GetDatabase(databaseName);
>>    Perhaps you should manually check for null and throw an InvalidOperationException instead.

>yeah, I also thought about this, I will do it

done

2021-02-10 15:51 UTC, MikalaiMazurenka requested changes
Great encryption tests refactoring!
A have a few minor suggestions on the deadlock prose tests.

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        externalKeyVaultClient: GetKeyVaultMongoClientByKey()))
Local method `GetKeyVaultMongoClientByKey` is redundant. Consider:
```suggestion
                        externalKeyVaultClient: keyVaultMongoClientKey == "client_keyvault" ? client_keyvault : null))
```

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            }
Alternative if you apply tuple suggestion below:
```suggestion
            void AssertEvents(IEnumerable<CommandStartedEvent> events, (string CommandName, string DatabaseName)[] expectedEventsDetails)
            {
                for (int i = 0; i < expectedEventsDetails.Length; i++)
                {
                    var expectedEventDetails = expectedEventsDetails[i];
                    var @event = events.ElementAt(i);
                    @event.DatabaseNamespace.DatabaseName.Should().Be(expectedEventDetails.DatabaseName);
                    @event.CommandName.Should().Be(expectedEventDetails.CommandName);
                }
                events.Count().Should().Be(expectedEventsDetails.Count());
            }
```

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                    },
Alternative if you apply tuple suggestion below:
```suggestion
                    new[]
                    {
                        ("listCollections", "db"),
                        ("find", "keyvault"),
                        ("insert", "db"),
                        ("find", "db")
                    },
```

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                string[] clientKeyVaultEventsExpectation)
Instead of splitting strings you can use tuples here:
```suggestion
                (string, string)[] clientEncryptedEventsExpectation,
                (string, string)[] clientKeyVaultEventsExpectation)
```

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            string[] clientKeyVaultEventsExpectation,
If you apply tuples suggestion below:
```suggestion
            (string, string)[] clientEncryptedEventsExpectation,
            (string, string)[] clientKeyVaultEventsExpectation,
```

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            IEnumerable<object[]> CaseWithAsync(
It is preferable to avoid using `object`. It can be substituted with a nested class `DeadlockTestData`. As a benefit, you will be able to skip unset fields in this case.

2021-02-10 15:51 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            }
I am deeply concerned about this code, but since it is a test solution and I don't have any better suggestions, I recommend to just keep this problem in mind for future major refactoring.

2021-02-10 15:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            string[] clientKeyVaultEventsExpectation,
it doesn't really work. In this case, we will have a problem with xunit and shown tests results. NOTE: your suggestion is how I did this originally

2021-02-10 15:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            }
answered above

2021-02-10 15:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                    },
answered above

2021-02-10 15:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            IEnumerable<object[]> CaseWithAsync(
it's done by purpose, otherwise, there is a problem with xunit serialization

2021-02-10 15:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                string[] clientKeyVaultEventsExpectation)
answered above

2021-02-10 15:59 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        findResult.Should().Be(BsonDocument.Parse($"{{ _id : 0, encrypted : '{value}' }}"));
will check it

2021-02-10 16:00 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        externalKeyVaultClient: GetKeyVaultMongoClientByKey()))
mostly agreed, I did this because the spec test idea was to map a provided string key to the client, currently, we have only one test key, but I think it's a valid assumption that the number of keys can be bigger further, so I would not change this

2021-02-10 16:00 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                var dataKeys = GetCollection(client_test, __keyVaultCollectionNamespace);
will check

2021-02-10 16:19 UTC, MikalaiMazurenka commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            }
One more suggestion, which you can apply at your own discretion, because it makes a bit more checks but gets rid of `Lazy`:
```suggestion
            IMongoClient internalClient = null;
            if (autoEncryptionOptions.KeyVaultClient == null || autoEncryptionOptions.BypassAutoEncryption == false)
            {
                var internalClientSettings = client.Settings.Clone();
                internalClientSettings.AutoEncryptionOptions = null;
                internalClientSettings.MinConnectionPoolSize = 0;
                internalClient = new MongoClient(internalClientSettings);
            }
            var keyVaultClient = autoEncryptionOptions.KeyVaultClient ?? internalClient;
            var metadataClient = autoEncryptionOptions.BypassAutoEncryption ? null : internalClient;

            return new AutoEncryptionLibMongoCryptController(
                internalClient,
                keyVaultClient,
                metadataClient,
                cryptClient,
                autoEncryptionOptions);
```

2021-02-11 12:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                var dataKeys = GetCollection(client_test, __keyVaultCollectionNamespace);
this happens here: https://github.com/mongodb/mongo-csharp-driver/pull/446/files#diff-0537777d32b586e768ac1e74c10677b06f8933c41fba72c3f11a6f74862925e7R743 (see `clearConnection` argument)

2021-02-11 13:10 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        findResult.Should().Be(BsonDocument.Parse($"{{ _id : 0, encrypted : '{value}' }}"));
good suggestion, done

2021-02-11 13:13 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            }
I think a lazy approach exactly matches to what is required by the spec. Also, I think the code written in this way is a bit more clear, so I would leave this as is

2021-02-11 15:22 UTC, MikalaiMazurenka approved these changes
LGTM

2021-02-11 16:15 UTC, rstam reviewed
I think a comment you added is not accurate, but maybe we can let it slide.

I have reviewed the driver changes but not the tests. Let me check with @jyemin whether he wants me to review the tests or whether he wants to add another reviewer to review the tests.

2021-02-11 16:15 UTC, rstam commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                throw new InvalidOperationException("Metadata client must be configured.");
I'm not sure "configured" is the right word here. That makes it sound like it's the application's fault for not configuring something correctly.

Don't know if you want to reword this or not. Since this should never happen we don't actually expect anyone to ever see this exception, other than readers of the code.

Consider:

    throw new InvalidOperationException("Metadata client is null.");

Or if you don't want to have to figure out a correct error message just remove the check and let a NullReferenceException be thrown if _metadataClient is null (which as we know will never happen).

2021-02-11 16:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                throw new InvalidOperationException("Metadata client must be configured.");
I would leave it. I changed the error message

2021-02-11 18:32 UTC, rstam requested changes
Overall test changes look good. I do have some suggested changes.

2021-02-11 18:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                var dataKeys = GetCollection(client_test, __keyVaultCollectionNamespace);
Consider naming this variable `dataKeysCollection`.

2021-02-11 18:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            var testCases = new[]
I found the data type of this variable confusing because of the double nesting (which you then have to undo in lines 910-916 before returning the actual test cases).

A variable named `testCases` should be be of type `IEnumerable<object[]>`.

You should refactor this to:

    var testCases = new List<object[]>();
    testCases.AddRange(
        CasesWithAsync(
            name: "case 1",
            maxPoolSize: 1,
            bypassAutoEncryption: false,
            keyVaultMongoClient: null,
            expectedNumberOfClients: 2,
            clientEncryptedEventsExpectation:
            new[]
            {
                "listCollections;db",
                "find;keyvault",
                "insert;db",
                "find;db"
            },
            clientKeyVaultEventsExpectation: null));
    testCases.AddRange(
        CasesWithAsync(
            name: "case 2",
            maxPoolSize: 1,
            bypassAutoEncryption: false,
            keyVaultMongoClient: "client_keyvault",
            expectedNumberOfClients: 2,
            clientEncryptedEventsExpectation:
            new[]
            {
                "listCollections;db",
                "insert;db",
                "find;db"
            },
            clientKeyVaultEventsExpectation:
            new[]
            {
                "find;keyvault"
            }));
    testCases.AddRange(
        CasesWithAsync(
            name: "case 3",
            maxPoolSize: 1,
            bypassAutoEncryption: true,
            keyVaultMongoClient: null,
            expectedNumberOfClients: 2,
            clientEncryptedEventsExpectation:
            new[]
            {
                "find;db",
                "find;keyvault"
            },
            clientKeyVaultEventsExpectation: null));
    testCases.AddRange(
        CasesWithAsync(
            name: "case 4",
            maxPoolSize: 1,
            bypassAutoEncryption: true,
            keyVaultMongoClient: "client_keyvault",
            expectedNumberOfClients: 1,
            clientEncryptedEventsExpectation:
            new[]
            {
                "find;db",
            },
            clientKeyVaultEventsExpectation:
            new[]
            {
                "find;keyvault"
            }));

    // cases 5-8 use "MaxPoolSize: 0" which is not supported by the c# driver

    return testCases;

2021-02-11 18:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            }
Lines 910-916 can be simplified to:

    return testCases;

after applying the suggestion above.

2021-02-11 18:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            IEnumerable<object[]> CaseWithAsync(
Rename to `CasesWithAsync` (plural) because this method returns *two* test cases.

2021-02-11 18:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                var dataKeys = GetCollection(client_test, __keyVaultCollectionNamespace);
done

2021-02-11 18:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            }
done

2021-02-11 18:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            IEnumerable<object[]> CaseWithAsync(
done

2021-02-11 18:57 UTC, DmitryLukyanov commented
EG: https://evergreen.mongodb.com/version/60257e130305b9597258fe4f

2021-02-11 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +            }
>I don't think the spec requires the use of the Lazy<T> class.

I meant not .NET lazy, but lazy approach in general when we postpone calling a method until it's actually required

2021-02-11 19:00 UTC, DmitryLukyanov commented
ready for review

2021-02-11 19:04 UTC, rstam approved these changes
LGTM

2021-02-11 19:04 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +            }
It's about both. Mostly the class `DisposableMongoClient` itself (I think this ideally should be done by test setup / teardown, but I don't see any good ways of doing it here). And the dispose logic (the new code) should ideally look simpler in my opinion, but again I don't have any suggestions, just the impression that it doesn't look simple enough.

2021-02-11 20:23 UTC, merged