CSHARP-3369: Adding solution filters
mongodb/mongo-csharp-driver pull request #448
Opened 2021-02-01 17:43 UTC by BorisDog

2021-02-01 17:45 UTC, DmitryLukyanov commented on CSharpDriver.Driver.slnf
> +      "tests\\MongoDB.Driver.TestHelpers\\MongoDB.Driver.TestHelpers.csproj",
if I'm not mistaken, we also should add this line `MongoDB.Driver.Core.TestHelpers` here

2021-02-01 17:57 UTC, rstam requested changes

2021-02-01 17:57 UTC, rstam commented on CSharpDriver.Driver.Core.slnf
> +      "src\\MongoDB.Driver.Core\\MongoDB.Driver.Core.csproj",
Add:

    "tests\\MongoDB.Bson.TestHelpers\\MongoDB.Bson.TestHelpers.csproj"

2021-02-01 17:57 UTC, rstam commented on CSharpDriver.Driver.slnf
> +      "tests\\MongoDB.Driver.TestHelpers\\MongoDB.Driver.TestHelpers.csproj",
Also: 

    "tests\\MongoDB.Bson.TestHelpers\\MongoDB.Bson.TestHelpers.csproj"

2021-02-01 17:58 UTC, DmitryLukyanov commented on CSharpDriver.Driver.Core.slnf
> +}
the last line should be empty, then you won't see this red circle

2021-02-01 19:48 UTC, DmitryLukyanov commented on CSharpDriver.Driver.slnf
> +      "src\\MongoDB.Driver.GridFS\\MongoDB.Driver.GridFS.csproj",
nit: this is probably unnecessary since this lib references Core and Driver

2021-02-01 19:48 UTC, DmitryLukyanov approved these changes
minor nit and then LGTM

2021-02-01 19:52 UTC, rstam approved these changes
LGTM after you apply Dmitry's suggestion to remove GridFS

2021-02-01 19:52 UTC, rstam commented on CSharpDriver.Driver.slnf
> +      "src\\MongoDB.Driver.GridFS\\MongoDB.Driver.GridFS.csproj",
I agree.

But also... I don't think we need to create yet another filter for the GridFS project. That should be used very rarely.

2021-02-01 19:55 UTC, DmitryLukyanov commented on CSharpDriver.Driver.slnf
> +      "src\\MongoDB.Driver.GridFS\\MongoDB.Driver.GridFS.csproj",
Yeah, I'm just saying that this library is useless in this list since the related tests are not added

2021-02-01 19:57 UTC, rstam commented on CSharpDriver.Driver.slnf
> +      "src\\MongoDB.Driver.GridFS\\MongoDB.Driver.GridFS.csproj",
And I'm agreeing with you... we should remove this project from this filter.

2021-02-01 20:12 UTC, BorisDog commented on CSharpDriver.Driver.slnf
> +      "src\\MongoDB.Driver.GridFS\\MongoDB.Driver.GridFS.csproj",
Needed in MongoDB.Driver.Tests

2021-02-02 17:27 UTC, BorisDog commented
Merged.

2021-02-02 17:27 UTC, closed without merging