CSHARP-2474 / CSHARP-2481: Implement libgssapi support for Kerberos auth on Linux
mongodb/mongo-csharp-driver pull request #449
Opened 2021-02-01 22:19 UTC by JamesKovacs

This PR implements CSHARP-2474 and CSHARP-2481.

2021-02-02 22:23 UTC, JamesKovacs commented
Evergreen GSSAPI tests are passing on Windows and Linux on all supported frameworks: 
https://spruce.mongodb.com/version/6019c9e7c9ec445f87c92457/tasks

2021-02-02 23:31 UTC, BorisDog requested changes

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            return new Oid {elements = ntUserNameHandle.AddrOfPinnedObject(), length = (uint) oidBytes.Length};
It's highly advisable to free the pinned handles asap. I think `Marshal.AllocHGlobal` and `Marshal.Copy` is more suitable for such unmanaged allocations.

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            private ISecurityContext _securityContext;
minor: readonly?

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                _isDisposed = true;
Should `_isDisposed ` functionality be threadsafe (changed by Interlocked operation), or removed at all?

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +/* Copyright 2020-present MongoDB Inc.
nit: 2021?

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +                    if (!string.IsNullOrEmpty(realm))
nit: IsNullOrWhitespace? Or is whitespace a valid value?

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Sspi/SspiSecurityContext.cs
> +            if (!_isDisposed && disposing)
Should we have interlocked `_isDisposed ` pattern here as well? Or is `_credential` dispose threadsafe?

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +    internal static class Gss {
nit: Allman braces style

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +            using (spnBuffer = new GssInputBuffer(spn))
minor: using (var spnBuffer = new GssInputBuffer(spn))

2021-02-02 23:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                using (nameBuffer = new GssInputBuffer(username))
minor: `using (var nameBuffer = new GssInputBuffer(username))` or
`using var nameBuffer = new MemoryStream();` without block braces

Applies for all usings.

2021-02-03 02:44 UTC, craiggwilson requested changes
Just a few comments/questions/suggestions. Nicely done James :)

2021-02-03 02:44 UTC, craiggwilson commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
Is there a more specific exception that can be caught here? Like, can the `LinuxException` and the `Win32Exception` have a common base class so we aren't just catching everything, but very specifically the problems that we know can go wrong in here?

2021-02-03 02:44 UTC, craiggwilson commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public void RegisterSecurityContext(ISecurityContext securityContext)
It feels like something is leaking here. Most SASL mechanisms don't have a security context, nor do they need one, yet a conversation applies to all SASL mechanisms. Is there any reason that IDisposable isn't suitable here?

2021-02-03 02:44 UTC, craiggwilson commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +                    if (!string.IsNullOrEmpty(realm))
technically, I think whitespace is valid although I hope no one ever does that.

2021-02-04 15:28 UTC, DmitryLukyanov reviewed
Initial review, I'm going to spend a bit more time on pinvokes invistigation

2021-02-04 15:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                NativeMethods.ReleaseName(out _, Handle);
should it be in try/catch?

2021-02-04 15:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                NativeMethods.ReleaseName(out _, Handle);
Also, let's assign the result into `_` to explicitly say that we know that this method returns a result, but we ignore it

2021-02-04 15:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +    internal struct GssInputBuffer : IDisposable
can we use this https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/NativeLibraryLoader/PinnedBuffer.cs#L21 instead?

2021-02-04 19:08 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +        public static Oid NtUserName = Create(0x2a, 0x86, 0x48, 0x86, 0xf7, 0x12, 0x01, 0x02, 0x01, 0x01);
The `Oid` struct is specifically for interop with unmanaged code. The intent is to mirror the unmanaged data structures exactly, which is why I'm using public fields and even violating .NET naming conventions (e.g. lowercase public members).

2021-02-04 19:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            return new Oid {elements = ntUserNameHandle.AddrOfPinnedObject(), length = (uint) oidBytes.Length};
These 3 OIDs exist for the lifetime of the app domain and there can only ever be 3 OIDs due to the private ctor. I debated over whether to pin the managed byte arrays so unmanaged code could use them or whether to AllocHGlobal/Copy. Both work, but the latter will play nicer with the .NET GC. I'll switch to using AllocHGlobal/Copy. Thanks for the suggestion.

2021-02-04 21:01 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            return new Oid {elements = ntUserNameHandle.AddrOfPinnedObject(), length = (uint) oidBytes.Length};
Done.

2021-02-04 21:09 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            private ISecurityContext _securityContext;
Not all SASL mechanisms require registering an `ISecurityContext` for disposal. Only SSPI and GSSAPI. This happens in `RegisterSecurityContext` and thus this field can't be marked `readonly`.

2021-02-04 21:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +        public static Oid NtUserName = Create(0x2a, 0x86, 0x48, 0x86, 0xf7, 0x12, 0x01, 0x02, 0x01, 0x01);
I meant to apply this change for "helper" static fields like `NtUserName`. Which are are not part of the original structures.

2021-02-04 21:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            private ISecurityContext _securityContext;
Right, missed the RegisterSecurityContext.

2021-02-04 21:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +            if (Length > int.MaxValue)
minor: should we have a lower limit than int.MaxValue? Something like 1K/1M/1G.

2021-02-04 21:47 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +/* Copyright 2020-present MongoDB Inc.
Some of files/code were created in 2020 while others in 2021. (I have an Alfred snippets template that inserts current year in the copyright message.) I can standardize on 2021, but I don't think it matters.

2021-02-04 21:49 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                _isDisposed = true;
Dispose should only be called from a single thread and never concurrently. Even if it was called concurrently, you'd have two threads fighting to set the value of `_isDisposed` to true. Whichever won, the value would still be true. So unless I'm missing some subtlety this code should work as advertised.

2021-02-04 21:51 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +                    if (!string.IsNullOrEmpty(realm))
I hope that no one ever encodes their realm name using [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) but if they do, we have them covered.

2021-02-04 21:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Sspi/SspiSecurityContext.cs
> +            if (!_isDisposed && disposing)
We shouldn't be calling Dispose concurrently from multiple threads. Each authenticating thread will have its own SaslConversation and related ISecurityContext.

2021-02-04 21:57 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +    internal static class Gss {
Fixed.

2021-02-04 22:03 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +            using (spnBuffer = new GssInputBuffer(spn))
Since `spnBuffer` must be passed by ref (see line 37), you can't declare it inside the `using` statement. If you do, you receive a C# compiler error:

```
  GssapiServicePrincipalName.cs(37, 77): [CS1657] Cannot use 'spnBuffer' as a ref or out value because it is a 'using variable'
```

2021-02-04 22:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                using (nameBuffer = new GssInputBuffer(username))
Same as above. `using (var foo = new Foo())` doesn't play nicely with `ref` parameters.

2021-02-04 22:37 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/NativeMethods.cs
> +        private const string GSSAPI_LIBRARY = @"gssapi_krb5";
I debugged through this using `LD_DEBUG` as well as reading through https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html. When you use `[DllImport(LibraryName, EntryPoint="MethodName")]`, .NET uses platform dependent rules to select the library - both name and search path. On Windows, it tries `LibraryName.dll` and then `LibraryName`. So if your library name is `foo.dll`, it will first look for `foo.dll.dll` and then `foo.dll`. For Linux, the rules are `libLibraryName.so` then `LibraryName.so` then `libLibraryName` then `LibraryName`. (Not 100% sure on the ordering other than the first two because initially I used `libgssapi_krb5` and the first library it search for was `liblibgssapi_krb5.so` followed by `libgssapi_krb5.so`. Similarly on OSX where it searches for `libLibraryName.dylib`.

As long as the Linux system has `libgssapi_krb5.so` in its LD_LIBRARY_PATH, then the bindings should work as expected. And yes, we should document this adequately because it will likely require installing extra dependencies on most systems.

2021-02-04 23:01 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
Fair point. I'll rework the exception handling in this portion of the code to catch either `Win32Exception` (for SASL) or `LibgssapiException` (for GSSAPI).

2021-02-04 23:16 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public void RegisterSecurityContext(ISecurityContext securityContext)
This is GitHub diff weirdness. `SaslConversation` still has a `Dispose` method (see line 246). Previously there was a `RegisterItemForDisposal(IDisposable item)`, but the only `IDisposable` registered was SSPI's `SecurityContext`. So I renamed `RegisterItemForDisposal` to `RegisterSecurityContext`. Then the `Dispose` method disposes the registered `ISecurityContext` if one has been registered when the owning `SaslConversation` is disposed. The `SaslConversation` is enclosed in a `using` block (same as previously) to ensure it is properly disposed when it leaves scope.

2021-02-04 23:18 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public void RegisterSecurityContext(ISecurityContext securityContext)
Note that `SaslConversation` called `GC.SuppressFinalize(this)` in its `Dispose` method, but it had no finalizer. So it was a NOP. Given that `SaslConversation` itself holds no unmanaged resources, there is no need for it to have a finalizer. There are other classes - such as `GssInputBuffer` - that do encapsulate unmanaged handles and I'm going to go back and plumb those with finalizers and `GC.SuppressFinalize(this)` to ensure that they're properly cleaned up if something unexpected happens.

2021-02-04 23:21 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +- name: gssapi-auth-tests-linux
I agree. The correct nomenclature is linux not posix in this case. The two places we use `posix` in `evergreen.yml` have nothing to do with my GSSAPI PR. I don't want to pollute my PR with unrelated changes.

2021-02-04 23:24 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
I reworked the exception handling in this area of the code to catch `Win32Exception` and `LibgssapiException` specifically rather than all exceptions.

```
catch (Exception ex) when (ex is Win32Exception or LibgssapiException)
```

2021-02-04 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                    if (password != null)
Actually `_password` isn't used outside of `FirstStep`. I'm going to eliminate the `_password` field and just use the passed-in `password` parameter.

2021-02-04 23:31 UTC, craiggwilson commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public void RegisterSecurityContext(ISecurityContext securityContext)
Sorry, I don't think I was clear. `ISecurityContext` has no meaning whatsoever to `ScramSha1`, for instance. Except that `ScramSha1` is forced to confront `ISecurityContext` when it looks at the `SaslConversation` (think: "Am I supposed to care about this and implement it? What is it for?") The fact that `ISecurityContext` is very specific to the GSSAPI stuff means that now `ScramSha1` must purposefully choose to ignore this thing about GSSAPI.

If this is left as registering something for disposal, all `ScramSha1` needs to realize is that he has nothing that needs to be cleaned up and move on.

(This is really subtle and I might be the only one who cares about it)

2021-02-04 23:32 UTC, craiggwilson commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/NativeMethods.cs
> +        private const string GSSAPI_LIBRARY = @"gssapi_krb5";
sgtm. :)

2021-02-04 23:38 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/ISecurityContext.cs
> +        /// <param name="challenge"></param>
Fixed.

2021-02-04 23:39 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/ISecurityContext.cs
> +/* Copyright 2020-present MongoDB Inc.
This file was created in 2020. 🤷

2021-02-04 23:40 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            var ntUserNameHandle = GCHandle.Alloc(oidBytes, GCHandleType.Pinned);
I modified the OIDs to use unmanaged memory rather than pinning managed memory to avoid potential GC problems.

2021-02-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            return new Oid {elements = ntUserNameHandle.AddrOfPinnedObject(), length = (uint) oidBytes.Length};
Fixed.

2021-02-04 23:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/ISecurityContext.cs
> +/* Copyright 2020-present MongoDB Inc.
at someday, we probably should finally force using a `2008 - nowadays` form :)

2021-02-04 23:42 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +using System.Runtime.InteropServices;
Fixed.

2021-02-04 23:45 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                NativeMethods.ReleaseName(out _, Handle);
P/invoked methods can return error codes, but can't throw exceptions. So no need to try/catch. In this case we attempt to release but there is not much we can do if the release fails. Hence ignoring the major/minor status codes.

2021-02-04 23:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +    internal struct GssInputBuffer : IDisposable
No, these are the struct layouts required by GSSAPI. Like it or lump it, these are the definitions that we have to use.

2021-02-04 23:50 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +            if (Length > int.MaxValue)
The issue is that Length is a `uint` (based on GSSAPI struct layout) but we are allocating a managed array to hold the returned value. It shouldn't be large, but who knows what GSSAPI is going to pass back to us?

2021-02-05 23:47 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +        public static Oid NtUserName = Create(0x2a, 0x86, 0x48, 0x86, 0xf7, 0x12, 0x01, 0x02, 0x01, 0x01);
The OIDs must be passed by reference to the `gss_*` functions. So autoprops won't work unfortunately. I've marked the fields as read-only to prevent misuse.

2021-02-05 23:50 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +            using (spnBuffer = new GssInputBuffer(spn))
I've modified `GssInputBuffer` to be a class, which removed the necessity to mark them as `ref` parameters in the `gss_*` functions. This allowed me to switch to the more typical syntax of declaring the variable inside the `using`.

2021-02-05 23:50 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                using (nameBuffer = new GssInputBuffer(username))
Fixed. See above.

2021-02-06 00:17 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            public void RegisterSecurityContext(ISecurityContext securityContext)
Fair enough point. I've switched back to the previous `RegisterItemForDisposal` impl that you wrote.

2021-02-06 00:21 UTC, JamesKovacs commented
Implemented various code fixes and improvements suggested by reviewers. I believe that I've responded to everyone's comments and addressed their concerns. If I missed something, please let me know. Re-requesting reviews. Thanks in advance.

2021-02-08 15:25 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
maybe it makes sense to add a base class here? Otherwise, we can have a 3rd exception here for mac?

2021-02-08 16:01 UTC, craiggwilson approved these changes

2021-02-08 19:05 UTC, JamesKovacs commented
@craiggwilson: Thank you for catching that. I have corrected the other places in `GssapiAuthenticator.cs` to catch either `Win32Exception` or `LibgssapiException` rather than the more generic `Exception`.

2021-02-08 19:09 UTC, BorisDog requested changes

2021-02-08 19:09 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +        private void InnerDispose()
nit: Dispose pattern usually defines two methods: `Dispose` and` Dispose(bool)`. While in this case there are no internal managed disposals, should we still follow the convention for consistency?

2021-02-08 19:09 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +    internal sealed class GssInputBuffer : IDisposable
General thought: If `GssInputBuffer` is a short lived buffer, it would be a good candidate for pinning instead for Marshal.Alloc

2021-02-08 19:09 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +            uint majorStatus = NativeMethods.ReleaseCredential(out uint minorStatus, base.handle);
nit: var and convert to Enums?

2021-02-08 19:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
Done.

2021-02-08 19:44 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                catch (Exception ex)
I assumed that `Win32Exception` was `System.ComponentModel.Win32Exception` from the .NET Framework. I didn't realize that we had defined our own. Since this is our own `Win32Exception` I agree that extracting out a common base class would be preferred to using `when`. I'll refactor the exception handling to extract a common base class. Thanks for catching this.

2021-02-08 21:03 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                            majorStatus = NativeMethods.AcquireCredentialWithPassword(out minorStatus, gssName, passwordBuffer, uint.MaxValue, IntPtr.Zero, GssCredentialUsage.Initiate, out securityCr
Great catch. The returned `OidSet` is not needed. Switched to passing in `IntPtr.Zero` to avoid the allocation and need to free it. This also eliminates the need for any `OidSet` objects in the Libgssapi code.

2021-02-08 21:03 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                        majorStatus = NativeMethods.AcquireCredential(out minorStatus, gssName, uint.MaxValue, IntPtr.Zero, GssCredentialUsage.Initiate, out securityCredential, out OidSet _, out uint
Same as above. `OidSet` removed.

2021-02-08 21:30 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/NativeMethods.cs
> +        public static extern uint DisplayStatus(out uint minorStatus, uint status, GssCode statusType, in IntPtr mechType, out uint messageContext, out GssOutputBuffer statusString);
Unfortunately not. 0 and 1 have special meaning and hence are included in the enum, but then there are a lot of other possible failure codes. That's why `Gss.ThrowIfError()` calls into `gss_display_status` to convert arbitrary major and minor status codes into a human-readable description.

2021-02-08 21:32 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/OidSet.cs
> +    internal struct OidSet
Turns out we don't need it. I modified the OidSet-returning calls to request not to return OidSet objects at all and removed OidSet from our codebase.

2021-02-08 21:44 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +    internal struct GssOutputBuffer
Unfortunately this cannot be a SafeHandle because libgssapi requires a very specific structure that is more than an IntPtr. As well, I could only get the libgssapi integration working when `GssOutputBuffer` is a struct. Attempting to make it a class and modifying in/out/ref calling as appropriate was not successful. So we have to be careful to call Dispose when done with a GssOutputBuffer to free its unmanaged memory.

2021-02-08 21:47 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                NativeMethods.DisplayStatus(out _, minorStatus, GssCode.MECH_CODE, in Oid.NoOid, out uint _, out var outputBuffer);
I felt it was more intention-revealing to use `Oid.NoOid`, which is actually `IntPtr.Zero`:
```
        public static readonly IntPtr NoOid = IntPtr.Zero;
```

2021-02-08 21:50 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +        private void InnerDispose()
I debated that myself. I decided that `InnerDispose` was better than `Dispose(bool disposing)` where the `disposing` parameter is never used.

2021-02-08 21:59 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +            if (Value != IntPtr.Zero)
We cannot use SafeHandle for GssInputBuffer because libgssapi requires a very specific struct layout, which we cannot provide with SafeHandle. Given that GssInputBuffer is only used to call a single libgssapi function, worst case scenario is that we don't call Dispose and the object ends up on the finalizer queue. We should never have concurrent execution of the Dispose method.

2021-02-08 21:59 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +    internal sealed class GssInputBuffer : IDisposable
In most if not all cases, GssInputBuffer is a short-lived buffer for passing parameters to libgssapi. The advantage of Marshal.Alloc is that we use it for both strings and byte arrays. If we switched to pinning, we could only pin the arrays since strings have to be converted from Unicode to a C-style string. Thus we would have to remember how the buffer was created so that we could free or unpin as necessary.

2021-02-08 22:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +            uint majorStatus = NativeMethods.ReleaseCredential(out uint minorStatus, base.handle);
Done. Switched to `var`. Enums won't work for the reason noted earlier.

2021-02-08 22:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                NativeMethods.ReleaseName(out _, Handle);
In expected cases, yes, but is it guaranteed? Idk this, but I can rely on you here

2021-02-08 22:13 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +    internal struct GssInputBuffer : IDisposable
I don't think that using structs is required. But anyway, this looks like not the solution anymore. As far as I can see, the target of these files is the same or at least very similar. So, if it's possible to reuse it, I would do it

2021-02-08 22:33 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +        private GssapiServicePrincipalName _servicePrincipalName;
Done.

2021-02-08 22:44 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +            GssOutputBuffer outputToken = new GssOutputBuffer();
Done.

2021-02-08 22:45 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +        /// <param name="username"></param>
Changed GssapiSecurityCredential to an internal class (to reduce API surface area) and removed XML comments.

2021-02-08 22:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +            IntPtr gssName = IntPtr.Zero;
Done.

2021-02-08 22:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +        /// <param name="username"></param>
Switched to internal class and removed xml comments.

2021-02-08 22:48 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/LibgssapiException.cs
> +        /// <param name="majorErrorMessage"></param>
Fixed.

2021-02-08 22:49 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +            /// <param name="securityContext"></param>
Switched back to previous impl using list of items registered for disposal.

2021-02-08 22:53 UTC, JamesKovacs commented on evergreen/run-gssapi-auth-tests.sh
> +#       AUTH_HOST             Set the hostname of a key distribution center (KDC)
Added descriptions of environment variables used by the script that weren't documented.

2021-02-08 23:00 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssInputBuffer.cs
> +        public ulong Length;
Fixed.

2021-02-08 23:00 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +        public ulong Length;
Fixed.

2021-02-08 23:02 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +        public bool IsInitialized { get; private set; }
Fixed.

2021-02-08 23:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +        public IntPtr Handle { get; }
Changed to use SafeHandle base class instead.

2021-02-08 23:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +        public static GssapiServicePrincipalName Create(string service, string host, string realm)
Done.

2021-02-08 23:06 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +        public uint length;
Done.

2021-02-08 23:06 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +                    _context.DecryptMessage(0, bytesReceivedFromServer);
Done.

2021-02-08 23:09 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +            var spn = $"{service}@{host}";
Fixed.

2021-02-08 23:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                spn += $"@{realm}";
Verified that this required in both cases.

2021-02-08 23:15 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SecurityContextFactory.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
Done.

2021-02-08 23:20 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                NativeMethods.DisplayStatus(out _, majorStatus, GssCode.GSS_CODE, ref Oid.NoOid, out uint _, out var outputBuffer);
Done.

2021-02-08 23:21 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                        majorStatus = NativeMethods.AcquireCredential(out minorStatus, gssName, uint.MaxValue, IntPtr.Zero, GssCredentialUsage.Initiate, out securityCredential, IntPtr.Zero, out uint
Should `IntPtr.Zero` be passed instead of `out uint _ ` (and it all `AcquireCredential`)?

2021-02-08 23:25 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssEnums.cs
> +        GSS_CODE = 1,
These enums are serialized via their integers representations. So the names don't matter to either the C# or C code. I have renamed the values as suggested to match the libgssapi definitions.

2021-02-08 23:27 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                NativeMethods.DisplayStatus(out _, minorStatus, GssCode.MECH_CODE, ref Oid.NoOid, out uint _, out var outputBuffer);
I'm honestly not sure why the Go driver does it that way. I haven't found a libgssapi error that required recursive lookup of the error messages. My worry is that if anything goes wrong during the error lookup, we could end up overwriting the original error with some unrelated error.

2021-02-08 23:28 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +        public static IntPtr NoOid = IntPtr.Zero;
Done.

2021-02-08 23:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                NativeMethods.DisplayStatus(out _, minorStatus, GssCode.MECH_CODE, ref Oid.NoOid, out uint _, out var outputBuffer);
I saw it not only on go but somewhere in docs, I can try to find it again

2021-02-08 23:39 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssEnums.cs
> +        Both = 0,
Done.

2021-02-08 23:39 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssEnums.cs
> +        Mutual = 2,
Done.

2021-02-09 00:12 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                outputBuffer.Dispose();
Refactored to ensure `GssOutputBuffer` is disposed.

2021-02-09 00:15 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +                outputBuffer.Dispose();
Refactored to use using.

2021-02-09 00:24 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +                outputToken.Dispose();
Refactored.

2021-02-09 00:24 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityContext.cs
> +                outputBuffer.Dispose();
Refactored.

2021-02-09 21:19 UTC, DmitryLukyanov approved these changes
Some minor comments and then LGTM, Great job!

2021-02-09 21:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +        public static GssapiSecurityCredential Acquire(string username, SecureString password)
nit: I think it would be better to split this class into two: `GssapiSecurityCredential` and `GssapiSecurityCredentialFactory`

2021-02-09 21:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                Ensure.IsNotNull(item, "item");
nit: Ensure.IsNotNull(item, nameof(item));

2021-02-09 21:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +                NativeMethods.ReleaseBuffer(out _, this);
nit: `_ = NativeMethods.ReleaseBuffer(out _, this);`

2021-02-09 21:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                    NativeMethods.ReleaseName(out _, gssName);
nit: `_ =  NativeMethods.ReleaseName(out _, gssName);`

2021-02-09 21:21 UTC, DmitryLukyanov commented
NOTE: I assume that we took `DllImport` as the approach here only for historical reasons

2021-02-10 00:04 UTC, JamesKovacs commented on evergreen/run-gssapi-auth-tests.sh
> +  echo "Setting krb5 config file"
In theory it would if P/Invoke to libgssapi worked on OSX.

2021-02-10 00:13 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/GssapiAuthenticator.cs
> +            public FirstStep(string serviceName, string hostname, string realm, string username, SecureString password, SaslConversation conversation)
Wikipedia says it is `hostname` rather than `hostName`.

2021-02-10 00:31 UTC, DmitryLukyanov commented on evergreen/run-gssapi-auth-tests.sh
> +  echo "Setting krb5 config file"
I meant that maybe it makes sense to add conditions like: 
  
    if windows
    else if linux
    else // TODO

2021-02-10 17:57 UTC, BorisDog commented
LGTM

2021-02-10 17:57 UTC, BorisDog approved these changes

2021-02-10 22:55 UTC, JamesKovacs commented on evergreen/run-gssapi-auth-tests.sh
> +
Removed.

2021-02-10 22:55 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/ISecurityContext.cs
> +        /// <summary>
Fixed.

2021-02-10 22:58 UTC, JamesKovacs commented on evergreen/run-gssapi-auth-tests.sh
> +  echo "Setting krb5 config file"
The else branch will work for Linux and OSX. I tested the technique with kinit on OSX and it worked the same as Linux.

2021-02-10 23:02 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +        public static GssapiSecurityCredential Acquire(string username, SecureString password)
I'm mirroring the existing `SspiSecurityCredential`. If I extract out the Acquire methods into their own factory classes, then `SecurityCredentialFactory` will be calling another factory. My preference is to minimize changes to the existing SSPI impl and mirror what was done there for consistency.

2021-02-10 23:02 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Oid.cs
> +            return new Oid { elements = unmanagedArray, length = (uint) numBytes };
Fixed.

2021-02-10 23:03 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                Ensure.IsNotNull(item, "item");
Good catch. I often forget that `nameof` exists for some reason. Fixed.

2021-02-10 23:05 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiSecurityCredential.cs
> +                    NativeMethods.ReleaseName(out _, gssName);
Thought I caught all these, but missed this one. Thanks. Fixed.

2021-02-10 23:06 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +                NativeMethods.ReleaseBuffer(out _, this);
Fixed.

2021-02-10 23:08 UTC, JamesKovacs commented
> NOTE: I assume that we took `DllImport` as the approach here only for historical reasons

I chose the `DllImport` approach for a few reasons...
1. It mirrors the existing SSPI impl.
2. I was familiar with it from previous projects.
3. While the delegate approach offers more flexibility, that flexibility wasn't required for integrating with libgssapi.

2021-02-10 23:10 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssOutputBuffer.cs
> +            if (Length > int.MaxValue)
Discussed via Slack. Since `length` is a 64-bit `ulong`, we have to verify that it doesn't exceed the maximum number of bytes that `Marshal.Copy` can handle.

2021-02-10 23:12 UTC, DmitryLukyanov commented
> 
> 
> > NOTE: I assume that we took `DllImport` as the approach here only for historical reasons
> 
> I chose the `DllImport` approach for a few reasons...
> 
>     1. It mirrors the existing SSPI impl.
> 
>     2. I was familiar with it from previous projects.
> 
>     3. While the delegate approach offers more flexibility, that flexibility wasn't required for integrating with libgssapi.

got it, my point was that it would be good to be consistent in our approaches(at least latest) at least if we can and there are no disadvantages in it

2021-02-10 23:16 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/GssapiServicePrincipalName.cs
> +                NativeMethods.ReleaseName(out _, Handle);
This class was changed to derive from `SafeHandle` and a failed release of the name is communicated to .NET's diagnostic machinery.

2021-02-11 00:10 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +                NativeMethods.DisplayStatus(out _, minorStatus, GssCode.MECH_CODE, ref Oid.NoOid, out uint _, out var outputBuffer);
Good catch. Certain `gss_*` functions can return a non-zero `message_context` from `gss_display_status` indicating that there is optional extra messages to follow. Modified the impl to read these extra messages if available.

2021-02-11 00:10 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/Gss.cs
> +            if (majorStatus != (uint)GssStatus.GSS_S_COMPLETE && majorStatus != (uint)GssStatus.GSS_S_CONTINUE_NEEDED)
Done.

2021-02-11 00:44 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/Libgssapi/NativeMethods.cs
> +    internal static class NativeMethods
Switched from C# to C-style naming.

2021-02-12 23:32 UTC, JamesKovacs commented
Squashed and merged with `master`.

2021-02-12 23:32 UTC, closed without merging