CSHARP-3355: Add more spec tests for invalid relaxed UUIDs.
mongodb/mongo-csharp-driver pull request #452
Opened 2021-02-05 18:59 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/601d956b3e8e86586c978855

2021-02-05 19:02 UTC, jyemin requested changes

2021-02-05 19:02 UTC, jyemin commented on tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
> +#!/usr/bin/env perl
I think this file can be deleted

2021-02-05 19:14 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
> +#!/usr/bin/env perl
as far as I know, we copy such files under git to make a diff with the spec folder easier. So, if we have such a file under git we can just fully copy all files from the spec folder into our tests without any analysis

2021-02-05 19:15 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
> +#!/usr/bin/env perl
at least mostly :)

2021-02-05 19:16 UTC, rstam requested changes

2021-02-05 19:16 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReader.cs
> +
I think you can replace lines 2093-2112 with:

    var guid = Guid.Parse(uuidToken.StringValue);
    var binaryData = new BsonBinaryData(guid, GuidRepresentation.Standard);

`Guid.Parse` already does all the validations we need.

2021-02-05 19:23 UTC, DmitryLukyanov commented
EG: https://evergreen.mongodb.com/version/601d9af00305b9115d9a8acd

2021-02-05 19:23 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonReader.cs
> +
good point, done

2021-02-05 19:43 UTC, jyemin commented on tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
> +#!/usr/bin/env perl
If that's the policy, then so be it, but this is a weird one to copy.

2021-02-05 19:43 UTC, jyemin commented
Removed James since Robert picked it up.

2021-02-05 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.Tests/Specifications/bson-corpus/tests/bsonview
> +#!/usr/bin/env perl
it's not a defined policy, but this is how we did previously

2021-02-11 20:46 UTC, rstam approved these changes
LGTM

2021-02-13 00:19 UTC, JamesKovacs requested changes
Changes look good. Verified that:
- BsonBinarySubType is still set correctly.
- Same exception type (FormatException) is thrown as before.
- Tests run successfully.

One minor change required. You have an extraneous `using` statement.

2021-02-13 00:19 UTC, JamesKovacs commented on src/MongoDB.Bson/IO/JsonReader.cs
> +using System.Linq;
Not used.

2021-02-13 00:29 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonReader.cs
> +using System.Linq;
Done

2021-02-17 23:13 UTC, JamesKovacs approved these changes
LGTM

2021-02-18 15:22 UTC, merged