CSHARP-3306: maxConnecting
mongodb/mongo-csharp-driver pull request #453
Opened 2021-02-11 23:03 UTC by BorisDog

- Connections establishment moved to ExclusiveConnectionPool
- maxConnecting functionality introduced

This PR is for initial review, more testing will be added afterwards.
- Basic tests where introduced, but extensive testing is needed.
- Unittests are named to match integration spec tests.

[EG](https://evergreen.mongodb.com/version/6025b08c3066157e124b7649)

2021-02-18 00:44 UTC, DmitryLukyanov reviewed
Initial review. I will check it once again tomorrow.

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <summary>
as I understand, this should be a constant in the `ExclusiveConnectionPool`. 
This settings class matches(more or less) with this spec: https://github.com/mongodb/specifications/blob/626bd79a271447e1bbeda0138de51c1226737bfb/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#connection-pool-options-1

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            public void Dispose() => throw new NotImplementedException();
?

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +        private sealed class ConnectionCreator : IDisposable
Consider moving this into a new file, we probably have much bigger number of nested classes here than necessary

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                        _ => throw new ArgumentOutOfRangeException(nameof(_connectingWaitStatus))
we usually throw `InvalidOperationException` for such cases

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    connection = _connectingWaitStatus switch
let's add comments here to explain this logic a bit

2021-02-18 00:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _stopwatch.Stop();
As I see this is missed in the first if branch

2021-02-18 00:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +                maxConnecting: maxConnecting,
this should be set via reflection

2021-02-18 00:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            ExecuteOnNewThread(threadsCount + 1, i =>
it's possible to use TaskScheduler from here: https://github.com/mongodb/mongo-csharp-driver/blob/master/tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs#L569

2021-02-18 20:30 UTC, JamesKovacs requested changes
Good progress on this feature. I need to think more deeply about connections, thread synchronization, and potential failure scenarios once you have more tests in place, but you're on the right track. I noticed a few minor issues to fix, which I've noted.

2021-02-18 20:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
>          }
as far as I understand, this should not be added to PoolSettings at least it's not mentioned in the spec

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <summary>
Good point. Done

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <returns> A new ConnectionPoolSettings instance.</returns>
Reverted all changes in the file.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <returns> A new ConnectionPoolSettings instance.</returns>
Reverted all changes in the file.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
>          }
Reverted all changes in the file.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
>              _maintenanceInterval = Ensure.IsInfiniteOrGreaterThanOrEqualToZero(maintenanceInterval.WithDefault(TimeSpan.FromMinutes(1)), "maintenanceInterval");
Reverted all changes in the file.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// Initializes a new instance of the <see cref="ConnectionPoolSettings" /> class.
Reverted all changes in the file.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
>          private readonly ConnectionPoolSettings _settings;
Good catch. Added.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _stopwatch.Stop();
Yup, needed only for `TimeoutException`.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            public void Dispose() => throw new NotImplementedException();
Tnx, leftovers. Reverted.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +        private sealed class ConnectionCreator : IDisposable
Good idea, done.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                        _ => throw new ArgumentOutOfRangeException(nameof(_connectingWaitStatus))
Seems that `ArgumentOutOfRangeException` is more suitable here, as it is the variable value that is being inspected as opposed to a specific operation execution attempt.
Additional note: Currently there is no code path that will result in default switch case, so this check is for future proofness.

2021-03-04 20:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    connection = _connectingWaitStatus switch
Done

2021-03-11 00:32 UTC, stIncMale reviewed
I tried reviewing the PR as requested, but I don't think it was useful in any way because I was mostly unable to extract even the high-level logic of the code. The main factors contributing to this are:
1. Virtually no knowledge of C# syntax, execution and memory model, .NET API.
2. No familiarity with the .NET MongoDB driver code.

it is my opinion that with regard to this PR I may only be useful when discussing the logic in plain English/Russian (having the code changes at hand when discussing may be useful).

2021-03-11 00:32 UTC, stIncMale commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +                    }
Should something be done if `Reset` is called when cancellation has not been requested?

2021-03-23 19:18 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPoolClasses.cs
> +        private sealed class ConnectionCreator : IDisposable
it would be good to write tests for this class and if so, I guess it's better to move this class to a new  file

2021-03-23 20:30 UTC, stIncMale commented on tests/MongoDB.Bson.TestHelpers/Threading/ThreadPerTaskScheduler.cs
> +    public sealed class ThreadPerTaskScheduler : TaskScheduler
If there is a bound on the number of threads a thread pool / executor may have, then submitting a task to such an executor is not the same as creating a new thread - in some situations it will result in putting the task in a queue so that it can be done later by one of the executor threads.

2021-03-25 23:20 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringTestRunner.cs
> +            if (applicationError.Contains("generation"))
Done.

2021-03-25 23:20 UTC, BorisDog commented on src/MongoDB.Driver.Core/MongoConnectionException.cs
> +        internal int? Generation
Done.

2021-03-25 23:20 UTC, BorisDog commented on src/MongoDB.Driver.Core/MongoConnectionException.cs
> +                    throw new InvalidOperationException("Generation is already set");
Done.

2021-03-25 23:20 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            Ensure.IsBetween(count, 0, 1024, nameof(count));
Sanity arguments check. Can be adjusted later if larger upper bound is needed.

2021-03-25 23:20 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +                    }
Good question. When resetting, we need just to clear the `Signaled` flag, which is expressed by `IsCancellationRequested`.

2021-03-25 23:20 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/Threading/ThreadPerTaskScheduler.cs
> +        public static Task CreateTask<T>(Func<T> function) =>
Removed.

2021-03-25 23:20 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Misc/SemaphoreSlimSignalableTests.cs
> +            [Values(true, false)] bool isAsync,
Discussed offline.

2021-03-25 23:20 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +            //mockConnectionPool.Verify(p => p.Clear(), Times.Once);
Removed

2021-03-25 23:20 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
> +
Done.

2021-03-25 23:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            Ensure.IsBetween(count, 0, 1024, nameof(count));
i think it's not needed, but at least let's add a comment about this

2021-03-25 23:49 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            bool isAsync)
we call it async, check other places also :)

2021-03-25 23:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Misc/SemaphoreSlimSignalableTests.cs
> +            [Values(0, 1, 2)] int intialCount,
`intialCount` - typo

2021-03-26 00:02 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Misc/SemaphoreSlimSignalableTests.cs
> +            [Values(0, 1, 2)] int intialCount,
Thanks done.

2021-03-26 00:03 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            bool isAsync)
Thanks, done.

2021-03-26 00:03 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    using (var connectionCreator = new ConnectionCreator(this, minTimeout))
It's background task, so there is no notion of timeouts here. Minimal timeout is used just to allow the operation not timeout immediately.

2021-03-26 00:04 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPoolClasses.cs
> +                        _ => throw new ArgumentOutOfRangeException(nameof(_connectingWaitStatus))
Thanks, done.

2021-03-26 00:07 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            Ensure.IsBetween(count, 0, 1024, nameof(count));
I think it's self explanatory. Stricter arguments checks to contributes to overall correctness, so I suggest we leave it as is. We'll have a better chance catching unreasonable usage/bugs in the future.

2021-03-26 00:09 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> -
I liked the idea of separating to multiple files. I think we should have helpers file and clean main class file, it's a bit more panful to review now, but more maintainable down the line.

2021-03-26 00:10 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPoolClasses.cs
> +/* Copyright 2021-present MongoDB Inc.
Agreed, renamed.

2021-03-26 12:00 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> -
I agreed that it's better, we just usually don't do it, if we're talking about significant changes, since it makes the git history and reviewing harder. However I don't insist, I will rely on you and @JamesKovacs  here

2021-03-26 12:04 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            Ensure.IsBetween(count, 0, 1024, nameof(count));
99.9% (Maybe even 100%) constants in our code are from the spec, so looking at this line, we may assume (after some time) that it's the same case which is not. So, I think it's better to add a comment about why it's added and that this is not the spec requirement

2021-03-26 17:21 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            Ensure.IsBetween(count, 0, 1024, nameof(count));
Added a comment.

2021-03-26 20:52 UTC, stIncMale commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +                    }
I see, thanks.

2021-03-26 20:56 UTC, stIncMale commented on tests/MongoDB.Bson.TestHelpers/Threading/ThreadPerTaskScheduler.cs
> +    // https://code.msdn.microsoft.com/Samples-for-Parallel-b4b76364/sourcecode?fileId=44488&pathId=2098696067
I am unable to resolve discussions (even started by me) in this PR (probably because I am not among reviewers anymore, but that's not a reasonable behaviour of the UI), so I will have to mark resolved discussions with the "Resolved" comment.

Resolved.

2021-04-06 00:04 UTC, JamesKovacs requested changes
The PR was difficult to review because refactoring changes were mixed into code changes. While both sets of changes are valid, it was difficult to differentiate new/modified code from code that was simply moved from one place to another. It would be much easier to review if we kept refactoring changes separate from implementation changes.

That said, I did notice an existing bug in our connection pool pruning logic where we skip connections during the pruning process. I see that CSHARP-3380 addresses this issue.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private CancellationTokenSource _signalCancelationTokenSource;
Good catch. done.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/MongoCoreDefaults.cs
> +    internal static class MongoInternalDefaults
Tnx, done.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +    internal sealed partial class ExclusiveConnectionPool : IConnectionPool
As we are exceeding 1K lines in single file, it become unmanageable. We got more changes coming up in helper classes btw. It's a good use case for partial files, so I suggest making `ExclusiveConnectionPool` first and exclusive (for now) partial class.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                        // TODO: log this, but don't throw... it's a bug if we get here
That's TODO from old code. And we don't have logging yet.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    for (int i = 0; i < _connections.Count; i++)
Good catch. Addressed in subsequent PR.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            private readonly List<PooledConnection> _connections;
There is not particular global ordering guaranteed, as connections are checked out and checked in into the pull randomly. Also ordering is non-goal here, and can be changed in the future if needed.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                        // TODO: log this, but don't throw... it's a bug if we get here
That's TODO from old code. And we don't have logging yet.

2021-04-07 00:30 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> -
I think partial classes have their place when used wisely. In this case it's a useful feature that allows us to split the main class and helpers to different files and increase readability.
In the case of `ConnectionPool`, most/all of helpers classes have no practical value outside `ConnectionPool` and are deeply integrated with `ConnectionPool` class itself. Therefore refactoring to standalone files is harder than it might seem, and also does not seem to achieve any significant benefit.

2021-04-08 18:16 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
> +        private static class Schema
It's an interesting technique to define the expected schema in this way. I'm not too concerned that it is different than our typical use of literal constants since this is in test code. It would be simple enough to rewrite it later if it leads to confusion. Let's keep it this way for now as I like the refactorability of it.

2021-04-08 18:16 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                        // TODO: log this, but don't throw... it's a bug if we get here
That's frustrating that we have old TODOs in this code that were never addressed. But fair enough that your PR isn't the place to address them.

2021-04-08 18:17 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +    internal sealed partial class ExclusiveConnectionPool : IConnectionPool
I agree that >1 KLOC in a single file is getting unmanageable. I definitely prefer more concise source files. What about refactoring the helper classes into their own classes rather than making them private nested child classes? The problem with private nested child classes is that they are difficult to test. I would like to see them broken out and tested properly.

2021-04-08 18:22 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            private readonly List<PooledConnection> _connections;
Although connections are checked in and out of the pool as needed, the net effect will be LIFO ordering such that idle connections will remain idle and available for reaping. Are there cases during the check in/out process where LIFO ordering isn't respected? Just curious.

2021-04-08 18:24 UTC, JamesKovacs requested changes
Just a question or two to answer and then we're good to go.

2021-04-08 21:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +    internal sealed partial class ExclusiveConnectionPool : IConnectionPool
I agreed that we can make this in the scope of a new ticket, but then I would suggest not doing it now and revert these changes. Still will rely on consensus decision between 3 of us

2021-04-08 21:12 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public void Dispose()
it's not a private method :)

2021-04-09 00:13 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public void Dispose()
Replaced.

2021-04-09 00:20 UTC, DmitryLukyanov approved these changes
LGTM, great job!

2021-04-16 19:50 UTC, JamesKovacs approved these changes
LGTM.

2021-04-19 15:59 UTC, merged