CSHARP-3370: Document Versioned API Usage in Drivers
mongodb/mongo-csharp-driver pull request #458
Opened 2021-02-16 18:54 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3370

2021-02-16 21:31 UTC, DmitryLukyanov commented on Docs/reference/content/reference/driver/versioned_api.md
> +{{% note %}}Currently there are no deprecations in version 1, so theoretical example is used.{{% /note %}}
Am I right that the 4th point from the ticket description is missed?

2021-02-18 17:01 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-02-18 17:01 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +{{% note %}}Currently there are no deprecations in version 1, so theoretical example is used.{{% /note %}}
Yep, I just checked and added it.

2021-02-18 17:05 UTC, DmitryLukyanov approved these changes
LGTM

2021-02-19 16:27 UTC, rstam requested changes
Mostly good. Minor changes requested.

2021-02-19 16:27 UTC, rstam commented on Docs/reference/content/reference/driver/versioned_api.md
> +The [`ServerApiVersion`]({{< apiref "T_MongoDB_Driver_Core_ServerApiVersion" >}}) is a required parameter of [`ServerApi`]({{< apiref "T_MongoDB_Driver_Core_ServerApi" >}}) and represents the version
Minor phrasing improvement:

    The [`ServerApiVersion`]({{< apiref "T_MongoDB_Driver_Core_ServerApiVersion" >}}) is a required parameter of type [`ServerApi`]({{< apiref "T_MongoDB_Driver_Core_ServerApi" >}}) and represents the version number that the server should behave in compatiblity with. Currently only version 1 is available. It can be acquired via a static property:

2021-02-19 16:27 UTC, rstam commented on Docs/reference/content/reference/driver/versioned_api.md
> +The strict flag is optional and defaults to false. Setting true causes commands (or their specific behavior, like command options or aggregation pipeline stages) to fail if they are not part of the d
Minor phrasing improvement:

    The `strict` flag is optional and defaults to false. Setting `strict` to true causes commands (or their specific behavior, like command options or aggregation pipeline stages) to fail if they are not part of the declared API version.

2021-02-19 16:27 UTC, rstam commented on Docs/reference/content/reference/driver/versioned_api.md
> +### Deprecation errors flag
Suggestion:

    ### DeprecationErrors flag

2021-02-19 16:27 UTC, rstam commented on Docs/reference/content/reference/driver/versioned_api.md
> +The deprecation errors flag is optional and defaults to false. Setting true causes commands (or their specific behavior) to fail with APIDeprecationError if they are deprecated in declared API versio
Minor phrasing improvement:

    The `deprecationErrors` flag is optional and defaults to false. Setting `deprecationErrors` to true causes commands (or their specific behavior) to fail with an error if they are deprecated in the declared API version.

2021-02-19 16:27 UTC, rstam commented on Docs/reference/content/reference/driver/versioned_api.md
> +{{% note %}}Currently there are no deprecations in version 1, so theoretical example is used.{{% /note %}}
Minor phrasing improvement:

    {{% note %}}Currently there are no deprecations in version 1, so a theoretical example is used.{{% /note %}}

2021-03-01 18:39 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-03-01 18:39 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +The [`ServerApiVersion`]({{< apiref "T_MongoDB_Driver_Core_ServerApiVersion" >}}) is a required parameter of [`ServerApi`]({{< apiref "T_MongoDB_Driver_Core_ServerApi" >}}) and represents the version
Done

2021-03-01 18:39 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +The strict flag is optional and defaults to false. Setting true causes commands (or their specific behavior, like command options or aggregation pipeline stages) to fail if they are not part of the d
Done

2021-03-01 18:39 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +### Deprecation errors flag
Done

2021-03-01 18:39 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +The deprecation errors flag is optional and defaults to false. Setting true causes commands (or their specific behavior) to fail with APIDeprecationError if they are deprecated in declared API versio
Done

2021-03-01 18:39 UTC, MikalaiMazurenka commented on Docs/reference/content/reference/driver/versioned_api.md
> +{{% note %}}Currently there are no deprecations in version 1, so theoretical example is used.{{% /note %}}
Done

2021-03-02 23:19 UTC, rstam approved these changes
LGTM

2021-03-08 13:11 UTC, merged