CSHARP-3422: Change estimatedDocumentCount() to use the $collStats Agg Stage Instead of Count Command.
mongodb/mongo-csharp-driver pull request #469
Opened 2021-03-02 01:53 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/603d9a267742ae71684b20ab

2021-03-02 02:08 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/tests/README.rst
> +"errInfo" is propagated
missed this prose test, will add this in the next commit

2021-03-02 18:52 UTC, DmitryLukyanov commented
NOTE: I didn't include version api changes in this PR since related changes are not in the master, but I checked them in the different commit(see above).

* The current PR's EG:
-  https://evergreen.mongodb.com/version/603e893b0305b971a2fcd648
* Merged with VersionApi changes: 
- EG: https://evergreen.mongodb.com/version/603e88c1306615468048fb35
- Commit: https://github.com/DmitryLukyanov/mongo-csharp-driver/commits/csharp3422_merged

2021-03-02 18:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/tests/README.rst
> +"errInfo" is propagated
false alarm, this was implemented previosly

2021-03-02 23:17 UTC, rstam requested changes
I only did a quick review. Don't replace either of the existing reviewers with me.

2021-03-02 23:17 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/SemanticVersion.cs
> +        internal SemanticVersion AsReleasedSemanticVersion => new SemanticVersion(_major, _minor, _patch);
I would make this a method.

Properties typically do no work and return properties of the current instance.

While the work being done here is small, it is a **conversion** operation that returns a totally new instance of `SemanticVersion` and not a property of the current instance.

2021-03-02 23:17 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/CountOperation.cs
> +        // private methods
Put these methods in the right order.

2021-03-02 23:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemanticVersion.cs
> +        internal SemanticVersion AsReleasedSemanticVersion => new SemanticVersion(_major, _minor, _patch);
I made this change as a quick solution, depending on Drivers-1591, this can be removed. But if not so, I will change it.

2021-03-04 17:28 UTC, MikalaiMazurenka requested changes
Great changes overall! I have just a few suggestions.

2021-03-04 17:28 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
> +            // TODO: use failpoints to force a timeout?
I think this should be covered in integration tests (I mean unified tests).

2021-03-04 17:28 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEstimatedDocumentCountOperation.cs
> +        }
Consider the refactored method which follows the style of other operations:
```
public UnifiedEstimatedDocumentCountOperation Build(string targetCollectionId, BsonDocument arguments)
{
	var collection = _entityMap.GetCollection(targetCollectionId);

	EstimatedDocumentCountOptions options = null;

	foreach (var argument in arguments ?? Enumerable.Empty<BsonElement>())
	{
		switch (argument.Name)
		{
			case "maxTimeMS":
				options ??= new EstimatedDocumentCountOptions();
				options.MaxTime = TimeSpan.FromMilliseconds(argument.Value.AsInt32);
				break;
			default:
				throw new FormatException($"Invalid EstimatedDocumentCountOperation argument name: '{argument.Name}'.");
		}
	}

	return new UnifiedEstimatedDocumentCountOperation(collection, options);
}
```

2021-03-04 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +            get => _collectionNamespace;
actually, it is not true, we use it a lot. Maybe it makes sense to not use it in the old files(but we do at least sometimes) with old format, but it looks fine for the new files

2021-03-04 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                        // a NamespaceNotFound(26) error will be returned during execution. Drivers MUST interpret the server error code 26 as a 0 count.
this comment is copied from the documentation

2021-03-04 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +        private IExecutableInRetryableReadContext<IAsyncCursor<BsonDocument>> CreateAggregationOperation(SemanticVersion serverVersion)
this file works either with CountOperation(old servers) or Aggregation operation(>=4.9), so this corresponds to it

2021-03-04 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +            IEnumerable<BsonDocument> CreateAggregationPipeline() =>
it's not private, it's local :) I consider this line like a self-commented code, maybe it's clear in your code also, but this method definitely has its own goal, so this goal is moved into a different area(method), and based on the name of the method, it's clear what the goal is. 

I don't have a strong opinion here, but I would say the way it's written originally is not bad, if you still feel that it should be changed, we can discuss it

2021-03-04 18:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                _ => throw new MongoClientException($"Expected aggregate command for {nameof(EstimatedDocumentCountOperation)} to return 1 document, but got {result.Count}."),
it's copied from here https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Operations/CountDocumentsOperation.cs#L239

2021-03-04 18:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
> +﻿/* Copyright 2013-present MongoDB Inc.
oh :(

2021-03-04 18:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
> +            AssertCommandDocument(result, readConcern: !readConcern.IsServerDefault ? readConcern.ToBsonDocument() : null);
will do

2021-03-04 18:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
> +            // TODO: use failpoints to force a timeout?
All, these tests are copied with small refactoring from `CountDocumentsOperationTests`. 
I don't think that it's related to unified tests at all. We may or may not have such a test there, I think the original idea of this comment was to try checking this behavior with a fail point, but probably it's overkill here since the name of the test only about setting `MaxTime`. The integration test to check how this value actually works with the server should be a different test (in this file or in any other place). So, I agree that this should be removed

2021-03-04 18:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEstimatedDocumentCountOperation.cs
> +        }
I don't think that settings this value `options ??= new EstimatedDocumentCountOptions();
` (even though now we have only one option) for all options is a good idea. It's fine to create an empty options field since we did this all the time previously

2021-03-04 18:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/Unified/CrudUnifiedTestRunner.cs
> +                        var name = $"{testCase.Name}:async={async}";
this is not necessary, since:
1. This test runner works only with the crud tests.
2. This is how it looks like in the test explorer: 
![image](https://user-images.githubusercontent.com/44870738/110011467-8b114880-7d30-11eb-9877-ed244e47eceb.png)
so, adding a double path looks wrong anyway
3. If you need a path in the JsonDrivenTestCase you should check `testCase.Test["_path"]`

2021-03-04 18:34 UTC, DmitryLukyanov commented
In the next commit I will apply the suggestions and will make rebasing on the current master

2021-03-04 20:29 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/Unified/CrudUnifiedTestRunner.cs
> +﻿/* Copyright 2021-present MongoDB Inc.
One more suggestion. Move the file up to `crud` folder.

2021-03-04 21:34 UTC, JamesKovacs requested changes
Minor suggestions.

2021-03-04 21:34 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +    public class EstimatedDocumentCountOperation : IReadOperation<long>
Since `CountOperation` adds support for `IExecutableInRetryableReadContext<T>`, shouldn't `EstimatedDocumenCountOperation` do so as well?

2021-03-04 21:34 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +            get => _collectionNamespace;
For getter-only properties, `public CollectionNamespace CollectionNamespace => _collectionNamespace;` is more common in our code base for new code.

2021-03-04 21:36 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +            get => _collectionNamespace;
Yeah, I misunderstood Mikalai's suggestion, will do it in the next commit

2021-03-04 21:40 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +    public class EstimatedDocumentCountOperation : IReadOperation<long>
We have enough other operations that don't implement this interface explicitly, so I would say not really. The only reason why it's added for CountOperation is to be able to call IExecutableInRetryableReadContext.Execute inside EstimatedDocumentCountOperation

2021-03-08 12:42 UTC, DmitryLukyanov reviewed
EG: https://evergreen.mongodb.com/version/604530272fbabe49ef3dfc40

2021-03-08 12:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                    return ExtractCountFromAggregationResult(result);
done

2021-03-08 18:34 UTC, rstam requested changes
Looks good. Requesting a few minor changes.

2021-03-08 18:34 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/CountOperation.cs
> +    public class CountOperation : IReadOperation<long>, IExecutableInRetryableReadContext<long>
I don't know what "BL point of view" means...

2021-03-08 18:34 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +    public class EstimatedDocumentCountOperation : IReadOperation<long>
Dmitry and I discussed this earlier.

Operations that create child operations are indirectly retryable (without needing to implement the `IExecutableInRetryableReadContext` interface) if the child operations are retryable.

2021-03-08 18:34 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                    var result = cursor.ToList(cancellationToken);
Name this variable `results` (plural) because the value is a list (even though we expect it to normally contain one element).

2021-03-08 18:34 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                    var result = await cursor.ToListAsync(cancellationToken).ConfigureAwait(false);
Name this variable `results` (plural) because the value is a list (even though we expect it to normally contain one element).

2021-03-08 18:34 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +        private long ExtractCountFromAggregationResult(List<BsonDocument> result) =>
Name this parameter `results` (plural) because the value is a list (even though we expect it to normally contain one element).

Consider renaming the method name to `ExtractCountFromAggregationResults` (plural) also.

2021-03-08 18:36 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CountOperation.cs
> +    public class CountOperation : IReadOperation<long>, IExecutableInRetryableReadContext<long>
"business logic", I meant that this is a technical change

2021-03-08 19:30 UTC, rstam approved these changes
LGTM

2021-03-08 22:57 UTC, JamesKovacs approved these changes
LGTM

2021-03-10 15:19 UTC, MikalaiMazurenka approved these changes
LGTM

2021-03-10 16:02 UTC, merged