CSHARP-3304: Consider server load during server selection
mongodb/mongo-csharp-driver pull request #474
Opened 2021-03-11 22:55 UTC by BorisDog

2021-03-15 01:28 UTC, DmitryLukyanov reviewed
Initial review

2021-03-15 01:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            private IClusterableServer SelectServerByOperationsCount(List<IClusterableServer> servers)
It looks like this logic still can be moved into server selector similar to:

      /// <summary>
    /// TODO
    /// </summary>
    public class OperationCountServerSelector : IServerSelector
    {
        #region static
        /// <summary>
        /// TODO
        /// </summary>
        /// <param name="servers"></param>
        /// <returns></returns>
        private static (EndPoint ServerAddress, int Count)[] SomePrepareStuff(IClusterableServer[] servers)
        {
            return servers.Select(s => (s.EndPoint, s.OutstandingOperationsCount)).ToArray();
        }

        /// <summary>
        /// TODO
        /// </summary>
        /// <param name="servers"></param>
        /// <returns></returns>
        public static IServerSelector Create(IClusterableServer[] servers)
        {
            var inputData = SomePrepareStuff(servers);
            return new OperationCountServerSelector(inputData);
        }
        #endregion

        private readonly (EndPoint ServerAddress, int Count)[] _serverAndPoolDescriptions;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="serverAndPoolDescriptions">TODO</param>
        public OperationCountServerSelector((EndPoint ServerAddress, int Count)[] serverAndPoolDescriptions)
        {
            _serverAndPoolDescriptions = serverAndPoolDescriptions;
        }

        /// <summary>
        /// TODO
        /// </summary>
        /// <param name="cluster"></param>
        /// <param name="servers"></param>
        /// <returns></returns>
        public IEnumerable<ServerDescription> SelectServers(ClusterDescription cluster, IEnumerable<ServerDescription> servers)
        {
            if (_serverAndPoolDescriptions.Length != servers.Count())
            {
                // TODO: ?
            }

            return servers
                .Select(
                    s =>
                    {
                        var poolDescription = _serverAndPoolDescriptions.Single(d => EndPointHelper.Equals(d.ServerAddress, s.EndPoint));
                        return new
                        {
                            ServerDescription = s,
                            OperationsCount = poolDescription.Count
                        };
                    })
                .OrderBy(c=>c.OperationsCount)
                .Select(s=>s.ServerDescription);
        }
    }

2021-03-15 01:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            private IClusterableServer SelectServerByOperationsCount(List<IClusterableServer> servers)
where the missed information is provided through ctor. So we will need to create a new instance of this selector in each attempt

2021-03-15 01:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                while (selectedServers.Count > 0 && clusterableServers.Count < 2)
can you elaborate on why you expect not bigger than 2 severs here?

2021-03-15 01:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
>                          __randomServerSelector.SelectServers(_description, selectedServers).Single();
as far as I understood the ticket description, the target of this ticket is the replacement of this randomSelector

2021-03-15 01:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
>                          __randomServerSelector.SelectServers(_description, selectedServers).Single();
so, the natural way to reach this is by moving connectionPool description to the ServerDescription, let's try to discuss this tomorrow with @rstam  once again before giving up here

2021-03-15 10:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
>                          __randomServerSelector.SelectServers(_description, selectedServers).Single();
Other options to consider (I don't say that they're better than the previous ones):
1. Add a method to the server description like: `GetConnectionDescriptionState`. This will call some delegate (?) which is filled on the server-side and return the required count
2. Add an event on the server-side like `ConnectionDescriptionChnaged` and handle this on the cluster side

2021-03-15 15:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                while (selectedServers.Count > 0 && clusterableServers.Count < 2)
Resolved. I missed this in the spec.

2021-03-15 15:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
>                          __randomServerSelector.SelectServers(_description, selectedServers).Single();
Discussed offline, the current way is the simplest

2021-03-15 15:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            private IClusterableServer SelectServerByOperationsCount(List<IClusterableServer> servers)
The above selector should be updated to reflect the spec requirements about choosing only 2 random servers

2021-03-17 23:06 UTC, JamesKovacs reviewed
Overall looking good. I added comments with my questions/concerns.

2021-03-17 23:06 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +            public static readonly string mocked_topology_state = nameof(mocked_topology_state);
Why is this file using snake case for field names?

2021-03-18 18:59 UTC, DmitryLukyanov reviewed
Is this prose test https://github.com/mongodb/specifications/commit/07790d1978ebe6b8ff7f574c9ac5e1365dd16e26#diff-8b993a775e4afe3d3151060c3903f9a1abb803ab0a3e314a2dcd79bf3e6cb272R279 implemented?

2021-03-18 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                    var selectedServerDescription = selectedServers.Count == 1 ?
also, expected formatting here:

                    var selectedServerDescription = selectedServers.Count == 1
                        ? selectedServers[0]
                        : __randomServerSelector.SelectServers(_description, selectedServers).Single();

2021-03-18 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
> +    internal sealed class OperationsCountServerSelector : IServerSelector
the rest of serverSelectors are public because they're expected to possibly be configured from the user side, but maybe in this particular case because of ctor this class is too internal for this, not sure. @JamesKovacs what do you think?

2021-03-18 18:59 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +            if (type.StartsWith(Schema.TopologyDescription.ClusterType.ReplicaSet))
switch?

2021-03-18 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +            private readonly InterlockedInt32 _state;
it sounds like we don't use `Open` state which can be confusing, do we really need this change?

2021-03-18 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            private readonly List<ServerDescription> _connectedServersDescriptions;
Can we remove this and use only `_connectedServers`?  ServerDescription is a field in a server

2021-03-18 18:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                if (selectedServers.Any())
as I remember `Any` calls GetEnumerator which then calls `Dispose`, this is why we try to avoid Linq methods if possible and use the Count property

2021-03-19 03:10 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +                var name = GetTestCaseName(document, document, 0);
Good suggestion, done.

2021-03-19 03:10 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +            if (type.StartsWith(Schema.TopologyDescription.ClusterType.ReplicaSet))
Unfortunately schema values are not consts but readonly.

2021-03-19 03:10 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +            if (type == Schema.TopologyDescription.ServerType.RSPrimary)
Unfortunately schema values are not consts but readonly.

2021-03-19 13:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        private int _outstandingOperationsCount;
I think this is exactly the same case as we have with the server, I don't believe that anyone uses our pool interface. My suggestion will simplify the server logic since now we won't need to calculate the pool-related information on the server-side. Since we already have this data in the pool. Also, It will make the server logic easier since we won't need to "spread" logic to calculate one field across the server.cs(in several different parts of the server.cs). If you and @JamesKovacs disagreed with this, I won't insist.

2021-03-19 13:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                    .Throws(new TimeoutException("Timeout"));
As far as I can see, SemaphoreSlim doesn't trigger a timeout exception (I missed something?)

>We don't really need to care about the exception details here.

 I think it's a bit more important. The test can be investigated to understand the underlying driver logic, so the test described behavior should not contradict what the test can do.

2021-03-19 13:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +            public static readonly string mocked_topology_state = nameof(mocked_topology_state);
Maybe not exactly this line, but you use deserialization below: `BsonSerializer.Deserialize<OperationsCount>`. I just want to say that this contradicts to how other test runners look like and I don't really see the reason for this yet

2021-03-19 13:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            private readonly List<ServerDescription> _connectedServersDescriptions;
For simplicity, I would say it's better to avoid handling "the same" entities twice :) Line 516 is the only place when we need this field so the target here can be reached via:

               var selectedServers = _selector
                    .SelectServers(_description, _connectedServers.Select(s=>s.Description))
                    .ToList();

2021-03-19 13:48 UTC, DmitryLukyanov commented
> 
> 
> Is this prose test [mongodb/specifications@07790d1#diff-8b993a775e4afe3d3151060c3903f9a1abb803ab0a3e314a2dcd79bf3e6cb272R279](https://github.com/mongodb/specifications/commit/07790d1978ebe6b8ff7f574c9ac5e1365dd16e26#diff-8b993a775e4afe3d3151060c3903f9a1abb803ab0a3e314a2dcd79bf3e6cb272R279) implemented?

@BorisDog  have you had a chance to look at this?

2021-03-19 13:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +            private readonly InterlockedInt32 _state;
not sure what is the best way here (maybe two state classes with inheritance?), but at least let's add a comment that we're not going to use `Open` state

2021-03-19 13:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                _connectedServerDescriptions.Clear();
nit: these lines are not really needed since we call `SelectServer` only once, but maybe it worth having this also

2021-03-19 16:39 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +            public static readonly string mocked_topology_state = nameof(mocked_topology_state);
Right, using `BsonSerializer.Deserialize<Outcome>` as well. I find it very convenient to define the schema and object model in one place, and to deserialize it directly.

2021-03-19 16:39 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +            if (type.StartsWith(Schema.TopologyDescription.ClusterType.ReplicaSet))
nice, done. tnx!

2021-03-19 16:39 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +            JsonDrivenHelper.EnsureAllFieldsAreValid(testDefinition, Schema.RootFields);
I find that defining the schema in single place and using predefined sets as `Schema.RootFields`  greatly increases readability, and simplifies future alterations if any.

2021-03-19 17:32 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +                    .Throws(new TimeoutException("Timeout"));
Thanks, @BorisDog for clarification, I missed place where we trigger timeout exception in the pool

2021-03-19 17:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                _connectedServerDescriptions.Clear();
got it

2021-03-30 13:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +           RSPrimary = ServerType.ReplicaSetPrimary,
incorrect tabs

2021-03-30 13:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        public void SelectServer_loadbalancing_prose_test([Values(false, true)] bool async)
My impression about this test:
1. We don't really understand what happens here since auth variants unexpectedly don't work
2. Also, all prose tests before were really straightforward in meaning that it was enough to use only high-level API, in your implementation you use methods like `GetChannel` that I would not expect here.

Since we're going to investigate this further, I would move the whole prose test to the new ticket and check them there. cc: @JamesKovacs

2021-03-30 13:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +            if (CoreTestConfiguration.ConnectionString.Tls == true &&
this way probably should work also, but this is a condition which we use to determine auth variant: ` CoreTestConfiguration.ConnectionString.Username != null;`

2021-03-30 22:55 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +
Thanks, fixed.

2021-03-30 22:55 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/ServerSelectionTestHelpers.cs
> +           RSPrimary = ServerType.ReplicaSetPrimary,
Good catch, fixed

2021-03-30 22:55 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +            if (CoreTestConfiguration.ConnectionString.Tls == true &&
Thanks, done.

2021-03-30 22:55 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        public void SelectServer_loadbalancing_prose_test([Values(false, true)] bool async)
This test works well on not Win Auth topologies, so I'd prefer to investigate the problematic topologies in scope of a new ticket, and have the test running on all other topologies.

2021-03-31 10:56 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        public void SelectServer_loadbalancing_prose_test([Values(false, true)] bool async)
mostlikely because we run auth tests only on windows yet :)

2021-03-31 18:25 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
> +        public IEnumerable<ServerDescription> SelectServers(ClusterDescription cluster, IEnumerable<ServerDescription> servers)
Ah yes. If it's part of the public interface, then we are kind of stuck. We have to maintain the public interface definition even if it is unlikely that external parties would have implemented their own.

2021-03-31 18:28 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                connection = _connectionPool.AcquireConnection(cancellationToken);
Gotcha. Missed the `throw;` at the end of the catch.

2021-03-31 18:28 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                connection = await _connectionPool.AcquireConnectionAsync(cancellationToken).ConfigureAwait(false);
Missed the rethrow.

2021-03-31 18:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        public void SelectServer_loadbalancing_prose_test([Values(false, true)] bool async)
Agreed on both counts.

2021-03-31 23:17 UTC, JamesKovacs requested changes
Some minor changes requested.

2021-03-31 23:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        private int _outstandingOperationsCount;
ok, then this is resolved

2021-04-01 18:36 UTC, DmitryLukyanov approved these changes
See my last comments, then LGTM

2021-04-01 18:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        public void SelectServer_loadbalancing_prose_test([Values(false, true)] bool async)
ok, i will approve this now and will make the more deep check in the next ticket

2021-04-01 18:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +    public class ClusterTests
call it ServerSelectionProseTests

2021-04-01 18:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +                RequirePlatform.GetCurrentOperatingSystem() == SupportedOperatingSystem.Windows)
I think Windows is not necessary here, and we will see the same behavior on all auth variants when we run this, so I would say, it's enough to say just: `RequireServer.Check().Authentication(false)`

2021-04-01 18:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +                RequirePlatform.GetCurrentOperatingSystem() == SupportedOperatingSystem.Windows)
or: `RequirePlatform.Check().SkipWhen(() => CoreTestConfiguration.ConnectionString.Username != null, SupportedOperatingSystem.Windows);`, but the first one looks enough to me

2021-04-01 18:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +        private static readonly HashSet<string> __commandsToNotCapture = new HashSet<string>
we definitely should do something with these commands at some point, we keep copying them all the time

2021-04-01 18:52 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Specifications/server-selection/InWindowTestRunner.cs
> +            public static readonly string mocked_topology_state = nameof(mocked_topology_state);
Now I understand what you're doing. Basically creating strongly-typed string constants. Interesting technique. I'm OK with it.

2021-04-01 20:18 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
> +    internal sealed class OperationsCountServerSelector : IServerSelector
Not sure about exposing it publicly. As it relies on the functionality of `IClusterableServer` which is intended to be internal and is public only due historic reasons. Further more, we will probably consider converting all pseudo-internal API to internal in v3, so it's better to avoid expanding pseudo-internal API when possible.

2021-04-01 20:18 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        int IClusterableServer.OutstandingOperationsCount => Interlocked.CompareExchange(ref _outstandingOperationsCount, 0, 0);
Good catch. Leftovers from refactoring. Fixed.

2021-04-01 22:45 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Clusters/ServerSelectors/OperationsCountServerSelector.cs
> +    internal sealed class OperationsCountServerSelector : IServerSelector
I'll mark this as resolved. If a user needs this public for custom configuration reasons, they can file a JIRA issue to request it. I think the risk is low and I prefer not expanding our API surface anymore than is necessary.

2021-04-01 22:46 UTC, JamesKovacs approved these changes
LGTM

2021-04-02 03:25 UTC, merged