CSHARP-3341: Update Astrolabe to use the unified test runner.
mongodb/mongo-csharp-driver pull request #476
Opened 2021-03-22 19:36 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/6058ec1e2a60ed2200ec9e0a

2021-03-22 20:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatProcessor.cs
> +        private void CreateAndRunOperation(BsonDocument operationDocument, bool async, CancellationToken cancellationToken)
this is renamed. Previously this naming was `AssertOperation` that is really confusing. Actually assert happens even not in each `case`, so renamed it to represent the actual action here

2021-03-22 20:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatProcessor.cs
> +        private void CreateAndRunOperation(BsonDocument operationDocument, bool async, CancellationToken cancellationToken)
Also, I think this logic is incorrectly mixed with the lower test levels, but this refactoring was out of the scope in this ticket, so left it as is

2021-03-22 20:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatProcessor.cs
> +            CancellationToken terminationCancellationToken = default)
termination cancellationToken has quite unusual handling and allows only reading a state whether the loop test should be stopped or no. This is a bit astrolabe specific option, but in the current implementation we don't have control over changing only particular methods in the test runner "processor", so needed to add this as a global field. I actually had a hard time to work with this design to, as much as possible, avoid the particular test related details on the common level. Not sure that we need to do the same thing next time

2021-03-22 20:33 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> -            Console.WriteLine($"Done.");
should be restored

2021-03-24 14:20 UTC, MikalaiMazurenka requested changes
Please apply the partial refactoring in my branch: https://github.com/MikalaiMazurenka/mongo-csharp-driver/tree/csharp3341-refactored

2021-03-24 14:20 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, BsonArray> _errorDocumentsMap;
There are many unnecessary changes in the file. Please refer to refactor branch

2021-03-25 20:47 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatProcessor _unifiedTestFormatTestRunner = new UnifiedTestFormatProcessor();
Dmitry and I were discussing this offline. I think it's OK to separate the following two concerns:

1. Selecting and loading the JSON test files
2. Executing the tests defined by those JSON files

The reason to separate the concerns is that while we load JSON files in several places, it is good for the "execution" of those tests to be separated from the "loading" of them.

2021-03-25 20:47 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatProcessor _unifiedTestFormatTestRunner = new UnifiedTestFormatProcessor();
Whether it's in scope or not is a separate question I suppose.

2021-03-25 20:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        /// <summary>
I'd like other opinions on whether this is the best name for this property.

It's not wrong, by maybe there is a better one.

2021-03-25 20:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/ServerOpeningEvent.cs
> +        private readonly DateTime _observedAt;
I had the same thought... but `struct` can't have a base class.

2021-03-25 20:47 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstralabeEventsHandler.cs
> +    public static class AstralabeEventsHandler
We have often used static classes for helper classes.

As long as the class has no state I'm OK with static classes used to contain static helper methods.

2021-03-25 20:47 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
> +    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
How are you using `dynamic` types?

2021-03-25 22:11 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatProcessor _unifiedTestFormatTestRunner = new UnifiedTestFormatProcessor();
My question in the chat was also about when we should do it, now or on a different ticket. I don't mind about a different ticket, but I assume this ticket will be with the low priority and we can just not take this into work. Then we will have a small outstanding technical debt

2021-03-25 22:11 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            var client = CreateClient(entity, id, clientEventCapturers);
I refactored this a bit, but I think it's a natural expectation that `CreateClient` actually returns a created client. out variables contains additional created details

2021-03-26 23:03 UTC, BorisDog reviewed
Initial review.

2021-03-26 23:03 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            List<(string Key, IEnumerable<string> Events, List<string> CommandNotToCapture)> eventTypesToCapture = new ();
I love that tuples provide very convenient logical grouping.

2021-03-29 16:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public Dictionary<string, BsonArray> ErrorDocumentsMap => _errorDocumentsMap;
My 2 cents, so now when those dictionaries are not read-only anymore, seems that it just exposing them as-is is a good architecture-simpler code balance for the test project.

2021-03-29 23:10 UTC, DmitryLukyanov reviewed
EG: https://evergreen.mongodb.com/version/60625e50d1fe072697ef93e6

2021-03-29 23:10 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +                CommandStartedEvent typedEvent =>
unfortunately, I was wrong and event names in the previous CMAP spec and now are surprisingly different, so moved this code to just a big switch since we cannot have a simple event mapper for the whole codebase

2021-03-29 23:10 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +                    //.Add("reason", typedEvent.Reason) TODO: should be implemented in the scope of CSHARP-3219
i will confirm this case

2021-03-29 23:10 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeTestRunner.cs
> -/* Copyright 2020-present MongoDB Inc.
no longer needed

2021-03-29 23:10 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeWorkloadExecutor.csproj
> +    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
removed

2021-03-29 23:12 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +        public EventCapturer CaptureBySpecName(string specEventName, IEnumerable<string> commandNotTocapture = null, bool useDefaltCommandNotToCapture = true)
Removed

2021-03-29 23:12 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +                throw new Exception(message != null ? message(timeout) : $"Waiting for the expected event exceeded the timeout {timeout}.");
Removed

2021-03-29 23:12 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +            #region static
Removed

2021-03-29 23:14 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +            public static bool ShouldCapture(object @event, IEnumerable<string> commandsNotTocapture, bool useDefaltCommandNotToCapture)
Removed

2021-03-29 23:14 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventsSpecMapper.cs
> +        private static Dictionary<string, Type> __eventsMap = new Dictionary<string, Type>
Removed

2021-03-29 23:16 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstralabeEventsHandler.cs
> +﻿/* Copyright 2021-present MongoDB Inc.
Since apparently, we cannot use a global events mapping, I reorganized this code into just a big switch

2021-03-30 21:58 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var resultsPath = Path.Combine(resultsDir ?? "", "results.json");
nit^2:  `var resultsDir = Environment.GetEnvironmentVariable("RESULTS_DIR") ?? ""; eventsPath = Path.Combine(resultsDir, "events.json");`

2021-03-30 21:58 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var resultDetails = HandleWorkloadResult(entityMap: entityMap);
Are we absolutely sure that `HandleWorkloadResult `and `ExecuteWorkload` can't never crash? Is `AstrolabeWorkloadExecutor` allowed to crash or is it expected to at log it's unhandled exceptions?

2021-03-30 21:58 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                Console.Out.Flush();
Depends on how resilient the runner is supposed to be. For example if just one of the files is locked for any reason, or temporary IO glitch, the whole process will crash, will we able to debug that and see the exception info? Or should we aim to catch and output as much test and error data as we can?

2021-03-30 22:35 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +                throw new Exception(message != null ? message(timeout) : $"Waiting for the expected event exceeded the timeout {timeout}.") ;
nit: extra space.

2021-03-30 22:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime ObservedAt
It the naming accurate? Technically driver does not observe an event, but creates one. Would `Timestamp` be more suitable naming?

2021-03-30 22:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        /// <summary>
Sorry I meant to address my comment to `ObservedAt` property

2021-03-30 22:35 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +            return ((DnsEndPoint)endpoint).Host + ":" + ((DnsEndPoint)endpoint).Port;
nit: 1 cast instead of 2 + string interpolation

2021-03-30 22:35 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +        private static double GetCurrentTimeSeconds(DateTime observedAt) => (double)(observedAt - BsonConstants.UnixEpoch).TotalMilliseconds / 1000;
nit: `((DateTimeOffset)observedAt).ToUnixTimeSeconds();` ?

2021-03-30 22:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                foreach (var operation in _loopOperations.Select(o => o.DeepClone().AsBsonDocument))
Curious, why is `DeepClone` needed? Is operation document modified?

2021-03-30 22:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        public Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken)
Is `ExecuteAsync` supposed to be synchronous? Or is it supposed to receive `createAndRunOperationCallbackAsync` ?

2021-03-30 22:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "time", GetCurrentTimeMilliseconds() }
`((DateTimeOffset)DateTime.Now).ToUnixTimeMilliseconds()` ?

2021-03-30 22:41 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +                throw new Exception(message != null ? message(timeout) : $"Waiting for the expected event exceeded the timeout {timeout}.") ;
yeah, but it's because I reverted this change. We will fix this at some other ticket

2021-03-30 22:42 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +            return ((DnsEndPoint)endpoint).Host + ":" + ((DnsEndPoint)endpoint).Port;
will fix it

2021-03-30 22:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                foreach (var operation in _loopOperations.Select(o => o.DeepClone().AsBsonDocument))
yeah, there was an issue with this, I don't remember details at the top of my mind, but can check it if you want

2021-03-30 22:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "time", GetCurrentTimeMilliseconds() }
will check it

2021-03-31 21:40 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +            return ((DnsEndPoint)endpoint).Host + ":" + ((DnsEndPoint)endpoint).Port;
done

2021-03-31 21:40 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +        private static double GetCurrentTimeSeconds(DateTime observedAt) => (double)(observedAt - BsonConstants.UnixEpoch).TotalMilliseconds / 1000;
doesn't work for net452

2021-03-31 21:40 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        public Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken)
it doesn't really matter since the callback is always sync, the only option that makes difference is setting async value to the callback

2021-03-31 21:40 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "time", GetCurrentTimeMilliseconds() }
it doesn't work for net452

2021-03-31 21:40 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var resultDetails = HandleWorkloadResult(entityMap: entityMap);
in case if something will unexpectedly fail, then the workload also be failed and then astrolabe will notice that workload was closed before expectation and will fail his executing

2021-03-31 23:03 UTC, MikalaiMazurenka requested changes
Please revert back the UnifiedTestRunner changes. They hide the diff which is very uncomfortable to work with.
Please use the refactored version: https://github.com/MikalaiMazurenka/mongo-csharp-driver/tree/csharp3341-refactored-2
It has design improvements, minor fixes and classes revisited from scratch:
1. Program.
2. UnifiedEntityMap
3. UnifiedLoopOperation
4. UnifiedTestRunner

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/IUnifiedWithTransactionOperation.cs
> +        Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken);
see this comment: https://github.com/mongodb/mongo-csharp-driver/pull/476#discussion_r600951810

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public Dictionary<string, BsonArray> ErrorDocumentsMap => _errorDocumentsMap;
>Exposing the dictionaries would lower the maintainability

can you provide a real example of this? As I already told you, you're trying to implement the right idea in the wrong way. See the above comments

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            clients.Add(id, clientDetails.Client);
we discussed this with @BorisDog, we agreed that tuples look better than out arguments since they have some restriction for dynamic functional and in general looks a bit old-style. Anyway, this is subjective, but 2 of us chose tuples

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            }
done

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
as far as I noticed you just don't use this: https://github.com/MikalaiMazurenka/mongo-csharp-driver/blob/dfede020b21d3ec4a8c0ae17c5cd439fec1479c4/tests/AstrolabeWorkloadExecutor/Program.cs#L112 so, your implementation is incorrect

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        }
it's subjective, I like this way because based on the method name, I know what this line does without any additional investigations, so it's self documented-code

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.WriteLine($"dotnet main> Results will be written to {resultsPath},\nEvents will be written to {eventsPath}...");
i don't have any questions to `\n`, however I don't mind, done

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/IUnifiedWithTransactionOperation.cs
> +        Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken);
I don't think that the suggestion with entityMap in the method arguments is better, it's actually just inventing a new approach for the way which is already implemented, so I'm willing to leave the current way

2021-04-01 00:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public Dictionary<string, BsonArray> ErrorDocumentsMap => _errorDocumentsMap;
as for this change: https://github.com/MikalaiMazurenka/mongo-csharp-driver/commit/dfede020b21d3ec4a8c0ae17c5cd439fec1479c4#diff-25f3c865e6e34147ad9fa5b0a2060774fa4516521625b64bcb9fe9a93e76f22cR131 this is still unnecessary and just adds one more abstraction level without any benefits of this

2021-04-01 00:21 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +        public static BsonDocument CreateCommandEventDocument(string eventName, DateTime observedAt, string commandName, int requestId) =>
good catch, done

2021-04-01 00:22 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +    public static class AstrolabeEventsHandler
We should always consider what real advantages or disadvantages we have as well as the previously implemented approaches, so in this particular case, there is nothing wrong with static classes

2021-04-01 00:31 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            }
It's not.

2021-04-01 00:31 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                return testsExecutor.EntityMap;
This comment doesn't resolve my comment.

2021-04-01 00:36 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public Dictionary<string, BsonArray> ErrorDocumentsMap => _errorDocumentsMap;
The benefit is a good design and decoupling.

2021-04-01 00:36 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            clients.Add(id, clientDetails.Client);
@BorisDog which method do you find more readable: the current one or the refactored one (https://github.com/MikalaiMazurenka/mongo-csharp-driver/blob/a5f01e0b7511135fe0808c6eb2d4ebce626a6d9d/tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs#L317)

2021-04-01 00:36 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/IUnifiedWithTransactionOperation.cs
> +        Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken);
The refactoring changed `EntityMap` from `composition` to `aggregation` and resolved the issue you had with a not disposed set of objects.

2021-04-01 00:40 UTC, MikalaiMazurenka requested changes

2021-04-01 00:40 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                allowKillSessions: false,
This is not an excuse for lowering the design quality

2021-04-01 00:40 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +    public class UnifiedTestFormatTestRunner
These changes hide design flaws which you didn't resolve.

2021-04-01 00:40 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
https://github.com/MikalaiMazurenka/mongo-csharp-driver/blob/dfede020b21d3ec4a8c0ae17c5cd439fec1479c4/tests/AstrolabeWorkloadExecutor/Program.cs#L59

2021-04-01 00:41 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            }
sorry, it was unpushed, done

2021-04-01 00:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/IUnifiedWithTransactionOperation.cs
> +        Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken);
>issue you had with a not disposed set of objects.

which one?

2021-04-01 00:58 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                return testsExecutor.EntityMap;
I didn't notice that entityMap is disposable, so I moved the handling of entityMap into the using brackets.

2021-04-01 20:18 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +        private static double GetCurrentTimeSeconds(DateTime observedAt) => (double)(observedAt - BsonConstants.UnixEpoch).TotalMilliseconds / 1000;
Frustrating.
Maybe adding
`public static double ToUnixTimeSeconds(this DateTime datetime) =>(datetime - __unixEpoch).TotalMilliseconds / 1000;`        
to `BsonConstants` would be convenient, and can be reused?

2021-04-01 20:56 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        public Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken)
Then we can just have `ExecuteInternal `to be called from `ExecuteAsync `and `Execute`

2021-04-01 22:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        public Task ExecuteAsync(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, CancellationToken cancellationToken)
done

2021-04-02 16:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private void ThrowIfDisposed()
added this as it was discussed offline

2021-04-02 16:44 UTC, MikalaiMazurenka approved these changes
After more discussion I realized my concerns were invalid. Good job.
LGTM

2021-04-02 16:49 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                foreach (var operation in _loopOperations.Select(o => o.DeepClone().AsBsonDocument))
the issue was about tests like `insert` and similar that set `_id` after the first attempt, so all next attempts will fail with the duplicate key error. I've added a comment to describe this.

2021-04-02 17:29 UTC, BorisDog requested changes

2021-04-02 17:29 UTC, BorisDog commented on src/MongoDB.Bson/BsonUtils.cs
> +        /// <returns>Number of milliseconds since Unix epoch.</returns>
+1

2021-04-02 17:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
>          {
minor: Assert `_entityMap == null`

2021-04-02 17:39 UTC, rstam requested changes
Minor changes suggested.

Feel free to push back on any of these suggestions.

2021-04-02 17:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
When I asked whether `ObservedAt` was the best name or not I was unaware that the spec said to use the name `ObservedAt`.

In that light do you want to revisit the question about what name to use?

I'm not sure what the right answer is here. `ObservedAt` sounded a bit off to me, but if that's what the spec uses maybe we can get used to it?

2021-04-02 17:39 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +            $"{{ name : '{eventName}',  observedAt : '{BsonUtils.ToSecondsSinceEpoch(timestamp)}', address : '{GetAddress(serverId)}'{customJsonNodeWithComma} }}";
There is a mismatch between the JSON (`observedAt`) and the `timestamp` parameter name.

Does this need to be resolved?

2021-04-02 17:39 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                async = true;
Why is true the default?

Perhaps we should throw an exception if this required environment variable is not set.

2021-04-02 17:39 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            // ensure all messages are propagated to the astrolabe time immediately
What does "astrolabe time" mean?

2021-04-02 17:39 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/MongoDB.Driver.Core.TestHelpers.csproj
> +    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
I assume we are OK adding this new dependency?

2021-04-02 17:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +        public UnifiedTestOperationFactory(UnifiedEntityMap entityMap, CancellationToken terminationCancellationToken)
This is awkward... passing in a `CancellationToken` that doesn't apply to any of the existing operations, only to the new `UnifiedLoopOperationBuilder`.

Normally we pass cancellation tokens to methods like `Execute`, not to constructors.

Not sure this is possible, but don't we normally use the `entityMap` as a grab bag of arguments to pass to the operation builders? Should the cancellation token be passed in the `entityMap`?

Just brainstorming here... not necessarily asking that this be changed.

2021-04-02 17:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/IUnifiedWithTransactionOperation.cs
> +    public interface IUnifiedOperationWithCreateAndRunOperationCallback : IUnifiedTestOperation
Rename file to match new interface name.

2021-04-02 17:39 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var resultDetails = ExecuteWorkload(connectionString, driverWorkload, async, cancellationTokenSource.Token);
Consider:

      var (resultsJson, eventsJson) = ExecuteWorkload(connectionString, driverWorkload, async, cancellationTokenSource.Token);

2021-04-02 17:39 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +        private static (string EventsJson, string ResultsJson) HandleWorkloadResult(UnifiedEntityMap entityMap)
Consider renaming to `CreateWorkloadResult`

2021-04-02 17:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
I don't have a strong opinion here, the spec defined the field name for the generated event result and I reflected it [here](https://github.com/DmitryLukyanov/mongo-csharp-driver/blob/csharp3341/tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs#L97), It didn't say about the event's field name directly. So not sure how strong we need to care about this. Also, Timestamp was a preferable naming for @BorisDog . I will be ok with any naming here.

2021-04-02 17:49 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            // ensure all messages are propagated to the astrolabe time immediately
Wrong wording, I meant that the writing time on the c# side should match with timestamps on the EG side, changed on:

>// ensure all messages are propagated to the astrolabe immediately

2021-04-02 17:49 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/MongoDB.Driver.Core.TestHelpers.csproj
> +    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
I would say so, we already have this dependency in other driver projects

2021-04-02 17:51 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
Maybe the events shouldn't have this field at all?

Maybe the `EventCapturer` should be the one recording at what time the event was observed?

Just a thought... it would obviously require some changes to the `EventCapturer` API to record both the `Event` and the time at which it was observed.

Just to be clear: I am not requesting this change necessarily, I just think it's worth thinking about.

2021-04-02 17:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +        public UnifiedTestOperationFactory(UnifiedEntityMap entityMap, CancellationToken terminationCancellationToken)
Anyway, you need to pass this value from the highest level(console app) to the lowest(test) one, so in the highest value, we don't have access to an entityMap before running the test. Also, I would not consider this CancellationToken in a regular way, it has only limited workflow which is: providing a flag to stop iterating the loop, it avoids throwing OperatingCancelationException exception or stopping the current operation. So it's more like a more simple way to use: `Func<bool>`.

2021-04-02 17:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +        public UnifiedTestOperationFactory(UnifiedEntityMap entityMap, CancellationToken terminationCancellationToken)
Also, entityMap reflects the key/values provided by the json file, I would avoid adding some additional technical fields there even if we can refactor this code a bit to use entityMap for that target

2021-04-02 17:58 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var resultDetails = ExecuteWorkload(connectionString, driverWorkload, async, cancellationTokenSource.Token);
cool, I didn't know that this is possible, done

2021-04-02 17:59 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +        private static (string EventsJson, string ResultsJson) HandleWorkloadResult(UnifiedEntityMap entityMap)
done

2021-04-02 18:01 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                async = true;
it was done previously, but I agreed, it should be updated, done

2021-04-02 18:02 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
I think we should try to prioritize our public API namings over our "internal" testing namings where possible. In this case I would guess that `Event.Timestamp` would feel more natural for our users.

I like the `EventCapturer ObservedAt ` suggestion, as it more accurately captures the `ObservedAt ` semantics of the test spec, and eliminates the Events changes. Maybe some internal `EventWrapper` helper can help. But that will require API changes. I guess it's your call @dmitry-lukyanov.

2021-04-02 18:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
I will think about it, will come back to it after the dinner

2021-04-02 19:30 UTC, rstam approved these changes
LGTM

2021-04-02 19:30 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        public DateTime Timestamp
@DmitryLukyanov I remember you had once suggested that adding a `Timestamp` to the `Event` classes would be useful to our users also, so it may well be the best solution to do what you currently have.

Since the spec doesn't say anything about the name of such a property `Timestamp` is fine. The word "observedAt" only appears in the JSON output sent to Astrolabe only, so it's probably no big deal if the names don't match.

Based on all the discussion above I vote to keep what you have right now.

Thanks for the discussion.

2021-04-02 19:30 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +            $"{{ name : '{eventName}',  observedAt : '{BsonUtils.ToSecondsSinceEpoch(timestamp)}', address : '{GetAddress(serverId)}'{customJsonNodeWithComma} }}";
Based on discussion in other comments I think it's OK for them to not mach.

2021-04-02 19:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/MongoDB.Driver.Core.TestHelpers.csproj
> +    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
I don't see this dependency anywhere else.

But everyone else is OK with adding this new dependency I am also.

2021-04-02 19:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +        public UnifiedTestOperationFactory(UnifiedEntityMap entityMap, CancellationToken terminationCancellationToken)
OK. Leave as is.

2021-04-02 19:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/MongoDB.Driver.Core.TestHelpers.csproj
> +    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
sorry, maybe it's not pushed yet, I'm not sure, we definitely discussed the somewhere :)

2021-04-02 21:04 UTC, rstam requested changes
I can LGTM again as is depending on what you think of the new suggestion for AdditionalArgs.

2021-04-02 21:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +        public UnifiedTestOperationFactory(UnifiedEntityMap entityMap, CancellationToken terminationCancellationToken)
Consider the following experiment:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3341-additionalargs

I first tried using the EntityMap to pass down the cancellation token but Dmitry pointed out that the spec says the EntityMap cannot have anything in it that is not in the spec, so I used a `Dictionary<string, object>` called `AdditionalArgs` that can be used to pass any additional args in, not just the Astrolabe cancellationToken.

We can live with the existing code if you want, I just find it awkward to see an Astrolabe specific thing in the UnifiedTest classes.

2021-04-02 21:11 UTC, DmitryLukyanov commented
> 
> 
> I can LGTM again as is depending on what you think of the new suggestion for AdditionalArgs.

the suggested solution works to me, will implement this if no other objections

2021-04-08 22:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +            _eventsFormatter = eventFormatter; // can be null
the above `_subscriber` actually makes the same logic as `_eventsFormatter` now, but I left this as-is for further refactoring later

2021-04-08 22:55 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var additionalArgs = new Dictionary<string, object>()
the below two fields can be moved into a new class like `TestContext` that probably should also include `EntityMap`

2021-04-08 22:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +        object Format(object @event);
maybe it's enough to have only this interface, thoughts?

2021-04-12 22:21 UTC, rstam requested changes

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +    public static class AstrolabeEventsHandler
Rename to `AstrolabeEventHelper`?

Or better yet... move all  these methods to private methods in the `AstrolabeEventFormatter` class.

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
>              var cancellationTokenSource = new CancellationTokenSource();
Rename to `astrolabeCancellationTokenSource`

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +        private static (string EventsJson, string ResultsJson) ExecuteWorkload(string connectionString, BsonDocument driverWorkload, bool async, CancellationToken cancellationToken)
Rename `cancellationToken` to `astrolabeCancellationToken`

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                { "events", new AstrolabeEventsFormatter() }
Do we need a comment that the "events" key is NOT freely chosen but MUST match a key present in the Astrolabe JSON document?

I had no idea that was the case until Dmitry just happened to mention it.

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            using (var testRunner = new UnifiedTestFormatTestRunner(
`UnifiedTestFormatTestRunner` is an xUnit test class, it seems odd to be newing one up.

I think you have a ticket about this Dmitry?

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                eventsFormatter: eventsFormatters))
I thought ALL additional args would go through `additionalArgs` so I was surprised to see `allowKillSessions` and `eventFormatters` as separate arguments.

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
>          private static void CancelWorkloadTask(CancellationTokenSource cancellationTokenSource)
Rename `cancellationTokenSource` to `astrolabeCancellationTokenSource`.

2021-04-12 22:21 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
>          private static void CancelWorkloadTask(CancellationTokenSource cancellationTokenSource)
Same on line 131 on the right (`HandleCancel` parameter)

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            Ensure.IsNull(_entityMap, nameof(_entityMap)); // ensure that we don't call Run more than once
Use an actual `bool` flag (possible name `_runHasBeenCalled`) to track whether `Run` has been called before.

Rather than relying on a subtle side effect of calling Run.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _entityMap = new UnifiedEntityMapBuilder(_eventsFormatters).Build(entities);
Seems like `_entityMap` should have been created in the constructor.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _successCounts;
The spec speaks of the "entity map" as if it was a `Dictionary<string, object>`.

This class is so far away from that it is unrecognizable.

Possible simplification in the future?

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, IEventsFormatter> _eventsFormatters;
Rename to `_eventFormatters`

The `entity` part is singular and the `formatters` part is plural.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public UnifiedEntityMapBuilder(Dictionary<string, IEventsFormatter> eventsFormatters)
Rename parameter to `eventFormatters`

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            var clientDetails = CreateClient(entity);
I really dislike hidden Tuples. Perhaps use:

    var (client, eventCapturers) = CreateClient(entity);

The Tuple itself is unimportant. We are just using it as a vehicle to return two values.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            List<(string Key, IEnumerable<string> Events, List<string> CommandNotToCapture)> eventTypesToCapture = new ();
I'm not as fond of Tuples as others seem to be.

They're fine to return two or more values but often their use results in harder to understand code.

A tuple is not much smarter than a 3 element array.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        eventTypesToCapture.Add((clientId, observeEvents, commandNamesToSkipInEvents));
I assume `clientId` should not be null?

If we had an actual type here instead of a Tuple we could enforce that in the constructor.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private EventCapturer CreateEventCapturer(IEnumerable<string> eventTypesToCapture, IEnumerable<string> commandNamesToSkip, IEventsFormatter eventsFormatter)
Rename last parameter to `eventFormatter`

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
Rename to `_loopCancellationToken`

The name emphasizes that what this token is used to cancel is the loop, not an individual method call.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            CancellationToken terminatorCancellationToken)
Rename to `loopCancellationToken`

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _storeErrorsAsEntity = storeErrorsAsEntity;
Do 51-54 need to be checked for null? Or are nulls valid?

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            Execute(createAndRunOperationCallback, async: true, cancellationToken);
This is NOT async.

It may be async at some point much later in the call stack. Is that enough?

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "error", ex.ToString() },
The result of `ToString` is .NET specific. Will Astrolabe be looking at this string?

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private void Execute(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, bool async, CancellationToken cancellationToken)
Instead of an `async` parameter shouldn't there be an `ExecuteAsync` method?

I'm confused about how and when we're actually doing async tests with Astrolabe.

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminationCancellationToken;
Rename to `_loopCancellationToken`

2021-04-12 22:21 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _terminationCancellationToken = (CancellationToken)Ensure.IsNotNull(additionalArgs, nameof(additionalArgs))["AstrolabeCancellationToken"];
It's a little disturbing to see the word "Astrolabe" in the `MongoDB.Driver.Tests` project which ideally would know nothing about Astrolabe.

Possible alternative neutral key name: `UnifiedLoopOperationLoopCancellationToken`

I know it's a mouthful... :)

2021-04-12 22:29 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            List<(string Key, IEnumerable<string> Events, List<string> CommandNotToCapture)> eventTypesToCapture = new ();
I second that. In fact I had a refactored version of this method without tuples and with other changes which in my opinion helped with readability: https://github.com/MikalaiMazurenka/mongo-csharp-driver/blob/a5f01e0b7511135fe0808c6eb2d4ebce626a6d9d/tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs#L317

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsFormatter.cs
> +    public class AstrolabeEventsFormatter : IEventsFormatter<string>
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventsHandler.cs
> +    public static class AstrolabeEventsHandler
will do it in the next commit

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
>              var cancellationTokenSource = new CancellationTokenSource();
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +        private static (string EventsJson, string ResultsJson) ExecuteWorkload(string connectionString, BsonDocument driverWorkload, bool async, CancellationToken cancellationToken)
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var eventsFormatters = new Dictionary<string, IEventsFormatter>()
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                { "events", new AstrolabeEventsFormatter() }
ok, will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            using (var testRunner = new UnifiedTestFormatTestRunner(
yep, will push these changes as soon as the current ticket will be merged

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
>          private static void CancelWorkloadTask(CancellationTokenSource cancellationTokenSource)
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +    public interface IEventsFormatter
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +    public interface IEventsFormatter<TResult> : IEventsFormatter
will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _entityMap = new UnifiedEntityMapBuilder(_eventsFormatters).Build(entities);
Agreed (as in some other places), but the current design doesn't allow doing it, maybe we will refactor it later :)

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _successCounts;
Agreed, we can consider this refactoring, I will think when we can do this, maybe we can create a new ticket

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            var clientDetails = CreateClient(entity);
yep, I like this suggestion, I just forget that it's possible to use this approach

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            Execute(createAndRunOperationCallback, async: true, cancellationToken);
I consider this not like `async` itself but more like the code which we need to call in the `async` code path, since it's a common interface, we don't know which of the test steps will support/require async calls and which no. Instead, we have the interface that provides for us the ability to create a new operation regardless of sync or async tests. I would not make a new interface just because the particular test step doesn't require awaiting.

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "error", ex.ToString() },
They require reporting it, but as for the format they define only this:
>If an event field in the driver is of a type that does not directly map to a BSON type (e.g. Exception for the failure field of CommandFailedEvent) the test runner MUST convert values of that field to one of the BSON types. For example, a test runner MAY store the exception's error message string as the failure field of CommandFailedEvent.

so, I think it's enough to save only to the BsonString and don't worry about wording itself

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private void Execute(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, bool async, CancellationToken cancellationToken)
It was suggested by @BorisDog to move this logic to a separate method since the only difference is passing an async argument. I agreed with him since we don't use awaiting here

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _terminationCancellationToken = (CancellationToken)Ensure.IsNotNull(additionalArgs, nameof(additionalArgs))["AstrolabeCancellationToken"];
sgtm, will do it

2021-04-12 22:53 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                eventsFormatter: eventsFormatters))
allowKillSessions is the high-level test runner option, so no reason to hide this (and it might be removed at all in the next ticket). As for eventFormatter, if so, we will need to ensure that `events id` won't be the same as our already presented args. 
Also I consider `eventFormatting`s as also a high-level test runner(not test-related) configuration, so I think it's enough to configure it like is now, but I don't mind changing it as you suggest also

2021-04-12 23:00 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            List<(string Key, IEnumerable<string> Events, List<string> CommandNotToCapture)> eventTypesToCapture = new ();
>They're fine to return two or more values but often their use results in harder to understand code.

well, tuple in this particular case is just dynamic equivalent for:

public class eventTypesToCapture 
{
    string Key,
    IEnumerable<string> Events,
    List<string> CommandNotToCapture
}

and we need to collect these details during parsing income data and then provide it to this line: https://github.com/mongodb/mongo-csharp-driver/blob/db7d863a1a41bdb4ca74df6f5d3b8ef42af7b8e3/tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs#L510 So I would not call it like harder to understand :) , we just collect information about particular eventcapturer in the same line (tuple item)

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +    public interface IEventsFormatter
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +    public interface IEventsFormatter<TResult> : IEventsFormatter
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/EventCapturer.cs
> +        private readonly IEventsFormatter _eventsFormatter;
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +        private readonly Dictionary<string, IEventsFormatter> _eventsFormatters;
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            Dictionary<string, IEventsFormatter> eventsFormatters = null)
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            Ensure.IsNull(_entityMap, nameof(_entityMap)); // ensure that we don't call Run more than once
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, IEventsFormatter> _eventsFormatters;
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public UnifiedEntityMapBuilder(Dictionary<string, IEventsFormatter> eventsFormatters)
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            var clientDetails = CreateClient(entity);
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        eventTypesToCapture.Add((clientId, observeEvents, commandNamesToSkipInEvents));
yeah.. but I would call it overkill here :)

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private EventCapturer CreateEventCapturer(IEnumerable<string> eventTypesToCapture, IEnumerable<string> commandNamesToSkip, IEventsFormatter eventsFormatter)
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
`termination` is a spec term.., but I if no objections, I don't mind either

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            CancellationToken terminatorCancellationToken)
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _storeErrorsAsEntity = storeErrorsAsEntity;
null is also the valid case

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _terminationCancellationToken = (CancellationToken)Ensure.IsNotNull(additionalArgs, nameof(additionalArgs))["AstrolabeCancellationToken"];
done

2021-04-13 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminationCancellationToken;
done

2021-04-13 00:29 UTC, DmitryLukyanov commented
done, I also previously forgot to push this change: https://github.com/mongodb/mongo-csharp-driver/pull/476/files#diff-23510efdc9896e501d76cd50f97a93c1e09c1c36cfa18704708300220c6aae9fR131. Originally I didn't know that we make a difference between asserting and failure errors in the unified test runner, so now we consider this condition also. This is a full copy of what java does : https://github.com/mongodb/mongo-java-driver/blob/master/driver-sync/src/test/functional/com/mongodb/client/unified/UnifiedTest.java#L319-L336

2021-04-13 01:35 UTC, rstam requested changes

2021-04-13 01:35 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventHelper.cs
> +    public static class AstrolabeEventHelper
Why did you not want to move these methods to private helper methods in AstrolabeEventFormatter?

That's is the only place they are ever used. The only point to these methods is to participate in the formatting.

But I leave it up to you.

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            if (!_runHasBeenCalled)
I try to avoid negative tests when there are both then and else clauses.

Consider:

    if (_runHasBeenCalled)
    {
        throw new InvalidOperationException("...");
    }
    _runHasBeenCalled;

Note: `InvalidOperationException` is probably more accurate than `Exception`

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            (Key: Ensure.IsNotNull(clientId, nameof(clientId)),
This is the sort of test that should be in the constructor of a helper class.

Tuples are too simple to allow any validation. And you don't want to have to repeat the validation everywhere you create an instance of the Tuple.

Just my two cents about why Tuples aren't as great as some claim.

Not saying you have to change it... just saying I don't like it.

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                    _ = _eventFormatters.TryGetValue(eventsDetails.Key, out var formatter);
I had to think a bit about what this line is doing...

We are relying on the out var `formatter` being set to `null` when TryGetValue fails (which the documentation says it will be). But it's a non-obvious side effect.

The only thing that would be less tricky but longer would be:

    var formatter = _eventFormatters.Contains(eventDetails.Key) ? _eventFormatters[eventDetails.Key] : null;

Longer but less tricky.

Your choice.

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            List<(string Key, IEnumerable<string> Events, List<string> CommandNotToCapture)> eventTypesToCapture = new ();
I think Tuples should be used very sparingly.

But I won't ask for any further changes here.

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            Execute(createAndRunOperationCallback, async: true, cancellationToken);
OK

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "error", ex.ToString() },
Would it make more sense to just save `ex.Message`?

Your choice. I don't understand what this is used for.

2021-04-13 01:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private void Execute(Action<BsonDocument, bool, CancellationToken> createAndRunOperationCallback, bool async, CancellationToken cancellationToken)
OK

2021-04-13 01:37 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +        private readonly CancellationToken _terminatorCancellationToken;
It's always good when you point out that a name is derived from the spec.

Your choice here then.

2021-04-13 01:54 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventHelper.cs
> +    public static class AstrolabeEventHelper
done

2021-04-13 01:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            if (!_runHasBeenCalled)
done

2021-04-13 01:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                    _ = _eventFormatters.TryGetValue(eventsDetails.Key, out var formatter);
done

2021-04-13 01:56 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                            (Key: Ensure.IsNotNull(clientId, nameof(clientId)),
I agreed that it's better to make such validation in ctor, but I would not make a new class just for this target

2021-04-13 01:59 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                { "error", ex.ToString() },
`ex.Message` can be different in different TF also. Also, it's not always enough to have the only Message, sometime you need to validate `baseException.Message` or even stacktrace. So I would not change it

2021-04-16 15:30 UTC, rstam requested changes

2021-04-16 15:30 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +        public BsonDocument CreateEventDocument(object @event) =>
private?

2021-04-16 15:30 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +        private static BsonDocument CreateCommandEventDocument(string eventName, DateTime timestamp, string commandName, int requestId, string customJsonNodeWithComma = "") =>
These methods should probably all be static (or all non-static, just be consistent).

2021-04-16 15:30 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +         @event switch
fix indenting

2021-04-16 16:09 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +        public BsonDocument CreateEventDocument(object @event) =>
done

2021-04-16 16:09 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +        private static BsonDocument CreateCommandEventDocument(string eventName, DateTime timestamp, string commandName, int requestId, string customJsonNodeWithComma = "") =>
missed this, done

2021-04-16 16:10 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +         @event switch
done

2021-04-16 16:18 UTC, rstam reviewed
I have no further changes to request at this time.

I'm going to defer to the other two reviewers to be the ones to approve this PR.

2021-04-19 21:56 UTC, MikalaiMazurenka requested changes
I like this variant a bit more. I will revisit several classes one more time after you update on requested changes.

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            var jsonWritterSettings = new JsonWriterSettings
-> `jsonWriterSettings`

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.WriteLine($"dotnet main> Starting workload executor...");
`$` is not required here

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var async = bool.Parse(Environment.GetEnvironmentVariable("ASYNC") ?? throw new Exception($"ASYNC environment variable must be configured."));
Avoid using general `Exception`

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.WriteLine($"dotnet main finally> Writing final results and events files");
`$` is not required

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var eventsDocument = @$"{{ ""events"" : {eventsJson}, ""errors"" : {errorDocuments}, ""failures"" : {failuresDocuments} }}";
Consider using only `$` with `\"` instead of `""`, or at least be consistent with the order: `@$` vs `$@` on the next line.

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                Console.WriteLine($"dotnet ExecuteWorkload> Returning...");
`$` is not required

2021-04-19 21:56 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.Write($"dotnet cancel workload> Canceling the workload task...");
`$` is not required

2021-04-19 22:06 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.Write($"dotnet cancel workload> Canceling the workload task...");
done

2021-04-19 22:06 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                Console.WriteLine($"dotnet ExecuteWorkload> Returning...");
done

2021-04-19 22:08 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var eventsDocument = @$"{{ ""events"" : {eventsJson}, ""errors"" : {errorDocuments}, ""failures"" : {failuresDocuments} }}";
I would prefer to avoid slashes here. Fixed arguments order

2021-04-19 22:08 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.WriteLine($"dotnet main finally> Writing final results and events files");
done

2021-04-19 22:08 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            Console.WriteLine($"dotnet main> Starting workload executor...");
done

2021-04-19 22:09 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            var jsonWritterSettings = new JsonWriterSettings
good catch, done

2021-04-19 22:16 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var async = bool.Parse(Environment.GetEnvironmentVariable("ASYNC") ?? throw new Exception($"ASYNC environment variable must be configured."));
idk which exception suits here better (ConfigurationException is not available in netcoreapp1.1), I added this one because we used this exception previously in all such places, I'm open to suggestions

2021-04-19 22:24 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var async = bool.Parse(Environment.GetEnvironmentVariable("ASYNC") ?? throw new Exception($"ASYNC environment variable must be configured."));
maybe invalidoperationexception if unset env variable is the same as `a property set is not appropriate given the object's current state.`, looks not super clear though
>Throw an InvalidOperationException exception if a property set or method call is not appropriate given the object's current state.
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#use-the-predefined-net-exception-types

2021-04-22 18:51 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +                        "CommandStartedEvent",
minor: should `nameof(EventClass)` be used instead of `"EventClass"` everywhere in this method?

2021-04-22 18:51 UTC, BorisDog commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            };
minor: should `jsonWriterSettings` be created once to avoid addition object allocation for each event?

2021-04-22 18:56 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +                        "CommandStartedEvent",
it would be a good idea if these values match in all cases, but since it doesn't, I would use the same "technic" everywhere :)

2021-04-22 18:56 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            };
yeah, it makes sense, will do it in the next commit

2021-04-22 19:04 UTC, DmitryLukyanov commented
ready for review

2021-04-22 19:04 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            };
done

2021-04-22 19:06 UTC, BorisDog approved these changes
LGTM

2021-04-23 18:45 UTC, MikalaiMazurenka requested changes

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _runHasBeenCalled = true;
I do not understand the purpose of this flag.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +                case IUnifiedOperationWithCreateAndRunOperationCallback operationWithCreateAndRunCallback:
Consider another name for the interface, e.g. `IUnifiedWithCallbackOperation`.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private bool _disposed;
I'd suggest to move this field after the readonly block

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        eventTypesToCapture.Add(
Consider getting read of tuples here. They are just complicating things in this case.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _loopCancellationToken = loopCancellationToken;
Add `Ensure.IsNotNull` here, since you access token's property in one of the methods.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _iterationCounts;
Rename to `_iterationCountMap`.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _successCounts;
Rename to `_successCountMap`.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                foreach (var operation in _loopOperations.Select(o => o.DeepClone().AsBsonDocument))  // the further operations can mutate the passed input documents
Consider moving the comments before the `foreach` line (because we don't usually use this format).

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            int iterationsCount = 0;
Rename to `iterationCount`

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            int successfulOperationsCount = 0;
Rename to `successCount`.

2021-04-23 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +using System.Threading;
Unnecessary using

2021-04-23 18:48 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _eventFormatters = eventFormatters;
Either add the `// can be null` to `_eventFormatters` or remove from `_additionalArgs`

2021-04-23 18:49 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            var jsonWritterSettings = new JsonWriterSettings
It's not

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +                var testCase = factory.CreateTestCase(driverWorkload, async);
because the astrolabe manages how this console app works and he expects only one run

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +        private static void CancelWorkloadTask(CancellationTokenSource astrolabeCancellationTokenSource)
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _eventFormatters = eventFormatters;
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            _runHasBeenCalled = true;
to ensure that we don't call `Run` more than once, it was Robert's suggestion

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +                case IUnifiedOperationWithCreateAndRunOperationCallback operationWithCreateAndRunCallback:
`callback` can mean a lot of things. So in this particular case, we provide a particular callback

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private bool _disposed;
we never do it in other places, so I think it's better to follow a common approach

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _iterationCounts;
I think it will be more correct to remove map suffix from all these fields (or add Map for all of them, but it's harder a bit), done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly Dictionary<string, long> _successCounts;
described above

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _loopCancellationToken = loopCancellationToken;
loopCancellationToken is struct and cannot be null

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestOperationFactory.cs
> +using System.Threading;
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            int iterationsCount = 0;
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            int successfulOperationsCount = 0;
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +                foreach (var operation in _loopOperations.Select(o => o.DeepClone().AsBsonDocument))  // the further operations can mutate the passed input documents
done

2021-04-23 19:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        eventTypesToCapture.Add(
as I wrote before, with a tuple I just accumulate all eventCapturer-related info in a single variable, so I don't think that it makes this more complicated

2021-04-23 19:47 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            var jsonWritterSettings = new JsonWriterSettings
not sure what you mean, the variable is renamed: https://github.com/DmitryLukyanov/mongo-csharp-driver/blob/csharp3341/tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs#L33

2021-04-23 19:47 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/AstrolabeEventFormatter.cs
> +            .Add("connectionId", connectionId.LocalValue);
discussed offline, in this particular case, it's reusing of common code parts

2021-04-26 14:52 UTC, MikalaiMazurenka approved these changes
LGTM

2021-04-26 14:52 UTC, MikalaiMazurenka commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            var async = bool.Parse(Environment.GetEnvironmentVariable("ASYNC") ?? throw new Exception($"ASYNC environment variable must be configured."));
You are right, I didn't see the ?? is inside `Parse` brackets.

2021-04-26 14:52 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLoopOperation.cs
> +            _loopCancellationToken = loopCancellationToken;
Good point. I've missed that.

2021-04-27 21:08 UTC, merged