CSHARP-3462: Unobserved task exception on connection failure raises its head again
mongodb/mongo-csharp-driver pull request #492
Opened 2021-04-06 21:58 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3462
EG: https://evergreen.mongodb.com/version/606cd75f0ae6066340c8e63e

Note: This is leftover from [CSHARP-3102: Memory leak related to heartbeat when connecting to Atlas clusters](https://github.com/mongodb/mongo-csharp-driver/commit/a2303983c22639a114727ec3696cb667e7817b8b).
And the sync path (`BinaryConnection.ReceiveMessage`) did not produce an unhandled exception (or it is not raised in the event for some reason), but I included both paths in the unit test.

2021-04-09 18:12 UTC, rstam requested changes

2021-04-09 18:12 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                    taskCompletionSource.Task.IgnoreExceptions();
I'm concerned that this is the wrong place to do this.

We don't want to ignore ALL unobserved task exceptions.

What we actually want to do is "observe" them all so that there are no unobserved exceptions.

Where was the unobserved task exception happening? I suspect it was in the heartbeat. Let's change the heartbeat code instead to observe the exception.

2021-04-14 16:15 UTC, MikalaiMazurenka reviewed
Please check my answers. If you still have concerns I will try to clarify things further and potentially make changes if required.

2021-04-14 16:15 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                    taskCompletionSource.Task.IgnoreExceptions();
> I'm concerned that this is the wrong place to do this.

I think this is the only place where this exception can be observed, because it happens on the `taskCompletionSource` task object.

> We don't want to ignore ALL unobserved task exceptions.

This exception will be still be thrown: [BinaryConnection:374](https://github.com/mongodb/mongo-csharp-driver/blob/bb5b38d7407b37453ce1aac82e8a67f5526b2f86/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L374)

> What we actually want to do is "observe" them all so that there are no unobserved exceptions.

This is exactly what `TaskExtensions.IgnoreExceptions` is doing: [TaskExtensions.IgnoreExceptions](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Misc/TaskExtensions.cs#L22)
By accessing the `.Exception` property of the task, it's exception is considered as observed.

> Where was the unobserved task exception happening? I suspect it was in the heartbeat. Let's change the heartbeat code instead to observe the exception.

I didn't manage to reproduce a case when it was not caused by heartbeat, and the heartbeat code in my opinion definitely requires refactoring, but I'm inclined to fix the issue at the lowest possible point, which is `BinaryConnection`. You can check the added unit test, which shows that the issue can be reproduced (with mocks) even without heartbeat involvement.

Additionally, we have a very similar logic in `BinaryConection.Open`: [BinaryConection:231](https://github.com/mongodb/mongo-csharp-driver/blob/bb5b38d7407b37453ce1aac82e8a67f5526b2f86/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L231). The exception is set on the `taskCompletionSource.Task`, but observed `_openTask.IgnoreExceptions();` and thrown.

2021-04-16 15:20 UTC, rstam requested changes

2021-04-16 15:20 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                    taskCompletionSource.Task.IgnoreExceptions();
I understand that by "ignoring" the exception we are technically "observing" it as far as .NET is concerned.

But I don't understand how "ignoring" the exception can be the right thing to do. Seems like all exceptions should be propagated to the caller and caught somewhere.

An unobserved exception means the exception was not caught, which would be a bug in our code.

Am I missing something?

2021-04-20 23:59 UTC, MikalaiMazurenka reviewed
I think this explanation is a bit better

2021-04-20 23:59 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                    taskCompletionSource.Task.IgnoreExceptions();
I didn't manage to unit test it, but I reproduced a case when we have two threads reading from the same connection and one sets an exception on `taskCompletionSource`. In this case when the exception is thrown on line [BinaryConnection:374](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L374) the other thread unlocks and attempts to remove a message from dropbox on line [BinaryConnection:360](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L360) which will result in propagating exception from `taskCompletionSource` ([BinaryConnection:810](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L810)).
So for each ignore call on `taskCompletionSource` there will be this very exception thrown to the caller, either via throw on line [BinaryConnection:374](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L374) or by accessing the result of completion source task on line [BinaryConnection:810](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L810) in multithreaded scenario.
To clarify, by calling [Dropbox.AddException](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L785) we add the exception to `taskCompletionSource` task and throw it synchronously ([BinaryConnection:374](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L374)), which sort of doubles the number of exceptions in this case (one thrown and one added to task), requiring us to observe the exception in the unobserved `taskCompletionSource` task.

2021-04-21 19:49 UTC, MikalaiMazurenka commented
@DmitryLukyanov suggested another approach with explicit observation of message task. I've checked it and looks way better than the previous one. Instead of adding the exception to `taskCompletionSource.Task` and then additionally throwing the exception on line [BinaryConnection:374](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L374), now we only add the exception to `taskCompletionSource.Task` and then observe it's result on line [BinaryConnection:379](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L379).

Note: I've force pushed the branch to include the fix for latest test fails from master to see the tests results clearly.

2021-04-22 18:30 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> -                            throw;
The exception will be observed and thrown by calling `return _dropbox.RemoveMessage(responseTo);` on the line 378 on the right side, because the [BinaryConnection.Dropbox.RemoveMessage](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs#L810) observes the message task.

2021-04-26 17:42 UTC, rstam approved these changes
LGTM

2021-05-12 23:17 UTC, DmitryLukyanov reviewed
Some comments and then it will be LGTM

2021-05-12 23:17 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
>                              _dropbox.AddException(ex);
this is probably not the issue for us since as I remember we don't call ReceiveBuffer with more than 1 attempt anymore (am I right?), but if we would do it, we would be able to have a memory leak in line 378 since RemoveMessage return buffer that is not disposed. But in our case it's not an issue, we cannot call addMessage since mostlikely the error will be thrown in line 368, so the buffer even is not created yet

2021-05-17 19:18 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-05-17 19:18 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> -                            throw;
Done

2021-05-17 19:18 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnectionTests.cs
> +        public void ReceiveMessage_should_not_produce_unobserved_task_exceptions_on_fail(
Done

2021-05-17 19:18 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnectionTests.cs
> +            var mockStream = new Mock<Stream>();
I decided to leave it in finally, since this block is present anyway.

2021-05-17 19:18 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnectionTests.cs
> +                if (args.Exception.InnerException is MongoConnectionException)
As discussed offline, now handling all of the exceptions and marking them as observed

2021-05-17 19:18 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
>                              _dropbox.AddException(ex);
Discussed offline. There could be theoretically a race condition when this happens, but practically this shouldn't be an issue.

2021-05-17 19:26 UTC, DmitryLukyanov approved these changes
LGTM

2021-05-17 21:32 UTC, merged