CSHARP-2936: Support [Serializable] when targeting netstandard2.0
mongodb/mongo-csharp-driver pull request #497
Opened 2021-04-12 23:34 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-2936
EG: https://evergreen.mongodb.com/version/6074d8d23627e056aee4fc20

Note: there were several `[Serializable]` occurrences in Legacy, but I omitted them.

2021-04-13 18:46 UTC, rstam requested changes
One small change requested.

Good job and nice attention to detail!

2021-04-13 18:46 UTC, rstam commented on src/MongoDB.Driver.Core/MongoExecutionTimeoutException.cs
> +#if !NETSTANDARD1_5
Add between lines 90-91:

    _result = (BsonDocument)info.GetValue("_result", typeof(BsonDocument));

Add between lines 112-113:

    #if !NETSTANDARD1_5
            /// <inheritdoc/>
            public override void GetObjectData(SerializationInfo info, StreamingContext context)
            {
                base.GetObjectData(info, context);
                info.AddValue("_result", _result);
            }
    #endif

2021-04-13 18:47 UTC, rstam commented
@jyemin is it OK to ignore Legacy in this PR?

2021-04-13 19:18 UTC, jyemin commented
Sure as long as we're tracking it somewhere

2021-04-14 17:42 UTC, MikalaiMazurenka reviewed
Thanks for appreciation!
Ready for review

2021-04-14 17:42 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/MongoExecutionTimeoutException.cs
> +#if !NETSTANDARD1_5
Good catch! I've updated the unit test to contain the `_result` field as well.

2021-04-15 04:02 UTC, rstam approved these changes
LGTM

2021-04-15 11:30 UTC, merged