CSHARP-3299: Enable Secure Tests on Linux
mongodb/mongo-csharp-driver pull request #499
Opened 2021-04-14 17:54 UTC by DmitryLukyanov

This PR for mac also :) 
EG: https://evergreen.mongodb.com/version/607727e81e2d176bc70b43a9

2021-04-14 18:06 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> +    #sudo security delete-certificate -c "<name of existing certificate>"
it sounds like this is not required, a similar line is presented for windows in the guide, but we don't use it, so I will remove this line also. I temporarily left this here for now just in case

2021-04-14 18:06 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> +function make_trusted() {
I'm open to suggestion/comments/critic here

2021-04-14 18:06 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +     # - name: test-netstandard15: auth tests fail on macos with test-netstandard15, so skip them
with this line, we will see a lot of errors like this: https://evergreen.mongodb.com/task_log_raw/dot_net_driver_secure_tests_macOS__version~4.0_os~macos_1014_topology~sharded_cluster_auth~auth_ssl~ssl_test_netstandard15_patch_804de83e2388793b111beef8ffeb09b5cf697451_60771cb87742ae6ad4a3fdd5_21_04_14_16_48_03/0?type=T#L37944. I think we don't need to spend time on investigating this issue for netstandard1.5

2021-04-14 18:06 UTC, DmitryLukyanov commented on evergreen/run-tests.sh
> +      '$env:MONGO_X509_CLIENT_CERTIFICATE_PATH="${MONGO_X509_CLIENT_CERTIFICATE_PATH}";'\
the value must be without `'`s

2021-04-14 18:06 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> -else
not sure why `keytool` way doesn't work for us, I saw somewhere that this way works only with java apps, but I'm not sure about details, anyway, the currently added way replaces these lines, so I think we can end up with the currently added approach

2021-04-14 18:10 UTC, DmitryLukyanov commented
EG: after rebasing

2021-04-22 16:46 UTC, JamesKovacs requested changes
Some minor feedback and changes requested. Overall looking good.

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/add-certs-if-needed.sh
> +    #sudo security delete-certificate -c "<name of existing certificate>"
Unless we are changing test root CAs frequently (and I doubt we are), I agree that we don't need to worry about automating cleanup of previously used root CAs. On EG, this won't matter either since we start with a clean machine every time. It would only matter on our own machines when troubleshooting EG scripts.

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/add-certs-if-needed.sh
> +    #sudo security delete-certificate -c "<name of existing certificate>"
Regarding the branching logic, we should detect OSX rather than falling through to it as the default. If we ever decide to run our test suite on Amazon Linux, RHEL, or any other OS, we will try to run the OSX commands on it and they likely won't work. I would include an `else` that errs with "unsupported OS" or something like that.

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/add-certs-if-needed.sh
> -else
`keytool` is a Java utility that manages the Java KeyStore. This isn't the same keystore used by the OS and other language runtimes. So the `keytool` code was likely a holdover from porting the Java impl and wouldn't work for anything other than Java.

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +            CAFILE=${DRIVERS_TOOLS}/.evergreen/x509gen/ca.pem \
Why do we pass this in as `CAFILE` but then use `${DRIVERS_TOOLS}/.evergreen/x509gen/ca.pem` to locate the certs in `add-certs-if-needed.sh`? If we are going to pass in `CAFILE`, should we not also pass in the OCSP ca.pem too?

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +     # - name: test-netstandard15: auth tests fail on macos with test-netstandard15, so skip them
.NET Core 1.1 uses OpenSSL on macOS, which may not be installed in the expected location depending on macOS version, especially on a clean build. Starting in .NET Core 2.0, .NET Core switched to using the Apple Security Framework on macOS.

https://github.com/dotnet/runtime/issues/17523
https://github.com/dotnet/announcements/issues/21

We can either `brew install openssl` on macOS to ensure that OpenSSL is installed for .NET Core 1.1 or we can skip the `netstandard1.5` tests on macOS. I would suggest the latter with a comment mentioning the missing OpenSSL dependency.

2021-04-22 16:46 UTC, JamesKovacs commented on evergreen/run-tests.sh
> +      '$env:MONGO_X509_CLIENT_CERTIFICATE_PATH="${MONGO_X509_CLIENT_CERTIFICATE_PATH}";'\
Odd that it worked before. But OK.

2021-04-22 17:14 UTC, DmitryLukyanov reviewed
EG: https://evergreen.mongodb.com/version/6081aee2c9ec447a1a7257bd

2021-04-22 17:14 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            CAFILE=${DRIVERS_TOOLS}/.evergreen/x509gen/ca.pem \
you're right, Removed

2021-04-22 17:14 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +     # - name: test-netstandard15: auth tests fail on macos with test-netstandard15, so skip them
done

2021-04-22 17:14 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> +    #sudo security delete-certificate -c "<name of existing certificate>"
done

2021-04-22 17:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> -            // temporary disable the test on Win Auth topologies, due to operations timings irregularities
this test fails on auth envs, so only a win condition is not relevant anymore

2021-04-27 21:17 UTC, JamesKovacs approved these changes
LGTM

2021-04-27 21:18 UTC, merged