CSHARP-3380: Iterate over all connections on connection checkout
mongodb/mongo-csharp-driver pull request #503
Opened 2021-04-19 18:24 UTC by BorisDog

CSHARP-3380: Iterate over all connections on connection checkout in ConnectionPool

[EG](https://evergreen.mongodb.com/version/607dc1f2a4cf47318e9e3122) (internal link)

2021-04-28 22:20 UTC, JamesKovacs requested changes
Overall looking good. The new connection pruning mechanism - where we prune, release, and prune some more - looks good.

There are some unused variables in tests, which need to be removed. The only major piece of feedback is the use of PRNG in one of the tests, which I don't like. The lack of determinism in tests can make them hard to debug in the face of failure. While that is true whenever there is threading in tests, there is no reason to make our lives even harder by introducing a PRNG. :)

2021-04-28 22:20 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var connectionsToExpire = new List<ConnectionId>();
`connectionsToExpire` is unused.

2021-04-28 22:20 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var random = new Random();
Using an unseeded PRNG can make tests difficult to debug. It would be better to succeed and fail in a set order. For example, always fail on odd-numbered connections or fail every third connection. If we need to test variations on that, we should write it as a parameterized `[Theory]`.

2021-04-29 13:50 UTC, DmitryLukyanov reviewed
Can you please explain highlighted place?

2021-04-29 13:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +                .Where(e => e is ConnectionPoolRemovingConnectionEvent)
use `OfType` instead (and in other places)

2021-04-29 13:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                        var connection = _connections.Last();
nit: previous one works a bit faster due to avoiding this cast: https://github.com/microsoft/referencesource/blob/master/System.Core/System/Linq/Enumerable.cs#L1090

2021-04-29 13:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                            result = connection;
is this change really required? It sounds like the previous one also works

2021-04-29 13:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                PooledConnection[] expiredConnections;
can you explain this change? I don't see significant difference yet

2021-04-29 16:18 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +                .Where(e => e is ConnectionPoolRemovingConnectionEvent)
Thanks, good idea!

2021-04-29 20:59 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                        var connection = _connections.Last();
done

2021-04-29 20:59 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                            result = connection;
Discussed offline

2021-04-29 21:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            private bool _isDisposed;
in other places, we mostly name this variable `disposed` (without `is`).

2021-04-29 21:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +                    var connectionMock = new Mock<IConnection>();
note: we have `MockConnection` class that already mocks some logic

2021-04-29 21:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var random = new Random();
I'm not sure what exactly this random stuff can say for us? That there is a random value that causes issues? But what if not all of the random values are problematic? How can we work with the failed tests which we don't know why exactly they were failed? I agree with @JamesKovacs , we need to be more explicit in this case

2021-04-29 21:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool IsDisposed
I would also add a note here about the reason why it's not enough to have only `IsExpired`

2021-04-29 22:16 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var random = new Random();
As discussed over Zoom, using `Random` with an unknown seed value can make test failures difficult to reproduce. I suggest creating a `Randomizer` test class that can generate and output a seed value for the test run so that failures can be more easily investigated. I would also suggest considering something akin to the following:

```
[Theory]
[InlineData(null)]
[InlineData(12345)]
[InlineData(67890)]
public void TestRandomly(int? seed)
{
    var random = seed.HasValue ? new Random(seed.Value) : new Random();
    // remainder of test code
}
```

This would allow for two fixed random seeds - with known test outputs - as well as an actual random seed to fuzz the test.

If we see a failure in one of these tests, this would allow us to quickly spot the root cause. Imagine if we just used truly random seeds and a particular test passed on Windows and Linux, but failed on OSX. Is it a problem with OSX? Was it the random seed value used? We have no idea. Take the same scenario but using the above technique. The fixed seeds pass on all platforms but a random seed fails on OSX. That is a pretty good indication that it is due to the random seed selected rather than a problem on OSX.

2021-04-29 22:21 UTC, JamesKovacs requested changes
Discussed the need for PRNG seeding and options for fuzzing over Zoom.

2021-04-30 21:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool IsDisposed
>I think IsDisposed and IsExpired are quite self-explanatory.

my point was that looking just at `PooledConnection` class, it's not clear how `IsDisposed` field related to `IsExpired`. Should we also consider `IsDisposed` field in places when we currently use only `IsExpired`. It would be good if we say that the only reason why we have this field is to avoid some double removing in particular place

2021-05-03 15:23 UTC, DmitryLukyanov approved these changes
LGTM

2021-05-03 23:31 UTC, JamesKovacs requested changes
Looks good but I still think we need two fixed random seeds. See my inline comment. Happy to discuss more if you'd like.

2021-05-03 23:31 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/RandomSeedAttribute.cs
> +        public object[] GenerateValues() => new object[] { Environment.TickCount ^ Process.GetCurrentProcess().Id };
Although we are generating a random seed, we will know the value since it will get reported in the xUnit output. Is that correct?

If so, I like the idea for its simplicity and debuggability. I would still like to see two fixed seed values so that tests are reproducible. I would suggest:

```
public object[] GenerateValues() => new object[] {
        int.MaxValue / 2,
        int.MaxValue,
        Environment.TickCount ^ Process.GetCurrentProcess().Id
};
```

I tried `int.MinValue` and zero but those generate the same sequence of pseudo-randoms as `int.MaxValue`. Another possibility would be to use 0 and 42 as the fixed random seeds.

2021-05-06 16:01 UTC, JamesKovacs approved these changes
LGTM. Thank you for the discussion and incorporating feedback.

2021-05-06 18:18 UTC, merged