CSHARP-2955: Check MethodHelper GetMethodDefinition method when targetting netstandard2.0
mongodb/mongo-csharp-driver pull request #508
Opened 2021-04-26 21:38 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-2955
EG: https://evergreen.mongodb.com/version/608728e63066157f0b79adb5

2021-04-26 21:50 UTC, MikalaiMazurenka commented on src/MongoDB.Driver/Linq/MethodHelper.cs
> +                .Where(m => m.MetadataToken == methodInfo.MetadataToken)
This change is tricky, but hear me out:
[MemberInfo.MetadataToken](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=netstandard-1.5) is unique per method per module (effectively per compiled assembly). Here we are searching for a method of a generic type with the same signature, but with generic parameter not specified. From the metadata perspective, both of these methods are the same and we are looking in the very same type, so in my opinion the usage of `MetadataToken` is fine in this case.
Though if you still think the usage of `MetadataToken` is not safe, I'm perfectly fine with reverting this back and just leaving the tests.

2021-04-26 22:03 UTC, rstam requested changes

2021-04-26 22:03 UTC, rstam commented on src/MongoDB.Driver/Linq/MethodHelper.cs
> +                .Where(m => m.MetadataToken == methodInfo.MetadataToken)
Before I study whether this change is correct can you explain why you even made it?

The point of the ticket was to verify whether the NETSTANDARD2_0 code path was correct.

2021-04-26 22:42 UTC, MikalaiMazurenka commented on src/MongoDB.Driver/Linq/MethodHelper.cs
> +                .Where(m => m.MetadataToken == methodInfo.MetadataToken)
In this case I misinterpreted the task description. Since there was nothing to change for netstandard2.0 I updated the netstandard1.5 path, since I saw a TODO there

2021-04-27 13:50 UTC, rstam requested changes

2021-04-27 13:50 UTC, rstam commented on src/MongoDB.Driver/Linq/MethodHelper.cs
> +                .Where(m => m.MetadataToken == methodInfo.MetadataToken)
The task was to see whether the NETSTANDARD2_0 (and now NETSTANDARD2_1) path need to be changed to use new APIs available in 2.0 and 2.1 (and presumably common to .NET 4.5.2).

I would leave the NETSTANDARD1_5 code path alone.

You can argue if you want that the NETSTANDARD1_5 code path should be changed, but since we are so close to removing support for NETSTANDARD1_5 anyway I wouldn't bother.

If we do bother, we probably need a different JIRA ticket and a justification.

2021-04-27 16:42 UTC, MikalaiMazurenka reviewed
I've reverted the netstandard 1.5 changes, but left this case documented in unit tests.
If tests are not necessary here, I will cancel this PR and close the issue as already implemented.

2021-04-27 16:42 UTC, MikalaiMazurenka commented on src/MongoDB.Driver/Linq/MethodHelper.cs
> +                .Where(m => m.MetadataToken == methodInfo.MetadataToken)
Agreed. Dropped this change.

2021-04-27 23:48 UTC, rstam approved these changes
LGTM

I leave it up to you whether you want to keep the tests or not.

This is LINQ2 code and will go away when LINQ2 goes away.

2021-04-28 15:19 UTC, MikalaiMazurenka commented
Closing, because the tests are not necessary, considering they will go away with the new LINQ implementation.

2021-04-28 15:19 UTC, closed without merging