CSHARP-3523: Split the unified test runner into 2 classes.
mongodb/mongo-csharp-driver pull request #511
Opened 2021-04-27 22:00 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/608889753e8e8678e0e2d8a7

2021-04-27 22:01 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatExecutor.cs
> +    public sealed class UnifiedTestFormatExecutor : IDisposable
This naming was suggested by @rstam , I'm open to suggestions.

2021-04-28 00:49 UTC, rstam requested changes
I like the refactoring. Nice work.

I have some naming recommendations that I think will help a lot.

2021-04-28 00:49 UTC, rstam commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor(
using (var runner = new UnifiedTestRunner(

See comments below on the names of some classes.

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
using (var runner = new UnifiedTestRunner(

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
using (var runner = new UnifiedTestRunner(

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatExecutor _unifiedTestFormatExecuter = new UnifiedTestFormatExecutor();
private readonly UnifiedTestRunner _runner = new UnifiedTestRunner();

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatExecutor _unifiedTestFormatExecuter = new UnifiedTestFormatExecutor();
Consider making this fail match for ValidPass file more closely by using a local variable in a `using` statement instead of a field.

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
using (var runner = new UnifiedTestRunner())

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
>      public sealed class UnifiedTestFormatNegativeTestRunner : IDisposable
Rename this file:

    UnifiedTestFormatValidFailTestRunner

Why? Because it runs the `valid_fail` JSON tests.

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +    public sealed class UnifiedTestFormatTestRunner
I think we should rename this file:

    UnifiedTestFormatValidPassTestRunner

Why? Because it runs the valid_pass JSON tests.

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/versioned-api/VersionedApiUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
using (var runner = new UnifiedTestRunner())

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatExecutor.cs
> +    public sealed class UnifiedTestFormatExecutor : IDisposable
Rename this file:

    UnifiedTestRunner

Refactor all places that use this file:

    var runner = new UnifiedTestRunner();

2021-04-28 00:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatExecutor.cs
> +    public sealed class UnifiedTestFormatExecutor : IDisposable
Before we had naming conflict with the file that runs the `valid_pass` tests, but now that we have given that file a more precise name this more general name is available for this file.

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestFormatExecutor.cs
> +    public sealed class UnifiedTestFormatExecutor : IDisposable
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/versioned-api/VersionedApiUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +    public sealed class UnifiedTestFormatTestRunner
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
> +        private readonly UnifiedTestFormatExecutor _unifiedTestFormatExecuter = new UnifiedTestFormatExecutor();
idk why this naming was chosen originally, but if it's not the spec naming, I'm ok with this, done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatNegativeTestRunner.cs
>      public sealed class UnifiedTestFormatNegativeTestRunner : IDisposable
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/AstrolabeWorkloadExecutor/Program.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor(
done

2021-04-28 12:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatTestRunner.cs
> +            using (var testExecutor = new UnifiedTestFormatExecutor())
done

2021-04-28 15:32 UTC, rstam approved these changes
LGTM with one small suggestion

2021-04-28 15:32 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +namespace MongoDB.Driver.Tests.Specifications.crud
Shouldn't this be:

    namespace MongoDB.Driver.Tests.Specifications.change_streams

2021-04-28 15:35 UTC, MikalaiMazurenka approved these changes
Great work! Before you merge, I wanted to ask you to unignore the `"poc-retryable-writes.json:InsertOne fails after multiple retryable writeConcernErrors"` test, since the linked ticket is completed. But since it's not in scope, feel free to ignore.

2021-04-28 15:35 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidPassTestRunner.cs
> +                "poc-retryable-writes.json:InsertOne fails after multiple retryable writeConcernErrors" // CSHARP-3269
This can be unignored, since [CSHARP-3269: Write operations do not include error labels from underlying exception](https://jira.mongodb.org/browse/CSHARP-3269) is already complete (I've checked the test, it succeeds).

2021-04-28 15:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +namespace MongoDB.Driver.Tests.Specifications.crud
interesting, will check this..

2021-04-28 15:37 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidPassTestRunner.cs
> +                "poc-retryable-writes.json:InsertOne fails after multiple retryable writeConcernErrors" // CSHARP-3269
ok, will remove this in the next commit, thanks

2021-04-29 11:51 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidPassTestRunner.cs
> +                "poc-retryable-writes.json:InsertOne fails after multiple retryable writeConcernErrors" // CSHARP-3269
done

2021-04-29 11:52 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +namespace MongoDB.Driver.Tests.Specifications.crud
done

2021-04-30 15:43 UTC, merged