CSHARP-3306: Implement and Test Connection Pool Paused State
mongodb/mongo-csharp-driver pull request #519
Opened 2021-05-07 11:18 UTC by BorisDog

2021-05-18 15:19 UTC, DmitryLukyanov reviewed
Initial review

2021-05-18 15:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            lock (_poolState)
is this part implemented (`lock on the TopologyDescription when clearing the pool`): https://github.com/mongodb/specifications/commit/beda39620fb39938a8d46eeaf63b75f807fe7c4e#diff-52a48d3b84e9e90e30fb87b3799c6302750f1ed2817b2abbead44e7a7bb6bb47R1214?

2021-05-18 15:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                _connectionPool.SetReady();
and this one: https://github.com/mongodb/specifications/commit/beda39620fb39938a8d46eeaf63b75f807fe7c4e#diff-52a48d3b84e9e90e30fb87b3799c6302750f1ed2817b2abbead44e7a7bb6bb47R1394?

2021-05-18 15:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                _connectionPool.SetReady();
is this also needs be added: https://github.com/mongodb/specifications/commit/beda39620fb39938a8d46eeaf63b75f807fe7c4e#diff-52a48d3b84e9e90e30fb87b3799c6302750f1ed2817b2abbead44e7a7bb6bb47R1626?

2021-05-18 15:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                do
can you please point me out on the doc with description for this logic?

2021-05-19 13:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        public sealed class SemaphoreSignalableAwaiter : IDisposable
I looked again here and now I see that this design is useful, but I would still want to see a different naming here

2021-05-21 15:53 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                _connectionPool.SetReady();
We need `IsDataBearing` in this condition. `ServerType.Arbiter` is never going to be data-bearing and will never be selected. As the condition stands, we would setup a connection pool for arbiters, which is incorrect.

2021-05-21 15:55 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                _connectionPool.SetReady();
4. related to the  #2, the ticket https://jira.mongodb.org/browse/DRIVERS-1773. But I  confirmed with Patric that expected way is to use IsDataBearing conditon here, so I would make a sync with the spec wording now. Also, adding condition on `e.OldServerDescription.Type == ServerType.Unknown` solves one of my other comments regarding the fact that we always set ready even if it had been set before. With this change we will set `ready` only in required situations

2021-05-21 16:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                            pooledConnection = connectionCreator.CreateOpenedOrReuse(cancellationToken);
why `pooledConnection` cannot be null anymore?

2021-05-21 16:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new ArgumentOutOfRangeException(nameof(_poolQueueWaitResult))
we throw `ArgumentOutOfRangeException` only in validating ctor arguments, it should be `InvalidOperationException`

2021-05-21 16:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new ArgumentOutOfRangeException(nameof(_poolQueueWaitResult))
also, is any other state expected here?

2021-05-23 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                _connectionPool.SetReady();
as it was discussed in the slack with Shane, it's better to not use this condition: `e.OldServerDescription.Type == ServerType.Unknown` just in case something wrong goes down in SDAM handling, with this condition we may never mark pool ready

2021-05-24 19:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        private readonly int _maxConnecting;
as we discussed in slack, we usually don't place any internal field and constants into such options class, but I also was wrong about the above guide requirement, so I will rely on you and @JamesKovacs  here

2021-05-24 19:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                MongoAuthenticationException => (invalidateAndClear: true, cancelCheck: false),
thanks

2021-05-24 19:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new InvalidOperationException($"Invalid {_poolQueueWaitResult}")
dot in the end of message

2021-05-24 19:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        public sealed class SemaphoreSignalableAwaiter : IDisposable
I will rely on you and @JamesKovacs  here

2021-05-24 19:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool TransitionState(State newState)
got it.
note: I agree that `TryX` method should not throw, but at least this follows how it's implemented currently: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Misc/InterlockedInt32.cs#L49.

also, the fact that we cannot imagine a correct name here rings a bit that we makes more steps than it could be inside this method, but I don't want to make it over-complicated, so will rely on you and @JamesKovacs

2021-05-24 19:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
it's always Endpoint, I think no reason to use string here especially if it requires changes in `MongoConnectionPoolPausedException`

2021-05-25 07:24 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new InvalidOperationException($"Invalid {_poolQueueWaitResult}")
Done.

2021-05-25 13:05 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
I don't agree with this. There is no need to introduce any logic that it's not used. Unless we will have a real case when the identification is not endpoint, I don't think we need to make such change now.

I think a typed safe way is always better than `string`ed.

>Also we let pool decide how to identify itself

currently it will be always endpoint

2021-05-25 13:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new ArgumentOutOfRangeException(nameof(_poolQueueWaitResult))
nit: we usually add a comment to the switch branches that are note expected to be used (unless a driver error), like: `should not be reached`, this will show that this case/if branch is added just in case

2021-05-25 13:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool TransitionState(State newState)
I think the main point here is that it allows two actions, returning `true`/`false` as the method result (`Try` part) and throwing exception if some internal condition is wrong

2021-05-25 13:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
We are not introducing new logic. We are preserving the old functionality and simplifying existing one by encapsulating the decision on what pool id is to pool itself. Additional side effect is that endpoint is serialized only once.

> currently it will be always endpoint
Not necessarily, we might want to add additional ID decoration later, for example for debugging purposes.

Note that this approach will also be useful/needed when we introduce logging.

2021-05-25 14:04 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool TransitionState(State newState)
There is not really `Try` part in this method. Returning `true/false` is not well described by `Try`, as it indicates whether the transition was self-transition or not.
Added a comment explaining that, maybe in addition we can think of some naming that indicates the self-transition nuance.

2021-05-25 14:05 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    _ => new ArgumentOutOfRangeException(nameof(_poolQueueWaitResult))
Thanks, done.

2021-05-31 15:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +                            settings.Servers.First()
is this mentioned somewhere in the spec?

2021-05-31 15:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/SingleServerReadBinding.cs
> +            if (_server.Description.State == ServerState.Disconnected)
is this condition about cases that can happen when we select server in `Unknown` state [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.GridFS/GridFSBucket.cs#L971)? If so, then it looks like the question for server selector..

2021-05-31 15:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
looking at this line in the driver ticket: `Server responds with ShutdownInProgress without TransientTransactionError labels`

should this happen only in catch block since we will appear there if `ShutdownInProgress` is triggered?

2021-05-31 15:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
also, maybe it's better just to update this condition: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs#L558?

2021-05-31 15:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
or to place this on transaction level similar to what we have for commit: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs#L277

2021-05-31 15:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/FailPoint.cs
> +            if (waitForConnected)
this looks like a hack.. even if it's valid change, 1 second might be not enough in some cases, and if so, it will be really hard to find this place, can you explain this change before we proceed?

2021-05-31 15:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +        private sealed class AcquireConnectionHelper : IDisposable
regarding our offline discussion about cases that could not be covered by json tests, I would not want to check all json descriptions to see what is not covered. After quick look I think this logic is not covered: https://github.com/mongodb/mongo-csharp-driver/blob/3f246f1ba10d9745e4f5e1e7db31918616b55c6d/src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs#L302
I will leave this up to you whether you want to add this (or similar) test or no

2021-05-31 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
ignore all the above, this case is fixed in one of my tickets. See this PR: https://github.com/mongodb/mongo-csharp-driver/pull/540

2021-06-01 10:16 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Specifications/connection-monitoring-and-pooling/ConnectionMonitoringAndPoolingTestRunner.cs
> +                            if (o is ConnectionOpenedEvent ||
Nice!

2021-06-01 10:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
Great! I'll revert if #540 completes beforehand.

2021-06-01 16:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoConnectionPoolPausedException.cs
> +        protected MongoConnectionPoolPausedException(SerializationInfo info, StreamingContext context)
it looks like we have both ways, then I'm ok with any way

2021-06-01 16:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoConnectionPoolPausedException.cs
> +        protected MongoConnectionPoolPausedException(SerializationInfo info, StreamingContext context)
>also, as I understand, this ctor works in pair with GetObjectData method

this is missed

2021-06-01 16:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenConfigureFailPointTest.cs
> +            if (TestRunner.FailPointServer != null)
missed

2021-06-01 16:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +                            settings.Servers.First()
missed

2021-06-02 10:25 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +                            settings.Servers.First()
We can't have multiple servers with direct connection.

2021-06-02 10:25 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenConfigureFailPointTest.cs
> +            if (TestRunner.FailPointServer != null)
as `MongoClientJsonDrivenTestRunnerBase` configures failpoint, and later `configureFailPoint` operation shuts it off before test end, it has to be same server.
For example `minPoolSize-error.json`

2021-06-02 10:43 UTC, BorisDog commented on src/MongoDB.Driver.Core/MongoConnectionPoolPausedException.cs
> +        protected MongoConnectionPoolPausedException(SerializationInfo info, StreamingContext context)
We don't have any special data to add in `GetObjectData`.

2021-06-02 10:43 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +            if ((ex is not MongoConnectionException connectionException))
Tnx, done.

2021-06-16 23:56 UTC, JamesKovacs requested changes
I haven't thoroughly vetted the tests as I want to discuss the other points raised first. I hope that you can prove me wrong about the apparent race condition noted below.

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    if (_poolQueueWaitResult == SemaphoreSlimSignalable.SemaphoreWaitResult.Entered)
I'm pretty sure we have a race condition here. Imagine a thread enters the wait queue and nears its timeout. A second thread enters the wait queue around this time and gets signalled as the first thread times out. The first thread sets `_poolQueueWaitResult` to timed out. The second thread sets it to entered. When we hit the `if` block, they both succeed and checkout connections. Or if the ordering is reversed, both appear to time out even though the second thread just entered the wait queue and is nowhere near the timeout.

I suspect we should be storing `_poolQueueWaitResult` in a local variable rather than a member variable. Or is there some thread synchronization that I'm missing that avoids the above scenario?

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                if (_poolState.TransitionState(State.Paused))
Are you transitioning the pool to State.Paused? Are you checking if the pool is in State.Paused? I'm not understanding the intent.

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                var entered = await poolAwaiter.WaitSignaledAsync(TimeSpan.FromMilliseconds(20), cancellationToken).ConfigureAwait(false);
Why 20ms?

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPoolFactory.cs
> +        public IConnectionPool CreateConnectionPool(ServerId serverId, EndPoint endPoint, IConnectionExceptionHandler connectionExceptionHandler)
Are we OK with adding parameters to public methods in Core?

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/ConnectionPools/IConnectionPool.cs
> +        void SetReady();
What about adding a method to a public interface in Core? Is `IConnectionPool` exposed anywhere in our public API?

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        public sealed class SemaphoreSignalableAwaiter : IDisposable
I'm OK with the `Awaiter` naming. Consider `SemaphoreSlimSignalableAwaiter`.

2021-06-16 23:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        public SemaphoreSignalableAwaiter CreateAwaiter() =>
`CreateAwaiter()` seems like the correct naming to me.

2021-06-23 14:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool TransitionState(State newState)
Self-transition is transition from a state to itself, for example from Disposed to Disposed. It's allowed for some states, and not for others. It matters as `TransitionState` returns whether the transition was not self-transition.

2021-06-23 14:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
Not sure, that's how it was always used. I am happy to refactor if everybody is onboard.
cc @DmitryLukyanov

2021-06-23 14:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                var entered = await poolAwaiter.WaitSignaledAsync(TimeSpan.FromMilliseconds(20), cancellationToken).ConfigureAwait(false);
I guess that's this old heuristic for "almost immediate" allows to account for some unexpected execution delays. Did not find a reason to change that.

2021-06-23 14:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        public sealed class SemaphoreSignalableAwaiter : IDisposable
Done.

2021-06-23 14:37 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
Yes, `Pool` identifies itself via `Endpoint`. But there is no good reason for `PoolState` or other helpers to make the `Pool` identification decision on-behalf of the pool.
As `PoolState` has on other use for `Endpoint `beyond serializing it as pool identification, if would be cleaner just to receive the minimal information needed.
Also note that it's a bit cleaner for the PoolStateTests to create `PoolState` objects :)

2021-06-23 16:03 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/IConnectionPool.cs
> +        void SetReady();
I think this is fine here (I don't see any way when someone can directly use this interface). I would also mention this in this ticket: https://jira.mongodb.org/browse/CSHARP-3679

2021-06-23 16:03 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPoolFactory.cs
> +        public IConnectionPool CreateConnectionPool(ServerId serverId, EndPoint endPoint, IConnectionExceptionHandler connectionExceptionHandler)
I think this is fine here (I don't see any way when someone can directly use this interface). I would also mention this in this ticket: https://jira.mongodb.org/browse/CSHARP-3679 (I think I also changed this interface in LB changes)

2021-06-23 16:04 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                var entered = await poolAwaiter.WaitSignaledAsync(TimeSpan.FromMilliseconds(20), cancellationToken).ConfigureAwait(false);
this is old value, let's not change it at least in the current PR :)

2021-06-23 16:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
I'm ok with a factory method (but I also agreed with James that using just a ctor will provide exactly the same logic). But as I mentioned somewhere, I think we should not provide a string value, if we provide endpoint, it should a type safe value.

2021-06-23 16:53 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
I think if we will need to add a different identificator, we will need to add a different factory method or ctor, but I think it won't be needed :)

2021-06-23 16:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
it's already pushed

2021-06-23 16:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +                            settings.Servers.First()
I just surprised that this logic is not mentioned anywhere, I would expect so

2021-06-23 16:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                _maintenanceTask.ConfigureAwait(false);
missed

2021-06-23 16:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    if (_poolQueueWaitResult == SemaphoreSlimSignalable.SemaphoreWaitResult.Entered)
missed

2021-06-23 16:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                if (_poolState.TransitionState(State.Paused))
missed

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
I look at this quite simply: Does `PoolState` or any depended entity actually need the `Endpoint` object, are they expected to use it in any way in the future? So from design perspective any entity should receive no more information that it actually needs.

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
In this case receiving string is type safe. The exception just needs a string and that's exactly what it gets. Not-type safe situations are when the object might not be of the expected type for any reason. It's not the case here.

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                _maintenanceTask.ConfigureAwait(false);
We just create and hold a reference to this task without inspecting the result. 
BTW we should aim to refactor this pattern for background tasks (that's used in other places) to regular threads.

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    if (_poolQueueWaitResult == SemaphoreSlimSignalable.SemaphoreWaitResult.Entered)
Good question: `AcquireConnectionHelper` object is created per request, so effectively each member is isolated to the executing thread.

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                TransactionHelper.UnpinServerIfNeededOnAbortTransaction(_session, _command);
Great, will revert this.

2021-06-23 18:39 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                if (_poolState.TransitionState(State.Paused))
Transitioning the pool to Paused, and checking whether it was transitioned to Paused (it can be paused already).
Similar (but not identical) to the pattern we use in different places `if (_state.TryChange(State.Disposed)) {...}`

2021-06-23 18:49 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
it's disputable, you can pass something like `abc` and it will be also "valid" and but not safe

2021-06-23 18:53 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
if it doesn't need than we should not pass it, if we want to show this information anywhere inside (so we need this), then no reason to not help to class consumer about what this "identificator" is about, if it will be not only endpoint, then we will need a new ctor (or factory method)

2021-06-23 19:07 UTC, JamesKovacs approved these changes
I see why we don't have a race condition in `AcquireConnectionHelper` now. Because each request creates its own instance, the `_poolQueueWaitResult` acts like a local variable. I had forgotten that `AcquireConnectionHelper` was instantiated on a per-request basis. Thanks for addressing/discussing my feedback. This PR now LGTM.

2021-06-23 19:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
Why would not it be safe? If `ABCPool` decided to identify itself as `abc`, it's totally fine. Also note that this is exactly what is done in tests.
"Type safety" usually referrers to types mismatches, which can't happen here.

2021-06-23 19:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public PoolState(string poolIdentifier)
Not sure I understood the last comment completely. The only thing `PoolState` needs is some "hint" for exception message, thinking about that, we can even do without the pool identifier at all, as it's not consistent with other exceptions.
I am not sure why would be need new ctors or factories, as  `PoolState` should not be aware of this objects/serialization/formatting at all. Also if any other helper classes would like to add pool info to their exception (not sure why they don't), this info should formatted in single place consistently, not by helpers, and not by exceptions.

2021-06-23 19:17 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +            public bool TransitionState(State newState)
Thanks, can't think how to improve the naming here. Let me know if there are any better ideas :)

2021-06-23 21:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    throw MongoConnectionPoolPausedException.ForConnectionPool(_poolIdentifier);
having ability to put any random string looks not the best solution to me, but it's minor, so I will rely on you here

2021-06-23 21:51 UTC, DmitryLukyanov approved these changes
LGTM

2021-07-19 20:25 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        private readonly bool _isPausable;
@DmitryLukyanov `_isPausable` is used in LB mode.

2021-07-22 15:46 UTC, DmitryLukyanov requested changes
It was a bit hard to review it since all the changes looked like a fully new changes. Some suggestions/questions are requested

2021-07-22 15:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +            // note that the pool can not be paused in LB mode.
well it's not really true. The connectionPool is paused initially in all modes. And we transit the pool to the ready state here from the paused state. I don't say that it should be changed here (other than probably the comment wording), but it would be good to hear @JamesKovacs  opinion here also

2021-07-22 15:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                MongoAuthenticationException => (invalidateAndClear: true, cancelCheck: false),
I forgot, does the spec require invalidating for auth exception now?

2021-07-22 15:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    catch (MongoConnectionException exception)
does it make sense to rely on SDAM error handling and defer all exception to that point? Non `MongoConnectionException` will be ignored there anyway

2021-07-22 15:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
>                  if (_disposeConnection)
can we change this logic now?

2021-07-23 00:23 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Helpers/MockConnection.cs
> +            _openedEventHandler?.Invoke(new ConnectionOpenedEvent(_connectionId, _connectionSettings, TimeSpan.FromMilliseconds(100), null));
Done.

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        protected bool IsStandaloneTopology()
Done

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +            else if (newDescription.IsDataBearing ||
Done.

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                MongoAuthenticationException => (invalidateAndClear: true, cancelCheck: false),
Yes: 

> elif isNetworkError(error) or (not error.completedHandshake and (isNetworkTimeout(error) or isAuthError(error)

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +            // note that the pool can not be paused in LB mode.
Clarified this nuance. The pool can start in paused state, but can not be transitioned back to paused mode.

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    catch (MongoConnectionException exception)
I don't think so. SDAM error handling should be applied only in connectivity area, so I don't see why it should be piggybacked for other possible exceptions.

2021-07-23 00:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
>                  if (_disposeConnection)
Thanks, removed that comment.  Errors during open are handled via SDAM.

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        private readonly int _maxConnecting;
see ConnectionPoolSettingsTests class

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            lock (_poolState)
I would say this logic should be hidden inside this class, but ok

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            // generation increment can happen outside lock, as _serviceStates is threadsafe
I don't see sense in this comment, other than it says that there is more work here to be done which is not true at least yet. I think this particular comment it's better to revert

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    catch (MongoConnectionException exception)
>I don't think so. SDAM error handling should be applied only in connectivity area

I don't think that it's fully true statement. We catch all exceptions and it's up to SDAM how many of them we should handle. Yes, currently we handle only MongoConnectionException there but it's decision that we take on the SDAM level. In other words,  if at some moment we will start looking at more exceptions in SDAM, we won't need to change this logic. In other words (x2), we can simply delegate all/any exceptions handling in connection to the SDAM level

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +            else if (newDescription.IsDataBearing ||
it looks like the spec won't be rephrased, then let's add a comment of why this wording contradicts to what the spec requires

2021-07-23 13:39 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.TestHelpers/JsonDrivenTests/JsonDrivenTest.cs
> +                (!errorElement.Value.IsBoolean || errorElement.Value.AsBoolean))
can it be not `boolean`?

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +                isPausable: true)
it's better to remove this, since you set only public fields here

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +            Optional<TimeSpan> waitQueueTimeout = default(Optional<TimeSpan>)) : this(
expected formatting here:

    Optional<TimeSpan> waitQueueTimeout = default(Optional<TimeSpan>)) 
    : this(...

2021-07-23 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    if (freeSlots == 0)
I still don't like this method, but I will rely on you here

2021-07-23 17:26 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        private readonly int _maxConnecting;
Added tests there.

2021-07-23 17:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoInternalDefaults.cs
> +        public const int SingleServerSelectionTimeoutMS = 1000;
not answered

2021-07-23 17:40 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var settings = _settings.With(
missed

2021-07-23 17:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    catch (MongoConnectionException exception)
agreed, I missed that we can catch more exception here (unrelated to connection at all)

2021-07-23 17:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            // generation increment can happen outside lock, as _serviceStates is threadsafe
then you should rephrase it. I don't think `for now` should be left here.

2021-07-23 17:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +                isPausable: true)
oh, then we probably specify both the internal options here, idk, I guess leave it as is, it's internal/private logic we can change it next time if we will find a better way

2021-07-23 17:46 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    if (freeSlots == 0)
:(

2021-07-23 18:07 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/ConnectionPools/ExclusiveConnectionPoolTests.cs
> +            var settings = _settings.With(
Done.

2021-07-23 19:01 UTC, DmitryLukyanov approved these changes
LGTM

2021-08-10 23:24 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
>          private void SetDescription(ServerDescription newDescription)
@DmitryLukyanov please review this change. It's a bug fix that was missed out in this PR.

2021-08-10 23:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
>          private void SetDescription(ServerDescription newDescription)
can you please provide mode details?

2021-08-11 00:01 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
>          private void SetDescription(ServerDescription newDescription)
@DmitryLukyanov Yes, setting server description has to happen after ready and before clear.

2021-08-12 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> -        private void OnDescriptionChanged(object sender, ServerDescriptionChangedEventArgs e)
I would want to leave this method since it corresponds to the spec naming in pseudo code

2021-08-12 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                _currentDescription = newDescription;
as It was discussed, this change has no practical effect. In theory I don't mind to leave this, but 2 points that bother me:
1. This makes me think that this is important for any logic we have which is not true. So I would want to not pay attention on something that has no real value.
2. This change requires removing `OnDescriptionChanged` method that is named and done similar to the spec pseudo code

So I would suggest revert this part. I assume that the solution for the failed tests that you mentioned before is related to the fact that now we don't make pool ready in case if the invalidating was triggered from the cluster level. Please correct me if I'm wrong

2021-08-12 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +        private void SetDescription(ServerDescription newDescription, bool clearConnectionPool)
I think this name `clearConnectionPool` should be precise. Looking at this argument I feel like this argument is responsible for clearing the pool, but it's true only partially. What about: `forceClearConnectionPool`?

2021-08-12 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +        private volatile ServerDescription _currentDescription;
I think the previous logic still works. If you want to proceed with this, we can discuss it

2021-08-12 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                SetDescription(e.NewServerDescription, false);
let's add a explicit argument name

2021-08-12 21:22 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +        private void SetDescription(ServerDescription newDescription, bool clearConnectionPool)
Done.

2021-08-12 21:22 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                SetDescription(e.NewServerDescription, false);
Done.

2021-08-12 21:22 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +        private volatile ServerDescription _currentDescription;
@JamesKovacs could you please review this change?

2021-08-12 21:22 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                _currentDescription = newDescription;
Discussed offline. Will be addressed in follow up ticket.

2021-08-13 00:59 UTC, merged