CSHARP-3527: Consider accepting EncryptionAlgorithm enum in EncryptOptions.
mongodb/mongo-csharp-driver pull request #526
Opened 2021-05-12 20:42 UTC by DmitryLukyanov

2021-05-12 20:44 UTC, DmitryLukyanov commented on CSharpDriver.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "SkippableTests", "tests\SkippableTests\SkippableTests.csproj", "{D198833A-6AC3-4327-8B02-5095455192D0}"
this will be reverted when the new nuget version will be available

2021-05-12 20:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <ProjectReference Include="..\..\..\libmongocrypt\bindings\cs\MongoDB.Libmongocrypt\MongoDB.Libmongocrypt.csproj" />
this will be reverted when the new nuget version will be available

2021-05-12 20:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDB.Driver.csproj
> +    <ProjectReference Include="..\..\..\libmongocrypt\bindings\cs\MongoDB.Libmongocrypt\MongoDB.Libmongocrypt.csproj" />
this will be reverted when the new nuget version will be available

2021-05-12 20:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/ExplicitEncryptionExamples.cs
> -using MongoDB.Libmongocrypt;
we usually don't leave so simple changes, but this ns can confuse, so it's better to remove all usage of it (related to algorithm)

2021-05-14 18:27 UTC, BorisDog approved these changes

2021-05-14 21:36 UTC, JamesKovacs requested changes
Comments inline.

2021-05-14 21:36 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +
This should be part of `EncryptionAlgorithm`. See below.

2021-05-14 21:36 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/EncryptionAlgorithm.cs
> +}
I would recommend making this a smart enum so that we can encapsulate all the conversion logic within the class. Something like this:

```
public class EncryptionAlgorithm
{
    public static EncryptionAlgorithm AEAD_AES_256_CBC_HMAC_SHA_512_Deterministic = new EncryptionAlgorithm("AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic");
    public static EncryptionAlgorithm AEAD_AES_256_CBC_HMAC_SHA_512_Random = new EncryptionAlgorithm("AEAD_AES_256_CBC_HMAC_SHA_512-Random");

    private readonly string _algorithm;

    private EncryptionAlgorithm(string algorithm)
    {
        _algorithm = algorithm;
    }

    public override string ToString() => _algorithm;
}
```

When using this smart enum class, it behaves just like an enum, but you can hang methods off it like `ToString()`:

```
Console.WriteLine(EncryptionAlgorithm.AEAD_AES_256_CBC_HMAC_SHA_512_Deterministic);
Console.WriteLine(EncryptionAlgorithm.AEAD_AES_256_CBC_HMAC_SHA_512_Random);
```

You can optionally add implicit casts to `string` so you can just use the smart enum wherever the string version is expected.

```
public static implicit operator string(EncryptionAlgorithm algorithm) => algorithm.ToString();
```

This would save you from having the overload (as you can just use the existing string parameter method), but makes the enum itself less discoverable. I think it's probably best not to add an implicit string conversion operator.

2021-05-15 23:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptionAlgorithm.cs
> +}
this looks like more complicated than we need to here, @BorisDog what do you think? I will rely on both of you :)

2021-05-17 07:53 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/EncryptionAlgorithm.cs
> +}
I like the "smart" enums technique for more complicated cases. I think we can keep things simple here and just use regular enums.

2021-05-27 16:08 UTC, JamesKovacs approved these changes
LGTM

2021-05-27 16:08 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/EncryptionAlgorithm.cs
> +}
I'd still prefer to keep all the `EncryptionAlgorithm`-related code together in a smart enum class, but this is a relatively simple case. I'm OK with leaving this as-is.

2021-07-20 13:52 UTC, DmitryLukyanov commented
the failures I observed yesterday are gone away (The latest [EG](https://evergreen.mongodb.com/version/60f6150d3e8e86392bd473e0)). It looks like it's related to the scope of this ticket https://jira.mongodb.org/browse/DRIVERS-1541. So closing this PR.

2021-07-20 13:52 UTC, merged

2021-08-03 15:54 UTC, damon-mcgraw-rack commented
@DmitryLukyanov  this is probably not the best place for this but I believe that when this PR was merged and then MongoDb.libmongocrypt nuget package published that it created a binary incompatibility with the MongoDb.Driver nuget package. I was wondering when an update MongoDb.Driver package might be released which would fix the incompatibility.

The specific error I get is (please forgive the formatting)
`Error loading assemblies: Error loading MongoDB.Driver, Version=2.13.0.0, Culture=neutral, PublicKeyToken=null: System.TypeLoadException: Could not load type MongoDB.Libmongocrypt.EncryptionAlgorithm from assembly MongoDB.Libmongocrypt, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null`

reverting to MongoDb.Libmongocrypt 1.2.1 resolves the issue but I'd rather not lock to that version if a new driver is coming soon.

2021-08-03 16:27 UTC, DmitryLukyanov commented
Hello @damon-mcgraw-rack thanks for your message, I don't see this error with any currently released driver versions. Can you please provide more details about your use case?

2021-08-03 17:04 UTC, damon-mcgraw-rack commented
@DmitryLukyanov Thanks for the quick response!
We have an IIS hosted web API targeting .Net Framework 4.7, the API loads various plugins through reflection depending on it's configuration and some of those plugins use the C# mongo driver. I'm seeing the error in our CI server, as well as our test environment when the plugin is loaded. 
We're using MongoDb.Driver 2.13 and MongoDb.LibMongoCrypt 1.2.2 when I see the error. With MongoDb.LibMongocrypt 1.2.1 the error goes away.

I suspected the namespace changed when the enum was moved and saw that this also updated the mongocrypt version used by the driver.
I'll try to provide a more specific example.

2021-08-03 17:07 UTC, DmitryLukyanov commented
yeah, more specific example will be helpful, `MongoDb.Driver 2.13` should look at `MongoDb.LibMongocrypt 1.2.1`, so I'm still now sure what exactly leads to your issue

2021-08-03 17:10 UTC, damon-mcgraw-rack commented
I think that's exactly it, I was using MongoDb.Driver 2.13 with MongoDb.LibMongoCrypt 1.2.2 as there isn't a newer release of MongoDb.Driver.

2021-08-03 17:18 UTC, DmitryLukyanov commented
by default, the `2.13 mongo driver` should work only with `MongoDb.LibMongocrypt 1.2.1`, so the question here is how the `2.13 driver` in your case sees `1.2.2 MongoDb.LibMongocrypt` ?

2021-08-03 17:20 UTC, damon-mcgraw-rack commented
We update the packages frequently and just pull the latest available, so once the 1.2.2 MongoDb.LibMongoCrypt was available it was automatically pulled in. I can lock the MongoDb.LibMongoCrypt version to 1.2.1 until a new driver is released if there are no current plans to release a new MongoDb.Driver package.

2021-08-03 17:23 UTC, DmitryLukyanov commented
>We update the packages frequently 

so you changed this [reference](https://github.com/mongodb/mongo-csharp-driver/blob/v2.13.0/src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj#L129) manually/via reflection somehow?

2021-08-03 17:25 UTC, damon-mcgraw-rack commented
The nuget package is a packages.config file and our process just goes through and updates anything in that file.
It's similar to just doing `Get-Project -All | update-package` from the package manager console in VS. 
So yes once the package is include from the initial addition of MongoDb.Driver, it is updated independently.

2021-08-05 13:18 UTC, DmitryLukyanov commented
Hello @damon-mcgraw-rack , the driver 2.13.1 has been released. This release works with the latest libmongocrypt version, so it should solve your issue.

2021-08-05 14:35 UTC, damon-mcgraw-rack commented
@DmitryLukyanov I've confirmed that with the new packages my issue is resolved. Thank you for the quick response!