CSHARP-3658: Versioned API Connection Examples for Docs
mongodb/mongo-csharp-driver pull request #533
Opened 2021-05-19 16:01 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3658

2021-05-20 15:26 UTC, jyemin requested changes

2021-05-20 15:26 UTC, jyemin commented on tests/MongoDB.Driver.Examples/VersionedApiExamples.cs
> +            mongoClientSettings.ServerApi = serverApi; // ServerApi is not available as a connection string option and should be configured on the settings object
Let's remove the comment

2021-05-20 15:26 UTC, jyemin commented on tests/MongoDB.Driver.Examples/VersionedApiExamples.cs
> +            var serverApi = new ServerApi(ServerApiVersion.V1, strict: false); // Current server default is false, but it can be specified explicitly
Let's remove the comment

2021-05-20 16:50 UTC, rstam approved these changes
LGTM

I'm fine with Jeff's suggested changes

2021-05-31 18:45 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-05-31 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Examples/VersionedApiExamples.cs
> +            mongoClientSettings.ServerApi = serverApi; // ServerApi is not available as a connection string option and should be configured on the settings object
Done.

2021-05-31 18:45 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Examples/VersionedApiExamples.cs
> +            var serverApi = new ServerApi(ServerApiVersion.V1, strict: false); // Current server default is false, but it can be specified explicitly
Done.

2021-06-02 15:15 UTC, jyemin approved these changes
LGTM

2021-06-02 19:19 UTC, merged