CSHARP-3516: Use hello command when API Version is declared.
mongodb/mongo-csharp-driver pull request #536
Opened 2021-05-26 00:47 UTC by JamesKovacs

This implements using `hello` instead of `isMaster` when server API version is declared for both the initial handshake and monitoring.

NOTE: This PR does not add support for `helloOk:true` and using `hello` for monitoring on supporting servers, which will be implemented separately in CSHARP-3659.

2021-05-26 01:25 UTC, JamesKovacs commented
The full test suite passes locally (on OSX), but there are some failures on EG. I'm going to investigate Wednesday morning to understand what's broken and why.

2021-05-28 20:55 UTC, JamesKovacs commented
We have some existing failures on latest but tests now pass otherwise. Ready for PR.

2021-06-03 21:14 UTC, rstam requested changes
Overall looks good.

Some minor refactoring requested.

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
> +                return false;
I think a switch statement is more understandable.

You could handle this with a **much** smaller change:

    switch (commandName.ToLowerInvariant())
    {
        // string constants MUST all be lowercase for the case-insensitive comparison to work
        case "authenticate":
        case "saslstart":
        case "saslcontinue":
        case "getnonce":
        case "createuser":
        case "updateuser":
        case "copydbgetnonce":
        case "copydbsaslstart":
        case "copydb":
            return true;

        case "hello":
        case string when commandName.Equals(OppressiveLanguageConstants.LegacyHelloCommandName, StringComparison.OrdinalIgnoreCase):
            return command.Names.Any(n => n.ToLowerInvariant() == "speculativeauthenticate");

        default:
            return false;
    }

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
> +            var helloCommand = serverApi != null ? HelloCommand.Modern : HelloCommand.Legacy;
Rename variable to `helloCommandName`

    var helloCommandName = serverApi != null ? "hello" : OppressiveLanguageConstants.LegacyHelloCommandName;

(it's only the name of the command, not the command)

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/IsMasterResult.cs
> +                        || _wrapped.GetValue(HelloCommand.LegacyResponseIsWritablePrimary, false).ToBoolean())
I realize we all have our preferred formatting conventions, but in most our driver code this would be formatted as:

    if (_wrapped.GetValue("isWritablePrimary", false).ToBoolean() ||
        _wrapped.GetValue(OppressiveLanguageConstants.LegacyHelloResponseIsWritablePrimaryFieldName, false).ToBoolean())

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/HelloCommand.cs
> +    internal static class HelloCommand
My initial reaction to this class name was confusion. It doesn't represent a hello command at all.

I am also against obfuscating string constants by hiding them in constants buried in some class separate from where they are used.

However, in offline discussions with James he explained that the whole point is to limit the number of places oppressive language is used by purposely obfuscating them.

So in that spirit I propose this class be refactored to:

    internal static class OppressiveLanguageConstants
    {
        public const string LegacyHelloCommandName = "isMaster";
        public const string LegacyHelloResponseIsWritablePrimaryFieldName = "ismaster";
    }

Note: I'm proposing leaving only the oppressive language constants, so there is one fewer constant than before.

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/Messages/CommandMessage.cs
> +            HelloCommand.Legacy,
Proposed refactoring:

    "hello",
    OppressiveLanguageConstants.LegacyHelloCommandName,

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                // the serer supports OP_MSG.
s/serer/server/

2021-06-03 21:14 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                     (serverVersion != null && Feature.CommandMessage.IsSupported(serverVersion)))
Indent 4 spaces instead of 5

2021-06-03 23:40 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/IsMasterResult.cs
> +                        || _wrapped.GetValue(HelloCommand.LegacyResponseIsWritablePrimary, false).ToBoolean())
I'm good with consistency. Updated.

2021-06-03 23:40 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
> +            var helloCommand = serverApi != null ? HelloCommand.Modern : HelloCommand.Legacy;
Valid point on variable name.

2021-06-03 23:40 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
> +                return false;
Done.

2021-06-03 23:47 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/HelloCommand.cs
> +    internal static class HelloCommand
Works for me. I've inlined `Modern` so the literal string "hello" is used as needed.

This makes the eventual removal of `OppressiveLanguageConstants` easier in some future version. Just find usages and fix.

2021-06-03 23:47 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/WireProtocol/Messages/CommandMessage.cs
> +            HelloCommand.Legacy,
Done.

2021-06-03 23:48 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                // the serer supports OP_MSG.
Thanks for catching the typo. 👍

2021-06-03 23:49 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                     (serverVersion != null && Feature.CommandMessage.IsSupported(serverVersion)))
Fixed.

2021-06-03 23:53 UTC, JamesKovacs commented
Incorporated @rstam's feedback.

2021-06-05 00:21 UTC, MikalaiMazurenka reviewed
I have no major comments about the code, but have questions on the scope of the changes, which should also make the topic clearer to me.

2021-06-05 00:21 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
I think the test name doesn't clearly reflect the wire protocol part. Consider something like:
`Authenticate_should_send_serverApi_and_use_command_wire_protocol_if_serverApi_is_provided`

2021-06-05 00:21 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBX509AuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Consider something like:
`Authenticate_should_send_serverApi_and_use_command_wire_protocol_if_serverApi_is_provided`
Unfortunately my suggestion doesn't mention the query wire protocol, but it would be too lengthy with it.

2021-06-05 00:21 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/PlainAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Consider:
`Authenticate_should_send_serverApi_and_use_command_wire_protocol_if_serverApi_is_provided`

2021-06-05 00:21 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Consider:
`Authenticate_should_send_serverApi_and_use_command_wire_protocol_if_serverApi_is_provided`

2021-06-05 00:21 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha256AuthenticatorTests.cs
> +            var saslStartReply = RawBsonDocumentHelper.FromJson($"{{ conversationId : 1, payload : BinData(0,'{ToUtf8Base64(__serverResponse1)}'), done : false, ok : 1 }}");
Consider changing the test name to something like:
`Authenticate_should_send_serverApi_and_use_command_wire_protocol_if_serverApi_is_provided`

2021-06-07 17:25 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                var command = CustomizeInitialIsMasterCommand(HelloHelper.CreateCommand(_serverApi));
The driver has to continue to support `isMaster` for the time being.

The idea is to use `hello` when we know the server will support it, but to use `isMaster` otherwise.

2021-06-07 17:25 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
> +                case string when commandName.Equals(OppressiveLanguageConstants.LegacyHelloCommandName, StringComparison.OrdinalIgnoreCase):
I think it is necessary.

1. We have to support both `hello` and `isMaster` because older servers don't use `hello`
2. I agree that string literals are more readable but it is a goal of the oppressive language spec to minimize the number of places oppressive language is used, and one way to do that is to hide the oppressive language behind a string constant

2021-06-07 17:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                var command = CustomizeInitialIsMasterCommand(HelloHelper.CreateCommand(_serverApi));
Originally I had both `isMaster` and `hello` abstracted away as constants to keep things consistent, but @rstam suggested I inline the `hello` constants for readability and consistency with the rest of the code base. Abstracting away "isMaster" into a constant called "LegacyHello" was part of the original goal to minimize the use of oppressive language in the driver.

2021-06-07 18:06 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                AddErrorLabelIfRequired(exception, connection.Description?.ServerVersion);
If we send `hello` for the initial handshake to a server that doesn't support it then we will receive a `CommandNotFound` error and this will happen before we call `buildInfo`. Without this null check, we will throw a `NullReferenceException` when attempting to determine the ServerVersion. With the null check, we return a much more comprehensible error noting that "no such command: 'hello'" on down-level servers.

2021-06-07 18:36 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoAWSAuthenticatorTests.cs
> +            var saslStartReply = RawBsonDocumentHelper.FromJson(saslStartReplyString);
Valid point. Fixed test naming.

2021-06-07 18:37 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBCRAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Fixed.

2021-06-07 18:39 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/MongoDBX509AuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Fixed.

2021-06-07 18:39 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/PlainAuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Fixed.

2021-06-07 18:40 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +        public void Authenticate_should_send_serverApi_with_wire_protocol(
Fixed.

2021-06-07 18:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha256AuthenticatorTests.cs
> +            var saslStartReply = RawBsonDocumentHelper.FromJson($"{{ conversationId : 1, payload : BinData(0,'{ToUtf8Base64(__serverResponse1)}'), done : false, ok : 1 }}");
Fixed.

2021-06-07 18:55 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
> +                case string when commandName.Equals(OppressiveLanguageConstants.LegacyHelloCommandName, StringComparison.OrdinalIgnoreCase):
Yes, it is necessary. The main goal of the project is to remove oppressive language from our code bases and when that's not possible, minimize its scope by introducing friendlier constants indicating the purpose (e.g. LegacyHello).

2021-06-07 18:56 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/HelloHelper.cs
> +            var helloCommandName = serverApi != null ? "hello" : OppressiveLanguageConstants.LegacyHelloCommandName;
Necessary due to goals of the project as explained above. Happy to answer any additional questions you might have.

2021-06-07 19:02 UTC, rstam approved these changes
LGTM

I didn't review the tests carefully but it looks like Mikalai did so I'm relying on his review there.

2021-06-07 19:26 UTC, merged