CSHARP-3688: Snapshot reads on Secondaries
mongodb/mongo-csharp-driver pull request #556
Opened 2021-06-26 09:20 UTC by BorisDog

2021-06-26 09:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedFindOperation.cs
> +                using var cursor = _session == null
Not just refactoring, added `using`.

2021-06-26 09:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +        public BsonTimestamp SnapshotTime => _snapshotTime;
`SnapshotTime` property is likely to be exposed in `IClientSession` interface later.

2021-06-28 21:35 UTC, rstam requested changes
Overall looks good. Some small changes requested.

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver/ClientSessionOptions.cs
> +        /// Gets or sets a value indicating whether this snapshot reads are requested.
/// Gets or sets a value indicating whether snapshot reads are requested.

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver/ClientSessionOptions.cs
> +                throw new MongoClientException("Combining both causal consistency and snapshot options is not supported.");
This is too late to be checking for this error.

Try moving the check to where the user first provides the options, maybe in `StartSession`

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +        public void TrySetSnapshotTime(BsonTimestamp snapshotTime)
This method doesn't really follow the expected behavior of `TryXyz` naming convention.

I suggest renaming this method to `SetSnapshotTimeIfNeeded`

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +            _snapshotTime = snapshotTime;
This logic would probably be easier to read and understand if refactored to:

            if (IsSnapshot && _snapshotTime == null)
            {
                _snapshotTime = snapshotTime;
            }

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSessionOptions.cs
> +            bool isSnapshot = false,
This change looks backward breaking.

Does it matter? If so figure out if there is a less breaking form (it might be impossible given that all parameters are optional).

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/DistinctOperation.cs
> +            var serialzer = new DistinctDeserializer(_valueSerializer);
Fix typo in variable name, rename to `serializer`

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/DistinctOperation.cs
> +        private sealed class DistinctDeserializer : SerializerBase<DistinctResult>
Rename class to `DistinctResultDeserializer`

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs
> +            if (cursorDocument.TryGetValue("atClusterTime", out var atClusterTimeDocument))
The variable name `atClusterTimeDocument` is not correct (because it's *not* a document).

Refactor to:

            if (cursorDocument.TryGetValue("atClusterTime", out var atClusterTime))
            {
                channelSource.Session.SetSnapshotTimeIfNeeded(atClusterTime.AsBsonTimestamp);
            }

2021-06-28 21:35 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs
> +            var atClusterTime = _readConcern.Level == ReadConcernLevel.Snapshot ? cursorDocument["atClusterTime"].AsBsonTimestamp : null;
Remove this unnecessary line.

2021-06-28 21:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
> +        public void IsSnapshot_and_causall_consistency_is_not_allowed()
`causal` does not have a double `ll`.

Also, if this check is moved to `StartSession` the test needs to be moved somewhere more appropriate.

2021-06-28 21:35 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedFindOperation.cs
> +                var result = await cursor.ToListAsync(cancellationToken);
Add `cancellationToken` to call to `ToList` on line 50 also.

2021-07-08 16:45 UTC, BorisDog commented on src/MongoDB.Driver/ClientSessionOptions.cs
> +                throw new MongoClientException("Combining both causal consistency and snapshot options is not supported.");
Good point. Done.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSessionOptions.cs
> +            bool isSnapshot = false,
Thanks, replaced the parameters order to be on the safe side.
Probably does not matter much as looks like `CoreSessionOptions` is intended for internal use.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/DistinctOperation.cs
> +            var serialzer = new DistinctDeserializer(_valueSerializer);
Fixed.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/DistinctOperation.cs
> +        private sealed class DistinctDeserializer : SerializerBase<DistinctResult>
Done.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs
> +            if (cursorDocument.TryGetValue("atClusterTime", out var atClusterTimeDocument))
Done.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs
> +            var atClusterTime = _readConcern.Level == ReadConcernLevel.Snapshot ? cursorDocument["atClusterTime"].AsBsonTimestamp : null;
Good catch, done.

2021-07-08 20:57 UTC, BorisDog commented on src/MongoDB.Driver/ClientSessionOptions.cs
> +        /// Gets or sets a value indicating whether this snapshot reads are requested.
Done.

2021-07-08 20:57 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
> +        public void IsSnapshot_and_causall_consistency_is_not_allowed()
Renamed.
This test is session prose test, so looks like `SessionsProseTests` under "sessions" folder is the natural location.

2021-07-08 20:57 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedFindOperation.cs
> +                var result = await cursor.ToListAsync(cancellationToken);
Thanks, done.

2021-07-09 18:48 UTC, rstam approved these changes
LGTM

Thanks for making the suggested changes.

2021-07-19 15:16 UTC, BorisDog commented
[Merged here](https://github.com/mongodb/mongo-csharp-driver/commit/2bd8c40429f6af03cd2f8e6e2b045ce134adb7ce)

2021-07-19 15:16 UTC, closed without merging