CSHARP-3672: LB support integration testing.
mongodb/mongo-csharp-driver pull request #560
Opened 2021-06-30 00:37 UTC by DmitryLukyanov

2021-06-30 00:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +        public int? BatchSize
this and similar changes are required because now we need more options for some operations in testing even though in the spec they're marked as "MAY be added"

2021-06-30 00:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedErrorMatcher.cs
> +                MongoClientException or
according to the spec, a timeout exception is client side error

2021-06-30 00:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +        public static List<object> FilterEventsByType(List<object> incomeEvents, string eventType)
for some reason the spec wants to compare events separately, command and cmap

2021-06-30 00:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                                    // TODO: not implemented yet
temporary reverted

2021-07-01 17:59 UTC, rstam requested changes
Overall looks good. Some changes requested.

2021-07-01 17:59 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +                throw new ArgumentNullException(paramName, "Value must be assigned.");
I don't think `ArgumnetNullException` is correct here. I suggest:

    throw new ArgumentException("The Nullable parameter must have a value.", paramName);

Note: I realize `Nullable<T>` uses `null` as a way of specifying "does not have value", but I think `ArgumentNullException` is only appropriate for `null` references to a reference class.

2021-07-01 17:59 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        public static Nullable<T> HasValue<T>(Nullable<T> value, string paramName) where T : struct
This method is a good addition to this class.

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +        public static List<object> FilterEventsByType(List<object> incomeEvents, string eventType)
I would rename `incomeEvents` to just `events`

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAggregateOnCollectionOperation.cs
> +                        break;
Why change the order to not be in alphabetical order?

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAggregateOnCollectionOperation.cs
> +            if (operatorName == "$out" || operatorName == "$merge")
If we're going to change the variable name I think a more accurate change would be to:

    lastStageName

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseCursorOperation.cs
> +    internal static class AsyncCursorEnumeratorReflector
This class should be in the `AsyncCursorEnumeratorTests.cs` file

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseCursorOperation.cs
> +    internal static class ChangeStreamCursorReflector
Use the existing class in the `ChangeStreamCursorTests.cs` file

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
I suggest refactoring this whole method to:

    public OperationResult Execute(CancellationToken cancellationToken)
    {
        using (var timeoutCancelationTokenSource = new CancellationTokenSource(_timeout))
        using (var linkedCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutCancelationTokenSource.Token))
        {
            while (true)
            {
                try
                {
                    linkedCancellationTokenSource.Token.ThrowIfCancellationRequested();
                    _enumerator.MoveNext(); // if MoveNext took a CancellationToken we would have passed linkedCancellationTokenSource.Token in
                    var current = _enumerator.Current;
                    if (current != null)
                    {
                        return OperationResult.FromResult(_converter.Convert(current));
                    }
                }
                catch (Exception exception) when (!linkedCancellationTokenSource.IsCancellationRequested)
                {
                    return OperationResult.FromException(exception);
                }
            }
        }
    }

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
I would suggest refactoring this whole method to:

    public Task<OperationResult> ExecuteAsync(CancellationToken cancellationToken)
    {
        using (var timeoutCancelationTokenSource = new CancellationTokenSource(_timeout))
        using (var linkedCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutCancelationTokenSource.Token))
        {
            while (true)
            {
                try
                {
                    linkedCancellationTokenSource.Token.ThrowIfCancellationRequested();
                    _enumerator.MoveNext(); // TODO: Change to async counterpart when async enumeration is implemented
                    var current = _enumerator.Current;
                    if (current != null)
                    {
                        return Task.FromResult(OperationResult.FromResult(_converter.Convert(current)));
                    }
                }
                catch (Exception exception) when (!linkedCancellationTokenSource.IsCancellationRequested)
                {
                    return Task.FromResult(OperationResult.FromException(exception));
                }
            }
        }
    }

2021-07-01 17:59 UTC, rstam commented on tests/MongoDB.Driver.Tests/AsyncCursorTests.cs
> +        public static int? _batchSize(this AsyncCursor<BsonDocument> obj) => (int?)Reflector.GetFieldValue(obj, nameof(_batchSize));
Keep in alphabetical order?

2021-07-01 18:27 UTC, DmitryLukyanov reviewed
ready for review

2021-07-01 18:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +                throw new ArgumentNullException(paramName, "Value must be assigned.");
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +                return _collection.UsingImplicitSession(session => List(session, options: null, cancellationToken), cancellationToken);
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoCollectionImpl.cs
> +                return _collection.UsingImplicitSessionAsync(session => ListAsync(session, options: null, cancellationToken), cancellationToken);
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AsyncCursorTests.cs
> +        public static int? _batchSize(this AsyncCursor<BsonDocument> obj) => (int?)Reflector.GetFieldValue(obj, nameof(_batchSize));
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +        public static List<object> FilterEventsByType(List<object> incomeEvents, string eventType)
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAggregateOnCollectionOperation.cs
> +                        break;
this change was added to master after the time I started to work on this ticket, so it's merging issue. Changed order

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAggregateOnCollectionOperation.cs
> +            if (operatorName == "$out" || operatorName == "$merge")
done

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseCursorOperation.cs
> +    internal static class ChangeStreamCursorReflector
these classes are in Core, so we don't see this reflectors

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseCursorOperation.cs
> +    internal static class AsyncCursorEnumeratorReflector
these classes are in Core, so we don't see this reflectors

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
I agreed that it's better to handle cancellationToken also, however I think cancellation exception and timeout like `InvalidOperationException` should not be the same exceptions. I think the current merged code looks better.

2021-07-01 18:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
answered above

2021-07-01 18:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
The refactoring I suggested was so that everything would still work if a new overload of `MoveNext` was added that took a cancellationToken:

    _enumerator.MoveNext(linkedCancellationTokenSource.Token);

So as a general rule we want to be able to handle cancellation even if it happens deep at a lower level.

2021-07-01 18:53 UTC, rstam requested changes
Please take another look at the suggested refactoring for `UnifiedIterateUntilDocumentOrErrorOperation.Execute`

I think you should reconsider.

Please reply with further justifications if you disagree.

2021-07-01 18:59 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +            throw new InvalidOperationException($"The {nameof(UnifiedIterateUntilDocumentOrErrorOperation<TDocument>)} executing exceed timeout {_timeout.TotalMilliseconds}ms.");
>everything would still work if a new overload of MoveNext was added that took a cancellationToken:

it's true for the current code also, the only difference that in the current code we don't loose the difference between timeout-like exception and cancellation exception

2021-07-01 20:06 UTC, rstam requested changes

2021-07-01 20:06 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +                    while (!linkedCancellationTokenSource.IsCancellationRequested)
I don't think a `while` loop is even needed here. `MoveNext` will block until a result document is available.

If we remove the `while` loop we can also remove the timeout.

2021-07-01 20:31 UTC, rstam requested changes
See simplification of `UnifiedIterateUntilDocumentOrErrorOperation.Execute` by removing `while` loop that is not needed.

2021-07-01 20:31 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedIterateUntilDocumentOrErrorOperation.cs
> +                    while (!linkedCancellationTokenSource.IsCancellationRequested)
I suggest this:

    public OperationResult Execute(CancellationToken cancellationToken)
    {
        try
        {
            var hasNext = _enumerator.MoveNext();
            if (hasNext == false)
            {
                throw new InvalidOperationException("Unexpected false return value from MoveNext.");
            }
            return OperationResult.FromResult(_converter.Convert(_enumerator.Current));
        }
        catch (Exception exception)
        {
            return OperationResult.FromException(exception);
        }
    }

We could remove the check on `hasNext == false` if we are confident that can never happen.

2021-07-01 20:45 UTC, DmitryLukyanov commented
ready for review

2021-07-01 20:55 UTC, rstam approved these changes
LGTM

2021-07-01 20:57 UTC, merged