CSHARP-3699: Bump maxWireVersion for MongoDB 5.0
mongodb/mongo-csharp-driver pull request #561
Opened 2021-06-30 14:48 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3699
EG: https://evergreen.mongodb.com/version/60dc82e52a60ed2f9c2432c0

2021-06-30 16:19 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        [InlineData(14, 15, true)]
I didn't add the tests as requested ([comment](https://jira.mongodb.org/browse/CSHARP-3699?focusedCommentId=3862427&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3862427)) because this test already does what intended, so I just bumped the wire version here. Let me know if you think a new test is required.

2021-07-07 22:15 UTC, JamesKovacs requested changes
One minor suggestion to add a few more test cases to verify edge case behaviour of the wire version check. Otherwise LGTM.

2021-07-07 22:15 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        [InlineData(14, 15, true)]
Works for me. My concern was to ensure that we test with incompatible wire versions, not that we write a new test specifically for this ticket.

2021-07-07 22:15 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs
> +        [InlineData(new[] { 14, 15 }, false)]
We should add some test cases that overlap but exceed the high end just as we do with the low end. I'd suggest:
```
[InlineData(new[] { 10, 14 }, true)]
[InlineData(new[] { 13, 15 }, true)]
```

2021-07-08 00:19 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-07-08 00:19 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs
> +        [InlineData(new[] { 14, 15 }, false)]
Good point!
Done

2021-07-08 16:34 UTC, JamesKovacs approved these changes
LGTM

2021-07-08 17:37 UTC, merged