CSHARP-3676: SRV support for load balancer mode + SDAM.
mongodb/mongo-csharp-driver pull request #562
Opened 2021-07-01 23:48 UTC by DmitryLukyanov

EG:  https://evergreen.mongodb.com/version/60de54362fbabe3344a05f95

2021-07-01 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            // TODO: temporary reverted
this will be added in the scope of CMAP changes

2021-07-01 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                _description = await _connectionInitializer.HandshakeAsync(this, cancellationToken).ConfigureAwait(false);
we need to know serviceId even though the connection fails, so I split this logic into 2 parts: handshake itself and authentication (+getLastError)

2021-07-01 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/IsMasterResult.cs
> +                    return ServerType.LoadBalanced; // TODO: change when Service Id will be supported by server
this should be updated according to the discussion we had on today meeting with Jeff (this should be filled only for LB)

2021-07-01 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/DefaultServer.cs
> +                (exception as MongoWriteConcernException)?.MappedWriteConcernResultException
this line corresponds to these lines in the master: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Servers/Server.cs#L526-L542. In 2 words, we just make the same logic as in ExceptionMapper only because the actual exception can be hidden inside `MongoWriteConcernException.writeConcernError`, I extract it into `MappedWriteConcernResultException` and as a result no reason to analyze exception codes on this level anymore.

However, to save time I'm ok to move this logic into a different ticket

2021-07-01 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +                mongoAuthenticationException.ServiceId.HasValue) // this value will be always filled for MongoAuthenticationException, adding this condition just in case
`mongoAuthenticationException.ServiceId.HasValue` this value should always present for LB mode, maybe it makes sense to trigger exception if for some reason it's null?

2021-07-01 23:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerMonitorTests.cs
> +        [Fact(Skip = "Will check this test")]
this is failing, I will investigate it now

2021-07-02 02:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/CoreServerSessionPool.cs
> +            var clusterType = _cluster.Description.Type;
related to sessions expiring

2021-07-06 17:24 UTC, rstam requested changes
Overall looks good with minor changes requested.

The only file I had a lot of trouble verifying is `DefaultServer.cs`. I expected it to have only minor differences from the original `Server.cs` but it has major differences. I think they all look OK but my confidence level is low.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/MultiServerCluster.cs
> +                Ensure.That(!settings.DirectConnection.GetValueOrDefault(), "DirectConnection is not supported for a MultiServerCluster.");
Will never throw because base class constructor would have already thrown.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
> +            IDnsMonitorFactory dnsMonitorFactory)
I thought it was a bug that this class was NOT calling the base class constructor.

And then I discovered to my total surprise that `LoadBalancedCluster`  is not a subclass of `Cluster`.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                }
I think lines 302-306 can be more simply written as:

                _description ??= handshakeDescription;

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                }
Same comment as above.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +
This method is probably not necessary. See comments above.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/IConnectionInitializer.cs
> +        ConnectionDescription Handshake(IConnection connection, CancellationToken cancellationToken);
Method names should be verbs and `Handshake` is a noun. Perhaps `Initialize` or  `SendHello`?

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/IConnectionInitializer.cs
> +        ConnectionDescription ConnectionAuthentication(IConnection connection, ConnectionDescription description, CancellationToken cancellationToken);
Method names should be verbs and `ConnectionAuthentication` is a noun. How about more simply `Authenticate`?

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/IConnectionInitializer.cs
> +        Task<ConnectionDescription> ConnectionAuthenticationAsync(IConnection connection, ConnectionDescription description, CancellationToken cancellationToken);
Alphabetical order?

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +            // no-opt
Change `no-opt` to `no-op` everywhere

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                Initializing();
This method name is confusing... what's the difference between `Initialize` and `Initializing`. They are basically synonyms.

How about `InitializeSubClass`?

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        private bool IsOpened() => _state.Value == State.Open;
Rename to `IsOpen`

The `ed` ending is not needed.

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerFactory.cs
> +                        _serverApi),
Remove redundant comma at end of line

2021-07-06 17:24 UTC, rstam commented on src/MongoDB.Driver.Core/MongoWriteConcernException.cs
> +            mappedException = null;
Move this assignment to immediately before `return false` line 63.

Not setting and out parameter to `null` at the top of the method allows the compiler to give us an error message if we forget to assign a value to an out parameter before returning `true`.

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/SingleServerCluster.cs
> +            Ensure.That(!settings.LoadBalanced, $"Load balanced mode is not supported for a {nameof(SingleServerCluster)}.");
also removed

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +            // no-opt
done

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +                Initializing();
the second one is already in progress :), `InitializeSubClass` sounds good to me, done

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/Server.cs
> +        private bool IsOpened() => _state.Value == State.Open;
done

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerFactory.cs
> +                        _serverApi),
done

2021-07-06 18:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoWriteConcernException.cs
> +            mappedException = null;
done

2021-07-06 18:39 UTC, rstam requested changes
A few minor questions remain. Almost ready to approve.

2021-07-06 18:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                _description = handshakeDescription;
This is slightly different that what I had suggested:

    _description ??= handshakeDescription;

They might be the same thing, but only if you guarantee that no further exceptions are thrown after the assignment to `_description` in the `try` block.

2021-07-06 18:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // we always need to have access to description after handshake regardless furher errors
Can we just remove this comment? It doesn't make sense to me.

If you insist on keeping it we will have to work on rewording it.

2021-07-06 18:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // if we have successful handshake description, we should propogate it to upper levels
Can we just remove this comment? It doesn't make sense to me.

If you insist on keeping it we will have to work on rewording it.

2021-07-06 18:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/IConnectionInitializer.cs
> +        Task<ConnectionDescription> SendHelloAsync(IConnection connection, CancellationToken cancellationToken);
Note: I am unfamiliar with the use of "handshake" as a verb. I don't think it's very common. But using `SendHello` avoids the question of whether "handshake" can be used as a verb or not.

For example, this dictionary defines it as a noun ony:

https://www.dictionary.com/browse/handshake

2021-07-06 18:57 UTC, DmitryLukyanov reviewed
ready for review

2021-07-06 18:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // if we have successful handshake description, we should propogate it to upper levels
done

2021-07-06 18:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                _description = handshakeDescription;
my mistake, fixed

2021-07-06 19:09 UTC, rstam requested changes
There are still some pending comments.

2021-07-06 19:09 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // we always need to have access to description after handshake regardless furher errors
Pending

2021-07-06 19:09 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // we always need to have access to description after handshake regardless furher errors
Can we just remove this comment? It doesn't make sense to me.

If you insist on keeping it we will have to work on rewording it.

2021-07-06 19:13 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/BinaryConnection.cs
> +                // we always need to have access to description after handshake regardless furher errors
I thought you meant only comments in the catch block, to save time I'm ok to remove this also, done

2021-07-06 19:15 UTC, rstam approved these changes
LGTM

2021-07-06 20:37 UTC, merged