CSHARP-3714: Implement missing test from Versioned API specification
mongodb/mongo-csharp-driver pull request #563
Opened 2021-07-06 21:40 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3714
EG: https://evergreen.mongodb.com/version/60e4ccd32fbabe528bceae27

2021-07-07 17:45 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilderExtensions.cs
> +            if (serverApi != null)
This is the only driver code change. I noticed that this method applies `serverApi` only to auth mechanisms, but should apply it to cluster builder as well.

2021-07-07 17:49 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/BulkMixedWriteOperationTests.cs
> +            RequireServer.Check().Supports(Feature.CommandMessage).RequireApiVersion(false);
The batch splitting depends on the current position in the buffer on the start of batch size calculation and `apiVersion` field wasn't initially expected here, so when present it shift the buffer position by 18, which I took into account by splitting tests with `serverApi` and without `serverApi`.

2021-07-07 18:25 UTC, jyemin commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilderExtensions.cs
> +            if (serverApi != null)
What is the effect of not having this?  What doesn't work?

2021-07-07 20:23 UTC, MikalaiMazurenka commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilderExtensions.cs
> +            if (serverApi != null)
Without this change if user want to configure `ClusterBuilder` with `serverApi` and connection string they would write:
```
var builder = new ClusterBuilder().ConfigureWithConnectionString(connectionString, serverApi);
```
But only authentication mechanism will be configured with `serverApi` and the cluster itself will have `serverApi` set to `null`. So the complete configuration will need one more call:
```
var builder = new ClusterBuilder().ConfigureWithConnectionString(connectionString, serverApi).ConfigureCluster(c => c.With(serverApi: serverApi));
```
Which I stumbled upon myself, thinking that I implemented `ConfigureWithConnectionString` to configure `serverApi` for all aspects of cluster.
So while it's debatable whether this is a bug, without this change the `ConfigureWithConnectionString` method behavior is at least unintuitive.

2021-07-07 21:30 UTC, JamesKovacs requested changes
Overall LGTM. Minor changes requested.

2021-07-07 21:30 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        public static ServerApi GetServerApi()
This should be a lazy static property like `Cluster`, `ConnectionString`, etc.

2021-07-07 23:49 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-07-07 23:49 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/BulkMixedWriteOperationTests.cs
> +            RequireServer.Check().Supports(Feature.CommandMessage).RequireApiVersion(false);
Great point!
Done

2021-07-07 23:49 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        public static ServerApi GetServerApi()
I generally think this class should be reimplemented. I do not think that overcomplicating the code with excessive usage of statics is worth the tiny performance savings. But agree that this PR is not the point to start major test code changes.
Done

2021-07-08 16:24 UTC, JamesKovacs approved these changes
LGTM

2021-07-08 22:31 UTC, merged