CSHARP-3673: Update connection pinning logic for LB mode.
mongodb/mongo-csharp-driver pull request #564
Opened 2021-07-06 22:16 UTC by DmitryLukyanov

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                    catch (MongoException ex)
in the current test suite we need to wrap MongoConnectionException into MongoAuthException. Maybe it makes sense to wrap all errors here?

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +                _currentTransaction?.UnpinAll();
previously we didn't need this because we didn't need to dispose the pinned server

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    SetEffectiveGenerationIfRequired(_connection.Description);
we need to update the current connection generation based on connectionsState and serviceId from the helloResponse

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                    return await _connection.ReceiveMessageAsync(responseTo, encoderSelector, messageEncoderSettings, cancellationToken).ConfigureAwait(false);
`await` needs to catch exception n this method

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +        public int GetConnectionPoolGenerationForConnection(ConnectionDescription description)
I would suggest deprecate Clear method and Generation property and instead use this method and a new method like `ClearPoolForAffectedConnections` (or similar). This will allow us handle serviceId only on the pool level. But since Generation and Clear are still described in the spec, I'm ok to move this discussion to later (or maybe we can just don't care about it)

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +            if (!TryTerminationPendingMode())
if getMore is inProgress, we need to defer closing until getMore will be finished

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +                            KillCursors(cancellationToken);
the spec says that we "MAY" protect killCursors against exception, but the current tests require this behavior

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +                if (!channel.Connection.IsExpired)
some tests require that if a connection isExpired, we should not try to run killCursors

2021-07-06 22:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/LoadBalancingIntergationTests.cs
> +        [SkippableTheory(Skip = "Investigate")]
this tests fails (for attempts > 1), because each new attempt increase referenceCounter and don't dispose enough of them, then when we got finishing like abortTransaction, the referenceCounter is bigger than expected so, actual resources like channel is not disposed

2021-07-06 22:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/load-balancers/LoadBalancersTestRunner.cs
> +                throw new SkipException("Not implemented yet.");
we decided to temporary disable these tests

2021-07-06 22:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedErrorMatcher.cs
> +            actualException
this change is related to this exception: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs#L122. That will be wrapped in the next step into `MongoConnectionException`. Maybe it makes sense to consider all innerExceptions and not only the first one

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +                    _currentTransaction.UnpinAll();
almost copy of mongos behavior for transactions

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +            _currentTransaction?.UnpinAll(); // unpin data if any when a new transaction is started
we didn't need this before, because we didn't need to dispose a pinned server

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                readBinding = new ChannelReadWriteBinding(
use a pinned connection/server if possible

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                var getMoreChannel = channelSource.GetChannel(CancellationToken.None); // no need for cancellation token since we already have channel in the source
`channelSource.GetChannel(CancellationToken.None)` effectively means `channel.Fork()` for this case

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                {
Since we fork the channel here it won't be disposed after cursor will be disposed

2021-07-06 22:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.Helpers.cs
> +                ex.Generation = _generation;
_generation is already up-to-date in the previous step

2021-07-06 23:00 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                if (IsInLoadBalancedMode(cluster.Description) && IsConnectionPinned(session.CurrentTransaction))
this logic is mostly coping from here: https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Clusters/IClusterExtensions.cs#L27

2021-07-07 15:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                if (session.IsInTransaction && !IsConnectionPinned(session.CurrentTransaction))
`!IsConnectionPinned(session.CurrentTransaction)` - a new logic, if we already pinned connection, no need to pin it again, it also allowed to remove a bit "hacky" code in the EndTransactionOperation.

2021-07-09 17:33 UTC, rstam requested changes
Some/most of the changes proposed are prototyped here:

https://github.com/rstam/mongo-csharp-driver/tree/csharp3673_v2-0708

Use my branch as a reference only, it is not intended to be fully fleshed out.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadContext.cs
> +                out var pinnedChannel))
I don't think an `out` combined with a `Tuple` is a good idea. I suggest:

    out var pinnedChannelSource,
    out var pinnedChannel))

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadContext.cs
> +                context.ReplaceChannel(pinnedChannel.Channel);
Combined with the previous comment this can read better as:

    context.ReplaceChannelSource(pinnedChannelSource);
    context.ReplaceChannel(pinnedChannel);

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableWriteContext.cs
> +                out var pinnedChannel))
I don't think an `out` combined with a `Tuple` is a good idea. I suggest:

    out var pinnedChannelSource,
    out var pinnedChannel))

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableWriteContext.cs
> +                context.ReplaceChannel(pinnedChannel.Channel);
Combined with the previous comment this can read better as:

    context.ReplaceChannelSource(pinnedChannelSource);
    context.ReplaceChannel(pinnedChannel);

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/LoadBalancedServer.cs
> +                    mongoConnectionException.Generation.Value != ConnectionPool.GetConnectionPoolGenerationForConnection(connection.Description))
mongoConnectionException.Generation.Value != ConnectionPool.GetGeneration(connection.Description?.ServiceId))

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +                    case ServerType.LoadBalanced:
I don't know if it's too late too change this but it should have been:

    ServerType.LoadBalancer

ending with "er" not "ed"

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +        public static IReadBindingHandle CreateEffectiveReadBinding(ICluster cluster, ICoreSessionHandle session, ReadPreference readPreference)
I think `CreateReadBinding` is a good enough name. Not sure "effective" is necessary.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                    session.CurrentTransaction.NewPinnedChannelHandleIfConfigured(),
session.CurrentTransaction.PinnedChannel.Fork(),

Just fork the channel. No need for a `NewPinnedChannelHandleIfConfigured` method

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +        public static IReadWriteBindingHandle CreateEffectiveReadWriteBinding(ICluster cluster, ICoreSessionHandle session)
I think `CreateReadWriteBinding` is a good enough name. Not sure "effective" is necessary.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                    session.CurrentTransaction.NewPinnedChannelHandleIfConfigured(),
session.CurrentTransaction.PinnedChannel.Fork(),

Just fork the channel. No need for a NewPinnedChannelHandleIfConfigured method

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +        internal static IChannelSourceHandle CreateEffectiveGetMoreChannelSource(IChannelSourceHandle channelSource, long cursorId)
I think `CreateGetMoreChannelSource` is a good enough name. Not sure "effective" is necessary.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +        internal static bool TryCreatePinnedChannelSourceAndPinChannel(
I would suggest `PinChannelSourceAndChannelIfRequired` as the name.

Normally `TryXyz` methods return false when they FAIL, not when an action is not required.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +            out (IChannelSourceHandle PinnedChannelSource, IChannelHandle Channel) pinnedChannel)
An `out` with `Tuple` doesn't really enhance usability. Just use two `out` vars:

    out IChannelSourceHandle pinnedChannelSource,
    out IChannelHandle pinnedChannel)

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                var forkedSession = session.Fork();
Implementation can be simplified to:

   if (IsInLoadBalancedMode(channel.ConnectionDescription))
   {
       var server = channelSource.Server;

       pinnedChannelSource = new ChannelSourceHandle(
           new ChannelChannelSource(
               server,
               channel.Fork(),
               session.Fork()));

       if (session.IsInTransaction && !IsConnectionPinned(session.CurrentTransaction))
       {
           session.CurrentTransaction.PinConnection(channel.Fork());
           session.CurrentTransaction.PinnedServer = server;
       }

       pinnedChannel = channel.Fork();

       return true;
   }

   pinnedChannelSource = null;
   pinnedChannel = null;
   return false;

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/ConnectionPools/IConnectionPool.cs
> +
The argument should be a `serviceId` instead of a connection description.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +            if (!TryTerminationPendingMode())
I did not review this file because you said you were going to revert these changes.

2021-07-09 17:33 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadContext.cs
> +        public static void PinConnectionIfRequired(this RetryableReadContext context)
As commented elsewhere I think it might be better if Create did the pinning automatically if required.

2021-07-09 19:54 UTC, DmitryLukyanov reviewed
First replies

2021-07-09 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +            if (!TryTerminationPendingMode())
done

2021-07-09 19:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +                    case ServerType.LoadBalanced:
will change this

2021-07-09 20:11 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/SaslAuthenticator.cs
> +                    catch (MongoException ex)
I leave it up to you and @jyemin whether a comment is necessary explaining why a connection error would be considered an authentication error

2021-07-09 20:11 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/CommandFailedEvent.cs
>          public CommandFailedEvent(string commandName, Exception exception, long? operationId, int requestId, ConnectionId connectionId, TimeSpan duration)
The problem is it is too easy to "forget" to pass the serviceId.

Why not pass `null` in the few instances where we don't have it?

2021-07-10 03:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> +                context.PinConnectionIfRequired();
Done

originally I thought that transactions can be added not for all operations on the driver side. So I missed some places where it should be added. Also, I added pinning connection for RetryableReads only for operations that returns cursors based on this:
>When the driver is in load balancing mode and executing any cursor-initiating command, the driver MUST NOT check the connection back into the pool unless the command fails or the server returns a cursor ID of 0 (i.e. all documents are returned in a single batch)

However, it looks harmless to add this logic for all operations in LB. But I will think about it one more time tomorrow.

2021-07-10 03:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
> +                    _server = _serverFactory.CreateServer(_clusterType, _clusterId, _clusterClock, endPoint);
`CreateInitializedServer` was waiting until server would trigger description change, but even after that the _server variable itself could still be unassigned

2021-07-10 04:03 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ChannelPinningHelper.cs
> +                pinnedChannel = channel.Fork();
done, I think I know why this change pinnedChannel = channel.`Fork()`; didn't cause any issue in my code, but I want to confirm it, so will check it tomorrow.

2021-07-10 15:55 UTC, rstam reviewed
Latest changes look good.

I added some minor comments.

2021-07-10 15:55 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +                    case ServerType.LoadBalanced:
Actually the reason I suggested the change was because I saw places in the spec that were using `LoadBalancer` instead of `LoadBalanced`.

But searching more thoroughly I find that the spec is inconsistent and uses BOTH variations.

But it seems to use `LoadBalanced` more frequently, which is unfortunate because `er` seems more correct and is already used in the `ShardRouter` `ServerType` (i.e. not `ShardRouted`).

So I guess leave as is...

2021-07-10 15:55 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Events/CommandFailedEvent.cs
>          public CommandFailedEvent(string commandName, Exception exception, long? operationId, int requestId, ConnectionId connectionId, TimeSpan duration)
I think you are missing my point that by leaving this constructor in the code we are making it easy to "forget" to pass the `serviceId` in situations where it is required.

But in any case you may leave as is.

2021-07-10 15:55 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadContext.cs
> +                    context.ReplaceChannel(pinnedChannel);
Here in the `Create` method is a good place to handle pinning. I like it.

But can't we just create the binding pinned or not? Do we have to create it "wrong" and then sometimes "replace" the channel source and channel?

2021-07-10 16:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadContext.cs
> +                    context.ReplaceChannel(pinnedChannel);
we will need to call the currently presented steps in Initialize anyway since they include selecting Server and acquiring connection and we will need to dispose original handles anyway in further pinning logic. So we can move these replacement into Initialize method. But it will be the same steps that will make exactly the same logic. I would probably won't change it

2021-07-10 18:36 UTC, rstam requested changes

2021-07-10 18:36 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        public static ConnectionString CreateConnectionString()
This name change is unnecessary, and arguably harmful.

We are "getting" the connection string from an environment variable (with suitable defaults if the environment variable isn't set).

We're not really "creating" anything. Imagine we were returning a `string` instead of wrapping it in a `ConnectionString` and it's easier to see that "get" is more appropriate than "create".

2021-07-10 18:45 UTC, rstam approved these changes
LGTM

Pending comments can be deferred until later

2021-07-13 19:14 UTC, DmitryLukyanov commented
Squashed/rebased/merged.

2021-07-13 19:14 UTC, closed without merging