CSHARP-3396: Expose the Reason an Operation Fails Document Validation
mongodb/mongo-csharp-driver pull request #566
Opened 2021-07-08 17:14 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3396
EG: https://evergreen.mongodb.com/version/60e731dd61837d70789586b3
Specification prose test: https://github.com/mongodb/specifications/blob/master/source/crud/tests/README.rst#2-writeerrordetails-exposes-writeerrorserrinfo

Note: the first prose test was in unexpected location and namespace, so I moved it without making any changes there.

2021-07-08 17:29 UTC, jyemin commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
What is the type of `exception`?  I don't really know what `InnerException` is...

2021-07-08 17:29 UTC, jyemin commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Does the exception have some sort of equivalent to Java's `toString()` method?  Or a standard Message property of type string that is printed as part of the exception stack trace?  If so, can we assert something about that message, and ensure that the write error details are serialized as a string into it?

2021-07-08 18:11 UTC, MikalaiMazurenka reviewed
Answered the questions

2021-07-08 18:11 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Yes, it has some custom logic around the `.ToString()` method, but it returns only the general info:
```
MongoDB.Driver.MongoWriteException: A write operation resulted in an error.\r\n  Document failed validation ---> MongoDB.Driver.MongoBulkWriteException`1[MongoDB.Bson.BsonDocument]: A bulk write operation resulted in one or more errors.\r\n  Document failed validation\r\n   at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken) in C:\\Projects\\MongoDB\\mongo-csharp-driver\\src\\MongoDB.Driver\\MongoCollectionImpl.cs:line 230\r\n   at 
...
```
Strictly speaking, `.ToString()` is default here and it just returns the `Message`, but the forming of the `Message` is a bit more custom, it includes the `WriteError`'s `Message` property, which in this case is `"Document failed validation"`, so the `code` and `details` fields won't make it into the exception message which the user would see.

So I see what is your concern here. The user won't see the exception details unless they access them explicitly, which is a normal practice, but requires some knowledge of driver exceptions and some custom error handling code.

**TL;DR:** Great catch! I will check if the code should be changed to include the `details` into resulting exception message.

2021-07-08 18:50 UTC, jyemin reviewed
You re-requested review before making any further changes.  So just re-reviewing to get back into the right state.

2021-07-08 18:51 UTC, jyemin commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Cool,  for the record I think both the outer and inner exception should contain info about write error(s), including the details.

2021-07-08 23:33 UTC, JamesKovacs requested changes
I don't see any changes to production code, only test code. I thought the goal of CSHARP-3396 was to make write errors more easily parsable and visible to developers. As far as I can see, the errors are still buried in inner exceptions inside stack traces.

2021-07-08 23:33 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
It would be worthwhile asserting that outer exception is a `MongoWriteException` as it expresses the intent that this operation results in a `MongoWriteException`.

Additionally you should `exception.Should().NotBeNull();` as you do on line 71. Otherwise line 102 will throw a NRE if we don't get a failure back as expected.

2021-07-08 23:33 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +}
`ConfigureFailPoint` and `CreateDisposableClient` would be very useful in one of the `TestHelpers` projects so we can easily re-use them.

2021-07-09 19:24 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Done

2021-07-09 19:24 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Done

2021-07-09 19:24 UTC, MikalaiMazurenka commented
Ready for review

2021-07-09 19:45 UTC, jyemin commented on tests/MongoDB.Driver.Tests/Specifications/crud/prose-tests/CrudProseTests.cs
> +            var bulkWriteException = exception.InnerException.Should().BeOfType<MongoBulkWriteException<BsonDocument>>().Subject;
Consider this resolved by me.  I'll leave it to James to actually resolve.

2021-07-09 19:45 UTC, jyemin approved these changes
LGTM!

2021-07-09 19:59 UTC, JamesKovacs approved these changes
LGTM

2021-07-09 21:50 UTC, merged