CSHARP-3700: Support 'let' option for aggregate command
mongodb/mongo-csharp-driver pull request #570
Opened 2021-07-12 19:07 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3700
EG: https://evergreen.mongodb.com/version/60ec91e93e8e860ef466a72a

Note: Public API `Feature` class was changed, which could be considered as a breaking change. The reason for the change is that existing `AggregateLet` feature was referring only to the `$lookup` stage of the aggregate pipeline, while the new feature applies to the whole `aggregate` operation.

2021-07-12 22:54 UTC, JamesKovacs requested changes
Overall looks good. One minor suggestion and some test improvements requested.

2021-07-12 22:54 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateLookupLet = new Feature("AggregateLookupLet", new SemanticVersion(3, 6, 0));
Rather than renaming the existing one, we should consider `Feature.AggregateOptionsLet` for the new feature. What do you think?

2021-07-12 22:54 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +        }
The query is not using `$$x`. So we don't know that the `let` variable was set correctly. Note that for `$$x` must be used in the context of an `$expr`.

2021-07-12 22:54 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateToCollectionOperationTests.cs
> +        }
The `let` variables aren't being used in the query and we don't know that they're set correctly.

2021-07-12 23:03 UTC, rstam requested changes

2021-07-12 23:03 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateLookupLet = new Feature("AggregateLookupLet", new SemanticVersion(3, 6, 0));
Definitely let's not rename an existing feature name.

2021-07-12 23:03 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +        }
Or better yet refactor the test to use the let variable in a `$project` instead of in a `$match`.

2021-07-13 14:10 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-07-13 14:10 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +        }
Added tests for each stage.
Done.

2021-07-13 14:10 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateToCollectionOperationTests.cs
> +        }
Done.

2021-07-13 15:18 UTC, rstam requested changes
The changes I am requesting are minor and could be skipped if James and Jeff are OK with the current version as-is.

2021-07-13 15:18 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOptionsLet = new Feature("AggregateOptionsLet", new SemanticVersion(5, 0, 0, ""));
Maintain alphabetical order?

2021-07-13 15:18 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public static Feature AggregateOptionsLet => __aggregateOptionsLet;
Maintain alphabetical order?

2021-07-13 15:18 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +            var expectedResult = new BsonDocument
This is a dangerous form of testing, where you essentially copy/paste essential parts of the code under test into the test. 

If the code you copy/paste has a bug the test is going to pass in spite of the bug.

In the interest of getting the release out no change needed. Just keep in mind for the future.

2021-07-13 15:19 UTC, JamesKovacs approved these changes
LGTM

2021-07-13 15:47 UTC, merged