Fix unified tests.
mongodb/mongo-csharp-driver pull request #577
Opened 2021-07-13 17:08 UTC by DmitryLukyanov

2021-07-13 17:14 UTC, BorisDog requested changes

2021-07-13 17:14 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                    ? await _database.ListCollectionsAsync(_options, cancellationToken).ConfigureAwait(false)
No need for `ConfigureAwait`

2021-07-13 17:14 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                var cursor = _session == null
I don't think that we can skip disposing entities as a pattern.
If this is a temporary patch, we need a ticket for fixing it.

2021-07-13 17:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                    ? await _database.ListCollectionsAsync(_options, cancellationToken).ConfigureAwait(false)
We seem to be inconsistent on whether to use `ConfigureAwait` in test projects or not.

2021-07-13 17:28 UTC, MikalaiMazurenka commented
Please change the PR name and commit name to something more specific, like `Add missing await to unified list operations`

2021-07-13 17:34 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                    ? await _database.ListCollectionsAsync(_options, cancellationToken).ConfigureAwait(false)
AFAIK technically we don't have a reason to use `ConfigureAwait` in tests.

2021-07-13 17:41 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                var cursor = _session == null
This will make investigating of test results harder since we will need to consider one more event. And sometimes it can be painful during debugging. From the other hand this looks like overkill to me here, but let's see what the spec author will say

2021-07-13 18:14 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                    ? await _database.ListCollectionsAsync(_options, cancellationToken).ConfigureAwait(false)
I think we did this sometimes, but at least in most of the cases it's not added. So, reverted

2021-07-13 18:16 UTC, BorisDog approved these changes

2021-07-13 18:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListCollectionsOperation.cs
> +                var cursor = _session == null
The issue is related to missed `await`. I forgot that we call `killCursors` only for `cursorId !=0`, so when we missed await, we can call `cursor.Dispose` before actual iterating. And then we will see the mentioned behavior. Adding await solves it.

2021-07-20 17:19 UTC, rstam approved these changes
LGTM

2021-07-20 20:23 UTC, merged