CSHARP-3387: Serverless testing
mongodb/mongo-csharp-driver pull request #583
Opened 2021-07-20 22:03 UTC by MikalaiMazurenka

JIRA: https://jira.mongodb.org/browse/CSHARP-3387
EG (serverless only): https://evergreen.mongodb.com/version/60f7458361837d39317cf654
EG (full run): https://evergreen.mongodb.com/version/60f7472a0305b93d3f83409f

2021-07-20 22:42 UTC, jyemin requested changes
Just a quick scan, found one thing.

2021-07-20 22:42 UTC, jyemin commented on tests/MongoDB.Driver.Tests/Specifications/retryable-reads/RetryableReadsTestRunner.cs
> +                // https://jira.mongodb.org/browse/CLOUDP-92618
Make sure not to commit with this link in the source code, as that project is private.  Maybe instead add a CSHARP ticket to re-enable these, and link the CSHARP ticket to the CLOUDP one.

2021-07-21 00:14 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-task-group
unless I don't know some context, see how framework is handled in other places for example in LB (few lines above)

2021-07-21 00:25 UTC, MikalaiMazurenka reviewed
Ready for review

2021-07-21 00:25 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/retryable-reads/RetryableReadsTestRunner.cs
> +                // https://jira.mongodb.org/browse/CLOUDP-92618
Done

2021-07-21 00:25 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +    - name: serverless-task-group
task groups cannot be arranged the same way as other tasks. So in order to test multiple frameworks in task group they should be defined as axis.

2021-07-21 15:29 UTC, MikalaiMazurenka commented
Some evergreen tasks failed with "system failure". That's because I've used all the available test instances, meaning nothing wrong with the tests or the code.

2021-07-21 18:28 UTC, DmitryLukyanov reviewed
I don't know the serverless specific deeply. So, I'm rely on the fact that tests passed.

2021-07-21 18:28 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-task-group
can you explain why `task groups` is required? It looks like java doesn't use it: https://github.com/mongodb/mongo-java-driver/pull/763/files#diff-bcd2c099e589f1ef43957739e25b7ac58b6a847e92cc1e5cc9d9c91acb2fe9f9R252

2021-07-21 18:28 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-task-group
My main point here, that it would be good to not introduce a new way to configure framework (if possible) since we already have one

2021-07-21 18:28 UTC, DmitryLukyanov commented on evergreen/run-serverless-tests.sh
> +export SERVERLESS=true
nit: I would call it: `SERVERLESS_ENABLED` or something similar

2021-07-21 18:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +            throw new SkipException("Test skipped because serverless is " + (require ? "required" : "not required"));
`dot` in the end of exception message

2021-07-21 18:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/transactions/tests/README.rst
> +Mongos Pinning Prose Tests
do we have such tests?

2021-07-21 18:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidFailTestRunner.cs
> +    [Trait("Category", "unified-test-format")]
does anything set this?

2021-07-21 18:28 UTC, DmitryLukyanov commented on build.cake
> +            var targetFramework = Environment.GetEnvironmentVariable("FRAMEWORK");
it's better to pass/handle this option in the same way as we do in other places in this file: https://github.com/mongodb/mongo-csharp-driver/blob/1c3488e2bdf2e05fc2c5d21ccaec6f5e83a4e981/build.cake#L325

2021-07-21 18:28 UTC, DmitryLukyanov commented on build.cake
> +                default: throw new ArgumentException($"Unexpected framework: \"{framework}\"");
we don't have such case option in other places here. I think it's better to choose the single approach maybe even with creating a cake method for this.

2021-07-21 18:28 UTC, DmitryLukyanov commented on build.cake
> +                default: throw new ArgumentException($"Unexpected framework: \"{framework}\"");
also, a `dot` in the end of error message

2021-07-21 18:28 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +# 42 minutes is the average for serverless tests (the longest of all, because of the heavy set up task)
this can be painful since it can hide timeout exception in some case. One of theory we have that at least partially the timeouts we have are related to performance. But I'm not sure whether we can implement it differently now

2021-07-21 18:28 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
it looks like this step never happens: https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/serverless/delete-instance.sh#L26 at least I don't see it here: https://evergreen.mongodb.com/task_log_raw/dot_net_driver_serverless_tests_ubuntu__os~ubuntu_1804_auth~auth_ssl~ssl_compressor~zlib_framework~netstandard21_serverless_tests_patch_c04e50a455112fd71df86991024ff66bec1fab97_60f7ff932fbabe15604a8a3d_21_07_21_11_06_22/0?type=T

2021-07-21 21:07 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedListIndexesOperation.cs
> +                _ = await cursor.ToListAsync(cancellationToken);
+1

2021-07-21 22:22 UTC, MikalaiMazurenka reviewed
Ready for review

2021-07-21 22:22 UTC, MikalaiMazurenka commented on evergreen/run-serverless-tests.sh
> +#   OS                                  Operating system, must be set
Removed the `MONGODB_SRV_URI`.

2021-07-21 22:22 UTC, MikalaiMazurenka commented on evergreen/run-serverless-tests.sh
> +export MONGODB_URI_WITH_MULTIPLE_MONGOSES="${MONGODB_URI:0:10}${SERVERLESS_ATLAS_USER}:${SERVERLESS_ATLAS_PASSWORD}@${MONGODB_URI:10}/?tls=true&authSource=admin&compressors=$COMPRESSOR"
The script is using `SERVERLESS_ATLAS_USER` from environment variables.
1. These lines' purpose is to create a complete `MONGODB_URI` to use in the test run via already existing `CoreTestConfiguration` mechanism.
2. Safe unless the the mongodb uri structure itself changes or `create-instance` starts producing entirely different format. It looks scary because it's bash. This manipulation could be done with python, but I'm afraid that won't help, `build.cake` is also an option, but a less preferable one, so I'd stick to current implementation.
3. It's almost the same code but with injected credentials.

2021-07-21 22:22 UTC, MikalaiMazurenka commented on evergreen/run-serverless-tests.sh
> +export SERVERLESS=true
That's a specification requirement.

2021-07-21 22:22 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +            throw new SkipException("Test skipped because serverless is " + (require ? "required" : "not required"));
Done

2021-07-21 22:22 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/unified-test-format/UnifiedTestFormatValidFailTestRunner.cs
> +    [Trait("Category", "unified-test-format")]
Great catch! A leftover from removed category implementation.

2021-07-21 22:22 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +                    serverVersion < new SemanticVersion(4, 1, 9) && ex.Code == (int)ServerErrorCode.Interrupted ||
This implementation is better as it takes less space with the same effect and readability. As for the comment, it's redundant, since it's not applied to C# driver (as mentioned in the comment itself).

2021-07-21 22:31 UTC, MikalaiMazurenka reviewed
Acknowledging missed comments!

2021-07-21 22:31 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +# 42 minutes is the average for serverless tests (the longest of all, because of the heavy set up task)
> Is is possible to override exec_timeout_secs just for serverless tests?
For example looks like it's done here or here

Missed your comment. Thanks for this example! Looks like it's possible, so I'll try to incorporate this in the next commit.

2021-07-21 22:31 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            return serverless != null;
Sounds like a valid option. I'll need some consideration and will likely incorporate this in the next commit.

2021-07-21 22:31 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
Great catch! The specification does mention these values. I'll add them in the next commit.

2021-07-21 23:06 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
is it mentioned somewhere that it should be `silent`ed? It will hide possible errors that we can see here. Also, at least the patch I checked in java didn't hide this logs

2021-07-21 23:33 UTC, DmitryLukyanov commented on evergreen/run-serverless-tests.sh
> +export MONGODB_URI_WITH_MULTIPLE_MONGOSES="${MONGODB_URI:0:10}${SERVERLESS_ATLAS_USER}:${SERVERLESS_ATLAS_PASSWORD}@${MONGODB_URI:10}/?tls=true&authSource=admin&compressors=$COMPRESSOR"
I would consider a java [way](https://github.com/mongodb/mongo-java-driver/pull/763/files#diff-c1a39fdd9eb0e51d578e3b88ec364894b2c6dbef3bf40630ebdc6b89c44f830aR24)

2021-07-21 23:33 UTC, DmitryLukyanov commented on evergreen/run-serverless-tests.sh
> +export MONGODB_URI_WITH_MULTIPLE_MONGOSES="${MONGODB_URI:0:10}${SERVERLESS_ATLAS_USER}:${SERVERLESS_ATLAS_PASSWORD}@${MONGODB_URI:10}/?tls=true&authSource=admin&compressors=$COMPRESSOR"
also, maybe I'm wrong, but it looks like java uses only single host connection string. Does the spec say anything about it?

2021-07-21 23:38 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          if [ "Windows_NT" = "$OS" ]; then
if it's a windows only fix, then it should be run only there. I think it wasn't added before, because we launched our tests only on windows long time. So, when we added linux/macos support, we just didn't notice this case. It's still a question why it didn't fail all this time, but it's minor

2021-07-22 18:25 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
in other places it's called: `test-#feature#-netstandard21`

2021-07-23 00:07 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-07-23 00:13 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
We always hide all the sensitive output in the logs. I'll check why Java doesn't do that (mind you: their PR is not merged yet)

2021-07-23 00:27 UTC, jyemin commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
It doesn't matter in Java because our whole Evergreen project is private.  I think .NET's is too.

2021-07-23 00:48 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
Yep, they all are private. Then there's no serious reason to keep it silenced.
My opinion is that as far as I'm concerned till this point nothing sensitive has being written into the logs and if we want to make evergreen project public some day, no extra work would be required. Also, if something happens, the build can be rerun with the silence flag lifted, so it is only useful in terms of saving time and catching volatile errors in the scripts.
@jyemin what do you think? Should the restriction be lifted for the advantage of seeing the exact error?

2021-07-23 05:08 UTC, rstam requested changes

2021-07-23 05:08 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +                if (!IsRequirementSatisfied(item.Name, item.Value))
Would this work?

    return requirement.All(item => IsRequirementSatisifed(item.Name, item.value);

or if you change the parameter type of `IsRequirementSatisifed` to `BsonElement`:

    return requirement.All(IsRequirementSatisfied);

Might also be better to rename `requiirement` to `requirements` (plural).

2021-07-23 13:59 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +exec_timeout_secs: 1800 # 30 minutes
let's revert the original one since nothing really changed here

2021-07-23 13:59 UTC, DmitryLukyanov commented on evergreen/run-serverless-tests.sh
> +export MONGODB_URI_WITH_MULTIPLE_MONGOSES="${MONGODB_URI:0:10}${SERVERLESS_ATLAS_USER}:${SERVERLESS_ATLAS_PASSWORD}@${MONGODB_URI:10}/?tls=true&authSource=admin&compressors=$COMPRESSOR"
now, this looks better, thanks

2021-07-23 14:12 UTC, DmitryLukyanov commented on evergreen/run-serverless-tests.sh
> +#   OS                                  Operating system, must be set
> but there is also $OS environment variable which is used in the script but not passed directly

It's passed in other [places](https://github.com/mongodb/mongo-csharp-driver/blob/master/evergreen/evergreen.yml#L301). So even thought there is way(probably) to configure it globally, I would say it's always better to pass it explicitly to see these details without deep investigation.

>(the summary says Supported/used environment variables: which is not the same as passed

Yes, we're not consistent in this behavior (I suppose it was missed during code reviews), but the original intention of this section was to explicitly say which variables are passed and which of them are used as output. I think we should probably define this behavior better, but at the very least let's: 1. mention everything that it's mentioned on the evergreen config side (like SERVERLESS_ATLAS_USER/PASSWORD`) and 2. add `${OS}` as input parameter on evergreen side.

2021-07-23 14:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/transactions/tests/README.rst
> +Mongos Pinning Prose Tests
yes, we have them in `PinnedShardRouterTests`

2021-07-23 14:23 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
I think we pass sensitive data a lot for example here `set-temp-fle-aws-creds.sh` and the only option we have in this case is `set +o xtrace # Disable tracing.` for a particular file. But I think the easiest and probably safest value is what we use here: https://github.com/mongodb/mongo-csharp-driver/blob/master/evergreen/evergreen.yml#L283-L290. This way doesn't print this data to the output.

2021-07-23 14:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
I think we need this logic here (I didn't check, but I think the idea is clear):

            if (definition.TryGetElement("serverless", out var serverless))
            {
                RequireServer.Check().RunOn(new BsonArray(new[] { serverless }));
            }

2021-07-23 14:43 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
most of them. I think a few different ones were missed during code review. No reason to not make unified for new ones

2021-07-23 15:16 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +  - func: delete-serverless-instance
well, this behavior is surprised. The fix that I meant and that I used in LB PR doesn't actually work as expected. I filed a ticket to fix it later. Currently I'm ok with the current way

2021-07-23 18:34 UTC, MikalaiMazurenka reviewed
Ready for review!

2021-07-23 18:34 UTC, MikalaiMazurenka commented on evergreen/run-serverless-tests.sh
> +#   OS                                  Operating system, must be set
Done

2021-07-23 18:34 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +                if (!IsRequirementSatisfied(item.Name, item.Value))
Great point!
Done

2021-07-23 18:34 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
Great point!
Done

2021-07-23 18:36 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
clear naming is this `test-#feature#-netstandard21` . we missed a few cases during previous code reviews, but it's just mistake it doesn't say that we should give up with this until fix that errors

2021-07-23 18:38 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +exec_timeout_secs: 1800 # 30 minutes
it says different, 12 minutes is the longest estimated/validated time for a run (which still might be true if we put aside timeout issues, idk the right value).

2021-07-23 18:46 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +exec_timeout_secs: 1800 # 30 minutes
however I don't rely insist here. It's minor anyway. The only painful part that it will be shown in the history where we didn't change anything here. I will rely on other reviewers here

2021-07-23 18:48 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
missed

2021-07-23 18:49 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        private bool IsAuthenticated() => CoreTestConfiguration.ConnectionString.Username != null;
methods order

2021-07-23 18:49 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
I think `feature`-tests-`target` is clear naming.
So let's put this aside, since anyway I'm not going to rename every task in scope of this PR so even if I rename the tasks I've added, the issue will still persist.

2021-07-23 19:15 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
Unfortunately this didn't work. Reverted to the initial logic.

2021-07-23 19:18 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
It's not about clear naming or no, it's about the used format in this file. I will rely on @BorisDog and you here

2021-07-23 19:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
I wasn't sure that `BsonArray` will parse `BsonElement`, then it should be:

            if (definition.TryGetElement("serverless", out var serverless))
            {
                RequireServer.Check().RunOn(new BsonArray(new[] { new BsonDocument(serverless.Name, serverless.Value)}));
            }

pay attention on the `TryGetElement` method

2021-07-23 20:25 UTC, MikalaiMazurenka commented
Dmitry's suggestion didn't work, the patch build fails:
https://evergreen.mongodb.com/version/60fb1548d6d80a4987269c18
I had to revert the passed environment variables change.

2021-07-23 20:41 UTC, DmitryLukyanov commented
> 
> 
> Dmitry's suggestion didn't work, the patch build fails:
> https://evergreen.mongodb.com/version/60fb1548d6d80a4987269c18
> I had to revert the passed environment variables change.

as I wrote, I wasn't sure in original implementation, since you said that it doesn't work, I needed to apply a small fix

2021-07-23 22:54 UTC, MikalaiMazurenka commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudTestRunner.cs
> +                if (serverless == "forbid")
As I already wrote, `crud-v1` tests will likely become obsolete along with `CrudTestRunner` before any updates are made to the specification, thus I don't see the benefits of updating this code unless necessary.
Current implementation is sufficient and is unlikely to require further changes.

2021-07-28 13:05 UTC, MikalaiMazurenka reviewed
Ready for review

2021-07-28 13:05 UTC, MikalaiMazurenka commented on evergreen/evergreen.yml
> +              bash ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
Removed silent, but left the tracing disabled.

2021-07-28 13:55 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +    - name: serverless-tests-net452
the matrix style has more options and they're not as obvious as the discussed one. I agreed that it should be standardize as well, but it's not the scope of this ticket. You should revert it.

2021-07-28 17:12 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        private bool CanRunOn(BsonDocument requirements)
I would encourage us using expression for short methods as well. On a second thought, maybe we don't need `CanRunOn` method at all anymore. 
Up to you.

2021-07-29 16:34 UTC, BorisDog approved these changes
LGTM

2021-07-29 22:24 UTC, DmitryLukyanov approved these changes
LGTM
we can fix all pending question in next tickets

2021-07-30 13:46 UTC, merged