CSHARP-3733: Don't modify the value of environment variables in test code.
mongodb/mongo-csharp-driver pull request #587
Opened 2021-07-27 15:27 UTC by DmitryLukyanov

2021-08-02 16:30 UTC, rstam requested changes

2021-08-02 16:30 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/LoadBalancingIntergationTests.cs
> +                .ConfigureAndCheck(new LoadBalancedCoreEnvironmentConfiguration())
I don't have time to review more thoroughly but I was expecting the current

    RequireServer.Check()... // checks requirements against default test server (i.e. cluster)

to be enhanced with a new overload like:

    RequireServer.Check(cluster)... // checks requirements against a specified cluster

The sheer volume of changes in this PR makes me think there has to be a better way.

2021-08-02 17:02 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/LoadBalancingIntergationTests.cs
> +                .ConfigureAndCheck(new LoadBalancedCoreEnvironmentConfiguration())
technically, I have almost the same change but which is a bit more complicated since the same logic should be applied for unified test runner.
Current logic:
1. I moved all cluster creating logic from CoreTestConfiguration into a new static helper `ClusterBuilderHelper`.
2. `ClusterTestWrapper` takes an ICluster as ctor argument. Then we can use the provided cluster to call helper logic from CoreTestConfiguration
3. `CoreEnvironmentConfiguration` - a class that is responsible for working with env variables. This is the main target for LB test runner that allows us working with different env variables values
4. `TestClientsProvider` a factory for clients based on `CoreEnvironmentConfiguration`

we can discuss it later

2021-09-14 16:10 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/LoadBalancingIntergationTests.cs
> +                .ConfigureAndCheck(new LoadBalancedCoreEnvironmentConfiguration())
Another option that I just found, we can create a new `DEBUG-like` configuration value, for example "LOCAL" or "UNSAFE" (or whatever) which can be specified only intentionally. I think It will remove any problems here

2021-09-16 18:41 UTC, rstam requested changes
I've spent some more time attempting to review this PR this morning. I don't think this approach is viable.

I think you should try a new approach. 

The key new requirement is that we now want to have more than one `CoreTestConfiguration`. A default one (like now), and a new one for testing against a loadbalancer. And maybe more in the future.

The way to do that should be to change the `CoreTestConfiguration` class from a `static` class to a non-static class that we can have multiple instances of.

A static property called `CoreTestConfiguration.Default` can be used to point to the default instance of the `CoreTestConfiguration` which would correspond to the current static one.

A similar approach could be used for `DriverTestConfiguration`.

And `RequireServer.Check()` should have a new `RequireServer.Check(cluster)` overload that you can use when running tests against the non-default cluster.

2021-09-16 21:47 UTC, DmitryLukyanov commented
discussed offline, for now we didn't find good enough and at the same time a simple enough solution, so moving this PR to hold and related ticket to Open

2022-01-27 23:19 UTC, JamesKovacs commented
Closing this PR based on previous comments.

2022-01-27 23:19 UTC, closed without merging