CSHARP-3716: Enable retryable writes tests on sharded cluster.
mongodb/mongo-csharp-driver pull request #590
Opened 2021-08-02 14:19 UTC by DmitryLukyanov

2021-08-02 18:28 UTC, BorisDog requested changes

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        private static IReadWriteBindingHandle CreateReadWriteBinding(ICluster cluster, ICoreSessionHandle session)
Do we need this overload?

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            string expectedServerKey = allowDataBearingServers ? "Databearing" : "Writable";
nit: `var`

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
>              // wait until the cluster has connected to a writable server
minor: `connected to the expected server`

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            if (Interlocked.CompareExchange(ref hasExpectedServer, 0, 0) == 0)
minor: `if (!SpinWait.SpinUntil(() => Interlocked.CompareExchange(ref hasExpectedServer, 0, 0) != 0, TimeSpan.FromSeconds(30));)` instead of additional check.

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                Interlocked.Exchange(ref hasExpectedServer, anyExpectedServer ? 1 : 0);
General: We can use `Volatile.Read` and `Volatile.Write` instead of `Interlocked.Exchange` and `Interlocked.CompareExchange` for simplicity here.

2021-08-02 18:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/retryable-writes/RetryableWriteTestRunner.cs
> +            if (CoreTestConfiguration.StorageEngine == "mmapv1")
Is it safer to whitelist instead of blacklisting here?

2021-08-05 21:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                Interlocked.Exchange(ref hasExpectedServer, anyExpectedServer ? 1 : 0);
you mean simplification like this:

instead:
>Interlocked.Exchange(ref hasExpectedServer, anyExpectedServer ? 1 : 0)

use this:

>Volatile.Write(ref hasExpectedServer, anyExpectedServer ? 1 : 0)

? :)

2021-08-09 18:25 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                    var fullHosts = shards["host"].AsString; // for example: "shard01/localhost:27018,localhost:27019,localhost:27020
Sorry, not sure I fully understand.
I meant that the example string has an open quotation mark, but not closing one.

2021-08-09 18:25 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                    var hostsChars = fullHosts.SkipWhile(c => c != '/').Skip(1).Cast<char>().ToArray();
Yeah but it might be a bit cleaner/readable, as current parsing is not very trivial.
Alternatively we could do 
`var firstHost = fullHosts.Substring(fullHosts.IndexOf('/') + 1).Split(',')[0] `without direct chars manipulation.
In any case `Cast<char>()` is not needed.

2021-08-09 18:29 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                    var fullHosts = shards["host"].AsString; // for example: "shard01/localhost:27018,localhost:27019,localhost:27020
oh, I misunderstood this, I thought you suggested adding "*" to the end like more servers coming. Done

2021-08-09 18:30 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                    var hostsChars = fullHosts.SkipWhile(c => c != '/').Skip(1).Cast<char>().ToArray();
not sure whether you noticed it, I simplified it to this one: `var hostsChars = fullHosts.Skip(fullHosts.IndexOf('/') + 1).ToArray();`

2021-08-09 18:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                    var hostsChars = fullHosts.SkipWhile(c => c != '/').Skip(1).Cast<char>().ToArray();
done

2021-08-09 19:13 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                Interlocked.Exchange(ref hasExpectedServer, anyExpectedServer ? 1 : 0);
`hasExpectedServer` is set in the eventHandler, so we still need to wait for this value is true.

2021-08-09 19:13 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                Interlocked.Exchange(ref hasExpectedServer, anyExpectedServer ? 1 : 0);
done

2021-08-09 19:30 UTC, BorisDog approved these changes
LGTM

2021-08-10 13:03 UTC, merged