CSHARP2714: Update minimum .NET & .NET Standard version.
mongodb/mongo-csharp-driver pull request #599
Opened 2021-08-09 13:32 UTC by DmitryLukyanov

2021-08-09 13:39 UTC, DmitryLukyanov commented on .gitignore
> +#*.nupkg
temporary change

2021-08-09 13:39 UTC, DmitryLukyanov commented on NuGet.config
> +<?xml version="1.0" encoding="utf-8"?> <configuration>
temporary changes

2021-08-09 13:39 UTC, DmitryLukyanov commented on build.cake
> -            default: throw new ArgumentException($"Unexpected target: \"{target}\".");
reverted because we need to launch tests regardless specified framework. This logic is refactored in the scope of my another ticket

2021-08-09 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/Sspi/SspiHandle.cs
>          [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
this attribute is obsolete, but I didn't want to look deeper at this in the scope of this ticket

2021-08-09 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="9.9.9" />
temporary change

2021-08-09 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDB.Driver.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="9.9.9" />
temporary change

2021-08-09 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Shared/IncrementalMD5.cs
> +    internal class IncrementalMD5Imp : IncrementalMD5
in theory this whole class can be removed, but in this case we will need to specify using MD5 each time when we use this logic and will need to make more changes. So left it as is

2021-08-09 13:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Legacy/Builders/BuilderBase.cs
> +#if NET472
we don't need this attribute, but since it's legacy I think we don't need to change it

2021-08-09 19:27 UTC, JamesKovacs requested changes
Overall LGTM. A few places to clean up as noted. Also missed a few references to `net452`:

- tests/MongoDB.Driver.Legacy.VB.Tests/MongoDB.Driver.Legacy.VB.Tests.vbproj
- tests/MongoDB.Driver.Legacy.VB.Tests/packages.config
- Docs/Api/LibMongocryptDocs.shfbproj
- Docs/Api/CSharpDriverDocs.shfbproj
- Docs/reference/content/getting_started/installation.md

Note that `installation.md` refers to both `net452` and `netstandard1.5`.

2021-08-09 19:27 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AuthenticationTests.cs
>          // .NET Standard
`SaslPrepHelper` only skipped normalization on netstandard1.5. We should run these tests on netstandard2.0 and 2.1. Thus this `#if NET472` should be removed.

2021-08-09 23:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Legacy/Builders/BuilderBase.cs
> +#if NET472
done

2021-08-09 23:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AuthenticationTests.cs
>          // .NET Standard
done

2021-08-09 23:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/NativeLibraryLoader/LibraryLoader.cs
>              if (!is64Bit)
done

2021-08-10 00:01 UTC, JamesKovacs requested changes
Just some dead code to remove in `BsonClassMap` and then you're all set.

2021-08-10 17:57 UTC, JamesKovacs approved these changes
LGTM

2021-08-25 01:43 UTC, merged