CSHARP-3789: Add BSON Binary subtype 7
mongodb/mongo-csharp-driver pull request #625
Opened 2021-09-13 20:39 UTC by rstam

2021-09-13 20:40 UTC, rstam commented
Evergreen patch build:

https://evergreen.mongodb.com/patches/project/dot-net-driver

2021-09-14 16:49 UTC, jyemin approved these changes
Was BSON Binary subtype 6 from CSFLE, or is it related to subtype 7?

2021-09-16 16:14 UTC, jyemin requested changes

2021-09-16 16:14 UTC, jyemin commented on src/MongoDB.Bson/ObjectModel/BsonBinarySubType.cs
> +        /// <summary>
This actually looks like it got mixed up.  The comments don't match the definitions.

2021-09-16 17:10 UTC, closed without merging