CSHARP-3225: Window Functions.
mongodb/mongo-csharp-driver pull request #630
Opened 2021-09-28 00:05 UTC by DmitryLukyanov

2021-09-28 00:09 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Linq/Translators/AggregateSetWindowFieldsTranslator.cs
> +                    if (outputWithoutWindow.TryGetValue(outputOptionFieldName, out var outputWindow) && outputWindow is BsonDocument outputWindowDocument)
the main place where we enrich output fields by output window options if present

2021-09-28 20:56 UTC, DmitryLukyanov commented
ready for review

2021-09-29 01:48 UTC, rstam reviewed
Questions about whether it's appropriate to use a `ProjectionDefinition` as the argument to one of the overloads of `SetWindowFields`.

2021-09-29 01:48 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluent.cs
> +        IAggregateFluent<TNewResult> SetWindowFields<TNewResult>(ProjectionDefinition<TResult, TNewResult> setWindowFieldsDefinition);
I don't understand how a `ProjectionDefinition` can be the argument to `SetWindowFields`.

It doesn't look at all like the arguments to the `$setWindowFields` stage.

2021-09-29 01:48 UTC, rstam commented on src/MongoDB.Driver/PipelineDefinitionBuilder.cs
> +            ProjectionDefinition<TIntermediate, TOutput> setWindowFieldsDefinition)
I don't understand how a `ProjectionDefinition` can be the argument to `SetWindowFields`.

It doesn't look at all like the arguments to the `$setWindowFields stage`.

2021-09-29 01:48 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
I don't understand how a `ProjectionDefinition` can be the argument to `SetWindowFields`.

It doesn't look at all like the arguments to the `$setWindowFields` stage.

2021-09-29 01:56 UTC, rstam requested changes

2021-09-29 01:56 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
I think this functionality is totally unnecessary.

If you are going to specify the entire SetWindowFields arguments as a single BsonDocument then what you actually should do is include `$setWindowFields` in the BsonDocument and use:

    .AppendStage(setWindowFieldsStage)

2021-09-29 09:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
$setWindowFields works similar to $group [where ](https://github.com/mongodb/mongo-csharp-driver/blob/512005dc97c74722bd83c59e28c5b1edff2e5272/src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs#L677) we use `ProjectionDefinition`, I've implemented this stage taking $group as example.

2021-09-29 09:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
we can say the same for any stage we have :) so at the same time we can say that no reasons to not have this functionality :)

2021-09-29 17:33 UTC, rstam requested changes

2021-09-29 17:33 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
A `ProjectionDefinition` defines the shape of the *projected* RESULT.

It is not intended to carry the arguments to a stage like `$setWindowFields`. So argument values like `partitionBy` and `sortBy` do not belong in a `ProjectionDefinition`.

I suppose a `ProjectionDefinition` *could* be used for `output` argument to the `$setWindowsField`, althought it wouldn't be a standard projection because it is limited to "window operators" along with `window` arguments to the "window operator".

2021-09-29 17:38 UTC, rstam requested changes

2021-09-29 17:38 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
I'm not objecting to having helpers for stages.

I'm just objecting that in this case we're essentially providing the *whole* stage as a BsonDocument so this helper is doing nothing useful.

An application should just use `AppendStage` if they're not going to use a type safe helper.

2021-09-29 17:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
It's used for `group Id`, in Group stage [here](https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs#L717) through `GroupExpressionProjection`. 
I think the whole description of this definition is: it's used to configure projection and requires input arguments to setup ait. For example like `groupId` in $group stage and `partitionBy` + `sortBy` in `setWindowFields`

2021-09-29 17:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
I just made a whole copy of how it's implemented in $group stage where we have exactly the same structure

2021-09-29 17:49 UTC, rstam requested changes

2021-09-29 17:49 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
In the `Group` and `Projection` helpers the `ProjectionDefinition` defines the RESULT.

If we use a `ProjectionDefinition` anywhere new it should ALSO define the RESULT.

It should not be used to carry arguments like `partitionBy` and `sortByt` that are NOT part of the RESULT.

2021-09-29 17:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
I understand that you made a copy of Group but I don't think that is correct.

2021-09-29 17:51 UTC, DmitryLukyanov commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            ProjectionDefinition<TInput, TOutput> setWindowFieldsProjection)
>In the Group and Projection helpers the ProjectionDefinition defines the RESULT.

not only, it's used to define `group Id` as well

2021-09-29 17:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentSetWindowFieldsTests.cs
> +                .SetWindowFields<CakeSales>(setWindowFieldsStage)
I kind of agreed about `sortBy`, originally i implemented it as a different argument, but then I decided that it's just an option that affects an output result almost the same as `partitionBy`, this is why I made this logic in the same way as `paritionBy`

2021-09-29 18:00 UTC, rstam requested changes

2021-09-29 23:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                partitionBy: new ExpressionAggregateExpressionDefinition<TInput, TPartitionBy>(partitionBy, ExpressionTranslationOptions.Default),
I didn't really understand what `ExpressionTranslationOptions` does, but it looks not required for the current changes, @rstam do you have any ideas?

2021-09-29 23:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            AggregateExpressionDefinition<TInput, TPartitionBy> partitionBy,
The main reason why I implemented the stage constructing not here, but on translator reason was that FieldExpression cannot handle cases like: `e => e.OrderDate.Year` correctly, so I needed to have a power of linq translator for that, but now I noticed that we already have a definition for this, so I just reused it

2021-09-29 23:58 UTC, DmitryLukyanov commented
ready for review

2021-10-05 21:43 UTC, rstam commented
I don't think we should adopt this work as-is. In these comments I'm going to focus mainly on the user level API.

The correct API to match the stage definition should be:

    SetWindowFields(
        AggregateExpressionDefinition partitionBy,
        SortDefinition sortBy,
        ProjectionDefinition output)

With possible convenience overloads:

    SetWindowFields(partitionBy, output) => SetWindowFields(partitionBy, sortBy: null, output)
    SetWindowFields(output) => SetWindowFields(partitionBy: null, sortBy: null, output)

Since partitionBy and sortBy are sometimes optional.

The problem with the above is that it doesn't provide any way to provide the window options for each output field.

You have worked around this by using an optional table of windowOptions:

    SetWindowFields(
        AggregateExpressionDefinition partitionBy,
        SortDefinition sortBy,
        ProjectionDefinition output,
        params AggregateOutputWindowOptionsBase[] windowOptions)

But that's a pretty awkward way of specifying window options, where each window option is matched by name with some field in the output projection.

While that's an interesting workaround, I don't think it's the API we want to provide.

We have discussed that in LINQ3 we could provide the window options using custom extension methods for the window operators. I say we want and do that.

2021-10-05 21:44 UTC, rstam requested changes
See previous comment.

2021-10-05 21:53 UTC, DmitryLukyanov commented
>You have worked around this by using an optional table of windowOptions:
>
>SetWindowFields(
>    AggregateExpressionDefinition partitionBy,
>    SortDefinition sortBy,
>    ProjectionDefinition output,
>    params AggregateOutputWindowOptionsBase[] windowOptions)

>But that's a pretty awkward way of specifying window options, where each window option is matched by name with some field in >the output projection.

we've already discussed this in the slack, there is no other way in LINQ2, I don't think that it's a bad approach (even though the suggested LINQ3 approach is definitely better), since we just provide a way to add additional configuration via only possible approach. I think it's up to @jyemin whether we want to add this in LINQ2 or no.

2022-01-27 23:17 UTC, JamesKovacs commented
Closing this PR as we decided to pursue a different public API for this feature.

2022-01-27 23:17 UTC, closed without merging