CSHARP-3940: Support BsonDocument and BsonArray in LINQ queries.
mongodb/mongo-csharp-driver pull request #672
Opened 2021-11-03 04:36 UTC by rstam

2021-11-03 04:37 UTC, rstam commented
Evergreen patch build:

https://evergreen.mongodb.com/version/618211c73066156ffc831bd7

2021-11-03 04:38 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3940Tests.cs
> +    public class CSharp3940Tests
There are probably more tests here than necessary but I wanted to make sure we had good coverage of BsonDocument and BsonArray, both nested and in combination.

2021-11-04 17:15 UTC, JamesKovacs requested changes
Nice and clean implementation. Only a question about whether we should add `method.DeclaringType == typeof(BsonValue)` in two places.

2021-11-04 17:15 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (!method.IsStatic && method.Name == "get_Item")
Should we also include `method.DeclaringType == typeof(BsonValue)`? Is there a reason not to?

2021-11-04 17:15 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (!method.IsStatic && method.Name == "get_Item")
Same here. `method.DeclaringType == typeof(BsonValue)`

2021-11-04 17:15 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +
There is some duplication of logic especially between the first and third `if` blocks. They only differ in the serializer chosen. That said, I like that each case is handled cleanly and clearly by its own block. If we have to support more methods in this translator, we should consider refactoring out the common code, but I'm ok with the small amount of duplication for now.

2021-11-06 17:39 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (!method.IsStatic && method.Name == "get_Item")
Better yet:

    if (method.Is(BsonValueMethod.GetItemWithInt))

2021-11-06 17:39 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (!method.IsStatic && method.Name == "get_Item")
Done

2021-11-06 17:39 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (!method.IsStatic && method.Name == "get_Item")
Done

2021-11-06 17:41 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (IsBsonValueGetItemMethodWithIntIndex(expression, out sourceExpression, out indexExpression))
I moved these two if statements up here so that we check the more specific conditions first.

In this case it didn't really matter but it's a good idea anyway.

2021-11-08 22:54 UTC, JamesKovacs requested changes
Re-arranging the `Translate` method introduced some compiler errors.

2021-11-08 22:54 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (IsBsonValueGetItemMethodWithIntIndex(expression, out sourceExpression, out indexExpression))
Re-arranging the statements has introduced compile errors. Rather than using `out var`, I would suggest declaring the required variables at the top of the method.

2021-11-08 23:19 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (IsBsonValueGetItemMethodWithIntIndex(expression, out sourceExpression, out indexExpression))
Well that's embarassing... I just assumed that changing the order wouldn't affect anything and neglected to verify.

2021-11-08 23:19 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/GetItemMethodToAggregationExpressionTranslator.cs
> +            if (IsBsonValueGetItemMethodWithIntIndex(expression, out sourceExpression, out indexExpression))
Done

2021-11-09 00:09 UTC, JamesKovacs approved these changes
LGTM

2021-11-09 01:14 UTC, closed without merging