CSHARP-3936: Support KMIP in client side field level encryption.
mongodb/mongo-csharp-driver pull request #675
Opened 2021-11-09 20:35 UTC by DmitryLukyanov

2021-11-09 20:54 UTC, DmitryLukyanov commented on .gitignore
> +#*.nupkg
will be reverted

2021-11-09 20:54 UTC, DmitryLukyanov commented on NuGet.config
> +	<activePackageSource>
will be reverted

2021-11-09 20:54 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          ALLOW_NOSSL=true \
for kmip we need to pass client certificate regardless ssl options

2021-11-09 20:54 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> -    - name: test-kms-tls-expired-certificate-netstandard21
new tests cover this logic

2021-11-09 20:54 UTC, DmitryLukyanov commented on evergreen/get-python-path.sh
> +if [ -z "$Venv" ]; then
a new script that provides python path

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="9.9.93" />
the final version will be `1.3.0`

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +                sb.AppendFormat("TlsOptions: {0}", _tlsOptions.Select(t => new BsonDocument(t.Key, "<hidden>")).ToJson(jsonWriterSettings));
I'm open to suggestions here

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/KmsProvidersHelper.cs
> +                if (kmsProviderTlsSettingValue.ServerCertificateValidationCallback != null) // tlsInsecure
the spec says:

    Drivers SHOULD raise an error if insecure TLS options are set. The error MUST contain the message "Insecure TLS options prohibited". This includes options equivalent to the following URI options:

    tlsInsecure
    tlsAllowInvalidCertificates
    tlsAllowInvalidHostnames
    tlsDisableOCSPEndpointCheck
    tlsDisableCertificateRevocationCheck

In c# we supports only:

* tlsInsecure => via allowing anything in ServerCertificateValidationCallback. Since we don't have control over what user can place inside, I think it's better to not allow specifying this callback at all
* tlsDisableCertificateRevocationCheck => the default value in c# driver is tlsDisableCertificateRevocationCheck=true, so I think we should avoid this validation
* I think it probably makes sense to disable configuring SslSettings.ClientCertificateSelectionCallback even thought it's not required directly, thoughts?

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/KmsProvidersHelper.cs
> +                if (kmsProviderTlsSettingValue.ServerCertificateValidationCallback != null) // tlsInsecure
Also, the spec has this requirement:

    Drivers MUST raise an error if the TLS options are set to disable TLS. The error MUST contain the message "TLS is required".

and `SslSettings.EnabledSslProtocols` has an option SslProtocols.None, but based on this doc https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=net-5.0#fields it's still `Tls` option, so I didn't disable it

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +            var sslStreamFactory = new SslStreamFactory(tlsStreamSettings, _networkStreamFactory);
reuse already existed logic to work with SslStream

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +        private class NetworkStreamFactory : IStreamFactory
in theory, this can be replaced on [TcpStreamFactory](https://github.com/mongodb/mongo-csharp-driver/blob/4183a08781e1da461da73a9c7056c6518a143a2d/src/MongoDB.Driver.Core/Core/Connections/TcpStreamFactory.cs#L32), but that class has much more complicated logic that we used here and this logic wasn't required in this ticket, so I just created a simple nested implementation

2021-11-09 20:54 UTC, DmitryLukyanov commented on src/MongoDB.Driver/SslSettings.cs
> +        internal SslStreamSettings ToSslStreamSettings()
no Core/Driver issues anymore 👍

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +    [DebuggerStepThrough]
This logic is described in CSHARP-3904, but there is one case that I didn't investigate/implement in this PR, so probably I won't close 3904 but just will add a note in the jira ticket

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +                //if (Aggregator.HasExceptions && testLoggable != null)
will be reverted

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                RequireEnvironment.Check().EnvironmentVariable("KMS_MOCK_SERVERS_ENABLED");
skip because kmip tests require kms mock servers

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +    [Trait("Category", "FLE")]
some of tests here still fail from time to time, investigating

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            void AssertException(Exception exception)
asserts exception based on OS, TF, Certificate configuration, KMS provider

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                clientEncryptionOptions._tlsOptions(tlsOptions); // avoid validation on serverCertificateValidationCallback
I use reflection, because settings serverCertificateValidationCallback is disabled via public API

2021-11-09 20:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            [Values("gcp")] string kmsProvider, // the rest kms providers are supported on all supported TFs
this test is not longer complicated because most of the cases were gone for now

2021-11-09 20:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        //ko.Add("endpoint", "localhost:5698");
missed this, will fix in the next commit

2021-11-10 03:11 UTC, DmitryLukyanov commented
Ready for review, the only pending question is related to failing tests with unexpected exception:
>Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

like [here]( https://evergreen.mongodb.com/task_log_raw/dot_net_driver_secure_tests__version~5.0_os~windows_64_topology~standalone_auth~auth_ssl~ssl_test_net472_patch_60ad0c84b164c0648eabe7dea72aa6d94f8289aa_618b3300c9ec4424bc57eb7d_21_11_10_02_49_12/0?type=T#L1661). It looks like it's related to mock server behavior, I asked Kevin maybe he faced with this, so will reach our him tommorow

2021-11-10 03:13 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +        [InlineData("kmip", null, null, "$HostNotFound$")]
1. I don't use enum itself, because it breaks a bit Test Explorer on .net framework, due some serialization issue
2. I use a code instead a message, because the message is platform dependent in some cases

2021-11-10 22:20 UTC, JamesKovacs requested changes
See comments inline to discuss. Main point of discussion is around testing strategy. A few auxiliary questions about API and impl.

2021-11-10 22:20 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                            kmsOptions.Add("endpoint", "localhost:5698"); // mock server
Should this be hard-coded or read in from an environment variable?

2021-11-10 22:20 UTC, JamesKovacs commented on evergreen/evergreen.yml
>            vars:
How should we run KMIP/KMS-related tests? Should they be included with all `test*` variants as done here? Or should they mimic the OCSP, CSFLE, GSSAPI, and other specialized tests and be their own variant(s)?

2021-11-10 22:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +            Optional<IReadOnlyDictionary<string, SslSettings>> tlsOptions = default)
I'm not wild about this API where `AutoEncryptionOptions` includes multiple separate dictionaries (`kmsProviders`, `extraOptions`, and `tlsOptions`), which should all have the same keys. This is probably not something we can change now unfortunately. Do we have code and tests to verify the expected keys are present in each?

2021-11-11 15:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/KmsProvidersHelper.cs
> +                if (kmsProviderTlsSettingValue.ServerCertificateValidationCallback != null) // tlsInsecure
The doc says:

>SslProtocols.None  => Allows the operating system to choose the best protocol to use, and to block protocols that are not secure. 

I didn't 100% understand what this means (but I inclined that TLS is presented in any case), but you say that it means that TLS can be disabled in this case? If so, I will change it in the next commit

2021-11-11 15:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +        private class NetworkStreamFactory : IStreamFactory
>Are we sure we don't need the extra logic in TcpStreamFactory for proper operation on .NET Core?

we don't have evidences for this yet. Also TcpStreamFactory sets some options like ReadTimeout that is used in the driver, I doubt any driver set it here, so I incline to leave it as is until we have evidence that this is required logic, but I' don't insist :)

2021-11-11 15:41 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> +ALLOW_NOSSL=${ALLOW_NOSSL:-nil}
this option allows skipping the validation where we add the certificate to trusted storage only if ${SSL}="ssl", so this describes exactly what happens. I don't mind to change it, but `REQUIRE_CERTS` is not what this variable have control about. What about: `IGNORE_SSL_CHECK`?

2021-11-11 15:41 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
>            vars:
I will get back to this question

2021-11-11 20:32 UTC, JamesKovacs commented on evergreen/add-certs-if-needed.sh
> +ALLOW_NOSSL=${ALLOW_NOSSL:-nil}
Given that there is no harm in adding certs even if they're unused, why don't we simplify the script to always add the certs and remove the need for this option?

2021-11-11 20:34 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +                  Ensure.IsNotNull(Ensure.IsNotNull(autoEncryptionOptions, nameof(autoEncryptionOptions)).TlsOptions, nameof(autoEncryptionOptions.TlsOptions)))
Fair enough. We can leave it as-is.

2021-11-11 20:35 UTC, DmitryLukyanov commented on evergreen/add-certs-if-needed.sh
> +ALLOW_NOSSL=${ALLOW_NOSSL:-nil}
this file is used in other logic like in OCSP and other, I would not want to change anything there

2021-11-11 20:37 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +            Optional<IReadOnlyDictionary<string, SslSettings>> tlsOptions = default)
If it is defined in the spec, then we should keep the same API - even if I don't particularly like it as a design choice. :)

2021-11-11 20:41 UTC, JamesKovacs requested changes
Some outstanding comments that need to be addressed. Please let me know if you have any questions or would like to discuss.

2021-11-11 20:41 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +                sb.AppendFormat("TlsOptions: {0}, ", _tlsOptions.ToJson(jsonWriterSettings));
I think hiding the `tlsOptions` - which could contain sensitive data - other than the key name is the correct thing to do even if it makes debugging more difficult. Why did you remove the `<hidden>` replacement code?

2021-11-11 20:51 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +                sb.AppendFormat("TlsOptions: {0}, ", _tlsOptions.ToJson(jsonWriterSettings));
I described it here: https://github.com/mongodb/mongo-csharp-driver/pull/675#discussion_r746986108 so, to simplify logic, but I see that it gives some problem with serialization IntPtr like:

>MongoDB.Bson.BsonSerializationException : No serializer found for type System.IntPtr.

EG: https://evergreen.mongodb.com/build/dot_net_driver_kms_tls_mocked_tests_windows__version~5.0_os~windows_64_topology~standalone_ssl~nossl_patch_60ad0c84b164c0648eabe7dea72aa6d94f8289aa_618d6e7de3c33142e63b40c5_21_11_11_19_27_33
I will probably revert it

2021-11-11 23:22 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +                sb.AppendFormat("TlsOptions: {0}, ", _tlsOptions.ToJson(jsonWriterSettings));
`SslStreamSettings` has 5 properties:
`CheckCertificateRevocation` - might be useful but currently only true is allowed for KMIP/KMS
`ClientCertificates` - we don't want to expose these
`ClientCertificateSelectionCallback` - delegate; only useful thing to show would be whether it is set or not
`EnabledSslProtocols` - might be useful to show these but we could potentially leak security information about whether support for older (and less secure) protocols is enabled 
`ServerCertificateValidationCallback` - delegate; only useful thing to show would be whether it is set or not

Of the 5 properties, they either have known values for KMIP/KMS or would leak security information. So I think `<hidden>` is a better choice rather than risking leaking sensitive information.

2021-11-12 00:17 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
>            vars:
changed

2021-11-12 00:17 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +                sb.AppendFormat("TlsOptions: {0}, ", _tlsOptions.ToJson(jsonWriterSettings));
reverted

2021-11-17 23:50 UTC, JamesKovacs approved these changes
LGTM

2021-11-17 23:50 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/KmsProvidersHelper.cs
> +                if (kmsProviderTlsSettingValue.ServerCertificateValidationCallback != null) // tlsInsecure
Your interpretation is correct. `SslProtocols.None` is not what I expected and neither is `SslProtocols.Default`.

2021-11-17 23:50 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +        private class NetworkStreamFactory : IStreamFactory
Let's leave it as it is here and revisit later if necessary.

2021-11-17 23:50 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +    [DebuggerStepThrough]
I'm good with implementing CSHARP-3904 immediately. I just don't want to have `[DebuggerStepThrough]` changes mixed into the KMIP changes.

2021-11-18 22:39 UTC, DmitryLukyanov commented on .gitignore
> +#*.nupkg
done

2021-11-18 22:39 UTC, DmitryLukyanov commented on NuGet.config
> +	<activePackageSource>
done

2021-11-18 22:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <PackageReference Include="MongoDB.Libmongocrypt" Version="9.9.93" />
done

2021-11-18 22:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +    [DebuggerStepThrough]
done

2021-11-18 22:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +                //if (Aggregator.HasExceptions && testLoggable != null)
done

2021-11-18 22:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            evergreen/cleanup-test-resources.sh
done

2021-11-18 22:39 UTC, DmitryLukyanov commented
EG: https://evergreen.mongodb.com/version/6196d5d82fbabe028bed4f63

2021-11-18 23:26 UTC, JamesKovacs approved these changes
LGTM

2021-11-18 23:49 UTC, merged