CSHARP-3952: Make maxConnecting configurable.
mongodb/mongo-csharp-driver pull request #678
Opened 2021-11-12 17:35 UTC by DmitryLukyanov

2021-11-12 18:19 UTC, BorisDog requested changes
I think we need to add `maxConnecting` to `ConnectionString` as well.

2021-11-12 18:19 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <param name="maxConnecting">The max connecting.</param>
nit: 'Maximum concurrent connections establishments.' or similar

2021-11-12 18:19 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        public void constructor_should_throw_when_maxConnecting_is_negative()
Let's validate `0` as well.

2021-11-12 18:19 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            var oldMaxConnecting = 1;
nit: my personal preference is to use `const` if possible, not critical though.

2021-11-12 18:22 UTC, JamesKovacs requested changes
These changes make `maxConnecting` configurable via code as follows:

```
var settings = new MongoClientSettings
{
    ClusterConfigurator = cb => cb.ConfigureConnectionPool(x => x.With(maxConnecting: 3))
};
```

I think this is sufficient for code-based configuration.

The URI spec has been updated (currently in PR) to include a `maxConnecting` URI option. Will you be adding `maxConnecting` URI parsing?

2021-11-12 21:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionPoolSettings.cs
> +        /// <param name="maxConnecting">The max connecting.</param>
we usually don't really worry about such XML comments, I don't really agree with this decision, but I would follow to what we usually do

2021-11-12 21:21 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        public void constructor_should_throw_when_maxConnecting_is_negative()
done

2021-11-12 21:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            var oldMaxConnecting = 1;
it's more letters :) I changed it, but mostly I would not worry about it

2021-11-12 21:27 UTC, DmitryLukyanov commented
This PR is a good example to spend few seconds more on even something that you think really simple. Originally I missed that we should not only make maxconnecting option public, but we also should add these values to the whole classes we have :( 

>I think this is sufficient for code-based configuration.

I would say it's better to have all options in the uri spec added to the all user-faced classes we have like MongoClientSettings, MongoUrl and etc.

>The URI spec has been updated (currently in PR) to include a maxConnecting URI option. Will you be adding maxConnecting URI parsing?

done

2021-11-12 23:17 UTC, JamesKovacs requested changes
Overall looking good. Just need to improve the XML comments on the new property and fix up some tests.

2021-11-12 23:17 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +        /// </summary>
Use description from spec.

2021-11-12 23:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            subject.MaxConnecting.Should().Be(__defaults.MaxConnecting);
We shouldn't be testing `maxConnecting` in the context of another property like `maintenanceInterval`. This applies to all assertions on `maxConnecting` in the below tests as well, except for `With_maxConnecting_should_return_expected_result` which specifically tests `maxConnecting` in the context of `With`.

2021-11-12 23:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        public void constructor_should_throw_when_maxConnecting_is_negative([Values(0, -1)] int invalidMaxConnecting)
Change the test name to `_is_invalid` because zero isn't negative. :)

2021-11-12 23:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        }
These additional assertions do not belong in this test. A test should (ideally) have one logical assertion.

2021-11-12 23:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +
We should have a similar ctor test that verifies a few valid `maxConnecting` values.

2021-11-15 18:18 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +        /// </summary>
discussed offline, left: `Gets the maximum number of connections a pool may be establishing concurrently. Defaults to 2.`

2021-11-15 18:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        public void constructor_should_throw_when_maxConnecting_is_negative([Values(0, -1)] int invalidMaxConnecting)
done

2021-11-15 18:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +
done

2021-11-15 18:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            subject.MaxConnecting.Should().Be(__defaults.MaxConnecting);
we don't test maxConnecting itself here, we test that the only assigned(changed) option here is maintenanceInterval (if maintenanceInterval has been passed as income parameter), the rest options are unchanged (default)

2021-11-15 18:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +        }
described above, 
>A test should (ideally) have one logical assertion.

even though it makes sense, it also makes sense to know not only that we have changed what we wanted to change, but that we didn't change that we didn't want to do

2021-11-15 18:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +            if (!condition(value))
we don't have this condition in all cases on this level, but the new json tests require it

2021-11-17 19:24 UTC, BorisDog approved these changes
LGTM.
Just needs a full EG, due to new spec tests.

2021-11-18 00:27 UTC, JamesKovacs requested changes
Only outstanding issue is the over-specified tests. If we are testing that setting `MaxConnecting` is successful, we don't need to verify that the other properties haven't been altered. Same with the other properties. If there are interrelationships between properties, then we would have tests to validate those interrelations.

2021-11-18 00:27 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            subject.MaxConnecting.Should().Be(__defaults.MaxConnecting);
But we shouldn't be asserting on properties that we aren't testing. We should only assert on `subject.MaintenanceInterval` if that's the purpose of this test. Otherwise the test is over-specified and more fragile than it need be.

2021-11-18 00:27 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionPoolSettingsTests.cs
> +            subject.MaintenanceInterval.Should().Be(__defaults.MaintenanceInterval);
We shouldn't be asserting the value of `MaintenanceInterval` here for the same reason.

2021-11-18 00:37 UTC, JamesKovacs approved these changes
Discussed over-specified tests via Slack. Given that the existing tests were like this, I can live with the fact that the tests are over-specified and revisit in the future if needed.

LGTM.

2021-11-18 18:23 UTC, merged