CSHARP-2088: Publish PDBs and sources on symbolsource.
mongodb/mongo-csharp-driver pull request #694
Opened 2021-11-25 02:08 UTC by DmitryLukyanov

Some notes:
1. Currently I temporally switched back to myget for tests reasons, probably we will know that it works with nuget only during next release.
2. In the scope of this ticket I also fixed nuget package warnings from [here](https://jira.mongodb.org/browse/CSHARP-3802) and [here](https://jira.mongodb.org/browse/CSHARP-3047). Steps that I took more or less taken from [here](https://lurumad.github.io/using-source-link-in-net-projects-and-how-to-configure-visual-studio-to-use-it).
After this PR, the nuget package manager should look like this:
![image](https://user-images.githubusercontent.com/44870738/143359998-79a5be41-e55b-4284-9607-04cd334472d5.png)

NOTE: it looks like myget doesn't work correctly with the above package validation, all nuget packages that I checked (including external) were red. Probably it's only myget issue. Will check it after release :) 

3. I needed to update cake to 1.3.0, to be able to configure `ContinuousIntegration` field that required to make package deterministic. Some article about it [here](https://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html).
4. What should be checked after package creating:
![image](https://user-images.githubusercontent.com/44870738/143364564-1dbecaf3-a943-4180-b9ac-e19f1823cc52.png)
where `Url` means the git repository that will be used to download source file and `Commit` a particular commit (make sure that it's pushed).
5. How it should be configured:
5.1. While we use myget in testing, this source `https://www.myget.org/F/mongodb/api/v3/index.json` should be added to nuget package manager.
5.2. Consume the test package in the consumer application
5.3. Make sure that VS has the same configuration:
![image](https://user-images.githubusercontent.com/44870738/143364964-807f4404-89ff-41f6-a176-d3263ec0be81.png)
5.4. Make sure that myget symbol server `https://www.myget.org/F/mongodb/api/v2/symbolpackage` is added to VS here:
![image](https://user-images.githubusercontent.com/44870738/143365111-0fc688af-f4f1-48eb-8498-49943fa1736c.png)
NOTE: I think when we will use nuget.org symbol server, it should be enough just to enable default nuget symbol server

2021-11-25 22:11 UTC, JamesKovacs approved these changes
LGTM! Very excited to see this feature enabled.

```
dotnet new console
dotnet add package MongoDB.Driver --version 2.14.0-csharp2088-4-1 --source https://www.myget.org/F/mongodb/api/v3/index.json
```

I configured JetBrains Rider to use the following Symbol Server as documented by myget.org:

`https://www.myget.org/F/mongodb/api/v2/symbolpackage/`

I then created a simple MongoDB program and was able to successfully debug into `db.GetCollection<BsonDocument>("coll")`! I confirmed that I had debugged into our actual sources by verifying that source comments were present along with our copyright. When working with decompiled sources, source comments aren't present (for obvious reasons) and rather than the copyright there is a "decompiled by" comment at the top of the file.

I had some initial fumbling around with configuration. Without explicitly adding the Symbol Server, you still get decompiled sources. So we will have to add some documentation on how to enable source debugging with our driver.

2021-11-25 22:16 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <!--obj-->
it says that `EmbedUntrackedSources` is responsible for `obj` folder

2021-11-25 22:17 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <EmbedUntrackedSources>true</EmbedUntrackedSources>
it's required to have files in `obj` folder available in debugging, I need to refresh my memory to recall what will happen if we remove it

2021-11-25 22:25 UTC, JamesKovacs requested changes
Meant to select "request changes" on my last review. Minor questions/suggestions only. Overall it works as expected.

2021-12-04 00:25 UTC, DmitryLukyanov commented on build.cake
> +public class BuildData
done

2021-12-06 16:13 UTC, JamesKovacs approved these changes
LGTM

2021-12-06 16:18 UTC, BorisDog requested changes
Look great overall. 
Confirmed that it works, exited to see this great enhancement for our debugging experience!

2021-12-06 16:18 UTC, BorisDog commented on build.cake
> +        };
Good idea!

2021-12-06 16:18 UTC, BorisDog commented on build.cake
> +            settings.MSBuildSettings.SetContinuousIntegrationBuild(continuousIntegrationBuild: true);
Is it possible to always use `SetContinuousIntegrationBuild` and skip having `IsReleaseMode` )as we don't use cake for debug/dev env.)?

2021-12-06 16:18 UTC, BorisDog commented on build.cake
> +    .Does<BuildConfig >((buildConfig) =>
nit: extra space: `<BuildConfig >`

2021-12-06 16:18 UTC, BorisDog commented on build.cake
> +Setup<BuildConfig >(
nit: extra space

2021-12-12 18:45 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <!--obj-->
There are few reasons:
1. Without this option, the package description triggers the warning:
![image](https://user-images.githubusercontent.com/44870738/145725108-bc9a1b4e-0fe8-4f01-afbb-427f4ca34622.png)

2021-12-12 18:45 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <!--obj-->
2. Based on this [article](https://mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking) and this [issue](https://mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking) it looks like at least it affects `AssemblyInfo.cs` which is placed in `obj\Release\{Framework}\`. I didn't check further, but in this file we may apply global assembly attributes that could be missed? Anyhow it looks like this option is always recommended. 
3. Also some [article](https://blog.actorsfit.in/a?ID=00001-4c00a300-f866-4bea-8a00-34fa075d39ed) that recommends setting it.

2021-12-13 16:32 UTC, JamesKovacs commented on build.cake
> +            settings.MSBuildSettings.SetContinuousIntegrationBuild(continuousIntegrationBuild: true);
We only publish release mode assemblies. If you're in debug mode for the driver, you're debugging through your local sources. You don't need to reach out to a source server to download a nuget package containing PDB files because you've got the PDB files on your local file system already. We should leave this check in place IMHO.

2021-12-13 20:25 UTC, JamesKovacs commented on src/MongoDB.Bson/MongoDB.Bson.csproj
> +    <EmbedUntrackedSources>true</EmbedUntrackedSources>
Discussed in Slack and decided that safer to not embed untracked files by default. We can revisit this decision if users report debugging problems.

2021-12-13 21:42 UTC, merged