CSHARP-3950: Get all tests to pass against a cluster with a single mongos and default configurations.
mongodb/mongo-csharp-driver pull request #695
Opened 2021-11-25 19:58 UTC by DmitryLukyanov

Waiting test results

2021-11-25 19:59 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
this is not ideal place to make such validation, but probably moving this logic on the lever higher will require more changes than we probably want here, I would probably leave it here, thoughts?

2021-11-29 20:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +            var clusterDescription = CoreTestConfiguration.Cluster.Description;
The method can be simplified:

            if (CoreTestConfiguration.MongosNumberIfSharded.HasValue) // This implies that topology is sharded or load balanced
            {
                if (CoreTestConfiguration.MongosNumberIfSharded.Value >= 2 || !useMultipleMongoses)
                {
                    return this;
                }
                else
                {
                    var skipReason = CoreTestConfiguration.MongosNumberIfSharded.HasValue
                        ? $"has {CoreTestConfiguration.MongosNumberIfSharded.Value} mongos, but expected number is greater than or equal 2"
                        : "must be sharded"; // should not be reached due the above check on topology
                    throw new SkipException($"Test skipped because the server {skipReason}.");
                }
            }
            else
            {
                // This option has no effect for topologies that are not sharded or load balanced.
                return this;
            }

2021-11-29 20:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        public RequireServer HasMongos(int mongos)
it looks like this method is not really required, so removed

2021-11-30 01:30 UTC, rstam requested changes
Overall looks very good.

I have requested some name changes and proposed that `CoreTestConfiguration.NumberOfMongoses` *not* be nullable.

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        private static Lazy<int?> __mongosNumberIfSharded = new Lazy<int?>(GetMongosNumberCountIfSharded, isThreadSafe: true);
Rename and doesn't need to be nullable:

    private static Lazy<int> __numberOfMongoses = new Lazy<int>(GetNumberOfMongoses, isThreadSafe: true);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        public static int? MongosNumberIfSharded => __mongosNumberIfSharded.Value;
Rename and doesn't need to be nullable:

    public static int NumberOfMongoses => __numberOfMongoses.Value;

Anyone calling this property should already have established that the cluster is sharded (or load balanced).

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            using (var binding = CreateReadBinding(cluster, ReadPreference.PrimaryPreferred, session))
Why `PrimaryPreferred` instead of `Primary`?

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +        private static int? GetMongosNumberCountIfSharded()
Rename and doesn't have to return a nullable int:

     private static int GetNumberOfMongoses()

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                return null;
throw new InvalidOperationException("Cluster is not sharded or load balanced.");

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                var mongosCollection = new CollectionNamespace("config", "mongos"); // magic collection
Why "magic collection"? Seems like it should be "config collection" in which case comment is redundant.

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                var shardsCollection = new CollectionNamespace("config", "shards"); // magic collection
Why "magic collection"? Seems like it should be "config collection" in which case comment is redundant.

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/retryable-writes/RetryableWriteTestRunner.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
RequireServer.Check().MultipleMongosesIfSharded(required: useMultipleShardRouters);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
RequireServer.Check().MultipleMongosesIfSharded(required: useMultipleShardRouters);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/transactions/TransactionTestRunner.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
RequireServer.Check().MultipleMongosesIfSharded(required: useMultipleShardRouters);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
Agreed that it's not the ideal place, but maybe it's the most expedient?

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
RequireServer.Check().MultipleMongosesIfSharded(required: useMultipleShardRouters);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> +                .UseMultipleMongoses(true);
.MultipleMongoses(true);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/PinnedShardRouterTests.cs
> +                .UseMultipleMongoses(true);
.MultipleMongoses(true);

2021-11-30 01:30 UTC, rstam commented on tests/MongoDB.Driver.Tests/PinnedShardRouterTests.cs
> +                .UseMultipleMongoses(true);
.MultipleMongoses(true);

2021-11-30 02:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
done

2021-11-30 02:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/retryable-writes/RetryableWriteTestRunner.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
done

2021-11-30 02:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/transactions/TransactionTestRunner.cs
> +            RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
done

2021-11-30 02:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                        RequireServer.Check().UseMultipleMongoses(useMultipleShardRouters);
done

2021-11-30 02:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +            using (var binding = CreateReadBinding(cluster, ReadPreference.PrimaryPreferred, session))
I think copied from somewhere, changed.

2021-11-30 03:04 UTC, rstam requested changes

2021-11-30 03:04 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +                // This option has no effect for topologies that are not sharded or load balanced.
This comment seems redundant. Doesn't the method name already mean exactly that?

2021-11-30 03:04 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +            if (clusterDescription.Type != Clusters.ClusterType.Sharded && clusterDescription.Type != Clusters.ClusterType.LoadBalanced)
This if condition feels backwards. The method name says "if sharded", but this condition is "if not sharded".

See refactoring comment at end of this method.

2021-11-30 03:04 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        }
Seems like the most straightforward implementation of this method is:

    public RequireServer MultipleMongosesIfSharded(bool required)
    {
        var clusterType = CoreTestConfiguration.Cluster.Description.Type;
        if (clusterType == Clusters.ClusterType.Sharded || clusterType == Clusters.ClusterType.LoadBalanced)
        {
            MultipleMongoses(required);
        }

        return this;
    }

2021-11-30 03:04 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        }
I guess you didn't take my suggested refactoring because you wanted the `throw` to be at the end of the method like it is in other methods in this class. That's reasonable, but can be simpler then:

    public RequireServer MultipleMongoses(bool required)
    {
        if (!required || CoreTestConfiguration.NumberOfMongoses >= 2)
        {
            return this;
        }

        throw new SkipException($"Test skipped because the cluster does not have multiple mongoses.");
    }

2021-11-30 03:04 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        }
I don't think the skip message needs to be any more complicated than this.

2021-11-30 13:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +                // This option has no effect for topologies that are not sharded or load balanced.
done

2021-11-30 13:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +            if (clusterDescription.Type != Clusters.ClusterType.Sharded && clusterDescription.Type != Clusters.ClusterType.LoadBalanced)
done

2021-11-30 13:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        }
done

2021-11-30 13:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/RequireServer.cs
> +        }
done

2021-11-30 16:10 UTC, merged