CSHARP-3978: SemaphoreSlimSignalable, missing cancellationTokenSource dispose and redundant allocations.
mongodb/mongo-csharp-driver pull request #699
Opened 2021-12-01 18:04 UTC by BorisDog

- Added disposing of linked cancellationTokenSource and signalCancellationTokenSource
- Skipping allocation of the linked cancellationTokenSource when user cancellationToken was not provided

2021-12-01 18:35 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
As I understand we have reproduction of this case (that James's confirmed), then we need to add a test for this

2021-12-01 18:54 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
We do have a repro. Unfortunately it is not easy to codify into a test. Basically we execute a large number of operations and make sure that `GC.GetTotalMemory(true)` doesn't increase over time. Turning that into an automated integration test isn't straightforward. Longer term it would be desirable to create one or more smoke tests that execute some workload and verify that common resources (memory, connections, sockets, threads, etc.) remain within some reasonable bound. This doesn't exist today and is outside the scope of this fix.

2021-12-01 18:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
I'm ok to skip it now, but I think we should implement it in one or another way, so can create a separate ticket for this.

2021-12-01 18:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
note: it can be just a unit test for `SemaphoreSlimSignalable.cs`

2021-12-01 19:10 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
I agree that we should think about how to validate situations like this. This one was particularly sneaky because `SemaphoreSlimSignalable` was introduced in 2.13.0, but didn't have a noticeable affect until 2.14.0 when the wait queue was refactored to use it.

We do have tests around this class. See `SemaphoreSlimSignalableTests`. Unfortunately the resource leak in this case happens due to local variables not being disposed correctly. Since the variables are locals, it is difficult (if not impossible) to unit test. I'm open to ideas - both that can be implemented now and larger efforts that can be captured in a new ticket.

2021-12-01 19:14 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
I think testing it should be possible somehow :), let's just create a ticket and will try to work on this soon

2021-12-01 19:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            _signalCancellationTokenSource.Dispose();
Should it be also cancelled before this line? I don't really see the whole logic here, but as I know it's recommended to call Cancel and then Dispose.

2021-12-01 20:55 UTC, JamesKovacs requested changes
Minor naming change for now. You mentioned on Slack that some additional `Dispose` calls are needed. Once those are in place, I'll retest the CSHARP-3978 repro.

2021-12-01 20:55 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private CancellationContext GetCancelationTokenContext(CancellationToken cancellationToken)
`GetCancelationTokenContext` => `GetCancellationTokenContext`

2021-12-01 21:06 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
I think we can address this in in scope of stress/smoke tests as @JamesKovacs  mentioned.

2021-12-01 21:06 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +            _signalCancellationTokenSource.Dispose();
Yes in general. But we need to be cautious with that, as `Cancel` can lead to a deadlock sometimes.
In this case not need to cancel as `_semaphore` is the only consumer of this token and it's disposed in a line before.
Also `_signalCancellationTokenSource` can be already disposed, and then `Cancel` with throw.

2021-12-01 21:06 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private CancellationContext GetCancelationTokenContext(CancellationToken cancellationToken)
Thanks, done.

2021-12-01 21:06 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +                var cancellationLinkedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(
Reverted using `signalTokenSource` directly for now, as it leads to a deadlock.

2021-12-01 21:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
I would prefer to have this sooner  :), but we can discuss on the next triage

2021-12-01 21:11 UTC, DmitryLukyanov approved these changes
LGTM

2021-12-01 21:34 UTC, JamesKovacs approved these changes
LGTM

2021-12-01 21:34 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/SemaphoreSlimSignalable.cs
> +        private readonly struct CancellationContext : IDisposable
Let's file a CSHARP ticket and triage it on Monday. Volunteer?

2021-12-02 03:11 UTC, BorisDog commented
[Merged](https://github.com/mongodb/mongo-csharp-driver/commit/f4fd11d2c3efea1844ce0979b97381749173b73e)

2021-12-02 03:11 UTC, closed without merging