CSHARP-3858: Remove code that implements support for server version 3.4.
mongodb/mongo-csharp-driver pull request #703
Opened 2021-12-03 22:53 UTC by DmitryLukyanov

Waiting EG: https://evergreen.mongodb.com/version/61aa9fb257e85a6de51bd9e9?

2021-12-03 23:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +{{
replacing OP_QUERY messages on OP_MSG

2021-12-03 23:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +                var dbElement = expectedSpeculativeAuthenticateDocument.GetElement("$db");
this is a bit tricky. `$db` and `db` are different fields. `db` is what we need for speculative auth, but `$db` is a common value that we add for all commands, these values can be different

2021-12-03 23:15 UTC, DmitryLukyanov commented
Some pending work has been moved into different tickets:
1. CSHARP-3984 : Remove BinaryConnection.DropBox
2. CSHARP-3980: Implement explain for OP_MSG which will allow fully remove OP_QUERY

2021-12-04 01:10 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnection_CommandEventTests.cs
> +        //[Fact]
missed this, I will remove it in the next commit

2021-12-06 19:47 UTC, rstam requested changes
Overall looks great. Just a couple of questions.

2021-12-06 19:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +{{
Is this really how you want to do indenting?

We don't usually cram things up against the left edge like this.

2021-12-06 19:47 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
Was the old version on the left a bug? Seems like now the following clause is `false`:

    serverVersion < Feature.CommandMessage.FirstSupportedVersion

So if we substitute `false` in for that and start simplifying:

    var expectedContainsReadPreference = clusterType == ClusterType.Standalone ||
        (clusterType == ClusterType.ReplicaSet && false)
            ? false
            : true;

=>

    var expectedContainsReadPreference = clusterType == ClusterType.Standalone ||
        false ?  false : true;

=>

    var expectedContainsReadPreference = clusterType == ClusterType.Standalone || true;

=>

    var expectedContainsReadPreference = true;

2021-12-06 20:04 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +{{
true, I forgot about it and just used what VS generated for me, but I'm ok to format it as a regular code

2021-12-06 20:11 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
>clusterType == ClusterType.Standalone ||
>                    (clusterType == ClusterType.ReplicaSet && serverVersion < >Feature.CommandMessage.FirstSupportedVersion)
>                    ? false
>                    : true;

It can be simplified to:

1)    clusterType == ClusterType.Standalone || (clusterType == ClusterType.ReplicaSet && false) ? false : true
2)    clusterType == ClusterType.Standalone ? false : true
3)    clusterType **!=** ClusterType.Standalone

As I see, the simplified version of this code:
>var expectedContainsReadPreference = clusterType == ClusterType.Standalone || false ? false : true;

is this one:

>var expectedContainsReadPreference = clusterType != ClusterType.Standalone && true;

2021-12-06 20:55 UTC, rstam requested changes

2021-12-06 20:55 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
Oh you're right, I made a mistake.

But I think your simplification is also wrong.

Here's another attempt (with some parentheses added to clarify order of execution):

    var expectedContainsReadPreference = clusterType == ClusterType.Standalone || ((clusterType == ClusterType.ReplicaSet && serverVersion < Feature.CommandMessage.FirstSupportedVersion) ? false : true);
    var expectedContainsReadPreference = clusterType == ClusterType.Standalone || ((clusterType == ClusterType.ReplicaSet && false) ? false : true);
    var expectedContainsReadPreference = clusterType == ClusterType.Standalone || (false ? false : true);
    var expectedContainsReadPreference = clusterType == ClusterType.Standalone || true;
    var expectedContainsReadPreference = clusterType == ClusterType.Standalone;

So I think you need to change line 61 to::

    var expectedContainsReadPreference = clusterType == ClusterType.Standalone;

2021-12-06 21:03 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
I don't think so, this part `? false : true` is related to the whole condition:

>var expectedContainsReadPreference = clusterType == ClusterType.Standalone || ((clusterType == ClusterType.ReplicaSet && serverVersion < Feature.CommandMessage.FirstSupportedVersion) ? false : true);

so the above is not correct it should be:

var expectedContainsReadPreference = (clusterType == ClusterType.Standalone || (clusterType == ClusterType.ReplicaSet && serverVersion < Feature.CommandMessage.FirstSupportedVersion) ? false : true);

you may see this even with default VS refactoring helping logic if you replace the original code into:

                var expectedContainsReadPreference = clusterType == ClusterType.Standalone ||
                    (clusterType == ClusterType.ReplicaSet && false)
                    ? false
                    : true;

and ask VS to simplify it. The first step will be:

     var expectedContainsReadPreference = clusterType != ClusterType.Standalone && (clusterType != ClusterType.ReplicaSet || true);
 
 which effectively the same as `clusterType != ClusterType.Standalone`

2021-12-06 21:16 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
Interesting... we're parsing the old code differently.

I'll look again more closely after lunch.

One moral of the story: we should add parentheses whenever order of execution is at risk of being confusing.

2021-12-06 22:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
I have convinced myself that your change is correct. Thanks for working through it with me.

Let's never write ternary expressions like that one again. The precedence is surprising and the expression is too complex to understand at a glance.

And again: let's use parentheses when appropriate to avoid confusion about order of execution.

2021-12-06 22:19 UTC, rstam approved these changes
LGTM but wait for James to LGTM also before pushing to master.

2021-12-07 00:26 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Connections/BinaryConnection_CommandEventTests.cs
> +        //[Fact]
done

2021-12-12 22:12 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
well, this change was quite good formatted originally (but I would def write it in a different way) and as I understand this workflow is always like: 
```
"whatever conditions" ? "logic branch 1" : "logic branch 2"
```
so even though I always like explicit definitions, in this case it looks like overkill to me.

2021-12-13 02:44 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
I don't think you understood my comment.

Ternary expression are fine, no problem there.

But when the condition is very complex it is easy to read the code incorrectly.

This problem can be avoided either by using a temporary variable for the condition, or by using extra parenthesis (even though they are technically not needed) in order to be very explicit about the precedence order.

As an additional comment I would say that using ternary expressions like:

    condition ? false : true

is probably misusing ternary expressions.

2021-12-13 14:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                var expectedContainsReadPreference = clusterType != ClusterType.Standalone;
>But when the condition is very complex it is easy to read the code incorrectly.

I would say a bit more here. It also can be improved by proper formatting :) 

>As an additional comment I would say that using ternary expressions like:
> condition ? false : true

I definitely agree with this. I think the original expression is not good enough. What I want to avoid is spending time on PR comments like let's add "parentheses" in one or another way, because such expression will be always  like:

```
 condition1 && conditionN ? branch1 : branch2
```

I mean that no way (in c# syntax) `condition1 && conditionN` will be considered not as a single check 

and just formatting like this:
```
 condition1 && conditionN 
      ? branch1 
      : branch2` 
```
will solve any problem we can have

2021-12-16 22:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                return _cachedWireProtocol = CreateCommandUsingCommandMessageWireProtocol();
This change will be reverted since we want get users a better exception message if they use pre 3.6. servers:
Expected one:
>Server at %s reports wire version %d, but this version of the driver requires at least %d (MongoDB %s).

and with the current change it will be something like:

> Server closed connection (or something to that effect)

As it was suggested in the slack, we can consider removing OP_QUERY a year after 6.0 comes out

2021-12-20 20:32 UTC, DmitryLukyanov commented
I've re-requested review since as it was discussed in the slack, we still need to send OP_QUERY for initial handshake. Also I've added some minor removing

2022-01-04 20:11 UTC, rstam requested changes
One small request, if you think it makes sense.

2022-01-04 20:11 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                if (_serverApi != null || serverVersion != null)
Since we are assuming that server version >= 3.6 and that therefore any server we have connected to supports OP_MSG it might be more appropriate to test like this:

    if (_serverApi != null || connection.Description != null)

2022-01-04 20:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                if (_serverApi != null || serverVersion != null)
done

2022-01-05 01:54 UTC, rstam approved these changes
LGTM

2022-01-11 00:41 UTC, JamesKovacs requested changes
Overall looking great. Comments inline below.

One question... We now have a bunch of empty `RequireServer.Check();` statements in integration tests, but as I recall we don't use this consistently in our integration tests to denote tests that require a server. I would argument that we should remove the empty checks as I note below, but if there is a reason to leave them in and possibly expand to all integration tests, we should discuss. If we are going to go down the latter route, I would suggest considering a common base class to denote integration tests that performs this check automatically rather than having to annotate every test.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +                var dbElement = expectedSpeculativeAuthenticateDocument.GetElement("$db");
Consider renaming the variable `dollarsDbElement` to highlight this fact.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateToCollectionOperationTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndDeleteOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
#pragma not required.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndReplaceOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
#pragma not required.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndReplaceOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
#pragma not required.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndUpdateOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
#pragma not required.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndUpdateOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
#pragma not required.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/ListDatabasesOperationTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/ListDatabasesOperationTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/ChangeStreamExamples.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/DocumentationExamples.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/DocumentationExamples.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/IAggregateFluentExtensionsTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/IAggregateFluentExtensionsTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTests/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTests/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
>              RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
Empty check. Remove.

2022-01-11 00:41 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
Empty check. Remove. And same for remaining.

2022-01-11 00:51 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateExplainOperationTests.cs
> +            RequireServer.Check();
Maybe... but it's not entirely empty.

It's what you use to say "this test requires being connected to a server".

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        [Obsolete("This property will be removed in a later release.")]
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/BulkMixedWriteOperation.cs
> +                    throw new NotSupportedException($"Hint is not supported for unacknowledged writes.");
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/BulkUnmixedWriteOperationBase.cs
> +                    throw new NotSupportedException($"Hint is not supported for unacknowledged writes.");
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndDeleteOperation.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndReplaceOperation.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndUpdateOperation.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryableUpdateCommandOperation.cs
> +                    throw new NotSupportedException($"Hint is not supported for unacknowledged writes.");
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                    // For pre-3.6 servers, it will allow throwing unsupporting wire protocol exception on the driver side.
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandWireProtocol.cs
> +                    // With OP_MSG, we will receve a general server error about closing connection without actual reason of why it happened
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha1AuthenticatorTests.cs
> +                var dbElement = expectedSpeculativeAuthenticateDocument.GetElement("$db");
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Authentication/ScramSha256AuthenticatorTests.cs
> +                var dbElement = expectedSpeculativeAuthenticateDocument.GetElement("$db");
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateExplainOperationTests.cs
> +            RequireServer.Check();
Yes, I agreed with @rstam . We've discussed this long time ago. It makes since to lave this check even though there are definitely places where we connect to the server but this check is missed

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateToCollectionOperationTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CountDocumentsOperationTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndDeleteOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndDeleteOperationTests.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndDeleteOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndReplaceOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndUpdateOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndUpdateOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/ListDatabasesOperationTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/ChangeStreamExamples.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/DocumentationExamples.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/DocumentationExamples.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentFacetTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithAirportsCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentGraphLookupWithEmployeeCollectionTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateFluentTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AggregateGraphLookupEnumerableFromOrToTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/IAggregateFluentExtensionsTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/IAggregateFluentExtensionsTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTests/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTests/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/MongoQueryableTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Linq/Linq2ImplementationTestsOnLinq3/Translators/AggregateProjectTranslatorTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
>              RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/PipelineStageDefinitionBuilderTests.cs
> +            RequireServer.Check();
answered above

2022-01-11 01:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private IExecutableInRetryableReadContext<IAsyncCursor<TDocument>> CreateOperation()
yes

2022-01-11 16:35 UTC, JamesKovacs approved these changes
LGTM.

Fair enough about `RequireServer.Check();`. Let's leave it as-is especially since it has been discussed previously.

2022-01-11 19:33 UTC, merged