CSHARP-3845: Deserialize Select of anonymous types using default values for missing fields.
mongodb/mongo-csharp-driver pull request #705
Opened 2021-12-07 22:47 UTC by rstam

2021-12-07 22:48 UTC, rstam commented
Evergreen patch build:

https://evergreen.mongodb.com/version/61afe46f306615750a434767

2021-12-07 22:49 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/NewExpressionToAggregationExpressionTranslator.cs
> +                classMap.MapProperty(member.Name).SetSerializer(memberSerializer).SetDefaultValue(defaultValue);
This is really all there is to this... configure a default value for the member.

2021-12-08 00:18 UTC, JamesKovacs requested changes
Nice simple solution. Some minor testing improvements and fixes requested.

2021-12-08 00:18 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +        }
Given that `InsertMany` accepts an `IEnumerable<T>`, we don't need the intermediate `documentsList`. Consider the following instead. (I flipped if/else branches around so we don't have the awkward `!documents.Any()` construct:

```
protected void CreateCollection<TDocument>(IMongoCollection<TDocument> collection, IEnumerable<TDocument> documents = null)
{
    var database = collection.Database;
    var collectionName = collection.CollectionNamespace.CollectionName;
    database.DropCollection(collectionName);

    if (documents != null && documents.Any())
    {
        collection.InsertMany(documents);
    }
    else
    {
        database.CreateCollection(collectionName);
    }
}
```

2021-12-08 00:18 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3845Tests.cs
> +        }
We are assuming order of returned results without specifying a sort. We should specify a sort.

2021-12-08 02:02 UTC, rstam reviewed
I don't object to any of your suggestions but I have questions/comments for you before making the changes.

2021-12-14 01:00 UTC, JamesKovacs requested changes
Feedback on discussion points.

2021-12-14 01:00 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +        }
In production code, I am definitely concerned with possible multiple enumeration. But given this is test code and all code paths supply it with an array, I'm not worried about it.

2021-12-14 19:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +            if (documentsList != null && documentsList.Count == 0)
Done

2021-12-14 19:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +        }
Done

But we should get in the habit of avoiding multiple enumeration... it's a bad practice. Being lazy in test code could lead to being lazy in production code.

It's a problem we were not aware of for a long time. There are multiple places in our production code where we inadvertently enumerate something multiple times.

2021-12-17 23:48 UTC, JamesKovacs approved these changes
LGTM

2021-12-18 00:16 UTC, closed without merging