CSHARP-3980: Implement $explain modifier for CommandWireProtocol (OP_MSG).
mongodb/mongo-csharp-driver pull request #712
Opened 2021-12-24 21:07 UTC by DmitryLukyanov

This is initial PR, there are some pending question that might require some changes + adding more tests.
Some notes/questions:
1. I'm not sure about current public API, so it would be good to discuss it.
2. do we want adding explain functionality for operations like:
* findAndModify (and other similar)
* changeStream probably there are more cases
* ?
3. I think logic in `FindCommandOperation` and `FindOperation` should be merged. Will do it in the final version.
4. Aggregate provides 2 ways to configure explain: 
* Explain command: https://docs.mongodb.com/manual/reference/command/explain/
* Explain argument in aggregate command itself: https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields
In this PR I left only the second approach(the first one is used in Legacy) since it would be good to have the same code path for all explain code paths. Also, only the second approach allows configuring verbosity, so this approach looks like the best. However I'm going to confirm that it doesn't give us some issues either performance or maybe missed functionality (probably only in January).
5. I'm also going to confirm whether I understand the format of server response for explain correctly (in other words there is no edge cases and etc).
6. In the scope of this PR, I also replaced serialization logic in AsyncCursor and Find in the same manner as it's done for aggregation. So, now aggregate and find and getmore use the same serializer. I'm not sure why it wasn't done in this way originally. So, we can discuss it.

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> +            if (_explainVerbosity.HasValue)
Configuring explain in aggregation

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> -        private AsyncCursor<TResult> CreateCursorFromInlineResult(BsonDocument command, AggregateResult result)
I'm going to confirm it (additionally to this [discussion](https://mongodb.slack.com/archives/C72LB5RPV/p1640358821319100?thread_ts=1640358021.318900&cid=C72LB5RPV)). But it looks like we no longer have a way to use this code path since the only approach that allowed cursorId be omitted is configuring `UseCursor=false` that we don't support anymore.

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> -        private class AggregateResult
I've created a global class CursorContext instead

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> -        private class AggregateResultDeserializer : SerializerBase<AggregateResult>
Now it's named `CursorContextDeserializer`

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AsyncCursor.cs
> +            return new CursorBatch<TDocument>(result);
it makes sense to call all deserializer logic on lower layers. It also allows reusing this logic in different places

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ExplainOperation.cs
> +            if (!command.TryGetValue("aggregate", out var collectionName) &&
here we get a `collectionNamespace`  value from explain response. I'm going to check/confirm which logic is better here

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +                                (Enum.TryParse<ExplainVerbosity>(value.ToString(), ignoreCase: true, out var verbosity)
We can remove `Enum.TryParse` logic since previosuly `_modifiers["$explain"]` didn't allow setting verbosity (it was just false/true flag). 
I checked with old servers that setting `_modifiers["$explain"]` corresponds to the verbosity: `ExplainVerbosity.AllPlansExecution`. so we can leave only this part. Thoughts?

2021-12-24 21:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver/ProjectionDefinition.cs
> +    internal sealed class ExplainBsonDocumentProjectionDefinition<TSource, TProjection> : ProjectionDefinition<TSource, BsonDocument>
this needs to convert a projection with custom type in TProjection (that might be configured by a user) to the same projection but with replacing TProjection on the same value but projected to BsonDocument

2021-12-24 21:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindCommandOperation.cs
> +            if (_explainVerbosity.HasValue)
configuring Explain for FindCommandOperation

2021-12-24 21:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private ExplainVerbosity? _explainVerbosity;
I think this class should be merged with `FindCommandOperation`. Will do it in the final commit.

2021-12-24 21:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver/FindFluent.cs
> +                newOptions.Projection = new ExplainBsonDocumentProjectionDefinition<TDocument, TProjection>(_options.Projection);
Replace TProjection on BsonDocument

2022-01-06 00:09 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> +            if (_explainVerbosity.HasValue)
I left only logic that already presented in previous version, explain in aggregate is temporary reverted. I will create a ticket to proceed with these changes there

2022-01-06 00:10 UTC, DmitryLukyanov commented on src/MongoDB.Driver/ProjectionDefinition.cs
> +    internal sealed class ExplainBsonDocumentProjectionDefinition<TSource, TProjection> : ProjectionDefinition<TSource, BsonDocument>
This logic is reverted for the scope of this PR

2022-01-06 00:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOperation.cs
> +        private ExplainVerbosity? _explainVerbosity;
This is not so easy as I expected originally, I think we can implement it in the scope of the follow-up ticket

2022-01-06 00:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ExplainOperation.cs
> +            return new CursorBatch<TResult>(
Originally I had tried to parse explain response to get collectionName which will allow us having collectionName value all the time, however $explain responses are not the same in different servers and parsing logic became too complicated eventially, so it's better to handle lack of collectionNamespace before creating cursor

2022-01-06 00:27 UTC, DmitryLukyanov commented
The last commit https://github.com/mongodb/mongo-csharp-driver/pull/712/commits/e8a5ebaf7206a97fe13131be6911df403195ea87 reverts changes in any user faced logic that had not been implemented before. This ticket https://jira.mongodb.org/browse/CSHARP-4008 tracks reverted changes

2022-01-11 21:02 UTC, DmitryLukyanov commented
ready for review

2022-01-12 16:13 UTC, rstam requested changes

2022-01-12 16:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/AggregateOperation.cs
> -        private class AggregateResultDeserializer : SerializerBase<AggregateResult>
but they're related to the CursorBatch, aren't they?

2022-01-14 15:41 UTC, rstam requested changes
Waiting for changes that were discussed in a Zoom meeting with James.

2022-01-14 17:51 UTC, rstam commented
This is a large PR and it's hard to work through the comments so far. Here's a summary of the changes I'm requesting (a few might be new):

replace `description.ServerVersion` with `description.MaxWireVersion` (not `description.WireVersionRange`)
Use `MaxWireVersion` everywhere instead of `WireVersionRange` (min of range is irrelevant)

use `int` for `MinWireVersion` and `MaxWireVersion` instead of `WireVersion` class

`WireVersion` can be a static class with the following helper methods:

    WireVersion.ToServerVersion(wireVersion) // approximate server version
    WireVersion.ToWireVersion(serverVersion)
 
Remove ALL uses of `ServerVersion` in the driver (OK to use `ServerVersion` in some form in tests, but see warning below)

Add `ConnectionDescription.MinWireVersion` and `ConnectionDescription.MaxWireVersion` instead of `ConnectionDescription.WireVersionRange` (ease of use and readability)

Remove `ConnectionDescription.BuildInfoResult` property entirely
returning `null` or a gutted emulated value is already backward breaking

Implement `ConnectionDescription.ServerVersion` to return an estimated server version based on MaxWireVersion

But now tests can't use `ConnectionDescription.ServerVersion` because it's no longer accurate
Tests need to run `buildInfo` explicitly: refactor `CoreTestConfiguration.ServerVersion` to lazily run `buildInfo` when first referenced

All `Feature` classes (including subclasses) should use wire version only and not server version
Remove server version entirely from `Feature` classes

NOTE: I'm assuming we're resolving the contradictory decisions about whether to call `buildInfo` or not by deciding NOT to call it anymore

2022-01-14 17:57 UTC, DmitryLukyanov commented
ready for review

2022-01-14 18:15 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp3980Tests.cs
> +            exception.Should().BeOfType<NotSupportedException>();
`cursor.Explain` should actually work now so this test needs to be altered.

I'm assuming it doesn't pass for you?

2022-01-14 18:18 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp3980Tests.cs
> +            exception.Should().BeOfType<NotSupportedException>();
done

2022-01-14 19:59 UTC, rstam requested changes
Something went wrong in the rebasing on master.

The following files need to be deleted:

FindCommandOperation.cs
FindOpcodeOperation.cs
FindOpcodeOperationTests.cs

Everything else looks good.

2022-01-15 03:43 UTC, DmitryLukyanov commented
ready for review

2022-01-17 23:56 UTC, rstam approved these changes
LGTM

2022-01-20 15:46 UTC, DmitryLukyanov commented
merged.

2022-01-20 15:46 UTC, closed without merging