CSHARP-3918: Support authorizedCollections option for listCollections helpers.
mongodb/mongo-csharp-driver pull request #715
Opened 2022-01-10 17:53 UTC by DmitryLukyanov

Waiting for EG

2022-01-10 17:55 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +    public class ListCollectionsOperation : IReadOperation<IAsyncCursor<BsonDocument>>, IExecutableInRetryableReadContext<IAsyncCursor<BsonDocument>>
The diff in this file is mostly related to the fact that I merged ListCollectionsOperation and ListCollectionsUsingCommandOperation. Effectively I removed `ListCollectionsOperation` and renamed `ListCollectionsUsingCommandOperation` to `ListCollectionsOperation`

2022-01-10 17:56 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/ListCollectionsOperationTests.cs
> +        [Fact]
The diff in this file is mostly related to the fact that I merged ListCollectionsOperationTests and ListCollectionsUsingCommandOperationTests. Effectively I removed ListCollectionsOperationTests and renamed ListCollectionsUsingCommandOperationTests to ListCollectionsOperationTests

2022-01-10 18:57 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +                    listCollectionNamesOptions.AuthorizedCollections = true;
in fact server doesn't throw exception for any property here, for example the below works "fine" too:

    MongoDB Enterprise mongos> db.runCommand({ listCollections:1, fake:1})
    {
            "result" : [ ],
            "cursor" : {
                    "id" : NumberLong(0),
                    "ns" : "test.$cmd.listCollections",
                    "firstBatch" : [ ]
            },
            "ok" : 1,
            "operationTime" : Timestamp(1641840858, 1),
            "$clusterTime" : {
                    "clusterTime" : Timestamp(1641840858, 1),
                    "signature" : {
                            "hash" : BinData(0,"AAAAAAAAAAAAAAAAAAAAAAAAAAA="),
                            "keyId" : NumberLong(0)
                    }
            }
    }

so the fact that the server didn't return exception for `AuthorizedCollections:true` diesn't mean it works correctly, but I would probably not to worry about this and would not involve tests with auth workflow

2022-01-11 21:23 UTC, BorisDog requested changes

2022-01-11 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +                        o.AuthorizedCollections == (authorizedCollections.HasValue ? authorizedCollections.Value : null) &&
`o.AuthorizedCollections == authorizedCollections` should be sufficient

2022-01-11 21:23 UTC, BorisDog commented on src/MongoDB.Driver/ListCollectionsOptions.cs
> +        private bool? _authorizedCollections;
Should `_authorizedCollections` option be added to `ListCollectionNamesOptions` only? As it has no effect without `nameOnly: true`, and we don't set `nameOnly` in this case. Or alternatively should we implement the "Drivers MUST specify true for the ``nameOnly`` option ..." section ?

2022-01-12 16:25 UTC, rstam commented
I added myself as a reviewer because I want to review any further changes that might happen with respect to the `nameOnly` flag (I'm trying to decipher the Slack discussion on that).

2022-01-12 16:36 UTC, rstam requested changes

2022-01-12 16:36 UTC, rstam commented on src/MongoDB.Driver/ListCollectionsOptions.cs
> +        private bool? _authorizedCollections;
I agree that it should be added for `ListCollectionNames` only.

2022-01-12 17:23 UTC, BorisDog requested changes
Minor comments

2022-01-12 17:23 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +        /// The authorizedCollections.
nit: Return value: `Whether authorizedCollections flag/option is set...`

2022-01-12 17:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +            [Values(false, true)] bool usingAuthorizedCollection,
nit: usingAuthorizedCollection**s**

2022-01-12 17:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +                var listCollectionNamesOptions = new ListCollectionNamesOptions();
The overload without options not tested anymore. Maybe we can add `null`  to `usingAuthorizedCollections `parameter values for that: `[Values(false, true, null)] bool usingAuthorizedCollection`?

2022-01-12 17:51 UTC, rstam approved these changes
LGTM but please re-request my review if you make any further significant changes.

2022-01-12 18:07 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +        /// The authorizedCollections.
done

2022-01-12 18:07 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +            [Values(false, true)] bool usingAuthorizedCollection,
done

2022-01-12 18:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoDatabaseImplTests.cs
> +                var listCollectionNamesOptions = new ListCollectionNamesOptions();
done

2022-01-12 18:11 UTC, DmitryLukyanov commented
ready for review

2022-01-12 18:35 UTC, BorisDog approved these changes
LGTM

2022-01-13 01:18 UTC, closed without merging