CSHARP-3480: Switch to using maxWireVersion rather than buildInfo to determine feature support.
mongodb/mongo-csharp-driver pull request #720
Opened 2022-01-13 20:41 UTC by DmitryLukyanov

2022-01-13 20:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateAccumulator = new Feature("AggregateAccumulator", new SemanticVersion(4, 4, 0));
we don't need to care about old developer releases

2022-01-13 20:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOutOnSecondary = new Feature("AggregateOutOnSecondary", WireVersion.Thirteen);
I used a new overload with WireVersion everywhere where I found that spec requires looking at maxWireVersion, but probably it makes sense to do it in other places?

2022-01-13 20:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                    ?? __wireVersionSemanticVersionsSet.Last();
there is a spec test that requires that we should handle providing a very large maxWireVersion

2022-01-13 20:48 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadOperationExecutor.cs
> -            if (context.Channel.ConnectionDescription.ServerVersion < initialServerVersion)
this logic is not (and it looks like never was) part of the spec

2022-01-13 20:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/ClusterTests.cs
> -            "buildInfo",
no longer needed. 
note: I will create a similar ticket for `getLastError`

2022-01-13 22:48 UTC, rstam requested changes
Preliminary comments. More to come after the next commit(s).

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                    mergedHelloResult);
We should continue to have buildInfo here.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                    mergedHelloResult);
And everywhere else also.

Note: we're still supposed to call `buildInfo` but we're supposed to have a try/catch around it and create a minimal fake `buildInfo` derive from max wire version if `buildInfo` fails.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                    mergedHelloResult);
We should no longer use BuildInfo ourselves... but to avoid backward breaking changes we should continue to capture and preserve it.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        internal bool IsSupported(Range<int> wireVersionRange)
Why is this argument a range?

The decision whether something is supported or not is based on max wire version alone.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionInitializer.cs
> +            return new ConnectionDescription(connection.ConnectionId, helloResult);
We were supposed to continue to call `buildInfo` in a try/catch and only use an emulated minimal buildInfo if the `buildInfo` command failed.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOutOnSecondary = new Feature("AggregateOutOnSecondary", WireVersion.Thirteen);
I think we should use maxWireVersion everywhere in this class.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/SemanticVersion.cs
> +        internal int MaxWireVersion
This doesn't seem to belong in `SemanticVersion`. It has nothing to do with semantic versions.

Let's find a better place for this mapping (perhaps even in the WireVersion class?).

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/ChangeStreamCursor.cs
> +        private readonly Range<int> _wireVersionRange;
Why a range?

Seems like max wire version is the only one that matters.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadOperationExecutor.cs
> -            if (context.Channel.ConnectionDescription.ServerVersion < initialServerVersion)
Is it an omission in the spec?

This is not here by accident. It makes no sense to send the retry to an older server.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +            _firstSupportedVersion = Ensure.IsNotNull(
Shouldn't Feature be defined in terms of supported wire version numbers now?

So the following fields need to be replaced with wire version equivalents:

    private readonly SemanticVersion _firstSupportedVersion;
    private readonly SemanticVersion _supportRemovedVersion;

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +            _firstSupportedVersion = Ensure.IsNotNull(
I think the goal of this ticket is:

1. Continue to provide ServerVersion info to the application to the extent possible for backward compatibility
2. Never use ServerVersion in the driver itself

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateOutOnSecondary = new Feature("AggregateOutOnSecondary", WireVersion.Thirteen);
I think you should just use `13` here:

    private static readonly Feature __aggregateOutOnSecondary = new Feature("AggregateOutOnSecondary", 13);

Mappings between wire version and approximate server version should be few and far between and can be handled by helper methods.

2022-01-13 22:48 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +    internal class WireVersion
I think we can just use `int` values when we need to refer to wire versions.

So just use `13` instead of `WireVersion.Thirteen`.

This class could instead become a static helper class that maps back and forth between wire version numbers and server versions.

For example:

    var serverVersion = WireVersion.ToServerVersion(13);
    var wireVersion = WireVersion.FromServerVersion(serverVersion);

2022-01-14 05:27 UTC, rstam requested changes
Further comments.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                && Feature.ScramSha256Authentication.IsSupported(description.WireVersionRange))
I think all occurrences of `description.ServerVersion` should be replaced with `description.MaxWireVersion` not with `description.WireVersionRange`.

It's in the name of the ticket! => switch to using maxWireVersion...

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Authentication/DefaultAuthenticator.cs
> +                    mergedHelloResult);
It's unclear to me now after our discussions today whether we are still supposed to call buildInfo or not.

There are multiple discussions that contradict each other.

@JamesKovacs ?

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionDescription.cs
> +        [Obsolete("This property will be removed in a later release.")]
If we are going to stop calling `buildInfo` then this property should be physically removed.

Yes that's backward breaking. And that's how we tell our users that they no longer have access to the build info.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionDescription.cs
> +        public Range<int> WireVersionRange
I would add `MaxWireVersion` and `MinWireVersion` instead.

Really `MaxWireVersion` is the only thing that matters for feature determination.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateAccumulator = new Feature("AggregateAccumulator", new SemanticVersion(4, 4, 0));
We did when we first added this.

But agreed that we no longer do.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __aggregateAccumulator = new Feature("AggregateAccumulator", new SemanticVersion(4, 4, 0));
But... all these feature classes should now be defined using wire versions instead of server versions.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +            _firstSupportedVersion = Ensure.IsNotNull(
But.... if the decision is to stop calling `buildInfo` then we can only guess at an approximate server version number.

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        internal void ThrowIfNotSupported(Range<int> wireVersionRange)
Parameter should be `int wireVersion` not a `Range<int>`

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/HintForFindAndModifyFeature.cs
> +        private readonly int _firstWireVersionWhereWeRelyOnServerToReturnError = WireVersion.Eight.MaxWireVersion;
`WireVersion.Eight.MaxWireVersion` is an odd way to write `8`

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/HintForFindAndModifyFeature.cs
> +            return serverVersion < WireVersion.GetWireVersion(_firstWireVersionWhereWeRelyOnServerToReturnError).FirstSupportedVersion;
We should be making decisions using only wire version numbers.

2022-01-14 05:27 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> -                var version = description.Version ?? (description.Type == ServerType.LoadBalanced ? _buildInfo.Value.ServerVersion : null);
What was this load balanced logic all about and why was it removed?

2022-01-14 05:27 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/HintForFindAndModifyFeature.cs
> +        private readonly int _firstWireVersionWhereWeRelyOnServerToReturnError = WireVersion.Eight.MaxWireVersion;
Note: I think the `WireVersion` class should either not exist or at most be a static class with a small number of helper methods for converting back and forth between wire version and *approximate* server version.

2022-01-14 18:16 UTC, rstam commented
This is a large PR and it's hard to work through the comments so far. Here's a summary of the changes I'm requesting (a few might be new):

replace `description.ServerVersion` with `description.MaxWireVersion` (not `description.WireVersionRange`)
Use `MaxWireVersion` everywhere instead of `WireVersionRange` (min of range is irrelevant)

use `int` for `MinWireVersion` and `MaxWireVersion` instead of `WireVersion` class

`WireVersion` can be a static class with the following helper methods:

    WireVersion.ToServerVersion(wireVersion) // approximate server version
    WireVersion.ToWireVersion(serverVersion)
 
Remove ALL uses of `ServerVersion` in the driver (OK to use `ServerVersion` in some form in tests, but see warning below)

Add `ConnectionDescription.MinWireVersion` and `ConnectionDescription.MaxWireVersion` instead of `ConnectionDescription.WireVersionRange` (ease of use and readability)

Remove `ConnectionDescription.BuildInfoResult` property entirely
returning `null` or a gutted emulated value is already backward breaking

Implement `ConnectionDescription.ServerVersion` to return an estimated server version based on MaxWireVersion

But now tests can't use `ConnectionDescription.ServerVersion` because it's no longer accurate
Tests need to run `buildInfo` explicitly: refactor `CoreTestConfiguration.ServerVersion` to lazily run `buildInfo` when first referenced

All `Feature` classes (including subclasses) should use wire version only and not server version
Remove server version entirely from `Feature` classes

NOTE: I'm assuming we're resolving the contradictory decisions about whether to call `buildInfo` or not by deciding NOT to call it anymore

2022-01-15 03:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +                    var emulatedServerVersion = WireVersion.ToServerVersion(maxWireVersion);
As per @JamesKovacs suggestion, we should not leave only wire version in the error message and also mention a server version. I tried to mimic the error message in this spec: https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#checking-wire-protocol-compatibility
However I'm open to suggestions

2022-01-17 19:52 UTC, rstam requested changes
Re-request our review after you have made any changes you are still working on.

2022-01-18 01:16 UTC, rstam requested changes

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        }
Why aren't we just removing this constructor. We should NOT be expressing feature detection using server version any more.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        internal int FirstSupportedMaxWireVersion => _firstSupportedWireVersion;
I think this property should be named `FirstSupportedWireVersion`.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        }
I think all references to `SemanticVersion` should be removed from this class so we don't accidentally try to do feature detection using server versions.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        internal bool IsSupported(int maxWireVersion)
Parameter should be named `wireVersion`.

Whether or not it is the max or not depends on the caller.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +                    var emulatedServerVersion = WireVersion.ToServerVersion(maxWireVersion);
Why do we have to have the wire version number in the error message at all? Users know nothing of wire versions.

How about simply?

    var serverVersion = WireVersion.ToServerVersion(wireVersion);
    errorMessage = $"Server version {serverVersion} does not support the {_name} feature.";

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/HintForFindAndModifyFeature.cs
> +        public bool DriverMustThrowIfNotSupported(int maxWireVersion)
Parameter should be named `wireVersion`.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/AggregateToCollectionOperation.cs
> +                return Feature.AggregateOutOnSecondary.IsSupported(server.MaxWireVersion ?? throw new InvalidOperationException("MaxWireVersion must be initialized."));
Can be simply: 

    return Feature.AggregateOutOnSecondary.IsSupported(server.MaxWireVersion);

We know this method is NOT called for load balancers.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndDeleteOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {emulatedServerVersion.Major}.{emulatedServerVersion.Mino
Message is too complex. How about:

    var serverVersion = WireVersion.ToServerVersion(maxWireVersion);
    throw new NotSupportedException($"Server version {serverVersion} does not support hints.");

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndDeleteOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {emulatedServerVersion.Major}.{emulatedServerVersion.Mino
Note: `emulatedServerVersion` is not a good name. It's "approximated", not "emulated".

We can just use `serverVersion`, or if you want a longer name `approximateServerVersion`.

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndReplaceOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {emulatedServerVersion.Major}.{emulatedServerVersion.Mino
Message too complex:

    var serverVersion = WireVersion.ToServerVersion(maxWireVersion);
    throw new NotSupportedException($"Server version {serverVersion} does not support hints.");

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndUpdateOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {emulatedServerVersion.Major}.{emulatedServerVersion.Mino
Message too complex:

    var serverVersion = WireVersion.ToServerVersion(maxWireVersion);
    throw new NotSupportedException($"Server version {serverVersion} does not support hints.");

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerDescription.cs
> +
As discussed on Slack for ease of use this should be of type `int`.

    public int MaxWireVersion
    {
        get
        {
            if (_wireVersionRange == null)
            {
                throw new InvalidOperationException("MaxWireVersion is not known.");
            }
            return _wireVersionRange.Max;
        }

    }

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                AddErrorLabelIfRequired(exception, connection.Description?.MaxWireVersion);
Why would `Description` be null?

2022-01-18 01:16 UTC, rstam commented on src/MongoDB.Driver.Legacy/Communication/MongoServerInstance.cs
> +                return new MongoServerBuildInfo(emulateServerVersion.ToString());
"emulated" doesn't sound right.

Simply use `serverVersion` or if you prefer `approximateServerVersion`.

2022-01-18 01:20 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryableReadOperationExecutor.cs
> -            if (context.Channel.ConnectionDescription.ServerVersion < initialServerVersion)
>The issue is that the older server might not support retryable reads at all!

any selected server can be only higher or equal to server 3.6 which supports retryable read and write.

2022-01-18 17:05 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndUpdateOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {emulatedServerVersion.Major}.{emulatedServerVersion.Mino
final formulation is still pending

2022-01-18 19:43 UTC, rstam requested changes
I think we're getting close!

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +        private static readonly SemanticVersion __minSupportedServerVersion = WireVersion.FirstSupportedServerVersion;
Use the following instead so we can eliminate the `FirstSupportedServerVersion` property that is not used anywhere else:

    private static readonly SemanticVersion __minSupportedServerVersion = WireVersion.ToServerVersion(WireVersion.SupportedWireVersionRange.Min);

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
>  #pragma warning disable CS0618 // Type or member is obsolete
All these pragmas are no longer needed.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
>  #pragma warning disable CS0618 // Type or member is obsolete
I figured out why I was so surprised that the `Feature` subclasses are no longer needed.

It has nothing to do with switching to `MaxWireInfo` for feature detection.

It is because all the subclasses were only needed for servers older than 3.6. So normally these would have been removed as part of an earlier PR.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public SemanticVersion FirstSupportedVersion => WireVersion.ToServerVersion(_firstSupportedWireVersion);
Just remove this property entirely. It is no longer needed.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public SemanticVersion LastNotSupportedVersion => WireVersion.ToServerVersion(LastNotSupportedWireVersion);
Just remove this property entirely. It is no longer needed.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +    internal class WireVersion
`WireVersion` can be a static class:

    internal static class WireVersion

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +        };
I think we should only list the supported wire versions:

    private static List<WireVersionInfo> __supportedWireVersions = new()
    {
        // must be sorted in ascending wire version (and therefore also ascending server version)
        // 10-12 were only used in pre-release versions and will therefore never be encountered
        new WireVersionInfo(wireVersion: 6, major: 3, minor: 6),
        new WireVersionInfo(wireVersion: 7, major: 4, minor: 0),
        new WireVersionInfo(wireVersion: 8, major: 4, minor: 2),
        new WireVersionInfo(wireVersion: 9, major: 4, minor: 4),
        new WireVersionInfo(wireVersion: 13, major: 5, minor: 0),
        new WireVersionInfo(wireVersion: 14, major: 5, minor: 1),
    };

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +        public static Range<int> SupportedWireRange
Just return value pre-computed in static constructor:

    public static Range<int> SupportedWireVersionRange => __supportedWireVersionRange;

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +        public static SemanticVersion FirstSupportedServerVersion
Remove this property. It is no longer needed.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +        public static SemanticVersion ToServerVersion(int maxWireVersion)
Rename parameter to `wireVersion`.

The general rule should be: the parameter should only be named `maxWireVersion` if we KNOW it is the max wire version or if it MUST be the max wire version.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +            return wireVersionInfo.FirstSupportedServerVersion;
Using the precomputed `__serverVersionsMap` proposed above we can avoid a scan and do a simple array lookup instead:

    public static SemanticVersion ToServerVersion(int wireVersion)
    {
        Ensure.IsGreaterThanOrEqualToZero(wireVersion, nameof(wireVersion));
        var serverVersion = wireVersion < __serverVersionsMap.Length ? __serverVersionsMap[wireVersion] : null;
        if (serverVersion == null)
        {
            throw new ArgumentException($"Wire version not supported: {wireVersion}.", nameof(wireVersion));
        }
        return serverVersion;
    }

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +            return __wireVersionSemanticVersionsSet.Last(w => w.FirstSupportedServerVersion <= semanticVersion).MaxWireVersion;
return __supportedWireVersions.Last(w => w.FirstSupportedServerVersion <= semanticVersion).WireVersion;

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +            public WireVersionInfo(int maxWireVersion, int major, int minor)
Rename `maxWireVersion` to `wireVersion`.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndDeleteOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {approximateServerVersion.Major}.{approximateServerVersio
Suggested error message:

    throw new NotSupportedException("Server version {approximateServerVersion}.x (wire version {wireVersion}) does not support hints.");

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndReplaceOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {approximateServerVersion.Major}.{approximateServerVersio
Suggested error message:

    throw new NotSupportedException("Server version {approximateServerVersion}.x (wire version {wireVersion}) does not support hints.");

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/FindOneAndUpdateOperation.cs
> +                    throw new NotSupportedException($"Server with reported max wire version {maxWireVersion} (Supported starting from MongoDB {approximateServerVersion.Major}.{approximateServerVersio
Suggested error message:

     throw new NotSupportedException("Server version {approximateServerVersion}.x (wire version {wireVersion}) does not support hints.");

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                AddErrorLabelIfRequired(exception, connection.Description.MaxWireVersion);
I asked the question "Why would Description be null".

I was hoping for a reason, not for a code change.

One possible reason might be the very FIRST command sent on a connection (perhaps the `hello` command itself) where we don't yet have a `Description` or maybe only have a `Description` where the `MaxWireVersion` is not yet known.

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
Get rid of `_buildInfo` entirely and replace it with:

    private static Lazy<int> __maxWireVersion = new Lazy<int>(GetMaxWireVersion, isThreadSafe: true);
    private static Lazy<SemanticVersion> __serverVersion = new Lazy<SemanticVersion>(GetServerVersion, isThreadSafe: true);

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
Where the helper methods that compute the values for `__maxWireVersion` and `__serverVersion` are:

    private static int GetMaxWireVersion()
    {
        using (var session = StartSession())
        using (var binding = CreateReadBinding(session))
        {
            var command = new BsonDocument("hello", 1);
            var operation = new ReadCommandOperation<BsonDocument>(DatabaseNamespace.Admin, command, BsonDocumentSerializer.Instance, __messageEncoderSettings);
            var response = operation.Execute(binding, CancellationToken.None);
            return response["maxWireVersion"].AsInt32;
        }
    }

    private static SemanticVersion GetServerVersion()
    {
        using (var session = StartSession())
        using (var binding = CreateReadBinding(session))
        {
            var command = new BsonDocument("buildinfo", 1);
            var operation = new ReadCommandOperation<BsonDocument>(DatabaseNamespace.Admin, command, BsonDocumentSerializer.Instance, __messageEncoderSettings);
            var response = operation.Execute(binding, CancellationToken.None);
            var versionString = response["version"].AsString;
            return SemanticVersion.Parse(versionString);
        }
    }

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                return SemanticVersion.Parse(serverVersion.ToString());
return __serverVersion.Value;

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                return WireVersion.ToWireVersion(ServerVersion);
return __maxWireVersion.Value;

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Misc/WireVersionTests.cs
> +            WireVersion.FirstSupportedServerVersion.Should().Be(new SemanticVersion(3, 6, 0));
Remove test. Property was removed.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +            return __wireVersionSemanticVersionsSet.Last(w => w.FirstSupportedServerVersion <= semanticVersion).MaxWireVersion;
In this case we can't avoid the scan because there are lots of server versions that aren't in the table.

2022-01-18 19:43 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                MaxWireVersion = maxWireVersion;
Rename `MaxWireVersion` to `WireVersion`.

2022-01-18 19:43 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
The key feature of these two helper methods is that we *actually* ask the server for the information. We don't assume anything.

Note that this also gives us the *exact* server version, not an approximation from wire version.

As mentioned before we assume that all nodes in a cluster are the same version and that the servers won't be upgraded in the middle of a test run.

2022-01-18 23:48 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
>We don't assume anything.

I don't think that we actually assume anything here. We call buildInfo directly and get actual server version. As for maxWireVersion, I can adding a call hello if you insist, but I don't see any reason for this. If we know actual server version, we ensure than maxWireVersion either correct or we thrown exception.

2022-01-18 23:54 UTC, rstam requested changes

2022-01-18 23:54 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
I guess you could "deduce" the `MaxWireVersion` from the `ServerVersion` if you wanted to.

I figured it was more correct to get it from the server.

2022-01-18 23:59 UTC, rstam requested changes

2022-01-18 23:59 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
On a related not... since we're supposed to use `MaxWireVersion` instead of `ServerVersion` can we just get rid of the `CoreTestConfiguration.ServerVersion` property?

2022-01-18 23:59 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
> As mentioned before we assume that all nodes in a cluster are the same version and that the servers won't be upgraded in the middle of a test run.

Why do you say we don't assume anything. We do in fact assume that the cluster topology and server versions won't change while the test suite is running.

That's the only reason it's OK to get the `MaxWireVersion` and `ServerVersion` ONCE and cache them.

2022-01-19 02:07 UTC, rstam requested changes

2022-01-19 02:07 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
I guess we can't actually get rid of this property, because even though we are only supposed to use `MaxWireVersion` for feature detection, the `runOn` section of JSON tests use server versions instead of wire versions.

2022-01-19 02:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public SemanticVersion FirstSupportedVersion => WireVersion.ToServerVersion(_firstSupportedWireVersion);
done

2022-01-19 02:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public SemanticVersion LastNotSupportedVersion => WireVersion.ToServerVersion(LastNotSupportedWireVersion);
done

2022-01-19 03:01 UTC, rstam requested changes

2022-01-19 03:01 UTC, rstam commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                AddErrorLabelIfRequired(exception, connection?.Description?.MaxWireVersion);
Revert to `connection` instead of `connection?.`

2022-01-19 15:37 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/WireProtocol/CommandUsingCommandMessageWireProtocol.cs
> +                AddErrorLabelIfRequired(exception, connection?.Description?.MaxWireVersion);
oh.. yes, my mistake, thanks for catching it.

2022-01-19 15:37 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +#pragma warning restore CS0618 // Type or member is obsolete
done

2022-01-19 15:37 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                return WireVersion.ToWireVersion(ServerVersion);
after thinking more, I think there is no harm to call `hello` once for tests. So I changed this logic as you suggested initially. Done

2022-01-19 15:37 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                wireVersion = __wireVersionSemanticVersionsSet.Count - 1;
As I wrote, we have a test for the case when we should handle huge maxWireVersion: https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/tests/rs/compatible.json#L35

Effectively it means any wire version upper than we support we converts to the last protocol we knows, as I see it should not be a problem in a real life. However, maybe another possible approach is to set serverVersion null for this case since we don't use connectionDescription.Version in any case anymore.

2022-01-19 15:41 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                wireVersion = __wireVersionSemanticVersionsSet.Count - 1;
We also can add a sanity check on null in `ConnectionDescription.Version` just in case

2022-01-19 15:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
>  #pragma warning disable CS0618 // Type or member is obsolete
done

2022-01-19 17:31 UTC, rstam requested changes

2022-01-19 17:31 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +                return _firstSupportedWireVersion > 0 ? _firstSupportedWireVersion - 1 : throw new ArgumentException("There is no maxWireVersion before 0.");
Besides rewording the exception message I think we should change the exception type to `InvalidOperationException` because there is no "argument" here.

    return _firstSupportedWireVersion > 0 ? _firstSupportedWireVersion - 1 : throw new InvalidOperationException("There is no wire version before 0.");

2022-01-19 17:31 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                "Incorrect supported wire version range configuration."); // should not be reached
I agree that we should normally throw a subclass of `Exception`.

I was willing to make an "exception" here (pun intended) because this exception would never actually be thrown, excepting maybe during development.

How about `ApplicationException` then?

2022-01-19 17:31 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Bindings/CoreSessionTests.cs
> +        [InlineData("RT,RN", "Server version 4.0.x does not support the ShardedTransactions feature.")]
@JamesKovacs said not to include `.x`

2022-01-19 17:31 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +                    errorMessage = $"Server version {approximateServerVersion.Major}.{approximateServerVersion.Minor}.x does not support the {_name} feature.";
@JamesKovacs said not to include `.x`:

    errorMessage = $"Server version {approximateServerVersion.Major}.{approximateServerVersion.Minor} does not support the {_name} feature.";

2022-01-19 18:53 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +                return null;
discussed offline

2022-01-19 19:46 UTC, rstam requested changes
A few minor questions and changes remaining.

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/WireVersion.cs
> +               !__knownWireVersions.Exists(w => w.WireVersion == maxWireVersion))
nit: indent in multiples of 4 spaces

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __createIndexesUsingInsertOperations = new Feature("CreateIndexesUsingInsertOperations", WireVersion.Zero, WireVersion.Server40);
Wouldn't 4.1.1 convert to `Server42`?

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __eval = new Feature("Eval", WireVersion.Zero, WireVersion.Server40);
Wouldn't 4.1.0 convert to `Server42`?

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __geoNearCommand = new Feature("GeoNearCommand", WireVersion.Zero, WireVersion.Server40);
Wouldn't 4.1.0 convert to `Server42`?

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __groupCommand = new Feature("GroupCommand", WireVersion.Zero, WireVersion.Server40);
Wouldn't 4.1.1 convert to `Server42`?

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __mmapV1StorageEngine = new Feature("MmapV1StorageEngine", WireVersion.Zero, WireVersion.Server40);
Wouldn't 4.1.0 convert to `Server42`?

2022-01-19 19:46 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/FeatureTests.cs
> +        [InlineData(/*maxWireVersion*/6, /*feature*/6, 7, /*isSupported*/true)]
I would discourage these types of comments. They are noisy and hard to maintain. For example, they don't even match the parameter names.

2022-01-19 19:46 UTC, rstam commented on tests/MongoDB.Driver.Tests/ReadPreferenceOnStandaloneTests.cs
> +                _ = client
This is odd... if we don't need the value why not remove lines 53-57?

2022-01-19 19:46 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerDescription.cs
>          /// The server version.
Maybe we should warn that only major and minor are known?

    /// Gets the approximate server version (only the major and minor version numbers are known).

2022-01-19 19:46 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndDeleteOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
`#pragma` is no longer necessary.

2022-01-19 19:46 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/FindOneAndReplaceOperationTests.cs
> +#pragma warning disable CS0618 // Type or member is obsolete
`#pragma` is no longer necessary.

2022-01-19 20:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __eval = new Feature("Eval", WireVersion.Zero, WireVersion.Server40);
no as I understand. This version is when we removed supporting. So versions higher than 4.1.0 (like 4.1.9) does support it. So the only way to ensure that we don't call a feature on the server that doesn't support it - is to round down

2022-01-19 20:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __eval = new Feature("Eval", WireVersion.Zero, WireVersion.Server40);
same for the rest of similar comments here

2022-01-19 20:09 UTC, rstam requested changes

2022-01-19 20:09 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __eval = new Feature("Eval", WireVersion.Zero, WireVersion.Server40);
I agree with your thinking, *except* that 4.1.0 is a *pre-release*.

This feature was removed in 4.2, *not* in 4.0.

2022-01-19 20:21 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __createIndexesUsingInsertOperations = new Feature("CreateIndexesUsingInsertOperations", WireVersion.Zero, WireVersion.Server40);
done

2022-01-19 20:21 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __eval = new Feature("Eval", WireVersion.Zero, WireVersion.Server40);
true, done

2022-01-19 20:21 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __geoNearCommand = new Feature("GeoNearCommand", WireVersion.Zero, WireVersion.Server40);
done

2022-01-19 20:21 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __groupCommand = new Feature("GroupCommand", WireVersion.Zero, WireVersion.Server40);
done

2022-01-19 20:21 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __mmapV1StorageEngine = new Feature("MmapV1StorageEngine", WireVersion.Zero, WireVersion.Server40);
done

2022-01-19 20:25 UTC, rstam approved these changes
LGTM

2022-01-19 20:52 UTC, JamesKovacs approved these changes
LGTM

2022-01-19 23:50 UTC, rstam requested changes

2022-01-19 23:50 UTC, rstam commented on src/MongoDB.Driver.Legacy/Communication/MongoServerInstance.cs
> -                    return BuildInfo.Version >= new Version(2, 4, 0);
Add after line 314:

    return true;

2022-01-19 23:50 UTC, rstam commented on src/MongoDB.Driver.Legacy/Communication/MongoServerInstance.cs
> -                    return BuildInfo.Version >= new Version(2, 6, 0);
Add after line 324:

    return true;

2022-01-19 23:55 UTC, rstam approved these changes
LGTM

2022-01-20 00:21 UTC, rstam reviewed
Questions.

2022-01-20 00:21 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterDescriptionTests.cs
> +                var wireVersionRange = wireRange == 0 ? new Range<int>(0, 0) : wireRange == 1 ? new Range<int>(6, 15) : null;
Are we going to have to change this test every time a new wire version is supported?

2022-01-20 00:21 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +            result.Should().Be(new Range<int>(6, 15));
Are we going to have to change this test every time a new wire version is supported?

2022-01-20 00:21 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/ClusterTests.cs
> +        [InlineData(16, 17, true)]
Are we going to have to change this test every time a new wire version is supported?

2022-01-20 00:21 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Servers/ServerDescriptionTests.cs
> +        [InlineData(new[] { 16, 17 }, false)]
Are we going to have to change this test every time a new wire version is supported?

2022-01-20 01:02 UTC, merged