CSHARP-3761: Reimplement SDAM to use a dedicated thread.
mongodb/mongo-csharp-driver pull request #722
Opened 2022-01-25 16:27 UTC by DmitryLukyanov

2022-01-25 16:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/ThreadHelper.cs
> +            Task.Delay(timeout, cancellationToken).Wait(cancellationToken);
originally we discussed a bit different solution like:
>cancellationToken.WaitHandle.WaitOne(20000);

but it triggers ObjectDisposedException instead of expected OperationCancelledException in case if cancellation is triggered. So I took another solution that was suggested by Robert

2022-01-25 17:49 UTC, rstam requested changes
Looks great. I only have a few minor comments.

2022-01-25 17:49 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                _serverMonitorThread.Start();
Handle `OperationCanceledException` the same way here that you do in `RountTripTimeMonitor`:

    public void Initialize()
    {
        if (_state.TryChange(State.Initial, State.Open))
        {
            _roundTripTimeMonitor.Start();

            _serverMonitorThread = new Thread(() => ThreadStart()) { IsBackground = true };
            _serverMonitorThread.Start();
        }

        void ThreadStart()
        {
            try
            {
                MonitorServer();
            }
            catch (OperationCanceledException)
            {
                // ignore OperationCanceledException
            }
        }
    }

2022-01-25 17:49 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3173Tests.cs
> +                });
You can get slightly simpler formatting if you declare the array type:

    var faultyConnectionResponses = new Queue<Action>(new Action[]
    {
        () => { /* no action needed*/ }, // the first hello or legacy hello configuration passes
        () => { /* no action needed*/ }, // RTT
        () => throw CreateDnsException(mockConnection.Object.ConnectionId), // the dns exception. Should be triggered after Invalidate
        () => WaitForTaskOrTimeout(hasClusterBeenDisposed.Task, TimeSpan.FromMinutes(1), "cluster dispose")
    });

2022-01-25 17:49 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                    newHeartbeatDelay.Wait(monitorCancellationToken);
Keep the comment?

    newHeartbeatDelay.Wait(monitorCancellationToken); // corresponds to wait method in spec

2022-01-25 18:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                _serverMonitorThread.Start();
it's not technically needed since we handle this in the monitor method itself, but I don't mind, done

2022-01-25 18:43 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                    newHeartbeatDelay.Wait(monitorCancellationToken);
done

2022-01-25 18:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Jira/CSharp3173Tests.cs
> +                });
done

2022-01-25 18:45 UTC, DmitryLukyanov commented
ready for review

2022-01-25 18:55 UTC, rstam approved these changes
LGTM

2022-01-26 00:41 UTC, JamesKovacs requested changes
Some very minor suggestions. Overall looks great! Your changes are very easy to follow and well thought-out.

2022-01-26 00:41 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +        public void Monitor()
public => private

2022-01-26 00:41 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +        private void MonitorServer()
Should this be `Monitor` to match the RTT impl? Or should the RTT impl be called `MonitorRoundTripTime`?

2022-01-26 00:41 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                                        "Unexpected exception in ServerMonitor.MonitorServer: {0}",
Change name in exception if you decide to change it above.

2022-01-26 00:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +        public void Monitor()
done

2022-01-26 00:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +        private void MonitorServer()
I think in both cases it should be named `MonitorServer`. The diff in these methods is represented in cs file name. Changed on `MonitorServer`

2022-01-26 00:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/ServerMonitor.cs
> +                                        "Unexpected exception in ServerMonitor.MonitorServer: {0}",
changed in RTT file

2022-01-26 00:58 UTC, DmitryLukyanov commented
ready for review

2022-01-26 01:02 UTC, JamesKovacs approved these changes
LGTM

2022-01-26 14:59 UTC, merged