CSHARP-3927: Drivers should check out an implicit session only after checking out a connection
mongodb/mongo-csharp-driver pull request #727
Opened 2022-02-10 20:50 UTC by BorisDog

2022-02-10 22:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/sessions/SessionsProseTests.cs
> +        public async Task Ensure_server_session_are_allocated_only_on_connection_checkout()
Prose test as described in the spec will not work with current implementation. Currently drivers will make their own judgment on the testing strategy.

2022-02-11 17:07 UTC, rstam requested changes
Overall looks good. Some changes requested.

2022-02-11 17:07 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +            ICoreServerSessionProvider serverSessionProvider,
The previous two parameters are mutually exclusive. Instead consider refactoring the constructors as follows so that only a `serverSession` or a `serverSessionPool` is provided:

    public CoreSession(
        ICluster cluster,
        ICoreServerSession serverSession,
        CoreSessionOptions options)
        : this(
            cluster: cluster,
            serverSession: new Lazy<ICoreServerSession>(() => serverSession, isThreadSafe: true),
            options: options)
    {
    }

    internal CoreSession(
        ICluster cluster,
        ICoreServerSessionPool serverSessionPool,
        CoreSessionOptions options)
        : this(
            cluster: cluster,
            serverSession: new Lazy<ICoreServerSession>(() => serverSessionPool.AcquireSession(), isThreadSafe: true),
            options: options)
    {
    }

    internal CoreSession(
        ICluster cluster,
        Lazy<ICoreServerSession> serverSession,
        CoreSessionOptions options)
    {
        _cluster = Ensure.IsNotNull(cluster, nameof(cluster));
        _serverSession = Ensure.IsNotNull(serverSession, nameof(serverSession));
        _options = Ensure.IsNotNull(options, nameof(options));
    }

NOTE: above assumes the recommendation to not introduce the new `ICoreSessionProvider` interface is accepted.

2022-02-11 17:07 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/ICoreServerSessionPool.cs
> +    internal interface ICoreServerSessionProvider
I don't see any value in splitting `ICoreServerSessionPool` into two.

I think we should leave this interface unchanged.

2022-02-11 17:07 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            var session = new CoreSession(this, null, _serverSessionPool, options);
After refactoring constructors to not have mutually exclusive parameters:

    var session = new CoreSession(this, _serverSessionPool, options);

2022-02-11 17:07 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
> +            var session = new CoreSession(this, null, _serverSessionPool, options);
After refactoring constructors to not have mutually exclusive parameters:

    var session = new CoreSession(this, _serverSessionPool, options);

2022-02-11 17:07 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +            CoreSessionOptions options) : this(
Formatting suggestion: we like to put the call to `this` on the following line.

Reasons:

1. It is logically separate from the parameter preceding it
2. Important things shouldn't be hidden near the end of the line

2022-02-11 19:03 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/ICoreServerSessionPool.cs
> +    internal interface ICoreServerSessionProvider
Yeah not sure what was the initial justification for splitting, reverted.

2022-02-11 19:03 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +            var session = new CoreSession(this, null, _serverSessionPool, options);
Done.

2022-02-11 19:04 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/LoadBalancedCluster.cs
> +            var session = new CoreSession(this, null, _serverSessionPool, options);
Done.

2022-02-11 19:09 UTC, BorisDog commented on src/MongoDB.Driver/ClientSessionHandle.cs
> +                if (_serverSession == null)
1. No, sessions are not thread safe in general.
2. Specifically `ServerSession` wrapper does not introduce additional state, so having multiple copies is safe.
3. General note: I could not find any usages of `ServerSession` in our code or Spec, so this property would be a candidate for removal.

2022-02-11 19:19 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/CoreSession.cs
> +            ICoreServerSessionProvider serverSessionProvider,
Good point, exposing mutually exclusive parameters even internally is not a good idea. Added additional private constructor.
Please note that `Lazy<ICoreServerSession>` will never be `null`, and the underlying objects are not validated in constructor. So the new private constructor still contains the both params, as I'd prefer to have all validations grouped together.

2022-02-14 22:51 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Bindings/ICoreServerSessionPool.cs
> -        // methods
Done.

2022-02-15 02:25 UTC, rstam approved these changes
LGTM

2022-02-15 23:36 UTC, merged