CSHARP-1541: Add support for $comment for profiling
mongodb/mongo-csharp-driver pull request #728
Opened 2022-02-21 22:22 UTC by BorisDog

[EG](https://spruce.mongodb.com/version/6213f18f5623435871e5c99)

Done together with [CSHARP-4043](https://jira.mongodb.org/browse/CSHARP-4043)
Follow up work in [CSHARP-4067](https://jira.mongodb.org/browse/CSHARP-4067)

2022-02-21 22:24 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
> +                    AssertValuesMatch(actualArray[i], expectedArray[i], isRoot: isRoot && !isRecursiveCall);
We need to allow "actual" documents in root array to have additional fields. [Spec](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.rst#allowing-extra-fields-in-root-level-documents).

2022-02-24 00:32 UTC, DmitryLukyanov requested changes

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateIndexesOperation.cs
> +        private BsonValue _comment;
Also, what about EndTransactionOperation (Abort/Commit). It's not main operation, but the same story is in `AggregateToCollection` where we added `$comment`

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateIndexesOperation.cs
> +        private BsonValue _comment;
Also what about getMore in cursors?

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +                { "comment", () => _comment, _comment != null },
let's not add delegate if it's not needed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListCollectionsOperation.cs
> +                { "comment", () => _comment, _comment != null },
`,` in the end

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListDatabasesOperation.cs
> +                { "comment", () => _comment, _comment != null }
let's not add delegate if it's not needed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListIndexesOperation.cs
> +        /// </summary>
`value` is missed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/ListIndexesUsingCommandOperation.cs
> +        /// </summary>
`value` is missed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryableWriteCommandOperationBase.cs
> +        /// </summary>
`value` is missed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver/CreateManyIndexesOptions.cs
> +        /// </summary>
`value` is missed

2022-02-24 00:32 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateIndexesOperation.cs
> +        private BsonValue _comment;
I see you've created follow-up ticket: https://jira.mongodb.org/browse/CSHARP-4067
However the list of operation looks not 100% the same with what I provided above
NOTE: I would say we don't need to add $comment for legacy operations like `GeoSearch` (or operation that is already deprecated). 
Also not sure what operation you mean by `Create`

2022-02-24 22:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateIndexesOperation.cs
> +        private BsonValue _comment;
`DropCollection, DropDatabase` - I didn't find this in the follow up ticket, did I miss it?

2022-02-24 22:53 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/CreateIndexesOperation.cs
> +        private BsonValue _comment;
You are right, missed that as well, added.

2022-02-25 00:12 UTC, DmitryLukyanov approved these changes
LGTM

2022-02-25 03:55 UTC, merged