CSHARP-3225: Implement SetWindowFields stage.
mongodb/mongo-csharp-driver pull request #731
Opened 2022-02-24 16:18 UTC by rstam

2022-03-01 22:00 UTC, JamesKovacs requested changes
Minor changes requested. Biggest question is whether the context data should be encapsulated in a `ContextData` class or left as an `IReadOnlyDictionary<string, object>`.

2022-03-01 22:00 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SetWindowFieldsMethodToAggregationExpressionTranslator.cs
> +        private static IBsonSerializer GetSortBySerializer(object sortBy, IBsonSerializer inputSerializer, BsonSerializerRegistry serializerRegistry)
Add a brief comment why we have to go through these conniptions to call the generic method to find the serializer.

2022-03-01 22:00 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> +                serializer = partitionSerializer.InputSerializer; // this is suspect
Why is this suspect? Is there a better or more correct way to find the serializer?

2022-03-01 22:00 UTC, JamesKovacs commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                (inputSerializer, sr, linqProvider) =>
What is `sr`? We try to avoid abbreviations like this.

2022-03-01 22:00 UTC, JamesKovacs commented on src/MongoDB.Driver/RangeWindow.cs
> +        public RangeWindow(RangeWindowBoundary lowerBoundary, RangeWindowBoundary upperBoundary)
`private` to ensure that instances are created through factory methods above?

2022-03-02 04:48 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/SetWindowFieldsMethodToAggregationExpressionTranslator.cs
> +        private static IBsonSerializer GetSortBySerializer(object sortBy, IBsonSerializer inputSerializer, BsonSerializerRegistry serializerRegistry)
Done

2022-03-02 16:56 UTC, JamesKovacs approved these changes
LGTM

2022-03-02 18:45 UTC, closed without merging