CSHARP-4048: "Take" doesn't work with GroupBy.
mongodb/mongo-csharp-driver pull request #740
Opened 2022-03-03 23:50 UTC by rstam

2022-03-03 23:52 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/TakeMethodToAggregationExpressionTranslator.cs
> +                var sourceTranslation = ExpressionToAggregationExpressionTranslator.TranslateEnumerable(context, sourceExpression);
Separate from this ticket I wonder if we should try to unify `Translate` and `TranslateEnumerable`.

It's just too easy to call `Translate` when we should call `TranslateEnumerable`

2022-03-03 23:52 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4048Tests.cs
> +            results[1].ToJson().Should().Be("{ \"_id\" : 2, \"Take\" : [{ \"_id\" : 2, \"X\" : 22 }] }");
There must be a better way to compare two objects when the class doesn't override `Equals`...

2022-03-04 04:20 UTC, rstam commented
`Take` might just be the tip of the iceberg.

I'm going to verify that *all* `IEnumerable` methods work with `IGrouping`.

2022-03-04 14:00 UTC, rstam commented
The very first `IEnumerable` method I checked (`Aggregate`) has the same issue. So probably most others do also.

2022-03-04 16:56 UTC, JamesKovacs requested changes
See requested changes.

2022-03-04 16:56 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4048Tests.cs
> +                .Select(x => new { Id = x.Key, Take = x.Take(1) });
We need to add `.OrderBy(x => x.Id);` as tests are failing about 25% of the time due to documents coming back in the opposite order.

2022-03-04 16:56 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4048Tests.cs
> +            };
Add `"{ $sort : { Id : 1 } }"` to match the added `OrderBy` clause.

2022-03-24 00:32 UTC, JamesKovacs approved these changes
LGTM.

2022-03-24 15:16 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4048Tests.cs
> +            };
Done

2022-03-24 18:45 UTC, closed without merging