CSHARP-3934: Do not error when parsing change stream event documents
mongodb/mongo-csharp-driver pull request #762
Opened 2022-04-05 21:58 UTC by BorisDog

CSHARP-4117: Change Stream event document missing "to" field for rename events

2022-04-06 15:17 UTC, DmitryLukyanov reviewed
question and then LGTM

2022-04-06 15:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentTests.cs
> +        public void CollectionNamespace_should_allow_extra_elements()
as I understand, CollectionNamespace can also be empty at least with dropDatabase, but it can be implemented in CSHARP-4130, I will rely on you here

2022-04-06 15:17 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/ChangeStreamOperationTypeSerializer.cs
> +                default: return (ChangeStreamOperationType)(-1);
do you know how this logic is implemented in other drivers? like in java, just curious

2022-04-06 15:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRenameCollectionOperation.cs
> +        private readonly string _newName;
alphabetical order?

2022-04-07 14:00 UTC, DmitryLukyanov requested changes

2022-04-07 16:51 UTC, rstam commented on src/MongoDB.Driver.Core/ChangeStreamDocument.cs
> +        public DatabaseNamespace DatabaseNamespace
This new property should be defined the same as the other properties in this `BsonDocumentBasedClass`:

    public DatabaseNamespace DatabaseNamespace => GetValue<DatabaseNamespace>(nameof(DatabaseNamespace), null);

2022-04-07 16:52 UTC, rstam commented on src/MongoDB.Driver.Core/ChangeStreamDocumentCollectionNamespaceSerializer.cs
> +                }
Normally I would have preferred this check to be done on a per-field level (since in general each field might be a different type and it's only a coincidence that in this case they are all strings).

But doing it this way does save a few lines of code.

2022-04-08 19:02 UTC, BorisDog commented on src/MongoDB.Driver.Core/ChangeStreamDocumentCollectionNamespaceSerializer.cs
> +                }
I agree, wrote this a bit differently, keeping the original count of loc :)

2022-04-11 15:03 UTC, DmitryLukyanov approved these changes
LGTM

2022-04-11 17:36 UTC, rstam approved these changes
Except for a very minor nit LGTM.

2022-04-11 17:36 UTC, rstam commented on src/MongoDB.Driver.Core/ChangeStreamDocumentCollectionNamespaceSerializer.cs
> +                    case "db" when reader.CurrentBsonType == BsonType.String:
This is nice.

2022-04-11 17:36 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/ChangeStreamDocumentTests.cs
> +        [InlineData("{ db: { x : 1 } }")]
Minor nit, our convention is to have a space around `:`

        [InlineData("{ }")]
        [InlineData("{ other : 1 }")]
        [InlineData("{ db : { x : 1 } }")]

2022-04-11 20:04 UTC, merged