CSHARP-1950: Allow string or regular expressions in values for $in with string.
mongodb/mongo-csharp-driver pull request #773
Opened 2022-04-19 23:05 UTC by rstam

2022-04-19 23:16 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +        public FilterDefinition<TDocument> AnyStringIn(FieldDefinition<TDocument, IEnumerable<string>> field, IEnumerable<StringOrRegularExpression> values)
This is like `AnyIn` except that `field` is `FieldDefinition<TDocument, IEnumerable<string>>` instead of `FieldDefinition<TDocument, IEnumerable<TItem>>` and `values` is `IEnumerable<StringOrRegularExpression>` instead of `IEnumerable<TItem>`.

Similarly for other new methods below.

2022-04-19 23:16 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +    internal abstract class StringInOrNinFilterDefinition<TDocument, TField> : FilterDefinition<TDocument>
This is different from a regular `$in` (or `$nin`) in that `values` is `IEnumerable<StringOrRegularExpression>` instead of `IEnumerable<string>`.

2022-04-19 23:16 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +                    if (value?.Type == typeof(BsonRegularExpression))
Serialize `BsonRegularExpression` as a `BsonRegularExpression`. Do *not* convert to `string`.

2022-04-19 23:16 UTC, rstam commented on src/MongoDB.Driver/StringOrRegularExpression.cs
> +    public class StringOrRegularExpression
I searched for general purpose discriminated unions and found some stuff but in the end I don't want a dependency on any third party Nuget package for this.

This is similar to what some examples on the web might call `OneOf<string, BsonRegularExpression>`.

2022-04-20 22:20 UTC, JamesKovacs requested changes
This works in `Builders<T>`, but is not supported in LINQ. For example, the following results in a compile error:
```
var query = coll.AsQueryable().Where(x => x.Name.In(new StringOrRegularExpression[] {new Regex("^start"), "A"}));
```
And `x.Name.StringIn` doesn't exist as a string extension method.

It would be ideal if we supported params-style syntax, but that would be a departure from the method signature for `In`:

```
var query = coll.AsQueryable().Where(x => x.Name.StringIn(new Regex("^start"), "A"));
```

2022-04-20 22:20 UTC, JamesKovacs commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +        public FilterDefinition<TDocument> AnyStringIn(FieldDefinition<TDocument, IEnumerable<string>> field, IEnumerable<StringOrRegularExpression> values)
One slight annoyance I found is that common use cases such as only using only string or only regex arguments requires the use of `new StringOrRegularExpression[] { }`. Changing the type signature to:

`public FilterDefinition<TDocument> AnyStringIn(FieldDefinition<TDocument, IEnumerable<string>> field, params StringOrRegularExpression[] values)`

allows us to call the method like this:
`var builder = Builders<C>.Filter.StringIn(x => x.Name, "A", "B");`
-- or --
`var builder = Builders<C>.Filter.StringIn(x => x.Name, new Regex("^start"), new Regex("end$"));`

The disadvantage of this technique is it breaks from the way `In` is defined:
`public FilterDefinition<TDocument> In<TField>(FieldDefinition<TDocument, TField> field, IEnumerable<TField> values)`

What do you think?

2022-05-19 04:15 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/StringSerializer.cs
> +        public static StringSerializer Instance => __instance;
This cached instance allows us to avoid creating a new one every time we need one.

2022-05-19 04:15 UTC, rstam commented on src/MongoDB.Driver/FilterDefinitionBuilder.cs
> +        public FilterDefinition<TDocument> AnyStringIn(FieldDefinition<TDocument, IEnumerable<string>> field, IEnumerable<StringOrRegularExpression> values)
Added `params` overloads.

2022-05-19 04:15 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToFilterTranslators/MethodTranslators/StringInOrNinMethodToFilterTranslator.cs
> +        public static AstFilter Translate(TranslationContext context, MethodCallExpression expression)
This is the implementation of the new LINQ support for $in and $nin.

2022-05-19 04:15 UTC, rstam commented on src/MongoDB.Driver/Linq/StringExtensions.cs
> +        public static bool AnyStringIn(this IEnumerable<string> s, IEnumerable<StringOrRegularExpression> values)
These are the new string extension methods used to support $in and $nin in LINQ.

2022-05-19 04:15 UTC, rstam commented on tests/MongoDB.Driver.Tests/Jira/CSharp1950BuilderTests.cs
> +                "a1", "a2");
The arguments to Assert are:

1. the filter to test
2. the expected rendered filter
3. the expected results (third argument omitted if no results expected)

All tests do the same thing, with the exception of the filter and the expected results. All the logic common to all tests is in the Assert helper method.

2022-05-19 04:15 UTC, rstam commented on tests/MongoDB.Driver.Tests/Jira/CSharp1950LinqTests.cs
> +                "a1", "a2");
The three arguments to Assert are:

1. the queryable to test
2. the expected pipeline stage
3. the expected results (third argument is omitted if no results are expected)

2022-05-19 04:15 UTC, rstam commented on tests/MongoDB.Driver.Tests/Jira/CSharp1950LinqTests.cs
> +                queryable => queryable.Where(x => x.S.StringIn()),
The tests in this file test the newly added LINQ support for $in and $nin you requested.

So this is a good file to see what the public API for $in and $nin in LINQ looks like.

2022-05-19 22:34 UTC, JamesKovacs approved these changes
LGTM

2022-05-26 23:19 UTC, merged