CSHARP-3140: PartialEvaluator should not evaluate unnecessary clauses for AndAlso, Conditional and OrElse
mongodb/mongo-csharp-driver pull request #775
Opened 2022-04-20 17:49 UTC by rstam

2022-04-20 22:43 UTC, JamesKovacs approved these changes
LGTM

2022-04-21 02:01 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/PartialEvaluator.cs
> +                return node.Update(test, Visit(node.IfTrue), Visit(node.IfFalse));
Minor optimization that prevents double visitation of test.

2022-04-21 02:01 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +        public void AndAlso_with_neither_clause_a_constant_should_work()
New test.

2022-04-21 02:01 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +        public void Conditional_with_test_that_is_not_a_constant_should_work()
New test.

2022-04-21 02:01 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +        public void OrElse_with_neither_clause_a_constant_should_work()
New test.

2022-04-21 16:26 UTC, JamesKovacs requested changes
Minor changes requested.

2022-04-21 18:40 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +            var currentUser = new User { Id = 1, Factory = null };
Done

2022-04-21 18:40 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +            var currentUser = new User { Id = 1, Factory = new Factory { Id = 1 } };
Done

2022-04-21 18:40 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3140Tests.cs
> +            var currentUser = new User { Id = 1, Factory = null };
Done

2022-04-25 21:21 UTC, JamesKovacs approved these changes
LGTM

2022-04-25 22:01 UTC, merged