CSHARP-4127: Language specific examples for AWS Lambda.
mongodb/mongo-csharp-driver pull request #779
Opened 2022-04-25 16:25 UTC by DmitryLukyanov

2022-04-25 18:41 UTC, JamesKovacs requested changes
See comment on DRIVERS-2018. We need to expand our example slightly to include some minimal CRUD operations otherwise we aren't guaranteed to be successfully talking to a server. We might have just established connection pool, but not successfully connected to a cluster from AWS Lambda.

https://jira.mongodb.org/browse/DRIVERS-2018?focusedCommentId=4504303&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4504303

2022-04-26 14:39 UTC, DmitryLukyanov commented
it was decided to use `find` instead listdatabases.

2022-04-26 18:26 UTC, JamesKovacs requested changes
Minor change requested.

2022-04-26 18:26 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string password = Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY");
Password should be stored in a `SecureString`.

2022-04-26 18:26 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +                new MongoCredential("MONGODB-AWS", new MongoExternalIdentity(username), new PasswordEvidence(password))
`PasswordEvidence` has a ctor that accepts a `SecureString`.

2022-04-26 20:36 UTC, JamesKovacs commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string password = Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY");
Microsoft is no longer recommending the use of `SecureString`.
https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=net-6.0
And this rule:
https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md

Let's skip the use of `SecureString` that I initially suggested and keep the example easier to follow as you have it.

2022-04-26 20:36 UTC, JamesKovacs approved these changes
LGTM

2022-04-28 00:34 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
Is it guaranteed that the ctor will be called once/not concurrently?
Or should it be `static ShareMongoClientLambdaHandler` ?

2022-04-28 00:34 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string username = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID");
Are environment variables part of the Aws Lambda auth process?
If not, maybe for simplicity just use dummy values: `var username = "<username>"`

2022-04-28 00:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
Recommended way I found was about regular ctor, see for example here https://blog.steadycoding.com/using-singletons-in-net-core-in-aws-lambda/. The note what I didn't mention before, that there are 2 modes for AWS Lambda called "Cold" and "Warm" start ("Hot is a bit different): https://medium.com/@danielmanchev/cold-warm-and-hot-start-in-aws-lambda-bc8d64f28575. So the actually reused instance will be only after `warm` start. Each `Cold` start will create new instance of lambda handler

2022-04-28 00:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string username = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID");
it's not specified in our envs, but I saw it in other examples exactly in this form, so I would leave it as here

2022-04-28 00:51 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string username = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID");
In this case if it's not required, wondering if `Environment.GetEnvironmentVariable` adds any additional value for the sample. Maybe we'd better keep it as simple as possible...

2022-04-28 01:02 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
From the first glance I fail to see the reason for initializing a static property in regular ctor. Do we know why is this the recommended way, and is it AWS recommendation as well?
In [AWS .Net samples](https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/ec2-spot/src/ec2spot/Function.cs) static ctors are used.
Probably we'd need to look deeper into this.

2022-05-09 13:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
As far as I understand, both ways can be used. This is what created by VS "Simple S3 function" project:
![image](https://user-images.githubusercontent.com/44870738/167421250-d6d795d4-ad55-4f97-8052-65ddaf7bf36a.png)

2022-05-09 23:36 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
Yes, note that `S3Client` in this case is not static. The initialization of a static field in non-static constructor is what puzzles me, but this does not mean it's not working though. I think we have to be able to explain such unusual combination, or follow the official samples.

2022-05-09 23:36 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string username = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID");
Looks like it's only one of the options, used in case of "build agent process", not sure what it is :)
Also I don't think we should prioritize simplifying the usage of this code in our driver.

Not a big issue, I just think it introduces some "noise" to the sample, and not sure we got any use for it.

2022-05-09 23:36 UTC, BorisDog commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +        public string HandleRequest(ILambdaContext context)
In all samples a came across, I see additional `inputType` parameter in Handler function:
https://docs.aws.amazon.com/lambda/latest/dg/csharp-handler.html

Can it be omitted, and do you happen to have some official sample without it?

2022-05-09 23:51 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +        public string HandleRequest(ILambdaContext context)
it can be omitted

2022-05-09 23:52 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
it's true, I forgot that suggested MongoClient is static. I think it can work in any way, but I will look at this one more time :(

2022-05-09 23:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +        public string HandleRequest(ILambdaContext context)
>to have some official sample without it?

I just saw that it works without this argument

2022-05-17 15:20 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
I think it's fine to take what is suggested in the VS templates (ie official place). So I removed static modifier

2022-05-17 15:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            string username = Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID");
At the very least these variables present in the examples that we needed to mimic: https://www.mongodb.com/docs/atlas/manage-connections-aws-lambda/. So I think we even have no way to not set it

2022-05-17 15:32 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Examples/AwsLambda/AwsLambdaExamples.cs
> +            MongoClient = CreateMongoClient();
I asked this in this issue just in case https://github.com/awsdocs/aws-lambda-developer-guide/issues/360

2022-06-16 23:17 UTC, BorisDog approved these changes
LGTM

2022-06-16 23:19 UTC, merged