CSHARP-3915: Implement Densify builder and LINQ methods.
mongodb/mongo-csharp-driver pull request #786
Opened 2022-05-01 01:03 UTC by rstam

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/AggregateFluent.cs
> +            params FieldDefinition<TResult>[] partitionByFields)
AFAIK it's good practice to provide general purpose IEnumerable version and also the params version.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/DensifyRange.cs
> +    public abstract class DensifyRange
All the classes in this file need to be carefully reviewed for naming and usage. They are public API.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/LambdaExpressionExtensions.cs
> +
The above changes are to support fields defined using `Expression<Func<TDocument, object>>` instead of `Expression<Func<TDocument, TField>>`.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +            return Densify(source, field, range, partitionByFields?.ToArray());
Normally the params version would delegate to the IEnumerable version, but in this case it was easier to go in the other direction.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +            }
How to quote an array of expressions looks easy now that I've figured it out, but figuring it out was quite hard. There are NO standard LINQ methods that have a list of Expressions that need to be quoted so there was no existing code that I could find to model this after.

The key here  is `NewArrayInit`, and the special case for `null`.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +        }
These are just like the existing methods above but for more parameters.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                    return new RenderedPipelineStageDefinition<TInput>(operatorName, document, s);
The above is where a builder based $densify stage bets build.

The LINQ version of Densify is handled in the LINQ translator.

2022-05-01 01:12 UTC, rstam commented on tests/MongoDB.Driver.Tests/Jira/CSharp3915Tests.cs
> +                    range: DensifyRange.Numeric(DensifyBounds.Full, step: 200),
Note the use of `DensifyBounds.Full` as the public API for the "full" bounds.

2022-05-01 01:12 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +            IEnumerable<Expression<Func<TResult, object>>> partitionByFields = null)
This has to be `Expression<Func<TResult, object>>` because each field is of a different type.

2022-05-03 00:52 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public static Feature DensifyStage => __densifyStage;
We've also often used a more verbose convention that would have resulted in this feature being named `AggregateDensifyStage`. Not sure whether it's worth using the longer name (all stages are aggregate sub-features).

2022-05-03 19:46 UTC, JamesKovacs requested changes
Minor changes and discussion requested.

2022-05-03 19:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        public static Feature DensifyStage => __densifyStage;
I don't think there is any ambiguity around `DensifyStage`. There isn't a need to prefix it with "aggregate".

2022-05-03 19:46 UTC, JamesKovacs commented on src/MongoDB.Driver/DensifyRange.cs
> +    public abstract class DensifyRange
I overall like the naming. It is clear and concise.

My only hesitation is that we are encountering a proliferation of of time-related enumerations:
- `DensifyDateTimeUnit`
- `TimeSeriesGranularity`
- `DateTimeUnit` <-- Smart enum, not simple enum
- `TimeSpanUnits`

Unfortunately while there is overlap in the enumeration value names, there isn't a one-to-one correspondence between them. Each server function has a different set of valid enumeration values. We will have to maintain separate though similar enumerations so that we can provide accurate Intellisense and avoid  allowing users to call server functions with invalid enumeration values.

The only thing I'm left scratching my head over is `DensifyDateTimeUnit` versus `DateTimeUnit`. Those two enumerations are very different but the naming suggests otherwise. Should we rename `DensifyDateTimeUnit` to `DensifyTimeUnit` to better match the `$densify` server documentation? Though I do like `DensifyDateTimeUnit` since the enumeration contains values related to time (millisecond, second, minute, hour) as well as dates (week, month, etc.). Throwing this out there for discussion.

2022-05-04 20:42 UTC, rstam commented on src/MongoDB.Driver/DensifyRange.cs
> +    public abstract class DensifyRange
I also was concerned about the potential duplication between enum types, but as you pointed out they don't all align perfectly so we seem to have no choice but to have different unique enums.

2022-05-04 20:42 UTC, rstam commented on src/MongoDB.Driver/DensifyRange.cs
> +                    break;
Int64 definitely feels like an omission.

The unsigned types don't exist server-side. Do we want to support then anyway?

2022-05-04 20:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Stages/AstDensifyStage.cs
> +            _partitionByFieldPaths = partitionByFieldPaths == null ? null : partitionByFieldPaths.AsReadOnlyList();
True. Will change in next commit.

2022-05-04 20:42 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                //(s, sr, linqProvider) => new RenderedPipelineStageDefinition<TInput>(operatorName, new BsonDocument(operatorName, filter.Render(s, sr, linqProvider)), s));
Oops. It is. Will remove in next commit.

2022-05-12 22:37 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +            }
Looking at this code today I'm wondering if `NewArrayInit` is really the right thing to do here.

I can't think of anything else that's better, but this is uncharted territory (because we're quoting multiple expressions).

2022-05-12 23:03 UTC, JamesKovacs approved these changes
LGTM

2022-05-12 23:03 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +            }
Seems reasonable to me though you've thought about it more deeply than I have. I can't think of a reason why it would be problematic. Let's run with it until we find a problem. Hopefully we never do.

2022-05-13 01:11 UTC, closed without merging