CSHARP-4095: Use count command for estimatedDocumentCount.
mongodb/mongo-csharp-driver pull request #789
Opened 2022-05-04 23:48 UTC by JamesKovacs

Mostly straightforward PR. Comments inline below.

2022-05-04 23:57 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> -
Although this is part of the public API, I am removing it entirely since under no conditions is `EstimatedDocumentCount` implemented using `collStats`. If we left this in place, there is no `WireVersion` we could use to represent a feature that is no longer implemented, nor ever will be.

2022-05-04 23:57 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +
We missed adding comment support to `EstimatedDocumentCount`. We now have a spec test that uses this and thus I had to add support.

2022-05-04 23:57 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
> +                    }
Not sure there is a better way to skip spec tests for a ticket that we haven't implemented yet. I'm open to better suggestions if you have any.

2022-05-04 23:57 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/tests/README.rst
> +in the `unified test format <../../unified-test-format/unified-test-format.rst>`_
All the `README.rst` and JSON/YAML changes in Specifications are a direct sync with the relevant directories in the specs repo.

2022-05-05 21:45 UTC, JamesKovacs commented
Found out why `CSHARP-4095` was failing on pre-5.0 servers. We have a new spec test (`crud.tests.unified.replaceOne-dots_and_dollars.json_Unacknowledged_write_using_dollar-prefixed_or_dotted_keys_may_be_silently_rejected_on_pre-5.0_server`) that only runs on pre-5.0 servers that executes an unacknowledged `replaceOne`. Our test code tries to convert the `ReplaceOneResult.Unacknowledged` object to an `OperationResult` but it fails when accessing the properties because it is unacknowledged. Looks like previous spec tests have only dealt with `ReplaceOneResult.Acknowledged` where accessing those properties is valid. The latest commit fixes this spec test conversion bug.

Also worth noting that this PR resolves `CSHARP-4094: Add 'comment' option to EstimatedDocumentCountOptions`. I noticed that these new spec tests were failing and didn't realize there was a separate ticket for this feature. We can discuss whether it is worth breaking this PR apart into two separate features.

2022-05-05 23:41 UTC, BorisDog requested changes

2022-05-05 23:41 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
>  using MongoDB.Driver.Core.Clusters;
Need to add simple comment tests, like:
[Comment_get_and_set_should_work](https://github.com/mongodb/mongo-csharp-driver/blob/7308368ff2235d3166ff3b1748be9ec3e6e546b0/tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs#L190)
[CreateCommand_should_return_expected_result_when_Comment_is_set](https://github.com/mongodb/mongo-csharp-driver/blob/7308368ff2235d3166ff3b1748be9ec3e6e546b0/tests/MongoDB.Driver.Core.Tests/Core/Operations/AggregateOperationTests.cs#L405)

2022-05-05 23:41 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
> +                    }
Maybe it would be easier/cleaner to cherry-pick just the relevant spec tests to CS4095?

2022-05-05 23:41 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/bulkWrite-comment.yml
> +                    multi: { $$unsetOrMatches: false }
Note: this addresses also https://jira.mongodb.org/browse/CSHARP-4134 changes.

2022-05-06 22:04 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                return await operation.ExecuteAsync(context, cancellationToken).ConfigureAwait(false);
Good point.

2022-05-07 15:12 UTC, alexmurari commented on src/MongoDB.Driver.Core/Core/Operations/EstimatedDocumentCountOperation.cs
> +                return await operation.ExecuteAsync(context, cancellationToken).ConfigureAwait(false);
`context` instance is in an `using` block, returning the incomplete `operation.ExecuteAsync` task by omitting `async/await` keywords would make `context` be disposed of prior to the execution of the task.

1. Disposes `context` by exiting the `using` block.
2. Returns the incomplete task from `operation.ExecuteAsync(context, cancellationToken)`

2022-05-09 19:36 UTC, JamesKovacs commented
Split CSHARP-4094 changes into its own PR #792.

2022-05-09 23:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/tests/unified/bulkWrite-comment.yml
> +                    multi: { $$unsetOrMatches: false }
Thanks for finding this. I'll close out CSHARP-4134 once I merge this PR.

2022-05-09 23:19 UTC, JamesKovacs commented
I had to force push the latest changes since I rebased on CSHARP-4094, which was split from this PR.

2022-05-09 23:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
>  using MongoDB.Driver.Core.Clusters;
Added in the 4094 PR that was split from this work.

2022-05-09 23:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/EstimatedDocumentCountOperationTests.cs
>  using MongoDB.Driver.Core.TestHelpers.XunitExtensions;
Added in 4094 PR.

2022-05-09 23:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/crud/CrudUnifiedTestRunner.cs
> +                    }
I removed the `-hint-unacknowledged` spec tests from the commit rather than ignoring them in code. I've remove the above skip code. Those spec tests can be added back when we implement CSHARP-3791.

2022-05-10 19:14 UTC, BorisDog approved these changes
LGTM

2022-05-10 20:16 UTC, merged