CSHARP-4149: Add FLE 2 behavior for CreateCollection() and Collection.Drop().
mongodb/mongo-csharp-driver pull request #790
Opened 2022-05-05 15:16 UTC by DmitryLukyanov

2022-05-05 15:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +        /// Supplying an encryptedFieldsMap provides more security than relying on an encryptedFields obtained from the server. It protects against a malicious server advertising a false encryptedFie
this xml comment is required in the spec

2022-05-05 15:23 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +        private async Task<IWriteOperation<BsonDocument>> CreateDropCollectionOperationAsync(string name, DropCollectionOptions options, IClientSessionHandle session, CancellationToken cancellationTo
it's unfortunate that creating collection step require calling a server, so now we need to have 2 versions of this method: sync and async

2022-05-09 18:04 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
minor: I think it's more "correct" and in some sense more safer, to execute tasks in tests via regular await pattern.
```
var resultedException = async
                ? await Record.ExceptionAsync(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None))
                : Record.Exception(() => subject.Execute(Mock.Of<IWriteBinding>(), CancellationToken.None));
```
That being said, functionally this does not matter a lot in this specific case, but still we might want to prefer this approach by default.

2022-05-09 18:19 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/AutoEncryptionOptionsTests.cs
> +        public void constructor_should_handle_schemaMap_and_encryptedFieldsMap_type_correctly(string schemaMapKey, string encryptedFieldsMapKey, string errorMessage, bool shouldFail)
minor: `shouldFail` parameter can be skipped, having just `errorMessage`

2022-05-09 18:31 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                        foreach (var encryptedFieldsMapElement in encryptedFieldsMapDocument.Elements)
minor, for your consideration:
```
var encryptedFieldsMapDocument = option.Value.AsBsonDocument;
var encryptedFieldsMap = encryptedFieldsMapDocument.Elements.ToDictionary(e => e.Name, e => e.Value.AsBsonDocument);
```

2022-05-09 18:32 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                        autoEncryptionOptions = autoEncryptionOptions.With(encryptedFieldsMap:encryptedFieldsMap);
minor: space around `:`

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +        internal CreateCollectionOperation(
I think we agreed that we can change majority of classed in the Core that are not supposed to be used by users - this class is definitely not supposed. But I think I will revert this change. The idea behind here that initially I had implementation without CompositeOperation and it required few constructors

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/DropCollectionOperation.cs
> +        private BsonDocument _encryptedFields;
for operation itself - nope, but we pass it to the factory method. It would be good to have ability to see what values was provided to the class via a property

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +        /// Supplying an encryptedFieldsMap provides more security than relying on an encryptedFields obtained from the server. It protects against a malicious server advertising a false encryptedFie
We don't use `value` for a new classes only for old that already have it. As I know we planned to remove this tag in 3.0.
`remarks` sounds good to me

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseBase.cs
>          public abstract Task DropCollectionAsync(string name, CancellationToken cancellationToken = default(CancellationToken));
the idea is to avoid BCs, not sure how healthy is this idea nowadays :) In 2 words, in past we expected that someone can inherit his classes from MongoCollectionBase class, so first methods in this class were abstract, but then to allow users compile their code after upgrading driver reference, we started to add new methods as virtual, they could still not use new methods, but at least they would not need to implement their bodies immediately

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                createCollectionOperationConfigurator: ccp =>
typo, will fix

2022-05-09 19:19 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
yes and if the condition in line 749 false

2022-05-09 19:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
it will require making test async. It's not big deal I think, but since almost all our code is written differently, not sure whether I want to start using it now, but I don't have strong opinion here, just consistency to the most of our code base

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Encryption/EncryptedCollectionHelper.cs
> +        private static BsonDocument __additionalCreateIndexDocument = new BsonDocument("__safeContent__", 1);
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CompositeWriteOperation.cs
> +    internal class CompositeWriteOperation<TResult> : IWriteOperation<TResult>
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CompositeWriteOperation.cs
> +        public async Task<TResult> ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +        /// <param name="encryptedFields">The encrypted feilds.</param>
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +        internal CreateCollectionOperation(
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/DropCollectionOperation.cs
> +                => new DropCollectionOperation(new CollectionNamespace(collectionNamespace.DatabaseNamespace.DatabaseName, collectionName.ToString()), messageEncoderSettings);
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +        /// Supplying an encryptedFieldsMap provides more security than relying on an encryptedFields obtained from the server. It protects against a malicious server advertising a false encryptedFie
I see that we use `value` here, so will add this too, done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            UsingImplicitSession(session => DropCollection(session, name, options: options, cancellationToken), cancellationToken);
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                createCollectionOperationConfigurator: ccp =>
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AutoEncryptionOptionsTests.cs
> +        public void constructor_should_handle_schemaMap_and_encryptedFieldsMap_type_correctly(string schemaMapKey, string encryptedFieldsMapKey, string errorMessage, bool shouldFail)
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AutoEncryptionOptionsTests.cs
> +                    foreach (var keyItem in key.Split(';'))
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/AutoEncryptionOptionsTests.cs
> +                return null;
It was something for a test part that no longer exists, removed

2022-05-09 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                        foreach (var encryptedFieldsMapElement in encryptedFieldsMapDocument.Elements)
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> +                        autoEncryptionOptions = autoEncryptionOptions.With(encryptedFieldsMap:encryptedFieldsMap);
done

2022-05-09 19:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Encryption/EncryptedCollectionHelper.cs
> +            if (joined.Count > 0)
done

2022-05-09 20:38 UTC, BorisDog commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
So should we check for `(autoEncryptionOptions.EncryptedFieldsMap != null)` instead?

2022-05-09 20:38 UTC, BorisDog commented on src/MongoDB.Driver/MongoDatabaseBase.cs
>          public abstract Task DropCollectionAsync(string name, CancellationToken cancellationToken = default(CancellationToken));
I see, it's a good point. BC here would also break Analyzer.

2022-05-09 20:38 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
Yes it will, we got lots of tests returning `Task` now. And I think the new tests that use tasks should be written with the usual TPL approach.
Not a big deal in this case at all, for your consideration.

2022-05-09 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Operations/DropCollectionOperation.cs
> +        private BsonDocument _encryptedFields;
Not sure that we should store non-used data.  Also it's a public class, and it would be harder to change our mind here.
Maybe `internal` if you find it useful in some cases? Relying on you here.

2022-05-09 20:45 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
I misread spec, I saw it required exactly this condition, but I see that it doesn't: https://github.com/mongodb/specifications/pull/1183/files#diff-de01d398114f63480af23798e09ffca599aa758efd04f15a9beec89b4566041bR679. So yeah, it should be `autoEncryptionOptions.EncryptedFieldsMap != null`. Will change it

2022-05-09 21:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/DropCollectionOperation.cs
> +        private BsonDocument _encryptedFields;
From consumer's for this class POV, this field is used. We don't send this to the server, but we provide it to a factory method that is almost like ctor in this meaning. I'm ok to make it internal

2022-05-09 21:05 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
I think to say that we will use it for all new tests further, we need to agree that we're ok to change implementation (on tasks) for a lot of old tests. Not sure that we're ok with this at this point, so I would probably not apply this suggestion at least for now

2022-05-09 21:18 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
done

2022-05-09 22:32 UTC, BorisDog approved these changes
LGTM, two minor comments for you considerations.

2022-05-09 22:32 UTC, BorisDog commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
minor: I'd combine the two conditions into single statement.

2022-05-09 22:32 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
Not sure that it's crucial to change all the old tests. But lots of new new tests are definitely using the usual TPL oriented approach.

2022-05-11 17:51 UTC, rstam requested changes

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            _ = EncryptedCollectionHelper.TryGetEffectiveEncryptedFields(collectionNamespace, options.EncryptedFields, _client.Settings?.AutoEncryptionOptions?.EncryptedFieldsMap, out var effectiveEn
How can you ignore the return value? What if `TryGetEffectiveEncryptedFields` returns `false`?

2022-05-11 17:51 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
I think the only reason OLD tests don't return Task is that when they were written xUnit did not yet support that.

And there was probably some period of time between when xUnit started supporting async tests and when we became aware of it and started using that.

I think it's fine to use async tests going forward. No need to change old tests. Perhaps if we work on on old tests for some reason we can change them little by little.

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            UsingImplicitSession(session => DropCollection(session, name, options: null, cancellationToken), cancellationToken);
I would avoid duplicating even small amounts of logic. Simply provide the default value for the missing parameter and delegate to the next method:

    DropCollection(name, options: null, cancellationToken);

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            return UsingImplicitSessionAsync(session => DropCollectionAsync(session, name, options: null, cancellationToken), cancellationToken);
Same here, avoid duplicating even the smallest amount of logic:

    return DropCollectionAsync(name, options: null, cancellationToken);

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            _ = EncryptedCollectionHelper.TryGetEffectiveEncryptedFields(collectionNamespace, options.EncryptedFields, _client.Settings?.AutoEncryptionOptions?.EncryptedFieldsMap, out var effectiveEn
This "looks" like a bug. Consider a new helper method instead:

    var effectiveEncryptedFields = EncryptedCollectionHelper.GetEffectiveEncryptedFields(collectionNamespace, options.EncryptedFields, _client.Settings?.AutoEncryptionOptions?.EncryptedFieldsMap);

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                messageEncoderSettings.Add(MessageEncoderSettingsName.GuidRepresentation, withEncryption ? GuidRepresentation.Unspecified : _settings.GuidRepresentation);
I don't think you need a `withEncryption` parameter at all, you can just do:

    messageEncoderSettings.Add(MessageEncoderSettingsName.GuidRepresentation, GuidRepresentation.Unspecified);

whether encryption is configured or not.

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Encryption/EncryptedCollectionHelper.cs
> +        }
I found the logic of the above method somewhat confusing and it took me a long time to convince myself that it could be correct. I think the following refactoring expresses the intent more clearly:

    public static bool TryGetEffectiveEncryptedFields(CollectionNamespace collectionNamespace, BsonDocument encryptedFields, IReadOnlyDictionary<string, BsonDocument> encryptedFieldsMap, out BsonDocument effectiveEncryptedFields)
    {
        if (encryptedFields != null)
        {
            effectiveEncryptedFields = encryptedFields;
            return true;
        }

        if (encryptedFieldsMap != null)
        {
            return encryptedFieldsMap.TryGetValue(collectionNamespace.ToString(), out effectiveEncryptedFields);
        }

        effectiveEncryptedFields = null;
        return false;
    }

What do you think?

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            _ = EncryptedCollectionHelper.TryGetEffectiveEncryptedFields(collectionNamespace, options.EncryptedFields, _client.Settings?.AutoEncryptionOptions?.EncryptedFieldsMap, out var effectiveEn
The new helper method could be:

    public static BsonDocument GetEffectiveEncryptedFields(CollectionNamespace collectionNamespace, BsonDocument encryptedFields, IReadOnlyDictionary<string, BsonDocument> encryptedFieldsMap)
    {
        if (TryGetEffectiveEncryptedFields(collectionNamespace, encryptedFields, encryptedFieldsMap, out var effectiveEncryptedFields))
        {
            return effectiveEncryptedFields;
        }
        else
        {
            return null;
        }
    }

I realize there's a bit of redundancy in this proposed helper method but it's very clear and doesn't rely on any side effects of the `TryGetEffectiveEncryptedFields` method.

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +                    (mainOperation, true),
Suggestion:

    (mainOperation, IsMainOperation: true),

2022-05-11 17:51 UTC, rstam commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                messageEncoderSettings.Add(MessageEncoderSettingsName.GuidRepresentation, withEncryption ? GuidRepresentation.Unspecified : _settings.GuidRepresentation);
And it is correct to only do this when `GuidRepresentationMode` is `V2`.

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/CreateCollectionOperation.cs
> +                    (mainOperation, true),
done

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            _ = EncryptedCollectionHelper.TryGetEffectiveEncryptedFields(collectionNamespace, options.EncryptedFields, _client.Settings?.AutoEncryptionOptions?.EncryptedFieldsMap, out var effectiveEn
done

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                    var listCollectionOptions = new ListCollectionsOptions() { Filter = $"{{ name : '{collectionNamespace.CollectionName}' }}" };
this line is already quite long with configureawait, not a big deal, but I would probably leave it as is

2022-05-11 21:31 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
then, let it be so :)

2022-05-11 21:31 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Operations/CompositeWriteOperationTests.cs
> +                ? Record.Exception(() => subject.ExecuteAsync(Mock.Of<IWriteBinding>(), CancellationToken.None).GetAwaiter().GetResult())
done

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Encryption/EncryptedCollectionHelper.cs
> +        }
done

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            UsingImplicitSession(session => DropCollection(session, name, options: null, cancellationToken), cancellationToken);
done

2022-05-11 21:31 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +            return UsingImplicitSessionAsync(session => DropCollectionAsync(session, name, options: null, cancellationToken), cancellationToken);
done

2022-05-11 23:28 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoDatabaseImpl.cs
> +                messageEncoderSettings.Add(MessageEncoderSettingsName.GuidRepresentation, withEncryption ? GuidRepresentation.Unspecified : _settings.GuidRepresentation);
discussed offline

2022-05-12 15:53 UTC, rstam approved these changes
LGTM

2022-05-12 19:44 UTC, merged