adds remarks when zero or null for IFindFluent.Limit
mongodb/mongo-csharp-driver pull request #804
Opened 2022-06-01 14:44 UTC by leandromoh

2022-06-13 14:11 UTC, leandromoh commented
FYI @DmitryLukyanov @rstam

2022-06-13 19:07 UTC, JamesKovacs requested changes
Thank you for contributing to the MongoDB .NET/C# Driver by clarifying our documentation. Please implement the minor wording change requested and I will merge your change into our source tree.

2022-06-13 19:07 UTC, JamesKovacs commented on src/MongoDB.Driver/IFindFluent.cs
> +        /// Limit equals to zero or null is equivalent to setting no limit.
This is a reasonable request to improve our documentation and is similar to the note in our [shell documentation on limit](https://www.mongodb.com/docs/manual/reference/method/cursor.limit/). The remark would read more naturally as "Limit of zero or null is..."

2022-06-13 21:49 UTC, leandromoh commented on src/MongoDB.Driver/IFindFluent.cs
> +        /// Limit equals to zero or null is equivalent to setting no limit.
adjust done @JamesKovacs ! thanks for review!

2022-06-16 00:04 UTC, JamesKovacs approved these changes
LGTM

2022-06-16 00:06 UTC, merged