CSHARP-4203: IFindFluentExtensions for Any and AnyAsync
mongodb/mongo-csharp-driver pull request #817
Opened 2022-06-09 23:21 UTC by mhdejonge

2022-06-13 18:31 UTC, BorisDog requested changes
Looks great, left a minor comment.

2022-06-13 18:31 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +
Unnecessary empty line

2022-06-13 19:23 UTC, mhdejonge-tby commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +
Removed it.

2022-06-13 19:24 UTC, mhdejonge commented on tests/MongoDB.Driver.Tests/IFindFluentExtensionsTests.cs
> +
Removed it.

2022-06-14 16:32 UTC, rstam approved these changes
LGTM

2022-06-14 17:24 UTC, merged