CSHARP-3529: Support $topN et al in GroupBy.
mongodb/mongo-csharp-driver pull request #820
Opened 2022-06-14 01:26 UTC by rstam

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstAccumulatorExpression.cs
> +    internal abstract class AstAccumulatorExpression : AstExpression
`AstAccumulatorExpression` is now abstract.

The old `AstAccumulatorExpression` has been renamed `AstUnaryAccumulatorExpression` and is now a subclass of `AstAccumulatorExpression`.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickAccumulatorExpression.cs
> +    internal sealed class AstPickAccumulatorExpression : AstAccumulatorExpression
New subclass of the now abstract `AstAccumulatorExpression` class.

This class supports all the `$topN`-like operators.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickExpression.cs
> +    internal sealed class AstPickExpression : AstAccumulatorExpression
Instances of this class in an AST are usually temporary and will be optimized into `AstPickAccumulatorExpression` by the `AstGroupPipelineOptimizer`.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickExpression.cs
> +    internal sealed class AstPickExpression : AstAccumulatorExpression
Oops.. this class should derive from `AstExpression`, not `AstAccumulatorExpression`.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickOperator.cs
> +                AstPickOperator.TopN => "$topN",
Most of these aren't supported by the server unless they're in a `$group` stage.

We've considered using strings like `$pseudoBottom`. Haven't decided yet...

Thoughts?

We'd also discussed writing tests that define what happens when these methods are used in the wrong context. That's not done yet.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Optimizers/AstGroupPipelineOptimizer.cs
> +            public override AstNode VisitPickExpression(AstPickExpression node)
This is the new optimizer method that moves `AstPickExpressions` to the `$group` stage.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +                        var nContext = context.WithSingleSymbol(keySymbol);
The `WithSingleSymbol` is important because the lambda to compute `n` can *only* refer to the `key` (`_id`) and nothing else.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +            // we get here when the PartialEvaluator couldn't fully evalute the SortDefinition
We've talked about this awhile back.

This is how we avoid having to make the `PartialEvaluator` know about `SortDefinition`.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +            return (AstSortFields)methodInfo.Invoke(null, new object[] { expression, sortByExpression, sortByDefinition, documentSerializer });
We have to use reflection to call `TranslateSortByDefinitionGeneric` because we don't know `TDocument` until runtime.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/TranslationContext.cs
> +        private readonly KnownSerializersRegistry _knownSerializersRegistry;
Fixing a typo I hadn't noticed before.

2022-06-14 01:42 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoEnumerable.cs
> +            TKey key,
Take note of the `key` parameter here.

Turns out not only do we need it to infer the `TKey` type, we also need it to discover the serializer for the key.

2022-06-14 01:42 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3529Tests.cs
> +                "{ $project : { Id : '$_id', PlayerId : '$__agg0', _id : 0 } }");
These pipelines don't *exactly* match the server documentation because of how we move accumulators to the `$group` stage and that we have to project away the `_id` to match the POCO coming out of the pipeline.

2022-06-17 22:04 UTC, JamesKovacs requested changes
Overall looks great. See my comment about throwing if the `AstPickExpression` cannot be optimized into a `$group`.

2022-06-22 21:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickOperator.cs
> +        TopNAccumulator
There are "accumulator" and "array" versions of these operators. 

Depending on the operator there might only be an "accumulator" version (no "array" version).

It is helpful to have different operators because the accumulator and array versions of the operators take different arguments and are rendered differently.

2022-06-22 21:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +                    throw new ExpressionNotSupportedException(expression, because: $"{method.Name} can only be used as an accumulator with GroupBy");
This is how we throw an exception when a method like `Bottom` is used in a way that is not supported.

2022-06-22 21:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +                if (IsGroupingSource(sourceTranslation.Ast))
The accumulator and array versions look the same in LINQ. The only difference is whether the `source` is a reference to `$_elements` or not (i.e. a "grouping" source).

2022-06-22 21:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +                    selectorAst = null;
Even though the accumulator and array versions look the same in LINQ, they are *not* the same in MQL.

In MQL we have to combine the `source` and the `selector` into a new source that combines them.

2022-06-22 21:53 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3529Tests.cs
> +                .Select(x => x.A.FirstN(e => e.X, 2));
As currently implemented `FirstN` (and others) look the same in LINQ whether being applied to a grouping or to an array.

Alternatively, we *could* choose to use a *different* API for the array versions.

For example, instead of:

```Select(x => x.A.FirstN(e => e.X, 2)```

we could require:

```Select(x => x.A.Select(e => e.x).FirstN(2)```

that is, the array version of `FirstN` would take only an `n` parameter (besides the `source`), just like the underlying MQL `$firstN` array operator.

2022-06-22 21:53 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/PickMethodToAggregationExpressionTranslator.cs
> +                    selectorAst = null;
Unless we change the public API for the array version. See another comment about this in the tests.

2022-06-22 22:59 UTC, JamesKovacs approved these changes
LGTM. Only outstanding question is whether to use `$bottomPlaceholder`, `$bottom(placeholder)`, or some other formulation that indicates it is not a real operator supported by the server.

2022-06-22 22:59 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickOperator.cs
> +        TopNAccumulator
Good realization.

2022-06-22 22:59 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstPickOperator.cs
> +                AstPickOperator.BottomAccumulator => "$bottomAccumulator",
My concern with `$bottomAccumulator` is that it isn't immediately obvious to the average user that this is a pseudo-operator that will get replaced. `$bottomPlaceholder` is better. Another option could be `$bottom(placeholder)`. Not sure which I prefer. Or some other nomenclature instead of `placeholder`. Dummy, fake, temporary? But all those have other meanings that might be more confusing.

2022-06-22 22:59 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3529Tests.cs
> +                .Select(x => x.A.FirstN(e => e.X, 2));
I honestly like the symmetry between the grouping and array versions. I think the array version is more discoverable as `x.A.FirstN(e => e.X, 2)` than the proposed alternative.

2022-06-23 15:53 UTC, JamesKovacs approved these changes
LGTM

2022-06-24 21:31 UTC, merged