CSHARP-4106: Add ClientEncryption entity and Key Management API operations to Unified Test Format.
mongodb/mongo-csharp-driver pull request #826
Opened 2022-06-21 14:26 UTC by DmitryLukyanov

2022-06-22 00:39 UTC, DmitryLukyanov commented on build.cake
> +Task("TestCsfleWithMongocryptd")
Slightly changed naming to follow already presented similar naming in `TestCsfleWithMockedKmsNetStandard21`. I'm open to suggestions here.

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +              export PATH=$PATH:/usr/share/dotnet
now `dotnet` can be used everywhere

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          ${PREPARE_CSFLE}
this looks a bit easier than before :)

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +  run-csfle-with-mocked-kms-tests:
This naming is closer to what we mostly use in this file

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          OS=${OS} \
this was missed before

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +  run-csfle-with-mongocryptd-tests:
this naming is a bit closer to what we already use for special csfle cases, I'm open to suggestions here

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          TARGET="TestCsfleWithMongocryptd" \
This is a bit closer to what we already use in this file for special CSFLE cases

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> -          TARGET="TestMongocryptd" \
It's not really needed. We can look at TARGET insted

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/run-tests.sh
> +if [ "$TARGET" == "TestCsfleWithMongocryptd" ]; then
ensure that `CRYPT_SHARED_LIB_PATH` has expected value

2022-06-22 00:39 UTC, DmitryLukyanov commented on evergreen/run-tests.sh
> +dotnet nuget locals all --clear
prevent the case we had during previous release when macos cached test nuget and then used it all the time

2022-06-22 00:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +        public Guid CreateKey(string kmsProvider, DataKeyOptions dataKeyOptions, CancellationToken cancellationToken = default)
However there is a question here related to a return type (Guid). The [spec](https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/client-side-encryption.rst#clientencryption) defines id as binary, so we can use either Guid or BsonBinary. It's mentioned here:
>Drivers MAY use a native UUID type in place of a parameter or return type specified as a BSON binary with subtype 0x04 as described in [Handling of Native UUID Types](https://github.com/mongodb/specifications/blob/master/source/uuid.rst).

However due to issues we have in the driver with GuidRepresentation mode, I know, we thought that it was not the best idea using guid initially (that hide subType info), so maybe it's a good time to change a return type from Guid to BsonBinary for a new method? If not, we will probably need using the same type for all ids here and we will need replacing all `BsonBinaryData` arguments on `Guid`

2022-06-22 00:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ExplicitEncryptionLibMongoCryptController.cs
> +                   ? ToBsonIfNotNull(new BsonDocument("keyAltName", value))
not really required here since unlikely altName can ever be guid, but I have done this for consistency in how we use ToBson in this file

2022-06-22 00:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/ClientSideEncryptionTestRunner.cs
> -        private string GetEnvironmentVariableOrDefaultOrThrowIfNothing(string variableName, string defaultValue = null) =>
moved to a single place

2022-06-22 00:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> -        private string GetEnvironmentVariableOrDefaultOrThrowIfNothing(string variableName, string defaultValue = null) =>
moved to a single place

2022-06-22 00:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedGetKeyByAltNameOperation.cs
> +                return OperationResult.FromException(exception);
this logic should be moved out of this level, but I already made enough refactoring changes here, we can consider this later

2022-06-23 01:33 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionOptions.cs
> +            new CryptClientSettings(
minor markup fix

2022-06-23 01:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/EncryptionTests.cs
> -﻿/* Copyright 2019-present MongoDB Inc.
split into 2 different classes

2022-06-27 23:39 UTC, BorisDog requested changes

2022-06-27 23:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +            return new ReadOnlyDictionary<string, IReadOnlyDictionary<string, object>>(providers);
minor: We can use `IReadOnlyDictionary` interface instead, and return `providers`

2022-06-27 23:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                .ToDictionary(k => k.Key, k => k.Value);
No need to copy the dictionary.

2022-06-27 23:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAddKeyAltNameOperation.cs
> +    public class UnifiedAddKeyAltNameOperation : IUnifiedEntityTestOperation
nit: sealed, here and other test files?

2022-06-27 23:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
> +                (actual ?? BsonNull.Value).Should().Be(expected ?? BsonNull.Value);
are we considering `null` and `BsonNull` to be equivalent?

2022-06-27 23:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +            IEnumerable<IDisposable> CombineIfDisposable(params IEnumerable[] items)
I think 
`IDisposable[] SelectDisposables(params IEnumerable[] items) => items.SelectMany(i => i.OfType<IDisposable>()).ToArray();`

might be sufficient;

2022-06-28 21:20 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +        private async ValueTask<BsonValue> ExplicitDecrypt(ClientEncryption clientEncryption, BsonBinaryData value, bool async) =>
not sure about this method name and approach in general.. I already missed in a test that the result is awaitable, but even in this case this code still compiled and looks correct:

    var result = ExplicitDecrypt()
    result.Should.Be(10);

I'm ok to try it now, but it looks like something to track how big deal it will be during next few tickets and how we can improve it.

2022-06-29 22:47 UTC, BorisDog requested changes

2022-06-30 00:46 UTC, BorisDog approved these changes
LGTM, assuming last comments are resolved.

2022-06-30 11:06 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +            __kmsProviders = new ReadOnlyDictionary<string, IReadOnlyDictionary<string, object>>(kmsProviders);
done

2022-07-14 23:14 UTC, BorisDog approved these changes
Some minor comments.
New changes LGTM.

2022-07-14 23:14 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        internal IMongoClient MongoCryptdClient => _mongocryptdClient.IsValueCreated ? _mongocryptdClient.Value : null;
nit: We probably don't need to worry about internal here, as the whole class is internal.

2022-07-14 23:14 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// <summary>
add empty line?

2022-07-14 23:14 UTC, BorisDog commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +                var contoller = mongoClient.LibMongoCryptController;
controller

2022-07-14 23:57 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        /// <summary>
done

2022-07-14 23:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/AutoEncryptionLibMongoController.cs
> +        internal IMongoClient MongoCryptdClient => _mongocryptdClient.IsValueCreated ? _mongocryptdClient.Value : null;
this is true, but it was done intentionally to highlight that this is not really good looking workaround. We will need removing this as soon as a mongoclient will be disposable

2022-07-15 00:00 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.TestHelpers/DisposableMongoClient.cs
> +                var contoller = mongoClient.LibMongoCryptController;
done

2022-07-15 01:31 UTC, merged