CSHARP-4209: Integrate with .NET Logging library
mongodb/mongo-csharp-driver pull request #842
Opened 2022-07-04 18:10 UTC by BorisDog

This is draft PR, and does not contain unit tests for logging

2022-07-12 00:21 UTC, JamesKovacs requested changes
Overall looking great. My main concern is that previously the driver would not create new event objects unless we had handlers registered. Now we create those event objects every time and they may never be used if no logger is present. I'm not sure if the additional allocation pressure is a concern or not, but we should do some quick tests to verify whether it has a noticeable effect on driver memory usage and/or performance. Happy to discuss more. Curious as to your thoughts.

2022-07-12 00:21 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +        private const string PrefixUnittests = "MongoDB.Unittests";
I assume that `PrefixUnittests` will be used for all our tests, not just the unit tests. Wouldn't this better named `PrefixTests` with a value of `MongoDB.Tests`?

2022-07-12 00:21 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/XUnitLogger.cs
> +    //[DebuggerStepThrough]
Should this still be commented?

2022-07-12 23:25 UTC, BorisDog reviewed
@JamesKovacs Memory pressure is an important aspect to track and validate. In our case, for better or for worse the events entities are structs, so at least we don't have to worry about that.

2022-07-12 23:25 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +        private const string PrefixUnittests = "MongoDB.Unittests";
Agreed, done and added tests.

2022-07-12 23:25 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Clusters/Cluster.cs
> +                    _clusterEventsLogger.LogDebug("CryptClient created. Shared library version {SharedLibraryVersion}", _cryptClient.CryptSharedLibraryVersion);
Done.

2022-07-13 01:58 UTC, DmitryLukyanov reviewed
Initial comments. I didn't go through all places yet. But it provides some questions to think on

2022-07-13 01:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/XUnitOutputAccumulator.cs
> +            _output = Ensure.IsNotNull(output, nameof(output));
I would say accumulator should not be responsible for output and better leave output logic outside. Thoughts?

2022-07-13 01:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            _eventsLogger.LogAndPublish(new ConnectionPoolClearingEvent(_serverId, _settings, serviceId));
here and in other places, previously we didn't create event if it wasn't requested. Now we do it a lot, not sure how bad it is

2022-07-13 01:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/DnsMonitor.cs
> +            _isSdamEventTracked = _eventsLogger.IsEventTracked<SdamInformationEvent>();
Can you describe what this "IsEventTracked" method is supposed to do? It will be true not only when we subscribed on events, but also if `  _isInformationEnabled = Logger?.IsEnabled(LogLevel.Information) == true;` is true.

2022-07-13 01:58 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
we should use a new logic for previous `ConfigureSdamLogging` logging

2022-08-05 22:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/EventType.cs
> +    internal enum EventType
let's keep eye on this enum. Maybe we will find a better approach eventually

2022-08-05 22:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LoggerFactoryCategoryDecorator.cs
> +    internal sealed class LoggerFactoryCategoryDecorator : ILoggerFactory
let's create a ticket to investigate downsides of using BeginScope instead decorator

2022-08-05 22:47 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LoggerDecorator.cs
> +        public LoggerDecorator(ILogger<T> logger, string decorationName, string decorationValue)
I'm ok to think about it in the scope of different ticket

2022-08-08 14:30 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
not answered

2022-08-08 14:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +        public LogEntry[] Logs => _output.Logs;
Just to recall previously unanswered points: 
1. Sooner or later you will need to break this style to add a backed field.
2. With this change, you have no longer a clear split between external and internal class API

2022-08-08 14:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +        protected virtual void Dispose(bool disposing) { }
not answered

2022-08-08 14:47 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/XUnitLoggerFactory.cs
> +        public void AddProvider(ILoggerProvider provider) { }
yeah, I missed that it's test side logic

2022-08-08 14:49 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Connections/CommandEventHelper.cs
> +            if (_shouldTrackSucceeded)
not answered

2022-08-09 22:25 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
well, we can make it obsolete at the very least. Let's create a ticket for this

2022-08-09 22:32 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +        public LogEntry[] Logs => _output.Logs;
1. Well, when it will happen, we may already had code base that will require changes. I would say it differently, let's use a new styling approach when we will know that the previous approach doesn't work for us for some reason to avoid any unnecessary changes.
2. it's not what I meant, unless you're planning to create a private properties. With this approach any property can be used as internal class API and external which gives some "small" pain.

After all, I disagree with this change, but also don't want spending time on this one more time

2022-08-10 20:32 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
Yeah good idea. Done.

2022-08-10 20:32 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +            _logger?.LogDebug("Running {0}", testCase.Name);
Done.

2022-08-12 16:59 UTC, DmitryLukyanov requested changes

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
can you post a link on ticket?

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/ClusterRegistry.cs
> +                .ConfigureLoggingFactory(_ => loggerFactory);
todo

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +            "MongoDB.Bson.Tests",
this looks like wrong logic given that now our driver code is aware of how it's used, ie it should not know about tests at all

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +            "MongoDB.Driver.Core"
MongoDB.Driver.GridFS?

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +            "MongoDB.Bson.Tests",
Can it be not `driverTests`, but something like `driverUsed` or something similar?

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                    _logger.LogDebug(ex, StructuredLogsTemplates.Message_ConnectionId, "Monitoring exception", connectionId);
RTT monitoring exception

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                    _logger.LogDebug(ex, StructuredLogsTemplates.Message_ConnectionId, "Monitoring exception", connectionId);
I still don't understand where we use `LogDebug` and where `LogException` or something. Can we define clear rules here?

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                    _logger.LogDebug(ex, StructuredLogsTemplates.Message_ConnectionId, "Monitoring exception", connectionId);
what will happen if connectionIs is null?

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +using Microsoft.Extensions.Logging;
this also should include logic like in this class `SdamLoggingSettings`

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +            Ensure.IsNotNull(configurator, nameof(configurator));
let's add a blank line after ensure as in other methods here

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/ClusterRegistry.cs
> +
empty line

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoClient.cs
> +            _cluster = ClusterRegistry.Instance.GetOrCreateCluster(_settings.ToClusterKey(), _settings.LoggerFactory);
I would say we need going though a regular workflow passing arguments from highlevel settings to low onces. Ie we need to do it through `ClusterKey`

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        public ILoggerFactory LoggerFactory
we have tests for this class

2022-08-12 16:59 UTC, DmitryLukyanov commented on src/MongoDB.Driver/ClusterRegistry.cs
> +                    cluster = CreateCluster(clusterKey, loggerFactory);
I think we need working through clusterKey as the rest of options here

2022-08-12 20:14 UTC, BorisDog commented on src/MongoDB.Driver/ClusterRegistry.cs
> +                    cluster = CreateCluster(clusterKey, loggerFactory);
Done.

2022-08-12 20:14 UTC, BorisDog commented on src/MongoDB.Driver/MongoClient.cs
> +            _cluster = ClusterRegistry.Instance.GetOrCreateCluster(_settings.ToClusterKey(), _settings.LoggerFactory);
Done.

2022-08-12 20:14 UTC, BorisDog commented on src/MongoDB.Driver/MongoClientSettings.cs
> +        public ILoggerFactory LoggerFactory
Added tests.

2022-08-12 20:24 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +            "MongoDB.Bson.Tests",
>BTW similar to our InternalsVisibleTo.

this is not too good workaround that we probably can remove when we will have better code structure (remove Core). At least we can consider this

>but we are making a compromise in favor of simplicity.

I'm ok with simplicity here, but renaming this naming from "test" into "notdriver" (or something) looks simple too. See how difficult to do it, if not too easy, we can consider this work later

2022-08-12 20:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Servers/RoundTripTimeMonitor.cs
> +                    _logger.LogDebug(ex, StructuredLogsTemplates.Message_ConnectionId, "Monitoring exception", connectionId);
>There is no LogException. Exception object can be optionality passed in regardless of verbosity.

I meant, do we call anything other than `LogDebug`? If so, how do we decide it? If no so, then why?

2022-08-12 20:33 UTC, DmitryLukyanov approved these changes
LGTM

See some remaining comments. I assume no issues on EG

2022-08-12 22:38 UTC, merged