CSHARP-4245: Dispose CancellationTokenSource in tests
mongodb/mongo-csharp-driver pull request #846
Opened 2022-07-11 16:58 UTC by BorisDog

2022-07-12 00:38 UTC, JamesKovacs requested changes
Very nice use of `using var` syntax. My one concern is around the use of `default` in certain mocking scenarios. See my comment below for more details. Plus a minor point about using `cancellationTokenSource` rather than `cts` (even though `cts` was in the original).

2022-07-12 00:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/DnsClientWrapperTests.cs
> +            using var cts = new CancellationTokenSource();
Since we are updating these lines anyways, let's go with our usual coding standard of not using abbreviations.

`cts` => `cancellationTokenSource`

Same elsewhere.

2022-07-12 00:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.GridFS.Tests/DelegatingStreamTests.cs
> +            mockStream.Setup(s => s.CopyToAsync(mockDestination.Object, bufferSize, default)).Returns(task1);
Isn't this changing the meaning of the test? Previously we were asserting that the passed-in `CancellationTokenSource` was passed correctly. But since `CancellationTokenSource` is a class `default(CancellationTokenSource` is simply `null`. Thus we cannot tell if the `CancellationTokenSource` is being correctly passed through or if we are simply explicitly passing `null` through the call chain.

2022-07-12 00:38 UTC, JamesKovacs commented on tests/MongoDB.Driver.Legacy.Tests/DefaultLegacyOperationExecutorTests.cs
> +            mockOperation.Verify(m => m.Execute(binding, default), Times.Once);
Same concern around the use of `default` as with the previous file.

2022-07-12 23:43 UTC, BorisDog commented on tests/MongoDB.Driver.GridFS.Tests/DelegatingStreamTests.cs
> +            mockStream.Setup(s => s.CopyToAsync(mockDestination.Object, bufferSize, default)).Returns(task1);
Fixed.

2022-07-12 23:43 UTC, BorisDog commented on tests/MongoDB.Driver.Legacy.Tests/DefaultLegacyOperationExecutorTests.cs
> +            mockOperation.Verify(m => m.Execute(binding, default), Times.Once);
Fixed.

2022-07-12 23:43 UTC, BorisDog commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/DnsClientWrapperTests.cs
> +            using var cts = new CancellationTokenSource();
Done.

2022-07-13 16:19 UTC, JamesKovacs approved these changes
LGTM

2022-07-13 20:10 UTC, merged