CSHARP-4271: Replace Snappy and Zstd with managed implementations
mongodb/mongo-csharp-driver pull request #853
Opened 2022-07-27 16:54 UTC by adelinowona

2022-07-27 18:50 UTC, DmitryLukyanov reviewed
Initial review related to our code base. I didn't look at external nugets yet

2022-07-27 18:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Compression/SnappyCompressor.cs
> +            var maxCompressedSize = Snappier.Snappy.GetMaxCompressedLength(uncompressedSize);
let's mention `Snappier` ns in the top of the page, same in other places

2022-07-27 18:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            if (compressionLevel.HasValue && (compressionLevel.Value <= 0 || compressionLevel.Value >= 23))
can you provide a link where you found these restrictions?

2022-07-27 18:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +  <ItemGroup>
is it really required?

2022-07-27 18:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Compression/Zstandard/PinnedBufferWalker.cs
> -    internal class PinnedBufferWalker : IDisposable
please close this ticket as well https://jira.mongodb.org/browse/CSHARP-2959

2022-07-27 18:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +
double blank line

2022-07-27 18:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/NativeLibraryLoader/LibraryLoader.cs
> -    internal class LibraryLoader
please close this ticket as well https://jira.mongodb.org/browse/CSHARP-3693

2022-07-27 18:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> -        public void Compressor_should_read_the_previously_written_message(CompressorType compressorType)
I would probably recommend to leave all previous tests in this file. And additionally put tests from the files you've removed

2022-07-27 18:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +            var testMessage = "abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789";
you already have global `__testMessage` , since the value in this test is copied from another test, you can modify `__testMessage` by the value in line 120 (to not change generated bytes)

2022-07-27 23:30 UTC, JamesKovacs requested changes
This is looking very good. Minor feedback below.

2022-07-27 23:30 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/SnappyCompressor.cs
> +            var maxCompressedSize = Snappier.Snappy.GetMaxCompressedLength(uncompressedSize);
Agreed. We should have `using Snappier;` in the using directives at the top to eliminate the need to include the namespace every time we use `Snappy`.

2022-07-27 23:30 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            using (var zstandardStream = new ZstdSharp.CompressionStream(output, _compressionLevel))
Same as with `Snappier`. We should include `using ZstdSharp;` in the using directives at the top.

2022-07-27 23:30 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +    <PackageReference Include="ZstdSharp.Port" Version="0.6.1" />
I would place these package references with the other 3rd-party NuGet packages such as DnsClient.NET below. (See line 59.)

2022-07-28 01:12 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            if (compressionLevel.HasValue && (compressionLevel.Value <= 0 || compressionLevel.Value >= 23))
The facebook zstd library states that it only supports compression levels 1 through 22. Here is a link: https://facebook.github.io/zstd/zstd_manual.html#:~:text=The%20library%20supports%20regular%20compression%20levels%20from%201%20up%20to%20ZSTD_maxCLevel()%2C%0A%20%20which%20is%20currently%2022.

The ZstdSharp.Port library I am using is a port of the facebook zstd library so it also only supports compression levels 1-22. The library does not throw an error if you pass in a compression level outside the 1-22 range. Instead it will clamp the value to be within that range. We could leave as it was but I thought we would want to be explicit here so that the user gets an error if they provide unsupported compression levels.

2022-07-28 01:20 UTC, adelinowona commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +  <ItemGroup>
This was automatically added to the project file when I added the managed libraries through nuget on VS but I think can remove it.

2022-07-28 01:26 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            if (compressionLevel.HasValue && (compressionLevel.Value <= 0 || compressionLevel.Value >= 23))
Effectively it says:
>The library supports regular compression levels from 1 up to ZSTD_maxCLevel(), which is currently 22. Levels >= 20,

so 22 is only current version. I would validate on calculated value instead. NOTE: we actually don't have a way to configure this option in the driver yet

2022-07-28 02:01 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> -        public void Compressor_should_read_the_previously_written_message(CompressorType compressorType)
I actually didn't delete this test. I just renamed it to Snappy as it was only testing the Snappy compressor after I wrote a similar tests for the Zstandard compressor that uses different compression levels. 

For the files I removed, I looked through the tests and only migrated some tests (those that didn't test the internal implementation details of the unmanaged compressors).

2022-07-28 12:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/MongoDB.Driver.Core.csproj
> +  <ItemGroup>
yes, I think this part is not needed

2022-07-28 13:34 UTC, DmitryLukyanov commented
Just to mention that there is a note that older TFs can have problems with performance on windows for snappier: https://github.com/brantburnett/Snappier#other-projects

2022-07-28 14:43 UTC, adelinowona commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            if (compressionLevel.HasValue && (compressionLevel.Value <= 0 || compressionLevel.Value >= 23))
Oh I had assumed the driver supported setting the compression level for zstd as it does for zlib. From your point, I also agree that we should use the calculated value but since the driver doesn't support passing a compression level for the zstd compressor, I think we can then omit this for now?

2022-07-28 14:44 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
> +            if (compressionLevel.HasValue && (compressionLevel.Value <= 0 || compressionLevel.Value >= 23))
sgtm

2022-07-28 15:33 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
I don't know but I can try to look into it

2022-07-28 16:29 UTC, JamesKovacs requested changes
Minor feedback.

2022-07-28 16:29 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        private static string __testMessage = "abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789";
This can be a constant and moved to private constants above.

2022-07-28 16:29 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        private static string __testMessage = "abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789";
Why was `__testMessage` changed from a-z repeated 3 times to a-z0-9<space> repeated 3 times? Changing `__testMessage` necessitated changing an unrelated zlib test.

2022-07-28 16:36 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_throw_when_output_stream_is_null()
also please put tests in this file in alphabetical order based on their names

2022-07-28 16:37 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +                        .Be("120,156,74,76,74,78,73,77,75,207,200,204,202,206,201,205,203,47,40,44,42,46,41,45,43,175,168,172,50,48,52,50,54,49,53,51,183,176,84,72,164,150,34,0,0,0,0,255,255,3,0,228,
why these bytes were changed?

2022-07-28 16:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        private static string __testMessage = "abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789 abcdefghijklmnopqrstuvwxyz0123456789";
I suggested this since we can use this `__testMessage` in zstandard. So this needed to not change expected bytes for zstandard, but I missed that this change will require updating expected result for zlib

2022-07-28 19:47 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
Ok so I did some investigating:
the last 3 bytes seem to be way of ending the compressed stream. There is a function called ZSTD_endStream that is used to end the stream. The unmanaged implementation in the driver actually called that function via Flush when it flushed the zstandard stream (https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs#:~:text=zstandardStream.Flush()%3B) you can follow the call stack for Flush to see it.

So I tried to also Flush the zstandard stream using the Library we are using I got this:
`"40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,132,170,39,40,181,47,253,32,0,1,0,0"`

The Flush in the library basically writes a null buffer to the compressed stream. You can see it has the 3 bytes (1, 0, 0) at the end. If I don't call Flush then those bytes won't be there.

However, I don't think any of these matters as I compressed a message with and without Flushing the stream using the library and then decompressed the compressed bytes using the unmanaged code implementation and it produced the right uncompressed output. I also compressed the message using the unmanaged code implementation and decompressed it using the library with success. Therefore, whether those bytes are there or not doesn't seem matter as far as I can tell.

2022-07-28 22:41 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
I think it's better to call Flush. Effectively it means that currently we ignore some information (last 3 bytes in this test). Maybe this information is "unimportant technical" details, maybe it's "technical" only for cases we checked in tests, and will be important in other cases. In any case it looks safer to work with all data compressor prepared for us

2022-07-28 22:52 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
SGTM

2022-07-29 19:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
given that you don't call flush, how did you get this result? Also, now the difference is even bigger than before, do you know why?

2022-07-29 19:44 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
I updated my commit with flushing as for some reason it didn't have the addition of flushing. Flushing writes a null buffer to the compressed stream and you can see that before the (1, 0, 0) bytes, the bytes (40,181,47,253) inserted are similar to the bytes at the start of the result bytes. My guess was the original zstd implementation do something to eliminate those starting bytes and just have the (1, 0, 0) bytes and the library we are using doesn't do it.

2022-08-01 18:30 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
well, I'm a bit surprised that we still have such difference. Can you please check what bytes are generated for this test with other zstd 3rd party nuget like with this one https://github.com/bp74/Zstandard.Net ?

2022-08-02 15:08 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
I tested and it returns the original expected bytes but I think that is to be expected since other third party libraries are wrappers and not re-implementations. I think ZstdSharp.Port is the only C# port of zstd and it is even recommended on the zstd website: https://facebook.github.io/zstd/#:~:text=https%3A//github.com/oleg%2Dst/ZstdSharp. Everything listed there is said to support the zstd format specification and are interoperable: https://facebook.github.io/zstd/#:~:text=All%20versions%20support%20the%20Zstandard%20format%20specification%20and%20are%20therefore%20interoperable.

2022-08-03 17:44 UTC, adelinowona commented
>

2022-08-03 21:26 UTC, JamesKovacs requested changes
Home stretch here. See my comments, but let's also discuss over Slack.

2022-08-03 21:26 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
>                  zstandardStream.Flush();
I did some investigation. The `01 00 00` is a data block denoting the last block of a frame. Without it the frame is considered corrupted though many non-strict implementations will still decode it. If you only call `Flush` or `Close` on the `CompressionStream`, this last block is not written. If you call both, it is.

```
zstandardStream.Flush();
zstandardStream.Close();
```

I would expect `Dispose` (which is implicitly called via the `using` block`) should flush and close the stream, but with this library it does not. At least it doesn't write out the final data block in the frame for some reason.

With both flush and close, the output bytes from managed zstd exactly matches the unmanaged version. You'll have to update the tests to account for the additional `01 00 00`.

2022-08-03 21:26 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
>              }
Given that we had to flush/close the `CompressionStream`, I would suggest explicitly calling `Close` on the `DecompressionStream`. Since we are reading from the `DecompressionStream` there is nothing to flush and in fact calling `Flush` is invalid.

2022-08-03 21:26 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        [InlineData(1, "40,181,47,253,0,72,109,1,0,84,2,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,48,49,50,51,52,53,54,55,56,57,32,1,0,53,13
If there are differences in the test output between the original unmanaged zstd impl and the new managed zstd impl, let's make sure that we can account for them.

2022-08-03 21:26 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
The output bytes are identical regardless of compression level since zstd decides to write the bytes out raw (aka uncompressed). If we are going to assert that different compression levels output the expected bytes, we should choose an input that produces different outputs depending on compression level. I would also be good with asserting that compression level 6 produces the expected output - which happens to be the raw ASCII text with a magic number and some headers.

2022-08-05 00:05 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
>                  zstandardStream.Flush();
As discussed over Zoom, updating to Zstandard.Port 0.6.2 resolves this issue and only `Flush` is required.

2022-08-05 00:09 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Compression/ZstandardCompressor.cs
>              }
This shouldn't be necessary after updating to Zstandard.Port 0.6.2.

2022-08-05 19:05 UTC, adelinowona commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
Removed this test as it showed itself as disposable given that the compressed format for the ZstdSharp.Port library is now fixed and although the output bytes are still different for different compression levels on input that is compressible, I have tested that other 3rd party wrappers of zstd can decompress the data compressed with the library without error and vice versa. The evergreen tests also show that we can communicate with server without errors.

2022-08-05 19:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
so bytes are still different than before? I would prefer to not remove this test. At the very list it's a good prove for now and later that upgrading a new version of nuget actually works as expected

2022-08-05 20:07 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
Testing whether the compressed bytes match some expected output is more about testing the compression library than testing our integration with it. We considered compressing and decompressing to validate that the input isn't modified, but that once again is testing whether the compression library does its job. The real test is whether Zstandard.Port can compress data that the server understands and whether it can decompress data from the server. That is already proven out via our Zstandard variants in EG. In summary, I'm OK with removing these tests because we verify this functionality already via our integration tests.

2022-08-05 20:12 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
> the compression library does its job

which is not bad idea given that we're working with 3rd part library which we don't know how close 100% reliability it is. I would prefer to have a control over this, but if you're ok with this, I can rely on you

2022-08-08 16:31 UTC, JamesKovacs approved these changes
LGTM

2022-08-08 16:31 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.Tests/Core/Compression/CompressorsTests.cs
> +        public void Zstandard_compress_should_generate_expected_bytes_for_different_compression_levels(int compressionLevel, string expectedBytes)
If there are meaningful inconsistencies that result in our driver not being able to decompress a response or compressing a request incorrectly, then our integration tests will catch it. So I'm good with leaving this to our integration testing via snappy and zstd variants rather than explicitly checking payloads.

2022-08-08 16:33 UTC, JamesKovacs commented
Note that we do have quite a few broken tests, but they are related to server changes (e.g. `latest`) or flaky tests. We need to fix these but they don't have to hold up integration of the compressor work IMHO.

2022-08-08 17:44 UTC, DmitryLukyanov approved these changes
LGTM

2022-08-09 16:12 UTC, adelinowona commented
Squash-merged manually due to a minor merge conflict.

2022-08-09 16:12 UTC, closed without merging