CSHARP-4256: Add a guard for CSFLE tests to ensure that used mongocryptd has expected version.
mongodb/mongo-csharp-driver pull request #855
Opened 2022-07-28 15:32 UTC by DmitryLukyanov

2022-07-28 16:31 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +                using (var process = new Process())
this approach doesn't spawn mongocryptd process itself

2022-07-29 22:11 UTC, BorisDog requested changes
minor comments

2022-08-01 22:17 UTC, BorisDog requested changes

2022-08-01 22:17 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +            if (!csfleSetupState.Value.IsValid)
Do we want to check this in the begging of the method? To skip all logic in case it's not valid.

2022-08-01 22:17 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +        private static Lazy<(bool IsValid, SemanticVersion Version)> csfleSetupState = new Lazy<(bool IsValid, SemanticVersion Version)>(() => (IsCsfleSetupValid(out var usedMongocryptdVersion), used
readonly,
__csfleSetupState,

also maybe, change IsCsfleSetupValid to `(bool, SemanticVersoin)  IsCsfleSetupValid` and then:
`private static readonly Lazy<(bool IsValid, SemanticVersion Version)> __csfleSetupState = new Lazy<(bool, SemanticVersion)>(IsCsfleSetupValid, isThreadSafe: true);`

2022-08-01 23:23 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +        private static Lazy<(bool IsValid, SemanticVersion Version)> csfleSetupState = new Lazy<(bool IsValid, SemanticVersion Version)>(() => (IsCsfleSetupValid(out var usedMongocryptdVersion), used
done

2022-08-02 14:51 UTC, BorisDog approved these changes
LGTM

2022-08-03 16:53 UTC, JamesKovacs requested changes
Looking good. Some minor naming and wording improvements suggested.

2022-08-03 16:53 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +                throw new Exception($"The used mongocryptd version {csfleSetupState.Value.Version} doesn't match to a server {CoreTestConfiguration.ServerVersion}.");
Awkward wording. How about this?
```
$"The configured mongocryptd version {csfleSetupState.Value.Version} doesn't match the server version {CoreTestConfiguration.ServerVersion}."
```

2022-08-03 16:53 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +        private static bool IsCsfleSetupValid(out SemanticVersion usedMongocryptdVersion)
usedMongocryptdVersion -> configuredMongocryptdVersion
or detectedMongocryptdVersion

2022-08-03 16:53 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +        private static string __defaultMongocryptdPath = Environment.GetEnvironmentVariable("MONGODB_BINARIES") ?? "";
Make readonly.

2022-08-03 16:53 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +            int SemanticVersionCompareToAsReleased(SemanticVersion a, SemanticVersion b)
`SemanticVersionCompareToAsReleased` -> `CompareSemanticVersionsAsReleased`

2022-08-03 17:01 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +            int SemanticVersionCompareToAsReleased(SemanticVersion a, SemanticVersion b)
done

2022-08-03 17:01 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +        private static bool IsCsfleSetupValid(out SemanticVersion usedMongocryptdVersion)
done

2022-08-03 17:02 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/EncryptionTestHelper.cs
> +                throw new Exception($"The used mongocryptd version {csfleSetupState.Value.Version} doesn't match to a server {CoreTestConfiguration.ServerVersion}.");
done

2022-08-03 21:27 UTC, JamesKovacs approved these changes
LGTM

2022-08-04 02:24 UTC, merged