CSHARP-4168: Obtain AWS credentials for CSFLE in the same way as for MONGODB-AWS.
mongodb/mongo-csharp-driver pull request #862
Opened 2022-08-05 01:58 UTC by DmitryLukyanov

2022-08-15 21:54 UTC, BorisDog requested changes

2022-08-15 21:54 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                            ),
Place closing bracket on the last line? I think that's the convention.

2022-08-15 21:54 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                            (MongoAWSAuthenticator.CreateAwsCredentialsFromEnvironmentVariables(subject: "AWS kms provider") ??
Should we group those method into single one, and reuse it in MongoAWSAuthenticator as well?

2022-08-15 21:54 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                    "aws" when kmsProvider.Value.Count == 0 =>
Seems that you are expecting more case here in the future?

2022-08-15 21:54 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +        internal static AwsCredentials CreateAwsCredentialsFromEc2Response()
We really should have async versions for those methods, instead of blocking code. Especially to use in `ProcessStateAsync`.

2022-08-15 21:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +        internal static AwsCredentials CreateAwsCredentialsFromEc2Response()
good point, agreed, since we actually use async code inside

2022-08-15 21:56 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                    "aws" when kmsProvider.Value.Count == 0 =>
yes, as I know the rest provides are planned too

2022-08-19 16:01 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +        internal static AwsCredentials CreateAwsCredentialsFromEnvironmentVariables(string subject = "MONGODB-AWS authentication")
done

2022-08-19 16:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                            ),
this logic has been moved into aws authenticator

2022-08-19 16:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +        internal static AwsCredentials CreateAwsCredentialsFromEc2Response()
done

2022-08-19 16:02 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +            public static AwsCredentials CreateAwsCredentialsFromExternal(string subject = "MONGODB-AWS authentication") =>
not sure whether `..FromExternal` is the best name here

2022-08-19 16:03 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/LibMongoCryptControllerBase.cs
> +                            (MongoAWSAuthenticator.CreateAwsCredentialsFromEnvironmentVariables(subject: "AWS kms provider") ??
done

2022-08-19 16:03 UTC, DmitryLukyanov commented
note: I see that tests failed on EG, looking at this

2022-08-19 17:35 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/IEncryptionOptions.cs
> +    internal interface IEncryptionOptions
base class is a bit better suits here, but it's a bit painful to make base class internal. So this is why I chose interface

2022-08-24 23:46 UTC, JamesKovacs requested changes
A few minor suggestions/questions...

2022-08-24 23:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +            public static AwsCredentials CreateAwsCredentialsFromExternal(string subject = "MONGODB-AWS authentication") =>
What about `CreateAwsCredentialsFromExternalSource`?

2022-08-24 23:46 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +                (await CreateAwsCredentialsFromExternalAsync("AWS kms provider").ConfigureAwait(false)).ConvertToKmsCredentials();
Why not call `CreateAwsCredentialsFromExternalAsync` directly from `LibMongocryptControllerBase` and eliminate the need for this helper method? You would need to call `ConvertToKmsCredentials` in `LibMongocryptControllerBase` of course.

2022-08-24 23:55 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +                (await CreateAwsCredentialsFromExternalAsync("AWS kms provider").ConfigureAwait(false)).ConvertToKmsCredentials();
Either way works for me :) I'm ok to change it

2022-08-25 00:29 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/MongoAWSAuthenticator.cs
> +                (await CreateAwsCredentialsFromExternalAsync("AWS kms provider").ConfigureAwait(false)).ConvertToKmsCredentials();
done

2022-08-25 19:58 UTC, JamesKovacs approved these changes
LGTM

2022-09-07 17:01 UTC, JamesKovacs approved these changes
LGTM. Remember to cleanup the local nuget packages used for testing.

2022-09-08 14:04 UTC, merged