CSHARP-4292: Performance: Eliminated allocations in GetHashCode methods
mongodb/mongo-csharp-driver pull request #864
Opened 2022-08-11 16:17 UTC by dnickless

Eliminated some boxing problems leading to substantial allocations in our code. Details located here: https://jira.mongodb.org/browse/CSHARP-4292

2022-08-18 22:17 UTC, BorisDog requested changes
Good optimization overall. Minor comments.

2022-08-18 22:17 UTC, BorisDog commented on src/MongoDB.Shared/Hasher.cs
> +                    _hashCode = 37 * _hashCode + (value == null ? -1 : EqualityComparer<T>.Default.GetHashCode());
Could you please wrap `EqualityComparer<T>.Default.GetHashCode())` in

 ```
internal class Hasher
 {
      #region static 

      // public static methods
      [MethodImpl(MethodImplOptions.AggressiveInlining)]
      public static int GetHashCode<T>(T obj) => EqualityComparer<T>.Default.GetHashCode(obj);

      #end

      // private fields
      private int _hashCode;
      ...
 }
```

2022-08-18 22:40 UTC, BorisDog commented on src/MongoDB.Shared/Hasher.cs
> +                    _hashCode = 37 * _hashCode + (value == null ? -1 : EqualityComparer<T>.Default.GetHashCode());
missing `value` in `EqualityComparer<T>.Default.GetHashCode(**value**).` 
This was caught by local tests.

2022-08-19 01:02 UTC, rstam commented on src/MongoDB.Bson/ObjectModel/BsonRegularExpression.cs
> +            hash = 37 * hash + EqualityComparer<string>.Default.GetHashCode(_pattern);
I don't think it's necessary for value types either, just for enums.

2022-08-19 10:33 UTC, dnickless commented
Everything fixed and cleaned up now using separate commits for easier change tracking - should arguably get squashed.

2022-08-19 16:30 UTC, BorisDog requested changes
Thanks, one last comment.

2022-08-19 16:30 UTC, BorisDog commented on src/MongoDB.Bson/ObjectModel/BsonBinaryData.cs
> +            hash = 37 * hash + EqualityComparer<BsonType>.Default.GetHashCode(BsonType);
Could you please substitute all `EqualityComparer<T>.Default` with `Hasher.GetHashCode`?

2022-08-19 16:30 UTC, BorisDog commented on src/MongoDB.Bson/ObjectModel/BsonRegularExpression.cs
> +            hash = 37 * hash + EqualityComparer<string>.Default.GetHashCode(_pattern);
Good point @rstam.

2022-08-23 17:28 UTC, JamesKovacs approved these changes
LGTM

2022-08-24 16:11 UTC, merged