CSHARP-4241: Basic smoke tests
mongodb/mongo-csharp-driver pull request #865
Opened 2022-08-12 22:57 UTC by BorisDog

[Smoke tests EG](https://spruce.mongodb.com/version/62e304fe3e8e865395b6ccd1)

2022-08-12 23:35 UTC, BorisDog commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +    <PackageReference Include="Microsoft.Extensions.Logging.TraceSource" Version="2.2.0" />
Remove unused references.

2022-08-12 23:35 UTC, BorisDog commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/InfrastructureUtilities.cs
> +﻿using System;
copyrights.

2022-08-16 15:30 UTC, DmitryLukyanov reviewed
Initial comments

2022-08-16 15:30 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +    <PackageReference Include="MongoDB.Driver" Version="[16.0.2-csharp4241.1-35]" Condition="'$(SmokeTestsPackageSha)' != ''" />
As I see, this should be removed since you're adding this reference in smoke test task

2022-08-16 15:30 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +  <PropertyGroup Condition="'$(SmokeTestsPackageSha)' != ''">
I think we need a new variable for `"'$(SmokeTestsPackageSha)' != ''"`

2022-08-16 22:42 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +    <PackageReference Include="MongoDB.Driver" Version="[16.0.2-csharp4241.1-35]" Condition="'$(SmokeTestsPackageSha)' != ''" />
I've checked again and it looks like it can be removed but in this case for local run, it will add a nuget without `Condition` which effectively will mean that we reference 2 the same sources for a project, i'm ok to leave it in this form

2022-09-27 22:52 UTC, DmitryLukyanov requested changes
Also, you will need to look at latest changes in how build.cake file looks now. See James' commit https://github.com/mongodb/mongo-csharp-driver/commit/3c1f0db0ef64603f32bbd7b240464abc523b5cdd

2022-09-27 22:52 UTC, DmitryLukyanov commented on build.cake
> +string GetPackageVersion()
I think better use a logic like in line 885 (similar new changes are in master too) with adding a new field `Version` to BuildConfig. So each particular task will be able to know what version it should use from input argument and particular value will be assigned in `Setup` step based on task name

2022-09-27 22:52 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            . ./evergreen/fetch-crypt_shared-library.sh
Let's remove this. This line is not enough to configure FLE and we don't use it here anyway

2022-09-27 22:52 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          echo "Skipping certificate removal..."
we should stop using this line. It's legacy artifact that has no meaning long time already

2022-09-27 22:52 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            evergreen/cleanup-test-resources.sh
A bit different that about FLE configuration, since a name is more common here, but effectively this step is useless too. See whether you're ok to remove it or no. I will be ok with any way

2022-09-27 22:52 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LogEntry.cs
> +        public LogLevel LogLevel { get; }
We put properties after ctor (Leaving a formatting question itself aside)

2022-09-27 22:52 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LogEntry.cs
> +        public override string ToString() => $"{LogLevel}_{Category}_{Message}";
should an xml comment be here?

2022-09-27 22:52 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/InfrastructureUtilities.cs
> +namespace MongoDB.Driver.SmokeTests.Sdk
I still think it's not right name here, but I'm ok to proceed for now

2022-09-28 19:24 UTC, BorisDog commented on build.cake
> +string GetPackageVersion()
Done

2022-09-28 22:16 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          echo "Skipping certificate removal..."
missed

2022-09-28 22:16 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            evergreen/cleanup-test-resources.sh
missed, but you can ignore it if you want

2022-09-28 22:17 UTC, DmitryLukyanov commented on build.cake
> +        Console.WriteLine($"Framework: {framework ?? "null (not set)"}, TargetPlatform: {targetPlatform}, IsReleaseMode: {isReleaseMode} PackageVersion: {packageVersion}");
missed comma

2022-09-28 22:19 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            FRAMEWORK: net50
do we actually install .net5 anywhere?

2022-09-28 22:45 UTC, BorisDog commented on evergreen/evergreen.yml
> +          echo "Skipping certificate removal..."
Done.

2022-09-28 22:45 UTC, BorisDog commented on evergreen/evergreen.yml
> +            evergreen/cleanup-test-resources.sh
Done.

2022-09-28 22:45 UTC, BorisDog commented on evergreen/evergreen.yml
> +            FRAMEWORK: net50
Not sure where, this just always worked for this PR.

2022-09-28 22:45 UTC, BorisDog commented on build.cake
> +        Console.WriteLine($"Framework: {framework ?? "null (not set)"}, TargetPlatform: {targetPlatform}, IsReleaseMode: {isReleaseMode} PackageVersion: {packageVersion}");
Fixed.

2022-09-28 22:48 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +            FRAMEWORK: net50
we install only 3 TFs: 2.1, 3.1 and 60, so when you use 50, I think you effectively use 60

2022-09-29 18:06 UTC, DmitryLukyanov approved these changes
Minor comments and don't forget to create ticket about .net 5

2022-09-29 18:06 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
> +                    logEntryActual.Category.Contains(logEntryExpected.Category) == true &&
nit: logEntryActual.Category.Contains(logEntryExpected.Category) && ..

2022-09-29 18:06 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
> +                "mongodb://localhost/?connect=replicaSet";
let's revert it

2022-09-29 19:09 UTC, BorisDog commented on build.cake
> +    public BuildConfig(bool isReleaseMode, string framework, string targetPlatform, string package)
Done.

2022-09-29 19:09 UTC, BorisDog commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
> +                    logEntryActual.Category.Contains(logEntryExpected.Category) == true &&
Good catch, probably nullable leftovers.

2022-09-29 19:09 UTC, BorisDog commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/LoggingTests.cs
> +                "mongodb://localhost/?connect=replicaSet";
Good catch, reverted.

2022-09-30 15:15 UTC, merged