CSHARP-4272: Validate return value of bsonClassMap.CreateInstance() in BsonClassMapSerializer
mongodb/mongo-csharp-driver pull request #867
Opened 2022-08-16 18:28 UTC by BorisDog

2022-08-17 19:22 UTC, JamesKovacs requested changes
Minor change with regard to the type of exception to throw.

2022-08-17 19:22 UTC, JamesKovacs commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                    throw new InvalidOperationException($"{nameof(BsonClassMap)} did not provide an instance of {typeof(TClass).Name}.");
Reviewing the exceptions thrown in `BsonClassMapSerializer`, I think that `BsonSerializationException` is more appropriate than `InvalidOperationException`. `BsonSerializationException` is used when a creator map is unexpectedly null or similar. `InvalidOperationException` is thrown when we attempt to perform an invalid operation such as setting an Id when there is no setter.

2022-08-19 17:27 UTC, BorisDog commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                    throw new InvalidOperationException($"{nameof(BsonClassMap)} did not provide an instance of {typeof(TClass).Name}.");
Done.

2022-08-19 19:19 UTC, JamesKovacs approved these changes
LGTM

2022-08-19 20:34 UTC, merged