CSHARP-4293: Update with aggregation pipeline fails when used on a OfTypeMongoCollection (OfType<T>).
mongodb/mongo-csharp-driver pull request #869
Opened 2022-08-22 15:43 UTC by DmitryLukyanov

2022-08-23 17:22 UTC, JamesKovacs requested changes
Just need to fix the diff as it looks like more was changed than actually was due to reformatting.

2022-08-23 17:22 UTC, JamesKovacs commented on src/MongoDB.Driver/FilteredMongoCollectionBase.cs
> +                .ToList();
It appears that the only change is the addition of `ToList()` on the end. This makes the diff confusing to review.

2022-08-23 19:40 UTC, DmitryLukyanov commented on src/MongoDB.Driver/FilteredMongoCollectionBase.cs
> +                .ToList();
done

2022-08-23 19:43 UTC, JamesKovacs approved these changes
LGTM

2022-08-24 17:05 UTC, DmitryLukyanov commented
This provided solution is incorrect, instead converting a pipeline argument to regular update document, we should emulate `$SetOnInsert` with aggregate pipeline stage. This was recommended by query team:

    rs:PRIMARY> db.mycoll.update({}, [{$set: {x: {$cond: [{$eq: [{$type: "$_id"}, "missing"]}, 1, 2]}}}], {upsert: true})
    WriteResult({
            "nMatched" : 0,
            "nUpserted" : 1,
            "nModified" : 0,
            "_id" : ObjectId("630561dceb783de551833de9")
    })
    rs:PRIMARY> db.mycoll.find()
    { "_id" : ObjectId("630561dceb783de551833de9"), "x" : 1 }
    rs:PRIMARY> db.mycoll.update({}, [{$set: {x: {$cond: [{$eq: [{$type: "$_id"}, "missing"]}, 1, 2]}}}], {upsert: true})
    WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
    rs:PRIMARY> db.mycoll.find()
    { "_id" : ObjectId("630561dceb783de551833de9"), "x" : 2 }

2022-08-24 18:54 UTC, DmitryLukyanov commented
ready for review

2022-08-24 21:08 UTC, JamesKovacs requested changes
Overall looking good, but we have failures on 3.6 and 4.0. From the EG logs:
```
FAILURE: MongoDB.Driver.MongoCommandException : Command update failed: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'.
```

2022-08-24 21:58 UTC, JamesKovacs approved these changes
LGTM

2022-08-25 11:58 UTC, merged