CSHARP-4319: FLE - maxWireVersion should run on Mongo Server 4.0.x.
mongodb/mongo-csharp-driver pull request #878
Opened 2022-09-15 15:57 UTC by DmitryLukyanov

2022-09-16 16:47 UTC, JamesKovacs requested changes
I don't think we should change `hello` to legacy hello when determining `MaxWireVersion` in our test suite.

2022-09-16 16:47 UTC, JamesKovacs commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                var command = new BsonDocument(OppressiveLanguageConstants.LegacyHelloCommandName, 1);
Using legacy hello will fail when running tests with `apiStrict` enabled. Note that `hello` was backported to earlier versions and is supported on 3.6.21, 4.0.21, 4.2.10, 4.4.2, and 5.0+. (See https://jira.mongodb.org/browse/SERVER-49986 for details.) While `hello` will fail against earlier patch builds of the server, we only test against latest patch of each version in Evergreen. Thus I don't think we need to make this change.

2022-09-16 16:52 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/CoreTestConfiguration.cs
> +                var command = new BsonDocument(OppressiveLanguageConstants.LegacyHelloCommandName, 1);
hmm, it's strange, I changed this because on server 40 that I launched locally, `hello` command has failed.. I don't think that I use too old version, but I will try to download newest server version and check again

2022-09-21 22:34 UTC, JamesKovacs approved these changes
LGTM

2022-09-21 23:09 UTC, merged