CSHARP-4278: Unified runner for logging tests
mongodb/mongo-csharp-driver pull request #879
Opened 2022-09-15 20:55 UTC by BorisDog

2022-09-15 21:08 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        {
I've already implemented this logic in SDAM test runner, so I think we don't need this now, we can discuss it

2022-09-15 21:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        {
https://github.com/DmitryLukyanov/mongo-csharp-driver/commit/8db024528079dbd80244b4aaf2d174db8c12258a#diff-c111e924835b5b0fbf76667b327e1e7e9efe1a7463337a802e73a9f0fe1dd877R51

2022-09-27 23:01 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        {
To simplify our work, we can defer refactoring I did to my next PR

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/IEvent.cs
> +﻿namespace MongoDB.Driver.Core.Events
copyright

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/LogCatergoryHelper.cs
> +        private static readonly IDictionary<Type, string> __catergories = new ConcurrentDictionary<Type, string>();
filename contains typo

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogsTemplates.cs
> +        public static readonly string ConnectionId_Message = $"{{{DriverConnectionId}}} {{{Message}}}";
can we use properties instead public fields?

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogsTemplatesCluster.cs
> +            {
I think better formatting is without tabs (same in other) like here https://github.com/mongodb/mongo-csharp-driver/pull/879/files#diff-8642a2a81535506783eea5811d0946bb45708157d8b1c7cade74e716e9605de8L322:

     private static string[] __clusterCommonParams = new[]
     {

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Logging/StructuredLogsTemplatesCluster.cs
> +        private static string ClusterCommonParams(params string[] @params) => Concat(__clusterCommonParams, @params);
alphabetical order?

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/EndPointHelper.cs
> +        internal static (string host, int port) GetHostAndPort(this EndPoint endPoint) =>
I think better format is with capital letter: 

    internal static (string Host, int Port)

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/ILoggingService.cs
> +﻿using Microsoft.Extensions.Logging;
copyright

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LogEntry.cs
> +        public int ClusterId { get; }
should it really be here? We def can have logging before cluster creating.

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/NullLoggingService.cs
> +﻿using Microsoft.Extensions.Logging;
copyright

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/command-monitoring/CommandLoggingUnifiedTestRunner.cs
> +        // public constructors
it's not necessary

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/command-monitoring/CommandLoggingUnifiedTestRunner.cs
> +﻿/* Copyright 2021-present MongoDB Inc.
2010

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedLogMatcher.cs
> +        public void AssertLogsMatch(LogEntry[] actualLogs, BsonArray expectedLogs)
let's not mix static and non static logic

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
> +                                continue;
can you explain this line?

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +                _client.Cluster.Dispose();
client here is Disposable, why not just client.Dispose?

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +                return OperationResult.FromResult(null);
OperationResult.Empty()

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +            var client = _entityMap.GetClient(targetClientId);
we usually add validation on arguments. In your case, validation that there is no any argument to make sure that we don't silently ignore it

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +            return new(client);
oh, this syntax is interesting, but it looks like for bigger methods it can hide what actual class we create, but for such small ones this looks ok

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateEntitiesOperation.cs
> +                return OperationResult.FromResult(null);
OperationResult.Empty

I've postponed the rest refactoring to unified sdam test runner PR

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateEntitiesOperation.cs
> +            var entities = arguments["entities"].AsBsonArray;
we usually add validation on arguments. In your case, validation that there is no any argument to make sure that we don't silently ignore it

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +                schemaSemanticVersion > new SemanticVersion(1, 11, 0))
it will be at least `1,12`

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        EventType IEvent.Type => EventType.ClusterAddedServer;
we put explicit implementation to the end (in this case to the end of events) with this comment: 

    // explicit interface implementations

2022-09-27 23:38 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +            using (var runner = new UnifiedTestRunner(loggingService: this))
do you think it's really better? Is only loggerFactory needed for a test runner and the rest is garbage there?

2022-09-27 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +                null);
I would recommend adding arguments name for cases when it's not clear from the context (like this one)

2022-09-28 20:42 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/IEvent.cs
> +﻿namespace MongoDB.Driver.Core.Events
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LogEntry.cs
> +        public int ClusterId { get; }
Yes for simplicity. It's commonly used parameter, so cashing it for optimization (if exists).

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/command-monitoring/CommandLoggingUnifiedTestRunner.cs
> +        // public constructors
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedLogMatcher.cs
> +        public void AssertLogsMatch(LogEntry[] actualLogs, BsonArray expectedLogs)
Split to UnifiedLogHelper.cs.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/ILoggingService.cs
> +﻿using Microsoft.Extensions.Logging;
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/NullLoggingService.cs
> +﻿using Microsoft.Extensions.Logging;
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/command-monitoring/CommandLoggingUnifiedTestRunner.cs
> +﻿/* Copyright 2021-present MongoDB Inc.
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
> +                                continue;
`$$matchAsDocument` means that the string value has to be parsed as bson document and validated as a document.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +                return OperationResult.FromResult(null);
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +            var client = _entityMap.GetClient(targetClientId);
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCloseClientOperation.cs
> +                _client.Cluster.Dispose();
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateEntitiesOperation.cs
> +                return OperationResult.FromResult(null);
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateEntitiesOperation.cs
> +            var entities = arguments["entities"].AsBsonArray;
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +                schemaSemanticVersion > new SemanticVersion(1, 11, 0))
Done.

2022-09-28 20:42 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/change-streams/ChangeStreamUnifiedTestRunner.cs
> +            using (var runner = new UnifiedTestRunner(loggingService: this))
We need `loggingService.Logs` as well.

2022-09-28 20:49 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedValueMatcher.cs
> +                                continue;
I meant `continue`

2022-09-28 23:10 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/ClusterAddedServerEvent.cs
> +        EventType IEvent.Type => EventType.ClusterAddedServer;
Done.

2022-09-28 23:11 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/ClusterBuilder.cs
> +                null);
Done.

2022-09-29 00:05 UTC, JamesKovacs requested changes
Why not use `Dictionary<Type, Delegate>` for `EventsPublisher.__eventHandlers`? This would remove the need for the `EventType` enum, `IEvent` interface, explicit interface impl on dozens of event classes, ... It would also remove the possibility of a mismatch between the `Event` derived class and its `IEvent.Type` when we add more events in the future. What do you think?

2022-09-29 01:36 UTC, BorisDog commented
> 
@JamesKovacs Yes, that would make the code simpler. The downside is that we would be introducing two dictionary look-ups for each event and/or log. Beforehand each event handler was resolved once, so the idea was not to introduce unnecessary look-ups on the hot path. Furthermore I think lookup by type is not the most efficient one.

Introducing internal `IEvent` interface is actually an old idea [CSHARP-3433](https://jira.mongodb.org/browse/CSHARP-3433) that introduces more structure to event handling code. We do have a way to achieve the same performance without additional interface, but interface was the most straightforward approach.

2022-09-30 19:40 UTC, BorisDog reviewed
Rebased and incorporated recent spec log tests spec changes.

2022-09-30 19:40 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +    public class UnifiedWaitForEventOperation : IUnifiedEntityTestOperation
@DmitryLukyanov  new op.

2022-09-30 19:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +    public class UnifiedWaitForEventOperation : IUnifiedEntityTestOperation
It's also implemented in my commit :) 
I think it should be inherited from `IUnifiedSpecialTestOperation` because exception in this step means failed test. We will never assert this exception

2022-09-30 19:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +            var clientId = arguments["client"].AsString;
Validate arguments

2022-09-30 19:55 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                events
first tab formatting was better

2022-09-30 19:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +            if (arguments.ElementCount != 3)
This will work, I would recommend using the same validation/assignment approach as in other operations: https://github.com/mongodb/mongo-csharp-driver/blob/master/tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedReplaceOneOperation.cs#L89-L117

2022-09-30 19:58 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +            if (arguments.ElementCount != 3)
at the very least if count will be missed we won't get nullreference exception

2022-09-30 21:53 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                events
Fixed.

2022-10-03 14:15 UTC, DmitryLukyanov approved these changes
Some minor questions and then LGRM

2022-10-03 14:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _eventsLogger.LogAndPublish(new ConnectionPoolOpeningEvent(_serverId, _settings), _connectionFactory.ConnectionSettings);
q: why do we show `connection` settings in a event related to connection pool? Looks wrong to me at first glance

2022-10-03 14:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/EventsPublisher.cs
>                  _eventHandlers[(int)eventType] = eventHandler;
nit: not needed cast, eventType is already `int`

2022-10-03 14:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/EventsPublisher.cs
> +        public void Publish<TEvent>(TEvent @event) where TEvent : struct, IEvent
nit: I think it's enough to have only: `where TEvent : IEvent`, now we consider as `event` anything that is inherited from IEvent (which is a goal of this interface), no need to have more strict restriction

2022-10-03 14:15 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Events/IEvent.cs
> +﻿namespace MongoDB.Driver.Core.Events
not done

2022-10-03 14:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/NullLoggingService.cs
> +        public ILoggerFactory LoggerFactory { get; } = NullLoggerFactory.Instance;
we put static properties before ctor, but regular after

2022-10-03 14:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenWaitForEventTest.cs
> +            Func<IEnumerable<object>, bool> eventsConditionWithFilterByCount = (events) =>
As far as I can see, this is the same logic as before, why did you change it?

2022-10-03 14:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLogHelper.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
2010

2022-10-03 14:15 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                    .Take(_count)
what's the point in this line? Should we just assert that number of events equals to expected?

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _eventsLogger.LogAndPublish(new ConnectionPoolOpeningEvent(_serverId, _settings), _connectionFactory.ConnectionSettings);
Events information is unchanged, for logs we need the `MaxIdleTime` parameter.

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/EventsPublisher.cs
>                  _eventHandlers[(int)eventType] = eventHandler;
Good catch.

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/IEvent.cs
> +﻿namespace MongoDB.Driver.Core.Events
Right, done now.

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/EventsPublisher.cs
> +        public void Publish<TEvent>(TEvent @event) where TEvent : struct, IEvent
You are right, removed.
We do need it other places where where `new TEvent` is used.

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Events/EventsPublisher.cs
>                  _eventHandlers[(int)eventType] = eventHandler;
Good catch.

2022-10-03 18:35 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/NullLoggingService.cs
> +        public ILoggerFactory LoggerFactory { get; } = NullLoggerFactory.Instance;
Done.

2022-10-03 18:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenWaitForEventTest.cs
> +            Func<IEnumerable<object>, bool> eventsConditionWithFilterByCount = (events) =>
I caught this when implementing UnifiedWaitForEvent op.
This is optimization to avoid iterating over all existing events, as opposed to up first instance (in the common case)

2022-10-03 18:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedLogHelper.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
Done.

2022-10-03 18:35 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                    .Take(_count)
Yes we should. The match is relatively complex op, so this avoids iterating over all events, only up to `_count`.
Also we need **at least** `_count`.

2022-10-03 18:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _eventsLogger.LogAndPublish(new ConnectionPoolOpeningEvent(_serverId, _settings), _connectionFactory.ConnectionSettings);
Changed.

2022-10-03 18:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenWaitForEventTest.cs
> +            Func<IEnumerable<object>, bool> eventsConditionWithFilterByCount = (events) =>
Given that we have no tons of events and it's only in test, I think more clear logic (ie 1 step instead 2) is more important. But it will leave this up to you

2022-10-03 18:40 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +                    _eventsLogger.LogAndPublish(new ConnectionPoolOpeningEvent(_serverId, _settings), _connectionFactory.ConnectionSettings);
Changed?

2022-10-03 18:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                timeout => $"Waiting for {_count} {_eventCapturer} exceeded the timeout {timeout}.");
I think it would be good to mention how many expected events we actually caught in the exception

2022-10-03 18:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                    .Take(_count)
Yes, we need `at least`, but I think it's helpful to provide how many expected events we actually caught (similar to what we do currently in master)

2022-10-03 19:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/JsonDrivenTests/JsonDrivenWaitForEventTest.cs
> +            Func<IEnumerable<object>, bool> eventsConditionWithFilterByCount = (events) =>
We do have lots events sometimes, and also lots of tests, so this all adds up.
Also the logic is quite self explanatory.

2022-10-03 19:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForEventOperation.cs
> +                timeout => $"Waiting for {_count} {_eventCapturer} exceeded the timeout {timeout}.");
Done.

2022-10-03 19:56 UTC, DmitryLukyanov approved these changes
LGTM

2022-10-03 20:22 UTC, JamesKovacs approved these changes
LGTM. I especially liked the refactoring to use generic methods instead of dozens of overloads.

2022-10-03 20:22 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Logging/EventsLogger.cs
> +        public void LogAndPublish<TEvent, TArg>(TEvent @event, TArg arg) where TEvent : struct, IEvent
I like how this generic method cleaned up and consolidated the dozens of overloads we had previously. Very nice work!

2022-10-04 00:59 UTC, merged