CSHARP-4328: Verify First in filter works in LINQ3.
mongodb/mongo-csharp-driver pull request #883
Opened 2022-09-26 18:49 UTC by rstam

2022-09-26 18:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2003Tests.cs
> +            var filter = Translate(collection, find.Filter);
Side effect of minor refactoring in `Linq3IntegrationTest`

2022-09-26 18:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +                    x.UpcomingOrders.First().NextTargetDeliveryDate >= startTargetDeliveryDate &&
Use a constant start date instead of `DateTime.UtcNow` so the test is reproducible.

2022-09-26 18:51 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +            var statusFilter = filterBuilder.Where(x => x.SubscriptionStatus == SubscriptionStatus.Active);
Cast to `byte` removed. I'll ask in the ticket why they had it.

2022-09-27 22:17 UTC, JamesKovacs requested changes
Minor changes requested.

Overall I think it worthwhile to include these test cases that demonstrate LINQ3 improvements over LINQ2. It also serves to increase our LINQ test coverage helping to prevent regressions as we add more improvements to LINQ3.

2022-09-27 22:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +            if (!string.IsNullOrEmpty(country))
Line 32 sets `country` to `"USA"`. The assertion below is based on this always being present. You can remove the `if` condition.

2022-09-27 22:17 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +            var country = "USA";
This can be a constant.

2022-09-28 00:50 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +            var country = "USA";
Changed to a parameter instead.

2022-09-28 00:50 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4328Tests.cs
> +            if (!string.IsNullOrEmpty(country))
I was trying to leave the code as similar as possible to the JIRA ticket.

I've made `country` a parameter which can be `null` or `"USA"` so the if condition is no longer a no-op.

2022-09-28 15:44 UTC, JamesKovacs approved these changes
LGTM

2022-09-28 16:20 UTC, merged