CSHARP-4332: Verify that the examples work in LINQ3 to the extent possible.
mongodb/mongo-csharp-driver pull request #884
Opened 2022-09-26 23:26 UTC by rstam

2022-09-26 23:27 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4332Tests.cs
> +            (c => c.InvoiceIdNullable == new InvoiceId(guid), "{ InvoiceIdNullable : '01020304-0506-0708-090a-0b0c0d0e0f10' }"),
The above 4 test cases were modified to do all type conversions client side.

2022-09-26 23:27 UTC, rstam commented on tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
> +    <LangVersion>10</LangVersion>
Not sure if there is any problem using 10 going forward.

2022-09-27 23:29 UTC, JamesKovacs requested changes
Consider using `MemberDataAttribute` instead of `ParameterAttributeDataAttribute`.

2022-09-27 23:29 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4332Tests.cs
> +        private static readonly InvoiceId? invoiceIdNullable = (InvoiceId?) invoiceId;
These should be `_guid`, `_invoiceId`, etc. to follow our naming conventions.

2022-09-27 23:29 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4332Tests.cs
> +        // note: when adding or removing test cases be sure to adjust the Range of values for i below
This is awkward. See below for a possible solution.

2022-09-27 23:29 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4332Tests.cs
> +            [Range(0, 15)] int i)
I played around with a few solutions to make this work better. Making the C# compiler happy about types was a bit of a challenge. The following shim works to transform `__testCases` into something that xUnit `MemberDataAttribute` understands. You can likely riff on this idea and come up with something better. The main advantage is that it no longer requires the range to match the array of test cases.

```
        public static IEnumerable<object[]> GetTestCases()
        {
            return __testCases.Select(testCase => new object[] { testCase.Predicate, testCase.ExpectedFilter });
        }

        [Theory]
        [MemberData(nameof(GetTestCases))]
        public void Where_expression_should_work(Expression<Func<Document,bool>> predicate, string expectedFilter)
```

2022-09-28 16:52 UTC, JamesKovacs approved these changes
Fair enough point keeping the test case as close to the provided repro as possible. And I see what you mean about xUnit being weird about `Expression`. I had half the tests fail simply by passing the lambda back from `GetTestCases` rather than grabbing it from the array. Your solution balances fixing the fragility of the hard-coded number of test cases (my main concern) and keeping the test cases close to the provided repro. LGTM.

2022-09-29 20:24 UTC, closed without merging