CSHARP-4220: Add support for $documents stage.
mongodb/mongo-csharp-driver pull request #885
Opened 2022-09-28 21:37 UTC by rstam

2022-09-28 21:41 UTC, rstam commented on src/MongoDB.Driver/AggregateExpressionDefinition.cs
> +    public interface IHasDocumentSerializer<TDocument>
Let's talk about this. Not sure this is the best approach.

2022-09-28 21:41 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +                    documentSerializer ??= (documents as IHasDocumentSerializer<TDocument>)?.DocumentSerializer ?? sr.GetSerializer<TDocument>();
This is where I need the new `IHasDocumentSerializer` interface.

Let's talk about this.

2022-09-28 21:41 UTC, rstam commented on src/MongoDB.Driver/IAggregateFluentExtensions.cs
> +            this IAggregateFluent<NoPipelineInput> aggregate,
Note the use of `NoPipelineInput` here so that `Documents` can only be called as the first stage.

2022-09-28 23:00 UTC, rstam reviewed
I'm pretty sure I found a way that the originally proposed `IHasDocumentSerializer` interface is not actually needed.

2022-09-28 23:00 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            return Documents(aggregateExpression, documentSerializer);
By passing the `documentSerializer` to *both* the `DocumentsAggregateExpressionDefinition` and the `Documents` method we no longer need the `IHasDocumentSerializer` interface.

2022-09-29 23:35 UTC, JamesKovacs requested changes
`$documents` impl looks great. Only a minor question around whether `Linq3IntegrationTest` is still the best name or not given it can handle both LINQ2 and LINQ3 integration tests.

2022-09-29 23:35 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +        protected IMongoClient GetClient(LinqProvider linqProvider = LinqProvider.V3)
Given that `GetClient` and `GetCollection` can request either the LINQ2 or LINQ3 `MongoClient`, should this test base class still be called `Linq3IntegrationTest`? Should we rename it to `LinqIntegrationTest`?

2022-09-30 15:18 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Linq3IntegrationTest.cs
> +        protected IMongoClient GetClient(LinqProvider linqProvider = LinqProvider.V3)
Discussed over Slack...

Robert:
>This class is never used in testing LINQ2 itself.
>It is only used when testing LINQ3.
>At most it is sometimes used when testing against LINQ3 when we want to write a test to compare what the LINQ3 implementation does to what the LINQ2 implementation did. This doesn't happen often. Most of the time we only care what LINQ3 does.
>We're never going to use this class to write integration tests against LINQ2.
>So I think the name is still OK.

James:
>Valid points. I’m ok with leaving the name as-is. But I’ll have to keep in mind when writing LINQ3 tests that I can swap the provider for comparison purposes. It’s a useful trick when seeing how LINQ2 executed the same expression.

2022-09-30 21:31 UTC, closed without merging