CSHARP-4304: Handle conversions to an interface.
mongodb/mongo-csharp-driver pull request #888
Opened 2022-09-30 18:43 UTC by rstam

2022-09-30 18:45 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4304Tests.cs
> +            var results = queryable.ToList();
I think we should do a full blown integration test with data, but that's going to take awhile to figure out and I wanted to let you look at the work so far.

2022-09-30 18:45 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +                    serializer = operandTranslation.Serializer;
Your suggestion is a one liner (not counting the if statement)!

I like it when fixes are simple.

Hopefully simple is correct in this case. I think it is, see if you can think of any way this could be wrong in other scenarios.

2022-10-03 23:24 UTC, JamesKovacs requested changes
I think the approach is a good one. Just need to turn the unit test into an integration test and we are good to go.

2022-10-03 23:24 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +                    serializer = operandTranslation.Serializer;
Where this will almost certainly break down is explicit interface implementations. I would suggest we don't support this for now and evaluate the use case if/when a user files a ticket complaining.

2022-10-03 23:24 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4304Tests.cs
> +            var results = queryable.ToList();
I agree that we should have a full-blown integration test. The one-liner approach discussed above is sufficient for now (and possibly forever). Let's get the integration test done so we can get this in.

2022-10-06 21:58 UTC, JamesKovacs approved these changes
LGTM

2022-10-07 16:06 UTC, merged