CSHARP-4279: Logs truncation
mongodb/mongo-csharp-driver pull request #891
Opened 2022-10-04 01:33 UTC by BorisDog

2022-10-07 17:23 UTC, rstam commented
As I start to review this PR I'm finding a number of naming issues that I would have raised earlier if I had been part of earlier PRs.

As a general rule class names should not be plural (e.g., `string` not `strings`, `Guid` not `Guids`) with a few exceptions like `XyzSettings`.

Accordingly, I would like to see the following names changed in the new logging code:

EventsLogger => EventLogger
StructuredLogsTemplates => StructuredLogTemplate
LoggingFactory => LoggerFactory (because it returns an `ILoggerFactory` not an `ILoggingFactory`)
EventsPublisher => EventPublisher
EventsLogsFormattingOptions => EventLogFormattingOptions
Extentions => Extensions (spelling)
LogsTemplateProvider => LogTemplateProvider

It would probably make sense to make these changes in a separate PR addressing only the name changes and then rebase this PR on master after pushing those changes to master.

2022-10-07 17:53 UTC, rstam requested changes
See comment about name changes that should be done as a separate PR before this one/

2022-10-07 18:49 UTC, rstam commented
Boris agrees the renamings should be in a separate PR but he wants to do it after this one, so I'm resuming review of this ignoring the naming issues for now.

2022-10-07 19:44 UTC, rstam requested changes

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +    /// Represents the settings for using SSL.
/// Represents the settings for logging.

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// Gets the maximal document size in chars
/// Gets the maximum document size in chars

"maximal" doesn't sound quite right to me.

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// <param name="maxDocumentSize">The maximal document size in chars.</param>
/// <param name="loggerFactory">The logger factory.</param>
        /// <param name="maxDocumentSize">The maximum document size in chars.</param>

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +                MaxDocumentSize == rhs.MaxDocumentSize;
Optionally could be simplified to:

            return
                rhs != null && // or equivalently: !object.ReferenceEquals(rhs, null)
                LoggerFactory == rhs.LoggerFactory &&
                MaxDocumentSize == rhs.MaxDocumentSize;

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// </returns>
Instead of repeating the doc comments from the base class just use:

        /// <inheritdoc/>

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// </returns>
/// <inheritdoc/>

2022-10-07 19:44 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Logging/LoggerExtentions.cs
> +            new EventsLogger<T>(eventSubscriber, null);
Consider:

        public EventsLogsFormattingOptions(int maxCommandDocumentSize)
        {
            MaxDocumentSize = Ensure.IsGreaterThanOrEqualToZero(maxCommandDocumentSize, nameof(maxCommandDocumentSize));
        }

It seems weird to use `=>` when there is no value being returned.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +    /// Represents the settings for using SSL.
Thanks, fixed.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// <param name="maxDocumentSize">The maximal document size in chars.</param>
Done.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// Gets the maximal document size in chars
Done.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +                MaxDocumentSize == rhs.MaxDocumentSize;
Good point, done.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// </returns>
Done.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Configuration/LoggingSettings.cs
> +        /// </returns>
Done.

2022-10-07 20:38 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Logging/LoggerExtentions.cs
> +            new EventsLogger<T>(eventSubscriber, null);
Done.

2022-10-07 21:04 UTC, rstam approved these changes
LGTM

2022-10-11 22:21 UTC, rstam requested changes
Probably LGTM but I had some minor questions.

2022-10-11 22:21 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Logging/EventsLogger.cs
> +          => LogAndPublish(null, @event, skipLog);
It's called `skipLogging` everywhere else

2022-10-11 22:21 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Logging/EventsLogger.cs
> +          => LogAndPublish(null, @event, skipLog);
Not all overloads of `LogAndPublish` take the new `skipLogging` parameter.

I assume that's intentional?

2022-10-11 22:28 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Logging/EventsLogger.cs
> +          => LogAndPublish(null, @event, skipLog);
Renamed.
The other overload is not used in places with where skipping logging is required. So for simplicity added only where it is necessary.
Side note: I believe that this parameter will be removed in [CSHARP-3823](https://jira.mongodb.org/browse/CSHARP-3823)

2022-10-12 01:17 UTC, merged