CSHARP-4273: Cache AWS Credentials Where Possible.
mongodb/mongo-csharp-driver pull request #894
Opened 2022-10-06 15:08 UTC by DmitryLukyanov

2022-10-06 15:11 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
> +        private static readonly TimeSpan __overlapWhenExpired = TimeSpan.FromMinutes(5);
This value was suggested to change up to 5 mins. cc: @blink1073

2022-10-06 15:53 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +        # ECS test is skipped until testing on Linux becomes possible
https://jira.mongodb.org/browse/CSHARP-4343

2022-10-06 17:47 UTC, blink1073 approved these changes
LGTM!

2022-10-06 22:32 UTC, JamesKovacs requested changes
Some minor comments to address but overall looking good.

2022-10-06 22:32 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
> +        // credentials are considered expired when: Expiration - now > 5 mins
Shouldn't this be `Expiration - now < 5 mins`? For example if credentials expire at noon and it's currently 11:50am, `noon - 11:50am = 10 minutes` and credentials don't need to be refreshed yet. But at 11:55am, `noon - 11:55am = 5 minutes` and credentials need refreshing.

Note that this only affects the comment and not the implemented logic, which uses `Expiration - now < 5 mins`.

2022-10-06 22:32 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
>          private AwsCredentials CreateAwsCreadentialsFromAwsResponse(string awsResponse)
Spelling:
`CreateAwsCreadentialsFromAwsResponse` => `CreateAwsCredentialsFromAwsResponse`

2022-10-06 22:32 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
> +            _expiration = expiration != null ? DateTime.Parse(expiration) : null;
The constructor should take the expiration as a `DateTime?`. See `CreateAwsCredentialsFromAwsResponse` below.

2022-10-06 22:32 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
> +            var expiration = parsedResponse.GetValue("Expiration", null)?.AsString;
We should do any input validation here in the factory method rather than delegating to the constructor. For example if the `Expiration` isn't a valid `DateTime` and fails parsing for any reason, it is better to throw in this factory method rather than in the constructor. We should also consider using `DateTime.TryParse` and how to best handle an error where the KMS sends back an invalid `DateTime`.

2022-10-06 23:18 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AwsAuthenticationCredentialsProvider.cs
> +                    throw new InvalidOperationException($"Expiration in AWS response is in invalid datetime format: {expiration}.");
open to suggestions about error message

2022-10-07 16:11 UTC, JamesKovacs approved these changes
LGTM

2022-10-07 16:47 UTC, blink1073 commented on tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
> +            // 4. Override the cached credentials with an "Expiration" that is within thirty seconds of the current UTC time.
I updated https://github.com/mongodb/specifications/pull/1281, with one tweak: this should be one minute.

2022-10-07 18:12 UTC, merged