CSHARP-4331: Make LINQ3 the default LinqProvider.
mongodb/mongo-csharp-driver pull request #897
Opened 2022-10-11 19:34 UTC by rstam

All tests are passing just by finding everywhere that was still defaulting to LINQ2 and changing the default to LINQ3. For the most part the failing tests were failing because they were asserting on LINQ2 expected results (like filters and stages).

Before we flip the switch though we might should refactor those tests to test against both LINQ2 and LINQ3, or perhaps only LINQ3 where appropriate.

2022-10-11 19:35 UTC, rstam commented
@JamesKovacs this PR can wait until you get back since it's not going into 2.18.0.

2022-10-11 20:38 UTC, rstam commented
See also:

https://jira.mongodb.org/browse/CSHARP-4358

2022-11-02 23:43 UTC, JamesKovacs requested changes
Questions inline.

2022-11-02 23:43 UTC, JamesKovacs commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            __linq2Client = new Lazy<MongoClient>(CreateLinq2Client, isThreadSafe: true);
Do we need `Client`, `Linq2Client`, and `Linq3Client`? Even if we keep all three to avoid a cascading change to hundreds of tests, shouldn't `__linq3Client = __client` rather than creating two separate instances on the LINQ3 `MongoClient`?

2022-11-02 23:43 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/AggregateFluentBucketTests.cs
> +            __database = DriverTestConfiguration.Linq2Client.GetDatabase(databaseNamespace.DatabaseName);
Shouldn't this now be tested against LINQ3? Same with all the following tests. If our default is LINQ3, our tests should run against LINQ3. Thoughts?

2022-11-03 23:40 UTC, closed without merging