CSHARP-4294: Support the Azure VM-assigned Managed Identity for Automatic KMS Credentials.
mongodb/mongo-csharp-driver pull request #898
Opened 2022-10-12 00:25 UTC by DmitryLukyanov

2022-10-12 21:16 UTC, BorisDog requested changes

2022-10-12 21:16 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/External/IExternalCredentialsHttpRequestMessageFactory.cs
> +    internal interface IExternalCredentialsHttpRequestMessageFactory
Another option for enabling unit testing,
Instead of introducing `IExternalCredentialsHttpRequestMessageFactory`, `AzureHttpRequestMessageFactory `and additional ctor in `AzureAuthenticationCredentialsProvider`, you could do the similar uri overwriting with `IHttpClientHelper` (or deriving from `HttpClientHelper`).
This approach might simplify both the driver and the testing code.

2022-10-12 21:16 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        var azureProvider = new AzureAuthenticationCredentialsProvider(ExternalCredentialsAuthenticators.Instance.HttpClientHelper, createHttpRequestMessageFactory);
minor:
```
azureProvider = ...
Record.Exception(...)
```
lines in most of test cases
Can be extracted to private method
`Exception CreateCredentialsAsync(...)`

2022-10-12 23:25 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        (result.Expiration - DateTime.UtcNow).Should().BeCloseTo(nearbyTime: TimeSpan.FromSeconds(60), precision: (int)TimeSpan.FromSeconds(10).TotalMilliseconds);
I don't mind, done, but with a bit different values since values 70 and 30 gives a range [40 - 100] where we need [50-70]. In fact it's enough to have value a bit less than 70, but range [60 - 70] looks safer in case if mock server will take more time than we expect

2022-10-12 23:37 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +            => new BsonDocument
missed this, done

2022-10-13 01:31 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +    internal class AzureCredentials : IExternalCredentials
maybe other internal classes can be also sealed, like
AzureAuthenticationCredentialsProvider
AzureHttpRequestMessageFactory

2022-10-13 01:35 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +        public bool IsExpired => _expiration.HasValue ? (_expiration.Value - DateTime.UtcNow) < __overlapWhereExpired : false;
I think we should define the possibility of having null clearly (otherwise the code is not consistent).
Following that it leaves us with two options:
1. Either ctor allows null for `_expiration`
2. `_expiration` becomes not nullable.

2022-10-13 11:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +            if (expiresIn == null || !int.TryParse(expiresIn, out var expiresInSeconds))
I didn't notice it, cool, done

2022-10-13 11:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +    internal class AzureCredentials : IExternalCredentials
done

2022-10-13 11:52 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/AzureAuthenticationCredentialsProvider.cs
> +        public bool IsExpired => _expiration.HasValue ? (_expiration.Value - DateTime.UtcNow) < __overlapWhereExpired : false;
I missed that you concern was about validation inside ctor. Yea, it makes sense to remove it. Done

2022-10-13 20:34 UTC, BorisDog requested changes

2022-10-13 20:34 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/External/HttpClientHelper.cs
> +        public HttpClientWrapper() : this(CreateHttpClient())
IMHO name change is not necessary, but if you changing it, update the filename as well.

2022-10-13 20:34 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Authentication/External/IExternalCredentialsHttpRequestMessageFactory.cs
> +    internal interface IExternalCredentialsHttpRequestMessageFactory
Nice.

2022-10-13 20:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                Action<HttpRequestMessage> withReplacedEndpoint =
btw, finally with C# 10 this can be also written as:
`var withReplacedEndpoint = (HttpRequestMessage httpRequestMessage) => ... ;`

2022-10-13 20:39 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Authentication/External/HttpClientHelper.cs
> +        public HttpClientWrapper() : this(CreateHttpClient())
It's a bit weird to have interface for something that is called `helper`. Good catch about file, done

2022-10-13 20:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                Action<HttpRequestMessage> withReplacedEndpoint =
makes sense, done

2022-10-13 20:46 UTC, BorisDog approved these changes
LGTM

2022-10-17 23:51 UTC, merged