CSHARP-3144: Verify that supplied repro works with LINQ3.
mongodb/mongo-csharp-driver pull request #909
Opened 2022-10-18 05:04 UTC by rstam

2022-10-18 05:09 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $in : [2, '$Items.GoodId'] } } }");
Please verify that you agree this translation is correct.

Is there a way to translate this more simply in filter language (without using `$expr`)?

2022-10-18 05:09 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $anyElementTrue : { $map : { input : '$Items.GoodId', as : 'e', in : { $eq : ['$$e', 2] } } } } } }");
Please verify that you agree this translation is correct.

Is there a way to translate this more simply in filter language (without using `$expr`)?

2022-10-24 23:27 UTC, JamesKovacs requested changes
While the generated MQL produces the correct results, we could use the simplified MQL noted below. The main advantage of the filter language formulation is that since `$expr` isn't used then an index can satisfy the query. See [SERVER-32549](https://jira.mongodb.org/browse/SERVER-32549).

I would suggest investing a few hours to determine how much effort would be required to produce the filter language MQL and whether there would be edge cases that would break this MQL but not the `$expr` formulation.

2022-10-24 23:27 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $in : [2, '$Items.GoodId'] } } }");
This is one potential correct translation, but it does require `$expr`. Another possible translation that doesn’t require `$expr` is:

```
[{$match: {"Items.GoodId": 2}}]
```

Quick testing shows that both produce the same results.

2022-10-24 23:27 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $anyElementTrue : { $map : { input : '$Items.GoodId', as : 'e', in : { $eq : ['$$e', 2] } } } } } }");
The same MQL will work here too because `[{$match: {"Items.GoodId": 2}}]` evaluates to true if any array element has `GoodId: 2`.

2022-10-28 18:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $in : [2, '$Items.GoodId'] } } }");
Latest commit implements this suggestion.

2022-10-28 18:28 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3144Tests.cs
> +            AssertStages(stages, "{ $match : { $expr : { $anyElementTrue : { $map : { input : '$Items.GoodId', as : 'e', in : { $eq : ['$$e', 2] } } } } } }");
Latest commit also handles this case!

2022-10-28 22:00 UTC, JamesKovacs approved these changes
LGTM

I was concerned that we could potentially break an existing query that renders using `$expr` given the narrow requirements in `SelectMethodToFilterFieldTranslator`. But when `SelectMethodToFilterFieldTranslator` doesn’t know how to handle something, it simply falls back to the `$expr` impl by throwing an `ExpressionNotSupportedException`. This allows us some nicely flexibility because we can gradually add more features (if needed) but still fall back to the existing `$expr` impl for all other scenarios.

2022-10-29 16:15 UTC, merged