CSHARP-3136: Add full support for $dateToString in LINQ3.
mongodb/mongo-csharp-driver pull request #911
Opened 2022-10-20 17:29 UTC by rstam

2022-10-20 17:35 UTC, rstam commented on src/MongoDB.Driver/Linq/DateTimeExtensions.cs
> +        public static string ToString(this DateTime @this, string format, string timezone)
Only the `NullableDateTime` overload takes has an `onNull` parameter.

2022-10-20 17:35 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/DateTimeMethod.cs
> +            __toStringWithFormat = ReflectionInfo.Method((DateTime @this, string format) => @this.ToString(format));
This overload is part of the .NET API.

We will use the standard existing overload but will require that the `format` string be a MongoDB format string.

2022-10-20 17:35 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ToStringMethodToAggregationExpressionTranslator.cs
> -            if (TryTranslateInstanceToStringWithNoArguments(context, expression, out var translation) ||
Instead of the `Try` pattern we just determine which method to call and only call the method if fully expect it to succeed except in the case of unsupported expressions.

2022-10-20 17:35 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ToStringMethodToAggregationExpressionTranslator.cs
> +            var dateTimeExpression = method.IsStatic ? arguments[0] : expression.Object;
Note that the `DateTime` value is `arguments[0]` for an extension method and `expression.Object` for an instance method.

2022-10-20 17:35 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/ToStringMethodToAggregationExpressionTranslator.cs
> +            var formatExpression = method.IsStatic ? arguments[1] : arguments[0];
Note that `format` is either argument `0` or `1` depending on whether the method is an extension method or not.

2022-10-26 23:45 UTC, JamesKovacs requested changes
I have some API questions below. Let me know what you think...

2022-10-26 23:45 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Reflection/DateTimeMethod.cs
> +            __toStringWithFormat = ReflectionInfo.Method((DateTime @this, string format) => @this.ToString(format));
Makes sense to use the existing overload but insist that the format string is something that MongoDB understands. It would be messy to parse and convert .NET DateTime format strings to MongoDB equivalent ones.

2022-10-26 23:45 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/NullableDateTimeExtensions.cs
> +        public static string ToString(this DateTime? @this, string format, string timezone, string onNull)
Do we even want to expose `onNull`? A more natural and flexible way to write this in C# would be:

```
var query = coll.AsQueryable().Select(x => new { D2 = x.N.ToString("%Y-%M-%D", null, null) ?? x.D.ToString() });
```

which is translated to:

```
test.coll.Aggregate([{ "$project" : { "D2" : { "$ifNull" : [{ "$dateToString" : { "date" : "$N", "format" : "%Y-%M-%D" } }, { "$toString" : "$D" }] }, "_id" : 0 } }])
```

Note that `onNull` can support arbitrary expressions, not just strings. The existing impl using `??` already can support arbitrary expressions whereas this `ToString` overload cannot. Maybe we should remove this `ToString` overload? What do you think?

Regardless we should have `DateTime?` extension methods for `format` and `format`/`timezone` overloads.

2022-10-27 00:19 UTC, rstam commented on src/MongoDB.Driver/Linq/NullableDateTimeExtensions.cs
> +        public static string ToString(this DateTime? @this, string format, string timezone, string onNull)
That's a neat trick using `??`. But it does generate much more verbose MQL.

I think it's still better to have actual support for the `onNull` parameter because it translates to smaller MQL (and therefore presumably more efficient).

I don't see why you can't use an arbitrary expression for the `onNull` argument value. If there isn't already a test for that I can modify the test to verify that an expression is allowed.

2022-10-27 02:08 UTC, rstam commented on src/MongoDB.Driver/Linq/NullableDateTimeExtensions.cs
> +        public static string ToString(this DateTime? @this, string format, string timezone, string onNull)
See the refactored tests that now include testing that the `onNull` argument can be an expression.

2022-10-28 20:23 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/NullableDateTimeExtensions.cs
> +        public static string ToString(this DateTime? @this, string format, string timezone, string onNull)
I was thinking about this incorrectly. I thought we would need a `ToString` overload with `Expression onNull`. But we can have an expression as long as it evaluates to string. And it wouldn't work if the expression didn't evaluate to a string.

2022-10-28 20:23 UTC, JamesKovacs approved these changes
LGTM

2022-10-28 20:48 UTC, closed without merging