CSHARP-4368: Support Convert to BsonValue in LINQ3.
mongodb/mongo-csharp-driver pull request #912
Opened 2022-10-21 22:26 UTC by rstam

2022-10-21 22:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/PrimitiveSerializationProvider.cs
> +                { typeof(Regex), typeof(RegexSerializer) },
This is a minor bug found while testing support for convert to BsonValue.

It could be factored out to its own ticket if you want.

2022-10-21 22:31 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/RegexSerializer.cs
> +
Another small bug found while testing convert to BsonValue.

This serializer was not handling `null` properly.

2022-10-21 22:31 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstExpression.cs
> +        public static AstExpression ToBool(AstExpression arg)
A small number of new factory methods.

2022-10-21 22:31 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +                TypeCode.Double => AstExpression.ToDouble(operandAst),
`Guid` is conspicuously absent.

We *could* support it, but for one the conversion from `Guid` to `BsonValue` is deprecated because it is ambiguous regarding representation.

What we could do is ignore the representation issue and simply return whatever `BsonBinaryData` is in the database (of unknown representation unless it's `Standard`).

2022-10-21 22:31 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +                    AstExpression.Convert(operandAst, expectedType)); // will fail server side
We could talk about this...

If you think the errors should occur client side that's possibly a reasonable alternative.

2022-10-22 18:52 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/ConvertExpressionToAggregationExpressionTranslator.cs
> +                    AstExpression.Convert(operandAst, expectedType)); // will fail server side
I'm having doubts about all this server side "type checking".

Maybe it's better to just let whatever is stored served side (unexpected or not) come out as a BsonValue.

That does mean you might get unexpected results, but only if the data is invalid.

For example, `(BsonValue)x.IntProperty` might result in a `BsonDouble` if the number stored in the database is a double instead of an int.

2022-11-01 00:06 UTC, JamesKovacs requested changes
Minor naming issue for a test helper method. Otherwise LGTM.

2022-11-01 00:06 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        private void Convert_to_BsonValue_from_TValue_should_work<TValue>(TValue value, string valueAsJson, BsonValue expectedResult, Expression<Func<Document<TValue>, BsonValue>> projection)
While we often name tests using snake_case, we don't name our helper methods like this. I would suggest `AssertCastToBsonValue` or something similar instead.

2022-11-01 02:31 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        private void Convert_to_BsonValue_from_TValue_should_work<TValue>(TValue value, string valueAsJson, BsonValue expectedResult, Expression<Func<Document<TValue>, BsonValue>> projection)
This method is not a simple Assert.

This IS the test.

Normally this would be a `Theory`, but it's got the `TValue` generic parameter, so we need separate `Fact` to introduce the actual `TValue` type.

Let me think about this...

2022-11-02 00:36 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        private void Convert_to_BsonValue_from_TValue_should_work<TValue>(TValue value, string valueAsJson, BsonValue expectedResult, Expression<Func<Document<TValue>, BsonValue>> projection)
I'm not too concerned with the naming since it is in tests. If you feel strongly about the method name, I'm ok leaving it. However these new tests are failing on certain variants in this patch. I haven't looked into why this might be yet. I'll let you investigate before I approve.

2022-11-02 22:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        public static TestCase CreateTestCase<TValue>(
Using a factory method for test cases allows more compact syntax.

2022-11-02 22:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        public void Convert_to_BsonValue_from_TValue_should_work<TValue>(int i, string valueAsJson, string projectionAsString)
This is the *real* test method.

The `Convert_to_BsonValue_from_TValue_should_work_invoker` method is a helper method to work around limitations xUnit has in invoking generic test methods.

2022-11-02 22:20 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4368Tests.cs
> +        private void Convert_to_BsonValue_from_TValue_should_work<TValue>(TValue value, string valueAsJson, BsonValue expectedResult, Expression<Func<Document<TValue>, BsonValue>> projection)
See the latest. There is now just one xUnit test method, which is an invoker for the *real* test method.

These two methods work together to work around limitations in xUnit not being able to invoke generic test methods.

2022-11-02 23:57 UTC, JamesKovacs approved these changes
LGTM

2022-11-03 03:56 UTC, merged