CSHARP-3965: Support OrderBy with an expression that does not resolve to a field.
mongodb/mongo-csharp-driver pull request #918
Opened 2022-10-28 14:39 UTC by rstam

2022-10-28 14:52 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3965Tests.cs
> +                "{ $replaceRoot : { newRoot : '$_sortedDocument' } }");
As I write these comments it occurs to me that some minor changes to the generated MQL might be beneficial:

    { $project : { _document : "$$ROOT", _id : 0, _key1 : expr1, ..., _keyn : exprn } }
    { $sort : { _key1 : d1, ..., _keyn : dn } }
    { $replaceRoot : { newRoot : "$_document } }

Naming the temporary field `_document` is shorter than `_sortedDocument` and also more correct since the document isn't sorted (yet) in the `$project` stage.

Putting the keys at the end of the `$project` stage makes it slightly easier to append a new key. But... it's easy enough no matter what so let's focus on making the generated MQL as logical and readable as possible as opposed to ease of implementation.

2022-10-28 23:09 UTC, JamesKovacs requested changes
Looks great. Minor changes mostly to make the changes you suggested.

2022-10-28 23:09 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3965Tests.cs
> +                "{ $replaceRoot : { newRoot : '$_sortedDocument' } }");
I like renaming `_sortedDocument` to `_document` and it makes sense for the reasons stated. I'm ambivalent on where `_id: 0` should appear. Keeping the keys at the end of the `$project` makes senes to me and if it simplifies the implementation, then I'm good with making that change.

2022-10-28 23:09 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToPipelineTranslators/OrderByMethodToPipelineTranslator.cs
> +
I was initially confused by the magic numbers `1` and `3` and why only these various combinations mattered. I'd suggest adding a comment such as "1 is a $sort stage and 3 is $project/$sort/$replaceRoot".

2022-11-01 00:50 UTC, JamesKovacs approved these changes
LGTM

2022-11-01 03:32 UTC, merged