CSHARP-4391: BsonClassMap should support deserializing structs using a constructor.
mongodb/mongo-csharp-driver pull request #920
Opened 2022-10-28 23:50 UTC by rstam

2022-10-28 23:51 UTC, rstam commented
I'm surprised we didn't already support deserializing structs that had a constructor.

2022-10-29 00:03 UTC, JamesKovacs requested changes
Missing test case.

2022-10-29 00:03 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +
We should test lines 438-442 of the `BsonClassMapSerializer` where we fail if we can't pass all fields to ctor arguments.

2022-10-29 16:04 UTC, rstam commented on tests/MongoDB.Driver.Legacy.Tests/Jira/CSharp218Tests.cs
> +                var expectedMessage = "An error occurred while deserializing the P field of class MongoDB.Driver.Tests.Jira.CSharp218.CSharp218Tests+C: Value class MongoDB.Driver.Tests.Jira.CSharp218
I missed this at first because I hadn't run the *full* test suite (this is in Legacy).

2022-10-29 16:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +    {
Added 6 new tests that test serialization alone.

2022-10-29 16:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +
Done

2022-10-29 16:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +            [BsonConstructor]
This attribute is required because we don't automap constructors unless the class is immutable.

2022-10-29 16:04 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +            [BsonElement("X")] public int X { get; }
This attribute is required because using `[BsonConstructor]` doesn't automatically result in the matching properties being automapped.

This property isn't automapped because it is readonly.

2022-10-31 09:27 UTC, troepolik requested changes

2022-10-31 09:27 UTC, troepolik commented on src/MongoDB.Bson/Serialization/Serializers/BsonClassMapSerializer.cs
> +                if (_isValueType)
it would be better for performance to remove excess checks from here, add class constraint to serializer and add another one for structs

2022-10-31 23:57 UTC, JamesKovacs approved these changes
LGTM. One minor naming inconsistency in a test to fix. No need for me to re-review it.

2022-10-31 23:57 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4391Tests.cs
> +            var t = new U() { Id = 1, X = 2, Y = 3 };
Local variable should be `u`.

2022-11-01 02:26 UTC, merged