CSHARP-2471: Add support for trig functions in LINQ3.
mongodb/mongo-csharp-driver pull request #922
Opened 2022-10-31 19:37 UTC by rstam

2022-10-31 19:43 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstBinaryOperator.cs
> +        Atan2,
Getting the casing in sync with .NET and MongoDB.

2022-10-31 19:43 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Ast/Expressions/AstUnaryOperator.cs
> +        Acosh,
Getting the casing in sync with .NET and MongoDB.

2022-10-31 19:43 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/MethodTranslators/TrigMethodToAggregationExpressionTranslator.cs
> +                MathMethod.Atan2
I know... there's only one, but no harm in mirroring the unary implementation and being future proof.

2022-10-31 19:43 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoDBMath.cs
> +        public static double DegreesToRadians(double degrees)
I couldn't find any methods in .NET to convert degrees to radians or vice versa.

I'm not thrilled with having to use `MongoDBMath.DegreesToRadians`, but there is no way to add a new static method like `Math.DegreesToRadians` because we don't own the `Math` class.

If you and think of a better new public API for these two methods let's discuss.

2022-10-31 19:43 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2471Tests.cs
> +                "$radiansToDegrees" => x => MongoDBMath.RadiansToDegrees(x.X),
Here's the new public API for these two methods in action.

2022-10-31 19:43 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2471Tests.cs
> +        [InlineData("$tanh", 0.0, 0.0)]
Do you think we need more "interesting" test values?

There are lot of zeros in there.

Might be fine... it's not our job to test the server implementation of these methods, but more  interesting values might be better at ensuring we translated to the correct server operator (because a lot of trig functions return 0.0 when called with 0.0).

2022-11-01 00:28 UTC, JamesKovacs requested changes
See my comments on using extension methods for the conversion syntax.

2022-11-01 00:28 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/MongoDBMath.cs
> +        public static double DegreesToRadians(double degrees)
Let's make them extension methods in the `MongoDB.Driver.Linq` namespace. Then instead of writing:

`x => MongoDBMath.DegreesToRadians(x.Value)`

you could instead write:

`x => x.Value.DegreesToRadians()`

We could even shorten these names to `ToRadians()` and `ToDegrees()` as the other unit is implied though we have no way to check. If you want to keep the more verbose `DegreesToRadians` to better match the server functions, I'm good with that too.

2022-11-01 00:28 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2471Tests.cs
> +        [InlineData("$tanh", 0.0, 0.0)]
I think it's fine. The important thing is the translation of C# method calls into the correct MQL, not ensuring that the server's impl of a function's precision remains consistent.

2022-11-01 00:28 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2471Tests.cs
> +                "$radiansToDegrees" => x => MongoDBMath.RadiansToDegrees(x.X),
See above. I think these should be `x.X.ToDegrees()` and `x.X.ToRadians()`, but up for discussion.

2022-11-01 03:30 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoDBMath.cs
> +        public static double DegreesToRadians(double degrees)
I considered this approach, but I think it has major disadvantages.

The first is lack of symmetry with the rest of the trig functions which are static methods in `Math`. So static methods in `MongoDBMath` is the closest we can come to that.

Another is that an extension method pollutes the namespace of `double` (admittedly only if you have the right `using` statement). Worse, we would need multiple extension methods for multiple numeric types.

`MongoDBMath.DegreesToRadians(180)` works because there is an implicit conversion from `int` to `double`.

An extension method on `double` will not be invoked for `180.DegreesToRadians`.

2022-11-02 00:44 UTC, JamesKovacs approved these changes
Valid point about needing extension methods on each numeric type and not being able to rely on implicit conversion. I hadn't thought of that wrinkle.

Your reasoning (as always) is sound. LGTM.

2022-11-04 00:03 UTC, closed without merging