CSHARP-2314: Verify that All works in LINQ3.
mongodb/mongo-csharp-driver pull request #925
Opened 2022-10-31 20:44 UTC by rstam

2022-11-01 00:10 UTC, JamesKovacs requested changes
Missing assertion on the generated MQL.

2022-11-01 00:10 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2134Tests.cs
> +
We should assert the MQL as we do in other tests.

2022-11-01 03:19 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2134Tests.cs
> +
Easier said than done... :)

`All` is a terminal method that returns `bool`, not an `IQueryable` that we can translate into a pipeline that we can assert against.

I'll have to think about whether there is a way to test the MQL.

2022-11-01 23:34 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2134Tests.cs
> +
Oh right! It didn't immediately occur to me that `All()` is a terminal expression returning a `bool`. You could rewrite it as a `Select(predicate).All(x => x)` but this will alter the generated MQL. Given we are proving that `All` works in LINQ3, this test is sufficient as-is.

2022-11-01 23:34 UTC, JamesKovacs approved these changes
LGTM

2022-11-02 23:53 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp2134Tests.cs
> +
I found a good way to assert against the generated stages.

Even though we haven't done this before, I would definitely do it going forward, so I'm happy to have found a decent way to do this!

2022-11-02 23:56 UTC, JamesKovacs approved these changes
Clever. LGTM.

2022-11-02 23:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        private ExecutableQuery<TDocument> _mostRecentExecutableQuery;
The query provider will get garbage collected when the queryable gets garbage collected, which typically happens right after the queryable is "executed".

While adding this field extends the lifetime of the most recent executable query by a little bit, it's usually for an extremely short time.

The only time it won't be immediately garbage collected is if someone hangs on to a queryable and "executes" it over and over. Each time it's executed `_mostRecentExecutableQuery` gets overwritten.

2022-11-02 23:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +            _mostRecentExecutableQuery = executableQuery;
The runtime overhead of an extra assignment statement is negligible.

The impact on garbage collection was discussed above.

2022-11-02 23:58 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        public override BsonDocument[] GetMostRecentPipelineStages()
I chose to return `BsonDocument[]` instead of `AstPipeline` because `AstPipeline` is `internal`.

2022-11-03 00:07 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        private ExecutableQuery<TDocument> _mostRecentExecutableQuery;
Makes sense. When I LGTM'd this earlier, I considered whether we would be potentially leaking references to instances and decided we weren't. You have to explicitly hang onto an instance for this brief caching to be a problem.

2022-11-03 00:07 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +            _mostRecentExecutableQuery = executableQuery;
Agreed.

2022-11-03 00:07 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        public override BsonDocument[] GetMostRecentPipelineStages()
Makes perfect sense.

2022-11-03 03:40 UTC, merged