CSHARP-3236: Verify that nested Contains works in LINQ3.
mongodb/mongo-csharp-driver pull request #926
Opened 2022-10-31 22:30 UTC by rstam

2022-11-01 00:09 UTC, JamesKovacs requested changes
Missing assertion in test. Given that these were omissions/bugs reported in LINQ2 that now work in LINQ3, I think we should incorporate these tests into our suite to prove that LINQ3 now handles these cases.

2022-11-01 00:09 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3326Tests.cs
> +            var result = queryable.Single();
We should assert the returned result here.

2022-11-01 03:17 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3326Tests.cs
> +    public class CSharp3236Tests : Linq3IntegrationTest
The file name was wrong.

I've renamed it.

2022-11-01 03:17 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp3326Tests.cs
> +            var result = queryable.Single();
Yes! An inadvertent omission.

2022-11-02 00:37 UTC, JamesKovacs approved these changes
LGTM

2022-11-03 03:46 UTC, merged