CSHARP-4385: Consider adding Directory.Build.props.
mongodb/mongo-csharp-driver pull request #934
Opened 2022-11-06 19:28 UTC by DmitryLukyanov

2022-11-06 19:48 UTC, DmitryLukyanov commented on CSharpDriver.sln
> +		src\Directory.Build.props = src\Directory.Build.props
it's possible to add this file into solution directory, but given that configuration makes sense only for src folder, probably better to leave it when it's currently placed

2022-11-06 19:53 UTC, DmitryLukyanov commented on src/MongoDB.Bson/MongoDB.Bson.csproj
>      <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.2" PrivateAssets="All" />
we can move this to directory.build.props. If we add this reference to the legacy project. Thoughts?

2022-11-09 20:09 UTC, BorisDog requested changes
Nice optimization!

2022-11-09 20:09 UTC, BorisDog commented on src/Directory.Build.props
> +<Project>
Maybe let's do another one for tests?

2022-11-09 20:09 UTC, BorisDog commented on src/MongoDB.Driver.Legacy/MongoDB.Driver.Legacy.csproj
>      <RootNamespace>MongoDB.Driver</RootNamespace>
Is RootNamespace needed? It's present only in 2 Legacy and Core projects.

2022-11-21 21:53 UTC, BorisDog commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +    <TargetFrameworks>$(TargetFrameworks);net5.0</TargetFrameworks>
I think tests props should not be shared with smoke tests.
Smoke tests intended to be "standalone" projects, and should not share anything with driver specific code.
We might want to consider props for all smoke tests if/when we expand them with more projects.

2022-11-28 16:23 UTC, DmitryLukyanov commented on tests/SmokeTests/MongoDB.Driver.SmokeTests.Sdk/MongoDB.Driver.SmokeTests.Sdk.csproj
> +    <TargetFrameworks>$(TargetFrameworks);net5.0</TargetFrameworks>
I think they can (should?) share some configuration like TF to ensure that all TFs we support works well in consumers application too. But I'm ok to defer this to further tickets, reverted

2022-11-28 16:44 UTC, BorisDog commented on tests/TestsProps/Directory.Build.props
> +<Project>
It looks like `Directory.Build.props` naming is only relevant when the props needs to be applied to all project in same directory.
Maybe is should be called `Tests.Build.props` and optionally the containing directory `BuildProps` (as it's already under tests dir)?

2022-11-28 16:44 UTC, BorisDog commented on tests/TestsProps/Directory.Build.props
> +    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
Any idea what $(DefineConstants) means and why it's not applied to TRACE?

2022-11-28 16:54 UTC, DmitryLukyanov commented on tests/TestsProps/Directory.Build.props
> +    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
in this section you can define different consts (based on condition) that then it will be visible in `#if` construction in tests

2022-11-28 16:54 UTC, DmitryLukyanov commented on tests/TestsProps/Directory.Build.props
> +<Project>
done

2022-11-28 17:28 UTC, BorisDog approved these changes
LGTM.
Nice improvement!

2022-11-28 19:54 UTC, merged