CSHARP-4400: Upgrade xunit to 2.4.2
mongodb/mongo-csharp-driver pull request #935
Opened 2022-11-07 15:37 UTC by BorisDog

SkippableTests removed

2022-11-07 15:37 UTC, BorisDog commented on CSharpDriver.sln
> +# Visual Studio Version 17
Good opportunity to update VS version as well?

2022-11-07 15:41 UTC, DmitryLukyanov commented on CSharpDriver.sln
> +# Visual Studio Version 17
=). I did the same here: https://github.com/mongodb/mongo-csharp-driver/pull/934/files#diff-915489976f8122b3863d80c3d6d98569674566a1d9d7a9080796e16cbac7ecd2R4

2022-11-08 18:26 UTC, DmitryLukyanov approved these changes
Question and then LGTM

2022-11-08 18:26 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
why do we need this change?

2022-11-08 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
To distinguish from `Xunit.Sdk.SkipException` that was introduced in 2.4.2. (we use `Xunit.SkipException` from Xunit.SkippableFact package).

2022-11-08 21:36 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
If xUnit now has `SkipException` why do we still need the SkippableFact nuget package?

2022-11-08 21:48 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
Good question.
That's was my line of thought as well, and I even removed SkippableFact nuget package. Only to discover that raising `Xunit.Sdk.SkipException` marks test as failed and not skipped.

2022-11-08 21:51 UTC, rstam commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
Maybe xUnit now has a different way than `[SkippableFact]` to mark a test as skippable?

2022-11-08 21:58 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
I did not find any. The only way I found is to specify `Skip` reason in the `Fact` attribute.
Also `SkipException` is not referenced anywhere directly in xunit main repository (defined xunit/asserts), so looks like there is not special handling for it.

2022-11-09 14:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
hmm, I even can't create Sdk.SkipException (ie I don't see it from the code). Do you observe different behavior?

2022-11-09 15:29 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
Yes,  new Xunit.Sdk.SkipException(...) works.

2022-11-09 15:29 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
We just need to `Xunit.SkipException` exception which is defined in Xunit.SkippableFact .
The goal is to better support generics, and looks like there are few bugs fixes in past two years.

2022-11-09 19:45 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
I still think that the existence of TWO versions of `SkipException` is a problem. At the very least it's confusing. More likely it's a sign that there is duplicate functionality and we should be able to drop our dependency on the `SkippableFact` nuget package.

2022-11-09 19:55 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
As mentioned above, I've investigated the possibility for dropping `SkippableFact` package. I have not been able to find the matching functionality in any V2 version of xUnit. I'll happy to be mistaken here.
I don't think it's a real problem, as we very rarely use `SkipException` directly.

2022-11-09 20:07 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
We probably need to spend more time on this. I think it's clear that a new SkipException should be used somehow, it's definitely not added just to confuse people. Maybe it's something about this directive https://github.com/xunit/assert.xunit/blob/b78867e1aa4b2aa255b5dfc577f6014812445adb/Sdk/Exceptions/SkipException.cs#L10 that can be configured via csproj..

2022-11-09 20:08 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingXunitTestMethodRunner.cs
> +        private static string[] __skippingExceptionNames = new string[] { typeof(Xunit.SkipException).FullName };
yeah, I didn't see this class until I remove all bin/obj folders

2022-11-09 20:14 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
`XUNIT_VISIBILITY_INTERNAL` is a directive affecting compilation process, so it's not relevant for us.
It would be great if we found a way to remove `SkippableFact` package. We can do this investigation in a follow up ticket.
Important to remember that `SkippableTestMessageBus` for that package is used in `TimeoutEnforcingXunitTestMethodRunner`. So that area will require some attention.

2022-11-09 20:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
>so it's not relevant for us.
you're right, we're working with complied binaries.

>TimeoutEnforcingXunitTestMethodRunner. So that area will require some attention.
that was my main concern initially, so not sure how easy it will be

>We can do this investigation in a follow up ticket.
How much urgent this change now? I would say not really and there is no rush with pushing these changes now. @rstam what do you think?

2022-11-09 20:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
I think we are two unrelated issues here:
1. Enabling generics in tests with this PR
2. Removing SkippableFact package (which from my research can't be done yet)

I think we can safely and easily achieve the original goal of this PR and deal with the second improvement when needed.

2022-11-09 20:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
From what I see, `Enabling generics in tests with this PR` is not too urgent issue to introduce code weirdness. We can simply wait until we will figure out the right and not confusing way to do it.

2022-11-09 21:15 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
My estimation is that we will be able to remove the `SkippableFact` only when upgrading to v3 xUnit or other testing framework.
Having generics support now would be quite convenient, while `code weirdness` will be practically unnoticed.

2022-11-10 19:39 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +using SkipException = Xunit.SkipException;
Added `Xunit.Sdk.SkipException` as skippable exception as well. Now either exception will skip the test.

2022-11-14 22:24 UTC, JamesKovacs requested changes
While these changes make sense and clean up the project quite nicely, something isn't quite right. If you look at the patch build, all base statuses of `Skip` are now `Failed`. Something isn't working correctly on Evergreen even if it is working locally.

2022-11-14 23:26 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
> +    </PackageReference>
Hides this reference from dependent projects.
For example: otherwise `SkippableFact` will be available in `MongoDB.Driver.Tests`.

2022-11-15 00:13 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/MongoDB.Bson.TestHelpers.csproj
> +    </PackageReference>
Ah ok. That makes sense.

So the only remaining question is why all the skipped tests are failing on Evergreen.

2022-11-30 13:21 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/SkippableTestMessageBus.cs
> +            var failed = message as TestFailed;
is it a copy of xunit logic? if no, what the point in this class?

2022-11-30 13:21 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +        private struct YieldNoContextAwaitable
I'm not a big fan of copying this class from the driver, but probably effective change here is placing this helper on some common level which only temporary is Bson level, so is it correct that thsi logic will be moved from here with some later refactoring?

2022-11-30 13:21 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/Logging/LoggableTestClass.cs
> +    public abstract class LoggableTestClass : IDisposable, ILoggingService, ITestExceptionHandler
I like this change

2022-11-30 13:21 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/XunitExtensionsConsts.cs
> -﻿namespace MongoDB.Driver.Core.TestHelpers.XunitExtensions
copyright :)

2022-11-30 13:21 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +            => Bson.TestHelpers.Reflector.SetFieldValue(obj, nameof(_connectionModeSwitch), connectionModeSwitch);
move prefix to using (same in other places if any)?

2022-11-30 19:25 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/ITestExceptionHandler.cs
> +﻿using System;
Done.

2022-11-30 19:25 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +        private struct YieldNoContextAwaitable
Yes exactly, moving the `TaskHelpers` was comlicated. Do you think there should be a comment for that in the code?

2022-11-30 19:25 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/SkippableTestMessageBus.cs
> +            var failed = message as TestFailed;
No, this is functionality implemented in `Xunit.SkippableFact` (not xUnit)
It allows to skip the test when `SkipException` is raised.

2022-11-30 19:25 UTC, BorisDog commented on tests/MongoDB.Driver.Core.TestHelpers/XunitExtensions/XunitExtensionsConsts.cs
> -﻿namespace MongoDB.Driver.Core.TestHelpers.XunitExtensions
Removed this file.

2022-11-30 19:28 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +        private struct YieldNoContextAwaitable
yeah, comment would be good

2022-11-30 19:31 UTC, DmitryLukyanov approved these changes
LGTM. Assuming the rest comments are resolved.

2022-11-30 19:40 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +            => Bson.TestHelpers.Reflector.SetFieldValue(obj, nameof(_connectionModeSwitch), connectionModeSwitch);
It conflicts with `Xunit.Sdk.Refelector`

2022-11-30 19:40 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +        private struct YieldNoContextAwaitable
Added.

2022-11-30 19:46 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/Runner/MongoClientJsonDrivenTestRunnerBase.cs
> +            => Bson.TestHelpers.Reflector.SetFieldValue(obj, nameof(_connectionModeSwitch), connectionModeSwitch);
Not is quite different. Also I would not recommend increasing our dependency in such areas on test framework.

2022-11-30 21:39 UTC, JamesKovacs requested changes
A few questions / minor changes...

2022-11-30 21:39 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +                : timeoutMS <= 0 ? XunitExtensionsConsts.DefaultTestTimeout : TimeSpan.FromMilliseconds(timeoutMS);
This should be named `XunitExtensionsConstants`.

2022-11-30 21:39 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/ITestExceptionHandler.cs
> +namespace MongoDB.Bson.TestHelpers.XunitExtensions.TimeoutEnforcing
I'm not liking that these test helpers - which have nothing to do with BSON - are in the `MongoDB.Bson` namespace. I realize that BSON is the lowest common denominator, but I wonder if we should create a `MongoDB.TestHelpers` project to contain code such as this. Thoughts?

2022-11-30 21:39 UTC, JamesKovacs commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/XunitExtensionsConsts.cs
> +    public static class XunitExtensionsConsts
`XunitExtensionsConstants` to follow our naming conventions.

2022-11-30 21:51 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/XunitExtensionsConsts.cs
> +    public static class XunitExtensionsConsts
Done

2022-11-30 21:51 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/ITestExceptionHandler.cs
> +namespace MongoDB.Bson.TestHelpers.XunitExtensions.TimeoutEnforcing
I like this idea!

2022-11-30 21:51 UTC, BorisDog commented on tests/MongoDB.Bson.TestHelpers/XunitExtensions/TimeoutEnforcing/TimeoutEnforcingTestInvoker.cs
> +                : timeoutMS <= 0 ? XunitExtensionsConsts.DefaultTestTimeout : TimeSpan.FromMilliseconds(timeoutMS);
Done.

2022-12-09 18:13 UTC, JamesKovacs approved these changes
LGTM

2022-12-09 22:21 UTC, rstam requested changes
Overall looks great!

I have one small suggestion. See what you think. If you don't agree with it I'm happy to LGTM as is. Let me know and re-request my review.

2022-12-09 22:21 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +        public static GuidRepresentation _guidRepresentation(this ObjectSerializer obj) => (GuidRepresentation)TestHelpers.Reflector.GetFieldValue(obj, nameof(_guidRepresentation));
Damn you `Xunit.Sdk.Reflector`... :(

Consider putting this at the top of the file to disambiguate once:

    using Reflector = MongoDB.Bson.TestHelpers.Reflector;

and the same in all other files where this happens.

2022-12-09 22:21 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +        public static GuidRepresentation _guidRepresentation(this ObjectSerializer obj) => (GuidRepresentation)TestHelpers.Reflector.GetFieldValue(obj, nameof(_guidRepresentation));
Looks like the only other file where this happens is `MongoClientJsonDrivenTestRunnerBase.cs`

2022-12-09 22:46 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +        public static GuidRepresentation _guidRepresentation(this ObjectSerializer obj) => (GuidRepresentation)TestHelpers.Reflector.GetFieldValue(obj, nameof(_guidRepresentation));
nit: since we already target c# 10, we can try setting global using: https://www.c-sharpcorner.com/article/global-using-directive-in-c-sharp-102/

2022-12-09 23:08 UTC, rstam commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +        public static GuidRepresentation _guidRepresentation(this ObjectSerializer obj) => (GuidRepresentation)TestHelpers.Reflector.GetFieldValue(obj, nameof(_guidRepresentation));
Not sure whether global using applies to the `using Name = FullTypeName` format.

Also not sure in general that we actually want global usings... I'd be pretty cautious about forcing a using statement into every single file. It would have to be a pretty limited set I would think.

I don't think the number of using statements in each file is a problem. It's not like we type them manually, Visual Studio adds them for us automatically (via Ctrl-.).

2022-12-10 00:18 UTC, BorisDog commented on tests/MongoDB.Bson.Tests/Serialization/Serializers/ObjectSerializerTests.cs
> +        public static GuidRepresentation _guidRepresentation(this ObjectSerializer obj) => (GuidRepresentation)TestHelpers.Reflector.GetFieldValue(obj, nameof(_guidRepresentation));
Good suggestion! Done.
I agree that making Reflector a global using is not a trivial decision.

2022-12-10 00:39 UTC, rstam approved these changes
LGTM I think?

You squashed and rebased and force pushed and I can no longer tell what changed since I last reviewed...

2022-12-10 00:43 UTC, BorisDog commented
> LGTM I think?
> 
> You squashed and rebased and force pushed and I can no longer tell what changed since I last reviewed...

Yes sorry, I spent some time on rebasing beforehand and it was just easier that way. The only new changes are namespaces resolutions with master and `using Reflector = MongoDB.Bson.TestHelpers.Reflector;`

2022-12-12 16:34 UTC, merged