CSHARP-4410: Test full support for enums in aggregation expressions
mongodb/mongo-csharp-driver pull request #943
Opened 2022-11-10 20:08 UTC by rstam

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Bson/Serialization/IRepresentationConfigurable.cs
> +    public interface ISerializerWithRepresentationProperty
This allows some serializers to expose a Representation property without making the representation configurable (i.e. no WithRepresentation method).

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/ConvertHelper.cs
> +                    targetType.IsSameAsOrNullableOf(underlyingType))
Notice how the right helper methods make this code much more readable.

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/TypeExtensions.cs
> +        public static bool IsEnum(this Type type, out Type underlyingType)
A bunch of new helper methods.

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Misc/TypeExtensions.cs
> -        public static bool IsGenericType(this Type type)
These helper methods are now obsolete (I think they were only needed back when we targeted netcore1).

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/EnumUnderlyingTypeSerializer.cs
> +        public static IBsonSerializer Create(IBsonSerializer serializer)
Or maybe have the callers handle the nullable enum case before calling this method?

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/KnownSerializers/KnownSerializerFinder.cs
> -        protected override Expression VisitBinary(BinaryExpression node)
This code was about figuring out the correct serializer for an enum constant.

That is now handled (more easily) in the translator.

2022-11-10 20:20 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToAggregationExpressionTranslators/BinaryExpressionToAggregationExpressionTranslator.cs
> +            else if (IsAddOrSubtractExpression(expression))
These are expressions that add or subtract an integer from an enum. The integer is not necessarily a constant.

2022-11-10 20:20 UTC, rstam commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4410Tests.cs
> +        public void Select_with_enum_comparison_should_work(int i, string projectionAsString, string expectedProjectStage, int[] expectedResults)
The projection is passed in as a string here because xUnit does not deal well with `Expression` parameters.

2022-11-10 20:26 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Serializers/EnumUnderlyingTypeSerializer.cs
> +        public static IBsonSerializer Create(IBsonSerializer serializer)
Actually I just checked and all callers handle any issues related to nullable enums before calling this method.

I will remove the if statement and keep the else clause only.

2022-11-15 00:11 UTC, JamesKovacs requested changes
Overall LGTM. Minor naming suggestion and small refactoring.

2022-11-15 01:35 UTC, rstam commented on src/MongoDB.Bson/Serialization/IRepresentationConfigurable.cs
> +    public interface ISerializerWithRepresentationProperty
`ISerializerWithRepresentationProperty` is actually pretty accurate name.

It doesn't necessarily imply that it derives from `IBsonSerializer`... though I see how you would think that.

We have other interfaces named somewhat like this that don't derive from `IBsonSerializer` either:

* IBsonDictionarySerializer
* IBsonPolymorphicSerializer
* IChildSerializerConfigurable
* INullableSerializer
* IEnumUnderlyingTypeSerializer
* ISetWindowFieldsPartitionSerializer
* IWrappedEnumerableSerializer

`IHasRepresentation` is a good name also, but it seems like it is a bit too non-serializer specific. Perhaps `IHasRepresentationSerializer`?

Any further thoughts?

2022-11-15 01:35 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +
Done.

2022-11-15 01:37 UTC, rstam commented on src/MongoDB.Bson/Serialization/Serializers/EnumSerializer.cs
> +
Note that I elected to keep the if statement at the call site to make it clear what's going on.

2022-11-18 17:20 UTC, rstam commented on src/MongoDB.Bson/Serialization/IRepresentationConfigurable.cs
> +    public interface ISerializerWithRepresentationProperty
Renamed to `IHasRepresentationSerializer`.

2022-11-18 23:45 UTC, JamesKovacs approved these changes
LGTM

2022-11-19 00:56 UTC, merged