CSHARP-4343: Enable AWS ECS tests.
mongodb/mongo-csharp-driver pull request #945
Opened 2022-11-11 12:08 UTC by DmitryLukyanov

2022-11-11 12:11 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          # SRC_DIRECTORY is workaround since EG_TOOLS expects "src" folder as a root
I've tried a number of attempts to move this logic on EG tools but with no luck. So here, I copy "mongo-csharp-driver" folder with driver sources into "src" and the content (`run-mongodb-aws-ecs-test.sh`) of "evergreen" folder to ".evergreen". All this structure is expected from EG_TOOLS scripts

2022-11-11 12:11 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          skip_ECS_auth_test: true
ECS works only on linux

2022-11-15 00:39 UTC, JamesKovacs requested changes
Overall looking good. Minor feedback. See below.

2022-11-15 00:39 UTC, JamesKovacs commented on evergreen/evergreen.yml
> +          OS="${OS}" ASSERT_NO_URI_CREDS=true evergreen/run-mongodb-aws-test.sh
`${OS}` shouldn't have any spaces in it and thus doesn't need to be quoted. If we do quote it, we should quote it consistently on line 595 below.

2022-11-15 00:39 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
> +        [SkippableFact]
If this is a `SkippableFact`, shouldn't we have some `RequireEnvironment.Check()` or similar statement to start?

2022-11-15 00:40 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
> +        [SkippableFact]
it was skippable, but not now. Yes, it should be changed

2022-11-15 00:50 UTC, DmitryLukyanov commented on evergreen/evergreen.yml
> +          OS="${OS}" ASSERT_NO_URI_CREDS=true evergreen/run-mongodb-aws-test.sh
done

2022-11-15 00:51 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Communication/Security/AwsAuthenticationTests.cs
> +            (awsContainerRelativeUri != null).Should().Be(isEcs);
this test was wrong, fixed

2022-11-15 00:53 UTC, JamesKovacs approved these changes
LGTM

2022-11-15 11:58 UTC, merged