Atlas search POC
mongodb/mongo-csharp-driver pull request #956
Opened 2022-11-18 18:58 UTC by BorisDog

Based on @dgolub  [project](https://github.com/mongodb-labs/mongo-csharp-search)

Sample usage:
`coll.Aggregate().Search(SearchBuilders<Person>.Search.Text(x => x.Title, "cat")).ToList()`

2022-11-21 15:44 UTC, dgolub reviewed
Integration looks good!  I left a few minor comments and suggestions.

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        /// Ensures that the value of a parameter is greater than or equal to a comparand.
```suggestion
        /// Ensures that the value of a parameter is greater than a comparand.
```

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +                var message = $"Value is not greater than or equal to {comparand}: {value}.";
```suggestion
                var message = $"Value is not greater than {comparand}: {value}.";
```

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver/Search/AggregateFluentBuilder.cs
> +    public static class AggregateFluentBuilder
The reason why I created a separate `AggregateFluentBuilder` class with extension methods rather than modifying `AggregateFluent` was that it was necessary in order to have Atlas Search in a separate assembly.  Now that we're integrating it into the driver, we might want to reconsider this decision.

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver/Search/FuzzyOptions.cs
> +namespace MongoDB.Driver
Should the namespace here be `MongoDB.Driver.Search`, given that it's in a subdirectory?

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver/Search/ScoreDefinitionBuilder.cs
> +    internal sealed class ConstantScoreDefinition<TDocument> : ScoreDefinition<TDocument>
```suggestion
    }
    
    internal sealed class ConstantScoreDefinition<TDocument> : ScoreDefinition<TDocument>
```

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver/Search/SearchBuilders.cs
> +    public static class SearchBuilders<TDocument>
The reason why I introduced a new `SearchBuilders` class rather than extending the existing `Builders` class was that it isn't possible to add static extension methods to a class.  This seems like another decision that would be worth reconsidering now that we're no longer forced into it.  I imagine that it would be a better experience for customers not to have to keep track of type different classes.

2022-11-21 15:44 UTC, dgolub commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +    internal sealed class TextSearchDefinition<TDocument> : SearchDefinition<TDocument>
We're restricting it to just `Text` for now and not adding support for any of the other operators?

2022-11-23 19:46 UTC, JamesKovacs requested changes
Overall looking good. I like the overall direction. @dgolub raises some valid points that we should address. (Thank you, @dgolub!)

A few broad comments...
- We need more testing.
- We should determine if we can integration test given that `$search` only works on Atlas. Good question for the Java team since they implemented `$search` already.
- Support for additional operators beyond `Text`.
- Support for LINQ.
- Investigate whether it is possible to provide a friendlier error message than `MongoServerError: $search not enabled! Enable Search by setting serverParameter mongotHost to a valid "host:port" string`.

With respect to LINQ, we can probably limit it to chaining off of `AsQueryable()`. While it would be nice to support in `where` comprehensions, it adds complexity because `$search` must be the first operator in the pipeline.

2022-11-28 21:02 UTC, rstam reviewed
I think the overall approach integrates with how we support existing pipeline stages.

I've added a few comments here and there on the POC code.

2022-11-28 21:02 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +            IsGreaterThanOrEqualTo(value, 0, paramName);
Same might apply to some of the other refactorings.

Do we really want one Ensure method calling another? Or should each Ensure method be complete by itself?

2022-11-29 16:05 UTC, dgolub commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            bool returnStoredSource = false)
The JSON fields in `$search` are called `highlight` and `count`, but I have no objection to this change if you feel that it will make it easier for customers to understand what the parameters do.

2022-11-29 17:23 UTC, rstam commented on src/MongoDB.Driver/Search/FuzzyOptions.cs
> +namespace MongoDB.Driver.Search
I know there's talk about moving all these classes up one level in the namespace, but maybe we should leave them here.

Being in their own namespace could help in avoiding future name collisions.

2022-11-29 17:23 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +                Ensure.IsBetween(value.Value, min, max, paramName);
The error message will be wrong when value is not null but not between.

The error message won't mention that null is valid.

This is probably a reason for each Ensure method to be self contained.

2022-11-29 17:23 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +            bool returnStoredSource = false)
I realized that the server uses the shorter names.

It's a conflict between our naming conventions and the server's.

I made this comment because normally a parameter names `count` would be of type `int`.

2022-12-01 21:13 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +                Ensure.IsBetween(value.Value, min, max, paramName);
That's a good catch.
I still think that we should and can easily reuse the code. 
We got similar behaviour in the old `IsNull*` methods. I suggest to fix them to in a separate ticket.

2022-12-01 21:41 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> -        private static UpdateDefinitionBuilder<TDocument> __update = new UpdateDefinitionBuilder<TDocument>();
My counter argument is that most of our classes already have private fields using the `_field` or `__staticField` naming convention.

In many cases (such as when validating in setters) an explicit backing field is required.

Why not just standardize on explicit backing fields and that way we can always know by glancing at the top of a class what state the class maintains.

Otherwise we have to tediously search the source file to see if there are any autoproperties we didn't know about.

2022-12-01 21:41 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +            IsGreaterThanOrEqualTo(value, 0, paramName);
Of course! But it changes the error messages.

2022-12-01 21:41 UTC, rstam commented on src/MongoDB.Driver/Search/FuzzyOptions.cs
> +        private int? _maxExpansions;
This is an example of a class where we have to use explicit backing fields.

I would like us to standardize on this approach even in cases where autoproperties could be used.

2022-12-01 21:41 UTC, rstam commented on src/MongoDB.Driver/Search/HighlightOptionsBuilder.cs
> +            => new()
You don't think `=>` should be indented one more tab stop?

Better yet use a method body... :)

2022-12-01 21:41 UTC, rstam commented on src/MongoDB.Driver/Search/HighlightOptionsBuilder.cs
> +            {
You don't think `{` should be indented on tab stop further than `=> new()`?

2022-12-02 00:49 UTC, BorisDog commented on src/MongoDB.Driver/Search/FuzzyOptions.cs
> +        private int? _maxExpansions;
Yes there always will be cases where non trivial setter is required.
That should not deter us from using autoproperties for simpler classes. And especially for cases where set is private or init only.

2022-12-02 00:49 UTC, BorisDog commented on src/MongoDB.Driver/Builders.cs
> -        private static UpdateDefinitionBuilder<TDocument> __update = new UpdateDefinitionBuilder<TDocument>();
I think the key here is finding a good balance between following the existing style and evolving our code base to use new language features and mainstream standards. We have already adopted some mainstream conventions like string interpolation, `nameof`, local methods and other, despite having most of the code written differently. I hope we continue to do so.
Autoproperties are a very good example of a "mainstream" and very loved feature by C# community (which continues to evolve), and I believe it is perceived as sort of "default" in C# dev process.

Like with fields, all properties (auto implemented or not) through the source file, they will always reside in same section, like fields. Given that, and the fact the major part of code is cleaned up, the "state" of the class appears more clear to me. Autoproperties indicate that this is just a simple data holders, no custom properties, no special relation between property and field that needs to be inspected. 

For more complicated classes,  where inspecting class state/functionality becomes is more complicated, and I find using VS built-in class/document explorers very useful.

2022-12-08 19:30 UTC, BorisDog commented
Follow up work in [CSHARP-4440](https://jira.mongodb.org/browse/CSHARP-4440).

2022-12-08 19:30 UTC, closed without merging