CSHARP-4417: ConnectionId should use longs for LocalValue and ServerValue
mongodb/mongo-csharp-driver pull request #974
Opened 2022-11-25 02:00 UTC by JamesKovacs

ConnectionId should use longs for LocalValue and ServerValue to match 64-bit integer connectionId returned from the server.

2022-11-25 04:40 UTC, rstam requested changes

2022-11-25 04:40 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionId.cs
> +        public long LocalValue
Is this a breaking change?

Maybe we should add a new property, `LongLocalvalue` and leave this one alone.

This would be similar to `Enumerable.LongCount` being added while leaving `Enumerable.Count` alone.

2022-11-25 16:59 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionId.cs
> +        public long LocalValue
Yes, this would be a (hopefully minor) breaking change that we could put in 2.19.0. As much as I don't care for `LocalValue` (int) and `LongLocalValue` (long), it is a good suggestion for making this an additive change rather than a breaking one. Good suggestion.

2022-11-25 18:07 UTC, JamesKovacs commented on src/MongoDB.Driver.Core/Core/Connections/ConnectionId.cs
> +        public long LocalValue
Yes, this would be a (hopefully minor) breaking change that we could put in 2.19.0. As much as I don't care for `LocalValue` (int) and `LongLocalValue` (long), it is a good suggestion for making this an additive change rather than a breaking one. Good suggestion.

2022-11-28 17:30 UTC, rstam approved these changes
LGTM

2022-11-28 17:48 UTC, merged