CSHARP-4421: Unify all spec tests in single test project
mongodb/mongo-csharp-driver pull request #977
Opened 2022-11-25 23:13 UTC by BorisDog

This is a prerequisite for both [CSHARP-4422](https://jira.mongodb.org/browse/CSHARP-4422) and for Driver/Core unification.

2022-11-25 23:14 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/MongoDB.Driver.Tests.csproj
> +    <EmbeddedResource LinkBase="Specifications\" Include="..\..\specifications\**\*.json" />
@JamesKovacs no need to split to folders anymore :)
The downside is that `GridFS` tests are included as resources. I think we can ignore that for now.

2022-11-30 20:11 UTC, JamesKovacs requested changes
Minor change requested. And please verify spec test counts are identical on EG before and after the reorganization and namespace changes.

2022-11-30 20:11 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
Previously the reflectors were only used in the file in which they were defined. Now they are split between two files. Let's move all reflectors to a `Reflectors.cs` file in this spec test folder.

2022-11-30 20:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
>Previously the reflectors were only used in the file in which they were defined

that's not really true. Mostly yes, but I think the idea is to define reflector in a class that suites most (`ServerMonitorReflector` in ServerMonitorTests, ServerReflector in ServerTests and etc) and reuse it in the rest of classes. But I agree for different reasons it worked not in all cases

2022-11-30 20:36 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
Oh no... let's not do that.

I'd rather reflectors stay in the one file were they are needed, and normally they'd be private, though sometimes public if we now and then need to call them from somewhere else.

2022-11-30 20:36 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
The general rule should be that `XyzReflector` lives in the `XyzTests.cs` file.

2022-11-30 20:54 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
The challenge here is that the same reflector is used in multiple test files. The other solution - which I'd be good with - is making the reflectors private to each file and duplicating the one `Server._monitor` method.

2022-11-30 21:08 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
Yes, it's not optimal for a test class to be dependent on a different test class/file which is not utils.
I am good with both duplicating and `Reflectors.cs`.
The problem here is that it's not `XyzReflector` and `XyzTests.cs` anymore, it's `XyzReflector`s repeated in multiple other files, so it starts to be messy.

2022-11-30 21:11 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
Also reflectors can't really be private. So there is always temptation to use them accidently in other files.

2022-11-30 22:55 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
I'm happy with either proposed solution - duplicating or `Reflectors.cs`. I'll let @rstam chime in on his preference.

2022-11-30 23:01 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
We can't really duplicate here (as reflectors are not private). So leave as is or `Reflectors.cs` (I got slight preference for `Reflectors.cs` but not a hard one).

2022-11-30 23:13 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
> The challenge here is that the same reflector is used in multiple test files.

Yet that's why reflectors are public.

I'd rather not have multiple reflectors for the same class if we can help it.

> The problem here is that it's not XyzReflector and XyzTests.cs anymore

Why not? I don't see why we can't keep doing that.

> So leave as is or Reflectors.cs

I have a preference for the current way. Reflectors.cs sounds like it's just going to be a giant grab bag of reflectors all in one source file.

2022-12-01 16:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
@JamesKovacs are we good to keep the code as is now?
We probably should think of more creative approach for using reflection in tests in general, in particular to avoid cross dependency between test files.

2022-12-06 23:31 UTC, JamesKovacs requested changes
Minor change and then I think we are good to go. `MockClusterableServerFactory.cs` and `MockConnection.cs` moved to the Core.TestHelpers assembly but the namespace wasn't changed to match.

2022-12-06 23:31 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringProseTests.cs
>          public static IRoundTripTimeMonitor _roundTripTimeMonitor(this IServerMonitor serverMonitor)
We can keep it as-is. I don't like the needed reflectors split between test files, but I don't see a better solution than this at the moment.

2022-12-07 21:51 UTC, BorisDog reviewed
Tests count verified.

2022-12-08 19:11 UTC, JamesKovacs approved these changes
LGTM

2022-12-08 19:14 UTC, merged