CSHARP-4229: Add support for $documents in LINQ.
mongodb/mongo-csharp-driver pull request #984
Opened 2022-12-06 23:29 UTC by rstam

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/IMongoQueryProvider.cs
> +        IBsonSerializer PipelineInputSerializer { get; }
We used to be able to assume that `CollectionDocumentSerializer` always existed, but that's no longer true when doing a LINQ query against a database.

`PipelineInputSerializer` is the same as the `CollectionDocumentSerializer` for LINQ queries against collections, but will be a `NoPipelineInputSerializer` for LINQ queries against a database.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/ExtensionMethods/ExpressionExtensions.cs
> +                return (queryProvider.CollectionNamespace.CollectionName, queryProvider.PipelineInputSerializer);
Pretty much everywhere LINQ3 used to use `CollectionDocumentSerializer` it now uses `PipelineInputSerializer` instead.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        private readonly IMongoDatabase _database;
Only one of `_collection` and `_database` will have a value. The other will be `null`.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/AllMethodToExecutableQueryTranslator.cs
> +                    provider,
We don't know if the query is against a collection or not. `ExecutableQuery.Create` will figure that out by looking at the `provider`.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/ExecutableQuery.cs
> +        private readonly IMongoDatabase _database;
Only one of `_collection` or `_database` will have a value. The other one will be `null`.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +        public static IMongoQueryable<TDocument> Documents<TDocument>(this IMongoQueryable<NoPipelineInput> source, params TDocument[] documents)
I chose two overloads rather than a single overload with a default value of `null` for the `documentSerializer` parameter because `Expression` does not support default parameters.

2022-12-06 23:36 UTC, rstam commented on src/MongoDB.Driver/NoPipelineInput.cs
> +    internal sealed class NoPipelineInputSerializer : IBsonSerializer<NoPipelineInput>, IBsonDocumentSerializer
Needed to play nice with LINQ.

2022-12-09 01:20 UTC, JamesKovacs requested changes
Looking good. Some questions/comments for your consideration.

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/MongoQueryProvider.cs
> +        private readonly IMongoDatabase _database;
Is there anywhere we should assert that either `_collection` or `_database` must be `null` and it is an error for both to have a value?

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/ExecutableQuery.cs
> +            return provider.Collection == null ?
This would be a good place to assert that only `provider.Collection` or `provider.Database` has a non-null value.

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/ExecutableQuery.cs
> +            return $"{(_collection == null ? _database.DatabaseNamespace : _collection.CollectionNamespace)}.Aggregate({_pipeline})";
This could be rewritten as:
```
_collection?.CollectionNamespace ?? _database.DatabaseNamespace
```

If you think the ternary operator is clearer, I'm ok with that construct.

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/ExecutableQuery.cs
> +            var cursor = (_collection, session) switch
`_collection`/`_database` only one not-null assertion logic here?

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/Linq3Implementation/Translators/ExpressionToExecutableQueryTranslators/ExecutableQuery.cs
> +            var cursor = (_collection, session) switch
If so, we would need the assertion logic here too.

2022-12-09 01:20 UTC, JamesKovacs commented on src/MongoDB.Driver/Linq/MongoQueryable.cs
> +        public static IMongoQueryable<TDocument> Documents<TDocument>(this IMongoQueryable<NoPipelineInput> source, params TDocument[] documents)
Good point.

2022-12-09 01:20 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4339Tests.cs
> +        public void Documents_should_throw_when_documents_is_null()
`db.aggregate([{$documents:[{}]}])` is valid. Not terribly useful, but it is valid. Should we allow this?

2022-12-13 23:06 UTC, JamesKovacs approved these changes
LGTM

2022-12-13 23:08 UTC, JamesKovacs requested changes
Just noticed that `$documents` tests are failing on MongoDB 5.0 with:

```
FAILURE: MongoDB.Driver.MongoCommandException : Command aggregate failed: $documents' is not allowed in user requests. (failure)
```

2022-12-14 00:23 UTC, JamesKovacs requested changes

2022-12-14 00:23 UTC, JamesKovacs commented on tests/MongoDB.Driver.Tests/Linq/Linq3ImplementationTests/Jira/CSharp4339Tests.cs
> +        [SkippableFact]
xUnit 2.4.2 changes have been merged and `SkippableFact` no longer exists. These tests will fail compile once you rebase.

2022-12-14 00:26 UTC, JamesKovacs approved these changes
LGTM. Discussed over Slack. Planned to fix the attributes when rebasing and squashing.

2022-12-14 00:33 UTC, merged