CSHARP-4422: Custom xunit test cases discoverer for unified format tests
mongodb/mongo-csharp-driver pull request #987
Opened 2022-12-12 20:05 UTC by BorisDog

- Single runner for all unified tests, replaces 15 unified runners.
- Navigation to unified spec test case (json file) directly via VS TestExplorer
- Introduced `CategoryAttribute(params string[] categories)` as a shortcut for [Trait("Category", "SomeCatergory")]

2022-12-12 20:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
even though it may work, I would still prefer to have a separate class for a test runner. A super class that is responsible for everything (all tests) doesn't look like a good idea almost always.

2022-12-12 20:45 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
Additionally we will probably have more often conflicts when we will implement spec tests even thought it will be about completely different areas

2022-12-12 20:56 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
Take a look at it in the local test explorer, the tests organizations is quite straightforward.
Almost all tests runners differ only by the tests folder path (as the should), so there is no really a point of copy pasting all that code, and a folder basis.
So now adding a spec test folder requires one-liner test method, instead of runner + tests factory.

Could you think of a conflict example that becomes harder with a single runner?

2022-12-16 15:11 UTC, DmitryLukyanov reviewed
Initial comments

2022-12-16 15:11 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
>Take a look at it in the local test explorer, the tests organizations is quite straightforward.

I think, same we can say for runners structure before

>Almost all tests runners differ only by the tests folder path

If it's simple runner, the only logic we actually need is to create a new file. The rest of logic we currently have can be improved. We simply can create a base class that will contain all logic we need including testcase factory and even current Run method. In theory we can end-up with just creating a new file and configure path for simple cases. It's a question whether it's worth it, but it's possible

I really don't like idea about a super class responsible for everything. It gives just a mess since now we actually need to mix all logic between runners. Even now, you spread a runner methods and related helpers across the same .cs file and the situation will become only worse

>So now adding a spec test folder requires one-liner test method, instead of runner + tests factory.

I think it's a good that we need a new file for a runner to encapsulate all particular runner related logic in the same place. The rest of changes can be improved, moving everything into one class is only one option

>Could you think of a conflict example that becomes harder with a single runner?

yes, we all will need to work on the same file. So if at the same time two of us will work on let's say adding new methods here, it will be a merge conflict, it may or may nor be resolved automatically, but the key point we don't need this situation at all

2022-12-16 15:11 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.Cmap.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
I don't see why we need a partial class here

2023-06-16 22:00 UTC, sanych-sun requested changes

2023-06-16 22:00 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestsDiscoverer.cs
> +                    if (_generateAsyncVersion)
Can we simply this code with?:

```
yield return new JsonDrivenTestCase($"{fileName}:{testCase.Name}", testCase.Shared, testCase.Test);

if (_generateAsyncVersion)
{
    var name = $"{fileName}:{testCase.Name}:async";
    var test = testCase.Test.DeepClone().AsBsonDocument.Add("async", true);
    yield return new JsonDrivenTestCase(name, testCase.Shared, test);
}
```

2023-06-16 22:00 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestsDiscoverer.cs
> +    public class UnifiedTestsAttribute : FactAttribute
Do we really need to inherit from the FactAttribute?

2023-06-16 22:06 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestsDiscoverer.cs
> +                    if (_generateAsyncVersion)
Or consider removing of _generateAsyncVersion at all.

2023-06-19 19:56 UTC, sanych-sun approved these changes
LGTM

2023-06-19 20:42 UTC, sanych-sun commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestsDiscoverer.cs
> +
This is not used anymore.

2023-06-19 21:06 UTC, sanych-sun approved these changes
LGTM

2023-06-22 21:49 UTC, rstam requested changes
Overall looks great. Just a few minor comments.

2023-06-22 21:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.Sdam.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
The intended use of `partial` classes is where part of the class is generated by a code generator (which might overwrite the file at any time) and user written code is in a second file that is not overwritten by the code generator.

If the argument for partial classes here is that a class is so big that you feel a need to spread it across multiple files, using partial classes doesn't address the fact that the class is too big.

I would not use `partial` here (or anywhere).

2023-06-22 21:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +        [UnifiedTests("change_streams.tests.unified")]
Consider renaming the attribute to make it clear that this is a "theory":

    [UnifiedTestsTheory("change_streams.tests.unified")]

2023-06-22 21:49 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.cs
> +        [Category("SupportLoadBalancing")]
If `[Category]` is *only* useful in the unified specs space it should probably have a more precise name:

    [UnifiedTestsCategory("SupportLoadBalancing")]

If it is a more general concept that can be used aside from unified tests then the very general name should be OK.

2023-06-23 23:22 UTC, rstam commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.Sdam.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
I won't withhold an LGTM to this PR based on the use of partial classes, but I'm not convinced it ever makes sense to use partial classes.

I'm curious what @JamesKovacs and @sanych-sun think about partial classes?

2023-06-23 23:28 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/UnifiedTestSpecRunner.Sdam.cs
> +    public partial class UnifiedTestSpecRunner : LoggableTestClass
Refactored to regions.

2023-06-23 23:33 UTC, rstam approved these changes
LGTM

2023-08-16 19:21 UTC, merged