CSHARP-4182: Support for Range Indexes.
mongodb/mongo-csharp-driver pull request #988
Opened 2022-12-12 20:11 UTC by DmitryLukyanov

2023-01-06 20:00 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            [Values("DoubleNoPrecision", "DoublePrecision", "Date", "Int", "Long")] string rangeSupportedType,
nit:
1. just `rangeType` or `rangeDataType`
2. should "// test case keys..." comment be before/above the `testCase` argument?

2023-01-06 20:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            BsonValue GetValue<TValue>(TValue value, string rangeSupportedType) => rangeSupportedType switch
Seems that `TValue` is not really used and will always be `int`.
So maybe make it non-generic and then you could skip the string parsing stage?
`"DoubleNoPrecision" => new BsonDouble(value)`
...

2023-01-06 20:11 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                        new BsonDocument { { encryptedKeyWithRangeSupportedType, encrypted0 }, { "_id", 0 } });
You also could just use `new() { { encryptedKeyWithRangeSupportedType, encrypted0 }, { "_id", 0 } }`

2023-01-06 20:15 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                            decryptedValue.Should().Be(BsonValue.Create(value6));
Curious why do we need `BsonValue.Create` here?

2023-01-06 20:22 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                    case "DoublePrecision":
minor: You could combine DoubleNoPrecision and DoublePrecision cases.

2023-01-06 20:25 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                            AssertResult(decryptedValue, rangeSupportedType);
Also do we need `AssertResult`? 
`decryptedValue.Should().Be(BsonValue.Create(value6)); `would not validate the BsonValue type as well?

2023-01-09 17:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __csfleRangeExplicitAlgorithm = new Feature("CsfleRangeExplicitAlgorithm", WireVersion.Server62);
`Explicit` in this context means explicit encryption (ie via ClientEncryption). I agreed that it's better to remove this part. Will do it.

2023-01-09 17:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +        private TEncryptedValue EnsureEncryptedData<TEncryptedValue>(BsonValue encryptedValue) where TEncryptedValue : BsonValue
If we (or libmongocrypt level) don't have a bug, this check is just in case, but I think it's a good check since it's easy to call not a right method since there are 2 almost the same inner methods with the same income arguments and the only difference in a return type

2023-01-09 17:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +                throw new InvalidOperationException($"The encrypted data must be {typeof(TEncryptedValue).Name}, but {butMessage}.");
yeah, good point, will do it

2023-01-09 17:50 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +            Ensure.That(!(_rangeOptions != null && _algorithm != EncryptionAlgorithm.RangePreview.ToString()), "RangeOptions only applies for RangePreview algorithm.");
I will double check it

2023-01-09 17:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            [Values("DoubleNoPrecision", "DoublePrecision", "Date", "Int", "Long")] string rangeSupportedType,
>should "// test case keys..." comment be before/above the testCase argument?

this comment is relevant only to the second input argument, so I would say no, better to place it only on the line when it has meaning

2023-01-09 17:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +            BsonValue GetValue<TValue>(TValue value, string rangeSupportedType) => rangeSupportedType switch
i will check it

2023-01-09 22:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +        private readonly long _sparsity;
>fields don't add any functionality

that's true, but it can be changed later. As we discussed previously, the reason why I prefer this approach: 
1. All code base is in this format already. 
2. This approach splits logic inside class on few simple and clear parts: 
 * Define fields for internal usage
 * Ctor
 * Define props for external usage.

I like this structure. The pain about few lines more in the file is smaller in my opinion comparing it with code consistency (for all cases) and a little bit more clear structure.

2023-01-09 22:53 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +            Ensure.That(!(_rangeOptions != null && _algorithm != EncryptionAlgorithm.RangePreview.ToString()), "RangeOptions only applies for RangePreview algorithm.");
I mean the following case: `_rangeOptions == null` and _`algorithm == RangePreview`

2023-01-09 22:53 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +        /// Min range.
Minimum value

2023-01-09 22:53 UTC, BorisDog commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __csfleRangeExplicitAlgorithm = new Feature("CsfleRangeExplicitAlgorithm", WireVersion.Server62);
Also do we want to call it Preview, to differentiate with future non preview?

2023-01-09 23:04 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                            decryptedValue.Should().Be(BsonValue.Create(value6));
I think this change is relevant in all other cases.

2023-01-09 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +        /// Min range.
done

2023-01-09 23:38 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +            Ensure.That(!(_rangeOptions != null && _algorithm != EncryptionAlgorithm.RangePreview.ToString()), "RangeOptions only applies for RangePreview algorithm.");
it looks like you're right, I will think about it

2023-01-10 19:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                            decryptedValue.Should().Be(BsonValue.Create(value6));
done

2023-01-10 19:22 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __csfleRangeExplicitAlgorithm = new Feature("CsfleRangeExplicitAlgorithm", WireVersion.Server62);
At this point I think we will use the same server version guard. Most-likely the only difference will be removing `Preview` suffix. I would defer any change here to the time when it will be clear what final shape we will end up here with.

2023-01-10 19:35 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/EncryptOptions.cs
> +            Ensure.That(!(_rangeOptions != null && _algorithm != EncryptionAlgorithm.RangePreview.ToString()), "RangeOptions only applies for RangePreview algorithm.");
discussed offline, there is a similar check mentioned in the documentation, but not this one. At this point, I think better to add arguments validation only for arguments combinations that are restricted in the spec

2023-01-18 21:23 UTC, BorisDog requested changes
Few minor comments.

2023-01-18 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                _ => throw new Exception($"Unsupported rangeSupportedType {rangeSupportedType}.")
nit: `$"Unsupported {nameof(rangeSupportedType)} {rangeSupportedType}."` or even better
`new ArgumentException($"Unsupported nameof(rangeSupportedType) {rangeSupportedType}.", nameof(rangeSupportedType))`

2023-01-18 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                ? clientEncryption.EncryptExpressionAsync(expression, encryptOptions).GetAwaiter().GetResult()
I would recommend to shift away from using `GetAwaiter().GetResult()` anti-pattern.
You can return `task` here, and make the whole test async.

2023-01-19 21:39 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                ? clientEncryption.EncryptExpressionAsync(expression, encryptOptions).GetAwaiter().GetResult()
I'm ok with this approach, but don't really want to change unrelated tests in this file just to make them compiled after this change. So I would use an old approach for this file

2023-01-19 21:40 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                _ => throw new Exception($"Unsupported rangeSupportedType {rangeSupportedType}.")
I prefer the first one, since we throw in test in majority of cases only `Exception`, done

2023-01-19 21:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                                    encryptOptions.With(rangeOptions: new RangeOptions(sparsity: 1, min: BsonValue.Create(0), max: BsonValue.Create(200), precision: 2)),
no, it's needed. Since the input type is `Optional<BsonValue>`, otherwise, it's not compiled

2023-01-19 23:12 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                                    encryptOptions.With(rangeOptions: new RangeOptions(sparsity: 1, min: BsonValue.Create(0), max: BsonValue.Create(200), precision: 2)),
I see, then let's use `(BsonValue)0`?

2023-01-19 23:12 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                _ => throw new Exception($"Unsupported {nameof(rangeSupportedType)} {rangeSupportedType}.")
`ArgumentException` is used a lot in the driver in such cases already, also it's more suitable exception type her, while `Exception` should be used only when there is no better specific exception.
Up to you.

2023-01-19 23:12 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                ? clientEncryption.EncryptExpressionAsync(expression, encryptOptions).GetAwaiter().GetResult()
Isn't this a new method used only by the new `RangeExplicitEncryptionTest` test?

2023-01-19 23:14 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                ? clientEncryption.EncryptExpressionAsync(expression, encryptOptions).GetAwaiter().GetResult()
Yes, but this test touches `Insert` that then touches everything else

2023-01-19 23:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                                    encryptOptions.With(rangeOptions: new RangeOptions(sparsity: 1, min: BsonValue.Create(0), max: BsonValue.Create(200), precision: 2)),
I would prefer `BsonValue.Create`. If you have a factory method, I would use it. NOTE: no huge logic happens behind the scene, it will be almost the same logic as you suggest

2023-01-19 23:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                _ => throw new Exception($"Unsupported {nameof(rangeSupportedType)} {rangeSupportedType}.")
it's interesting, I expected that we use it rare than it actually happen. We still use: `throw new Exception` more often.. but I'm ok to change it

2023-01-19 23:53 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                _ => throw new Exception($"Unsupported {nameof(rangeSupportedType)} {rangeSupportedType}.")
done

2023-01-19 23:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/client-side-encryption/prose-tests/ClientEncryptionProseTests.cs
> +                ? clientEncryption.EncryptExpressionAsync(expression, encryptOptions).GetAwaiter().GetResult()
discussed offline, changed

2023-01-20 00:04 UTC, BorisDog approved these changes
LGTM.

2023-01-23 23:10 UTC, merged