CSHARP-4440: Incorporate MongoDB.Labs.Search library
mongodb/mongo-csharp-driver pull request #989
Opened 2022-12-12 23:16 UTC by BorisDog

2022-12-13 20:51 UTC, dgolub reviewed
Left a couple of minor suggestions.  Otherwise, the changes look great.

2022-12-13 20:51 UTC, dgolub commented on src/MongoDB.Driver/Search/SearchRange.cs
> +        /// Initializes a new instance of the <see cref="Range{TValue}"/> class.
```suggestion
        /// Initializes a new instance of the <see cref="SearchRange{TValue}"/> class.
```

2022-12-13 20:51 UTC, dgolub commented on src/MongoDB.Driver/Search/SearchDefinitions.cs
> +                { "tokenOrder", _tokenOrder.ToCamelCase(), _tokenOrder == AutocompleteTokenOrder.Sequential },
```suggestion
                { "tokenOrder", _tokenOrder.ToCamelCase(), _tokenOrder != AutocompleteTokenOrder.Any },
```

This should be more future-proof in case they add other token order options.

2022-12-13 20:51 UTC, dgolub commented on src/MongoDB.Driver/Search/SearchDefinitions.cs
> +        private static BsonValue ToBsonValue(TField value) =>
This is probably enforceable at compile time using the new generic math stuff that they added in the latest C# version, but I'm assuming that we can't use that for backward compatibility reasons?

2022-12-13 22:06 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchRange.cs
> +        /// Initializes a new instance of the <see cref="Range{TValue}"/> class.
Thanks.

2022-12-13 22:06 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitions.cs
> +                { "tokenOrder", _tokenOrder.ToCamelCase(), _tokenOrder == AutocompleteTokenOrder.Sequential },
Thanks, good catch!

2022-12-13 22:06 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitions.cs
> +        private static BsonValue ToBsonValue(TField value) =>
Yeah backward compatibility, I wish we could use that.

2022-12-15 18:39 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        public SearchDefinition<TDocument> GeoWithin<TCoordinates, TField>(
IIRC generic type inference fails.

2022-12-15 21:18 UTC, rstam reviewed
This is my first pass at reviewing.

Overall this looks great.

I do think we need to be more careful about naming things in a way that doesn't risk name collisions now or in the future.

For example, you named a class `SearchCountOptions` to avoid colliding with the existing `CountOptions` class. This is good.

We should use the same naming convention for all our search related classes, both for consistent naming and to avoid future possible name collisions.

So for example, rename `FuzzyOptions` to `SearchFuzzyOptions` and `HighlightOptions` to `SearchHighlightOptions` and similarly for all our new classes.

I realize that all these new classes are in a `.Search` sub-namespace and thus are technically unambiguous in the face of name collisions, but only when prefixing them with full or partial namespaces. Let's just avoid potential collisions in the first place and adopt a consistent naming convention, even if it does make the type names slightly longer. Shorter is not always better when it creates ambiguity (either real ambiguity, as in a compile time error, or conceptual ambiguity such `QueryDefinition` vs `SearchQueryDefinition`, where the first doesn't sound like it has anything to do with Search and sounds more like it might apply to Find).

Once we've worked through these renaming suggestions I would like to review again in more detail.

Good work overall!

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Search/SpanDefinition.cs
> +    public abstract class SpanDefinition<TDocument>
Rename class to SearchSpanDefinition

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Search/SpanDefinitionBuilder.cs
> +    public sealed class SpanDefinitionBuilder<TDocument>
Rename class to SearchSpanDefinitionBuilder

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Search/SpanDefinitionBuilder.cs
> +    internal sealed class FirstSpanDefinition<TDocument> : SpanDefinition<TDocument>
Rename class to FirstSearchSpanDefinition

Similarly for the rest of the classes in this file

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        /// <summary>Gets a <see cref="FilterDefinitionBuilder{TDocument}"/>.</summary>
I'm not a fan of these changes... as you now.

Also not a fan of random diffs that make reviewing changes more difficult.

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        public static SearchFacetBuilder<TDocument> Facet { get; } = new SearchFacetBuilder<TDocument>();
Rename property to SearchFacet

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        public static PathDefinitionBuilder<TDocument> Path { get; } = new PathDefinitionBuilder<TDocument>();
Rename property to SearchPath

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        public static ScoreDefinitionBuilder<TDocument> Score { get; } = new ScoreDefinitionBuilder<TDocument>();
Rename property to SearchScore

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        public static ScoreFunctionBuilder<TDocument> ScoreFunction { get; } = new ScoreFunctionBuilder<TDocument>();
Rename property to SearchScoreFunction

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/Builders.cs
> +        public static SpanDefinitionBuilder<TDocument> Span { get; } = new SpanDefinitionBuilder<TDocument>();
Rename property to SearchSpan

2022-12-15 21:18 UTC, rstam commented on src/MongoDB.Driver/PipelineStageDefinitionBuilder.cs
> +        {
Just wondering whether we have the best ordering of parameters here.

For example, if indexName is the most commonly used optional parameter, maybe it should be the first optional parameter.

I don't actually know what parameters are more likely to be used than others. I just want to make sure we get the optimal parameter ordering right the first time, because we can't change it later.

If we do change the order let's be sure to change it the same way everywhere.

2022-12-24 00:09 UTC, BorisDog reviewed
I am not a big fun of longer names, especially as Search namespace makes this a non issue. In our case actual names are less important, as mostly Builders are expected to be used. Also most of the classes are internal.
I don't think this change will have noticeable impact on our API, so made this change.

2023-01-10 21:17 UTC, rstam requested changes
Apologies that there are many comments.

Overall this looks great and these are just small comments to fine tune and polish the result.

2023-01-10 21:17 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/MongoQueryableTests.cs
> +        }
Helper method:

        private IMongoQueryable<Person> CreateSubject()
        {
            var client = DriverTestConfiguration.Linq3Client;
            var database = client.GetDatabase(DriverTestConfiguration.DatabaseNamespace.DatabaseName);
            var collection = database.GetCollection<Person>(DriverTestConfiguration.CollectionNamespace.CollectionName);
            return collection.AsQueryable();
        }

2023-01-12 01:27 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
I've put the path first.
But I think `relation` should come after `geometry`, as we specify the main "query" object first and then all parameters.
I thinks it's also sort of a convention, some examples:
[NetTopologySuite](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_Relate_NetTopologySuite_Geometries_Geometry_System_String_)
[ArgGic](https://developers.arcgis.com/net/api-reference/api/netwin/Esri.ArcGISRuntime/Esri.ArcGISRuntime.Geometry.GeometryEngine.Relate.html#Esri_ArcGISRuntime_Geometry_GeometryEngine_Relate_Esri_ArcGISRuntime_Geometry_Geometry_Esri_ArcGISRuntime_Geometry_Geometry_System_String_)

2023-01-12 01:27 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        public SearchDefinition<TDocument> MoreLikeThis(IEnumerable<TDocument> like) =>
This is probably a good suggestion. I think we can think about this in a follow up ticket.

2023-01-12 01:27 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/MongoQueryableTests.cs
> +        private readonly IMongoQueryable<Person> _queryable;
Thanks, I will consider this in the next round.

2023-01-13 05:39 UTC, rstam requested changes
I can see the finish line!

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            };
It's nice that you can reuse the same variable name on different cases!

I still think a few casts are called for to make clear that short integral values are converted to int:

        private static BsonValue ToBsonValue(TField value) =>
            value switch
            {
                sbyte v => (int)v,
                byte v => (int)v,
                short v => (int)v,
                ushort v => (int)v,
                int v => v,
                uint v => (int)v,
                long v => v,
                double v => v,
                DateTime v => v,
                _ => throw new InvalidCastException()
            };

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            : base(OperatorType.Regex, path, score)
Indent call to : base one more tab.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            : base(OperatorType.Text, path, score)
Indent call to : base one more tab.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            : base(OperatorType.Wildcard, path, score)
Indent call to : base one more tab.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// Creates a search definition that combines two or more operators into a single query.
/// Creates a builder for a search definition that combines two or more operators into a single query.
 
or maybe:

        /// Creates a builder for a compound search definition.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
I still think the order should be:

    path, relation, geometry

for clarity and readability.

Consider these examples as illustrations of this order being more readable because the parameters are in the same order as the english language phrase describing the operation:

    SearchDefinitionBuilder<TDocument> search;

    // search for properties completely within a county
    // i.e. property is within county
    search.GeoShape(x => x.PropertyBoundary, GeoShapeRelation.Within, countyBoundary)

    // search for properties that are at least partially in a county
    // i.e. property intersects county
    search.GeoShape(x => x.PropertyBoundary, GeoShapeRelation.Intersects, countyBoundary)

    // search for properties that are not in a county
    // i.e. property is disjoint with county
    search.GeoShape(x => x.PropertyBoundary, GeoShapeRelation.Disjoint, countyBoundary)

    // search for the county a property is completely contained in
    // i.e. county contains property
    search.GeoShape(x => x.CountyBoundary, GeoShapeRelation.Contains, propertyBoundary);

    // search for all counties a property is even partially contained in
    // i.e. county intersects property
    search.GeoShape(x => x.CountyBoundary, GeoShapeRelation.Intersects, propertyBoundary);

@JamesKovacs you should probably look at this public API decision and chime in also.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// <param name="area">Object that specifies the geo object to search within./// </param>
/// <param name="area">Object that specifies the area to search within./// </param>

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        /// <param name="area">Object that specifies the geo object to search within./// </param>
/// <param name="area">Object that specifies the area to search within./// </param>

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            Range(new ExpressionFieldDefinition<TDocument>(path), range, score);
Indent one more tab stop

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchFacetBuilder.cs
> +            string name,
I think this is the exception to putting the path first. `name` should go first.

We're building a facet, and the parameter to building a facet are `name` + `everything else`, so `name` should go first and `everything else` after that.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchFacetBuilder.cs
> +                { "numBuckets", _numBuckets, _numBuckets != null }
Does this even work? I would expect to see:

                { "numBuckets", () => _numBuckets.Value, _numBuckets != null }

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchFuzzyOptions.cs
> +        }
Missing blank line

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchHighlightOptions.cs
> +        }
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchMetaResult.cs
> +    public sealed class SearchMetaCountResult
This class is impossible to instantiate. Either add a constructor (and remove `private set`) or just make the class mutable (public `set`).

Yes it's a shame we can't use `init` because we are targetting some ancient TFs.

I think the claim that this class is OK as is just because the serializers can get around the non-instantiability of the class is not a convincing argument.

Same for the other classes in this file.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchPathDefinition.cs
> +        public static implicit operator SearchPathDefinition<TDocument>(string[] fieldNames) =>
Would there be any point in adding a `List<string>` overload for symmetry with the other methods?

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchPathDefinitionBuilder.cs
> +            Single(new ExpressionFieldDefinition<TDocument>(field));
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchPathDefinitionBuilder.cs
> +        };
This formatting makes the braces look like the body of a method. Consider this instead:

        public override BsonValue Render(IBsonSerializer<TDocument> documentSerializer, IBsonSerializerRegistry serializerRegistry) =>
            new BsonDocument()
            {
                {  "value", _field.Render(documentSerializer, serializerRegistry).FieldName },
                {  "multi", _analyzerName }
            };

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchPathDefinitionBuilder.cs
> +    }
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchPathDefinitionBuilder.cs
> +        };
This formatting makes the braces look like a method body. Consider this instead:

        public override BsonValue Render(IBsonSerializer<TDocument> documentSerializer, IBsonSerializerRegistry serializerRegistry) =>
            new BsonDocument()
            {
                { "wildcard", _query }
            };

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +    {
We normally put the static members in a #region at the top of the class:

        #region static
        /// <summary>Empty range.</summary>
        public static SearchRange<TValue> Empty { get; } = new(default, default, default, default);
        #endregion

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +    public static class SearchRangeBuilder
It's a bit odd to see factory methods and extension methods in the same class.

Possibly consider moving the extension methods to `SearchRangeExtensions` class?

Not a big deal. Your choice.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +            => new(value, searchRange.Max, false, searchRange.IsMaxInclusive);
Consider adding some parameter names for clarity:

            => new(min: value, searchRange.Max, isMinInclusive: false, searchRange.IsMaxInclusive);

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +            => new(value, searchRange.Max, false, searchRange.IsMaxInclusive);
i.e. when I read `false` I don't know what it means without navigating to the method implementation, and `isMinInclusive: false` documents what `false` means in this case.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +            => new(value, searchRange.Max, false, searchRange.IsMaxInclusive);
Same for other methods below.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchRange.cs
> +            => SearchRange<TValue>.Empty.Lte(value);
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchScoreDefinitionBuilder.cs
> +    }
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchScoreFunctionBuilder.cs
> +            => new GaussSearchScoreFunction<TDocument>(path, origin, scale, decay, offset);
Indent one more tab stop

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchScoreFunctionBuilder.cs
> +            => Gauss(new ExpressionFieldDefinition<TDocument>(path), origin, scale, decay, offset);
Indent one more tab stop

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchSpanDefinitionBuilder.cs
> +        /// <param name="path">The indexed field or fields to search.</param>
Probably better if doc comments are in the same order as the parameters.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/AggregateFluentBase.cs
> +            SearchDefinition<TResult> query,
Rename `query` to `searchDefinition` to be consistent with all other `Search` methods.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Misc/Ensure.cs
> +        /// Ensures that the value of a parameter is greater than a comparand.
Carefully double check alphabetical order of methods?

Watch for: `HasValue`, `IsGreaterThan`, `IsGreaterThanOrEqualTo`.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/MongoQueryableTests.cs
> +        private readonly IMongoQueryable<Person> _queryable;
Don't forget to switch from constructor setup to `CreateSubject` helper method.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +                            new GeoJsonPolygon<GeoJson2DGeographicCoordinates>(
Indentation is wrong on this line.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/SearchDefinitionBuilderTests.cs
> +                        })));
Missing blank line.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/SearchPathDefinitionBuilderTests.cs
> +        }
Missing blank line

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +                BsonDocument.Parse("{ $search: { text: { query: 'foo', path: 'bar' } } }"));
Simplify to:

            var stages = RenderStages(result, BsonDocumentSerializer.Instance);
            stages[0].Should().Be("{ $search: { text: { query: 'bar', path: 'foo' } } }");

No need for `BsonDocument.Parse`

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +                BsonDocument.Parse("{ $search: { text: { query: 'foo', path: 'bar' } } }"));
Same for all other new tests immediately below.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +            var builder = new SearchDefinitionBuilder<BsonDocument>();
Add a blank line after Arrange section.

Same for other new tests below.

2023-01-13 05:39 UTC, rstam commented on tests/MongoDB.Driver.Tests/PipelineDefinitionBuilderTests.cs
> +            var result = pipeline.Search(builder.Text("bar", "foo"));
Add a blank line after Act section.

Same for other new tests below.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +    internal sealed class MoreLikeThisSearchDefinition<TDocument> : OperatorSearchDefinition<TDocument>
@JamesKovacs  let's discuss this one.

2023-01-13 05:39 UTC, rstam commented on src/MongoDB.Driver/Search/SearchFacetBuilder.cs
> +            string name,
Same for all methods in this file.

2023-01-14 01:23 UTC, rstam requested changes
Looks like we're only a few issues away from being done.

Besides the requested changes here we have the following design issues to discuss with @JamesKovacs 

* GeoShape parameter order
* MoreLike with partial documents

2023-01-14 01:23 UTC, rstam commented on tests/MongoDB.Driver.Tests/Search/MongoQueryableTests.cs
> +                .Where(x => x.FirstName == "Alexandra")
Remove the call to `Where`?

2023-01-14 01:23 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
Do you need to edit your comment? There are multiple `polygon` parameters.

I see nothing wrong with adding more (possibly optional) parameters at the end.

The following looks fine to me:

    GeoShape(point, GeoShapeRelation.Within, polygon, padding, threshold)

2023-01-16 18:28 UTC, rstam requested changes

2023-01-16 18:28 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
Note that in our own documentation the order is `path`, `relation`, `geometry`:

https://www.mongodb.com/docs/atlas/atlas-search/geoShape/

2023-01-16 18:31 UTC, rstam requested changes

2023-01-16 18:31 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
This is the example from our documentation:

    {
        "$search": {
           "index": <index name>, // optional, defaults to "default"
           "geoShape": {
              "path": "<field-to-search>",
              "relation": "contains | disjoint | intersects | within",
              "geometry": <GeoJSON-object>,
              "score": <score-options>
           }
    }

2023-01-16 19:50 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +        public SearchDefinition<TDocument> MoreLikeThis(IEnumerable<TDocument> like) =>
I think typed overload is convenient. `morelikethis` documentation gives example of executing `morelikethis` queries with objects returned by previous queries. Also rendered document does not have to be entire document, as null can be omitted.
With such usage pattern in mind typed overload is useful. 

I agree that `BsonDocument` overload would be useful, added.

2023-01-16 19:50 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +            };
> it's about what Range needs.

Missed this nuance, that's a good point! Done.

2023-01-16 23:54 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
All our search operators are in form of `Operator(subject, queryObject, params)`, which happens to align with general convention for geospatial libs, of `Relate(Geomerty, relation, params)`. So with that in mind, the API should be:
`GeoShape(point, polygon, relation, padding, threshold)`. It's also more intuitive imho. 

If you think we should match the ordering of parameters to the official docs, we could do that (even that there are some problematic nuances with such approach). In this case we should match rest of the operators as well, and alternate the position of the `path` argument (it does not always come first).

2023-01-17 00:04 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
I didn't mean to propose that we should slavishly follow whatever order the server documentation is in. The server documentation is not consistent with itself. We should be consistent with ourselves.

I just meant this particular example as showing that I'm not the only one who thinks of this operation using the same order as I would say them in: `path`, `relation`, `geometry`. As in "county contains property", instead of "county property contains" (which is not grammatical).

Doesn't sound like we're getting any closer to a consensus, since we each are coming at this from different directions. I think it should be "readable" (and to my mind more "intuitive"). You think it should be consistent with external libraries that have nothing to do with our driver (and to your different interpretation of what is "intuitive").

I'm just going to defer to @JamesKovacs  on this one. If James wants to go the same way you are suggesting, then we will go that way. I won't like it, but I will accept it.

2023-01-17 00:33 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
Yes I understand the grammatical argument, but I don't think we should try to follow this approach at all costs, I see it more as "nice to have". Yes, those libraries have nothing to do with out driver, but I think their conventions in this area are sort of a good standard.

Reminder: NetTopologySuite is used by Microsoft EF core, CosmosDB and Npsql.

2023-01-17 02:53 UTC, rstam requested changes
Small changes requested. Let me know what you think of them.

2023-01-17 02:53 UTC, rstam commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +    }
I like this approach in general, but I think it is too restrictive. I could see myself creating a smaller POCO to use for query by example calls to MoreLike, so `TDocument` and `BsonDocument` are not the only two valid choices for the like values. For example, I might declare a `PersonQBE` class that is a subset of `Person` and use that with `MoreByLike`. If I have to use `BsonDocument` I could get lots of things wrong.

While it is true that allowing arbitrary `TLike` classes could be misused, the same is already true by allowing `BsonDocument`.

Would you consider simplifying this class to:

    internal sealed class MoreLikeThisSearchDefinition<TDocument, TLike> : OperatorSearchDefinition<TDocument>
    {
        private readonly TLike[] _like;

        public MoreLikeThisSearchDefinition(IEnumerable<TLike> like)
            : base(OperatorType.MoreLikeThis)
        {
            _like = Ensure.IsNotNull(like, nameof(like)).ToArray();
        }

        private protected override BsonDocument RenderArguments(IBsonSerializer<TDocument> documentSerializer, IBsonSerializerRegistry serializerRegistry)
        {
            var likeSerializer = serializerRegistry.GetSerializer<TLike>();
            var likeArray = new BsonArray(_like.Select(e => e.ToBsonDocument(likeSerializer)));
            return new("like", likeArray);
        }
    }

2023-01-17 02:53 UTC, rstam commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            new MoreLikeThisSearchDefinition<TDocument, TDocument>(like);
Consider the more flexible:

    public SearchDefinition<TDocument> MoreLikeThis<TLike>(IEnumerable<TLike> like) =>
        new MoreLikeThisSearchDefinition<TDocument, TLike>(like);

and

    public SearchDefinition<TDocument> MoreLikeThis<TLike>(params TLike[] like) =>
        MoreLikeThis((IEnumerable<TLike>)like);

which would make the `BsonDocument` overloads unnecessary and allow them to be removed.

2023-01-17 18:43 UTC, BorisDog commented on src/MongoDB.Driver/Search/OperatorSearchDefinitions.cs
> +    }
Good point and good suggestion, done.

2023-01-17 18:43 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            new MoreLikeThisSearchDefinition<TDocument, TDocument>(like);
Done.

2023-01-17 21:09 UTC, rstam requested changes
Minor comments.

Still pending are some questions for @JamesKovacs, *specially* the one about the order of the parameters for `GeoSearch`.

2023-01-17 21:22 UTC, BorisDog commented on evergreen/run-atlas-search-test.sh
> +powershell.exe .\\build.ps1 --target TestAtlasSearch
No reason. Copied this from other Atlas tests scripts. Changed.

2023-01-17 21:22 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            new MoreLikeThisSearchDefinition<TDocument, TLike>(like);
Good point, changed.

2023-01-17 21:22 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchHighlight.cs
> +        public string Path { get; private set; }
We can use the `init` modifier (by [introducing ](https://btburnett.com/csharp/2020/12/11/csharp-9-records-and-init-only-setters-without-dotnet5.html) the internal `IsExternalInit`)

2023-01-17 21:22 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchHighlightOptions.cs
> +            this(new ExpressionFieldDefinition<TDocument>(path), maxCharsToExamine, maxNumPassages)
Done.

2023-01-17 21:22 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Search/AtlasSearchTests.cs
> +            new(new(new(new GeoJson2DGeographicCoordinates[]
Yes, this is more readable :) !
The idea is to skip the multi-line boilerplate code, which does not provide any useful into for regular tests maintenance. The only important bit of information are the coordinates themselves.
This way the whole tests class is simpler and more readable.

In the rare case the geo object needs to be edited, it's can be easily done with VS intellisense. Seems that mouse hovering or pressing F12 is a reasonable price to pay.

2023-01-17 22:01 UTC, JamesKovacs commented on src/MongoDB.Driver/Search/SearchDefinitionBuilder.cs
> +            GeoShapeRelation relation,
I’m in favour of the `path, relation, geometry` suggestion as the `relation` acts like an operator.

```{
  field1: {$in: [ 1, 2, 3 ]},
  field2: {$gt: 42}
}```

`path` is `fieldX`. `relation` is the operator. `geometry` is equivalent to the operator argument. The following is an imagining of `path, geometry, relation` for `$in` and `$gt`.

```{
  field1: {arg: [ 1, 2, 3 ], op: "in"},
  field2: {arg: 42, op: "gt"}
}```

So I would argue that `path, relation, geometry` makes more sense syntactically.

2023-01-17 22:32 UTC, JamesKovacs commented on src/MongoDB.Driver/Search/SearchMetaResult.cs
> +    public sealed class SearchMetaCountResult
See my previous comment on `init`. If users can instantiate instances with init-only properties and adding `IsExternalInit` doesn't cause compat problems (I don't think it does), then I'm good going down this path.

2023-01-17 23:09 UTC, JamesKovacs requested changes
See my previous inline comments. To summarize:
1. `GeoShape` param order should be `path, relation, geometry`.
2. Using `init` for `SearchHighlight` and related classes sounds like a good solution as long as users of our driver can instantiate instances of those classes.

2023-01-17 23:11 UTC, rstam commented
If using `init` on older TFs poses a risk we can just use `public` and be safe.

Sure we'd rather the class be immutable, but if the user mutates it, it can't hurt us.

2023-01-17 23:58 UTC, JamesKovacs commented
Summary of my `init` investigations. TL;DR: We can't use `init`.

The `init` magic is done by the compiler. You can use it on earlier TFMs using the `IsExternalInit` trick however you must use a compiler compatible with `init`. And this is where we run into problems...

I defined a library `Lib` with an `init` property. TFM is `netstandard2.0` and `LangVersion` is 9.0. I then created a console app `App` and referenced `Lib`. App is `netcoreapp3.1` with `LangVersion` 8.0. I instantiated an instance of the init-only containing class from `Lib`. When I compiled, I got the following error:

```
error CS8400: Feature 'init-only setters' is not available in C# 8.0. Please use language version 9.0 or greater.
```

If you change the `LangVersion` of App to 9.0, then everything works. The problem is that if we use `init` in our driver we will require our users to upgrade their toolchain to C# 9 or later. If they’re still using `netcoreapp3.1` or earlier, they might not be able to upgrade their toolchain.

The safest option is to make the setters public on `SearchHighlight` and related so that users can instantiate their own instances for testing purposes.

2023-01-18 02:00 UTC, BorisDog commented on src/MongoDB.Driver/Search/SearchHighlight.cs
> +        public SearchHighlight(string path, double score, SearchHighlightText[] texts)
Adopted the ctors approach. Thanks @rstam for making this work.

2023-01-18 23:15 UTC, JamesKovacs approved these changes
LGTM

2023-01-19 16:06 UTC, merged