CSHARP-4255: Fix bug and some tests.
mongodb/mongo-csharp-driver pull request #993
Opened 2022-12-15 19:00 UTC by DmitryLukyanov

2022-12-15 19:09 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +        public void CreateEncryptedCollection(IMongoDatabase database, string collectionName, CreateCollectionOptions createCollectionOptions, string kmsProvider, DataKeyOptions dataKeyOptions, Cance
spec API is described [here](https://github.com/mongodb/specifications/commit/02c6e3fa7dbc3a64e5312ef820e0f1779069cadb#diff-de01d398114f63480af23798e09ffca599aa758efd04f15a9beec89b4566041bR939)

2023-01-13 00:30 UTC, DmitryLukyanov commented on tests/MongoDB.Bson.TestHelpers/BsonValueEquivalencyComparer.cs
> +        public static bool Compare(BsonValue a, BsonValue b, Action<BsonValue, BsonValue> massageAction = null)
`massageAction` - we use such naming in other places in the driver

2023-01-16 19:58 UTC, BorisDog requested changes

2023-01-16 19:58 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/MongoEncryptionCreateCollectionException.cs
> +            info.AddValue("_encryptedFields", _encryptedFields);
Is `nameof` applicable here?

2023-01-16 19:58 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +                throw new MongoEncryptionCreateCollectionException(ex, encryptedFields);
Returning operation data, which is unrelated to exception, within exception is a bit unusual, but I am fine with this here.
@JamesKovacs this is follow up for our slack discussion, please double check that you are ok with this as well.

2023-01-16 19:58 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/CreateEncryptedCollectionResult.cs
> +    /// </summary>
Sealed.

2023-01-16 19:58 UTC, BorisDog commented on src/MongoDB.Driver/Encryption/MongoEncryptionCreateCollectionException.cs
> +    public class MongoEncryptionCreateCollectionException : MongoEncryptionException
sealed?

2023-01-16 19:58 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                    createCollectionOptions = new CreateCollectionOptions() { EncryptedFields = encryptedFieldsStr != null ? BsonDocument.Parse(encryptedFieldsStr) : null };
No need to recreate `CreateCollectionOptions` everywhere now.

2023-01-16 19:58 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                    effectiveEncryptedFields = await subject.CreateEncryptedCollectionAsync(database, collectionName, createCollectionOptions, kmsProvider, dataKeyOptions);
`createCollectionResult` instead of `effectiveEncryptedFields`?

2023-01-16 20:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                    createCollectionOptions = new CreateCollectionOptions() { EncryptedFields = encryptedFieldsStr != null ? BsonDocument.Parse(encryptedFieldsStr) : null };
done

2023-01-16 20:16 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                    effectiveEncryptedFields = await subject.CreateEncryptedCollectionAsync(database, collectionName, createCollectionOptions, kmsProvider, dataKeyOptions);
done

2023-01-16 20:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/MongoEncryptionCreateCollectionException.cs
> +            info.AddValue("_encryptedFields", _encryptedFields);
done

2023-01-16 20:16 UTC, DmitryLukyanov commented on src/MongoDB.Driver/Encryption/CreateEncryptedCollectionResult.cs
> +    /// </summary>
done

2023-01-16 20:54 UTC, BorisDog requested changes
minor comments

2023-01-16 20:54 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                createCollectionOptions = new CreateCollectionOptions() { EncryptedFields = BsonDocument.Parse(encryptedFieldsStr) };
No need to recreate `createCollectionOptions`.

2023-01-16 20:54 UTC, BorisDog commented on src/MongoDB.Driver/CreateCollectionOptions.cs
> +            var clone = new CreateCollectionOptions<TDocument>();
nit: you could use initialization syntax.
var = new CreateCollectionOptions<TDocument>() { x= y ... }

2023-01-16 21:03 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Encryption/ClientEncryptionTests.cs
> +                createCollectionOptions = new CreateCollectionOptions() { EncryptedFields = BsonDocument.Parse(encryptedFieldsStr) };
missed, done

2023-01-16 21:04 UTC, DmitryLukyanov commented on src/MongoDB.Driver/CreateCollectionOptions.cs
> +            var clone = new CreateCollectionOptions<TDocument>();
done

2023-01-16 21:11 UTC, BorisDog approved these changes
LGTM.

2023-01-16 22:13 UTC, JamesKovacs commented on src/MongoDB.Driver/Encryption/ClientEncryption.cs
> +                throw new MongoEncryptionCreateCollectionException(ex, encryptedFields);
Discussed with Dima via Slack. While from an API perspective it feels odd to return successfully-created keys in the exception, I don't see another reasonable way to avoid phantom encryption keys. While we could modify `CreateCollectionOptions` as we generate dataKeys, it violates the principle of least surprise to modify one's input parameters unexpectedly. I think this is the best option given the available trade-offs.

2023-01-17 00:07 UTC, merged