CSHARP-4227: Convert SDAM integration spec tests to the unified test format.
mongodb/mongo-csharp-driver pull request #996
Opened 2022-12-20 23:03 UTC by DmitryLukyanov

2022-12-20 23:27 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/ConnectionPools/ExclusiveConnectionPool.cs
> +            ConnectionHolder.TrackInUseConnection(pooledConnection);
start tracking connection before ConnectionCreated event is emitted

2022-12-20 23:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/FailPoint.cs
> +        private const string ApplicationNameTestableSuffix = "_async_";
all changes here are needed to limit failpoint related logic only to this class and avoid configuring an async workaround in different driver parts

2022-12-20 23:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.TestHelpers/FailPoint.cs
> +        private const string ApplicationNameTestableSuffix = "_async_";
We might consider this work https://jira.mongodb.org/browse/CSHARP-4460 later too

2022-12-20 23:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertEventCountOperation.cs
> +            var becauseMessage = $"{_event.ToString().Replace("{", "#").Replace("}", "#").Replace(@$"""", "'")} must be triggered exactly {_count} times";
unfortunately xunit `because`  logic fails if I just print `_event`

2023-01-24 20:33 UTC, BorisDog requested changes

2023-01-24 20:33 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForThreadOperation.cs
> +            _thread.GetAwaiter().GetResult();
The thread wait operation has it's own timeout (10 sec). I think it should stay separate from any other timeout (i.e. parameterized).
Moving to proper task awaiting or threads would allow us to support this requirement, and having more correct code as a bonus.

2023-01-24 20:33 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForPrimaryChangeOperation.cs
> +            SpinWait.SpinUntil(() => IsTopologyChanged(_client, _priorClusterDescription), _timeout).Should().BeTrue($"because cluster topology should be changed during {_timeout}, but it wasn't");
minor: consider changing `IsTopologyChanged` to `void IsTopologyChanged()` and eliminating unnessary lambda.

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForPrimaryChangeOperation.cs
> +            SpinWait.SpinUntil(() => IsTopologyChanged(_client, _priorClusterDescription), _timeout).Should().BeTrue($"because cluster topology should be changed during {_timeout}, but it wasn't");
If I understand what you suggest correctly, I think the current approach is more natural, we're waiting until some boolean flag will be true and calculating this flag is placed in a method.

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        public static string EnsureCorrectBecauseFormatting(string becausePart) => becausePart.Replace("{", "{{").Replace("}", "}}");
done

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +            _ms = Ensure.HasValue(ms, nameof(ms)).Value;
done

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForThreadOperation.cs
> +        private readonly Task _thread;
because tasks provides cool features to wait something like our events via TaskCompletionSource. Yes maybe it can be written differently, but I doubt the final code will look better that the current one

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForThreadOperation.cs
> +            _thread.GetAwaiter().GetResult();
I don't really understand what you mean, let's discuss it when we will sync about other questions

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly ConcurrentDictionary<string, Task> _threads;
I need to recall details, but the idea is to have protected access to the thread at any moment

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .Where(e => __eventsMapWithSpec.Values.Where(v => v.GetMappedDriverEvent(e) != null).Should().ContainSingle("because mapping for driver side events should be unique.").Which.EventSetT
I think it will be hard to do, we need a particular event to call `GetMappedDriverEvent` and the result of this delegate should be single.

2023-02-03 01:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +            }
I will think about it

2023-02-08 20:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +    public interface IEventsMassage
done

2023-02-08 20:24 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        internal class UnifiedEntityMapCreator
done

2023-02-08 20:25 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRecordTopologyDescriptionOperation.cs
> +    public class UnifiedRecordTopologyDescriptionOperation : IUnifiedSpecialTestOperation
done

2023-02-08 20:25 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRecordTopologyDescriptionOperation.cs
> +    public class UnifiedRecordTopologyDescriptionOperationBuilder
done

2023-02-08 20:26 UTC, DmitryLukyanov commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// Needs to workaround issues with inner string.Format logic inside FluentAssertions  and '{' / '}' in the original message.
done

2023-02-08 20:26 UTC, DmitryLukyanov commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// <param name="becausePart">The original because message.</param>
done

2023-02-08 20:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForThreadOperation.cs
> +    public class UnifiedWaitForThreadOperation : IUnifiedSpecialTestOperation
done

2023-02-08 20:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForThreadOperation.cs
> +    public class UnifiedWaitForThreadOperationBuilder
sealed

2023-02-08 20:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +    public class UnifiedWaitOperation : IUnifiedEntityTestOperation
done

2023-02-08 20:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
done

2023-02-08 20:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +    public class UnifiedWaitOperationBuilder
done

2023-02-08 20:51 UTC, DmitryLukyanov commented on specifications/server-discovery-and-monitoring/tests/unified/auth-error.json
> +  "description": "auth-error",
I've asked Patrick to confirm it, but I think you're right. Done

2023-02-22 20:00 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +        {
I see, I think the current approach is that:
1. Topology/runtime dependent tests are skipped in runtime
2. All the rest skipped in discovery

Seems like in this case, tests will be skipped for all patches, until the related tickets are resolved. So I think this is a classic case where tests should be skipped in discovery. Also a bit more efficient of course.

2023-02-22 20:00 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringIntegrationTestRunner.cs
> +    [Trait("Category", "SDAM")]
Yes, I meant that `ServerDiscoveryAndMonitoringIntegrationTestRunner` is not needed anymore. You removed it.

2023-02-22 20:04 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +            }
done

2023-02-23 02:42 UTC, BorisDog requested changes
Partial review, mainly minor comments.

2023-02-23 15:02 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringIntegrationTestRunner.cs
> +    [Trait("Category", "SDAM")]
Ah, I misunderstood it :)

2023-02-23 15:03 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +            { "commandStartedEvent", ((e) => e as CommandStartedEvent?,  EventSetType.Command) },
done

2023-02-23 15:03 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        public ConcurrentDictionary<string, Task> Threads
moved to a diff ticket

2023-02-23 15:06 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertEventCountOperation.cs
> +    public class UnifiedAssertEventCountOperation : IUnifiedSpecialTestOperation
done

2023-02-23 15:07 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertEventCountOperation.cs
> +    public class UnifiedAssertEventCountOperationBuilder
done

2023-02-23 15:07 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertTopologyTypeOperation.cs
> +    public class UnifiedAssertTopologyTypeOperation : IUnifiedSpecialTestOperation
done

2023-02-23 15:08 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertTopologyTypeOperation.cs
> +    public class UnifiedAssertTopologyTypeOperationBuilder
done

2023-02-23 15:08 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedCreateEntitiesOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
done

2023-02-23 15:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRunOnThreadOperation.cs
> +    public class UnifiedRunOnThreadOperation : IUnifiedOperationWithCreateAndRunOperationCallback
done

2023-02-23 15:09 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRunOnThreadOperation.cs
> +    public class UnifiedRunOnThreadOperationBuilder
done

2023-02-23 15:10 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitForPrimaryChangeOperation.cs
> +    public class UnifiedWaitForPrimaryChangeOperation : IUnifiedSpecialTestOperation
done

2023-02-23 15:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +                    baseDictionary.Add(newItem.Key, newItem.Value);
good point, done

2023-02-23 15:22 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private class UnifiedEntityMapCreator
done

2023-02-23 15:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +            if (!Enum.TryParse<EventSetType>(eventSetType, ignoreCase: true, out var eventTypeEnum))
> with same exception.

I agree with this, but it's not the same exception. This is exception on thrown in a regular Enum.Parse: 

>System.ArgumentException: 'Requested value 'UnexistedField' was not found.'

for a case like: `Enum.Parse(typeof(Test), "UnexistedField")`. It says nothing about enum in general, about the income value, about even any context. This error can be thrown from any place in the code. But to save time, I'm ok to add this

2023-02-23 16:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +        {
done

2023-02-23 16:52 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedEntityMap.cs
> +        private readonly ConcurrentDictionary<string, Task> _threads;
I wasn't able to imagine any issue if we change it on Dictionary. So we can do it and just keep eye on this

2023-02-23 19:30 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +            }
done

2023-02-23 19:31 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +        private class EventsMassage : IEventsMassage
done

2023-02-23 22:46 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/Specifications/server-discovery-and-monitoring/ServerDiscoveryAndMonitoringUnifiedTestRunner.cs
> +                // See for details: CSHARP-4458
done

2023-02-24 00:05 UTC, BorisDog requested changes

2023-02-24 00:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +            await Task.Delay(_waitInterval);
pass `cancellationToken` to `Task.Delay`

2023-02-24 00:05 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +            Thread.Sleep(_waitInterval);
Consider `cancellationToken.WaitHandle.WaitOne(_waitInterval);`

2023-02-24 00:17 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                return newDescriptionType;
In this case we care only about `newDescription`, because it's the only field we currently support in ServerDescriptionChangedEvent. In non unified test runner, we also support `previousDescription` (maybe more not sure). So the idea is if a newly added test contains some fields for asserting that we don't support yet, then we should know about it instead of ignoring and this is why we throw exception.

2023-02-24 00:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +            Thread.Sleep(_waitInterval);
I think better to use `ThreadHelper.Sleep`. Done

2023-02-24 00:19 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +            await Task.Delay(_waitInterval);
done

2023-02-24 19:33 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .Where(e => __eventsMapWithSpec.Values.Where(v => v.GetMappedDriverEvent(e) != null).Should().ContainSingle("because mapping for driver side events should be unique.").Which.EventSetT
Done.

2023-02-24 19:35 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .OfType<IEvent>()
I think we need a ticket to replace using IEvent instead object. But it might be not too easy since this type is internal

2023-02-24 21:23 UTC, BorisDog requested changes

2023-02-24 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .Where(e => __eventsMapBySetType[eventTypeEnum].ContainsKey(e.Type))
There is not guarantee that __`eventsMapBySetType` will contain value for `eventTypeEnum`.
Not critical as the test will fail in during development phase.
But it's better to memoize `__eventsMapBySetType[eventTypeEnum]`, to skip O(N) lookups.

2023-02-24 21:23 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .ToDictionary(dk => dk.Key, dv => dv.ToDictionary(idk => idk.Type, idv => idv.SpecName));
Would not the following be sufficient?
1. skip `ToList` stage
2. skip temporary anon object creation.

```
__eventsMapBySetType = __eventsMapWithSpec
  .GroupBy(gi => gi.Value.EventSetType)
  .ToDictionary(dk => dk.Key, dv => dv.ToDictionary(idk => idk.Value.EventType, idv => idv.Key));
```

2023-02-24 21:27 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .OfType<IEvent>()
Mostly yes, but at this point, an internal from Core are visible only in core tests, not driver tests. Also, if you create a method with internal arguments, then the whole method should be internal. And internal from Core.Tests is not visible in Driver.Tests So some fun is going to happen here :)

2023-02-24 21:32 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .Where(e => __eventsMapBySetType[eventTypeEnum].ContainsKey(e.Type))
done

2023-02-24 21:34 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/Matchers/UnifiedEventMatcher.cs
> +                .ToDictionary(dk => dk.Key, dv => dv.ToDictionary(idk => idk.Type, idv => idv.SpecName));
done

2023-02-24 23:37 UTC, BorisDog requested changes

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertEventCountOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
2010

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRunOnThreadOperation.cs
> +            AssignTask(() => Execute(createAndRunOperationCallback, async: true, cancellationToken), cancellationToken);
nit: for your consideration more compact syntax:
`AssignTask(createAndRunOperationCallback, true, cancellationToken);` and 

```
private void AssignTask(Action action, bool async, CancellationToken cancellationToken)
{
  _threads[_threadKey] = TasksUtils.CreateTaskOnOwnThread(() => action(_operation, async, cancellationToken), cancellationToken);
}

```
no need for `Execute`.

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +using MongoDB.Driver.Core.Events;
sort usings.

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +        public void PostProcessEvents(List<object> events, string type);
no need for `public`?

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
not done.

2023-02-24 23:37 UTC, BorisDog commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// Needs to workaround issues with inner string.Format logic inside FluentAssertions  and '{' / '}' in the original message.
I don't see it as done.

2023-02-24 23:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedWaitOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
sounds like what I applied as `Add suggestion to batch` was lost somehow. done now

2023-02-24 23:43 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +        public void PostProcessEvents(List<object> events, string type);
done

2023-02-24 23:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedTestRunner.cs
> +using MongoDB.Driver.Core.Events;
done

2023-02-24 23:44 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedAssertEventCountOperation.cs
> +﻿/* Copyright 2020-present MongoDB Inc.
done

2023-02-24 23:46 UTC, DmitryLukyanov commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// Needs to workaround issues with inner string.Format logic inside FluentAssertions  and '{' / '}' in the original message.
done

2023-02-24 23:50 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/UnifiedTestOperations/UnifiedRunOnThreadOperation.cs
> +            AssignTask(() => Execute(createAndRunOperationCallback, async: true, cancellationToken), cancellationToken);
done

2023-02-24 23:54 UTC, BorisDog commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// <param name="becausePart">The original because message.</param>
Not done.

2023-02-24 23:56 UTC, BorisDog commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// <param name="becausePart">The original because message.</param>
Maybe just `inputString` or `stringToEscape`

2023-02-24 23:57 UTC, DmitryLukyanov commented on tests/MongoDB.TestHelpers/FluentAssertionsHelper.cs
> +        /// <param name="becausePart">The original because message.</param>
done

2023-02-25 00:00 UTC, BorisDog approved these changes
LGTM!

2023-02-25 18:20 UTC, merged